vkQuake2 doxygen: C:/entry/dev/vq2/src/ref_vk/vk_draw.c File Reference
vk_draw.c File Reference
#include "vk_local.h"
Functions
void Draw_InitLocal (void)
void Draw_Char (int x, int y, int num)
image_t * Draw_FindPic (char *name)
void Draw_GetPicSize (int *w, int *h, char *pic)
void Draw_StretchPic (int x, int y, int w, int h, char *pic)
void Draw_Pic (int x, int y, char *pic)
void Draw_TileClear (int x, int y, int w, int h, char *pic)
void Draw_Fill (int x, int y, int w, int h, int c)
void Draw_FadeScreen (void)
void Draw_StretchRaw (int x, int y, int w, int h, int cols, int rows, byte *data)
Variables
image_t * draw_chars
unsigned r_rawpalette [256]
qvktexture_t vk_rawTexture
Function Documentation
Draw_Char()
void Draw_Char (int x, int y, int num)
Definition at line 51 of file vk_draw.c.
 {
     int             row, col;
     float           frow, fcol, size;
     num &= 255;
     if ((num & 127) == 32)
         return;     // space
     if (y <= -8)
         return;         // totally off screen
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     row = num >> 4;
     col = num & 15;
     frow = row * 0.0625;
     fcol = col * 0.0625;
     size = 0.0625;
     float imgTransform[] = { (float)x / vid.width, (float)y / vid.height,
                              8.f * scale->value / vid.width, 8.f * scale->value / vid.height,
                              fcol, frow, size, size };
     QVk_DrawTexRect(imgTransform, sizeof(imgTransform), &draw_chars->vk_texture);
 }
Referenced by GetRefAPI().
Draw_FadeScreen()
void Draw_FadeScreen (void)
Definition at line 227 of file vk_draw.c.
 {
     float imgTransform[] = { 0.f, 0.f, vid.width, vid.height, 0.f, 0.f, 0.f, .8f };
     QVk_DrawColorRect(imgTransform, sizeof(imgTransform), RP_UI);
 }
Referenced by GetRefAPI().
Draw_Fill()
void Draw_Fill (int x, int y, int w, int h, int c)
Definition at line 200 of file vk_draw.c.
 {
     union
     {
         unsigned    c;
         byte        v[4];
     } color;
     if ((unsigned)c > 255)
         ri.Sys_Error(ERR_FATAL, "Draw_Fill: bad color");
     color.c = d_8to24table[c];
     float imgTransform[] = { (float)x / vid.width, (float)y / vid.height,
                              (float)w / vid.width, (float)h / vid.height,
                              color.v[0] / 255.f, color.v[1] / 255.f, color.v[2] / 255.f, 1.f };
     QVk_DrawColorRect(imgTransform, sizeof(imgTransform), RP_UI);
 }
Referenced by GetRefAPI().
Draw_FindPic()
image_t* Draw_FindPic (char * name)
Definition at line 84 of file vk_draw.c.
 {
     image_t *vk;
     char    fullname[MAX_QPATH];
     if (name[0] != '/' && name[0] != '\\')
     {
         Com_sprintf(fullname, sizeof(fullname), "pics/%s.pcx", name);
         vk = Vk_FindImage(fullname, it_pic, NULL);
     }
     else
         vk = Vk_FindImage(name + 1, it_pic, NULL);
     return vk;
 }
Referenced by Draw_GetPicSize(), Draw_Pic(), Draw_StretchPic(), Draw_TileClear(), and GetRefAPI().
Draw_GetPicSize()
void Draw_GetPicSize (int * w, int * h, char * pic)
Definition at line 105 of file vk_draw.c.
 {
     image_t *vk;
     vk = Draw_FindPic(pic);
     if (!vk)
     {
         *w = *h = -1;
         return;
     }
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     *w = vk->width * scale->value;
     *h = vk->height * scale->value;
 }
Draw_InitLocal()
void Draw_InitLocal (void)
Definition at line 33 of file vk_draw.c.
 {
     // load console characters (don't bilerp characters)
     qvksampler_t samplerType = S_NEAREST;
     draw_chars = Vk_FindImage("pics/conchars.pcx", it_pic, &samplerType);
 }
Draw_Pic()
void Draw_Pic (int x, int y, char * pic)
Definition at line 151 of file vk_draw.c.
 {
     image_t *vk;
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     vk = Draw_FindPic(pic);
     if (!vk)
     {
         ri.Con_Printf(PRINT_ALL, "Can't find pic: %s\n", pic);
         return;
     }
     Draw_StretchPic(x, y, vk->width*scale->value, vk->height*scale->value, pic);
 }
Referenced by GetRefAPI().
Draw_StretchPic()
void Draw_StretchPic (int x, int y, int w, int h, char * pic)
Definition at line 127 of file vk_draw.c.
 {
     image_t *vk;
     vk = Draw_FindPic(pic);
     if (!vk)
     {
         ri.Con_Printf(PRINT_ALL, "Can't find pic: %s\n", pic);
         return;
     }
     float imgTransform[] = { (float)x / vid.width, (float)y / vid.height,
                              (float)w / vid.width, (float)h / vid.height,
                               vk->sl,               vk->tl,
                               vk->sh - vk->sl,      vk->th - vk->tl };
     QVk_DrawTexRect(imgTransform, sizeof(imgTransform), &vk->vk_texture);
 }
Referenced by Draw_Pic().
Draw_StretchRaw()
void Draw_StretchRaw (int x, int y, int w, int h, int cols, int rows, byte * data)
Definition at line 245 of file vk_draw.c.
 {
     unsigned    image32[256 * 256];
     int         i, j, trows;
     byte        *source;
     int         frac, fracstep;
     float       hscale;
     int         row;
     float       t;
     if (rows <= 256)
     {
         hscale = 1;
         trows = rows;
     }
     else
     {
         hscale = rows / 256.0;
         trows = 256;
     }
     t = rows * hscale / 256;
     unsigned *dest;
     for (i = 0; i < trows; i++)
     {
         row = (int)(i*hscale);
         if (row > rows)
             break;
         source = data + cols * row;
         dest = &image32[i * 256];
         fracstep = cols * 0x10000 / 256;
         frac = fracstep >> 1;
         for (j = 0; j < 256; j++)
         {
             dest[j] = r_rawpalette[source[frac >> 16]];
             frac += fracstep;
         }
     }
     if (vk_rawTexture.image != VK_NULL_HANDLE)
     {
         QVk_UpdateTextureData(&vk_rawTexture, (unsigned char*)&image32, 0, 0, 256, 256);
     }
     else
     {
         QVVKTEXTURE_CLEAR(vk_rawTexture);
         QVk_CreateTexture(&vk_rawTexture, (unsigned char*)&image32, 256, 256, vk_current_sampler);
         QVk_DebugSetObjectName((uint64_t)vk_rawTexture.image, VK_OBJECT_TYPE_IMAGE, "Image: raw texture");
         QVk_DebugSetObjectName((uint64_t)vk_rawTexture.imageView, VK_OBJECT_TYPE_IMAGE_VIEW, "Image View: raw texture");
         QVk_DebugSetObjectName((uint64_t)vk_rawTexture.descriptorSet, VK_OBJECT_TYPE_DESCRIPTOR_SET, "Descriptor Set: raw texture");
         QVk_DebugSetObjectName((uint64_t)vk_rawTexture.allocInfo.deviceMemory, VK_OBJECT_TYPE_DEVICE_MEMORY, "Memory: raw texture");
     }
     float imgTransform[] = { (float)x / vid.width, (float)y / vid.height,
                              (float)w / vid.width, (float)h / vid.height,
                              0.f, 0.f, 1.f, t };
     QVk_DrawTexRect(imgTransform, sizeof(imgTransform), &vk_rawTexture);
 }
Draw_TileClear()
void Draw_TileClear (int x, int y, int w, int h, char * pic)
Definition at line 174 of file vk_draw.c.
 {
     image_t *image;
     image = Draw_FindPic(pic);
     if (!image)
     {
         ri.Con_Printf(PRINT_ALL, "Can't find pic: %s\n", pic);
         return;
     }
     float imgTransform[] = { (float)x / vid.width,  (float)y / vid.height,
                              (float)w / vid.width,  (float)h / vid.height,
                              (float)x / 64.0,       (float)y / 64.0,
                              (float)w / 64.0,       (float)h / 64.0 };
     QVk_DrawTexRect(imgTransform, sizeof(imgTransform), &image->vk_texture);
 }
Referenced by GetRefAPI().
Variable Documentation
draw_chars
image_t* draw_chars
Definition at line 26 of file vk_draw.c.
Referenced by Draw_Char(), and Draw_InitLocal().
r_rawpalette
unsigned r_rawpalette[256]
Definition at line 1572 of file gl_rmain.c.
Referenced by Draw_StretchRaw(), and R_SetPalette().
vk_rawTexture
qvktexture_t vk_rawTexture
Definition at line 28 of file vk_image.c.
Referenced by Draw_StretchRaw(), Vk_ShutdownImages(), and Vk_TextureMode().