vq2 doxygen: refexport_t Struct Reference
refexport_t Struct Reference
#include <ref.h>
Public Attributes
int api_version
qboolean(* Init)(void *hinstance, void *wndproc)
void(* Shutdown)(void)
void(* BeginRegistration)(char *map)
struct model_s *(* RegisterModel)(char *name)
struct image_s *(* RegisterSkin)(char *name)
struct image_s *(* RegisterPic)(char *name)
void(* SetSky)(char *name, float rotate, vec3_t axis)
void(* EndRegistration)(void)
void(* RenderFrame)(refdef_t *fd)
void(* DrawGetPicSize)(int *w, int *h, char *name)
void(* DrawPic)(int x, int y, char *name)
void(* DrawStretchPic)(int x, int y, int w, int h, char *name)
void(* DrawChar)(int x, int y, int c)
void(* DrawTileClear)(int x, int y, int w, int h, char *name)
void(* DrawFill)(int x, int y, int w, int h, int c)
void(* DrawFadeScreen)(void)
void(* DrawStretchRaw)(int x, int y, int w, int h, int cols, int rows, byte *data)
void(* CinematicSetPalette)(const unsigned char *palette)
void(* BeginFrame)(float camera_separation)
void(* EndFrame)(void)
void(* EndWorldRenderpass)(void)
void(* AppActivate)(qboolean activate)
Detailed Description
Definition at line 133 of file ref.h.
Member Data Documentation
api_version
int refexport_t::api_version
Definition at line 136 of file ref.h.
Referenced by GetRefAPI(), and VID_LoadRefresh().
AppActivate
void(* refexport_t::AppActivate) (qboolean activate)
Definition at line 185 of file ref.h.
Referenced by GetRefAPI(), and MainWndProc().
BeginFrame
void(* refexport_t::BeginFrame) (float camera_separation)
Definition at line 181 of file ref.h.
Referenced by GetRefAPI(), SCR_TimeRefresh_f(), and SCR_UpdateScreen().
BeginRegistration
void(* refexport_t::BeginRegistration) (char *map)
Definition at line 157 of file ref.h.
Referenced by CL_PrepRefresh(), and GetRefAPI().
CinematicSetPalette
void(* refexport_t::CinematicSetPalette) (const unsigned char *palette)
Definition at line 180 of file ref.h.
Referenced by CL_Disconnect(), GetRefAPI(), SCR_DrawCinematic(), SCR_StopCinematic(), and SCR_UpdateScreen().
DrawChar
void(* refexport_t::DrawChar) (int x, int y, int c)
Definition at line 169 of file ref.h.
Referenced by CL_DrawInventory(), Con_DrawConsole(), Con_DrawInput(), Con_DrawNotify(), DrawAltString(), DrawHUDString(), DrawString(), GetRefAPI(), Inv_DrawString(), KeyCursorDrawFunc(), M_Credits_MenuDraw(), M_DrawCharacter(), and SCR_DrawCenterString().
DrawFadeScreen
void(* refexport_t::DrawFadeScreen) (void)
Definition at line 172 of file ref.h.
Referenced by GetRefAPI(), and M_Draw().
DrawFill
void(* refexport_t::DrawFill) (int x, int y, int w, int h, int c)
Definition at line 171 of file ref.h.
Referenced by GetRefAPI(), M_Draw(), SCR_DrawConsole(), and SCR_DrawDebugGraph().
DrawGetPicSize
void(* refexport_t::DrawGetPicSize) (int *w, int *h, char *name)
Definition at line 166 of file ref.h.
Referenced by GetRefAPI(), M_Banner(), M_Main_Draw(), M_Quit_Draw(), SCR_DrawLoading(), SCR_DrawPause(), SCR_TouchPics(), SCR_UpdateScreen(), and VID_MenuDraw().
DrawPic
void(* refexport_t::DrawPic) (int x, int y, char *name)
Definition at line 167 of file ref.h.
Referenced by CL_DrawInventory(), GetRefAPI(), M_Banner(), M_DrawCursor(), M_DrawPic(), M_Main_Draw(), M_Quit_Draw(), PlayerConfig_MenuDraw(), SCR_DrawCrosshair(), SCR_DrawField(), SCR_DrawLoading(), SCR_DrawNet(), SCR_DrawPause(), SCR_ExecuteLayoutString(), SCR_UpdateScreen(), and VID_MenuDraw().
DrawStretchPic
void(* refexport_t::DrawStretchPic) (int x, int y, int w, int h, char *name)
Definition at line 168 of file ref.h.
Referenced by Con_DrawConsole(), and GetRefAPI().
DrawStretchRaw
void(* refexport_t::DrawStretchRaw) (int x, int y, int w, int h, int cols, int rows, byte *data)
Definition at line 175 of file ref.h.
Referenced by GetRefAPI(), and SCR_DrawCinematic().
DrawTileClear
void(* refexport_t::DrawTileClear) (int x, int y, int w, int h, char *name)
Definition at line 170 of file ref.h.
Referenced by GetRefAPI(), and SCR_TileClear().
EndFrame
void(* refexport_t::EndFrame) (void)
Definition at line 182 of file ref.h.
Referenced by GetRefAPI(), SCR_TimeRefresh_f(), and SCR_UpdateScreen().
EndRegistration
void(* refexport_t::EndRegistration) (void)
Definition at line 162 of file ref.h.
Referenced by CL_PrepRefresh(), and GetRefAPI().
EndWorldRenderpass
void(* refexport_t::EndWorldRenderpass) (void)
Definition at line 183 of file ref.h.
Referenced by GetRefAPI(), SCR_UpdateScreen(), and V_RenderView().
Init
qboolean(* refexport_t::Init) (void *hinstance, void *wndproc)
Definition at line 139 of file ref.h.
Referenced by GetRefAPI(), and VID_LoadRefresh().
RegisterModel
struct model_s*(* refexport_t::RegisterModel) (char *name)
Definition at line 158 of file ref.h.
Referenced by CL_AddPacketEntities(), CL_LoadClientinfo(), CL_ParseConfigString(), CL_PrepRefresh(), CL_RegisterTEntModels(), GetRefAPI(), PlayerConfig_MenuDraw(), S_RegisterSexedModel(), and V_Gun_Model_f().
RegisterPic
struct image_s*(* refexport_t::RegisterPic) (char *name)
Definition at line 160 of file ref.h.
Referenced by CL_LoadClientinfo(), CL_ParseConfigString(), CL_PrepRefresh(), CL_RegisterTEntModels(), GetRefAPI(), M_DrawCursor(), and SCR_TouchPics().
RegisterSkin
struct image_s*(* refexport_t::RegisterSkin) (char *name)
Definition at line 159 of file ref.h.
Referenced by CL_AddPacketEntities(), CL_LoadClientinfo(), GetRefAPI(), and PlayerConfig_MenuDraw().
RenderFrame
void(* refexport_t::RenderFrame) (refdef_t *fd)
Definition at line 164 of file ref.h.
Referenced by GetRefAPI(), PlayerConfig_MenuDraw(), SCR_TimeRefresh_f(), and V_RenderView().
SetSky
void(* refexport_t::SetSky) (char *name, float rotate, vec3_t axis)
Definition at line 161 of file ref.h.
Referenced by CL_PrepRefresh(), GetRefAPI(), and SCR_Sky_f().
Shutdown
void(* refexport_t::Shutdown) (void)
Definition at line 142 of file ref.h.
Referenced by GetRefAPI(), VID_LoadRefresh(), and VID_Shutdown().
The documentation for this struct was generated from the following file:
C:/entry/syn/github/vq2/client/ref.h