vq2 doxygen: C:/entry/syn/github/vq2/game/q_shared.h File Reference
q_shared.h File Reference
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
Classes
struct cvar_s
struct cplane_s
struct cmodel_s
struct csurface_s
struct mapsurface_s
struct trace_t
struct pmove_state_t
struct usercmd_s
struct pmove_t
struct entity_state_s
struct player_state_t
Macros
#define id386 0
#define idaxp 0
#define NULL ((void *)0)
#define PITCH 0
#define YAW 1
#define ROLL 2
#define MAX_STRING_CHARS 1024
#define MAX_STRING_TOKENS 80
#define MAX_TOKEN_CHARS 128
#define MAX_QPATH 64
#define MAX_OSPATH 256
#define MAX_CLIENTS 256
#define MAX_EDICTS 1024
#define MAX_LIGHTSTYLES 256
#define MAX_MODELS 256
#define MAX_SOUNDS 256
#define MAX_IMAGES 256
#define MAX_ITEMS 256
#define MAX_GENERAL (MAX_CLIENTS*2)
#define PRINT_LOW 0
#define PRINT_MEDIUM 1
#define PRINT_HIGH 2
#define PRINT_CHAT 3
#define ERR_FATAL 0
#define ERR_DROP 1
#define ERR_DISCONNECT 2
#define PRINT_ALL 0
#define PRINT_DEVELOPER 1
#define PRINT_ALERT 2
#define M_PI 3.14159265358979323846
#define nanmask (255<<23)
#define IS_NAN(x) (((*(int *)&x)&nanmask)==nanmask)
#define DotProduct(x, y) (x[0]*y[0]+x[1]*y[1]+x[2]*y[2])
#define VectorSubtract(a, b, c) (c[0]=a[0]-b[0],c[1]=a[1]-b[1],c[2]=a[2]-b[2])
#define VectorAdd(a, b, c) (c[0]=a[0]+b[0],c[1]=a[1]+b[1],c[2]=a[2]+b[2])
#define VectorCopy(a, b) (b[0]=a[0],b[1]=a[1],b[2]=a[2])
#define VectorClear(a) (a[0]=a[1]=a[2]=0)
#define VectorNegate(a, b) (b[0]=-a[0],b[1]=-a[1],b[2]=-a[2])
#define VectorSet(v, x, y, z) (v[0]=(x), v[1]=(y), v[2]=(z))
#define BOX_ON_PLANE_SIDE(emins, emaxs, p)
#define MAX_INFO_KEY 64
#define MAX_INFO_VALUE 64
#define MAX_INFO_STRING 512
#define SFF_ARCH 0x01
#define SFF_HIDDEN 0x02
#define SFF_RDONLY 0x04
#define SFF_SUBDIR 0x08
#define SFF_SYSTEM 0x10
#define CVAR
#define CVAR_ARCHIVE 1
#define CVAR_USERINFO 2
#define CVAR_SERVERINFO 4
#define CVAR_NOSET 8
#define CVAR_LATCH 16
#define CONTENTS_SOLID 1
#define CONTENTS_WINDOW 2
#define CONTENTS_AUX 4
#define CONTENTS_LAVA 8
#define CONTENTS_SLIME 16
#define CONTENTS_WATER 32
#define CONTENTS_MIST 64
#define LAST_VISIBLE_CONTENTS 64
#define CONTENTS_AREAPORTAL 0x8000
#define CONTENTS_PLAYERCLIP 0x10000
#define CONTENTS_MONSTERCLIP 0x20000
#define CONTENTS_CURRENT_0 0x40000
#define CONTENTS_CURRENT_90 0x80000
#define CONTENTS_CURRENT_180 0x100000
#define CONTENTS_CURRENT_270 0x200000
#define CONTENTS_CURRENT_UP 0x400000
#define CONTENTS_CURRENT_DOWN 0x800000
#define CONTENTS_ORIGIN 0x1000000
#define CONTENTS_MONSTER 0x2000000
#define CONTENTS_DEADMONSTER 0x4000000
#define CONTENTS_DETAIL 0x8000000
#define CONTENTS_TRANSLUCENT 0x10000000
#define CONTENTS_LADDER 0x20000000
#define SURF_LIGHT 0x1
#define SURF_SLICK 0x2
#define SURF_SKY 0x4
#define SURF_WARP 0x8
#define SURF_TRANS33 0x10
#define SURF_TRANS66 0x20
#define SURF_FLOWING 0x40
#define SURF_NODRAW 0x80
#define MASK_ALL (-1)
#define MASK_SOLID (CONTENTS_SOLID|CONTENTS_WINDOW)
#define MASK_PLAYERSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_WINDOW|CONTENTS_MONSTER)
#define MASK_DEADSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_WINDOW)
#define MASK_MONSTERSOLID (CONTENTS_SOLID|CONTENTS_MONSTERCLIP|CONTENTS_WINDOW|CONTENTS_MONSTER)
#define MASK_WATER (CONTENTS_WATER|CONTENTS_LAVA|CONTENTS_SLIME)
#define MASK_OPAQUE (CONTENTS_SOLID|CONTENTS_SLIME|CONTENTS_LAVA)
#define MASK_SHOT (CONTENTS_SOLID|CONTENTS_MONSTER|CONTENTS_WINDOW|CONTENTS_DEADMONSTER)
#define MASK_CURRENT (CONTENTS_CURRENT_0|CONTENTS_CURRENT_90|CONTENTS_CURRENT_180|CONTENTS_CURRENT_270|CONTENTS_CURRENT_UP|CONTENTS_CURRENT_DOWN)
#define AREA_SOLID 1
#define AREA_TRIGGERS 2
#define CPLANE_NORMAL_X 0
#define CPLANE_NORMAL_Y 4
#define CPLANE_NORMAL_Z 8
#define CPLANE_DIST 12
#define CPLANE_TYPE 16
#define CPLANE_SIGNBITS 17
#define CPLANE_PAD0 18
#define CPLANE_PAD1 19
#define PMF_DUCKED 1
#define PMF_JUMP_HELD 2
#define PMF_ON_GROUND 4
#define PMF_TIME_WATERJUMP 8
#define PMF_TIME_LAND 16
#define PMF_TIME_TELEPORT 32
#define PMF_NO_PREDICTION 64
#define BUTTON_ATTACK 1
#define BUTTON_USE 2
#define BUTTON_ANY 128
#define MAXTOUCH 32
#define EF_ROTATE 0x00000001
#define EF_GIB 0x00000002
#define EF_BLASTER 0x00000008
#define EF_ROCKET 0x00000010
#define EF_GRENADE 0x00000020
#define EF_HYPERBLASTER 0x00000040
#define EF_BFG 0x00000080
#define EF_COLOR_SHELL 0x00000100
#define EF_POWERSCREEN 0x00000200
#define EF_ANIM01 0x00000400
#define EF_ANIM23 0x00000800
#define EF_ANIM_ALL 0x00001000
#define EF_ANIM_ALLFAST 0x00002000
#define EF_FLIES 0x00004000
#define EF_QUAD 0x00008000
#define EF_PENT 0x00010000
#define EF_TELEPORTER 0x00020000
#define EF_FLAG1 0x00040000
#define EF_FLAG2 0x00080000
#define EF_IONRIPPER 0x00100000
#define EF_GREENGIB 0x00200000
#define EF_BLUEHYPERBLASTER 0x00400000
#define EF_SPINNINGLIGHTS 0x00800000
#define EF_PLASMA 0x01000000
#define EF_TRAP 0x02000000
#define EF_TRACKER 0x04000000
#define EF_DOUBLE 0x08000000
#define EF_SPHERETRANS 0x10000000
#define EF_TAGTRAIL 0x20000000
#define EF_HALF_DAMAGE 0x40000000
#define EF_TRACKERTRAIL 0x80000000
#define RF_MINLIGHT 1
#define RF_VIEWERMODEL 2
#define RF_WEAPONMODEL 4
#define RF_FULLBRIGHT 8
#define RF_DEPTHHACK 16
#define RF_TRANSLUCENT 32
#define RF_FRAMELERP 64
#define RF_BEAM 128
#define RF_CUSTOMSKIN 256
#define RF_GLOW 512
#define RF_SHELL_RED 1024
#define RF_SHELL_GREEN 2048
#define RF_SHELL_BLUE 4096
#define RF_IR_VISIBLE 0x00008000
#define RF_SHELL_DOUBLE 0x00010000
#define RF_SHELL_HALF_DAM 0x00020000
#define RF_USE_DISGUISE 0x00040000
#define RDF_UNDERWATER 1
#define RDF_NOWORLDMODEL 2
#define RDF_IRGOGGLES 4
#define RDF_UVGOGGLES 8
#define MZ_BLASTER 0
#define MZ_MACHINEGUN 1
#define MZ_SHOTGUN 2
#define MZ_CHAINGUN1 3
#define MZ_CHAINGUN2 4
#define MZ_CHAINGUN3 5
#define MZ_RAILGUN 6
#define MZ_ROCKET 7
#define MZ_GRENADE 8
#define MZ_LOGIN 9
#define MZ_LOGOUT 10
#define MZ_RESPAWN 11
#define MZ_BFG 12
#define MZ_SSHOTGUN 13
#define MZ_HYPERBLASTER 14
#define MZ_ITEMRESPAWN 15
#define MZ_IONRIPPER 16
#define MZ_BLUEHYPERBLASTER 17
#define MZ_PHALANX 18
#define MZ_SILENCED 128
#define MZ_ETF_RIFLE 30
#define MZ_UNUSED 31
#define MZ_SHOTGUN2 32
#define MZ_HEATBEAM 33
#define MZ_BLASTER2 34
#define MZ_TRACKER 35
#define MZ_NUKE1 36
#define MZ_NUKE2 37
#define MZ_NUKE4 38
#define MZ_NUKE8 39
#define MZ2_TANK_BLASTER_1 1
#define MZ2_TANK_BLASTER_2 2
#define MZ2_TANK_BLASTER_3 3
#define MZ2_TANK_MACHINEGUN_1 4
#define MZ2_TANK_MACHINEGUN_2 5
#define MZ2_TANK_MACHINEGUN_3 6
#define MZ2_TANK_MACHINEGUN_4 7
#define MZ2_TANK_MACHINEGUN_5 8
#define MZ2_TANK_MACHINEGUN_6 9
#define MZ2_TANK_MACHINEGUN_7 10
#define MZ2_TANK_MACHINEGUN_8 11
#define MZ2_TANK_MACHINEGUN_9 12
#define MZ2_TANK_MACHINEGUN_10 13
#define MZ2_TANK_MACHINEGUN_11 14
#define MZ2_TANK_MACHINEGUN_12 15
#define MZ2_TANK_MACHINEGUN_13 16
#define MZ2_TANK_MACHINEGUN_14 17
#define MZ2_TANK_MACHINEGUN_15 18
#define MZ2_TANK_MACHINEGUN_16 19
#define MZ2_TANK_MACHINEGUN_17 20
#define MZ2_TANK_MACHINEGUN_18 21
#define MZ2_TANK_MACHINEGUN_19 22
#define MZ2_TANK_ROCKET_1 23
#define MZ2_TANK_ROCKET_2 24
#define MZ2_TANK_ROCKET_3 25
#define MZ2_INFANTRY_MACHINEGUN_1 26
#define MZ2_INFANTRY_MACHINEGUN_2 27
#define MZ2_INFANTRY_MACHINEGUN_3 28
#define MZ2_INFANTRY_MACHINEGUN_4 29
#define MZ2_INFANTRY_MACHINEGUN_5 30
#define MZ2_INFANTRY_MACHINEGUN_6 31
#define MZ2_INFANTRY_MACHINEGUN_7 32
#define MZ2_INFANTRY_MACHINEGUN_8 33
#define MZ2_INFANTRY_MACHINEGUN_9 34
#define MZ2_INFANTRY_MACHINEGUN_10 35
#define MZ2_INFANTRY_MACHINEGUN_11 36
#define MZ2_INFANTRY_MACHINEGUN_12 37
#define MZ2_INFANTRY_MACHINEGUN_13 38
#define MZ2_SOLDIER_BLASTER_1 39
#define MZ2_SOLDIER_BLASTER_2 40
#define MZ2_SOLDIER_SHOTGUN_1 41
#define MZ2_SOLDIER_SHOTGUN_2 42
#define MZ2_SOLDIER_MACHINEGUN_1 43
#define MZ2_SOLDIER_MACHINEGUN_2 44
#define MZ2_GUNNER_MACHINEGUN_1 45
#define MZ2_GUNNER_MACHINEGUN_2 46
#define MZ2_GUNNER_MACHINEGUN_3 47
#define MZ2_GUNNER_MACHINEGUN_4 48
#define MZ2_GUNNER_MACHINEGUN_5 49
#define MZ2_GUNNER_MACHINEGUN_6 50
#define MZ2_GUNNER_MACHINEGUN_7 51
#define MZ2_GUNNER_MACHINEGUN_8 52
#define MZ2_GUNNER_GRENADE_1 53
#define MZ2_GUNNER_GRENADE_2 54
#define MZ2_GUNNER_GRENADE_3 55
#define MZ2_GUNNER_GRENADE_4 56
#define MZ2_CHICK_ROCKET_1 57
#define MZ2_FLYER_BLASTER_1 58
#define MZ2_FLYER_BLASTER_2 59
#define MZ2_MEDIC_BLASTER_1 60
#define MZ2_GLADIATOR_RAILGUN_1 61
#define MZ2_HOVER_BLASTER_1 62
#define MZ2_ACTOR_MACHINEGUN_1 63
#define MZ2_SUPERTANK_MACHINEGUN_1 64
#define MZ2_SUPERTANK_MACHINEGUN_2 65
#define MZ2_SUPERTANK_MACHINEGUN_3 66
#define MZ2_SUPERTANK_MACHINEGUN_4 67
#define MZ2_SUPERTANK_MACHINEGUN_5 68
#define MZ2_SUPERTANK_MACHINEGUN_6 69
#define MZ2_SUPERTANK_ROCKET_1 70
#define MZ2_SUPERTANK_ROCKET_2 71
#define MZ2_SUPERTANK_ROCKET_3 72
#define MZ2_BOSS2_MACHINEGUN_L1 73
#define MZ2_BOSS2_MACHINEGUN_L2 74
#define MZ2_BOSS2_MACHINEGUN_L3 75
#define MZ2_BOSS2_MACHINEGUN_L4 76
#define MZ2_BOSS2_MACHINEGUN_L5 77
#define MZ2_BOSS2_ROCKET_1 78
#define MZ2_BOSS2_ROCKET_2 79
#define MZ2_BOSS2_ROCKET_3 80
#define MZ2_BOSS2_ROCKET_4 81
#define MZ2_FLOAT_BLASTER_1 82
#define MZ2_SOLDIER_BLASTER_3 83
#define MZ2_SOLDIER_SHOTGUN_3 84
#define MZ2_SOLDIER_MACHINEGUN_3 85
#define MZ2_SOLDIER_BLASTER_4 86
#define MZ2_SOLDIER_SHOTGUN_4 87
#define MZ2_SOLDIER_MACHINEGUN_4 88
#define MZ2_SOLDIER_BLASTER_5 89
#define MZ2_SOLDIER_SHOTGUN_5 90
#define MZ2_SOLDIER_MACHINEGUN_5 91
#define MZ2_SOLDIER_BLASTER_6 92
#define MZ2_SOLDIER_SHOTGUN_6 93
#define MZ2_SOLDIER_MACHINEGUN_6 94
#define MZ2_SOLDIER_BLASTER_7 95
#define MZ2_SOLDIER_SHOTGUN_7 96
#define MZ2_SOLDIER_MACHINEGUN_7 97
#define MZ2_SOLDIER_BLASTER_8 98
#define MZ2_SOLDIER_SHOTGUN_8 99
#define MZ2_SOLDIER_MACHINEGUN_8 100
#define MZ2_MAKRON_BFG 101
#define MZ2_MAKRON_BLASTER_1 102
#define MZ2_MAKRON_BLASTER_2 103
#define MZ2_MAKRON_BLASTER_3 104
#define MZ2_MAKRON_BLASTER_4 105
#define MZ2_MAKRON_BLASTER_5 106
#define MZ2_MAKRON_BLASTER_6 107
#define MZ2_MAKRON_BLASTER_7 108
#define MZ2_MAKRON_BLASTER_8 109
#define MZ2_MAKRON_BLASTER_9 110
#define MZ2_MAKRON_BLASTER_10 111
#define MZ2_MAKRON_BLASTER_11 112
#define MZ2_MAKRON_BLASTER_12 113
#define MZ2_MAKRON_BLASTER_13 114
#define MZ2_MAKRON_BLASTER_14 115
#define MZ2_MAKRON_BLASTER_15 116
#define MZ2_MAKRON_BLASTER_16 117
#define MZ2_MAKRON_BLASTER_17 118
#define MZ2_MAKRON_RAILGUN_1 119
#define MZ2_JORG_MACHINEGUN_L1 120
#define MZ2_JORG_MACHINEGUN_L2 121
#define MZ2_JORG_MACHINEGUN_L3 122
#define MZ2_JORG_MACHINEGUN_L4 123
#define MZ2_JORG_MACHINEGUN_L5 124
#define MZ2_JORG_MACHINEGUN_L6 125
#define MZ2_JORG_MACHINEGUN_R1 126
#define MZ2_JORG_MACHINEGUN_R2 127
#define MZ2_JORG_MACHINEGUN_R3 128
#define MZ2_JORG_MACHINEGUN_R4 129
#define MZ2_JORG_MACHINEGUN_R5 130
#define MZ2_JORG_MACHINEGUN_R6 131
#define MZ2_JORG_BFG_1 132
#define MZ2_BOSS2_MACHINEGUN_R1 133
#define MZ2_BOSS2_MACHINEGUN_R2 134
#define MZ2_BOSS2_MACHINEGUN_R3 135
#define MZ2_BOSS2_MACHINEGUN_R4 136
#define MZ2_BOSS2_MACHINEGUN_R5 137
#define MZ2_CARRIER_MACHINEGUN_L1 138
#define MZ2_CARRIER_MACHINEGUN_R1 139
#define MZ2_CARRIER_GRENADE 140
#define MZ2_TURRET_MACHINEGUN 141
#define MZ2_TURRET_ROCKET 142
#define MZ2_TURRET_BLASTER 143
#define MZ2_STALKER_BLASTER 144
#define MZ2_DAEDALUS_BLASTER 145
#define MZ2_MEDIC_BLASTER_2 146
#define MZ2_CARRIER_RAILGUN 147
#define MZ2_WIDOW_DISRUPTOR 148
#define MZ2_WIDOW_BLASTER 149
#define MZ2_WIDOW_RAIL 150
#define MZ2_WIDOW_PLASMABEAM 151
#define MZ2_CARRIER_MACHINEGUN_L2 152
#define MZ2_CARRIER_MACHINEGUN_R2 153
#define MZ2_WIDOW_RAIL_LEFT 154
#define MZ2_WIDOW_RAIL_RIGHT 155
#define MZ2_WIDOW_BLASTER_SWEEP1 156
#define MZ2_WIDOW_BLASTER_SWEEP2 157
#define MZ2_WIDOW_BLASTER_SWEEP3 158
#define MZ2_WIDOW_BLASTER_SWEEP4 159
#define MZ2_WIDOW_BLASTER_SWEEP5 160
#define MZ2_WIDOW_BLASTER_SWEEP6 161
#define MZ2_WIDOW_BLASTER_SWEEP7 162
#define MZ2_WIDOW_BLASTER_SWEEP8 163
#define MZ2_WIDOW_BLASTER_SWEEP9 164
#define MZ2_WIDOW_BLASTER_100 165
#define MZ2_WIDOW_BLASTER_90 166
#define MZ2_WIDOW_BLASTER_80 167
#define MZ2_WIDOW_BLASTER_70 168
#define MZ2_WIDOW_BLASTER_60 169
#define MZ2_WIDOW_BLASTER_50 170
#define MZ2_WIDOW_BLASTER_40 171
#define MZ2_WIDOW_BLASTER_30 172
#define MZ2_WIDOW_BLASTER_20 173
#define MZ2_WIDOW_BLASTER_10 174
#define MZ2_WIDOW_BLASTER_0 175
#define MZ2_WIDOW_BLASTER_10L 176
#define MZ2_WIDOW_BLASTER_20L 177
#define MZ2_WIDOW_BLASTER_30L 178
#define MZ2_WIDOW_BLASTER_40L 179
#define MZ2_WIDOW_BLASTER_50L 180
#define MZ2_WIDOW_BLASTER_60L 181
#define MZ2_WIDOW_BLASTER_70L 182
#define MZ2_WIDOW_RUN_1 183
#define MZ2_WIDOW_RUN_2 184
#define MZ2_WIDOW_RUN_3 185
#define MZ2_WIDOW_RUN_4 186
#define MZ2_WIDOW_RUN_5 187
#define MZ2_WIDOW_RUN_6 188
#define MZ2_WIDOW_RUN_7 189
#define MZ2_WIDOW_RUN_8 190
#define MZ2_CARRIER_ROCKET_1 191
#define MZ2_CARRIER_ROCKET_2 192
#define MZ2_CARRIER_ROCKET_3 193
#define MZ2_CARRIER_ROCKET_4 194
#define MZ2_WIDOW2_BEAMER_1 195
#define MZ2_WIDOW2_BEAMER_2 196
#define MZ2_WIDOW2_BEAMER_3 197
#define MZ2_WIDOW2_BEAMER_4 198
#define MZ2_WIDOW2_BEAMER_5 199
#define MZ2_WIDOW2_BEAM_SWEEP_1 200
#define MZ2_WIDOW2_BEAM_SWEEP_2 201
#define MZ2_WIDOW2_BEAM_SWEEP_3 202
#define MZ2_WIDOW2_BEAM_SWEEP_4 203
#define MZ2_WIDOW2_BEAM_SWEEP_5 204
#define MZ2_WIDOW2_BEAM_SWEEP_6 205
#define MZ2_WIDOW2_BEAM_SWEEP_7 206
#define MZ2_WIDOW2_BEAM_SWEEP_8 207
#define MZ2_WIDOW2_BEAM_SWEEP_9 208
#define MZ2_WIDOW2_BEAM_SWEEP_10 209
#define MZ2_WIDOW2_BEAM_SWEEP_11 210
#define SPLASH_UNKNOWN 0
#define SPLASH_SPARKS 1
#define SPLASH_BLUE_WATER 2
#define SPLASH_BROWN_WATER 3
#define SPLASH_SLIME 4
#define SPLASH_LAVA 5
#define SPLASH_BLOOD 6
#define CHAN_AUTO 0
#define CHAN_WEAPON 1
#define CHAN_VOICE 2
#define CHAN_ITEM 3
#define CHAN_BODY 4
#define CHAN_NO_PHS_ADD 8
#define CHAN_RELIABLE 16
#define ATTN_NONE 0
#define ATTN_NORM 1
#define ATTN_IDLE 2
#define ATTN_STATIC 3
#define STAT_HEALTH_ICON 0
#define STAT_HEALTH 1
#define STAT_AMMO_ICON 2
#define STAT_AMMO 3
#define STAT_ARMOR_ICON 4
#define STAT_ARMOR 5
#define STAT_SELECTED_ICON 6
#define STAT_PICKUP_ICON 7
#define STAT_PICKUP_STRING 8
#define STAT_TIMER_ICON 9
#define STAT_TIMER 10
#define STAT_HELPICON 11
#define STAT_SELECTED_ITEM 12
#define STAT_LAYOUTS 13
#define STAT_FRAGS 14
#define STAT_FLASHES 15
#define STAT_CHASE 16
#define STAT_SPECTATOR 17
#define MAX_STATS 32
#define DF_NO_HEALTH 0x00000001
#define DF_NO_ITEMS 0x00000002
#define DF_WEAPONS_STAY 0x00000004
#define DF_NO_FALLING 0x00000008
#define DF_INSTANT_ITEMS 0x00000010
#define DF_SAME_LEVEL 0x00000020
#define DF_SKINTEAMS 0x00000040
#define DF_MODELTEAMS 0x00000080
#define DF_NO_FRIENDLY_FIRE 0x00000100
#define DF_SPAWN_FARTHEST 0x00000200
#define DF_FORCE_RESPAWN 0x00000400
#define DF_NO_ARMOR 0x00000800
#define DF_ALLOW_EXIT 0x00001000
#define DF_INFINITE_AMMO 0x00002000
#define DF_QUAD_DROP 0x00004000
#define DF_FIXED_FOV 0x00008000
#define DF_QUADFIRE_DROP 0x00010000
#define DF_NO_MINES 0x00020000
#define DF_NO_STACK_DOUBLE 0x00040000
#define DF_NO_NUKES 0x00080000
#define DF_NO_SPHERES 0x00100000
#define ROGUE_VERSION_ID 1278
#define ROGUE_VERSION_STRING "08/21/1998 Beta 2 for Ensemble"
#define ANGLE2SHORT(x) ((int)((x)*65536/360) & 65535)
#define SHORT2ANGLE(x) ((x)*(360.0/65536))
#define CS_NAME 0
#define CS_CDTRACK 1
#define CS_SKY 2
#define CS_SKYAXIS 3
#define CS_SKYROTATE 4
#define CS_STATUSBAR 5
#define CS_AIRACCEL 29
#define CS_MAXCLIENTS 30
#define CS_MAPCHECKSUM 31
#define CS_MODELS 32
#define CS_SOUNDS (CS_MODELS+MAX_MODELS)
#define CS_IMAGES (CS_SOUNDS+MAX_SOUNDS)
#define CS_LIGHTS (CS_IMAGES+MAX_IMAGES)
#define CS_ITEMS (CS_LIGHTS+MAX_LIGHTSTYLES)
#define CS_PLAYERSKINS (CS_ITEMS+MAX_ITEMS)
#define CS_GENERAL (CS_PLAYERSKINS+MAX_CLIENTS)
#define MAX_CONFIGSTRINGS (CS_GENERAL+MAX_GENERAL)
#define VIDREF_VK 1
#define VIDREF_GL 2
#define VIDREF_SOFT 3
#define VIDREF_OTHER 4
Typedefs
typedef unsigned char byte
typedef float vec_t
typedef vec_t vec3_t[3]
typedef vec_t vec5_t[5]
typedef int fixed4_t
typedef int fixed8_t
typedef int fixed16_t
typedef struct cvar_s cvar_t
typedef struct cplane_s cplane_t
typedef struct cmodel_s cmodel_t
typedef struct csurface_s csurface_t
typedef struct mapsurface_s mapsurface_t
typedef struct usercmd_s usercmd_t
typedef struct entity_state_s entity_state_t
Enumerations
enum qboolean { false, true, false, true }
enum multicast_t {
MULTICAST_ALL, MULTICAST_PHS, MULTICAST_PVS, MULTICAST_ALL_R,
MULTICAST_PHS_R, MULTICAST_PVS_R, MULTICAST_ALL, MULTICAST_PHS,
MULTICAST_PVS, MULTICAST_ALL_R, MULTICAST_PHS_R, MULTICAST_PVS_R
}
enum pmtype_t {
PM_NORMAL, PM_SPECTATOR, PM_DEAD, PM_GIB,
PM_FREEZE, PM_NORMAL, PM_SPECTATOR, PM_DEAD,
PM_GIB, PM_FREEZE
}
enum temp_event_t {
TE_GUNSHOT, TE_BLOOD, TE_BLASTER, TE_RAILTRAIL,
TE_SHOTGUN, TE_EXPLOSION1, TE_EXPLOSION2, TE_ROCKET_EXPLOSION,
TE_GRENADE_EXPLOSION, TE_SPARKS, TE_SPLASH, TE_BUBBLETRAIL,
TE_SCREEN_SPARKS, TE_SHIELD_SPARKS, TE_BULLET_SPARKS, TE_LASER_SPARKS,
TE_PARASITE_ATTACK, TE_ROCKET_EXPLOSION_WATER, TE_GRENADE_EXPLOSION_WATER, TE_MEDIC_CABLE_ATTACK,
TE_BFG_EXPLOSION, TE_BFG_BIGEXPLOSION, TE_BOSSTPORT, TE_BFG_LASER,
TE_GRAPPLE_CABLE, TE_WELDING_SPARKS, TE_GREENBLOOD, TE_BLUEHYPERBLASTER,
TE_PLASMA_EXPLOSION, TE_TUNNEL_SPARKS, TE_BLASTER2, TE_RAILTRAIL2,
TE_FLAME, TE_LIGHTNING, TE_DEBUGTRAIL, TE_PLAIN_EXPLOSION,
TE_FLASHLIGHT, TE_FORCEWALL, TE_HEATBEAM, TE_MONSTER_HEATBEAM,
TE_STEAM, TE_BUBBLETRAIL2, TE_MOREBLOOD, TE_HEATBEAM_SPARKS,
TE_HEATBEAM_STEAM, TE_CHAINFIST_SMOKE, TE_ELECTRIC_SPARKS, TE_TRACKER_EXPLOSION,
TE_TELEPORT_EFFECT, TE_DBALL_GOAL, TE_WIDOWBEAMOUT, TE_NUKEBLAST,
TE_WIDOWSPLASH, TE_EXPLOSION1_BIG, TE_EXPLOSION1_NP, TE_FLECHETTE,
TE_GUNSHOT, TE_BLOOD, TE_BLASTER, TE_RAILTRAIL,
TE_SHOTGUN, TE_EXPLOSION1, TE_EXPLOSION2, TE_ROCKET_EXPLOSION,
TE_GRENADE_EXPLOSION, TE_SPARKS, TE_SPLASH, TE_BUBBLETRAIL,
TE_SCREEN_SPARKS, TE_SHIELD_SPARKS, TE_BULLET_SPARKS, TE_LASER_SPARKS,
TE_PARASITE_ATTACK, TE_ROCKET_EXPLOSION_WATER, TE_GRENADE_EXPLOSION_WATER, TE_MEDIC_CABLE_ATTACK,
TE_BFG_EXPLOSION, TE_BFG_BIGEXPLOSION, TE_BOSSTPORT, TE_BFG_LASER,
TE_GRAPPLE_CABLE, TE_WELDING_SPARKS, TE_GREENBLOOD, TE_BLUEHYPERBLASTER,
TE_PLASMA_EXPLOSION, TE_TUNNEL_SPARKS, TE_BLASTER2, TE_RAILTRAIL2,
TE_FLAME, TE_LIGHTNING, TE_DEBUGTRAIL, TE_PLAIN_EXPLOSION,
TE_FLASHLIGHT, TE_FORCEWALL, TE_HEATBEAM, TE_MONSTER_HEATBEAM,
TE_STEAM, TE_BUBBLETRAIL2, TE_MOREBLOOD, TE_HEATBEAM_SPARKS,
TE_HEATBEAM_STEAM, TE_CHAINFIST_SMOKE, TE_ELECTRIC_SPARKS, TE_TRACKER_EXPLOSION,
TE_TELEPORT_EFFECT, TE_DBALL_GOAL, TE_WIDOWBEAMOUT, TE_NUKEBLAST,
TE_WIDOWSPLASH, TE_EXPLOSION1_BIG, TE_EXPLOSION1_NP, TE_FLECHETTE
}
enum entity_event_t {
EV_NONE, EV_ITEM_RESPAWN, EV_FOOTSTEP, EV_FALLSHORT,
EV_FALL, EV_FALLFAR, EV_PLAYER_TELEPORT, EV_OTHER_TELEPORT,
EV_NONE, EV_ITEM_RESPAWN, EV_FOOTSTEP, EV_FALLSHORT,
EV_FALL, EV_FALLFAR, EV_PLAYER_TELEPORT, EV_OTHER_TELEPORT
}
Functions
long Q_ftol (float f)
void VectorMA (vec3_t veca, float scale, vec3_t vecb, vec3_t vecc)
vec_t _DotProduct (vec3_t v1, vec3_t v2)
void _VectorSubtract (vec3_t veca, vec3_t vecb, vec3_t out)
void _VectorAdd (vec3_t veca, vec3_t vecb, vec3_t out)
void _VectorCopy (vec3_t in, vec3_t out)
void ClearBounds (vec3_t mins, vec3_t maxs)
void AddPointToBounds (vec3_t v, vec3_t mins, vec3_t maxs)
int VectorCompare (vec3_t v1, vec3_t v2)
vec_t VectorLength (vec3_t v)
void CrossProduct (vec3_t v1, vec3_t v2, vec3_t cross)
vec_t VectorNormalize (vec3_t v)
vec_t VectorNormalize2 (vec3_t v, vec3_t out)
void VectorInverse (vec3_t v)
void VectorScale (vec3_t in, vec_t scale, vec3_t out)
int Q_log2 (int val)
void R_ConcatRotations (float in1[3][3], float in2[3][3], float out[3][3])
void R_ConcatTransforms (float in1[3][4], float in2[3][4], float out[3][4])
void AngleVectors (vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s *plane)
float anglemod (float a)
float LerpAngle (float a1, float a2, float frac)
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
void PerpendicularVector (vec3_t dst, const vec3_t src)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
char * COM_SkipPath (char *pathname)
void COM_StripExtension (char *in, char *out)
void COM_FileBase (char *in, char *out)
void COM_FilePath (char *in, char *out)
void COM_DefaultExtension (char *path, char *extension)
char * COM_Parse (char **data_p)
void Com_sprintf (char *dest, int size, char *fmt,...)
void Com_PageInMemory (byte *buffer, int size)
int Q_stricmp (char *s1, char *s2)
int Q_strcasecmp (char *s1, char *s2)
int Q_strncasecmp (char *s1, char *s2, int n)
short BigShort (short l)
short LittleShort (short l)
int BigLong (int l)
int LittleLong (int l)
float BigFloat (float l)
float LittleFloat (float l)
void Swap_Init (void)
char * va (char *format,...)
char * Info_ValueForKey (char *s, char *key)
void Info_RemoveKey (char *s, char *key)
void Info_SetValueForKey (char *s, char *key, char *value)
qboolean Info_Validate (char *s)
int Sys_Milliseconds (void)
void Sys_Mkdir (char *path)
void * Hunk_Begin (int maxsize)
void * Hunk_Alloc (int size)
void Hunk_Free (void *buf)
int Hunk_End (void)
char * Sys_FindFirst (char *path, unsigned musthave, unsigned canthave)
char * Sys_FindNext (unsigned musthave, unsigned canthave)
void Sys_FindClose (void)
void Sys_Error (char *error,...)
void Com_Printf (char *msg,...)
Variables
vec3_t vec3_origin
int curtime
vec3_t monster_flash_offset []
int vidref_val
Macro Definition Documentation
ANGLE2SHORT
#define ANGLE2SHORT (x) ((int)((x)*65536/360) & 65535)
Definition at line 1092 of file q_shared.h.
AREA_SOLID
#define AREA_SOLID 1
Definition at line 407 of file q_shared.h.
AREA_TRIGGERS
#define AREA_TRIGGERS 2
Definition at line 408 of file q_shared.h.
ATTN_IDLE
#define ATTN_IDLE 2
Definition at line 996 of file q_shared.h.
ATTN_NONE
#define ATTN_NONE 0
Definition at line 994 of file q_shared.h.
ATTN_NORM
#define ATTN_NORM 1
Definition at line 995 of file q_shared.h.
ATTN_STATIC
#define ATTN_STATIC 3
Definition at line 997 of file q_shared.h.
BOX_ON_PLANE_SIDE
#define BOX_ON_PLANE_SIDE (emins, emaxs, p)
Value:
    (((p)->type < 3)?                       \
    (                                       \
        ((p)->dist <= (emins)[(p)->type])?  \
            1                               \
        :                                   \
        (                                   \
            ((p)->dist >= (emaxs)[(p)->type])?\
                2                           \
            :                               \
                3                           \
        )                                   \
    )                                       \
    :                                       \
        BoxOnPlaneSide( (emins), (emaxs), (p)))
Definition at line 197 of file q_shared.h.
BUTTON_ANY
#define BUTTON_ANY 128
Definition at line 513 of file q_shared.h.
BUTTON_ATTACK
#define BUTTON_ATTACK 1
Definition at line 511 of file q_shared.h.
BUTTON_USE
#define BUTTON_USE 2
Definition at line 512 of file q_shared.h.
CHAN_AUTO
#define CHAN_AUTO 0
Definition at line 983 of file q_shared.h.
CHAN_BODY
#define CHAN_BODY 4
Definition at line 987 of file q_shared.h.
CHAN_ITEM
#define CHAN_ITEM 3
Definition at line 986 of file q_shared.h.
CHAN_NO_PHS_ADD
#define CHAN_NO_PHS_ADD 8
Definition at line 989 of file q_shared.h.
CHAN_RELIABLE
#define CHAN_RELIABLE 16
Definition at line 990 of file q_shared.h.
CHAN_VOICE
#define CHAN_VOICE 2
Definition at line 985 of file q_shared.h.
CHAN_WEAPON
#define CHAN_WEAPON 1
Definition at line 984 of file q_shared.h.
CONTENTS_AREAPORTAL
#define CONTENTS_AREAPORTAL 0x8000
Definition at line 357 of file q_shared.h.
CONTENTS_AUX
#define CONTENTS_AUX 4
Definition at line 348 of file q_shared.h.
CONTENTS_CURRENT_0
#define CONTENTS_CURRENT_0 0x40000
Definition at line 363 of file q_shared.h.
CONTENTS_CURRENT_180
#define CONTENTS_CURRENT_180 0x100000
Definition at line 365 of file q_shared.h.
CONTENTS_CURRENT_270
#define CONTENTS_CURRENT_270 0x200000
Definition at line 366 of file q_shared.h.
CONTENTS_CURRENT_90
#define CONTENTS_CURRENT_90 0x80000
Definition at line 364 of file q_shared.h.
CONTENTS_CURRENT_DOWN
#define CONTENTS_CURRENT_DOWN 0x800000
Definition at line 368 of file q_shared.h.
CONTENTS_CURRENT_UP
#define CONTENTS_CURRENT_UP 0x400000
Definition at line 367 of file q_shared.h.
CONTENTS_DEADMONSTER
#define CONTENTS_DEADMONSTER 0x4000000
Definition at line 373 of file q_shared.h.
CONTENTS_DETAIL
#define CONTENTS_DETAIL 0x8000000
Definition at line 374 of file q_shared.h.
CONTENTS_LADDER
#define CONTENTS_LADDER 0x20000000
Definition at line 376 of file q_shared.h.
CONTENTS_LAVA
#define CONTENTS_LAVA 8
Definition at line 349 of file q_shared.h.
CONTENTS_MIST
#define CONTENTS_MIST 64
Definition at line 352 of file q_shared.h.
CONTENTS_MONSTER
#define CONTENTS_MONSTER 0x2000000
Definition at line 372 of file q_shared.h.
CONTENTS_MONSTERCLIP
#define CONTENTS_MONSTERCLIP 0x20000
Definition at line 360 of file q_shared.h.
CONTENTS_ORIGIN
#define CONTENTS_ORIGIN 0x1000000
Definition at line 370 of file q_shared.h.
CONTENTS_PLAYERCLIP
#define CONTENTS_PLAYERCLIP 0x10000
Definition at line 359 of file q_shared.h.
CONTENTS_SLIME
#define CONTENTS_SLIME 16
Definition at line 350 of file q_shared.h.
CONTENTS_SOLID
#define CONTENTS_SOLID 1
Definition at line 346 of file q_shared.h.
CONTENTS_TRANSLUCENT
#define CONTENTS_TRANSLUCENT 0x10000000
Definition at line 375 of file q_shared.h.
CONTENTS_WATER
#define CONTENTS_WATER 32
Definition at line 351 of file q_shared.h.
CONTENTS_WINDOW
#define CONTENTS_WINDOW 2
Definition at line 347 of file q_shared.h.
CPLANE_DIST
#define CPLANE_DIST 12
Definition at line 426 of file q_shared.h.
CPLANE_NORMAL_X
#define CPLANE_NORMAL_X 0
Definition at line 423 of file q_shared.h.
CPLANE_NORMAL_Y
#define CPLANE_NORMAL_Y 4
Definition at line 424 of file q_shared.h.
CPLANE_NORMAL_Z
#define CPLANE_NORMAL_Z 8
Definition at line 425 of file q_shared.h.
CPLANE_PAD0
#define CPLANE_PAD0 18
Definition at line 429 of file q_shared.h.
CPLANE_PAD1
#define CPLANE_PAD1 19
Definition at line 430 of file q_shared.h.
CPLANE_SIGNBITS
#define CPLANE_SIGNBITS 17
Definition at line 428 of file q_shared.h.
CPLANE_TYPE
#define CPLANE_TYPE 16
Definition at line 427 of file q_shared.h.
CS_AIRACCEL
#define CS_AIRACCEL 29
Definition at line 1108 of file q_shared.h.
CS_CDTRACK
#define CS_CDTRACK 1
Definition at line 1102 of file q_shared.h.
CS_GENERAL
#define CS_GENERAL (CS_PLAYERSKINS+MAX_CLIENTS)
Definition at line 1118 of file q_shared.h.
CS_IMAGES
#define CS_IMAGES (CS_SOUNDS+MAX_SOUNDS)
Definition at line 1114 of file q_shared.h.
CS_ITEMS
#define CS_ITEMS (CS_LIGHTS+MAX_LIGHTSTYLES)
Definition at line 1116 of file q_shared.h.
CS_LIGHTS
#define CS_LIGHTS (CS_IMAGES+MAX_IMAGES)
Definition at line 1115 of file q_shared.h.
CS_MAPCHECKSUM
#define CS_MAPCHECKSUM 31
Definition at line 1110 of file q_shared.h.
CS_MAXCLIENTS
#define CS_MAXCLIENTS 30
Definition at line 1109 of file q_shared.h.
CS_MODELS
#define CS_MODELS 32
Definition at line 1112 of file q_shared.h.
CS_NAME
#define CS_NAME 0
Definition at line 1101 of file q_shared.h.
CS_PLAYERSKINS
#define CS_PLAYERSKINS (CS_ITEMS+MAX_ITEMS)
Definition at line 1117 of file q_shared.h.
CS_SKY
#define CS_SKY 2
Definition at line 1103 of file q_shared.h.
CS_SKYAXIS
#define CS_SKYAXIS 3
Definition at line 1104 of file q_shared.h.
CS_SKYROTATE
#define CS_SKYROTATE 4
Definition at line 1105 of file q_shared.h.
CS_SOUNDS
#define CS_SOUNDS (CS_MODELS+MAX_MODELS)
Definition at line 1113 of file q_shared.h.
CS_STATUSBAR
#define CS_STATUSBAR 5
Definition at line 1106 of file q_shared.h.
CVAR
#define CVAR
Definition at line 314 of file q_shared.h.
CVAR_ARCHIVE
#define CVAR_ARCHIVE 1
Definition at line 316 of file q_shared.h.
CVAR_LATCH
#define CVAR_LATCH 16
Definition at line 321 of file q_shared.h.
CVAR_NOSET
#define CVAR_NOSET 8
Definition at line 319 of file q_shared.h.
CVAR_SERVERINFO
#define CVAR_SERVERINFO 4
Definition at line 318 of file q_shared.h.
CVAR_USERINFO
#define CVAR_USERINFO 2
Definition at line 317 of file q_shared.h.
DF_ALLOW_EXIT
#define DF_ALLOW_EXIT 0x00001000
Definition at line 1036 of file q_shared.h.
DF_FIXED_FOV
#define DF_FIXED_FOV 0x00008000
Definition at line 1039 of file q_shared.h.
DF_FORCE_RESPAWN
#define DF_FORCE_RESPAWN 0x00000400
Definition at line 1034 of file q_shared.h.
DF_INFINITE_AMMO
#define DF_INFINITE_AMMO 0x00002000
Definition at line 1037 of file q_shared.h.
DF_INSTANT_ITEMS
#define DF_INSTANT_ITEMS 0x00000010
Definition at line 1028 of file q_shared.h.
DF_MODELTEAMS
#define DF_MODELTEAMS 0x00000080
Definition at line 1031 of file q_shared.h.
DF_NO_ARMOR
#define DF_NO_ARMOR 0x00000800
Definition at line 1035 of file q_shared.h.
DF_NO_FALLING
#define DF_NO_FALLING 0x00000008
Definition at line 1027 of file q_shared.h.
DF_NO_FRIENDLY_FIRE
#define DF_NO_FRIENDLY_FIRE 0x00000100
Definition at line 1032 of file q_shared.h.
DF_NO_HEALTH
#define DF_NO_HEALTH 0x00000001
Definition at line 1024 of file q_shared.h.
DF_NO_ITEMS
#define DF_NO_ITEMS 0x00000002
Definition at line 1025 of file q_shared.h.
DF_NO_MINES
#define DF_NO_MINES 0x00020000
Definition at line 1045 of file q_shared.h.
DF_NO_NUKES
#define DF_NO_NUKES 0x00080000
Definition at line 1047 of file q_shared.h.
DF_NO_SPHERES
#define DF_NO_SPHERES 0x00100000
Definition at line 1048 of file q_shared.h.
DF_NO_STACK_DOUBLE
#define DF_NO_STACK_DOUBLE 0x00040000
Definition at line 1046 of file q_shared.h.
DF_QUAD_DROP
#define DF_QUAD_DROP 0x00004000
Definition at line 1038 of file q_shared.h.
DF_QUADFIRE_DROP
#define DF_QUADFIRE_DROP 0x00010000
Definition at line 1042 of file q_shared.h.
DF_SAME_LEVEL
#define DF_SAME_LEVEL 0x00000020
Definition at line 1029 of file q_shared.h.
DF_SKINTEAMS
#define DF_SKINTEAMS 0x00000040
Definition at line 1030 of file q_shared.h.
DF_SPAWN_FARTHEST
#define DF_SPAWN_FARTHEST 0x00000200
Definition at line 1033 of file q_shared.h.
DF_WEAPONS_STAY
#define DF_WEAPONS_STAY 0x00000004
Definition at line 1026 of file q_shared.h.
DotProduct
#define DotProduct (x, y) (x[0]*y[0]+x[1]*y[1]+x[2]*y[2])
Definition at line 162 of file q_shared.h.
EF_ANIM01
#define EF_ANIM01 0x00000400
Definition at line 571 of file q_shared.h.
EF_ANIM23
#define EF_ANIM23 0x00000800
Definition at line 572 of file q_shared.h.
EF_ANIM_ALL
#define EF_ANIM_ALL 0x00001000
Definition at line 573 of file q_shared.h.
EF_ANIM_ALLFAST
#define EF_ANIM_ALLFAST 0x00002000
Definition at line 574 of file q_shared.h.
EF_BFG
#define EF_BFG 0x00000080
Definition at line 568 of file q_shared.h.
EF_BLASTER
#define EF_BLASTER 0x00000008
Definition at line 564 of file q_shared.h.
EF_BLUEHYPERBLASTER
#define EF_BLUEHYPERBLASTER 0x00400000
Definition at line 584 of file q_shared.h.
EF_COLOR_SHELL
#define EF_COLOR_SHELL 0x00000100
Definition at line 569 of file q_shared.h.
EF_DOUBLE
#define EF_DOUBLE 0x08000000
Definition at line 591 of file q_shared.h.
EF_FLAG1
#define EF_FLAG1 0x00040000
Definition at line 579 of file q_shared.h.
EF_FLAG2
#define EF_FLAG2 0x00080000
Definition at line 580 of file q_shared.h.
EF_FLIES
#define EF_FLIES 0x00004000
Definition at line 575 of file q_shared.h.
EF_GIB
#define EF_GIB 0x00000002
Definition at line 563 of file q_shared.h.
EF_GREENGIB
#define EF_GREENGIB 0x00200000
Definition at line 583 of file q_shared.h.
EF_GRENADE
#define EF_GRENADE 0x00000020
Definition at line 566 of file q_shared.h.
EF_HALF_DAMAGE
#define EF_HALF_DAMAGE 0x40000000
Definition at line 594 of file q_shared.h.
EF_HYPERBLASTER
#define EF_HYPERBLASTER 0x00000040
Definition at line 567 of file q_shared.h.
EF_IONRIPPER
#define EF_IONRIPPER 0x00100000
Definition at line 582 of file q_shared.h.
EF_PENT
#define EF_PENT 0x00010000
Definition at line 577 of file q_shared.h.
EF_PLASMA
#define EF_PLASMA 0x01000000
Definition at line 586 of file q_shared.h.
EF_POWERSCREEN
#define EF_POWERSCREEN 0x00000200
Definition at line 570 of file q_shared.h.
EF_QUAD
#define EF_QUAD 0x00008000
Definition at line 576 of file q_shared.h.
EF_ROCKET
#define EF_ROCKET 0x00000010
Definition at line 565 of file q_shared.h.
EF_ROTATE
#define EF_ROTATE 0x00000001
Definition at line 562 of file q_shared.h.
EF_SPHERETRANS
#define EF_SPHERETRANS 0x10000000
Definition at line 592 of file q_shared.h.
EF_SPINNINGLIGHTS
#define EF_SPINNINGLIGHTS 0x00800000
Definition at line 585 of file q_shared.h.
EF_TAGTRAIL
#define EF_TAGTRAIL 0x20000000
Definition at line 593 of file q_shared.h.
EF_TELEPORTER
#define EF_TELEPORTER 0x00020000
Definition at line 578 of file q_shared.h.
EF_TRACKER
#define EF_TRACKER 0x04000000
Definition at line 590 of file q_shared.h.
EF_TRACKERTRAIL
#define EF_TRACKERTRAIL 0x80000000
Definition at line 595 of file q_shared.h.
EF_TRAP
#define EF_TRAP 0x02000000
Definition at line 587 of file q_shared.h.
ERR_DISCONNECT
#define ERR_DISCONNECT 2
Definition at line 106 of file q_shared.h.
ERR_DROP
#define ERR_DROP 1
Definition at line 105 of file q_shared.h.
ERR_FATAL
#define ERR_FATAL 0
Definition at line 104 of file q_shared.h.
id386
#define id386 0
Definition at line 46 of file q_shared.h.
idaxp
#define idaxp 0
Definition at line 52 of file q_shared.h.
IS_NAN
#define IS_NAN (x) (((*(int *)&x)&nanmask)==nanmask)
Definition at line 151 of file q_shared.h.
LAST_VISIBLE_CONTENTS
#define LAST_VISIBLE_CONTENTS 64
Definition at line 353 of file q_shared.h.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 142 of file q_shared.h.
MASK_ALL
#define MASK_ALL (-1)
Definition at line 394 of file q_shared.h.
MASK_CURRENT
#define MASK_CURRENT (CONTENTS_CURRENT_0|CONTENTS_CURRENT_90|CONTENTS_CURRENT_180|CONTENTS_CURRENT_270|CONTENTS_CURRENT_UP|CONTENTS_CURRENT_DOWN)
Definition at line 402 of file q_shared.h.
MASK_DEADSOLID
#define MASK_DEADSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_WINDOW)
Definition at line 397 of file q_shared.h.
MASK_MONSTERSOLID
#define MASK_MONSTERSOLID (CONTENTS_SOLID|CONTENTS_MONSTERCLIP|CONTENTS_WINDOW|CONTENTS_MONSTER)
Definition at line 398 of file q_shared.h.
MASK_OPAQUE
#define MASK_OPAQUE (CONTENTS_SOLID|CONTENTS_SLIME|CONTENTS_LAVA)
Definition at line 400 of file q_shared.h.
MASK_PLAYERSOLID
#define MASK_PLAYERSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_WINDOW|CONTENTS_MONSTER)
Definition at line 396 of file q_shared.h.
MASK_SHOT
#define MASK_SHOT (CONTENTS_SOLID|CONTENTS_MONSTER|CONTENTS_WINDOW|CONTENTS_DEADMONSTER)
Definition at line 401 of file q_shared.h.
MASK_SOLID
#define MASK_SOLID (CONTENTS_SOLID|CONTENTS_WINDOW)
Definition at line 395 of file q_shared.h.
MASK_WATER
#define MASK_WATER (CONTENTS_WATER|CONTENTS_LAVA|CONTENTS_SLIME)
Definition at line 399 of file q_shared.h.
MAX_CLIENTS
#define MAX_CLIENTS 256
Definition at line 86 of file q_shared.h.
MAX_CONFIGSTRINGS
#define MAX_CONFIGSTRINGS (CS_GENERAL+MAX_GENERAL)
Definition at line 1119 of file q_shared.h.
MAX_EDICTS
#define MAX_EDICTS 1024
Definition at line 87 of file q_shared.h.
MAX_GENERAL
#define MAX_GENERAL (MAX_CLIENTS*2)
Definition at line 93 of file q_shared.h.
MAX_IMAGES
#define MAX_IMAGES 256
Definition at line 91 of file q_shared.h.
MAX_INFO_KEY
#define MAX_INFO_KEY 64
Definition at line 257 of file q_shared.h.
MAX_INFO_STRING
#define MAX_INFO_STRING 512
Definition at line 259 of file q_shared.h.
MAX_INFO_VALUE
#define MAX_INFO_VALUE 64
Definition at line 258 of file q_shared.h.
MAX_ITEMS
#define MAX_ITEMS 256
Definition at line 92 of file q_shared.h.
MAX_LIGHTSTYLES
#define MAX_LIGHTSTYLES 256
Definition at line 88 of file q_shared.h.
MAX_MODELS
#define MAX_MODELS 256
Definition at line 89 of file q_shared.h.
MAX_OSPATH
#define MAX_OSPATH 256
Definition at line 81 of file q_shared.h.
MAX_QPATH
#define MAX_QPATH 64
Definition at line 80 of file q_shared.h.
MAX_SOUNDS
#define MAX_SOUNDS 256
Definition at line 90 of file q_shared.h.
MAX_STATS
#define MAX_STATS 32
Definition at line 1020 of file q_shared.h.
MAX_STRING_CHARS
#define MAX_STRING_CHARS 1024
Definition at line 76 of file q_shared.h.
MAX_STRING_TOKENS
#define MAX_STRING_TOKENS 80
Definition at line 77 of file q_shared.h.
MAX_TOKEN_CHARS
#define MAX_TOKEN_CHARS 128
Definition at line 78 of file q_shared.h.
MAXTOUCH
#define MAXTOUCH 32
Definition at line 528 of file q_shared.h.
MZ2_ACTOR_MACHINEGUN_1
#define MZ2_ACTOR_MACHINEGUN_1 63
Definition at line 741 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_L1
#define MZ2_BOSS2_MACHINEGUN_L1 73
Definition at line 753 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_L2
#define MZ2_BOSS2_MACHINEGUN_L2 74
Definition at line 754 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_L3
#define MZ2_BOSS2_MACHINEGUN_L3 75
Definition at line 755 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_L4
#define MZ2_BOSS2_MACHINEGUN_L4 76
Definition at line 756 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_L5
#define MZ2_BOSS2_MACHINEGUN_L5 77
Definition at line 757 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_R1
#define MZ2_BOSS2_MACHINEGUN_R1 133
Definition at line 817 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_R2
#define MZ2_BOSS2_MACHINEGUN_R2 134
Definition at line 818 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_R3
#define MZ2_BOSS2_MACHINEGUN_R3 135
Definition at line 819 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_R4
#define MZ2_BOSS2_MACHINEGUN_R4 136
Definition at line 820 of file q_shared.h.
MZ2_BOSS2_MACHINEGUN_R5
#define MZ2_BOSS2_MACHINEGUN_R5 137
Definition at line 821 of file q_shared.h.
MZ2_BOSS2_ROCKET_1
#define MZ2_BOSS2_ROCKET_1 78
Definition at line 758 of file q_shared.h.
MZ2_BOSS2_ROCKET_2
#define MZ2_BOSS2_ROCKET_2 79
Definition at line 759 of file q_shared.h.
MZ2_BOSS2_ROCKET_3
#define MZ2_BOSS2_ROCKET_3 80
Definition at line 760 of file q_shared.h.
MZ2_BOSS2_ROCKET_4
#define MZ2_BOSS2_ROCKET_4 81
Definition at line 761 of file q_shared.h.
MZ2_CARRIER_GRENADE
#define MZ2_CARRIER_GRENADE 140
Definition at line 826 of file q_shared.h.
MZ2_CARRIER_MACHINEGUN_L1
#define MZ2_CARRIER_MACHINEGUN_L1 138
Definition at line 824 of file q_shared.h.
MZ2_CARRIER_MACHINEGUN_L2
#define MZ2_CARRIER_MACHINEGUN_L2 152
Definition at line 838 of file q_shared.h.
MZ2_CARRIER_MACHINEGUN_R1
#define MZ2_CARRIER_MACHINEGUN_R1 139
Definition at line 825 of file q_shared.h.
MZ2_CARRIER_MACHINEGUN_R2
#define MZ2_CARRIER_MACHINEGUN_R2 153
Definition at line 839 of file q_shared.h.
MZ2_CARRIER_RAILGUN
#define MZ2_CARRIER_RAILGUN 147
Definition at line 833 of file q_shared.h.
MZ2_CARRIER_ROCKET_1
#define MZ2_CARRIER_ROCKET_1 191
Definition at line 877 of file q_shared.h.
MZ2_CARRIER_ROCKET_2
#define MZ2_CARRIER_ROCKET_2 192
Definition at line 878 of file q_shared.h.
MZ2_CARRIER_ROCKET_3
#define MZ2_CARRIER_ROCKET_3 193
Definition at line 879 of file q_shared.h.
MZ2_CARRIER_ROCKET_4
#define MZ2_CARRIER_ROCKET_4 194
Definition at line 880 of file q_shared.h.
MZ2_CHICK_ROCKET_1
#define MZ2_CHICK_ROCKET_1 57
Definition at line 730 of file q_shared.h.
MZ2_DAEDALUS_BLASTER
#define MZ2_DAEDALUS_BLASTER 145
Definition at line 831 of file q_shared.h.
MZ2_FLOAT_BLASTER_1
#define MZ2_FLOAT_BLASTER_1 82
Definition at line 763 of file q_shared.h.
MZ2_FLYER_BLASTER_1
#define MZ2_FLYER_BLASTER_1 58
Definition at line 732 of file q_shared.h.
MZ2_FLYER_BLASTER_2
#define MZ2_FLYER_BLASTER_2 59
Definition at line 733 of file q_shared.h.
MZ2_GLADIATOR_RAILGUN_1
#define MZ2_GLADIATOR_RAILGUN_1 61
Definition at line 737 of file q_shared.h.
MZ2_GUNNER_GRENADE_1
#define MZ2_GUNNER_GRENADE_1 53
Definition at line 725 of file q_shared.h.
MZ2_GUNNER_GRENADE_2
#define MZ2_GUNNER_GRENADE_2 54
Definition at line 726 of file q_shared.h.
MZ2_GUNNER_GRENADE_3
#define MZ2_GUNNER_GRENADE_3 55
Definition at line 727 of file q_shared.h.
MZ2_GUNNER_GRENADE_4
#define MZ2_GUNNER_GRENADE_4 56
Definition at line 728 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_1
#define MZ2_GUNNER_MACHINEGUN_1 45
Definition at line 717 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_2
#define MZ2_GUNNER_MACHINEGUN_2 46
Definition at line 718 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_3
#define MZ2_GUNNER_MACHINEGUN_3 47
Definition at line 719 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_4
#define MZ2_GUNNER_MACHINEGUN_4 48
Definition at line 720 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_5
#define MZ2_GUNNER_MACHINEGUN_5 49
Definition at line 721 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_6
#define MZ2_GUNNER_MACHINEGUN_6 50
Definition at line 722 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_7
#define MZ2_GUNNER_MACHINEGUN_7 51
Definition at line 723 of file q_shared.h.
MZ2_GUNNER_MACHINEGUN_8
#define MZ2_GUNNER_MACHINEGUN_8 52
Definition at line 724 of file q_shared.h.
MZ2_HOVER_BLASTER_1
#define MZ2_HOVER_BLASTER_1 62
Definition at line 739 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_1
#define MZ2_INFANTRY_MACHINEGUN_1 26
Definition at line 696 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_10
#define MZ2_INFANTRY_MACHINEGUN_10 35
Definition at line 705 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_11
#define MZ2_INFANTRY_MACHINEGUN_11 36
Definition at line 706 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_12
#define MZ2_INFANTRY_MACHINEGUN_12 37
Definition at line 707 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_13
#define MZ2_INFANTRY_MACHINEGUN_13 38
Definition at line 708 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_2
#define MZ2_INFANTRY_MACHINEGUN_2 27
Definition at line 697 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_3
#define MZ2_INFANTRY_MACHINEGUN_3 28
Definition at line 698 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_4
#define MZ2_INFANTRY_MACHINEGUN_4 29
Definition at line 699 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_5
#define MZ2_INFANTRY_MACHINEGUN_5 30
Definition at line 700 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_6
#define MZ2_INFANTRY_MACHINEGUN_6 31
Definition at line 701 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_7
#define MZ2_INFANTRY_MACHINEGUN_7 32
Definition at line 702 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_8
#define MZ2_INFANTRY_MACHINEGUN_8 33
Definition at line 703 of file q_shared.h.
MZ2_INFANTRY_MACHINEGUN_9
#define MZ2_INFANTRY_MACHINEGUN_9 34
Definition at line 704 of file q_shared.h.
MZ2_JORG_BFG_1
#define MZ2_JORG_BFG_1 132
Definition at line 816 of file q_shared.h.
MZ2_JORG_MACHINEGUN_L1
#define MZ2_JORG_MACHINEGUN_L1 120
Definition at line 804 of file q_shared.h.
MZ2_JORG_MACHINEGUN_L2
#define MZ2_JORG_MACHINEGUN_L2 121
Definition at line 805 of file q_shared.h.
MZ2_JORG_MACHINEGUN_L3
#define MZ2_JORG_MACHINEGUN_L3 122
Definition at line 806 of file q_shared.h.
MZ2_JORG_MACHINEGUN_L4
#define MZ2_JORG_MACHINEGUN_L4 123
Definition at line 807 of file q_shared.h.
MZ2_JORG_MACHINEGUN_L5
#define MZ2_JORG_MACHINEGUN_L5 124
Definition at line 808 of file q_shared.h.
MZ2_JORG_MACHINEGUN_L6
#define MZ2_JORG_MACHINEGUN_L6 125
Definition at line 809 of file q_shared.h.
MZ2_JORG_MACHINEGUN_R1
#define MZ2_JORG_MACHINEGUN_R1 126
Definition at line 810 of file q_shared.h.
MZ2_JORG_MACHINEGUN_R2
#define MZ2_JORG_MACHINEGUN_R2 127
Definition at line 811 of file q_shared.h.
MZ2_JORG_MACHINEGUN_R3
#define MZ2_JORG_MACHINEGUN_R3 128
Definition at line 812 of file q_shared.h.
MZ2_JORG_MACHINEGUN_R4
#define MZ2_JORG_MACHINEGUN_R4 129
Definition at line 813 of file q_shared.h.
MZ2_JORG_MACHINEGUN_R5
#define MZ2_JORG_MACHINEGUN_R5 130
Definition at line 814 of file q_shared.h.
MZ2_JORG_MACHINEGUN_R6
#define MZ2_JORG_MACHINEGUN_R6 131
Definition at line 815 of file q_shared.h.
MZ2_MAKRON_BFG
#define MZ2_MAKRON_BFG 101
Definition at line 785 of file q_shared.h.
MZ2_MAKRON_BLASTER_1
#define MZ2_MAKRON_BLASTER_1 102
Definition at line 786 of file q_shared.h.
MZ2_MAKRON_BLASTER_10
#define MZ2_MAKRON_BLASTER_10 111
Definition at line 795 of file q_shared.h.
MZ2_MAKRON_BLASTER_11
#define MZ2_MAKRON_BLASTER_11 112
Definition at line 796 of file q_shared.h.
MZ2_MAKRON_BLASTER_12
#define MZ2_MAKRON_BLASTER_12 113
Definition at line 797 of file q_shared.h.
MZ2_MAKRON_BLASTER_13
#define MZ2_MAKRON_BLASTER_13 114
Definition at line 798 of file q_shared.h.
MZ2_MAKRON_BLASTER_14
#define MZ2_MAKRON_BLASTER_14 115
Definition at line 799 of file q_shared.h.
MZ2_MAKRON_BLASTER_15
#define MZ2_MAKRON_BLASTER_15 116
Definition at line 800 of file q_shared.h.
MZ2_MAKRON_BLASTER_16
#define MZ2_MAKRON_BLASTER_16 117
Definition at line 801 of file q_shared.h.
MZ2_MAKRON_BLASTER_17
#define MZ2_MAKRON_BLASTER_17 118
Definition at line 802 of file q_shared.h.
MZ2_MAKRON_BLASTER_2
#define MZ2_MAKRON_BLASTER_2 103
Definition at line 787 of file q_shared.h.
MZ2_MAKRON_BLASTER_3
#define MZ2_MAKRON_BLASTER_3 104
Definition at line 788 of file q_shared.h.
MZ2_MAKRON_BLASTER_4
#define MZ2_MAKRON_BLASTER_4 105
Definition at line 789 of file q_shared.h.
MZ2_MAKRON_BLASTER_5
#define MZ2_MAKRON_BLASTER_5 106
Definition at line 790 of file q_shared.h.
MZ2_MAKRON_BLASTER_6
#define MZ2_MAKRON_BLASTER_6 107
Definition at line 791 of file q_shared.h.
MZ2_MAKRON_BLASTER_7
#define MZ2_MAKRON_BLASTER_7 108
Definition at line 792 of file q_shared.h.
MZ2_MAKRON_BLASTER_8
#define MZ2_MAKRON_BLASTER_8 109
Definition at line 793 of file q_shared.h.
MZ2_MAKRON_BLASTER_9
#define MZ2_MAKRON_BLASTER_9 110
Definition at line 794 of file q_shared.h.
MZ2_MAKRON_RAILGUN_1
#define MZ2_MAKRON_RAILGUN_1 119
Definition at line 803 of file q_shared.h.
MZ2_MEDIC_BLASTER_1
#define MZ2_MEDIC_BLASTER_1 60
Definition at line 735 of file q_shared.h.
MZ2_MEDIC_BLASTER_2
#define MZ2_MEDIC_BLASTER_2 146
Definition at line 832 of file q_shared.h.
MZ2_SOLDIER_BLASTER_1
#define MZ2_SOLDIER_BLASTER_1 39
Definition at line 710 of file q_shared.h.
MZ2_SOLDIER_BLASTER_2
#define MZ2_SOLDIER_BLASTER_2 40
Definition at line 711 of file q_shared.h.
MZ2_SOLDIER_BLASTER_3
#define MZ2_SOLDIER_BLASTER_3 83
Definition at line 765 of file q_shared.h.
MZ2_SOLDIER_BLASTER_4
#define MZ2_SOLDIER_BLASTER_4 86
Definition at line 768 of file q_shared.h.
MZ2_SOLDIER_BLASTER_5
#define MZ2_SOLDIER_BLASTER_5 89
Definition at line 771 of file q_shared.h.
MZ2_SOLDIER_BLASTER_6
#define MZ2_SOLDIER_BLASTER_6 92
Definition at line 774 of file q_shared.h.
MZ2_SOLDIER_BLASTER_7
#define MZ2_SOLDIER_BLASTER_7 95
Definition at line 777 of file q_shared.h.
MZ2_SOLDIER_BLASTER_8
#define MZ2_SOLDIER_BLASTER_8 98
Definition at line 780 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_1
#define MZ2_SOLDIER_MACHINEGUN_1 43
Definition at line 714 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_2
#define MZ2_SOLDIER_MACHINEGUN_2 44
Definition at line 715 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_3
#define MZ2_SOLDIER_MACHINEGUN_3 85
Definition at line 767 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_4
#define MZ2_SOLDIER_MACHINEGUN_4 88
Definition at line 770 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_5
#define MZ2_SOLDIER_MACHINEGUN_5 91
Definition at line 773 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_6
#define MZ2_SOLDIER_MACHINEGUN_6 94
Definition at line 776 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_7
#define MZ2_SOLDIER_MACHINEGUN_7 97
Definition at line 779 of file q_shared.h.
MZ2_SOLDIER_MACHINEGUN_8
#define MZ2_SOLDIER_MACHINEGUN_8 100
Definition at line 782 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_1
#define MZ2_SOLDIER_SHOTGUN_1 41
Definition at line 712 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_2
#define MZ2_SOLDIER_SHOTGUN_2 42
Definition at line 713 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_3
#define MZ2_SOLDIER_SHOTGUN_3 84
Definition at line 766 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_4
#define MZ2_SOLDIER_SHOTGUN_4 87
Definition at line 769 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_5
#define MZ2_SOLDIER_SHOTGUN_5 90
Definition at line 772 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_6
#define MZ2_SOLDIER_SHOTGUN_6 93
Definition at line 775 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_7
#define MZ2_SOLDIER_SHOTGUN_7 96
Definition at line 778 of file q_shared.h.
MZ2_SOLDIER_SHOTGUN_8
#define MZ2_SOLDIER_SHOTGUN_8 99
Definition at line 781 of file q_shared.h.
MZ2_STALKER_BLASTER
#define MZ2_STALKER_BLASTER 144
Definition at line 830 of file q_shared.h.
MZ2_SUPERTANK_MACHINEGUN_1
#define MZ2_SUPERTANK_MACHINEGUN_1 64
Definition at line 743 of file q_shared.h.
MZ2_SUPERTANK_MACHINEGUN_2
#define MZ2_SUPERTANK_MACHINEGUN_2 65
Definition at line 744 of file q_shared.h.
MZ2_SUPERTANK_MACHINEGUN_3
#define MZ2_SUPERTANK_MACHINEGUN_3 66
Definition at line 745 of file q_shared.h.
MZ2_SUPERTANK_MACHINEGUN_4
#define MZ2_SUPERTANK_MACHINEGUN_4 67
Definition at line 746 of file q_shared.h.
MZ2_SUPERTANK_MACHINEGUN_5
#define MZ2_SUPERTANK_MACHINEGUN_5 68
Definition at line 747 of file q_shared.h.
MZ2_SUPERTANK_MACHINEGUN_6
#define MZ2_SUPERTANK_MACHINEGUN_6 69
Definition at line 748 of file q_shared.h.
MZ2_SUPERTANK_ROCKET_1
#define MZ2_SUPERTANK_ROCKET_1 70
Definition at line 749 of file q_shared.h.
MZ2_SUPERTANK_ROCKET_2
#define MZ2_SUPERTANK_ROCKET_2 71
Definition at line 750 of file q_shared.h.
MZ2_SUPERTANK_ROCKET_3
#define MZ2_SUPERTANK_ROCKET_3 72
Definition at line 751 of file q_shared.h.
MZ2_TANK_BLASTER_1
#define MZ2_TANK_BLASTER_1 1
Definition at line 670 of file q_shared.h.
MZ2_TANK_BLASTER_2
#define MZ2_TANK_BLASTER_2 2
Definition at line 671 of file q_shared.h.
MZ2_TANK_BLASTER_3
#define MZ2_TANK_BLASTER_3 3
Definition at line 672 of file q_shared.h.
MZ2_TANK_MACHINEGUN_1
#define MZ2_TANK_MACHINEGUN_1 4
Definition at line 673 of file q_shared.h.
MZ2_TANK_MACHINEGUN_10
#define MZ2_TANK_MACHINEGUN_10 13
Definition at line 682 of file q_shared.h.
MZ2_TANK_MACHINEGUN_11
#define MZ2_TANK_MACHINEGUN_11 14
Definition at line 683 of file q_shared.h.
MZ2_TANK_MACHINEGUN_12
#define MZ2_TANK_MACHINEGUN_12 15
Definition at line 684 of file q_shared.h.
MZ2_TANK_MACHINEGUN_13
#define MZ2_TANK_MACHINEGUN_13 16
Definition at line 685 of file q_shared.h.
MZ2_TANK_MACHINEGUN_14
#define MZ2_TANK_MACHINEGUN_14 17
Definition at line 686 of file q_shared.h.
MZ2_TANK_MACHINEGUN_15
#define MZ2_TANK_MACHINEGUN_15 18
Definition at line 687 of file q_shared.h.
MZ2_TANK_MACHINEGUN_16
#define MZ2_TANK_MACHINEGUN_16 19
Definition at line 688 of file q_shared.h.
MZ2_TANK_MACHINEGUN_17
#define MZ2_TANK_MACHINEGUN_17 20
Definition at line 689 of file q_shared.h.
MZ2_TANK_MACHINEGUN_18
#define MZ2_TANK_MACHINEGUN_18 21
Definition at line 690 of file q_shared.h.
MZ2_TANK_MACHINEGUN_19
#define MZ2_TANK_MACHINEGUN_19 22
Definition at line 691 of file q_shared.h.
MZ2_TANK_MACHINEGUN_2
#define MZ2_TANK_MACHINEGUN_2 5
Definition at line 674 of file q_shared.h.
MZ2_TANK_MACHINEGUN_3
#define MZ2_TANK_MACHINEGUN_3 6
Definition at line 675 of file q_shared.h.
MZ2_TANK_MACHINEGUN_4
#define MZ2_TANK_MACHINEGUN_4 7
Definition at line 676 of file q_shared.h.
MZ2_TANK_MACHINEGUN_5
#define MZ2_TANK_MACHINEGUN_5 8
Definition at line 677 of file q_shared.h.
MZ2_TANK_MACHINEGUN_6
#define MZ2_TANK_MACHINEGUN_6 9
Definition at line 678 of file q_shared.h.
MZ2_TANK_MACHINEGUN_7
#define MZ2_TANK_MACHINEGUN_7 10
Definition at line 679 of file q_shared.h.
MZ2_TANK_MACHINEGUN_8
#define MZ2_TANK_MACHINEGUN_8 11
Definition at line 680 of file q_shared.h.
MZ2_TANK_MACHINEGUN_9
#define MZ2_TANK_MACHINEGUN_9 12
Definition at line 681 of file q_shared.h.
MZ2_TANK_ROCKET_1
#define MZ2_TANK_ROCKET_1 23
Definition at line 692 of file q_shared.h.
MZ2_TANK_ROCKET_2
#define MZ2_TANK_ROCKET_2 24
Definition at line 693 of file q_shared.h.
MZ2_TANK_ROCKET_3
#define MZ2_TANK_ROCKET_3 25
Definition at line 694 of file q_shared.h.
MZ2_TURRET_BLASTER
#define MZ2_TURRET_BLASTER 143
Definition at line 829 of file q_shared.h.
MZ2_TURRET_MACHINEGUN
#define MZ2_TURRET_MACHINEGUN 141
Definition at line 827 of file q_shared.h.
MZ2_TURRET_ROCKET
#define MZ2_TURRET_ROCKET 142
Definition at line 828 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_1
#define MZ2_WIDOW2_BEAM_SWEEP_1 200
Definition at line 886 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_10
#define MZ2_WIDOW2_BEAM_SWEEP_10 209
Definition at line 895 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_11
#define MZ2_WIDOW2_BEAM_SWEEP_11 210
Definition at line 896 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_2
#define MZ2_WIDOW2_BEAM_SWEEP_2 201
Definition at line 887 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_3
#define MZ2_WIDOW2_BEAM_SWEEP_3 202
Definition at line 888 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_4
#define MZ2_WIDOW2_BEAM_SWEEP_4 203
Definition at line 889 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_5
#define MZ2_WIDOW2_BEAM_SWEEP_5 204
Definition at line 890 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_6
#define MZ2_WIDOW2_BEAM_SWEEP_6 205
Definition at line 891 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_7
#define MZ2_WIDOW2_BEAM_SWEEP_7 206
Definition at line 892 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_8
#define MZ2_WIDOW2_BEAM_SWEEP_8 207
Definition at line 893 of file q_shared.h.
MZ2_WIDOW2_BEAM_SWEEP_9
#define MZ2_WIDOW2_BEAM_SWEEP_9 208
Definition at line 894 of file q_shared.h.
MZ2_WIDOW2_BEAMER_1
#define MZ2_WIDOW2_BEAMER_1 195
Definition at line 881 of file q_shared.h.
MZ2_WIDOW2_BEAMER_2
#define MZ2_WIDOW2_BEAMER_2 196
Definition at line 882 of file q_shared.h.
MZ2_WIDOW2_BEAMER_3
#define MZ2_WIDOW2_BEAMER_3 197
Definition at line 883 of file q_shared.h.
MZ2_WIDOW2_BEAMER_4
#define MZ2_WIDOW2_BEAMER_4 198
Definition at line 884 of file q_shared.h.
MZ2_WIDOW2_BEAMER_5
#define MZ2_WIDOW2_BEAMER_5 199
Definition at line 885 of file q_shared.h.
MZ2_WIDOW_BLASTER
#define MZ2_WIDOW_BLASTER 149
Definition at line 835 of file q_shared.h.
MZ2_WIDOW_BLASTER_0
#define MZ2_WIDOW_BLASTER_0 175
Definition at line 861 of file q_shared.h.
MZ2_WIDOW_BLASTER_10
#define MZ2_WIDOW_BLASTER_10 174
Definition at line 860 of file q_shared.h.
MZ2_WIDOW_BLASTER_100
#define MZ2_WIDOW_BLASTER_100 165
Definition at line 851 of file q_shared.h.
MZ2_WIDOW_BLASTER_10L
#define MZ2_WIDOW_BLASTER_10L 176
Definition at line 862 of file q_shared.h.
MZ2_WIDOW_BLASTER_20
#define MZ2_WIDOW_BLASTER_20 173
Definition at line 859 of file q_shared.h.
MZ2_WIDOW_BLASTER_20L
#define MZ2_WIDOW_BLASTER_20L 177
Definition at line 863 of file q_shared.h.
MZ2_WIDOW_BLASTER_30
#define MZ2_WIDOW_BLASTER_30 172
Definition at line 858 of file q_shared.h.
MZ2_WIDOW_BLASTER_30L
#define MZ2_WIDOW_BLASTER_30L 178
Definition at line 864 of file q_shared.h.
MZ2_WIDOW_BLASTER_40
#define MZ2_WIDOW_BLASTER_40 171
Definition at line 857 of file q_shared.h.
MZ2_WIDOW_BLASTER_40L
#define MZ2_WIDOW_BLASTER_40L 179
Definition at line 865 of file q_shared.h.
MZ2_WIDOW_BLASTER_50
#define MZ2_WIDOW_BLASTER_50 170
Definition at line 856 of file q_shared.h.
MZ2_WIDOW_BLASTER_50L
#define MZ2_WIDOW_BLASTER_50L 180
Definition at line 866 of file q_shared.h.
MZ2_WIDOW_BLASTER_60
#define MZ2_WIDOW_BLASTER_60 169
Definition at line 855 of file q_shared.h.
MZ2_WIDOW_BLASTER_60L
#define MZ2_WIDOW_BLASTER_60L 181
Definition at line 867 of file q_shared.h.
MZ2_WIDOW_BLASTER_70
#define MZ2_WIDOW_BLASTER_70 168
Definition at line 854 of file q_shared.h.
MZ2_WIDOW_BLASTER_70L
#define MZ2_WIDOW_BLASTER_70L 182
Definition at line 868 of file q_shared.h.
MZ2_WIDOW_BLASTER_80
#define MZ2_WIDOW_BLASTER_80 167
Definition at line 853 of file q_shared.h.
MZ2_WIDOW_BLASTER_90
#define MZ2_WIDOW_BLASTER_90 166
Definition at line 852 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP1
#define MZ2_WIDOW_BLASTER_SWEEP1 156
Definition at line 842 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP2
#define MZ2_WIDOW_BLASTER_SWEEP2 157
Definition at line 843 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP3
#define MZ2_WIDOW_BLASTER_SWEEP3 158
Definition at line 844 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP4
#define MZ2_WIDOW_BLASTER_SWEEP4 159
Definition at line 845 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP5
#define MZ2_WIDOW_BLASTER_SWEEP5 160
Definition at line 846 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP6
#define MZ2_WIDOW_BLASTER_SWEEP6 161
Definition at line 847 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP7
#define MZ2_WIDOW_BLASTER_SWEEP7 162
Definition at line 848 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP8
#define MZ2_WIDOW_BLASTER_SWEEP8 163
Definition at line 849 of file q_shared.h.
MZ2_WIDOW_BLASTER_SWEEP9
#define MZ2_WIDOW_BLASTER_SWEEP9 164
Definition at line 850 of file q_shared.h.
MZ2_WIDOW_DISRUPTOR
#define MZ2_WIDOW_DISRUPTOR 148
Definition at line 834 of file q_shared.h.
MZ2_WIDOW_PLASMABEAM
#define MZ2_WIDOW_PLASMABEAM 151
Definition at line 837 of file q_shared.h.
MZ2_WIDOW_RAIL
#define MZ2_WIDOW_RAIL 150
Definition at line 836 of file q_shared.h.
MZ2_WIDOW_RAIL_LEFT
#define MZ2_WIDOW_RAIL_LEFT 154
Definition at line 840 of file q_shared.h.
MZ2_WIDOW_RAIL_RIGHT
#define MZ2_WIDOW_RAIL_RIGHT 155
Definition at line 841 of file q_shared.h.
MZ2_WIDOW_RUN_1
#define MZ2_WIDOW_RUN_1 183
Definition at line 869 of file q_shared.h.
MZ2_WIDOW_RUN_2
#define MZ2_WIDOW_RUN_2 184
Definition at line 870 of file q_shared.h.
MZ2_WIDOW_RUN_3
#define MZ2_WIDOW_RUN_3 185
Definition at line 871 of file q_shared.h.
MZ2_WIDOW_RUN_4
#define MZ2_WIDOW_RUN_4 186
Definition at line 872 of file q_shared.h.
MZ2_WIDOW_RUN_5
#define MZ2_WIDOW_RUN_5 187
Definition at line 873 of file q_shared.h.
MZ2_WIDOW_RUN_6
#define MZ2_WIDOW_RUN_6 188
Definition at line 874 of file q_shared.h.
MZ2_WIDOW_RUN_7
#define MZ2_WIDOW_RUN_7 189
Definition at line 875 of file q_shared.h.
MZ2_WIDOW_RUN_8
#define MZ2_WIDOW_RUN_8 190
Definition at line 876 of file q_shared.h.
MZ_BFG
#define MZ_BFG 12
Definition at line 644 of file q_shared.h.
MZ_BLASTER
#define MZ_BLASTER 0
Definition at line 632 of file q_shared.h.
MZ_BLASTER2
#define MZ_BLASTER2 34
Definition at line 659 of file q_shared.h.
MZ_BLUEHYPERBLASTER
#define MZ_BLUEHYPERBLASTER 17
Definition at line 650 of file q_shared.h.
MZ_CHAINGUN1
#define MZ_CHAINGUN1 3
Definition at line 635 of file q_shared.h.
MZ_CHAINGUN2
#define MZ_CHAINGUN2 4
Definition at line 636 of file q_shared.h.
MZ_CHAINGUN3
#define MZ_CHAINGUN3 5
Definition at line 637 of file q_shared.h.
MZ_ETF_RIFLE
#define MZ_ETF_RIFLE 30
Definition at line 655 of file q_shared.h.
MZ_GRENADE
#define MZ_GRENADE 8
Definition at line 640 of file q_shared.h.
MZ_HEATBEAM
#define MZ_HEATBEAM 33
Definition at line 658 of file q_shared.h.
MZ_HYPERBLASTER
#define MZ_HYPERBLASTER 14
Definition at line 646 of file q_shared.h.
MZ_IONRIPPER
#define MZ_IONRIPPER 16
Definition at line 649 of file q_shared.h.
MZ_ITEMRESPAWN
#define MZ_ITEMRESPAWN 15
Definition at line 647 of file q_shared.h.
MZ_LOGIN
#define MZ_LOGIN 9
Definition at line 641 of file q_shared.h.
MZ_LOGOUT
#define MZ_LOGOUT 10
Definition at line 642 of file q_shared.h.
MZ_MACHINEGUN
#define MZ_MACHINEGUN 1
Definition at line 633 of file q_shared.h.
MZ_NUKE1
#define MZ_NUKE1 36
Definition at line 661 of file q_shared.h.
MZ_NUKE2
#define MZ_NUKE2 37
Definition at line 662 of file q_shared.h.
MZ_NUKE4
#define MZ_NUKE4 38
Definition at line 663 of file q_shared.h.
MZ_NUKE8
#define MZ_NUKE8 39
Definition at line 664 of file q_shared.h.
MZ_PHALANX
#define MZ_PHALANX 18
Definition at line 651 of file q_shared.h.
MZ_RAILGUN
#define MZ_RAILGUN 6
Definition at line 638 of file q_shared.h.
MZ_RESPAWN
#define MZ_RESPAWN 11
Definition at line 643 of file q_shared.h.
MZ_ROCKET
#define MZ_ROCKET 7
Definition at line 639 of file q_shared.h.
MZ_SHOTGUN
#define MZ_SHOTGUN 2
Definition at line 634 of file q_shared.h.
MZ_SHOTGUN2
#define MZ_SHOTGUN2 32
Definition at line 657 of file q_shared.h.
MZ_SILENCED
#define MZ_SILENCED 128
Definition at line 652 of file q_shared.h.
MZ_SSHOTGUN
#define MZ_SSHOTGUN 13
Definition at line 645 of file q_shared.h.
MZ_TRACKER
#define MZ_TRACKER 35
Definition at line 660 of file q_shared.h.
MZ_UNUSED
#define MZ_UNUSED 31
Definition at line 656 of file q_shared.h.
nanmask
#define nanmask (255<<23)
Definition at line 149 of file q_shared.h.
NULL
#define NULL ((void *)0)
Definition at line 67 of file q_shared.h.
PITCH
#define PITCH 0
Definition at line 72 of file q_shared.h.
PMF_DUCKED
#define PMF_DUCKED 1
Definition at line 481 of file q_shared.h.
PMF_JUMP_HELD
#define PMF_JUMP_HELD 2
Definition at line 482 of file q_shared.h.
PMF_NO_PREDICTION
#define PMF_NO_PREDICTION 64
Definition at line 487 of file q_shared.h.
PMF_ON_GROUND
#define PMF_ON_GROUND 4
Definition at line 483 of file q_shared.h.
PMF_TIME_LAND
#define PMF_TIME_LAND 16
Definition at line 485 of file q_shared.h.
PMF_TIME_TELEPORT
#define PMF_TIME_TELEPORT 32
Definition at line 486 of file q_shared.h.
PMF_TIME_WATERJUMP
#define PMF_TIME_WATERJUMP 8
Definition at line 484 of file q_shared.h.
PRINT_ALERT
#define PRINT_ALERT 2
Definition at line 110 of file q_shared.h.
PRINT_ALL
#define PRINT_ALL 0
Definition at line 108 of file q_shared.h.
PRINT_CHAT
#define PRINT_CHAT 3
Definition at line 100 of file q_shared.h.
PRINT_DEVELOPER
#define PRINT_DEVELOPER 1
Definition at line 109 of file q_shared.h.
PRINT_HIGH
#define PRINT_HIGH 2
Definition at line 99 of file q_shared.h.
PRINT_LOW
#define PRINT_LOW 0
Definition at line 97 of file q_shared.h.
PRINT_MEDIUM
#define PRINT_MEDIUM 1
Definition at line 98 of file q_shared.h.
RDF_IRGOGGLES
#define RDF_IRGOGGLES 4
Definition at line 625 of file q_shared.h.
RDF_NOWORLDMODEL
#define RDF_NOWORLDMODEL 2
Definition at line 622 of file q_shared.h.
RDF_UNDERWATER
#define RDF_UNDERWATER 1
Definition at line 621 of file q_shared.h.
RDF_UVGOGGLES
#define RDF_UVGOGGLES 8
Definition at line 626 of file q_shared.h.
RF_BEAM
#define RF_BEAM 128
Definition at line 606 of file q_shared.h.
RF_CUSTOMSKIN
#define RF_CUSTOMSKIN 256
Definition at line 607 of file q_shared.h.
RF_DEPTHHACK
#define RF_DEPTHHACK 16
Definition at line 603 of file q_shared.h.
RF_FRAMELERP
#define RF_FRAMELERP 64
Definition at line 605 of file q_shared.h.
RF_FULLBRIGHT
#define RF_FULLBRIGHT 8
Definition at line 602 of file q_shared.h.
RF_GLOW
#define RF_GLOW 512
Definition at line 608 of file q_shared.h.
RF_IR_VISIBLE
#define RF_IR_VISIBLE 0x00008000
Definition at line 614 of file q_shared.h.
RF_MINLIGHT
#define RF_MINLIGHT 1
Definition at line 599 of file q_shared.h.
RF_SHELL_BLUE
#define RF_SHELL_BLUE 4096
Definition at line 611 of file q_shared.h.
RF_SHELL_DOUBLE
#define RF_SHELL_DOUBLE 0x00010000
Definition at line 615 of file q_shared.h.
RF_SHELL_GREEN
#define RF_SHELL_GREEN 2048
Definition at line 610 of file q_shared.h.
RF_SHELL_HALF_DAM
#define RF_SHELL_HALF_DAM 0x00020000
Definition at line 616 of file q_shared.h.
RF_SHELL_RED
#define RF_SHELL_RED 1024
Definition at line 609 of file q_shared.h.
RF_TRANSLUCENT
#define RF_TRANSLUCENT 32
Definition at line 604 of file q_shared.h.
RF_USE_DISGUISE
#define RF_USE_DISGUISE 0x00040000
Definition at line 617 of file q_shared.h.
RF_VIEWERMODEL
#define RF_VIEWERMODEL 2
Definition at line 600 of file q_shared.h.
RF_WEAPONMODEL
#define RF_WEAPONMODEL 4
Definition at line 601 of file q_shared.h.
ROGUE_VERSION_ID
#define ROGUE_VERSION_ID 1278
Definition at line 1079 of file q_shared.h.
ROGUE_VERSION_STRING
#define ROGUE_VERSION_STRING "08/21/1998 Beta 2 for Ensemble"
Definition at line 1081 of file q_shared.h.
ROLL
#define ROLL 2
Definition at line 74 of file q_shared.h.
SFF_ARCH
#define SFF_ARCH 0x01
Definition at line 286 of file q_shared.h.
SFF_HIDDEN
#define SFF_HIDDEN 0x02
Definition at line 287 of file q_shared.h.
SFF_RDONLY
#define SFF_RDONLY 0x04
Definition at line 288 of file q_shared.h.
SFF_SUBDIR
#define SFF_SUBDIR 0x08
Definition at line 289 of file q_shared.h.
SFF_SYSTEM
#define SFF_SYSTEM 0x10
Definition at line 290 of file q_shared.h.
SHORT2ANGLE
#define SHORT2ANGLE (x) ((x)*(360.0/65536))
Definition at line 1093 of file q_shared.h.
SPLASH_BLOOD
#define SPLASH_BLOOD 6
Definition at line 977 of file q_shared.h.
SPLASH_BLUE_WATER
#define SPLASH_BLUE_WATER 2
Definition at line 973 of file q_shared.h.
SPLASH_BROWN_WATER
#define SPLASH_BROWN_WATER 3
Definition at line 974 of file q_shared.h.
SPLASH_LAVA
#define SPLASH_LAVA 5
Definition at line 976 of file q_shared.h.
SPLASH_SLIME
#define SPLASH_SLIME 4
Definition at line 975 of file q_shared.h.
SPLASH_SPARKS
#define SPLASH_SPARKS 1
Definition at line 972 of file q_shared.h.
SPLASH_UNKNOWN
#define SPLASH_UNKNOWN 0
Definition at line 971 of file q_shared.h.
STAT_AMMO
#define STAT_AMMO 3
Definition at line 1004 of file q_shared.h.
STAT_AMMO_ICON
#define STAT_AMMO_ICON 2
Definition at line 1003 of file q_shared.h.
STAT_ARMOR
#define STAT_ARMOR 5
Definition at line 1006 of file q_shared.h.
STAT_ARMOR_ICON
#define STAT_ARMOR_ICON 4
Definition at line 1005 of file q_shared.h.
STAT_CHASE
#define STAT_CHASE 16
Definition at line 1017 of file q_shared.h.
STAT_FLASHES
#define STAT_FLASHES 15
Definition at line 1016 of file q_shared.h.
STAT_FRAGS
#define STAT_FRAGS 14
Definition at line 1015 of file q_shared.h.
STAT_HEALTH
#define STAT_HEALTH 1
Definition at line 1002 of file q_shared.h.
STAT_HEALTH_ICON
#define STAT_HEALTH_ICON 0
Definition at line 1001 of file q_shared.h.
STAT_HELPICON
#define STAT_HELPICON 11
Definition at line 1012 of file q_shared.h.
STAT_LAYOUTS
#define STAT_LAYOUTS 13
Definition at line 1014 of file q_shared.h.
STAT_PICKUP_ICON
#define STAT_PICKUP_ICON 7
Definition at line 1008 of file q_shared.h.
STAT_PICKUP_STRING
#define STAT_PICKUP_STRING 8
Definition at line 1009 of file q_shared.h.
STAT_SELECTED_ICON
#define STAT_SELECTED_ICON 6
Definition at line 1007 of file q_shared.h.
STAT_SELECTED_ITEM
#define STAT_SELECTED_ITEM 12
Definition at line 1013 of file q_shared.h.
STAT_SPECTATOR
#define STAT_SPECTATOR 17
Definition at line 1018 of file q_shared.h.
STAT_TIMER
#define STAT_TIMER 10
Definition at line 1011 of file q_shared.h.
STAT_TIMER_ICON
#define STAT_TIMER_ICON 9
Definition at line 1010 of file q_shared.h.
SURF_FLOWING
#define SURF_FLOWING 0x40
Definition at line 388 of file q_shared.h.
SURF_LIGHT
#define SURF_LIGHT 0x1
Definition at line 380 of file q_shared.h.
SURF_NODRAW
#define SURF_NODRAW 0x80
Definition at line 389 of file q_shared.h.
SURF_SKY
#define SURF_SKY 0x4
Definition at line 384 of file q_shared.h.
SURF_SLICK
#define SURF_SLICK 0x2
Definition at line 382 of file q_shared.h.
SURF_TRANS33
#define SURF_TRANS33 0x10
Definition at line 386 of file q_shared.h.
SURF_TRANS66
#define SURF_TRANS66 0x20
Definition at line 387 of file q_shared.h.
SURF_WARP
#define SURF_WARP 0x8
Definition at line 385 of file q_shared.h.
VectorAdd
#define VectorAdd (a, b, c) (c[0]=a[0]+b[0],c[1]=a[1]+b[1],c[2]=a[2]+b[2])
Definition at line 164 of file q_shared.h.
VectorClear
#define VectorClear (a) (a[0]=a[1]=a[2]=0)
Definition at line 166 of file q_shared.h.
VectorCopy
#define VectorCopy (a, b) (b[0]=a[0],b[1]=a[1],b[2]=a[2])
Definition at line 165 of file q_shared.h.
VectorNegate
#define VectorNegate (a, b) (b[0]=-a[0],b[1]=-a[1],b[2]=-a[2])
Definition at line 167 of file q_shared.h.
VectorSet
#define VectorSet (v, x, y, z) (v[0]=(x), v[1]=(y), v[2]=(z))
Definition at line 168 of file q_shared.h.
VectorSubtract
#define VectorSubtract (a, b, c) (c[0]=a[0]-b[0],c[1]=a[1]-b[1],c[2]=a[2]-b[2])
Definition at line 163 of file q_shared.h.
VIDREF_GL
#define VIDREF_GL 2
Definition at line 1203 of file q_shared.h.
VIDREF_OTHER
#define VIDREF_OTHER 4
Definition at line 1205 of file q_shared.h.
VIDREF_SOFT
#define VIDREF_SOFT 3
Definition at line 1204 of file q_shared.h.
VIDREF_VK
#define VIDREF_VK 1
Definition at line 1202 of file q_shared.h.
YAW
#define YAW 1
Definition at line 73 of file q_shared.h.
Typedef Documentation
byte
typedef unsigned char byte
Definition at line 62 of file q_shared.h.
cmodel_t
typedef struct cmodel_s cmodel_t
cplane_t
typedef struct cplane_s cplane_t
csurface_t
typedef struct csurface_s csurface_t
cvar_t
typedef struct cvar_s cvar_t
entity_state_t
typedef struct entity_state_s entity_state_t
fixed16_t
typedef int fixed16_t
Definition at line 139 of file q_shared.h.
fixed4_t
typedef int fixed4_t
Definition at line 137 of file q_shared.h.
fixed8_t
typedef int fixed8_t
Definition at line 138 of file q_shared.h.
mapsurface_t
typedef struct mapsurface_s mapsurface_t
usercmd_t
typedef struct usercmd_s usercmd_t
vec3_t
typedef vec_t vec3_t[3]
Definition at line 134 of file q_shared.h.
vec5_t
typedef vec_t vec5_t[5]
Definition at line 135 of file q_shared.h.
vec_t
typedef float vec_t
Definition at line 133 of file q_shared.h.
Enumeration Type Documentation
entity_event_t
enum entity_event_t
Enumerator
EV_NONE
EV_ITEM_RESPAWN
EV_FOOTSTEP
EV_FALLSHORT
EV_FALL
EV_FALLFAR
EV_PLAYER_TELEPORT
EV_OTHER_TELEPORT
EV_NONE
EV_ITEM_RESPAWN
EV_FOOTSTEP
EV_FALLSHORT
EV_FALL
EV_FALLFAR
EV_PLAYER_TELEPORT
EV_OTHER_TELEPORT
Definition at line 1129 of file q_shared.h.
 {
     EV_NONE,
     EV_ITEM_RESPAWN,
     EV_FOOTSTEP,
     EV_FALLSHORT,
     EV_FALL,
     EV_FALLFAR,
     EV_PLAYER_TELEPORT,
     EV_OTHER_TELEPORT
 } entity_event_t;
multicast_t
enum multicast_t
Enumerator
MULTICAST_ALL
MULTICAST_PHS
MULTICAST_PVS
MULTICAST_ALL_R
MULTICAST_PHS_R
MULTICAST_PVS_R
MULTICAST_ALL
MULTICAST_PHS
MULTICAST_PVS
MULTICAST_ALL_R
MULTICAST_PHS_R
MULTICAST_PVS_R
Definition at line 114 of file q_shared.h.
 {
 MULTICAST_ALL,
 MULTICAST_PHS,
 MULTICAST_PVS,
 MULTICAST_ALL_R,
 MULTICAST_PHS_R,
 MULTICAST_PVS_R
 } multicast_t;
pmtype_t
enum pmtype_t
Enumerator
PM_NORMAL
PM_SPECTATOR
PM_DEAD
PM_GIB
PM_FREEZE
PM_NORMAL
PM_SPECTATOR
PM_DEAD
PM_GIB
PM_FREEZE
Definition at line 469 of file q_shared.h.
 {
     // can accelerate and turn
     PM_NORMAL,
     PM_SPECTATOR,
     // no acceleration or turning
     PM_DEAD,
     PM_GIB,     // different bounding box
     PM_FREEZE
 } pmtype_t;
qboolean
enum qboolean
Enumerator
false
true
false
true
Definition at line 63 of file q_shared.h.
 {false, true}   qboolean;
temp_event_t
enum temp_event_t
Enumerator
TE_GUNSHOT
TE_BLOOD
TE_BLASTER
TE_RAILTRAIL
TE_SHOTGUN
TE_EXPLOSION1
TE_EXPLOSION2
TE_ROCKET_EXPLOSION
TE_GRENADE_EXPLOSION
TE_SPARKS
TE_SPLASH
TE_BUBBLETRAIL
TE_SCREEN_SPARKS
TE_SHIELD_SPARKS
TE_BULLET_SPARKS
TE_LASER_SPARKS
TE_PARASITE_ATTACK
TE_ROCKET_EXPLOSION_WATER
TE_GRENADE_EXPLOSION_WATER
TE_MEDIC_CABLE_ATTACK
TE_BFG_EXPLOSION
TE_BFG_BIGEXPLOSION
TE_BOSSTPORT
TE_BFG_LASER
TE_GRAPPLE_CABLE
TE_WELDING_SPARKS
TE_GREENBLOOD
TE_BLUEHYPERBLASTER
TE_PLASMA_EXPLOSION
TE_TUNNEL_SPARKS
TE_BLASTER2
TE_RAILTRAIL2
TE_FLAME
TE_LIGHTNING
TE_DEBUGTRAIL
TE_PLAIN_EXPLOSION
TE_FLASHLIGHT
TE_FORCEWALL
TE_HEATBEAM
TE_MONSTER_HEATBEAM
TE_STEAM
TE_BUBBLETRAIL2
TE_MOREBLOOD
TE_HEATBEAM_SPARKS
TE_HEATBEAM_STEAM
TE_CHAINFIST_SMOKE
TE_ELECTRIC_SPARKS
TE_TRACKER_EXPLOSION
TE_TELEPORT_EFFECT
TE_DBALL_GOAL
TE_WIDOWBEAMOUT
TE_NUKEBLAST
TE_WIDOWSPLASH
TE_EXPLOSION1_BIG
TE_EXPLOSION1_NP
TE_FLECHETTE
TE_GUNSHOT
TE_BLOOD
TE_BLASTER
TE_RAILTRAIL
TE_SHOTGUN
TE_EXPLOSION1
TE_EXPLOSION2
TE_ROCKET_EXPLOSION
TE_GRENADE_EXPLOSION
TE_SPARKS
TE_SPLASH
TE_BUBBLETRAIL
TE_SCREEN_SPARKS
TE_SHIELD_SPARKS
TE_BULLET_SPARKS
TE_LASER_SPARKS
TE_PARASITE_ATTACK
TE_ROCKET_EXPLOSION_WATER
TE_GRENADE_EXPLOSION_WATER
TE_MEDIC_CABLE_ATTACK
TE_BFG_EXPLOSION
TE_BFG_BIGEXPLOSION
TE_BOSSTPORT
TE_BFG_LASER
TE_GRAPPLE_CABLE
TE_WELDING_SPARKS
TE_GREENBLOOD
TE_BLUEHYPERBLASTER
TE_PLASMA_EXPLOSION
TE_TUNNEL_SPARKS
TE_BLASTER2
TE_RAILTRAIL2
TE_FLAME
TE_LIGHTNING
TE_DEBUGTRAIL
TE_PLAIN_EXPLOSION
TE_FLASHLIGHT
TE_FORCEWALL
TE_HEATBEAM
TE_MONSTER_HEATBEAM
TE_STEAM
TE_BUBBLETRAIL2
TE_MOREBLOOD
TE_HEATBEAM_SPARKS
TE_HEATBEAM_STEAM
TE_CHAINFIST_SMOKE
TE_ELECTRIC_SPARKS
TE_TRACKER_EXPLOSION
TE_TELEPORT_EFFECT
TE_DBALL_GOAL
TE_WIDOWBEAMOUT
TE_NUKEBLAST
TE_WIDOWSPLASH
TE_EXPLOSION1_BIG
TE_EXPLOSION1_NP
TE_FLECHETTE
Definition at line 909 of file q_shared.h.
 {
     TE_GUNSHOT,
     TE_BLOOD,
     TE_BLASTER,
     TE_RAILTRAIL,
     TE_SHOTGUN,
     TE_EXPLOSION1,
     TE_EXPLOSION2,
     TE_ROCKET_EXPLOSION,
     TE_GRENADE_EXPLOSION,
     TE_SPARKS,
     TE_SPLASH,
     TE_BUBBLETRAIL,
     TE_SCREEN_SPARKS,
     TE_SHIELD_SPARKS,
     TE_BULLET_SPARKS,
     TE_LASER_SPARKS,
     TE_PARASITE_ATTACK,
     TE_ROCKET_EXPLOSION_WATER,
     TE_GRENADE_EXPLOSION_WATER,
     TE_MEDIC_CABLE_ATTACK,
     TE_BFG_EXPLOSION,
     TE_BFG_BIGEXPLOSION,
     TE_BOSSTPORT,           // used as '22' in a map, so DON'T RENUMBER!!!
     TE_BFG_LASER,
     TE_GRAPPLE_CABLE,
     TE_WELDING_SPARKS,
     TE_GREENBLOOD,
     TE_BLUEHYPERBLASTER,
     TE_PLASMA_EXPLOSION,
     TE_TUNNEL_SPARKS,
 //ROGUE
     TE_BLASTER2,
     TE_RAILTRAIL2,
     TE_FLAME,
     TE_LIGHTNING,
     TE_DEBUGTRAIL,
     TE_PLAIN_EXPLOSION,
     TE_FLASHLIGHT,
     TE_FORCEWALL,
     TE_HEATBEAM,
     TE_MONSTER_HEATBEAM,
     TE_STEAM,
     TE_BUBBLETRAIL2,
     TE_MOREBLOOD,
     TE_HEATBEAM_SPARKS,
     TE_HEATBEAM_STEAM,
     TE_CHAINFIST_SMOKE,
     TE_ELECTRIC_SPARKS,
     TE_TRACKER_EXPLOSION,
     TE_TELEPORT_EFFECT,
     TE_DBALL_GOAL,
     TE_WIDOWBEAMOUT,
     TE_NUKEBLAST,
     TE_WIDOWSPLASH,
     TE_EXPLOSION1_BIG,
     TE_EXPLOSION1_NP,
     TE_FLECHETTE
 //ROGUE
 } temp_event_t;
Function Documentation
_DotProduct()
vec_t _DotProduct (vec3_t v1, vec3_t v2)
Definition at line 727 of file q_shared.c.
 {
     return v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2];
 }
Referenced by Touch_Multi().
_VectorAdd()
void _VectorAdd (vec3_t veca, vec3_t vecb, vec3_t out)
Definition at line 739 of file q_shared.c.
 {
     out[0] = veca[0]+vecb[0];
     out[1] = veca[1]+vecb[1];
     out[2] = veca[2]+vecb[2];
 }
_VectorCopy()
void _VectorCopy (vec3_t in, vec3_t out)
Definition at line 746 of file q_shared.c.
 {
     out[0] = in[0];
     out[1] = in[1];
     out[2] = in[2];
 }
_VectorSubtract()
void _VectorSubtract (vec3_t veca, vec3_t vecb, vec3_t out)
Definition at line 732 of file q_shared.c.
 {
     out[0] = veca[0]-vecb[0];
     out[1] = veca[1]-vecb[1];
     out[2] = veca[2]-vecb[2];
 }
AddPointToBounds()
void AddPointToBounds (vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 656 of file q_shared.c.
 {
     int     i;
     vec_t   val;
     for (i=0 ; i<3 ; i++)
     {
         val = v[i];
         if (val < mins[i])
             mins[i] = val;
         if (val > maxs[i])
             maxs[i] = val;
     }
 }
Referenced by Think_SpawnDoorTrigger().
anglemod()
float anglemod (float a)
Definition at line 293 of file q_shared.c.
 {
 #if 0
     if (a >= 0)
         a -= 360*(int)(a/360);
     else
         a += 360*( 1 + (int)(-a/360) );
 #endif
     a = (360.0/65536) * ((int)(a*(65536/360.0)) & 65535);
     return a;
 }
Referenced by CL_AddPacketEntities(), FacingIdeal(), M_ChangeYaw(), and SV_NewChaseDir().
AngleVectors()
void AngleVectors (vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 93 of file q_shared.c.
 {
     float       angle;
     static float        sr, sp, sy, cr, cp, cy;
     // static to help MS compiler fp bugs
     angle = angles[YAW] * (M_PI*2 / 360);
     sy = sin(angle);
     cy = cos(angle);
     angle = angles[PITCH] * (M_PI*2 / 360);
     sp = sin(angle);
     cp = cos(angle);
     angle = angles[ROLL] * (M_PI*2 / 360);
     sr = sin(angle);
     cr = cos(angle);
     if (forward)
     {
         forward[0] = cp*cy;
         forward[1] = cp*sy;
         forward[2] = -sp;
     }
     if (right)
     {
         right[0] = (-1*sr*sp*cy+-1*cr*-sy);
         right[1] = (-1*sr*sp*sy+-1*cr*cy);
         right[2] = -1*sr*cp;
     }
     if (up)
     {
         up[0] = (cr*sp*cy+-sr*-sy);
         up[1] = (cr*sp*sy+-sr*cy);
         up[2] = cr*cp;
     }
 }
Referenced by actorMachineGun(), ai_run(), Blaster_Fire(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), Chaingun_Fire(), CheckPowerArmor(), ChickRocket(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_CalcViewValues(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_TrackerTrail(), ClientEndServerFrame(), CM_TransformedBoxTrace(), CM_TransformedPointContents(), CTFGrappleDrawCable(), CTFGrappleFire(), CTFGrapplePull(), CTFSetIDView(), Drop_Item(), fire_grenade(), fire_grenade2(), fire_hit(), fire_lead(), floater_fire_blaster(), floater_zap(), flyer_fire(), G_SetMovedir(), gib_touch(), GL_DrawAliasFrameLerp(), GladiatorGun(), GunnerFire(), GunnerGrenade(), hover_fire_blaster(), InfantryMachineGun(), infront(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), Machinegun_Fire(), makronBFG(), MakronHyperblaster(), MakronRailgun(), medic_cable_attack(), medic_fire_blaster(), mutant_jump_takeoff(), old_teleporter_touch(), parasite_drain_attack(), PM_ClampAngles(), Pmove(), R_AliasSetUpLerpData(), R_AliasSetUpTransform(), R_CullAliasModel(), R_DrawBrushModel(), R_DrawSpriteModel(), R_SetupFrame(), RotatedBBox(), soldier_fire(), SP_func_door_secret(), SpawnTech(), supertankMachineGun(), supertankRocket(), SV_Push(), TankBlaster(), TankMachineGun(), TankRocket(), Touch_Multi(), turret_breach_fire(), UpdateChaseCam(), Vk_DrawAliasFrameLerp(), weapon_bfg_fire(), weapon_grenade_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
BigFloat()
float BigFloat (float l)
Definition at line 949 of file q_shared.c.
 {return _BigFloat(l);}
BigLong()
int BigLong (int l)
Definition at line 947 of file q_shared.c.
 {return _BigLong(l);}
BigShort()
short BigShort (short l)
Definition at line 945 of file q_shared.c.
 {return _BigShort(l);}
BoxOnPlaneSide()
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s * plane)
Definition at line 349 of file q_shared.c.
 {
     float   dist1, dist2;
     int     sides;
 // fast axial cases
     if (p->type < 3)
     {
         if (p->dist <= emins[p->type])
             return 1;
         if (p->dist >= emaxs[p->type])
             return 2;
         return 3;
     }
 // general case
     switch (p->signbits)
     {
     case 0:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
         break;
     case 1:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
         break;
     case 2:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
         break;
     case 3:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
         break;
     case 4:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
         break;
     case 5:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
         break;
     case 6:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
         break;
     case 7:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
         break;
     default:
         dist1 = dist2 = 0;      // shut up compiler
         assert( 0 );
         break;
     }
     sides = 0;
     if (dist1 >= p->dist)
         sides = 1;
     if (dist2 < p->dist)
         sides |= 2;
     assert( sides != 0 );
     return sides;
 }
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 650 of file q_shared.c.
 {
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
COM_DefaultExtension()
void COM_DefaultExtension (char * path, char * extension)
Definition at line 907 of file q_shared.c.
 {
     char    *src;
 //
 // if path doesn't have a .EXT, append extension
 // (extension should include the .)
 //
     src = path + strlen(path) - 1;
     while (*src != '/' && src != path)
     {
         if (*src == '.')
             return;                 // it has an extension
         src--;
     }
     strcat (path, extension);
 }
COM_FileBase()
void COM_FileBase (char * in, char * out)
Definition at line 859 of file q_shared.c.
 {
     char *s, *s2;
     s = in + strlen(in) - 1;
     while (s != in && *s != '.')
         s--;
     for (s2 = s ; s2 != in && *s2 != '/' ; s2--)
     ;
     if (s-s2 < 2)
         out[0] = 0;
     else
     {
         s--;
         strncpy (out,s2+1, s-s2);
         out[s-s2] = 0;
     }
 }
COM_FilePath()
void COM_FilePath (char * in, char * out)
Definition at line 888 of file q_shared.c.
 {
     char *s;
     s = in + strlen(in) - 1;
     while (s != in && *s != '/')
         s--;
     strncpy (out,in, s-in);
     out[s-in] = 0;
 }
Referenced by Sys_FindFirst().
Com_PageInMemory()
void Com_PageInMemory (byte * buffer, int size)
Definition at line 1162 of file q_shared.c.
 {
     int     i;
     for (i=size-1 ; i>0 ; i-=4096)
         paged_total += buffer[i];
 }
Referenced by R_EndRegistration(), R_FreeUnusedImages(), and S_EndRegistration().
COM_Parse()
char* COM_Parse (char ** data_p)
Definition at line 1072 of file q_shared.c.
 {
     int     c;
     int     len;
     char    *data;
     data = *data_p;
     len = 0;
     com_token[0] = 0;
     if (!data)
     {
         *data_p = NULL;
         return "";
     }
 // skip whitespace
 skipwhite:
     while ( (c = *data) <= ' ')
     {
         if (c == 0)
         {
             *data_p = NULL;
             return "";
         }
         data++;
     }
 // skip // comments
     if (c=='/' && data[1] == '/')
     {
         while (*data && *data != '\n')
             data++;
         goto skipwhite;
     }
 // handle quoted strings specially
     if (c == '\"')
     {
         data++;
         while (1)
         {
             c = *data++;
             if (c=='\"' || !c)
             {
                 com_token[len] = 0;
                 *data_p = data;
                 return com_token;
             }
             if (len < MAX_TOKEN_CHARS)
             {
                 com_token[len] = c;
                 len++;
             }
         }
     }
 // parse a regular word
     do
     {
         if (len < MAX_TOKEN_CHARS)
         {
             com_token[len] = c;
             len++;
         }
         data++;
         c = *data;
     } while (c>32);
     if (len == MAX_TOKEN_CHARS)
     {
 //      Com_Printf ("Token exceeded %i chars, discarded.\n", MAX_TOKEN_CHARS);
         len = 0;
     }
     com_token[len] = 0;
     *data_p = data;
     return com_token;
 }
Referenced by Cmd_MacroExpandString(), Cmd_TokenizeString(), ED_ParseEdict(), SCR_ExecuteLayoutString(), SpawnEntities(), and StartServer_MenuInit().
Com_Printf()
void Com_Printf (char * msg, ...)
Definition at line 104 of file common.c.
 {
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     if (rd_target)
     {
         if ((strlen (msg) + strlen(rd_buffer)) > (rd_buffersize - 1))
         {
             rd_flush(rd_target, rd_buffer);
             *rd_buffer = 0;
         }
         strcat (rd_buffer, msg);
         return;
     }
     Con_Print (msg);
     // also echo to debugging console
     Sys_ConsoleOutput (msg);
     // logfile
     if (logfile_active && logfile_active->value)
     {
         char    name[MAX_QPATH];
         if (!logfile)
         {
             Com_sprintf (name, sizeof(name), "%s/qconsole.log", FS_Gamedir ());
             if (logfile_active->value > 2)
                 logfile = fopen (name, "a");
             else
                 logfile = fopen (name, "w");
         }
         if (logfile)
             fprintf (logfile, "%s", msg);
         if (logfile_active->value > 1)
             fflush (logfile);       // force it to save every time
     }
 }
Referenced by Cbuf_AddText(), CD_f(), CDAudio_Init(), CDAudio_Play2(), CL_AddEntities(), CL_Changing_f(), CL_CheckForResend(), CL_CheckOrDownloadFile(), CL_CheckPredictionError(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_Disconnect(), CL_Download_f(), CL_DumpPackets(), CL_ForwardToServer_f(), CL_KeyState(), CL_Packet_f(), CL_ParseBeam(), CL_ParseBeam2(), CL_ParseDownload(), CL_ParseFrame(), CL_ParseLightning(), CL_ParsePacketEntities(), CL_ParsePlayerBeam(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStatusMessage(), CL_PingServers_f(), CL_PredictMovement(), CL_PrepRefresh(), CL_Rcon_f(), CL_ReadPackets(), CL_Reconnect_f(), CL_Record_f(), CL_SendConnectPacket(), CL_Setenv_f(), CL_Skins_f(), CL_Stop_f(), CL_Userinfo_f(), CL_WriteConfiguration(), Cmd_AddCommand(), Cmd_Alias_f(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_ForwardToServer(), Cmd_List_f(), Cmd_MacroExpandString(), Cmd_RemoveCommand(), Com_DPrintf(), Com_Error(), Com_sprintf(), Con_Dump_f(), Con_Init(), Cvar_Command(), Cvar_Get(), Cvar_List_f(), Cvar_Set2(), Cvar_Set_f(), DS_CreateBuffers(), DumpChunks(), FS_Dir_f(), FS_Link_f(), FS_LoadPackFile(), FS_Path_f(), FS_SetGamedir(), GetWavinfo(), Huff1Decompress(), IN_StartupJoystick(), Info_Print(), Info_SetValueForKey(), Joy_AdvancedUpdate_f(), Key_Bind_f(), Key_Bindlist_f(), Key_Console(), Key_Event(), Key_Unbind_f(), KeyDown(), Master_Heartbeat(), Master_Shutdown(), Miniaudio_f(), Miniaudio_Play(), NET_GetPacket(), NET_Init(), NET_IPSocket(), NET_IPXSocket(), NET_SendPacket(), Netchan_Process(), Netchan_Transmit(), PF_cprintf(), PF_dprintf(), PrintPmove(), Qcommon_Frame(), Qcommon_Init(), S_Init(), S_IssuePlaysound(), S_LoadSound(), S_SoundInfo_f(), S_SoundList(), S_StartLocalSound(), S_Update(), SCR_CenterPrint(), SCR_LoadPCX(), SCR_PlayCinematic(), SCR_RunCinematic(), SCR_Sky_f(), SCR_TimeRefresh_f(), SCR_UpdateScreen(), SHOWNET(), SNDDMA_BeginPainting(), SNDDMA_Init(), SNDDMA_InitDirect(), SNDDMA_InitWav(), SNDDMA_Submit(), SV_AreaEdicts_r(), SV_Baselines_f(), SV_Begin_f(), SV_BroadcastPrintf(), SV_Configstrings_f(), SV_ConnectionlessPacket(), SV_DumpUser_f(), SV_ExecuteClientMessage(), SV_Frame(), SV_GameMap_f(), SV_InitGame(), SV_Kick_f(), SV_Loadgame_f(), SV_Map_f(), SV_New_f(), SV_ReadLevelFile(), SV_ReadPackets(), SV_ReadServerFile(), SV_RunGameFrame(), SV_Savegame_f(), SV_SendClientDatagram(), SV_ServerCommand_f(), SV_Serverinfo_f(), SV_ServerRecord_f(), SV_ServerStop_f(), SV_SetMaster_f(), SV_SetPlayer(), SV_SpawnServer(), SV_Status_f(), SV_WriteLevelFile(), SV_WriteServerFile(), SVC_Ack(), SVC_DirectConnect(), SVC_RemoteCommand(), SVC_Status(), SZ_GetSpace(), V_Gun_Next_f(), V_Gun_Prev_f(), V_RenderView(), V_Viewpos_f(), VID_LoadRefresh(), VID_Printf(), and Z_Stats_f().
COM_SkipPath()
char* COM_SkipPath (char * pathname)
Definition at line 807 of file q_shared.c.
 {
     char    *last;
     last = pathname;
     while (*pathname)
     {
         if (*pathname=='/')
             last = pathname+1;
         pathname++;
     }
     return last;
 }
Com_sprintf()
void Com_sprintf (char * dest, int size, char * fmt, ...)
Definition at line 1224 of file q_shared.c.
 {
     int     len;
     va_list     argptr;
     char    bigbuffer[0x10000];
     va_start (argptr,fmt);
     len = vsnprintf (bigbuffer,0x10000,fmt,argptr);
     va_end (argptr);
     if (len >= size)
         Com_Printf ("Com_sprintf: overflow of %i in %i\n", len, size);
     strncpy (dest, bigbuffer, size-1);
 }
Referenced by AddressBook_MenuInit(), AddressBook_MenuKey(), ApplyChanges(), CL_Download_f(), CL_DownloadFileName(), CL_DrawInventory(), CL_LoadClientinfo(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_PingServers_f(), CL_Record_f(), CL_RegisterTEntSounds(), CL_RequestNextDownload(), CL_WriteConfiguration(), Cmd_PlayerList_f(), Cmd_Players_f(), Cmd_Say_f(), Com_Printf(), Con_DrawConsole(), Con_Dump_f(), Create_Savestrings(), CreateTargetChangeLevel(), CTFAssignSkin(), CTFPlayerList(), Cvar_SetValue(), Cvar_WriteVariables(), DeathmatchScoreboardMessage(), DMFlagCallback(), Draw_FindPic(), ExitLevel(), FS_AddGameDirectory(), FS_Dir_f(), FS_ExecAutoexec(), FS_FOpenFile(), FS_SetGamedir(), func_clock_format_countdown(), func_clock_think(), GL_ScreenShot_f(), GLimp_EnableLogging(), HelpComputer(), Info_SetValueForKey(), InitGame(), JoinServerFunc(), Key_Event(), Keys_MenuKey(), LoadTrack(), M_DrawCursor(), Mod_LoadTexinfo(), NET_AdrToString(), PlayerConfig_MenuDraw(), PlayerConfig_MenuKey(), PlayerConfig_ScanDirectories(), QGL_Init(), R_BeginFrame(), R_BeginRegistration(), R_ScreenShot_f(), R_SetSky(), S_LoadSound(), S_RegisterSexedModel(), S_RegisterSexedSound(), SCR_DrawField(), SCR_PlayCinematic(), SCR_TouchPics(), SP_target_speaker(), StartServer_MenuInit(), SV_BeginDemoserver(), SV_CheckForSavegame(), SV_CopySaveGame(), SV_InitGame(), SV_Loadgame_f(), SV_Map_f(), SV_ReadLevelFile(), SV_ReadServerFile(), SV_ServerRecord_f(), SV_SpawnServer(), SV_StatusString(), SV_WipeSavegame(), SV_WriteLevelFile(), SV_WriteServerFile(), SVC_Info(), Sys_FindFirst(), Sys_FindNext(), Sys_GetGameAPI(), V_Gun_Model_f(), VID_CheckChanges(), Vk_ScreenShot_f(), Vkimp_EnableLogging(), and vtos().
COM_StripExtension()
void COM_StripExtension (char * in, char * out)
Definition at line 826 of file q_shared.c.
 {
     while (*in && *in != '.')
         *out++ = *in++;
     *out = 0;
 }
CrossProduct()
void CrossProduct (vec3_t v1, vec3_t v2, vec3_t cross)
Definition at line 753 of file q_shared.c.
 {
     cross[0] = v1[1]*v2[2] - v1[2]*v2[1];
     cross[1] = v1[2]*v2[0] - v1[0]*v2[2];
     cross[2] = v1[0]*v2[1] - v1[1]*v2[0];
 }
Referenced by MakeNormalVectors(), PM_StepSlideMove_(), R_IMFlatShadedQuad(), RotatePointAroundVector(), and SV_FlyMove().
Hunk_Alloc()
void* Hunk_Alloc (int size)
Definition at line 57 of file q_shwin.c.
 {
     void    *buf;
     // round to cacheline
     size = (size+31)&~31;
 #ifdef VIRTUAL_ALLOC
     // commit pages as needed
 //  buf = VirtualAlloc (membase+cursize, size, MEM_COMMIT, PAGE_READWRITE);
     buf = VirtualAlloc (membase, cursize+size, MEM_COMMIT, PAGE_READWRITE);
     if (!buf)
     {
         FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM, NULL, GetLastError(), MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPTSTR) &buf, 0, NULL);
         Sys_Error ("VirtualAlloc commit failed.\n%s", buf);
     }
 #endif
     cursize += size;
     if (cursize > hunkmaxsize)
         Sys_Error ("Hunk_Alloc overflow");
     return (void *)(membase+cursize-size);
 }
Hunk_Begin()
void* Hunk_Begin (int maxsize)
Definition at line 41 of file q_shwin.c.
 {
     // reserve a huge chunk of memory, but don't commit any yet
     cursize = 0;
     hunkmaxsize = maxsize;
 #ifdef VIRTUAL_ALLOC
     membase = VirtualAlloc (NULL, maxsize, MEM_RESERVE, PAGE_NOACCESS);
 #else
     membase = malloc (maxsize);
     memset (membase, 0, maxsize);
 #endif
     if (!membase)
         Sys_Error ("VirtualAlloc reserve failed");
     return (void *)membase;
 }
Hunk_End()
int Hunk_End (void)
Definition at line 81 of file q_shwin.c.
 {
     // free the remaining unused virtual memory
 #if 0
     void    *buf;
     // write protect it
     buf = VirtualAlloc (membase, cursize, MEM_COMMIT, PAGE_READONLY);
     if (!buf)
         Sys_Error ("VirtualAlloc commit failed");
 #endif
     hunkcount++;
 //Com_Printf ("hunkcount: %i\n", hunkcount);
     return cursize;
 }
Hunk_Free()
void Hunk_Free (void * buf)
Definition at line 99 of file q_shwin.c.
 {
     if ( base )
 #ifdef VIRTUAL_ALLOC
         VirtualFree (base, 0, MEM_RELEASE);
 #else
         free (base);
 #endif
     hunkcount--;
 }
Info_RemoveKey()
void Info_RemoveKey (char * s, char * key)
Definition at line 1296 of file q_shared.c.
 {
     char    *start;
     char    pkey[512];
     char    value[512];
     char    *o;
     if (strstr (key, "\\"))
     {
 //      Com_Printf ("Can't use a key with a \\\n");
         return;
     }
     while (1)
     {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\')
         {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value;
         while (*s != '\\' && *s)
         {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp (key, pkey) )
         {
             strcpy (start, s);  // remove this part
             return;
         }
         if (!*s)
             return;
     }
 }
Referenced by Info_SetValueForKey().
Info_SetValueForKey()
void Info_SetValueForKey (char * s, char * key, char * value)
Definition at line 1363 of file q_shared.c.
 {
     char    newi[MAX_INFO_STRING], *v;
     int     c;
     int     maxsize = MAX_INFO_STRING;
     if (strstr (key, "\\") || strstr (value, "\\") )
     {
         Com_Printf ("Can't use keys or values with a \\\n");
         return;
     }
     if (strstr (key, ";") )
     {
         Com_Printf ("Can't use keys or values with a semicolon\n");
         return;
     }
     if (strstr (key, "\"") || strstr (value, "\"") )
     {
         Com_Printf ("Can't use keys or values with a \"\n");
         return;
     }
     if (strlen(key) > MAX_INFO_KEY-1 || strlen(value) > MAX_INFO_KEY-1)
     {
         Com_Printf ("Keys and values must be < 64 characters.\n");
         return;
     }
     Info_RemoveKey (s, key);
     if (!value || !strlen(value))
         return;
     Com_sprintf (newi, sizeof(newi), "\\%s\\%s", key, value);
     if (strlen(newi) + strlen(s) > maxsize)
     {
         Com_Printf ("Info string length exceeded\n");
         return;
     }
     // only copy ascii values
     s += strlen(s);
     v = newi;
     while (*v)
     {
         c = *v++;
         c &= 127;       // strip high bits
         if (c >= 32 && c < 127)
             *s++ = c;
     }
     *s = 0;
 }
Referenced by ClientConnect(), Cvar_BitInfo(), and SVC_DirectConnect().
Info_Validate()
qboolean Info_Validate (char * s)
Definition at line 1354 of file q_shared.c.
 {
     if (strstr (s, "\""))
         return false;
     if (strstr (s, ";"))
         return false;
     return true;
 }
Referenced by ClientUserinfoChanged().
Info_ValueForKey()
char* Info_ValueForKey (char * s, char * key)
Definition at line 1254 of file q_shared.c.
 {
     char    pkey[512];
     static  char value[2][512]; // use two buffers so compares
                                 // work without stomping on each other
     static  int valueindex;
     char    *o;
     valueindex ^= 1;
     if (*s == '\\')
         s++;
     while (1)
     {
         o = pkey;
         while (*s != '\\')
         {
             if (!*s)
                 return "";
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value[valueindex];
         while (*s != '\\' && *s)
         {
             if (!*s)
                 return "";
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp (key, pkey) )
             return value[valueindex];
         if (!*s)
             return "";
         s++;
     }
 }
Referenced by ClientConnect(), ClientTeam(), ClientUserinfoChanged(), CTFJoinTeam(), CTFTeam_f(), IsFemale(), IsNeutral(), PutClientInServer(), spectator_respawn(), SV_UserinfoChanged(), and SVC_DirectConnect().
LerpAngle()
float LerpAngle (float a1, float a2, float frac)
Definition at line 283 of file q_shared.c.
 {
     if (a1 - a2 > 180)
         a1 -= 360;
     if (a1 - a2 < -180)
         a1 += 360;
     return a2 + frac * (a1 - a2);
 }
Referenced by CL_AddPacketEntities(), CL_AddViewWeapon(), and CL_CalcViewValues().
LittleFloat()
float LittleFloat (float l)
Definition at line 950 of file q_shared.c.
 {return _LittleFloat(l);}
LittleLong()
int LittleLong (int l)
Definition at line 948 of file q_shared.c.
 {return _LittleLong(l);}
LittleShort()
short LittleShort (short l)
Definition at line 946 of file q_shared.c.
 {return _LittleShort(l);}
PerpendicularVector()
void PerpendicularVector (vec3_t dst, const vec3_t src)
Definition at line 152 of file q_shared.c.
 {
     int pos;
     int i;
     float minelem = 1.0F;
     vec3_t tempvec;
     /*
     ** find the smallest magnitude axially aligned vector
     */
     for ( pos = 0, i = 0; i < 3; i++ )
     {
         if ( fabs( src[i] ) < minelem )
         {
             pos = i;
             minelem = fabs( src[i] );
         }
     }
     tempvec[0] = tempvec[1] = tempvec[2] = 0.0F;
     tempvec[pos] = 1.0F;
     /*
     ** project the point onto the plane defined by src
     */
     ProjectPointOnPlane( dst, tempvec, src );
     /*
     ** normalize the result
     */
     VectorNormalize( dst );
 }
Referenced by R_DrawBeam(), and RotatePointAroundVector().
ProjectPointOnPlane()
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
Definition at line 130 of file q_shared.c.
 {
     float d;
     vec3_t n;
     float inv_denom;
     inv_denom = 1.0F / DotProduct( normal, normal );
     d = DotProduct( normal, p ) * inv_denom;
     n[0] = normal[0] * inv_denom;
     n[1] = normal[1] * inv_denom;
     n[2] = normal[2] * inv_denom;
     dst[0] = p[0] - d * n[0];
     dst[1] = p[1] - d * n[1];
     dst[2] = p[2] - d * n[2];
 }
Referenced by PerpendicularVector().
Q_ftol()
long Q_ftol (float f)
Q_log2()
int Q_log2 (int val)
Definition at line 790 of file q_shared.c.
 {
     int answer=0;
     while (val>>=1)
         answer++;
     return answer;
 }
Q_strcasecmp()
int Q_strcasecmp (char * s1, char * s2)
Definition at line 1217 of file q_shared.c.
 {
     return Q_strncasecmp (s1, s2, 99999);
 }
Referenced by CD_f(), CL_AddPacketEntities(), Cmd_ExecuteString(), FS_FOpenFile(), Key_StringToKeynum(), and Miniaudio_f().
Q_stricmp()
int Q_stricmp (char * s1, char * s2)
Definition at line 1181 of file q_shared.c.
 {
 #if defined(WIN32)
     return _stricmp (s1, s2);
 #else
     return strcasecmp (s1, s2);
 #endif
 }
Referenced by CheckNeedPass(), CL_DrawInventory(), CL_FixUpGender(), CL_LoadClientinfo(), ClientCommand(), Cmd_Drop_f(), Cmd_Give_f(), CTFTeam_f(), CTFUpdateJoinMenu(), CTFWarp(), door_use_areaportals(), ED_ParseField(), EndDMLevel(), FindItem(), FindItemByClassname(), G_Find(), G_UseTargets(), GL_TextureAlphaMode(), GL_TextureMode(), GL_TextureSolidMode(), JoinServerFunc(), Miniaudio_Play(), PlayerConfig_MenuInit(), R_BeginFrame(), SelectCoopSpawnPoint(), SelectSpawnPoint(), ServerCommand(), SP_CreateCoopSpots(), SP_FixCoopSpots(), SP_info_player_coop(), SP_info_player_start(), SP_monster_flyer(), SP_target_changelevel(), SP_target_secret(), SpawnEntities(), StartServerActionFunc(), SV_Map(), VID_MenuInit(), Vk_LmapTextureMode(), Vk_TextureMode(), and Weapon_Generic().
Q_strncasecmp()
int Q_strncasecmp (char * s1, char * s2, int n)
Definition at line 1191 of file q_shared.c.
 {
     int     c1, c2;
     do
     {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--)
             return 0;       // strings are equal until end point
         if (c1 != c2)
         {
             if (c1 >= 'a' && c1 <= 'z')
                 c1 -= ('a' - 'A');
             if (c2 >= 'a' && c2 <= 'z')
                 c2 -= ('a' - 'A');
             if (c1 != c2)
                 return -1;      // strings not equal
         }
     } while (c1);
     return 0;       // strings are equal
 }
Referenced by Q_strcasecmp().
R_ConcatRotations()
void R_ConcatRotations (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 191 of file q_shared.c.
 {
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
                 in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
                 in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
                 in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
                 in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
                 in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
                 in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
                 in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
                 in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
                 in1[2][2] * in2[2][2];
 }
Referenced by R_RotateBmodel(), and RotatePointAroundVector().
R_ConcatTransforms()
void R_ConcatTransforms (float in1[3][4], float in2[3][4], float out[3][4])
Definition at line 219 of file q_shared.c.
 {
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
                 in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
                 in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
                 in1[0][2] * in2[2][2];
     out[0][3] = in1[0][0] * in2[0][3] + in1[0][1] * in2[1][3] +
                 in1[0][2] * in2[2][3] + in1[0][3];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
                 in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
                 in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
                 in1[1][2] * in2[2][2];
     out[1][3] = in1[1][0] * in2[0][3] + in1[1][1] * in2[1][3] +
                 in1[1][2] * in2[2][3] + in1[1][3];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
                 in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
                 in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
                 in1[2][2] * in2[2][2];
     out[2][3] = in1[2][0] * in2[0][3] + in1[2][1] * in2[1][3] +
                 in1[2][2] * in2[2][3] + in1[2][3];
 }
Referenced by R_AliasSetUpTransform().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 32 of file q_shared.c.
 {
     float   m[3][3];
     float   im[3][3];
     float   zrot[3][3];
     float   tmpmat[3][3];
     float   rot[3][3];
     int i;
     vec3_t vr, vup, vf;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector( vr, dir );
     CrossProduct( vr, vf, vup );
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy( im, m, sizeof( im ) );
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset( zrot, 0, sizeof( zrot ) );
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     zrot[0][0] = cos( DEG2RAD( degrees ) );
     zrot[0][1] = sin( DEG2RAD( degrees ) );
     zrot[1][0] = -sin( DEG2RAD( degrees ) );
     zrot[1][1] = cos( DEG2RAD( degrees ) );
     R_ConcatRotations( m, zrot, tmpmat );
     R_ConcatRotations( tmpmat, im, rot );
     for ( i = 0; i < 3; i++ )
     {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
Referenced by R_DrawBeam(), and R_SetFrustum().
Swap_Init()
void Swap_Init (void)
Definition at line 1011 of file q_shared.c.
 {
     byte    swaptest[2] = {1,0};
 // set the byte swapping variables in a portable manner
     if ( *(short *)swaptest == 1)
     {
         bigendien = false;
         _BigShort = ShortSwap;
         _LittleShort = ShortNoSwap;
         _BigLong = LongSwap;
         _LittleLong = LongNoSwap;
         _BigFloat = FloatSwap;
         _LittleFloat = FloatNoSwap;
     }
     else
     {
         bigendien = true;
         _BigShort = ShortNoSwap;
         _LittleShort = ShortSwap;
         _BigLong = LongNoSwap;
         _LittleLong = LongSwap;
         _BigFloat = FloatNoSwap;
         _LittleFloat = FloatSwap;
     }
 }
Referenced by GetRefAPI(), and Qcommon_Init().
Sys_Error()
void Sys_Error (char * error, ...)
Definition at line 68 of file sys_win.c.
 {
     va_list     argptr;
     char        text[1024];
     CL_Shutdown ();
     Qcommon_Shutdown ();
     va_start (argptr, error);
     vsnprintf (text, 1024, error, argptr);
     va_end (argptr);
     MessageBox(NULL, text, "Error", 0 /* MB_OK */ );
     if (qwclsemaphore)
         CloseHandle (qwclsemaphore);
 // shut down QHOST hooks if necessary
     DeinitConProc ();
     exit (1);
 }
Referenced by Sys_ConsoleInput(), and Sys_Init().
Sys_FindClose()
void Sys_FindClose (void)
Definition at line 206 of file q_shwin.c.
 {
     if (findhandle != -1)
         _findclose (findhandle);
     findhandle = 0;
 }
Referenced by FS_ExecAutoexec(), FS_ListFiles(), PlayerConfig_ScanDirectories(), SV_CopySaveGame(), and SV_WipeSavegame().
Sys_FindFirst()
char* Sys_FindFirst (char * path, unsigned musthave, unsigned canthave)
Definition at line 173 of file q_shwin.c.
 {
     struct _finddata_t findinfo;
     if (findhandle)
         Sys_Error ("Sys_BeginFind without close");
     findhandle = 0;
     COM_FilePath (path, findbase);
     findhandle = _findfirst (path, &findinfo);
     if (findhandle == -1)
         return NULL;
     if ( !CompareAttributes( findinfo.attrib, musthave, canthave ) )
         return NULL;
     Com_sprintf (findpath, sizeof(findpath), "%s/%s", findbase, findinfo.name);
     return findpath;
 }
Referenced by FS_ExecAutoexec(), FS_ListFiles(), PlayerConfig_ScanDirectories(), SV_CopySaveGame(), and SV_WipeSavegame().
Sys_FindNext()
char* Sys_FindNext (unsigned musthave, unsigned canthave)
Definition at line 191 of file q_shwin.c.
 {
     struct _finddata_t findinfo;
     if (findhandle == -1)
         return NULL;
     if (_findnext (findhandle, &findinfo) == -1)
         return NULL;
     if ( !CompareAttributes( findinfo.attrib, musthave, canthave ) )
         return NULL;
     Com_sprintf (findpath, sizeof(findpath), "%s/%s", findbase, findinfo.name);
     return findpath;
 }
Referenced by FS_ListFiles(), SV_CopySaveGame(), and SV_WipeSavegame().
Sys_Milliseconds()
int Sys_Milliseconds (void)
Definition at line 120 of file q_shwin.c.
 {
     static int      base;
     static qboolean initialized = false;
     if (!initialized)
     {   // let base retain 16 bits of effectively random data
         base = timeGetTime() & 0xffff0000;
         initialized = true;
     }
     curtime = timeGetTime() - base;
     return curtime;
 }
Referenced by CL_Disconnect(), CL_Frame(), CL_InitLocal(), Field_Draw(), KeyCursorDrawFunc(), Menu_Draw(), Netchan_Init(), Qcommon_Frame(), R_EdgeDrawing(), R_PrintDSpeeds(), R_PrintTimes(), R_RenderFrame(), SCR_BeginLoadingPlaque(), SCR_PlayCinematic(), SCR_TimeRefresh_f(), SCR_UpdateScreen(), SV_RunGameFrame(), V_RenderView(), and WinMain().
Sys_Mkdir()
void Sys_Mkdir (char * path)
Definition at line 135 of file q_shwin.c.
 {
     _mkdir (path);
 }
Referenced by FS_CreatePath(), GL_ScreenShot_f(), R_ScreenShot_f(), and Vk_ScreenShot_f().
va()
char* va (char * format, ...)
Definition at line 1050 of file q_shared.c.
 {
     va_list     argptr;
     static char     string[1024];
     va_start (argptr, format);
     vsnprintf (string, 1024, format,argptr);
     va_end (argptr);
     return string;
 }
Referenced by Cbuf_AddEarlyCommands(), CheckNeedPass(), CL_CheckOrDownloadFile(), CL_Connect_f(), CL_Download_f(), CL_PingServers_f(), CL_RequestNextDownload(), ClientUserinfoChanged(), Cmd_ExecuteString(), Com_Error(), CreateDynamicBuffers(), CreateFramebuffers(), CreateImageViews(), CreateStagingBuffers(), CTFAssignSkin(), FS_InitFilesystem(), FS_SetGamedir(), insane_die(), insane_pain(), LM_UploadBlock(), LoadGameCallback(), NET_OpenIP(), NET_OpenIPX(), Netchan_Init(), P_DamageFeedback(), player_die(), Qcommon_Frame(), Qcommon_Init(), QVk_GetIndexBuffer(), QVk_GetUniformBuffer(), QVk_GetVertexBuffer(), QVk_Init(), SaveGameCallback(), SCR_ExecuteLayoutString(), SCR_FinishCinematic(), SP_worldspawn(), SpawnEntities(), StartServerActionFunc(), SV_Baselines_f(), SV_Configstrings_f(), SV_GameMap_f(), SV_Init(), SV_InitGame(), SV_Map(), SV_New_f(), Vk_BeginBuildingLightmaps(), and Vk_LoadPic().
VectorCompare()
int VectorCompare (vec3_t v1, vec3_t v2)
Definition at line 672 of file q_shared.c.
 {
     if (v1[0] != v2[0] || v1[1] != v2[1] || v1[2] != v2[2])
             return 0;
     return 1;
 }
Referenced by AngleMove_Final(), CL_AddPlayerBeams(), door_secret_use(), fire_lead(), G_SetMovedir(), InitTrigger(), rotating_use(), SP_trigger_multiple(), SV_FlyMove(), target_laser_think(), and Touch_Multi().
VectorInverse()
void VectorInverse (vec3_t v)
Definition at line 775 of file q_shared.c.
 {
     v[0] = -v[0];
     v[1] = -v[1];
     v[2] = -v[2];
 }
Referenced by R_AliasSetUpTransform(), and R_DrawSprite().
VectorLength()
vec_t VectorLength (vec3_t v)
Definition at line 762 of file q_shared.c.
 {
     int     i;
     float   length;
     length = 0;
     for (i=0 ; i< 3 ; i++)
         length += v[i]*v[i];
     length = sqrt (length);     // FIXME
     return length;
 }
Referenced by ai_run(), AngleMove_Begin(), bfg_explode(), boss2_attack(), check_dodge(), CL_AddPlayerBeams(), CL_BfgParticles(), CTFFragBonuses(), CTFGrappleDrawCable(), CTFGrapplePull(), CTFSay_Team_Location(), findradius(), FindTarget(), fire_hit(), gladiator_attack(), Grenade_Explode(), jorg_attack(), loc_findradius(), makron_attack(), medic_cable_attack(), Mod_LoadTexinfo(), mutant_check_jump(), mutant_jump_touch(), parasite_drain_attack_ok(), PlayersRangeFromSpot(), PM_DeadMove(), PM_FlyMove(), R_LightPoint(), R_LightPointColor(), R_RenderDlight(), RadiusFromBounds(), range(), SP_FixCoopSpots(), supertank_attack(), SV_BuildClientFrame(), T_RadiusDamage(), tank_attack(), and turret_driver_link().
VectorMA()
void VectorMA (vec3_t veca, float scale, vec3_t vecb, vec3_t vecc)
Definition at line 719 of file q_shared.c.
 {
     vecc[0] = veca[0] + scale*vecb[0];
     vecc[1] = veca[1] + scale*vecb[1];
     vecc[2] = veca[2] + scale*vecb[2];
 }
Referenced by actorMachineGun(), barrel_explode(), bfg_explode(), bfg_think(), bfg_touch(), boss2_firebullet_left(), boss2_firebullet_right(), check_dodge(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_Heatbeam(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_ParseMuzzleFlash(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_RailTrail(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_Widowbeamout(), CL_WidowSplash(), CTFFireGrapple(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_hit(), fire_lead(), fire_rail(), Grenade_Explode(), GunnerFire(), InfantryMachineGun(), jorg_firebullet_left(), jorg_firebullet_right(), MakeNormalVectors(), MakronSpawn(), medic_cable_attack(), mutant_jump_touch(), P_DamageFeedback(), PM_AddCurrents(), PM_CheckSpecialMovement(), PM_FlyMove(), R_DrawSpriteModel(), R_LightPoint(), R_LightPointColor(), RecursiveLightPoint(), rocket_touch(), RotatedBBox(), soldier_fire(), SP_func_button(), SP_func_door(), SP_func_door_rotating(), SP_func_door_secret(), SP_func_water(), SP_trigger_once(), supertankMachineGun(), SV_AddRotationalFriction(), SV_Physics_Noclip(), SV_Physics_Toss(), T_RadiusDamage(), target_laser_think(), ThrowDebris(), ThrowGib(), ThrowHead(), turret_breach_fire(), and UpdateChaseCam().
VectorNormalize()
vec_t VectorNormalize (vec3_t v)
Definition at line 681 of file q_shared.c.
 {
     float   length, ilength;
     length = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
     length = sqrt (length);     // FIXME
     if (length)
     {
         ilength = 1/length;
         v[0] *= ilength;
         v[1] *= ilength;
         v[2] *= ilength;
     }
     return length;
 }
Referenced by actorMachineGun(), bfg_think(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), CheckPowerArmor(), ChickRocket(), CL_AddBeams(), CL_AddPlayerBeams(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DebugTrail(), CL_DiminishingTrail(), CL_FlagTrail(), CL_ForceWall(), CL_Heatbeam(), CL_IonripperTrail(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_TrapParticles(), CL_Widowbeamout(), CL_WidowSplash(), CTFFireGrapple(), CTFGrapplePull(), CTFSetIDView(), fire_blaster(), fire_hit(), fire_lead(), func_explosive_explode(), GladiatorGun(), GunnerFire(), InfantryMachineGun(), infront(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), MakeNormalVectors(), makronBFG(), MakronRailgun(), MakronSpawn(), Mat_Rotate(), Move_Calc(), mutant_jump_touch(), P_DamageFeedback(), PerpendicularVector(), PM_AirMove(), PM_CheckSpecialMovement(), PM_DeadMove(), PM_FlyMove(), PM_StepSlideMove_(), PM_WaterMove(), R_DrawAliasModel(), R_DrawBeam(), R_IMFlatShadedQuad(), R_SetFrustum(), R_ViewChanged(), S_SpatializeOrigin(), soldier_fire(), supertankMachineGun(), supertankRocket(), T_Damage(), TankRocket(), target_laser_think(), and UpdateChaseCam().
VectorNormalize2()
vec_t VectorNormalize2 (vec3_t v, vec3_t out)
Definition at line 700 of file q_shared.c.
 {
     float   length, ilength;
     length = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
     length = sqrt (length);     // FIXME
     if (length)
     {
         ilength = 1/length;
         out[0] = v[0]*ilength;
         out[1] = v[1]*ilength;
         out[2] = v[2]*ilength;
     }
     return length;
 }
VectorScale()
void VectorScale (vec3_t in, vec_t scale, vec3_t out)
Definition at line 782 of file q_shared.c.
 {
     out[0] = in[0]*scale;
     out[1] = in[1]*scale;
     out[2] = in[2]*scale;
 }
Referenced by AngleMove_Begin(), AngleMove_Final(), Blaster_Fire(), CanDamage(), CL_AddPlayerBeams(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DebugTrail(), CL_DiminishingTrail(), CL_FlagTrail(), CL_ForceWall(), CL_Heatbeam(), CL_IonripperTrail(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_TrackerTrail(), CL_TrapParticles(), CTFFireGrapple(), CTFGrappleFire(), CTFGrapplePull(), CTFSetIDView(), D_CalcGradients(), Drop_Item(), fire_bfg(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_lead(), fire_rocket(), func_explosive_explode(), GL_DrawParticles(), misc_viper_bomb_prethink(), misc_viper_bomb_use(), Move_Begin(), Move_Final(), mutant_jump_takeoff(), old_teleporter_touch(), PM_AirMove(), PM_CheckSpecialMovement(), PM_DeadMove(), PM_FlyMove(), PM_StepSlideMove_(), PM_WaterMove(), R_DrawBeam(), R_DrawParticles(), R_DrawSprite(), R_LightPoint(), R_LightPointColor(), RotatedBBox(), rotating_use(), SP_target_spawner(), SpawnTech(), SubdividePolygon(), SV_FlyMove(), SV_Physics_Pusher(), SV_Physics_Toss(), T_Damage(), Think_AccelMove(), ThrowGib(), trigger_push_touch(), turret_breach_think(), V_RenderView(), VelocityForDamage(), Vk_DrawParticles(), weapon_bfg_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
Variable Documentation
curtime
int curtime
Definition at line 119 of file q_shwin.c.
Referenced by CL_Frame(), CL_SendCmd(), Netchan_Process(), Netchan_Setup(), Netchan_Transmit(), SV_SendClientMessages(), SVC_GetChallenge(), and Sys_Milliseconds().
monster_flash_offset
vec3_t monster_flash_offset[]
Definition at line 27 of file m_flash.c.
vec3_origin
vec3_t vec3_origin
Definition at line 24 of file q_shared.c.
Referenced by AngleMove_Final(), bfg_explode(), bfg_think(), blaster_touch(), CanDamage(), CL_AddPlayerBeams(), CL_ClipMoveToEntities(), CL_ParseMuzzleFlash2(), CL_WidowSplash(), Cmd_Kill_f(), CTFGrapplePull(), CTFGrappleTouch(), CTFTeam_f(), CTFWeapon_Grapple_Fire(), D_DrawSurfaces(), door_blocked(), door_secret_blocked(), door_secret_move6(), door_secret_use(), DrawSkyPolygon(), fire_hit(), floater_zap(), func_explosive_use(), func_object_touch(), Grenade_Explode(), hurt_touch(), InitTrigger(), KillBox(), loc_CanSee(), M_CheckBottom(), M_WorldEffects(), MakronSpawn(), P_FallingDamage(), P_WorldEffects(), parasite_drain_attack(), PF_Configstring(), plat_blocked(), PM_FlyMove(), PM_StepSlideMove_(), R_BuildPolygonFromSurface(), R_DrawEntitiesOnList(), R_LightPoint(), R_LightPointColor(), RecursiveLightPoint(), RecursiveLightPointColor(), rotating_blocked(), rotating_touch(), rotating_use(), SP_trigger_multiple(), SV_ClipMoveToEntities(), SV_FindIndex(), SV_FlyMove(), SV_Physics_Toss(), SV_PointContents(), SV_Push(), SV_Trace(), T_RadiusDamage(), target_laser_think(), Touch_Multi(), train_blocked(), turret_blocked(), UpdateChaseCam(), use_target_changelevel(), visible(), and Weapon_Blaster_Fire().
vidref_val
int vidref_val
Definition at line 28 of file cl_ents.c.
Referenced by CL_AddPacketEntities().