vkQuake2 doxygen: C:/entry/dev/vq2/src/client/sound.h File Reference
sound.h File Reference
Functions
void S_Init (void)
void S_Shutdown (void)
void S_StartSound (vec3_t origin, int entnum, int entchannel, struct sfx_s *sfx, float fvol, float attenuation, float timeofs)
void S_StartLocalSound (char *s)
void S_RawSamples (int samples, int rate, int width, int channels, byte *data)
void S_StopAllSounds (void)
void S_Update (vec3_t origin, vec3_t v_forward, vec3_t v_right, vec3_t v_up)
void S_Activate (qboolean active)
void S_BeginRegistration (void)
struct sfx_s * S_RegisterSound (char *sample)
void S_EndRegistration (void)
struct sfx_s * S_FindName (char *name, qboolean create)
void CL_GetEntitySoundOrigin (int ent, vec3_t org)
Function Documentation
CL_GetEntitySoundOrigin()
void CL_GetEntitySoundOrigin (int ent, vec3_t org)
Definition at line 1529 of file cl_ents.c.
 {
     centity_t   *old;
     if (ent < 0 || ent >= MAX_EDICTS)
         Com_Error (ERR_DROP, "CL_GetEntitySoundOrigin: bad ent");
     old = &cl_entities[ent];
     VectorCopy (old->lerp_origin, org);
     // FIXME: bmodel issues...
 }
Referenced by S_Spatialize().
S_Activate()
void S_Activate (qboolean active)
Definition at line 844 of file snd_win.c.
 {
     if ( active )
     {
         if ( pDS && cl_hwnd && snd_isdirect )
         {
             DS_CreateBuffers();
         }
     }
     else
     {
         if ( pDS && cl_hwnd && snd_isdirect )
         {
             DS_DestroyBuffers();
         }
     }
 }
Referenced by AppActivate().
S_BeginRegistration()
void S_BeginRegistration (void)
Definition at line 293 of file snd_dma.c.
 {
     s_registration_sequence++;
     s_registering = true;
 }
Referenced by CL_RegisterSounds().
S_EndRegistration()
void S_EndRegistration (void)
Definition at line 328 of file snd_dma.c.
 {
     int     i;
     sfx_t   *sfx;
     int     size;
     // free any sounds not from this registration sequence
     for (i=0, sfx=known_sfx ; i < num_sfx ; i++,sfx++)
     {
         if (!sfx->name[0])
             continue;
         if (sfx->registration_sequence != s_registration_sequence)
         {   // don't need this sound
             if (sfx->cache) // it is possible to have a leftover
                 Z_Free (sfx->cache);    // from a server that didn't finish loading
             memset (sfx, 0, sizeof(*sfx));
         }
         else
         {   // make sure it is paged in
             if (sfx->cache)
             {
                 size = sfx->cache->length*sfx->cache->width;
                 Com_PageInMemory ((byte *)sfx->cache, size);
             }
         }
     }
     // load everything in
     for (i=0, sfx=known_sfx ; i < num_sfx ; i++,sfx++)
     {
         if (!sfx->name[0])
             continue;
         S_LoadSound (sfx);
     }
     s_registering = false;
 }
Referenced by CL_RegisterSounds().
S_FindName()
struct sfx_s* S_FindName (char * name, qboolean create)
Definition at line 205 of file snd_dma.c.
 {
     int     i;
     sfx_t   *sfx;
     if (!name)
         Com_Error (ERR_FATAL, "S_FindName: NULL\n");
     if (!name[0])
         Com_Error (ERR_FATAL, "S_FindName: empty name\n");
     if (strlen(name) >= MAX_QPATH)
         Com_Error (ERR_FATAL, "Sound name too long: %s", name);
     // see if already loaded
     for (i=0 ; i < num_sfx ; i++)
         if (!strcmp(known_sfx[i].name, name))
         {
             return &known_sfx[i];
         }
     if (!create)
         return NULL;
     // find a free sfx
     for (i=0 ; i < num_sfx ; i++)
         if (!known_sfx[i].name[0])
 //          registration_sequence < s_registration_sequence)
             break;
     if (i == num_sfx)
     {
         if (num_sfx == MAX_SFX)
             Com_Error (ERR_FATAL, "S_FindName: out of sfx_t");
         num_sfx++;
     }
     sfx = &known_sfx[i];
     memset (sfx, 0, sizeof(*sfx));
     strcpy (sfx->name, name);
     sfx->registration_sequence = s_registration_sequence;
     return sfx;
 }
Referenced by S_RegisterSexedSound(), and S_RegisterSound().
S_Init()
void S_Init (void)
Definition at line 116 of file snd_dma.c.
 {
     cvar_t  *cv;
     Com_Printf("\n------- sound initialization -------\n");
     cv = Cvar_Get ("s_initsound", "1", 0);
     if (!cv->value)
         Com_Printf ("not initializing.\n");
     else
     {
         s_volume = Cvar_Get ("s_volume", "0.7", CVAR_ARCHIVE);
         s_khz = Cvar_Get ("s_khz", "11", CVAR_ARCHIVE);
         s_loadas8bit = Cvar_Get ("s_loadas8bit", "1", CVAR_ARCHIVE);
         s_mixahead = Cvar_Get ("s_mixahead", "0.2", CVAR_ARCHIVE);
         s_show = Cvar_Get ("s_show", "0", 0);
         s_testsound = Cvar_Get ("s_testsound", "0", 0);
         s_primary = Cvar_Get ("s_primary", "0", CVAR_ARCHIVE);  // win32 specific
         Cmd_AddCommand("play", S_Play);
         Cmd_AddCommand("stopsound", S_StopAllSounds);
         Cmd_AddCommand("soundlist", S_SoundList);
         Cmd_AddCommand("soundinfo", S_SoundInfo_f);
         if (!SNDDMA_Init())
             return;
         S_InitScaletable ();
         sound_started = 1;
         num_sfx = 0;
         soundtime = 0;
         paintedtime = 0;
         Com_Printf ("sound sampling rate: %i\n", dma.speed);
         S_StopAllSounds ();
     }
     Com_Printf("------------------------------------\n");
 }
Referenced by CL_Init(), and CL_Snd_Restart_f().
S_RawSamples()
void S_RawSamples (int samples, int rate, int width, int channels, byte * data)
Definition at line 910 of file snd_dma.c.
 {
     int     i;
     int     src, dst;
     float   scale;
     if (!sound_started)
         return;
     if (s_rawend < paintedtime)
         s_rawend = paintedtime;
     scale = (float)rate / dma.speed;
 //Com_Printf ("%i < %i < %i\n", soundtime, paintedtime, s_rawend);
     if (channels == 2 && width == 2)
     {
         if (scale == 1.0)
         {   // optimized case
             for (i=0 ; i<samples ; i++)
             {
                 dst = s_rawend&(MAX_RAW_SAMPLES-1);
                 s_rawend++;
                 s_rawsamples[dst].left =
                     LittleShort(((short *)data)[i*2]) << 8;
                 s_rawsamples[dst].right =
                     LittleShort(((short *)data)[i*2+1]) << 8;
             }
         }
         else
         {
             for (i=0 ; ; i++)
             {
                 src = i*scale;
                 if (src >= samples)
                     break;
                 dst = s_rawend&(MAX_RAW_SAMPLES-1);
                 s_rawend++;
                 s_rawsamples[dst].left =
                     LittleShort(((short *)data)[src*2]) << 8;
                 s_rawsamples[dst].right =
                     LittleShort(((short *)data)[src*2+1]) << 8;
             }
         }
     }
     else if (channels == 1 && width == 2)
     {
         for (i=0 ; ; i++)
         {
             src = i*scale;
             if (src >= samples)
                 break;
             dst = s_rawend&(MAX_RAW_SAMPLES-1);
             s_rawend++;
             s_rawsamples[dst].left =
                 LittleShort(((short *)data)[src]) << 8;
             s_rawsamples[dst].right =
                 LittleShort(((short *)data)[src]) << 8;
         }
     }
     else if (channels == 2 && width == 1)
     {
         for (i=0 ; ; i++)
         {
             src = i*scale;
             if (src >= samples)
                 break;
             dst = s_rawend&(MAX_RAW_SAMPLES-1);
             s_rawend++;
             s_rawsamples[dst].left =
                 ((char *)data)[src*2] << 16;
             s_rawsamples[dst].right =
                 ((char *)data)[src*2+1] << 16;
         }
     }
     else if (channels == 1 && width == 1)
     {
         for (i=0 ; ; i++)
         {
             src = i*scale;
             if (src >= samples)
                 break;
             dst = s_rawend&(MAX_RAW_SAMPLES-1);
             s_rawend++;
             s_rawsamples[dst].left =
                 (((byte *)data)[src]-128) << 16;
             s_rawsamples[dst].right = (((byte *)data)[src]-128) << 16;
         }
     }
 }
Referenced by SCR_ReadNextFrame().
S_RegisterSound()
struct sfx_s* S_RegisterSound (char * sample)
Definition at line 305 of file snd_dma.c.
 {
     sfx_t   *sfx;
     if (!sound_started)
         return NULL;
     sfx = S_FindName (name, true);
     sfx->registration_sequence = s_registration_sequence;
     if (!s_registering)
         S_LoadSound (sfx);
     return sfx;
 }
Referenced by CL_EntityEvent(), CL_ParseConfigString(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParseTEnt(), CL_RegisterSounds(), CL_RegisterTEntSounds(), S_Play(), S_RegisterSexedSound(), and S_StartLocalSound().
S_Shutdown()
void S_Shutdown (void)
Definition at line 164 of file snd_dma.c.
 {
     int     i;
     sfx_t   *sfx;
     if (!sound_started)
         return;
     SNDDMA_Shutdown();
     sound_started = 0;
     Cmd_RemoveCommand("play");
     Cmd_RemoveCommand("stopsound");
     Cmd_RemoveCommand("soundlist");
     Cmd_RemoveCommand("soundinfo");
     // free all sounds
     for (i=0, sfx=known_sfx ; i < num_sfx ; i++,sfx++)
     {
         if (!sfx->name[0])
             continue;
         if (sfx->cache)
             Z_Free (sfx->cache);
         memset (sfx, 0, sizeof(*sfx));
     }
     num_sfx = 0;
 }
Referenced by CL_Shutdown(), CL_Snd_Restart_f(), and SNDDMA_BeginPainting().
S_StartLocalSound()
void S_StartLocalSound (char * s)
Definition at line 738 of file snd_dma.c.
 {
     sfx_t   *sfx;
     if (!sound_started)
         return;
     sfx = S_RegisterSound (sound);
     if (!sfx)
     {
         Com_Printf ("S_StartLocalSound: can't cache %s\n", sound);
         return;
     }
     S_StartSound (NULL, cl.playernum+1, 0, sfx, 1, 1, 0);
 }
Referenced by CL_ParseServerMessage(), M_Draw(), M_Keydown(), and M_PopMenu().
S_StartSound()
void S_StartSound (vec3_t origin, int entnum, int entchannel, struct sfx_s * sfx, float fvol, float attenuation, float timeofs)
Definition at line 655 of file snd_dma.c.
 {
     sfxcache_t  *sc;
     int         vol;
     playsound_t *ps, *sort;
     int         start;
     if (!sound_started)
         return;
     if (!sfx)
         return;
     if (sfx->name[0] == '*')
         sfx = S_RegisterSexedSound(&cl_entities[entnum].current, sfx->name);
     // make sure the sound is loaded
     sc = S_LoadSound (sfx);
     if (!sc)
         return;     // couldn't load the sound's data
     vol = fvol*255;
     // make the playsound_t
     ps = S_AllocPlaysound ();
     if (!ps)
         return;
     if (origin)
     {
         VectorCopy (origin, ps->origin);
         ps->fixed_origin = true;
     }
     else
         ps->fixed_origin = false;
     ps->entnum = entnum;
     ps->entchannel = entchannel;
     ps->attenuation = attenuation;
     ps->volume = vol;
     ps->sfx = sfx;
     // drift s_beginofs
     start = cl.frame.servertime * 0.001 * dma.speed + s_beginofs;
     if (start < paintedtime)
     {
         start = paintedtime;
         s_beginofs = start - (cl.frame.servertime * 0.001 * dma.speed);
     }
     else if (start > paintedtime + 0.3 * dma.speed)
     {
         start = paintedtime + 0.1 * dma.speed;
         s_beginofs = start - (cl.frame.servertime * 0.001 * dma.speed);
     }
     else
     {
         s_beginofs-=10;
     }
     if (!timeofs)
         ps->begin = paintedtime;
     else
         ps->begin = start + timeofs * dma.speed;
     // sort into the pending sound list
     for (sort = s_pendingplays.next ;
         sort != &s_pendingplays && sort->begin < ps->begin ;
         sort = sort->next)
             ;
     ps->next = sort;
     ps->prev = sort->prev;
     ps->next->prev = ps;
     ps->prev->next = ps;
 }
Referenced by CL_EntityEvent(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParseStartSoundPacket(), CL_ParseTEnt(), S_Play(), and S_StartLocalSound().
S_StopAllSounds()
void S_StopAllSounds (void)
Definition at line 785 of file snd_dma.c.
 {
     int     i;
     if (!sound_started)
         return;
     // clear all the playsounds
     memset(s_playsounds, 0, sizeof(s_playsounds));
     s_freeplays.next = s_freeplays.prev = &s_freeplays;
     s_pendingplays.next = s_pendingplays.prev = &s_pendingplays;
     for (i=0 ; i<MAX_PLAYSOUNDS ; i++)
     {
         s_playsounds[i].prev = &s_freeplays;
         s_playsounds[i].next = s_freeplays.next;
         s_playsounds[i].prev->next = &s_playsounds[i];
         s_playsounds[i].next->prev = &s_playsounds[i];
     }
     // clear all the channels
     memset(channels, 0, sizeof(channels));
     S_ClearBuffer ();
 }
Referenced by CL_ClearState(), CL_Reconnect_f(), GetSoundtime(), S_Init(), SCR_BeginLoadingPlaque(), and VID_CheckChanges().
S_Update()
void S_Update (vec3_t origin, vec3_t v_forward, vec3_t v_right, vec3_t v_up)
Definition at line 1009 of file snd_dma.c.
 {
     int         i;
     int         total;
     channel_t   *ch;
     channel_t   *combine;
     if (!sound_started)
         return;
     // if the laoding plaque is up, clear everything
     // out to make sure we aren't looping a dirty
     // dma buffer while loading
     if (cls.disable_screen)
     {
         S_ClearBuffer ();
         return;
     }
     // rebuild scale tables if volume is modified
     if (s_volume->modified)
         S_InitScaletable ();
     VectorCopy(origin, listener_origin);
     VectorCopy(forward, listener_forward);
     VectorCopy(right, listener_right);
     VectorCopy(up, listener_up);
     combine = NULL;
     // update spatialization for dynamic sounds
     ch = channels;
     for (i=0 ; i<MAX_CHANNELS; i++, ch++)
     {
         if (!ch->sfx)
             continue;
         if (ch->autosound)
         {   // autosounds are regenerated fresh each frame
             memset (ch, 0, sizeof(*ch));
             continue;
         }
         S_Spatialize(ch);         // respatialize channel
         if (!ch->leftvol && !ch->rightvol)
         {
             memset (ch, 0, sizeof(*ch));
             continue;
         }
     }
     // add loopsounds
     S_AddLoopSounds ();
     //
     // debugging output
     //
     if (s_show->value)
     {
         total = 0;
         ch = channels;
         for (i=0 ; i<MAX_CHANNELS; i++, ch++)
             if (ch->sfx && (ch->leftvol || ch->rightvol) )
             {
                 Com_Printf ("%3i %3i %s\n", ch->leftvol, ch->rightvol, ch->sfx->name);
                 total++;
             }
         Com_Printf ("----(%i)---- painted: %i\n", total, paintedtime);
     }
 // mix some sound
     S_Update_();
 }
Referenced by CL_Frame().