vq2 doxygen: C:/entry/syn/github/vq2/ref_soft/r_aclip.c File Reference
r_aclip.c File Reference
#include "r_local.h"
Functions
void R_AliasProjectAndClipTestFinalVert (finalvert_t *fv)
void R_Alias_clip_top (finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out)
void R_Alias_clip_bottom (finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out)
void R_Alias_clip_left (finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out)
void R_Alias_clip_right (finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out)
void R_Alias_clip_z (finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out)
int R_AliasClip (finalvert_t *in, finalvert_t *out, int flag, int count, void(*clip)(finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out))
void R_AliasClipTriangle (finalvert_t *index0, finalvert_t *index1, finalvert_t *index2)
void R_AliasClipTriangleRGB (finalvert_t *index0, finalvert_t *index1, finalvert_t *index2)
Variables
static finalvert_t fv [2][8]
Function Documentation
R_Alias_clip_bottom()
void R_Alias_clip_bottom (finalvert_t * pfv0, finalvert_t * pfv1, finalvert_t * out)
Definition at line 186 of file r_aclip.c.
 {
     float       scale;
     if (pfv0->v >= pfv1->v)
     {
         scale = (float)(r_refdef.aliasvrectbottom - pfv0->v) /
                 (pfv1->v - pfv0->v);
         out->u  = pfv0->u  + ( pfv1->u  - pfv0->u ) * scale + 0.5;
         out->v  = pfv0->v  + ( pfv1->v  - pfv0->v ) * scale + 0.5;
         out->s  = pfv0->s  + ( pfv1->s  - pfv0->s ) * scale + 0.5;
         out->t  = pfv0->t  + ( pfv1->t  - pfv0->t ) * scale + 0.5;
         out->l  = pfv0->l  + ( pfv1->l  - pfv0->l ) * scale + 0.5;
         out->zi = pfv0->zi + ( pfv1->zi - pfv0->zi) * scale + 0.5;
         out->lr  = pfv0->lr  + ( pfv1->lr  - pfv0->lr ) * scale + 0.5;
         out->lg  = pfv0->lg  + ( pfv1->lg  - pfv0->lg ) * scale + 0.5;
         out->lb  = pfv0->lb  + ( pfv1->lb  - pfv0->lb ) * scale + 0.5;
     }
     else
     {
         scale = (float)(r_refdef.aliasvrectbottom - pfv1->v) /
                 (pfv0->v - pfv1->v);
         out->u  = pfv1->u  + ( pfv0->u  - pfv1->u ) * scale + 0.5;
         out->v  = pfv1->v  + ( pfv0->v  - pfv1->v ) * scale + 0.5;
         out->s  = pfv1->s  + ( pfv0->s  - pfv1->s ) * scale + 0.5;
         out->t  = pfv1->t  + ( pfv0->t  - pfv1->t ) * scale + 0.5;
         out->l  = pfv1->l  + ( pfv0->l  - pfv1->l ) * scale + 0.5;
         out->zi = pfv1->zi + ( pfv0->zi - pfv1->zi) * scale + 0.5;
         out->lr  = pfv1->lr  + ( pfv0->lr  - pfv1->lr ) * scale + 0.5;
         out->lg  = pfv1->lg  + ( pfv0->lg  - pfv1->lg ) * scale + 0.5;
         out->lb  = pfv1->lb  + ( pfv0->lb  - pfv1->lb ) * scale + 0.5;
     }
 }
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().
R_Alias_clip_left()
void R_Alias_clip_left (finalvert_t * pfv0, finalvert_t * pfv1, finalvert_t * out)
Definition at line 69 of file r_aclip.c.
 {
     float       scale;
     if (pfv0->v >= pfv1->v )
     {
         scale = (float)(r_refdef.aliasvrect.x - pfv0->u) /
                 (pfv1->u - pfv0->u);
         out->u  = pfv0->u  + ( pfv1->u  - pfv0->u ) * scale + 0.5;
         out->v  = pfv0->v  + ( pfv1->v  - pfv0->v ) * scale + 0.5;
         out->s  = pfv0->s  + ( pfv1->s  - pfv0->s ) * scale + 0.5;
         out->t  = pfv0->t  + ( pfv1->t  - pfv0->t ) * scale + 0.5;
         out->l  = pfv0->l  + ( pfv1->l  - pfv0->l ) * scale + 0.5;
         out->zi = pfv0->zi + ( pfv1->zi - pfv0->zi) * scale + 0.5;
 #ifdef COLMODEL
         out->lr  = pfv0->lr  + ( pfv1->lr  - pfv0->lr ) * scale + 0.5;
         out->lg  = pfv0->lg  + ( pfv1->lg  - pfv0->lg ) * scale + 0.5;
         out->lb  = pfv0->lb  + ( pfv1->lb  - pfv0->lb ) * scale + 0.5;
 #endif
     }
     else
     {
         scale = (float)(r_refdef.aliasvrect.x - pfv1->u) /
                 (pfv0->u - pfv1->u);
         out->u  = pfv1->u  + ( pfv0->u  - pfv1->u ) * scale + 0.5;
         out->v  = pfv1->v  + ( pfv0->v  - pfv1->v ) * scale + 0.5;
         out->s  = pfv1->s  + ( pfv0->s  - pfv1->s ) * scale + 0.5;
         out->t  = pfv1->t  + ( pfv0->t  - pfv1->t ) * scale + 0.5;
         out->l  = pfv1->l  + ( pfv0->l  - pfv1->l ) * scale + 0.5;
         out->zi = pfv1->zi + ( pfv0->zi - pfv1->zi) * scale + 0.5;
 #ifdef COLMODEL
         out->lr  = pfv1->lr  + ( pfv0->lr  - pfv1->lr ) * scale + 0.5;
         out->lg  = pfv1->lg  + ( pfv0->lg  - pfv1->lg ) * scale + 0.5;
         out->lb  = pfv1->lb  + ( pfv0->lb  - pfv1->lb ) * scale + 0.5;
 #endif
     }
 }
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().
R_Alias_clip_right()
void R_Alias_clip_right (finalvert_t * pfv0, finalvert_t * pfv1, finalvert_t * out)
Definition at line 108 of file r_aclip.c.
 {
     float       scale;
     if ( pfv0->v >= pfv1->v )
     {
         scale = (float)(r_refdef.aliasvrectright - pfv0->u ) /
                 (pfv1->u - pfv0->u );
         out->u  = pfv0->u  + ( pfv1->u  - pfv0->u ) * scale + 0.5;
         out->v  = pfv0->v  + ( pfv1->v  - pfv0->v ) * scale + 0.5;
         out->s  = pfv0->s  + ( pfv1->s  - pfv0->s ) * scale + 0.5;
         out->t  = pfv0->t  + ( pfv1->t  - pfv0->t ) * scale + 0.5;
         out->l  = pfv0->l  + ( pfv1->l  - pfv0->l ) * scale + 0.5;
         out->zi = pfv0->zi + ( pfv1->zi - pfv0->zi) * scale + 0.5;
 #ifdef COLMODEL
         out->lr  = pfv0->lr  + ( pfv1->lr  - pfv0->lr ) * scale + 0.5;
         out->lg  = pfv0->lg  + ( pfv1->lg  - pfv0->lg ) * scale + 0.5;
         out->lb  = pfv0->lb  + ( pfv1->lb  - pfv0->lb ) * scale + 0.5;
 #endif
     }
     else
     {
         scale = (float)(r_refdef.aliasvrectright - pfv1->u ) /
                 (pfv0->u - pfv1->u );
         out->u  = pfv1->u  + ( pfv0->u  - pfv1->u ) * scale + 0.5;
         out->v  = pfv1->v  + ( pfv0->v  - pfv1->v ) * scale + 0.5;
         out->s  = pfv1->s  + ( pfv0->s  - pfv1->s ) * scale + 0.5;
         out->t  = pfv1->t  + ( pfv0->t  - pfv1->t ) * scale + 0.5;
         out->l  = pfv1->l  + ( pfv0->l  - pfv1->l ) * scale + 0.5;
         out->zi = pfv1->zi + ( pfv0->zi - pfv1->zi) * scale + 0.5;
 #ifdef COLMODEL
         out->lr  = pfv1->lr  + ( pfv0->lr  - pfv1->lr ) * scale + 0.5;
         out->lg  = pfv1->lg  + ( pfv0->lg  - pfv1->lg ) * scale + 0.5;
         out->lb  = pfv1->lb  + ( pfv0->lb  - pfv1->lb ) * scale + 0.5;
 #endif
     }
 }
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().
R_Alias_clip_top()
void R_Alias_clip_top (finalvert_t * pfv0, finalvert_t * pfv1, finalvert_t * out)
Definition at line 147 of file r_aclip.c.
 {
     float       scale;
     if (pfv0->v >= pfv1->v)
     {
         scale = (float)(r_refdef.aliasvrect.y - pfv0->v) /
                 (pfv1->v - pfv0->v);
         out->u  = pfv0->u  + ( pfv1->u  - pfv0->u ) * scale + 0.5;
         out->v  = pfv0->v  + ( pfv1->v  - pfv0->v ) * scale + 0.5;
         out->s  = pfv0->s  + ( pfv1->s  - pfv0->s ) * scale + 0.5;
         out->t  = pfv0->t  + ( pfv1->t  - pfv0->t ) * scale + 0.5;
         out->l  = pfv0->l  + ( pfv1->l  - pfv0->l ) * scale + 0.5;
         out->zi = pfv0->zi + ( pfv1->zi - pfv0->zi) * scale + 0.5;
 #ifdef COLMODEL
         out->lr  = pfv0->lr  + ( pfv1->lr  - pfv0->lr ) * scale + 0.5;
         out->lg  = pfv0->lg  + ( pfv1->lg  - pfv0->lg ) * scale + 0.5;
         out->lb  = pfv0->lb  + ( pfv1->lb  - pfv0->lb ) * scale + 0.5;
 #endif
     }
     else
     {
         scale = (float)(r_refdef.aliasvrect.y - pfv1->v) /
                 (pfv0->v - pfv1->v);
         out->u  = pfv1->u  + ( pfv0->u  - pfv1->u ) * scale + 0.5;
         out->v  = pfv1->v  + ( pfv0->v  - pfv1->v ) * scale + 0.5;
         out->s  = pfv1->s  + ( pfv0->s  - pfv1->s ) * scale + 0.5;
         out->t  = pfv1->t  + ( pfv0->t  - pfv1->t ) * scale + 0.5;
         out->l  = pfv1->l  + ( pfv0->l  - pfv1->l ) * scale + 0.5;
         out->zi = pfv1->zi + ( pfv0->zi - pfv1->zi) * scale + 0.5;
 #ifdef COLMODEL
         out->lr  = pfv1->lr  + ( pfv0->lr  - pfv1->lr ) * scale + 0.5;
         out->lg  = pfv1->lg  + ( pfv0->lg  - pfv1->lg ) * scale + 0.5;
         out->lb  = pfv1->lb  + ( pfv0->lb  - pfv1->lb ) * scale + 0.5;
 #endif
     }
 }
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().
R_Alias_clip_z()
void R_Alias_clip_z (finalvert_t * pfv0, finalvert_t * pfv1, finalvert_t * out)
Definition at line 44 of file r_aclip.c.
 {
     float       scale;
     scale = (ALIAS_Z_CLIP_PLANE - pfv0->xyz[2]) /
             (pfv1->xyz[2] - pfv0->xyz[2]);
     out->xyz[0] = pfv0->xyz[0] + (pfv1->xyz[0] - pfv0->xyz[0]) * scale;
     out->xyz[1] = pfv0->xyz[1] + (pfv1->xyz[1] - pfv0->xyz[1]) * scale;
     out->xyz[2] = ALIAS_Z_CLIP_PLANE;
     out->s =    pfv0->s + (pfv1->s - pfv0->s) * scale;
     out->t =    pfv0->t + (pfv1->t - pfv0->t) * scale;
     out->l =    pfv0->l + (pfv1->l - pfv0->l) * scale;
 //qb: colored lighting from leilei
     out->lr =   pfv0->lr + (pfv1->lr - pfv0->lr) * scale;
     out->lg =   pfv0->lg + (pfv1->lg - pfv0->lg) * scale;
     out->lb =   pfv0->lb + (pfv1->lb - pfv0->lb) * scale;
     R_AliasProjectAndClipTestFinalVert (out);
 }
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().
R_AliasClip()
int R_AliasClip (finalvert_t * in, finalvert_t * out, int flag, int count, void(*)(finalvert_t *pfv0, finalvert_t *pfv1, finalvert_t *out) clip)
Definition at line 226 of file r_aclip.c.
 {
     int         i,j,k;
     int         flags, oldflags;
     j = count-1;
     k = 0;
     for (i=0 ; i<count ; j = i, i++)
     {
         oldflags = in[j].flags & flag;
         flags = in[i].flags & flag;
         if (flags && oldflags)
             continue;
         if (oldflags ^ flags)
         {
             clip (&in[j], &in[i], &out[k]);
             out[k].flags = 0;
             if (out[k].u < r_refdef.aliasvrect.x)
                 out[k].flags |= ALIAS_LEFT_CLIP;
             if (out[k].v < r_refdef.aliasvrect.y)
                 out[k].flags |= ALIAS_TOP_CLIP;
             if (out[k].u > r_refdef.aliasvrectright)
                 out[k].flags |= ALIAS_RIGHT_CLIP;
             if (out[k].v > r_refdef.aliasvrectbottom)
                 out[k].flags |= ALIAS_BOTTOM_CLIP;
             k++;
         }
         if (!flags)
         {
             out[k] = in[i];
             k++;
         }
     }
     return k;
 }
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().
R_AliasClipTriangle()
void R_AliasClipTriangle (finalvert_t * index0, finalvert_t * index1, finalvert_t * index2)
Definition at line 271 of file r_aclip.c.
 {
     int             i, k, pingpong;
     unsigned        clipflags;
 // copy vertexes and fix seam texture coordinates
     fv[0][0] = *index0;
     fv[0][1] = *index1;
     fv[0][2] = *index2;
 // clip
     clipflags = fv[0][0].flags | fv[0][1].flags | fv[0][2].flags;
     if (clipflags & ALIAS_Z_CLIP)
     {
         k = R_AliasClip (fv[0], fv[1], ALIAS_Z_CLIP, 3, R_Alias_clip_z);
         if (k == 0)
             return;
         pingpong = 1;
         clipflags = fv[1][0].flags | fv[1][1].flags | fv[1][2].flags;
     }
     else
     {
         pingpong = 0;
         k = 3;
     }
     if (clipflags & ALIAS_LEFT_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_LEFT_CLIP, k, R_Alias_clip_left);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     if (clipflags & ALIAS_RIGHT_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_RIGHT_CLIP, k, R_Alias_clip_right);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     if (clipflags & ALIAS_BOTTOM_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_BOTTOM_CLIP, k, R_Alias_clip_bottom);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     if (clipflags & ALIAS_TOP_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_TOP_CLIP, k, R_Alias_clip_top);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     for (i=0 ; i<k ; i++)
     {
         if (fv[pingpong][i].u < r_refdef.aliasvrect.x)
             fv[pingpong][i].u = r_refdef.aliasvrect.x;
         else if (fv[pingpong][i].u > r_refdef.aliasvrectright)
             fv[pingpong][i].u = r_refdef.aliasvrectright;
         if (fv[pingpong][i].v < r_refdef.aliasvrect.y)
             fv[pingpong][i].v = r_refdef.aliasvrect.y;
         else if (fv[pingpong][i].v > r_refdef.aliasvrectbottom)
             fv[pingpong][i].v = r_refdef.aliasvrectbottom;
         fv[pingpong][i].flags = 0;
     }
 // draw triangles
     for (i=1 ; i<k-1 ; i++)
     {
         aliastriangleparms.a = &fv[pingpong][0];
         aliastriangleparms.b = &fv[pingpong][i];
         aliastriangleparms.c = &fv[pingpong][i+1];
         R_DrawTriangle();
     }
 }
Referenced by R_AliasPreparePoints().
R_AliasClipTriangleRGB()
void R_AliasClipTriangleRGB (finalvert_t * index0, finalvert_t * index1, finalvert_t * index2)
Definition at line 372 of file r_aclip.c.
 {
     int             i, k, pingpong;
     unsigned        clipflags;
 // copy vertexes and fix seam texture coordinates
     fv[0][0] = *index0;
     fv[0][1] = *index1;
     fv[0][2] = *index2;
 // clip
     clipflags = fv[0][0].flags | fv[0][1].flags | fv[0][2].flags;
     if (clipflags & ALIAS_Z_CLIP)
     {
         k = R_AliasClip (fv[0], fv[1], ALIAS_Z_CLIP, 3, R_Alias_clip_z);
         if (k == 0)
             return;
         pingpong = 1;
         clipflags = fv[1][0].flags | fv[1][1].flags | fv[1][2].flags;
     }
     else
     {
         pingpong = 0;
         k = 3;
     }
     if (clipflags & ALIAS_LEFT_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_LEFT_CLIP, k, R_Alias_clip_left);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     if (clipflags & ALIAS_RIGHT_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_RIGHT_CLIP, k, R_Alias_clip_right);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     if (clipflags & ALIAS_BOTTOM_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_BOTTOM_CLIP, k, R_Alias_clip_bottom);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     if (clipflags & ALIAS_TOP_CLIP)
     {
         k = R_AliasClip (fv[pingpong], fv[pingpong ^ 1],
                             ALIAS_TOP_CLIP, k, R_Alias_clip_top);
         if (k == 0)
             return;
         pingpong ^= 1;
     }
     for (i=0 ; i<k ; i++)
     {
         if (fv[pingpong][i].u < r_refdef.aliasvrect.x)
             fv[pingpong][i].u = r_refdef.aliasvrect.x;
         else if (fv[pingpong][i].u > r_refdef.aliasvrectright)
             fv[pingpong][i].u = r_refdef.aliasvrectright;
         if (fv[pingpong][i].v < r_refdef.aliasvrect.y)
             fv[pingpong][i].v = r_refdef.aliasvrect.y;
         else if (fv[pingpong][i].v > r_refdef.aliasvrectbottom)
             fv[pingpong][i].v = r_refdef.aliasvrectbottom;
         fv[pingpong][i].flags = 0;
     }
 // draw triangles
     for (i=1 ; i<k-1 ; i++)
     {
         aliastriangleparms.a = &fv[pingpong][0];
         aliastriangleparms.b = &fv[pingpong][i];
         aliastriangleparms.c = &fv[pingpong][i+1];
         R_DrawTriangle();
     }
 }
Referenced by R_AliasPreparePoints().
R_AliasProjectAndClipTestFinalVert()
void R_AliasProjectAndClipTestFinalVert (finalvert_t * fv)
Definition at line 813 of file r_alias.c.
 {
     float   zi;
     float   x, y, z;
     // project points
     x = fv->xyz[0];
     y = fv->xyz[1];
     z = fv->xyz[2];
     zi = 1.0 / z;
     fv->zi = zi * s_ziscale;
     fv->u = (x * aliasxscale * zi) + aliasxcenter;
     fv->v = (y * aliasyscale * zi) + aliasycenter;
     if (fv->u < r_refdef.aliasvrect.x)
         fv->flags |= ALIAS_LEFT_CLIP;
     if (fv->v < r_refdef.aliasvrect.y)
         fv->flags |= ALIAS_TOP_CLIP;
     if (fv->u > r_refdef.aliasvrectright)
         fv->flags |= ALIAS_RIGHT_CLIP;
     if (fv->v > r_refdef.aliasvrectbottom)
         fv->flags |= ALIAS_BOTTOM_CLIP;
 }
Referenced by R_Alias_clip_z(), and R_AliasTransformFinalVerts().
Variable Documentation
fv
finalvert_t fv[2][8] static
Definition at line 24 of file r_aclip.c.
Referenced by R_AliasClipTriangle(), and R_AliasClipTriangleRGB().