vq2 doxygen: C:/entry/syn/github/vq2/ctf/g_ctf.h File Reference
g_ctf.h File Reference
Classes
struct ghost_s
Macros
#define CTF_VERSION 1.52
#define CTF_VSTRING2(x) #x
#define CTF_VSTRING(x) CTF_VSTRING2(x)
#define CTF_STRING_VERSION CTF_VSTRING(CTF_VERSION)
#define STAT_CTF_TEAM1_PIC 17
#define STAT_CTF_TEAM1_CAPS 18
#define STAT_CTF_TEAM2_PIC 19
#define STAT_CTF_TEAM2_CAPS 20
#define STAT_CTF_FLAG_PIC 21
#define STAT_CTF_JOINED_TEAM1_PIC 22
#define STAT_CTF_JOINED_TEAM2_PIC 23
#define STAT_CTF_TEAM1_HEADER 24
#define STAT_CTF_TEAM2_HEADER 25
#define STAT_CTF_TECH 26
#define STAT_CTF_ID_VIEW 27
#define STAT_CTF_MATCH 28
#define STAT_CTF_ID_VIEW_COLOR 29
#define STAT_CTF_TEAMINFO 30
#define CONFIG_CTF_MATCH (CS_AIRACCEL-1)
#define CONFIG_CTF_TEAMINFO (CS_AIRACCEL-2)
#define CTF_TEAM1_SKIN "ctf_r"
#define CTF_TEAM2_SKIN "ctf_b"
#define DF_CTF_FORCEJOIN 131072
#define DF_ARMOR_PROTECT 262144
#define DF_CTF_NO_TECH 524288
#define CTF_CAPTURE_BONUS 15
#define CTF_TEAM_BONUS 10
#define CTF_RECOVERY_BONUS 1
#define CTF_FLAG_BONUS 0
#define CTF_FRAG_CARRIER_BONUS 2
#define CTF_FLAG_RETURN_TIME 40
#define CTF_CARRIER_DANGER_PROTECT_BONUS 2
#define CTF_CARRIER_PROTECT_BONUS 1
#define CTF_FLAG_DEFENSE_BONUS 1
#define CTF_RETURN_FLAG_ASSIST_BONUS 1
#define CTF_FRAG_CARRIER_ASSIST_BONUS 2
#define CTF_TARGET_PROTECT_RADIUS 400
#define CTF_ATTACKER_PROTECT_RADIUS 400
#define CTF_CARRIER_DANGER_PROTECT_TIMEOUT 8
#define CTF_FRAG_CARRIER_ASSIST_TIMEOUT 10
#define CTF_RETURN_FLAG_ASSIST_TIMEOUT 10
#define CTF_AUTO_FLAG_RETURN_TIMEOUT 30
#define CTF_TECH_TIMEOUT 60
#define CTF_GRAPPLE_SPEED 650
#define CTF_GRAPPLE_PULL_SPEED 650
Typedefs
typedef struct ghost_s ghost_t
Enumerations
enum ctfteam_t { CTF_NOTEAM, CTF_TEAM1, CTF_TEAM2 }
enum ctfgrapplestate_t { CTF_GRAPPLE_STATE_FLY, CTF_GRAPPLE_STATE_PULL, CTF_GRAPPLE_STATE_HANG }
Functions
void CTFInit (void)
void CTFSpawn (void)
void CTFPrecache (void)
void SP_info_player_team1 (edict_t *self)
void SP_info_player_team2 (edict_t *self)
char * CTFTeamName (int team)
char * CTFOtherTeamName (int team)
void CTFAssignSkin (edict_t *ent, char *s)
void CTFAssignTeam (gclient_t *who)
edict_t * SelectCTFSpawnPoint (edict_t *ent)
qboolean CTFPickup_Flag (edict_t *ent, edict_t *other)
void CTFDrop_Flag (edict_t *ent, gitem_t *item)
void CTFEffects (edict_t *player)
void CTFCalcScores (void)
void SetCTFStats (edict_t *ent)
void CTFDeadDropFlag (edict_t *self)
void CTFScoreboardMessage (edict_t *ent, edict_t *killer)
void CTFTeam_f (edict_t *ent)
void CTFID_f (edict_t *ent)
void CTFSay_Team (edict_t *who, char *msg)
void CTFFlagSetup (edict_t *ent)
void CTFResetFlag (int ctf_team)
void CTFFragBonuses (edict_t *targ, edict_t *inflictor, edict_t *attacker)
void CTFCheckHurtCarrier (edict_t *targ, edict_t *attacker)
void CTFWeapon_Grapple (edict_t *ent)
void CTFPlayerResetGrapple (edict_t *ent)
void CTFGrapplePull (edict_t *self)
void CTFResetGrapple (edict_t *self)
gitem_t * CTFWhat_Tech (edict_t *ent)
qboolean CTFPickup_Tech (edict_t *ent, edict_t *other)
void CTFDrop_Tech (edict_t *ent, gitem_t *item)
void CTFDeadDropTech (edict_t *ent)
void CTFSetupTechSpawn (void)
int CTFApplyResistance (edict_t *ent, int dmg)
int CTFApplyStrength (edict_t *ent, int dmg)
qboolean CTFApplyStrengthSound (edict_t *ent)
qboolean CTFApplyHaste (edict_t *ent)
void CTFApplyHasteSound (edict_t *ent)
void CTFApplyRegeneration (edict_t *ent)
qboolean CTFHasRegeneration (edict_t *ent)
void CTFRespawnTech (edict_t *ent)
void CTFResetTech (void)
void CTFOpenJoinMenu (edict_t *ent)
qboolean CTFStartClient (edict_t *ent)
void CTFVoteYes (edict_t *ent)
void CTFVoteNo (edict_t *ent)
void CTFReady (edict_t *ent)
void CTFNotReady (edict_t *ent)
qboolean CTFNextMap (void)
qboolean CTFMatchSetup (void)
qboolean CTFMatchOn (void)
void CTFGhost (edict_t *ent)
void CTFAdmin (edict_t *ent)
qboolean CTFInMatch (void)
void CTFStats (edict_t *ent)
void CTFWarp (edict_t *ent)
void CTFBoot (edict_t *ent)
void CTFPlayerList (edict_t *ent)
qboolean CTFCheckRules (void)
void SP_misc_ctf_banner (edict_t *ent)
void SP_misc_ctf_small_banner (edict_t *ent)
void UpdateChaseCam (edict_t *ent)
void ChaseNext (edict_t *ent)
void ChasePrev (edict_t *ent)
void CTFObserver (edict_t *ent)
void SP_trigger_teleport (edict_t *ent)
void SP_info_teleport_destination (edict_t *ent)
void CTFSetPowerUpEffect (edict_t *ent, int def)
Variables
cvar_t * ctf
char * ctf_statusbar
Macro Definition Documentation
CONFIG_CTF_MATCH
#define CONFIG_CTF_MATCH (CS_AIRACCEL-1)
Definition at line 41 of file g_ctf.h.
CONFIG_CTF_TEAMINFO
#define CONFIG_CTF_TEAMINFO (CS_AIRACCEL-2)
Definition at line 42 of file g_ctf.h.
CTF_ATTACKER_PROTECT_RADIUS
#define CTF_ATTACKER_PROTECT_RADIUS 400
Definition at line 96 of file g_ctf.h.
CTF_AUTO_FLAG_RETURN_TIMEOUT
#define CTF_AUTO_FLAG_RETURN_TIMEOUT 30
Definition at line 102 of file g_ctf.h.
CTF_CAPTURE_BONUS
#define CTF_CAPTURE_BONUS 15
Definition at line 82 of file g_ctf.h.
CTF_CARRIER_DANGER_PROTECT_BONUS
#define CTF_CARRIER_DANGER_PROTECT_BONUS 2
Definition at line 89 of file g_ctf.h.
CTF_CARRIER_DANGER_PROTECT_TIMEOUT
#define CTF_CARRIER_DANGER_PROTECT_TIMEOUT 8
Definition at line 98 of file g_ctf.h.
CTF_CARRIER_PROTECT_BONUS
#define CTF_CARRIER_PROTECT_BONUS 1
Definition at line 90 of file g_ctf.h.
CTF_FLAG_BONUS
#define CTF_FLAG_BONUS 0
Definition at line 85 of file g_ctf.h.
CTF_FLAG_DEFENSE_BONUS
#define CTF_FLAG_DEFENSE_BONUS 1
Definition at line 91 of file g_ctf.h.
CTF_FLAG_RETURN_TIME
#define CTF_FLAG_RETURN_TIME 40
Definition at line 87 of file g_ctf.h.
CTF_FRAG_CARRIER_ASSIST_BONUS
#define CTF_FRAG_CARRIER_ASSIST_BONUS 2
Definition at line 93 of file g_ctf.h.
CTF_FRAG_CARRIER_ASSIST_TIMEOUT
#define CTF_FRAG_CARRIER_ASSIST_TIMEOUT 10
Definition at line 99 of file g_ctf.h.
CTF_FRAG_CARRIER_BONUS
#define CTF_FRAG_CARRIER_BONUS 2
Definition at line 86 of file g_ctf.h.
CTF_GRAPPLE_PULL_SPEED
#define CTF_GRAPPLE_PULL_SPEED 650
Definition at line 107 of file g_ctf.h.
CTF_GRAPPLE_SPEED
#define CTF_GRAPPLE_SPEED 650
Definition at line 106 of file g_ctf.h.
CTF_RECOVERY_BONUS
#define CTF_RECOVERY_BONUS 1
Definition at line 84 of file g_ctf.h.
CTF_RETURN_FLAG_ASSIST_BONUS
#define CTF_RETURN_FLAG_ASSIST_BONUS 1
Definition at line 92 of file g_ctf.h.
CTF_RETURN_FLAG_ASSIST_TIMEOUT
#define CTF_RETURN_FLAG_ASSIST_TIMEOUT 10
Definition at line 100 of file g_ctf.h.
CTF_STRING_VERSION
#define CTF_STRING_VERSION CTF_VSTRING(CTF_VERSION)
Definition at line 24 of file g_ctf.h.
CTF_TARGET_PROTECT_RADIUS
#define CTF_TARGET_PROTECT_RADIUS 400
Definition at line 95 of file g_ctf.h.
CTF_TEAM1_SKIN
#define CTF_TEAM1_SKIN "ctf_r"
Definition at line 75 of file g_ctf.h.
CTF_TEAM2_SKIN
#define CTF_TEAM2_SKIN "ctf_b"
Definition at line 76 of file g_ctf.h.
CTF_TEAM_BONUS
#define CTF_TEAM_BONUS 10
Definition at line 83 of file g_ctf.h.
CTF_TECH_TIMEOUT
#define CTF_TECH_TIMEOUT 60
Definition at line 104 of file g_ctf.h.
CTF_VERSION
#define CTF_VERSION 1.52
Definition at line 21 of file g_ctf.h.
CTF_VSTRING
#define CTF_VSTRING (x) CTF_VSTRING2(x)
Definition at line 23 of file g_ctf.h.
CTF_VSTRING2
#define CTF_VSTRING2 (x) #x
Definition at line 22 of file g_ctf.h.
DF_ARMOR_PROTECT
#define DF_ARMOR_PROTECT 262144
Definition at line 79 of file g_ctf.h.
DF_CTF_FORCEJOIN
#define DF_CTF_FORCEJOIN 131072
Definition at line 78 of file g_ctf.h.
DF_CTF_NO_TECH
#define DF_CTF_NO_TECH 524288
Definition at line 80 of file g_ctf.h.
STAT_CTF_FLAG_PIC
#define STAT_CTF_FLAG_PIC 21
Definition at line 30 of file g_ctf.h.
STAT_CTF_ID_VIEW
#define STAT_CTF_ID_VIEW 27
Definition at line 36 of file g_ctf.h.
STAT_CTF_ID_VIEW_COLOR
#define STAT_CTF_ID_VIEW_COLOR 29
Definition at line 38 of file g_ctf.h.
STAT_CTF_JOINED_TEAM1_PIC
#define STAT_CTF_JOINED_TEAM1_PIC 22
Definition at line 31 of file g_ctf.h.
STAT_CTF_JOINED_TEAM2_PIC
#define STAT_CTF_JOINED_TEAM2_PIC 23
Definition at line 32 of file g_ctf.h.
STAT_CTF_MATCH
#define STAT_CTF_MATCH 28
Definition at line 37 of file g_ctf.h.
STAT_CTF_TEAM1_CAPS
#define STAT_CTF_TEAM1_CAPS 18
Definition at line 27 of file g_ctf.h.
STAT_CTF_TEAM1_HEADER
#define STAT_CTF_TEAM1_HEADER 24
Definition at line 33 of file g_ctf.h.
STAT_CTF_TEAM1_PIC
#define STAT_CTF_TEAM1_PIC 17
Definition at line 26 of file g_ctf.h.
STAT_CTF_TEAM2_CAPS
#define STAT_CTF_TEAM2_CAPS 20
Definition at line 29 of file g_ctf.h.
STAT_CTF_TEAM2_HEADER
#define STAT_CTF_TEAM2_HEADER 25
Definition at line 34 of file g_ctf.h.
STAT_CTF_TEAM2_PIC
#define STAT_CTF_TEAM2_PIC 19
Definition at line 28 of file g_ctf.h.
STAT_CTF_TEAMINFO
#define STAT_CTF_TEAMINFO 30
Definition at line 39 of file g_ctf.h.
STAT_CTF_TECH
#define STAT_CTF_TECH 26
Definition at line 35 of file g_ctf.h.
Typedef Documentation
ghost_t
typedef struct ghost_s ghost_t
Enumeration Type Documentation
ctfgrapplestate_t
enum ctfgrapplestate_t
Enumerator
CTF_GRAPPLE_STATE_FLY
CTF_GRAPPLE_STATE_PULL
CTF_GRAPPLE_STATE_HANG
Definition at line 50 of file g_ctf.h.
              {
     CTF_GRAPPLE_STATE_FLY,
     CTF_GRAPPLE_STATE_PULL,
     CTF_GRAPPLE_STATE_HANG
 } ctfgrapplestate_t;
ctfteam_t
enum ctfteam_t
Enumerator
CTF_NOTEAM
CTF_TEAM1
CTF_TEAM2
Definition at line 44 of file g_ctf.h.
              {
     CTF_NOTEAM,
     CTF_TEAM1,
     CTF_TEAM2
 } ctfteam_t;
Function Documentation
ChaseNext()
void ChaseNext (edict_t * ent)
Definition at line 111 of file g_chase.c.
 {
     int i;
     edict_t *e;
     if (!ent->client->chase_target)
         return;
     i = ent->client->chase_target - g_edicts;
     do {
         i++;
         if (i > maxclients->value)
             i = 1;
         e = g_edicts + i;
         if (!e->inuse)
             continue;
         if (e->solid != SOLID_NOT)
             break;
     } while (e != ent->client->chase_target);
     ent->client->chase_target = e;
     ent->client->update_chase = true;
 }
ChasePrev()
void ChasePrev (edict_t * ent)
Definition at line 135 of file g_chase.c.
 {
     int i;
     edict_t *e;
     if (!ent->client->chase_target)
         return;
     i = ent->client->chase_target - g_edicts;
     do {
         i--;
         if (i < 1)
             i = maxclients->value;
         e = g_edicts + i;
         if (!e->inuse)
             continue;
         if (e->solid != SOLID_NOT)
             break;
     } while (e != ent->client->chase_target);
     ent->client->chase_target = e;
     ent->client->update_chase = true;
 }
CTFAdmin()
void CTFAdmin (edict_t * ent)
Definition at line 3963 of file g_ctf.c.
 {
     char text[1024];
     if (!allow_admin->value) {
         gi.cprintf(ent, PRINT_HIGH, "Administration is disabled\n");
         return;
     }
     if (gi.argc() > 1 && admin_password->string && *admin_password->string &&
         !ent->client->resp.admin && strcmp(admin_password->string, gi.argv(1)) == 0) {
         ent->client->resp.admin = true;
         gi.bprintf(PRINT_HIGH, "%s has become an admin.\n", ent->client->pers.netname);
         gi.cprintf(ent, PRINT_HIGH, "Type 'admin' to access the adminstration menu.\n");
     }
     if (!ent->client->resp.admin) {
         sprintf(text, "%s has requested admin rights.",
             ent->client->pers.netname);
         CTFBeginElection(ent, ELECT_ADMIN, text);
         return;
     }
     if (ent->client->menu)
         PMenu_Close(ent);
     CTFOpenAdminMenu(ent);
 }
Referenced by ClientCommand().
CTFApplyHaste()
qboolean CTFApplyHaste (edict_t * ent)
Definition at line 2120 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     if (!tech)
         tech = FindItemByClassname("item_tech3");
     if (tech && ent->client &&
         ent->client->pers.inventory[ITEM_INDEX(tech)])
         return true;
     return false;
 }
Referenced by Weapon_Generic().
CTFApplyHasteSound()
void CTFApplyHasteSound (edict_t * ent)
Definition at line 2132 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     float volume = 1.0;
     if (ent->client && ent->client->silencer_shots)
         volume = 0.2;
     if (!tech)
         tech = FindItemByClassname("item_tech3");
     if (tech && ent->client &&
         ent->client->pers.inventory[ITEM_INDEX(tech)] &&
         ent->client->ctf_techsndtime < level.time) {
         ent->client->ctf_techsndtime = level.time + 1;
         gi.sound(ent, CHAN_VOICE, gi.soundindex("ctf/tech3.wav"), volume, ATTN_NORM, 0);
     }
 }
Referenced by Weapon_Generic2().
CTFApplyRegeneration()
void CTFApplyRegeneration (edict_t * ent)
Definition at line 2150 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     qboolean noise = false;
     gclient_t *client;
     int index;
     float volume = 1.0;
     client = ent->client;
     if (!client)
         return;
     if (ent->client->silencer_shots)
         volume = 0.2;
     if (!tech)
         tech = FindItemByClassname("item_tech4");
     if (tech && client->pers.inventory[ITEM_INDEX(tech)]) {
         if (client->ctf_regentime < level.time) {
             client->ctf_regentime = level.time;
             if (ent->health < 150) {
                 ent->health += 5;
                 if (ent->health > 150)
                     ent->health = 150;
                 client->ctf_regentime += 0.5;
                 noise = true;
             }
             index = ArmorIndex (ent);
             if (index && client->pers.inventory[index] < 150) {
                 client->pers.inventory[index] += 5;
                 if (client->pers.inventory[index] > 150)
                     client->pers.inventory[index] = 150;
                 client->ctf_regentime += 0.5;
                 noise = true;
             }
         }
         if (noise && ent->client->ctf_techsndtime < level.time) {
             ent->client->ctf_techsndtime = level.time + 1;
             gi.sound(ent, CHAN_VOICE, gi.soundindex("ctf/tech4.wav"), volume, ATTN_NORM, 0);
         }
     }
 }
Referenced by ClientThink().
CTFApplyResistance()
int CTFApplyResistance (edict_t * ent, int dmg)
Definition at line 2065 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     float volume = 1.0;
     if (ent->client && ent->client->silencer_shots)
         volume = 0.2;
     if (!tech)
         tech = FindItemByClassname("item_tech1");
     if (dmg && tech && ent->client && ent->client->pers.inventory[ITEM_INDEX(tech)]) {
         // make noise
         gi.sound(ent, CHAN_VOICE, gi.soundindex("ctf/tech1.wav"), volume, ATTN_NORM, 0);
         return dmg / 2;
     }
     return dmg;
 }
Referenced by T_Damage().
CTFApplyStrength()
int CTFApplyStrength (edict_t * ent, int dmg)
Definition at line 2083 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     if (!tech)
         tech = FindItemByClassname("item_tech2");
     if (dmg && tech && ent->client && ent->client->pers.inventory[ITEM_INDEX(tech)]) {
         return dmg * 2;
     }
     return dmg;
 }
Referenced by T_Damage().
CTFApplyStrengthSound()
qboolean CTFApplyStrengthSound (edict_t * ent)
Definition at line 2095 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     float volume = 1.0;
     if (ent->client && ent->client->silencer_shots)
         volume = 0.2;
     if (!tech)
         tech = FindItemByClassname("item_tech2");
     if (tech && ent->client &&
         ent->client->pers.inventory[ITEM_INDEX(tech)]) {
         if (ent->client->ctf_techsndtime < level.time) {
             ent->client->ctf_techsndtime = level.time + 1;
             if (ent->client->quad_framenum > level.framenum)
                 gi.sound(ent, CHAN_VOICE, gi.soundindex("ctf/tech2x.wav"), volume, ATTN_NORM, 0);
             else
                 gi.sound(ent, CHAN_VOICE, gi.soundindex("ctf/tech2.wav"), volume, ATTN_NORM, 0);
         }
         return true;
     }
     return false;
 }
Referenced by Weapon_Generic2().
CTFAssignSkin()
void CTFAssignSkin (edict_t * ent, char * s)
Definition at line 417 of file g_ctf.c.
 {
     int playernum = ent-g_edicts-1;
     char *p;
     char t[64];
     Com_sprintf(t, sizeof(t), "%s", s);
     if ((p = strchr(t, '/')) != NULL)
         p[1] = 0;
     else
         strcpy(t, "male/");
     switch (ent->client->resp.ctf_team) {
     case CTF_TEAM1:
         gi.configstring (CS_PLAYERSKINS+playernum, va("%s\\%s%s",
             ent->client->pers.netname, t, CTF_TEAM1_SKIN) );
         break;
     case CTF_TEAM2:
         gi.configstring (CS_PLAYERSKINS+playernum,
             va("%s\\%s%s", ent->client->pers.netname, t, CTF_TEAM2_SKIN) );
         break;
     default:
         gi.configstring (CS_PLAYERSKINS+playernum,
             va("%s\\%s", ent->client->pers.netname, s) );
         break;
     }
 //  gi.cprintf(ent, PRINT_HIGH, "You have been assigned to %s team.\n", ent->client->pers.netname);
 }
Referenced by ClientUserinfoChanged(), CTFJoinTeam(), and CTFTeam_f().
CTFAssignTeam()
void CTFAssignTeam (gclient_t * who)
Definition at line 447 of file g_ctf.c.
 {
     edict_t     *player;
     int i;
     int team1count = 0, team2count = 0;
     who->resp.ctf_state = 0;
     if (!((int)dmflags->value & DF_CTF_FORCEJOIN)) {
         who->resp.ctf_team = CTF_NOTEAM;
         return;
     }
     for (i = 1; i <= maxclients->value; i++) {
         player = &g_edicts[i];
         if (!player->inuse || player->client == who)
             continue;
         switch (player->client->resp.ctf_team) {
         case CTF_TEAM1:
             team1count++;
             break;
         case CTF_TEAM2:
             team2count++;
         }
     }
     if (team1count < team2count)
         who->resp.ctf_team = CTF_TEAM1;
     else if (team2count < team1count)
         who->resp.ctf_team = CTF_TEAM2;
     else if (rand() & 1)
         who->resp.ctf_team = CTF_TEAM1;
     else
         who->resp.ctf_team = CTF_TEAM2;
 }
Referenced by InitClientResp().
CTFBoot()
void CTFBoot (edict_t * ent)
Definition at line 4154 of file g_ctf.c.
 {
     int i;
     edict_t *targ;
     char text[80];
     if (!ent->client->resp.admin) {
         gi.cprintf(ent, PRINT_HIGH, "You are not an admin.\n");
         return;
     }
     if (gi.argc() < 2) {
         gi.cprintf(ent, PRINT_HIGH, "Who do you want to kick?\n");
         return;
     }
     if (*gi.argv(1) < '0' && *gi.argv(1) > '9') {
         gi.cprintf(ent, PRINT_HIGH, "Specify the player number to kick.\n");
         return;
     }
     i = atoi(gi.argv(1));
     if (i < 1 || i > maxclients->value) {
         gi.cprintf(ent, PRINT_HIGH, "Invalid player number.\n");
         return;
     }
     targ = g_edicts + i;
     if (!targ->inuse) {
         gi.cprintf(ent, PRINT_HIGH, "That player number is not connected.\n");
         return;
     }
     sprintf(text, "kick %d\n", i - 1);
     gi.AddCommandString(text);
 }
Referenced by ClientCommand().
CTFCalcScores()
void CTFCalcScores (void)
Definition at line 1001 of file g_ctf.c.
 {
     int i;
     ctfgame.total1 = ctfgame.total2 = 0;
     for (i = 0; i < maxclients->value; i++) {
         if (!g_edicts[i+1].inuse)
             continue;
         if (game.clients[i].resp.ctf_team == CTF_TEAM1)
             ctfgame.total1 += game.clients[i].resp.score;
         else if (game.clients[i].resp.ctf_team == CTF_TEAM2)
             ctfgame.total2 += game.clients[i].resp.score;
     }
 }
Referenced by BeginIntermission(), and CTFEndMatch().
CTFCheckHurtCarrier()
void CTFCheckHurtCarrier (edict_t * targ, edict_t * attacker)
Definition at line 713 of file g_ctf.c.
 {
     gitem_t *flag_item;
     if (!targ->client || !attacker->client)
         return;
     if (targ->client->resp.ctf_team == CTF_TEAM1)
         flag_item = flag2_item;
     else
         flag_item = flag1_item;
     if (targ->client->pers.inventory[ITEM_INDEX(flag_item)] &&
         targ->client->resp.ctf_team != attacker->client->resp.ctf_team)
         attacker->client->resp.ctf_lasthurtcarrier = level.time;
 }
Referenced by T_Damage().
CTFCheckRules()
qboolean CTFCheckRules (void)
Definition at line 3363 of file g_ctf.c.
 {
     int t;
     int i, j;
     char text[64];
     edict_t *ent;
     if (ctfgame.election != ELECT_NONE && ctfgame.electtime <= level.time) {
         gi.bprintf(PRINT_CHAT, "Election timed out and has been cancelled.\n");
         ctfgame.election = ELECT_NONE;
     }
     if (ctfgame.match != MATCH_NONE) {
         t = ctfgame.matchtime - level.time;
         // no team warnings in match mode
         ctfgame.warnactive = 0;
         if (t <= 0) { // time ended on something
             switch (ctfgame.match) {
             case MATCH_SETUP :
                 // go back to normal mode
                 if (competition->value < 3) {
                     ctfgame.match = MATCH_NONE;
                     gi.cvar_set("competition", "1");
                     CTFResetAllPlayers();
                 } else {
                     // reset the time
                     ctfgame.matchtime = level.time + matchsetuptime->value * 60;
                 }
                 return false;
             case MATCH_PREGAME :
                 // match started!
                 CTFStartMatch();
                 gi.positioned_sound (world->s.origin, world, CHAN_AUTO | CHAN_RELIABLE, gi.soundindex("misc/tele_up.wav"), 1, ATTN_NONE, 0);
                 return false;
             case MATCH_GAME :
                 // match ended!
                 CTFEndMatch();
                 gi.positioned_sound (world->s.origin, world, CHAN_AUTO | CHAN_RELIABLE, gi.soundindex("misc/bigtele.wav"), 1, ATTN_NONE, 0);
                 return false;
             default:
                 return false;
             }
         }
         if (t == ctfgame.lasttime)
             return false;
         ctfgame.lasttime = t;
         switch (ctfgame.match) {
         case MATCH_SETUP :
             for (j = 0, i = 1; i <= maxclients->value; i++) {
                 ent = g_edicts + i;
                 if (!ent->inuse)
                     continue;
                 if (ent->client->resp.ctf_team != CTF_NOTEAM &&
                     !ent->client->resp.ready)
                     j++;
             }
             if (competition->value < 3)
                 sprintf(text, "%02d:%02d SETUP: %d not ready",
                     t / 60, t % 60, j);
             else
                 sprintf(text, "SETUP: %d not ready", j);
             gi.configstring (CONFIG_CTF_MATCH, text);
             break;
         case MATCH_PREGAME :
             sprintf(text, "%02d:%02d UNTIL START",
                 t / 60, t % 60);
             gi.configstring (CONFIG_CTF_MATCH, text);
             if (t <= 10 && !ctfgame.countdown) {
                 ctfgame.countdown = true;
                 gi.positioned_sound (world->s.origin, world, CHAN_AUTO | CHAN_RELIABLE, gi.soundindex("world/10_0.wav"), 1, ATTN_NONE, 0);
             }
             break;
         case MATCH_GAME:
             sprintf(text, "%02d:%02d MATCH",
                 t / 60, t % 60);
             gi.configstring (CONFIG_CTF_MATCH, text);
             if (t <= 10 && !ctfgame.countdown) {
                 ctfgame.countdown = true;
                 gi.positioned_sound (world->s.origin, world, CHAN_AUTO | CHAN_RELIABLE, gi.soundindex("world/10_0.wav"), 1, ATTN_NONE, 0);
             }
             break;
         default:
             break;
         }
         return false;
     } else {
         int team1 = 0, team2 = 0;
         if (level.time == ctfgame.lasttime)
             return false;
         ctfgame.lasttime = level.time;
         // this is only done in non-match (public) mode
         if (warn_unbalanced->value) {
             // count up the team totals
             for (i = 1; i <= maxclients->value; i++) {
                 ent = g_edicts + i;
                 if (!ent->inuse)
                     continue;
                 if (ent->client->resp.ctf_team == CTF_TEAM1)
                     team1++;
                 else if (ent->client->resp.ctf_team == CTF_TEAM2)
                     team2++;
             }
             if (team1 - team2 >= 2 && team2 >= 2) {
                 if (ctfgame.warnactive != CTF_TEAM1) {
                     ctfgame.warnactive = CTF_TEAM1;
                     gi.configstring (CONFIG_CTF_TEAMINFO, "WARNING: Red has too many players");
                 }
             } else if (team2 - team1 >= 2 && team1 >= 2) {
                 if (ctfgame.warnactive != CTF_TEAM2) {
                     ctfgame.warnactive = CTF_TEAM2;
                     gi.configstring (CONFIG_CTF_TEAMINFO, "WARNING: Blue has too many players");
                 }
             } else
                 ctfgame.warnactive = 0;
         } else
             ctfgame.warnactive = 0;
     }
     if (capturelimit->value &&
         (ctfgame.team1 >= capturelimit->value ||
         ctfgame.team2 >= capturelimit->value)) {
         gi.bprintf (PRINT_HIGH, "Capturelimit hit.\n");
         return true;
     }
     return false;
 }
Referenced by CheckDMRules().
CTFDeadDropFlag()
void CTFDeadDropFlag (edict_t * self)
Definition at line 903 of file g_ctf.c.
 {
     edict_t *dropped = NULL;
     if (self->client->pers.inventory[ITEM_INDEX(flag1_item)]) {
         dropped = Drop_Item(self, flag1_item);
         self->client->pers.inventory[ITEM_INDEX(flag1_item)] = 0;
         gi.bprintf(PRINT_HIGH, "%s lost the %s flag!\n",
             self->client->pers.netname, CTFTeamName(CTF_TEAM1));
     } else if (self->client->pers.inventory[ITEM_INDEX(flag2_item)]) {
         dropped = Drop_Item(self, flag2_item);
         self->client->pers.inventory[ITEM_INDEX(flag2_item)] = 0;
         gi.bprintf(PRINT_HIGH, "%s lost the %s flag!\n",
             self->client->pers.netname, CTFTeamName(CTF_TEAM2));
     }
     if (dropped) {
         dropped->think = CTFDropFlagThink;
         dropped->nextthink = level.time + CTF_AUTO_FLAG_RETURN_TIMEOUT;
         dropped->touch = CTFDropFlagTouch;
     }
 }
Referenced by ClientDisconnect(), CTFObserver(), CTFResetAllPlayers(), and player_die().
CTFDeadDropTech()
void CTFDeadDropTech (edict_t * ent)
Definition at line 1953 of file g_ctf.c.
 {
     gitem_t *tech;
     edict_t *dropped;
     int i;
     i = 0;
     while (tnames[i]) {
         if ((tech = FindItemByClassname(tnames[i])) != NULL &&
             ent->client->pers.inventory[ITEM_INDEX(tech)]) {
             dropped = Drop_Item(ent, tech);
             // hack the velocity to make it bounce random
             dropped->velocity[0] = (rand() % 600) - 300;
             dropped->velocity[1] = (rand() % 600) - 300;
             dropped->nextthink = level.time + CTF_TECH_TIMEOUT;
             dropped->think = TechThink;
             dropped->owner = NULL;
             ent->client->pers.inventory[ITEM_INDEX(tech)] = 0;
         }
         i++;
     }
 }
Referenced by ClientDisconnect(), CTFObserver(), CTFResetAllPlayers(), and player_die().
CTFDrop_Flag()
void CTFDrop_Flag (edict_t * ent, gitem_t * item)
Definition at line 926 of file g_ctf.c.
 {
     if (rand() & 1)
         gi.cprintf(ent, PRINT_HIGH, "Only lusers drop flags.\n");
     else
         gi.cprintf(ent, PRINT_HIGH, "Winners don't drop flags.\n");
 }
CTFDrop_Tech()
void CTFDrop_Tech (edict_t * ent, gitem_t * item)
Definition at line 1943 of file g_ctf.c.
 {
     edict_t *tech;
     tech = Drop_Item(ent, item);
     tech->nextthink = level.time + CTF_TECH_TIMEOUT;
     tech->think = TechThink;
     ent->client->pers.inventory[ITEM_INDEX(item)] = 0;
 }
CTFEffects()
void CTFEffects (edict_t * player)
Definition at line 980 of file g_ctf.c.
 {
     player->s.effects &= ~(EF_FLAG1 | EF_FLAG2);
     if (player->health > 0) {
         if (player->client->pers.inventory[ITEM_INDEX(flag1_item)]) {
             player->s.effects |= EF_FLAG1;
         }
         if (player->client->pers.inventory[ITEM_INDEX(flag2_item)]) {
             player->s.effects |= EF_FLAG2;
         }
     }
     if (player->client->pers.inventory[ITEM_INDEX(flag1_item)])
         player->s.modelindex3 = gi.modelindex("players/male/flag1.md2");
     else if (player->client->pers.inventory[ITEM_INDEX(flag2_item)])
         player->s.modelindex3 = gi.modelindex("players/male/flag2.md2");
     else
         player->s.modelindex3 = 0;
 }
Referenced by G_SetClientEffects().
CTFFlagSetup()
void CTFFlagSetup (edict_t * ent)
Definition at line 942 of file g_ctf.c.
 {
     trace_t     tr;
     vec3_t      dest;
     float       *v;
     v = tv(-15,-15,-15);
     VectorCopy (v, ent->mins);
     v = tv(15,15,15);
     VectorCopy (v, ent->maxs);
     if (ent->model)
         gi.setmodel (ent, ent->model);
     else
         gi.setmodel (ent, ent->item->world_model);
     ent->solid = SOLID_TRIGGER;
     ent->movetype = MOVETYPE_TOSS;
     ent->touch = Touch_Item;
     v = tv(0,0,-128);
     VectorAdd (ent->s.origin, v, dest);
     tr = gi.trace (ent->s.origin, ent->mins, ent->maxs, dest, ent, MASK_SOLID);
     if (tr.startsolid)
     {
         gi.dprintf ("CTFFlagSetup: %s startsolid at %s\n", ent->classname, vtos(ent->s.origin));
         G_FreeEdict (ent);
         return;
     }
     VectorCopy (tr.endpos, ent->s.origin);
     gi.linkentity (ent);
     ent->nextthink = level.time + FRAMETIME;
     ent->think = CTFFlagThink;
 }
Referenced by SpawnItem().
CTFFragBonuses()
void CTFFragBonuses (edict_t * targ, edict_t * inflictor, edict_t * attacker)
Definition at line 570 of file g_ctf.c.
 {
     int i;
     edict_t *ent;
     gitem_t *flag_item, *enemy_flag_item;
     int otherteam;
     edict_t *flag, *carrier = NULL;
     char *c;
     vec3_t v1, v2;
     if (targ->client && attacker->client) {
         if (attacker->client->resp.ghost)
             if (attacker != targ)
                 attacker->client->resp.ghost->kills++;
         if (targ->client->resp.ghost)
             targ->client->resp.ghost->deaths++;
     }
     // no bonus for fragging yourself
     if (!targ->client || !attacker->client || targ == attacker)
         return;
     otherteam = CTFOtherTeam(targ->client->resp.ctf_team);
     if (otherteam < 0)
         return; // whoever died isn't on a team
     // same team, if the flag at base, check to he has the enemy flag
     if (targ->client->resp.ctf_team == CTF_TEAM1) {
         flag_item = flag1_item;
         enemy_flag_item = flag2_item;
     } else {
         flag_item = flag2_item;
         enemy_flag_item = flag1_item;
     }
     // did the attacker frag the flag carrier?
     if (targ->client->pers.inventory[ITEM_INDEX(enemy_flag_item)]) {
         attacker->client->resp.ctf_lastfraggedcarrier = level.time;
         attacker->client->resp.score += CTF_FRAG_CARRIER_BONUS;
         gi.cprintf(attacker, PRINT_MEDIUM, "BONUS: %d points for fragging enemy flag carrier.\n",
             CTF_FRAG_CARRIER_BONUS);
         // the target had the flag, clear the hurt carrier
         // field on the other team
         for (i = 1; i <= maxclients->value; i++) {
             ent = g_edicts + i;
             if (ent->inuse && ent->client->resp.ctf_team == otherteam)
                 ent->client->resp.ctf_lasthurtcarrier = 0;
         }
         return;
     }
     if (targ->client->resp.ctf_lasthurtcarrier &&
         level.time - targ->client->resp.ctf_lasthurtcarrier < CTF_CARRIER_DANGER_PROTECT_TIMEOUT &&
         !attacker->client->pers.inventory[ITEM_INDEX(flag_item)]) {
         // attacker is on the same team as the flag carrier and
         // fragged a guy who hurt our flag carrier
         attacker->client->resp.score += CTF_CARRIER_DANGER_PROTECT_BONUS;
         gi.bprintf(PRINT_MEDIUM, "%s defends %s's flag carrier against an agressive enemy\n",
             attacker->client->pers.netname,
             CTFTeamName(attacker->client->resp.ctf_team));
         if (attacker->client->resp.ghost)
             attacker->client->resp.ghost->carrierdef++;
         return;
     }
     // flag and flag carrier area defense bonuses
     // we have to find the flag and carrier entities
     // find the flag
     switch (attacker->client->resp.ctf_team) {
     case CTF_TEAM1:
         c = "item_flag_team1";
         break;
     case CTF_TEAM2:
         c = "item_flag_team2";
         break;
     default:
         return;
     }
     flag = NULL;
     while ((flag = G_Find (flag, FOFS(classname), c)) != NULL) {
         if (!(flag->spawnflags & DROPPED_ITEM))
             break;
     }
     if (!flag)
         return; // can't find attacker's flag
     // find attacker's team's flag carrier
     for (i = 1; i <= maxclients->value; i++) {
         carrier = g_edicts + i;
         if (carrier->inuse &&
             carrier->client->pers.inventory[ITEM_INDEX(flag_item)])
             break;
         carrier = NULL;
     }
     // ok we have the attackers flag and a pointer to the carrier
     // check to see if we are defending the base's flag
     VectorSubtract(targ->s.origin, flag->s.origin, v1);
     VectorSubtract(attacker->s.origin, flag->s.origin, v2);
     if ((VectorLength(v1) < CTF_TARGET_PROTECT_RADIUS ||
         VectorLength(v2) < CTF_TARGET_PROTECT_RADIUS ||
         loc_CanSee(flag, targ) || loc_CanSee(flag, attacker)) &&
         attacker->client->resp.ctf_team != targ->client->resp.ctf_team) {
         // we defended the base flag
         attacker->client->resp.score += CTF_FLAG_DEFENSE_BONUS;
         if (flag->solid == SOLID_NOT)
             gi.bprintf(PRINT_MEDIUM, "%s defends the %s base.\n",
                 attacker->client->pers.netname,
                 CTFTeamName(attacker->client->resp.ctf_team));
         else
             gi.bprintf(PRINT_MEDIUM, "%s defends the %s flag.\n",
                 attacker->client->pers.netname,
                 CTFTeamName(attacker->client->resp.ctf_team));
         if (attacker->client->resp.ghost)
             attacker->client->resp.ghost->basedef++;
         return;
     }
     if (carrier && carrier != attacker) {
         VectorSubtract(targ->s.origin, carrier->s.origin, v1);
         VectorSubtract(attacker->s.origin, carrier->s.origin, v1);
         if (VectorLength(v1) < CTF_ATTACKER_PROTECT_RADIUS ||
             VectorLength(v2) < CTF_ATTACKER_PROTECT_RADIUS ||
             loc_CanSee(carrier, targ) || loc_CanSee(carrier, attacker)) {
             attacker->client->resp.score += CTF_CARRIER_PROTECT_BONUS;
             gi.bprintf(PRINT_MEDIUM, "%s defends the %s's flag carrier.\n",
                 attacker->client->pers.netname,
                 CTFTeamName(attacker->client->resp.ctf_team));
             if (attacker->client->resp.ghost)
                 attacker->client->resp.ghost->carrierdef++;
             return;
         }
     }
 }
Referenced by player_die().
CTFGhost()
void CTFGhost (edict_t * ent)
Definition at line 2969 of file g_ctf.c.
 {
     int i;
     int n;
     if (gi.argc() < 2) {
         gi.cprintf(ent, PRINT_HIGH, "Usage:  ghost <code>\n");
         return;
     }
     if (ent->client->resp.ctf_team != CTF_NOTEAM) {
         gi.cprintf(ent, PRINT_HIGH, "You are already in the game.\n");
         return;
     }
     if (ctfgame.match != MATCH_GAME) {
         gi.cprintf(ent, PRINT_HIGH, "No match is in progress.\n");
         return;
     }
     n = atoi(gi.argv(1));
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (ctfgame.ghosts[i].code && ctfgame.ghosts[i].code == n) {
             gi.cprintf(ent, PRINT_HIGH, "Ghost code accepted, your position has been reinstated.\n");
             ctfgame.ghosts[i].ent->client->resp.ghost = NULL;
             ent->client->resp.ctf_team = ctfgame.ghosts[i].team;
             ent->client->resp.ghost = ctfgame.ghosts + i;
             ent->client->resp.score = ctfgame.ghosts[i].score;
             ent->client->resp.ctf_state = 0;
             ctfgame.ghosts[i].ent = ent;
             ent->svflags = 0;
             ent->flags &= ~FL_GODMODE;
             PutClientInServer(ent);
             gi.bprintf(PRINT_HIGH, "%s has been reinstated to %s team.\n",
                 ent->client->pers.netname, CTFTeamName(ent->client->resp.ctf_team));
             return;
         }
     }
     gi.cprintf(ent, PRINT_HIGH, "Invalid ghost code.\n");
 }
Referenced by ClientCommand().
CTFGrapplePull()
void CTFGrapplePull (edict_t * self)
Definition at line 1388 of file g_ctf.c.
 {
     vec3_t hookdir, v;
     float vlen;
     if (strcmp(self->owner->client->pers.weapon->classname, "weapon_grapple") == 0 &&
         !self->owner->client->newweapon &&
         self->owner->client->weaponstate != WEAPON_FIRING &&
         self->owner->client->weaponstate != WEAPON_ACTIVATING) {
         CTFResetGrapple(self);
         return;
     }
     if (self->enemy) {
         if (self->enemy->solid == SOLID_NOT) {
             CTFResetGrapple(self);
             return;
         }
         if (self->enemy->solid == SOLID_BBOX) {
             VectorScale(self->enemy->size, 0.5, v);
             VectorAdd(v, self->enemy->s.origin, v);
             VectorAdd(v, self->enemy->mins, self->s.origin);
             gi.linkentity (self);
         } else
             VectorCopy(self->enemy->velocity, self->velocity);
         if (self->enemy->takedamage &&
             !CheckTeamDamage (self->enemy, self->owner)) {
             float volume = 1.0;
             if (self->owner->client->silencer_shots)
                 volume = 0.2;
             T_Damage (self->enemy, self, self->owner, self->velocity, self->s.origin, vec3_origin, 1, 1, 0, MOD_GRAPPLE);
             gi.sound (self, CHAN_WEAPON, gi.soundindex("weapons/grapple/grhurt.wav"), volume, ATTN_NORM, 0);
         }
         if (self->enemy->deadflag) { // he died
             CTFResetGrapple(self);
             return;
         }
     }
     CTFGrappleDrawCable(self);
     if (self->owner->client->ctf_grapplestate > CTF_GRAPPLE_STATE_FLY) {
         // pull player toward grapple
         // this causes icky stuff with prediction, we need to extend
         // the prediction layer to include two new fields in the player
         // move stuff: a point and a velocity.  The client should add
         // that velociy in the direction of the point
         vec3_t forward, up;
         AngleVectors (self->owner->client->v_angle, forward, NULL, up);
         VectorCopy(self->owner->s.origin, v);
         v[2] += self->owner->viewheight;
         VectorSubtract (self->s.origin, v, hookdir);
         vlen = VectorLength(hookdir);
         if (self->owner->client->ctf_grapplestate == CTF_GRAPPLE_STATE_PULL &&
             vlen < 64) {
             float volume = 1.0;
             if (self->owner->client->silencer_shots)
                 volume = 0.2;
             self->owner->client->ps.pmove.pm_flags |= PMF_NO_PREDICTION;
             gi.sound (self->owner, CHAN_RELIABLE+CHAN_WEAPON, gi.soundindex("weapons/grapple/grhang.wav"), volume, ATTN_NORM, 0);
             self->owner->client->ctf_grapplestate = CTF_GRAPPLE_STATE_HANG;
         }
         VectorNormalize (hookdir);
         VectorScale(hookdir, CTF_GRAPPLE_PULL_SPEED, hookdir);
         VectorCopy(hookdir, self->owner->velocity);
         SV_AddGravity(self->owner);
     }
 }
Referenced by ClientThink().
CTFHasRegeneration()
qboolean CTFHasRegeneration (edict_t * ent)
Definition at line 2193 of file g_ctf.c.
 {
     static gitem_t *tech = NULL;
     if (!tech)
         tech = FindItemByClassname("item_tech4");
     if (tech && ent->client &&
         ent->client->pers.inventory[ITEM_INDEX(tech)])
         return true;
     return false;
 }
Referenced by MegaHealth_think(), and Pickup_Health().
CTFID_f()
void CTFID_f (edict_t * ent)
Definition at line 1016 of file g_ctf.c.
 {
     if (ent->client->resp.id_state) {
         gi.cprintf(ent, PRINT_HIGH, "Disabling player identication display.\n");
         ent->client->resp.id_state = false;
     } else {
         gi.cprintf(ent, PRINT_HIGH, "Activating player identication display.\n");
         ent->client->resp.id_state = true;
     }
 }
Referenced by ClientCommand().
CTFInit()
void CTFInit (void)
Definition at line 341 of file g_ctf.c.
 {
     ctf = gi.cvar("ctf", "1", CVAR_SERVERINFO);
     ctf_forcejoin = gi.cvar("ctf_forcejoin", "", 0);
     competition = gi.cvar("competition", "0", CVAR_SERVERINFO);
     matchlock = gi.cvar("matchlock", "1", CVAR_SERVERINFO);
     electpercentage = gi.cvar("electpercentage", "66", 0);
     matchtime = gi.cvar("matchtime", "20", CVAR_SERVERINFO);
     matchsetuptime = gi.cvar("matchsetuptime", "10", 0);
     matchstarttime = gi.cvar("matchstarttime", "20", 0);
     admin_password = gi.cvar("admin_password", "", 0);
     allow_admin = gi.cvar("allow_admin", "1", 0);
     warp_list = gi.cvar("warp_list", "q2ctf1 q2ctf2 q2ctf3 q2ctf4 q2ctf5", 0);
     warn_unbalanced = gi.cvar("warn_unbalanced", "1", 0);
 }
Referenced by InitGame().
CTFInMatch()
qboolean CTFInMatch (void)
Definition at line 3356 of file g_ctf.c.
 {
     if (ctfgame.match > MATCH_NONE)
         return true;
     return false;
 }
Referenced by CheckDMRules().
CTFMatchOn()
qboolean CTFMatchOn (void)
Definition at line 3017 of file g_ctf.c.
 {
     if (ctfgame.match == MATCH_GAME)
         return true;
     return false;
 }
Referenced by ClientBeginServerFrame().
CTFMatchSetup()
qboolean CTFMatchSetup (void)
Definition at line 3010 of file g_ctf.c.
 {
     if (ctfgame.match == MATCH_SETUP || ctfgame.match == MATCH_PREGAME)
         return true;
     return false;
 }
Referenced by T_Damage(), and Touch_Item().
CTFNextMap()
qboolean CTFNextMap (void)
Definition at line 2807 of file g_ctf.c.
 {
     if (ctfgame.match == MATCH_POST) {
         ctfgame.match = MATCH_SETUP;
         CTFResetAllPlayers();
         return true;
     }
     return false;
 }
Referenced by ExitLevel().
CTFNotReady()
void CTFNotReady (edict_t * ent)
Definition at line 2942 of file g_ctf.c.
 {
     if (ent->client->resp.ctf_team == CTF_NOTEAM) {
         gi.cprintf(ent, PRINT_HIGH, "Pick a team first (hit <TAB> for menu)\n");
         return;
     }
     if (ctfgame.match != MATCH_SETUP && ctfgame.match != MATCH_PREGAME) {
         gi.cprintf(ent, PRINT_HIGH, "A match is not being setup.\n");
         return;
     }
     if (!ent->client->resp.ready) {
         gi.cprintf(ent, PRINT_HIGH, "You haven't commited.\n");
         return;
     }
     ent->client->resp.ready = false;
     gi.bprintf(PRINT_HIGH, "%s is no longer ready.\n", ent->client->pers.netname);
     if (ctfgame.match == MATCH_PREGAME) {
         gi.bprintf(PRINT_CHAT, "Match halted.\n");
         ctfgame.match = MATCH_SETUP;
         ctfgame.matchtime = level.time + matchsetuptime->value * 60;
     }
 }
Referenced by ClientCommand().
CTFObserver()
void CTFObserver (edict_t * ent)
Definition at line 3331 of file g_ctf.c.
 {
     char        userinfo[MAX_INFO_STRING];
     // start as 'observer'
     if (ent->movetype == MOVETYPE_NOCLIP)
     CTFPlayerResetGrapple(ent);
     CTFDeadDropFlag(ent);
     CTFDeadDropTech(ent);
     ent->deadflag = DEAD_NO;
     ent->movetype = MOVETYPE_NOCLIP;
     ent->solid = SOLID_NOT;
     ent->svflags |= SVF_NOCLIENT;
     ent->client->resp.ctf_team = CTF_NOTEAM;
     ent->client->ps.gunindex = 0;
     ent->client->resp.score = 0;
     memcpy (userinfo, ent->client->pers.userinfo, sizeof(userinfo));
     InitClientPersistant(ent->client);
     ClientUserinfoChanged (ent, userinfo);
     gi.linkentity (ent);
     CTFOpenJoinMenu(ent);
 }
Referenced by ClientCommand().
CTFOpenJoinMenu()
void CTFOpenJoinMenu (edict_t * ent)
Definition at line 3291 of file g_ctf.c.
 {
     int team;
     team = CTFUpdateJoinMenu(ent);
     if (ent->client->chase_target)
         team = 8;
     else if (team == CTF_TEAM1)
         team = 4;
     else
         team = 6;
     PMenu_Open(ent, joinmenu, team, sizeof(joinmenu) / sizeof(pmenu_t), NULL);
 }
Referenced by Cmd_Inven_f(), CTFObserver(), CTFReturnToMain(), and CTFStartClient().
CTFOtherTeamName()
char* CTFOtherTeamName (int team)
Definition at line 389 of file g_ctf.c.
 {
     switch (team) {
     case CTF_TEAM1:
         return "BLUE";
     case CTF_TEAM2:
         return "RED";
     }
     return "UNKNOWN"; // Hanzo pointed out this was spelled wrong as "UKNOWN"
 }
Referenced by CTFPickup_Flag().
CTFPickup_Flag()
qboolean CTFPickup_Flag (edict_t * ent, edict_t * other)
Definition at line 768 of file g_ctf.c.
 {
     int ctf_team;
     int i;
     edict_t *player;
     gitem_t *flag_item, *enemy_flag_item;
     // figure out what team this flag is
     if (strcmp(ent->classname, "item_flag_team1") == 0)
         ctf_team = CTF_TEAM1;
     else if (strcmp(ent->classname, "item_flag_team2") == 0)
         ctf_team = CTF_TEAM2;
     else {
         gi.cprintf(ent, PRINT_HIGH, "Don't know what team the flag is on.\n");
         return false;
     }
     // same team, if the flag at base, check to he has the enemy flag
     if (ctf_team == CTF_TEAM1) {
         flag_item = flag1_item;
         enemy_flag_item = flag2_item;
     } else {
         flag_item = flag2_item;
         enemy_flag_item = flag1_item;
     }
     if (ctf_team == other->client->resp.ctf_team) {
         if (!(ent->spawnflags & DROPPED_ITEM)) {
             // the flag is at home base.  if the player has the enemy
             // flag, he's just won!
             if (other->client->pers.inventory[ITEM_INDEX(enemy_flag_item)]) {
                 gi.bprintf(PRINT_HIGH, "%s captured the %s flag!\n",
                         other->client->pers.netname, CTFOtherTeamName(ctf_team));
                 other->client->pers.inventory[ITEM_INDEX(enemy_flag_item)] = 0;
                 ctfgame.last_flag_capture = level.time;
                 ctfgame.last_capture_team = ctf_team;
                 if (ctf_team == CTF_TEAM1)
                     ctfgame.team1++;
                 else
                     ctfgame.team2++;
                 gi.sound (ent, CHAN_RELIABLE+CHAN_NO_PHS_ADD+CHAN_VOICE, gi.soundindex("ctf/flagcap.wav"), 1, ATTN_NONE, 0);
                 // other gets another 10 frag bonus
                 other->client->resp.score += CTF_CAPTURE_BONUS;
                 if (other->client->resp.ghost)
                     other->client->resp.ghost->caps++;
                 // Ok, let's do the player loop, hand out the bonuses
                 for (i = 1; i <= maxclients->value; i++) {
                     player = &g_edicts[i];
                     if (!player->inuse)
                         continue;
                     if (player->client->resp.ctf_team != other->client->resp.ctf_team)
                         player->client->resp.ctf_lasthurtcarrier = -5;
                     else if (player->client->resp.ctf_team == other->client->resp.ctf_team) {
                         if (player != other)
                             player->client->resp.score += CTF_TEAM_BONUS;
                         // award extra points for capture assists
                         if (player->client->resp.ctf_lastreturnedflag + CTF_RETURN_FLAG_ASSIST_TIMEOUT > level.time) {
                             gi.bprintf(PRINT_HIGH, "%s gets an assist for returning the flag!\n", player->client->pers.netname);
                             player->client->resp.score += CTF_RETURN_FLAG_ASSIST_BONUS;
                         }
                         if (player->client->resp.ctf_lastfraggedcarrier + CTF_FRAG_CARRIER_ASSIST_TIMEOUT > level.time) {
                             gi.bprintf(PRINT_HIGH, "%s gets an assist for fragging the flag carrier!\n", player->client->pers.netname);
                             player->client->resp.score += CTF_FRAG_CARRIER_ASSIST_BONUS;
                         }
                     }
                 }
                 CTFResetFlags();
                 return false;
             }
             return false; // its at home base already
         }
         // hey, its not home.  return it by teleporting it back
         gi.bprintf(PRINT_HIGH, "%s returned the %s flag!\n",
             other->client->pers.netname, CTFTeamName(ctf_team));
         other->client->resp.score += CTF_RECOVERY_BONUS;
         other->client->resp.ctf_lastreturnedflag = level.time;
         gi.sound (ent, CHAN_RELIABLE+CHAN_NO_PHS_ADD+CHAN_VOICE, gi.soundindex("ctf/flagret.wav"), 1, ATTN_NONE, 0);
         //CTFResetFlag will remove this entity!  We must return false
         CTFResetFlag(ctf_team);
         return false;
     }
     // hey, its not our flag, pick it up
     gi.bprintf(PRINT_HIGH, "%s got the %s flag!\n",
         other->client->pers.netname, CTFTeamName(ctf_team));
     other->client->resp.score += CTF_FLAG_BONUS;
     other->client->pers.inventory[ITEM_INDEX(flag_item)] = 1;
     other->client->resp.ctf_flagsince = level.time;
     // pick up the flag
     // if it's not a dropped flag, we just make is disappear
     // if it's dropped, it will be removed by the pickup caller
     if (!(ent->spawnflags & DROPPED_ITEM)) {
         ent->flags |= FL_RESPAWN;
         ent->svflags |= SVF_NOCLIENT;
         ent->solid = SOLID_NOT;
     }
     return true;
 }
CTFPickup_Tech()
qboolean CTFPickup_Tech (edict_t * ent, edict_t * other)
Definition at line 1895 of file g_ctf.c.
 {
     gitem_t *tech;
     int i;
     i = 0;
     while (tnames[i]) {
         if ((tech = FindItemByClassname(tnames[i])) != NULL &&
             other->client->pers.inventory[ITEM_INDEX(tech)]) {
             CTFHasTech(other);
             return false; // has this one
         }
         i++;
     }
     // client only gets one tech
     other->client->pers.inventory[ITEM_INDEX(ent->item)]++;
     other->client->ctf_regentime = level.time;
     return true;
 }
CTFPlayerList()
void CTFPlayerList (edict_t * ent)
Definition at line 4056 of file g_ctf.c.
 {
     int i;
     char st[80];
     char text[1400];
     edict_t *e2;
 #if 0
     *text = 0;
     if (ctfgame.match == MATCH_SETUP) {
         for (i = 1; i <= maxclients->value; i++) {
             e2 = g_edicts + i;
             if (!e2->inuse)
                 continue;
             if (!e2->client->resp.ready && e2->client->resp.ctf_team != CTF_NOTEAM) {
                 sprintf(st, "%s is not ready.\n", e2->client->pers.netname);
                 if (strlen(text) + strlen(st) < sizeof(text) - 50)
                     strcat(text, st);
             }
         }
     }
 #endif
     // number, name, connect time, ping, score, admin
     *text = 0;
     for (i = 1; i <= maxclients->value; i++) {
         e2 = g_edicts + i;
         if (!e2->inuse)
             continue;
         Com_sprintf(st, sizeof(st), "%3d %-16.16s %02d:%02d %4d %3d%s%s\n",
             i,
             e2->client->pers.netname,
             (level.framenum - e2->client->resp.enterframe) / 600,
             ((level.framenum - e2->client->resp.enterframe) % 600)/10,
             e2->client->ping,
             e2->client->resp.score,
             (ctfgame.match == MATCH_SETUP || ctfgame.match == MATCH_PREGAME) ?
             (e2->client->resp.ready ? " (ready)" : " (notready)") : "",
             e2->client->resp.admin ? " (admin)" : "");
         if (strlen(text) + strlen(st) > sizeof(text) - 50) {
             sprintf(text+strlen(text), "And more...\n");
             gi.cprintf(ent, PRINT_HIGH, "%s", text);
             return;
         }
         strcat(text, st);
     }
     gi.cprintf(ent, PRINT_HIGH, "%s", text);
 }
Referenced by ClientCommand().
CTFPlayerResetGrapple()
void CTFPlayerResetGrapple (edict_t * ent)
Definition at line 1250 of file g_ctf.c.
 {
     if (ent->client && ent->client->ctf_grapple)
         CTFResetGrapple(ent->client->ctf_grapple);
 }
Referenced by CTFObserver(), CTFResetAllPlayers(), CTFStartMatch(), old_teleporter_touch(), player_die(), and teleporter_touch().
CTFPrecache()
void CTFPrecache (void)
Definition at line 361 of file g_ctf.c.
 {
     imageindex_i_ctf1 =   gi.imageindex("i_ctf1");
     imageindex_i_ctf2 =   gi.imageindex("i_ctf2");
     imageindex_i_ctf1d =  gi.imageindex("i_ctf1d");
     imageindex_i_ctf2d =  gi.imageindex("i_ctf2d");
     imageindex_i_ctf1t =  gi.imageindex("i_ctf1t");
     imageindex_i_ctf2t =  gi.imageindex("i_ctf2t");
     imageindex_i_ctfj =   gi.imageindex("i_ctfj");
     imageindex_sbfctf1 =  gi.imageindex("sbfctf1");
     imageindex_sbfctf2 =  gi.imageindex("sbfctf2");
     imageindex_ctfsb1 =   gi.imageindex("ctfsb1");
     imageindex_ctfsb2 =   gi.imageindex("ctfsb2");
 }
Referenced by SP_worldspawn().
CTFReady()
void CTFReady (edict_t * ent)
Definition at line 2896 of file g_ctf.c.
 {
     int i, j;
     edict_t *e;
     int t1, t2;
     if (ent->client->resp.ctf_team == CTF_NOTEAM) {
         gi.cprintf(ent, PRINT_HIGH, "Pick a team first (hit <TAB> for menu)\n");
         return;
     }
     if (ctfgame.match != MATCH_SETUP) {
         gi.cprintf(ent, PRINT_HIGH, "A match is not being setup.\n");
         return;
     }
     if (ent->client->resp.ready) {
         gi.cprintf(ent, PRINT_HIGH, "You have already commited.\n");
         return;
     }
     ent->client->resp.ready = true;
     gi.bprintf(PRINT_HIGH, "%s is ready.\n", ent->client->pers.netname);
     t1 = t2 = 0;
     for (j = 0, i = 1; i <= maxclients->value; i++) {
         e = g_edicts + i;
         if (!e->inuse)
             continue;
         if (e->client->resp.ctf_team != CTF_NOTEAM && !e->client->resp.ready)
             j++;
         if (e->client->resp.ctf_team == CTF_TEAM1)
             t1++;
         else if (e->client->resp.ctf_team == CTF_TEAM2)
             t2++;
     }
     if (!j && t1 && t2) {
         // everyone has commited
         gi.bprintf(PRINT_CHAT, "All players have commited.  Match starting\n");
         ctfgame.match = MATCH_PREGAME;
         ctfgame.matchtime = level.time + matchstarttime->value;
         ctfgame.countdown = false;
         gi.positioned_sound (world->s.origin, world, CHAN_AUTO | CHAN_RELIABLE, gi.soundindex("misc/talk1.wav"), 1, ATTN_NONE, 0);
     }
 }
Referenced by ClientCommand().
CTFResetFlag()
void CTFResetFlag (int ctf_team)
Definition at line 733 of file g_ctf.c.
 {
     char *c;
     edict_t *ent;
     switch (ctf_team) {
     case CTF_TEAM1:
         c = "item_flag_team1";
         break;
     case CTF_TEAM2:
         c = "item_flag_team2";
         break;
     default:
         return;
     }
     ent = NULL;
     while ((ent = G_Find (ent, FOFS(classname), c)) != NULL) {
         if (ent->spawnflags & DROPPED_ITEM)
             G_FreeEdict(ent);
         else {
             ent->svflags &= ~SVF_NOCLIENT;
             ent->solid = SOLID_TRIGGER;
             gi.linkentity(ent);
             ent->s.event = EV_ITEM_RESPAWN;
         }
     }
 }
Referenced by BecomeExplosion1(), CTFDropFlagThink(), CTFPickup_Flag(), and CTFResetFlags().
CTFResetGrapple()
void CTFResetGrapple (edict_t * self)
Definition at line 1257 of file g_ctf.c.
 {
     if (self->owner->client->ctf_grapple) {
         float volume = 1.0;
         gclient_t *cl;
         if (self->owner->client->silencer_shots)
             volume = 0.2;
         gi.sound (self->owner, CHAN_RELIABLE+CHAN_WEAPON, gi.soundindex("weapons/grapple/grreset.wav"), volume, ATTN_NORM, 0);
         cl = self->owner->client;
         cl->ctf_grapple = NULL;
         cl->ctf_grapplereleasetime = level.time;
         cl->ctf_grapplestate = CTF_GRAPPLE_STATE_FLY; // we're firing, not on hook
         cl->ps.pmove.pm_flags &= ~PMF_NO_PREDICTION;
         G_FreeEdict(self);
     }
 }
Referenced by CTFGrappleDrawCable(), CTFGrapplePull(), CTFGrappleTouch(), CTFPlayerResetGrapple(), and CTFWeapon_Grapple().
CTFResetTech()
void CTFResetTech (void)
Definition at line 2052 of file g_ctf.c.
 {
     edict_t *ent;
     int i;
     for (ent = g_edicts + 1, i = 1; i < globals.num_edicts; i++, ent++) {
         if (ent->inuse)
             if (ent->item && (ent->item->flags & IT_TECH))
                 G_FreeEdict(ent);
     }
     SpawnTechs(NULL);
 }
Referenced by CTFResetAllPlayers().
CTFRespawnTech()
void CTFRespawnTech (edict_t * ent)
Definition at line 2031 of file g_ctf.c.
 {
     edict_t *spot;
     if ((spot = FindTechSpawn()) != NULL)
         SpawnTech(ent->item, spot);
     G_FreeEdict(ent);
 }
Referenced by BecomeExplosion1().
CTFSay_Team()
void CTFSay_Team (edict_t * who, char * msg)
Definition at line 2459 of file g_ctf.c.
 {
     char outmsg[256];
     char buf[256];
     int i;
     char *p;
     edict_t *cl_ent;
     if (CheckFlood(who))
         return;
     outmsg[0] = 0;
     if (*msg == '\"') {
         msg[strlen(msg) - 1] = 0;
         msg++;
     }
     for (p = outmsg; *msg && (p - outmsg) < sizeof(outmsg) - 2; msg++) {
         if (*msg == '%') {
             switch (*++msg) {
                 case 'l' :
                 case 'L' :
                     CTFSay_Team_Location(who, buf);
                     if (strlen(buf) + (p - outmsg) < sizeof(outmsg) - 2) {
                         strcpy(p, buf);
                         p += strlen(buf);
                     }
                     break;
                 case 'a' :
                 case 'A' :
                     CTFSay_Team_Armor(who, buf);
                     if (strlen(buf) + (p - outmsg) < sizeof(outmsg) - 2) {
                         strcpy(p, buf);
                         p += strlen(buf);
                     }
                     break;
                 case 'h' :
                 case 'H' :
                     CTFSay_Team_Health(who, buf);
                     if (strlen(buf) + (p - outmsg) < sizeof(outmsg) - 2) {
                         strcpy(p, buf);
                         p += strlen(buf);
                     }
                     break;
                 case 't' :
                 case 'T' :
                     CTFSay_Team_Tech(who, buf);
                     if (strlen(buf) + (p - outmsg) < sizeof(outmsg) - 2) {
                         strcpy(p, buf);
                         p += strlen(buf);
                     }
                     break;
                 case 'w' :
                 case 'W' :
                     CTFSay_Team_Weapon(who, buf);
                     if (strlen(buf) + (p - outmsg) < sizeof(outmsg) - 2) {
                         strcpy(p, buf);
                         p += strlen(buf);
                     }
                     break;
                 case 'n' :
                 case 'N' :
                     CTFSay_Team_Sight(who, buf);
                     if (strlen(buf) + (p - outmsg) < sizeof(outmsg) - 2) {
                         strcpy(p, buf);
                         p += strlen(buf);
                     }
                     break;
                 default :
                     *p++ = *msg;
             }
         } else
             *p++ = *msg;
     }
     *p = 0;
     for (i = 0; i < maxclients->value; i++) {
         cl_ent = g_edicts + 1 + i;
         if (!cl_ent->inuse)
             continue;
         if (cl_ent->client->resp.ctf_team == who->client->resp.ctf_team)
             gi.cprintf(cl_ent, PRINT_CHAT, "(%s): %s\n",
                 who->client->pers.netname, outmsg);
     }
 }
Referenced by ClientCommand().
CTFScoreboardMessage()
void CTFScoreboardMessage (edict_t * ent, edict_t * killer)
Definition at line 1661 of file g_ctf.c.
 {
     char    entry[1024];
     char    string[1400];
     int     len;
     int     i, j, k, n;
     int     sorted[2][MAX_CLIENTS];
     int     sortedscores[2][MAX_CLIENTS];
     int     score, total[2], totalscore[2];
     int     last[2];
     gclient_t   *cl;
     edict_t     *cl_ent;
     int team;
     int maxsize = 1000;
     // sort the clients by team and score
     total[0] = total[1] = 0;
     last[0] = last[1] = 0;
     totalscore[0] = totalscore[1] = 0;
     for (i=0 ; i<game.maxclients ; i++)
     {
         cl_ent = g_edicts + 1 + i;
         if (!cl_ent->inuse)
             continue;
         if (game.clients[i].resp.ctf_team == CTF_TEAM1)
             team = 0;
         else if (game.clients[i].resp.ctf_team == CTF_TEAM2)
             team = 1;
         else
             continue; // unknown team?
         score = game.clients[i].resp.score;
         for (j=0 ; j<total[team] ; j++)
         {
             if (score > sortedscores[team][j])
                 break;
         }
         for (k=total[team] ; k>j ; k--)
         {
             sorted[team][k] = sorted[team][k-1];
             sortedscores[team][k] = sortedscores[team][k-1];
         }
         sorted[team][j] = i;
         sortedscores[team][j] = score;
         totalscore[team] += score;
         total[team]++;
     }
     // print level name and exit rules
     // add the clients in sorted order
     *string = 0;
     len = 0;
     // team one
     sprintf(string, "if 24 xv 8 yv 8 pic 24 endif "
         "xv 40 yv 28 string \"%4d/%-3d\" "
         "xv 98 yv 12 num 2 18 "
         "if 25 xv 168 yv 8 pic 25 endif "
         "xv 200 yv 28 string \"%4d/%-3d\" "
         "xv 256 yv 12 num 2 20 ",
         totalscore[0], total[0],
         totalscore[1], total[1]);
     len = (int)strlen(string);
     for (i=0 ; i<16 ; i++)
     {
         if (i >= total[0] && i >= total[1])
             break; // we're done
 #if 0 //ndef NEW_SCORE
         // set up y
         sprintf(entry, "yv %d ", 42 + i * 8);
         if (maxsize - len > strlen(entry)) {
             strcat(string, entry);
             len = strlen(string);
         }
 #else
         *entry = 0;
 #endif
         // left side
         if (i < total[0]) {
             cl = &game.clients[sorted[0][i]];
             cl_ent = g_edicts + 1 + sorted[0][i];
 #if 0 //ndef NEW_SCORE
             sprintf(entry+strlen(entry),
             "xv 0 %s \"%3d %3d %-12.12s\" ",
             (cl_ent == ent) ? "string2" : "string",
             cl->resp.score,
             (cl->ping > 999) ? 999 : cl->ping,
             cl->pers.netname);
             if (cl_ent->client->pers.inventory[ITEM_INDEX(flag2_item)])
                 strcat(entry, "xv 56 picn sbfctf2 ");
 #else
             sprintf(entry+strlen(entry),
                 "ctf 0 %d %d %d %d ",
                 42 + i * 8,
                 sorted[0][i],
                 cl->resp.score,
                 cl->ping > 999 ? 999 : cl->ping);
             if (cl_ent->client->pers.inventory[ITEM_INDEX(flag2_item)])
                 sprintf(entry + strlen(entry), "xv 56 yv %d picn sbfctf2 ",
                     42 + i * 8);
 #endif
             if (maxsize - len > strlen(entry)) {
                 strcat(string, entry);
                 len = (int)strlen(string);
                 last[0] = i;
             }
         }
         // right side
         if (i < total[1]) {
             cl = &game.clients[sorted[1][i]];
             cl_ent = g_edicts + 1 + sorted[1][i];
 #if 0 //ndef NEW_SCORE
             sprintf(entry+strlen(entry),
             "xv 160 %s \"%3d %3d %-12.12s\" ",
             (cl_ent == ent) ? "string2" : "string",
             cl->resp.score,
             (cl->ping > 999) ? 999 : cl->ping,
             cl->pers.netname);
             if (cl_ent->client->pers.inventory[ITEM_INDEX(flag1_item)])
                 strcat(entry, "xv 216 picn sbfctf1 ");
 #else
             sprintf(entry+strlen(entry),
                 "ctf 160 %d %d %d %d ",
                 42 + i * 8,
                 sorted[1][i],
                 cl->resp.score,
                 cl->ping > 999 ? 999 : cl->ping);
             if (cl_ent->client->pers.inventory[ITEM_INDEX(flag1_item)])
                 sprintf(entry + strlen(entry), "xv 216 yv %d picn sbfctf1 ",
                     42 + i * 8);
 #endif
             if (maxsize - len > strlen(entry)) {
                 strcat(string, entry);
                 len = (int)strlen(string);
                 last[1] = i;
             }
         }
     }
     // put in spectators if we have enough room
     if (last[0] > last[1])
         j = last[0];
     else
         j = last[1];
     j = (j + 2) * 8 + 42;
     k = n = 0;
     if (maxsize - len > 50) {
         for (i = 0; i < maxclients->value; i++) {
             cl_ent = g_edicts + 1 + i;
             cl = &game.clients[i];
             if (!cl_ent->inuse ||
                 cl_ent->solid != SOLID_NOT ||
                 cl_ent->client->resp.ctf_team != CTF_NOTEAM)
                 continue;
             if (!k) {
                 k = 1;
                 sprintf(entry, "xv 0 yv %d string2 \"Spectators\" ", j);
                 strcat(string, entry);
                 len = (int)strlen(string);
                 j += 8;
             }
             sprintf(entry+strlen(entry),
                 "ctf %d %d %d %d %d ",
                 (n & 1) ? 160 : 0, // x
                 j, // y
                 i, // playernum
                 cl->resp.score,
                 cl->ping > 999 ? 999 : cl->ping);
             if (maxsize - len > strlen(entry)) {
                 strcat(string, entry);
                 len = (int)strlen(string);
             }
             if (n & 1)
                 j += 8;
             n++;
         }
     }
     if (total[0] - last[0] > 1) // couldn't fit everyone
         sprintf(string + strlen(string), "xv 8 yv %d string \"..and %d more\" ",
             42 + (last[0]+1)*8, total[0] - last[0] - 1);
     if (total[1] - last[1] > 1) // couldn't fit everyone
         sprintf(string + strlen(string), "xv 168 yv %d string \"..and %d more\" ",
             42 + (last[1]+1)*8, total[1] - last[1] - 1);
     gi.WriteByte (svc_layout);
     gi.WriteString (string);
 }
Referenced by DeathmatchScoreboardMessage().
CTFSetPowerUpEffect()
void CTFSetPowerUpEffect (edict_t * ent, int def)
Definition at line 4192 of file g_ctf.c.
 {
     if (ent->client->resp.ctf_team == CTF_TEAM1)
         ent->s.effects |= EF_PENT; // red
     else if (ent->client->resp.ctf_team == CTF_TEAM2)
         ent->s.effects |= EF_QUAD; // red
     else
         ent->s.effects |= def;
 }
Referenced by G_SetClientEffects().
CTFSetupTechSpawn()
void CTFSetupTechSpawn (void)
Definition at line 2040 of file g_ctf.c.
 {
     edict_t *ent;
     if (((int)dmflags->value & DF_CTF_NO_TECH))
         return;
     ent = G_Spawn();
     ent->nextthink = level.time + 2;
     ent->think = SpawnTechs;
 }
Referenced by CTFSpawn().
CTFSpawn()
void CTFSpawn (void)
Definition at line 326 of file g_ctf.c.
 {
     if (!flag1_item)
         flag1_item = FindItemByClassname("item_flag_team1");
     if (!flag2_item)
         flag2_item = FindItemByClassname("item_flag_team2");
     memset(&ctfgame, 0, sizeof(ctfgame));
     CTFSetupTechSpawn();
     if (competition->value > 1) {
         ctfgame.match = MATCH_SETUP;
         ctfgame.matchtime = level.time + matchsetuptime->value * 60;
     }
 }
Referenced by SpawnEntities().
CTFStartClient()
qboolean CTFStartClient (edict_t * ent)
Definition at line 3311 of file g_ctf.c.
 {
     if (ent->client->resp.ctf_team != CTF_NOTEAM)
         return false;
     if (!((int)dmflags->value & DF_CTF_FORCEJOIN) || ctfgame.match >= MATCH_SETUP) {
         // start as 'observer'
         ent->movetype = MOVETYPE_NOCLIP;
         ent->solid = SOLID_NOT;
         ent->svflags |= SVF_NOCLIENT;
         ent->client->resp.ctf_team = CTF_NOTEAM;
         ent->client->ps.gunindex = 0;
         gi.linkentity (ent);
         CTFOpenJoinMenu(ent);
         return true;
     }
     return false;
 }
Referenced by PutClientInServer().
CTFStats()
void CTFStats (edict_t * ent)
Definition at line 3994 of file g_ctf.c.
 {
     int i, e;
     ghost_t *g;
     char st[80];
     char text[1024];
     edict_t *e2;
     *text = 0;
     if (ctfgame.match == MATCH_SETUP) {
         for (i = 1; i <= maxclients->value; i++) {
             e2 = g_edicts + i;
             if (!e2->inuse)
                 continue;
             if (!e2->client->resp.ready && e2->client->resp.ctf_team != CTF_NOTEAM) {
                 sprintf(st, "%s is not ready.\n", e2->client->pers.netname);
                 if (strlen(text) + strlen(st) < sizeof(text) - 50)
                     strcat(text, st);
             }
         }
     }
     for (i = 0, g = ctfgame.ghosts; i < MAX_CLIENTS; i++, g++)
         if (g->ent)
             break;
     if (i == MAX_CLIENTS) {
         if (*text)
             gi.cprintf(ent, PRINT_HIGH, "%s", text);
         gi.cprintf(ent, PRINT_HIGH, "No statistics available.\n");
         return;
     }
     strcat(text, "  #|Name            |Score|Kills|Death|BasDf|CarDf|Effcy|\n");
     for (i = 0, g = ctfgame.ghosts; i < MAX_CLIENTS; i++, g++) {
         if (!*g->netname)
             continue;
         if (g->deaths + g->kills == 0)
             e = 50;
         else
             e = g->kills * 100 / (g->kills + g->deaths);
         sprintf(st, "%3d|%-16.16s|%5d|%5d|%5d|%5d|%5d|%4d%%|\n",
             g->number,
             g->netname,
             g->score,
             g->kills,
             g->deaths,
             g->basedef,
             g->carrierdef,
             e);
         if (strlen(text) + strlen(st) > sizeof(text) - 50) {
             sprintf(text+strlen(text), "And more...\n");
             gi.cprintf(ent, PRINT_HIGH, "%s", text);
             return;
         }
         strcat(text, st);
     }
     gi.cprintf(ent, PRINT_HIGH, "%s", text);
 }
Referenced by ClientCommand().
CTFTeam_f()
void CTFTeam_f (edict_t * ent)
Definition at line 1592 of file g_ctf.c.
 {
     char *t, *s;
     int desired_team;
     t = gi.args();
     if (!*t) {
         gi.cprintf(ent, PRINT_HIGH, "You are on the %s team.\n",
             CTFTeamName(ent->client->resp.ctf_team));
         return;
     }
     if (ctfgame.match > MATCH_SETUP) {
         gi.cprintf(ent, PRINT_HIGH, "Can't change teams in a match.\n");
         return;
     }
     if (Q_stricmp(t, "red") == 0)
         desired_team = CTF_TEAM1;
     else if (Q_stricmp(t, "blue") == 0)
         desired_team = CTF_TEAM2;
     else {
         gi.cprintf(ent, PRINT_HIGH, "Unknown team %s.\n", t);
         return;
     }
     if (ent->client->resp.ctf_team == desired_team) {
         gi.cprintf(ent, PRINT_HIGH, "You are already on the %s team.\n",
             CTFTeamName(ent->client->resp.ctf_team));
         return;
     }
     ent->svflags = 0;
     ent->flags &= ~FL_GODMODE;
     ent->client->resp.ctf_team = desired_team;
     ent->client->resp.ctf_state = 0;
     s = Info_ValueForKey (ent->client->pers.userinfo, "skin");
     CTFAssignSkin(ent, s);
     if (ent->solid == SOLID_NOT) { // spectator
         PutClientInServer (ent);
         // add a teleportation effect
         ent->s.event = EV_PLAYER_TELEPORT;
         // hold in place briefly
         ent->client->ps.pmove.pm_flags = PMF_TIME_TELEPORT;
         ent->client->ps.pmove.pm_time = 14;
         gi.bprintf(PRINT_HIGH, "%s joined the %s team.\n",
             ent->client->pers.netname, CTFTeamName(desired_team));
         return;
     }
     ent->health = 0;
     player_die (ent, ent, ent, 100000, vec3_origin);
     // don't even bother waiting for death frames
     ent->deadflag = DEAD_DEAD;
     respawn (ent);
     ent->client->resp.score = 0;
     gi.bprintf(PRINT_HIGH, "%s changed to the %s team.\n",
         ent->client->pers.netname, CTFTeamName(desired_team));
 }
Referenced by ClientCommand().
CTFTeamName()
char* CTFTeamName (int team)
Definition at line 378 of file g_ctf.c.
 {
     switch (team) {
     case CTF_TEAM1:
         return "RED";
     case CTF_TEAM2:
         return "BLUE";
     }
     return "UNKNOWN"; // Hanzo pointed out this was spelled wrong as "UKNOWN"
 }
Referenced by BecomeExplosion1(), CTFDeadDropFlag(), CTFDropFlagThink(), CTFFragBonuses(), CTFGhost(), CTFJoinTeam(), CTFPickup_Flag(), and CTFTeam_f().
CTFVoteNo()
void CTFVoteNo (edict_t * ent)
Definition at line 2874 of file g_ctf.c.
 {
     if (ctfgame.election == ELECT_NONE) {
         gi.cprintf(ent, PRINT_HIGH, "No election is in progress.\n");
         return;
     }
     if (ent->client->resp.voted) {
         gi.cprintf(ent, PRINT_HIGH, "You already voted.\n");
         return;
     }
     if (ctfgame.etarget == ent) {
         gi.cprintf(ent, PRINT_HIGH, "You can't vote for yourself.\n");
         return;
     }
     ent->client->resp.voted = true;
     gi.bprintf(PRINT_HIGH, "%s\n", ctfgame.emsg);
     gi.bprintf(PRINT_CHAT, "Votes: %d  Needed: %d  Time left: %ds\n", ctfgame.evotes, ctfgame.needvotes,
         (int)(ctfgame.electtime - level.time));
 }
Referenced by ClientCommand().
CTFVoteYes()
void CTFVoteYes (edict_t * ent)
Definition at line 2846 of file g_ctf.c.
 {
     if (ctfgame.election == ELECT_NONE) {
         gi.cprintf(ent, PRINT_HIGH, "No election is in progress.\n");
         return;
     }
     if (ent->client->resp.voted) {
         gi.cprintf(ent, PRINT_HIGH, "You already voted.\n");
         return;
     }
     if (ctfgame.etarget == ent) {
         gi.cprintf(ent, PRINT_HIGH, "You can't vote for yourself.\n");
         return;
     }
     ent->client->resp.voted = true;
     ctfgame.evotes++;
     if (ctfgame.evotes == ctfgame.needvotes) {
         // the election has been won
         CTFWinElection();
         return;
     }
     gi.bprintf(PRINT_HIGH, "%s\n", ctfgame.emsg);
     gi.bprintf(PRINT_CHAT, "Votes: %d  Needed: %d  Time left: %ds\n", ctfgame.evotes, ctfgame.needvotes,
         (int)(ctfgame.electtime - level.time));
 }
Referenced by ClientCommand().
CTFWarp()
void CTFWarp (edict_t * ent)
Definition at line 4109 of file g_ctf.c.
 {
     char text[1024];
     char *mlist, *token;
     static const char *seps = " \t\n\r";
     if (gi.argc() < 2) {
         gi.cprintf(ent, PRINT_HIGH, "Where do you want to warp to?\n");
         gi.cprintf(ent, PRINT_HIGH, "Available levels are: %s\n", warp_list->string);
         return;
     }
     mlist = strdup(warp_list->string);
     token = strtok(mlist, seps);
     while (token != NULL) {
         if (Q_stricmp(token, gi.argv(1)) == 0)
             break;
         token = strtok(NULL, seps);
     }
     if (token == NULL) {
         gi.cprintf(ent, PRINT_HIGH, "Unknown CTF level.\n");
         gi.cprintf(ent, PRINT_HIGH, "Available levels are: %s\n", warp_list->string);
         free(mlist);
         return;
     }
     free(mlist);
     if (ent->client->resp.admin) {
         gi.bprintf(PRINT_HIGH, "%s is warping to level %s.\n",
             ent->client->pers.netname, gi.argv(1));
         strncpy(level.forcemap, gi.argv(1), sizeof(level.forcemap) - 1);
         EndDMLevel();
         return;
     }
     sprintf(text, "%s has requested warping to level %s.",
             ent->client->pers.netname, gi.argv(1));
     if (CTFBeginElection(ent, ELECT_MAP, text))
         strncpy(ctfgame.elevel, gi.argv(1), sizeof(ctfgame.elevel) - 1);
 }
Referenced by ClientCommand().
CTFWeapon_Grapple()
void CTFWeapon_Grapple (edict_t * ent)
Definition at line 1548 of file g_ctf.c.
 {
     static int  pause_frames[]  = {10, 18, 27, 0};
     static int  fire_frames[]   = {6, 0};
     int prevstate;
     // if the the attack button is still down, stay in the firing frame
     if ((ent->client->buttons & BUTTON_ATTACK) &&
         ent->client->weaponstate == WEAPON_FIRING &&
         ent->client->ctf_grapple)
         ent->client->ps.gunframe = 9;
     if (!(ent->client->buttons & BUTTON_ATTACK) &&
         ent->client->ctf_grapple) {
         CTFResetGrapple(ent->client->ctf_grapple);
         if (ent->client->weaponstate == WEAPON_FIRING)
             ent->client->weaponstate = WEAPON_READY;
     }
     if (ent->client->newweapon &&
         ent->client->ctf_grapplestate > CTF_GRAPPLE_STATE_FLY &&
         ent->client->weaponstate == WEAPON_FIRING) {
         // he wants to change weapons while grappled
         ent->client->weaponstate = WEAPON_DROPPING;
         ent->client->ps.gunframe = 32;
     }
     prevstate = ent->client->weaponstate;
     Weapon_Generic (ent, 5, 9, 31, 36, pause_frames, fire_frames,
         CTFWeapon_Grapple_Fire);
     // if we just switched back to grapple, immediately go to fire frame
     if (prevstate == WEAPON_ACTIVATING &&
         ent->client->weaponstate == WEAPON_READY &&
         ent->client->ctf_grapplestate > CTF_GRAPPLE_STATE_FLY) {
         if (!(ent->client->buttons & BUTTON_ATTACK))
             ent->client->ps.gunframe = 9;
         else
             ent->client->ps.gunframe = 5;
         ent->client->weaponstate = WEAPON_FIRING;
     }
 }
CTFWhat_Tech()
gitem_t* CTFWhat_Tech (edict_t * ent)
Definition at line 1879 of file g_ctf.c.
 {
     gitem_t *tech;
     int i;
     i = 0;
     while (tnames[i]) {
         if ((tech = FindItemByClassname(tnames[i])) != NULL &&
             ent->client->pers.inventory[ITEM_INDEX(tech)]) {
             return tech;
         }
         i++;
     }
     return NULL;
 }
Referenced by Cmd_Drop_f().
SelectCTFSpawnPoint()
edict_t* SelectCTFSpawnPoint (edict_t * ent)
Definition at line 492 of file g_ctf.c.
 {
     edict_t *spot, *spot1, *spot2;
     int     count = 0;
     int     selection;
     float   range, range1, range2;
     char    *cname;
     if (ent->client->resp.ctf_state)
         if ( (int)(dmflags->value) & DF_SPAWN_FARTHEST)
             return SelectFarthestDeathmatchSpawnPoint ();
         else
             return SelectRandomDeathmatchSpawnPoint ();
     ent->client->resp.ctf_state++;
     switch (ent->client->resp.ctf_team) {
     case CTF_TEAM1:
         cname = "info_player_team1";
         break;
     case CTF_TEAM2:
         cname = "info_player_team2";
         break;
     default:
         return SelectRandomDeathmatchSpawnPoint();
     }
     spot = NULL;
     range1 = range2 = 99999;
     spot1 = spot2 = NULL;
     while ((spot = G_Find (spot, FOFS(classname), cname)) != NULL)
     {
         count++;
         range = PlayersRangeFromSpot(spot);
         if (range < range1)
         {
             range1 = range;
             spot1 = spot;
         }
         else if (range < range2)
         {
             range2 = range;
             spot2 = spot;
         }
     }
     if (!count)
         return SelectRandomDeathmatchSpawnPoint();
     if (count <= 2)
     {
         spot1 = spot2 = NULL;
     }
     else
         count -= 2;
     selection = rand() % count;
     spot = NULL;
     do
     {
         spot = G_Find (spot, FOFS(classname), cname);
         if (spot == spot1 || spot == spot2)
             selection++;
     } while(selection--);
     return spot;
 }
Referenced by SelectSpawnPoint().
SetCTFStats()
void SetCTFStats (edict_t * ent)
Definition at line 1081 of file g_ctf.c.
 {
     gitem_t *tech;
     int i;
     int p1, p2;
     edict_t *e;
     if (ctfgame.match > MATCH_NONE)
         ent->client->ps.stats[STAT_CTF_MATCH] = CONFIG_CTF_MATCH;
     else
         ent->client->ps.stats[STAT_CTF_MATCH] = 0;
     if (ctfgame.warnactive)
         ent->client->ps.stats[STAT_CTF_TEAMINFO] = CONFIG_CTF_TEAMINFO;
     else
         ent->client->ps.stats[STAT_CTF_TEAMINFO] = 0;
     //ghosting
     if (ent->client->resp.ghost) {
         ent->client->resp.ghost->score = ent->client->resp.score;
         strcpy(ent->client->resp.ghost->netname, ent->client->pers.netname);
         ent->client->resp.ghost->number = ent->s.number;
     }
     // logo headers for the frag display
     ent->client->ps.stats[STAT_CTF_TEAM1_HEADER] = imageindex_ctfsb1;
     ent->client->ps.stats[STAT_CTF_TEAM2_HEADER] = imageindex_ctfsb2;
     // if during intermission, we must blink the team header of the winning team
     if (level.intermissiontime && (level.framenum & 8)) { // blink 1/8th second
         // note that ctfgame.total[12] is set when we go to intermission
         if (ctfgame.team1 > ctfgame.team2)
             ent->client->ps.stats[STAT_CTF_TEAM1_HEADER] = 0;
         else if (ctfgame.team2 > ctfgame.team1)
             ent->client->ps.stats[STAT_CTF_TEAM2_HEADER] = 0;
         else if (ctfgame.total1 > ctfgame.total2) // frag tie breaker
             ent->client->ps.stats[STAT_CTF_TEAM1_HEADER] = 0;
         else if (ctfgame.total2 > ctfgame.total1)
             ent->client->ps.stats[STAT_CTF_TEAM2_HEADER] = 0;
         else { // tie game!
             ent->client->ps.stats[STAT_CTF_TEAM1_HEADER] = 0;
             ent->client->ps.stats[STAT_CTF_TEAM2_HEADER] = 0;
         }
     }
     // tech icon
     i = 0;
     ent->client->ps.stats[STAT_CTF_TECH] = 0;
     while (tnames[i]) {
         if ((tech = FindItemByClassname(tnames[i])) != NULL &&
             ent->client->pers.inventory[ITEM_INDEX(tech)]) {
             ent->client->ps.stats[STAT_CTF_TECH] = gi.imageindex(tech->icon);
             break;
         }
         i++;
     }
     // figure out what icon to display for team logos
     // three states:
     //   flag at base
     //   flag taken
     //   flag dropped
     p1 = imageindex_i_ctf1;
     e = G_Find(NULL, FOFS(classname), "item_flag_team1");
     if (e != NULL) {
         if (e->solid == SOLID_NOT) {
             int i;
             // not at base
             // check if on player
             p1 = imageindex_i_ctf1d; // default to dropped
             for (i = 1; i <= maxclients->value; i++)
                 if (g_edicts[i].inuse &&
                     g_edicts[i].client->pers.inventory[ITEM_INDEX(flag1_item)]) {
                     // enemy has it
                     p1 = imageindex_i_ctf1t;
                     break;
                 }
         } else if (e->spawnflags & DROPPED_ITEM)
             p1 = imageindex_i_ctf1d; // must be dropped
     }
     p2 = imageindex_i_ctf2;
     e = G_Find(NULL, FOFS(classname), "item_flag_team2");
     if (e != NULL) {
         if (e->solid == SOLID_NOT) {
             int i;
             // not at base
             // check if on player
             p2 = imageindex_i_ctf2d; // default to dropped
             for (i = 1; i <= maxclients->value; i++)
                 if (g_edicts[i].inuse &&
                     g_edicts[i].client->pers.inventory[ITEM_INDEX(flag2_item)]) {
                     // enemy has it
                     p2 = imageindex_i_ctf2t;
                     break;
                 }
         } else if (e->spawnflags & DROPPED_ITEM)
             p2 = imageindex_i_ctf2d; // must be dropped
     }
     ent->client->ps.stats[STAT_CTF_TEAM1_PIC] = p1;
     ent->client->ps.stats[STAT_CTF_TEAM2_PIC] = p2;
     if (ctfgame.last_flag_capture && level.time - ctfgame.last_flag_capture < 5) {
         if (ctfgame.last_capture_team == CTF_TEAM1)
             if (level.framenum & 8)
                 ent->client->ps.stats[STAT_CTF_TEAM1_PIC] = p1;
             else
                 ent->client->ps.stats[STAT_CTF_TEAM1_PIC] = 0;
         else
             if (level.framenum & 8)
                 ent->client->ps.stats[STAT_CTF_TEAM2_PIC] = p2;
             else
                 ent->client->ps.stats[STAT_CTF_TEAM2_PIC] = 0;
     }
     ent->client->ps.stats[STAT_CTF_TEAM1_CAPS] = ctfgame.team1;
     ent->client->ps.stats[STAT_CTF_TEAM2_CAPS] = ctfgame.team2;
     ent->client->ps.stats[STAT_CTF_FLAG_PIC] = 0;
     if (ent->client->resp.ctf_team == CTF_TEAM1 &&
         ent->client->pers.inventory[ITEM_INDEX(flag2_item)] &&
         (level.framenum & 8))
         ent->client->ps.stats[STAT_CTF_FLAG_PIC] = imageindex_i_ctf2;
     else if (ent->client->resp.ctf_team == CTF_TEAM2 &&
         ent->client->pers.inventory[ITEM_INDEX(flag1_item)] &&
         (level.framenum & 8))
         ent->client->ps.stats[STAT_CTF_FLAG_PIC] = imageindex_i_ctf1;
     ent->client->ps.stats[STAT_CTF_JOINED_TEAM1_PIC] = 0;
     ent->client->ps.stats[STAT_CTF_JOINED_TEAM2_PIC] = 0;
     if (ent->client->resp.ctf_team == CTF_TEAM1)
         ent->client->ps.stats[STAT_CTF_JOINED_TEAM1_PIC] = imageindex_i_ctfj;
     else if (ent->client->resp.ctf_team == CTF_TEAM2)
         ent->client->ps.stats[STAT_CTF_JOINED_TEAM2_PIC] = imageindex_i_ctfj;
     if (ent->client->resp.id_state)
         CTFSetIDView(ent);
     else {
         ent->client->ps.stats[STAT_CTF_ID_VIEW] = 0;
         ent->client->ps.stats[STAT_CTF_ID_VIEW_COLOR] = 0;
     }
 }
Referenced by G_SetStats().
SP_info_player_team1()
void SP_info_player_team1 (edict_t * self)
Definition at line 1233 of file g_ctf.c.
 {
 }
SP_info_player_team2()
void SP_info_player_team2 (edict_t * self)
Definition at line 1240 of file g_ctf.c.
 {
 }
SP_info_teleport_destination()
void SP_info_teleport_destination (edict_t * ent)
Definition at line 3605 of file g_ctf.c.
 {
     ent->s.origin[2] += 16;
 }
SP_misc_ctf_banner()
void SP_misc_ctf_banner (edict_t * ent)
Definition at line 2559 of file g_ctf.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_NOT;
     ent->s.modelindex = gi.modelindex ("models/ctf/banner/tris.md2");
     if (ent->spawnflags & 1) // team2
         ent->s.skinnum = 1;
     ent->s.frame = rand() % 16;
     gi.linkentity (ent);
     ent->think = misc_ctf_banner_think;
     ent->nextthink = level.time + FRAMETIME;
 }
SP_misc_ctf_small_banner()
void SP_misc_ctf_small_banner (edict_t * ent)
Definition at line 2578 of file g_ctf.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_NOT;
     ent->s.modelindex = gi.modelindex ("models/ctf/banner/small.md2");
     if (ent->spawnflags & 1) // team2
         ent->s.skinnum = 1;
     ent->s.frame = rand() % 16;
     gi.linkentity (ent);
     ent->think = misc_ctf_banner_think;
     ent->nextthink = level.time + FRAMETIME;
 }
SP_trigger_teleport()
void SP_trigger_teleport (edict_t * ent)
Definition at line 3574 of file g_ctf.c.
 {
     edict_t *s;
     int i;
     if (!ent->target)
     {
         gi.dprintf ("teleporter without a target.\n");
         G_FreeEdict (ent);
         return;
     }
     ent->svflags |= SVF_NOCLIENT;
     ent->solid = SOLID_TRIGGER;
     ent->touch = old_teleporter_touch;
     gi.setmodel (ent, ent->model);
     gi.linkentity (ent);
     // noise maker and splash effect dude
     s = G_Spawn();
     ent->enemy = s;
     for (i = 0; i < 3; i++)
         s->s.origin[i] = ent->mins[i] + (ent->maxs[i] - ent->mins[i])/2;
     s->s.sound = gi.soundindex ("world/hum1.wav");
     gi.linkentity(s);
 }
UpdateChaseCam()
void UpdateChaseCam (edict_t * ent)
Definition at line 23 of file g_chase.c.
 {
     vec3_t o, ownerv, goal;
     edict_t *targ;
     vec3_t forward, right;
     trace_t trace;
     int i;
     vec3_t oldgoal;
     vec3_t angles;
     // is our chase target gone?
     if (!ent->client->chase_target->inuse) {
         ent->client->chase_target = NULL;
         return;
     }
     targ = ent->client->chase_target;
     VectorCopy(targ->s.origin, ownerv);
     VectorCopy(ent->s.origin, oldgoal);
     ownerv[2] += targ->viewheight;
     VectorCopy(targ->client->v_angle, angles);
     if (angles[PITCH] > 56)
         angles[PITCH] = 56;
     AngleVectors (angles, forward, right, NULL);
     VectorNormalize(forward);
     VectorMA(ownerv, -30, forward, o);
     if (o[2] < targ->s.origin[2] + 20)
         o[2] = targ->s.origin[2] + 20;
     // jump animation lifts
     if (!targ->groundentity)
         o[2] += 16;
     trace = gi.trace(ownerv, vec3_origin, vec3_origin, o, targ, MASK_SOLID);
     VectorCopy(trace.endpos, goal);
     VectorMA(goal, 2, forward, goal);
     // pad for floors and ceilings
     VectorCopy(goal, o);
     o[2] += 6;
     trace = gi.trace(goal, vec3_origin, vec3_origin, o, targ, MASK_SOLID);
     if (trace.fraction < 1) {
         VectorCopy(trace.endpos, goal);
         goal[2] -= 6;
     }
     VectorCopy(goal, o);
     o[2] -= 6;
     trace = gi.trace(goal, vec3_origin, vec3_origin, o, targ, MASK_SOLID);
     if (trace.fraction < 1) {
         VectorCopy(trace.endpos, goal);
         goal[2] += 6;
     }
     ent->client->ps.pmove.pm_type = PM_FREEZE;
     VectorCopy(goal, ent->s.origin);
     for (i=0 ; i<3 ; i++)
         ent->client->ps.pmove.delta_angles[i] = ANGLE2SHORT(targ->client->v_angle[i] - ent->client->resp.cmd_angles[i]);
     VectorCopy(targ->client->v_angle, ent->client->ps.viewangles);
     VectorCopy(targ->client->v_angle, ent->client->v_angle);
     ent->viewheight = 0;
     ent->client->ps.pmove.pm_flags |= PMF_NO_PREDICTION;
     gi.linkentity(ent);
     if ((!ent->client->showscores && !ent->client->menu &&
         !ent->client->showinventory && !ent->client->showhelp &&
         !(level.framenum & 31)) || ent->client->update_chase) {
         char s[1024];
         ent->client->update_chase = false;
         sprintf(s, "xv 0 yb -68 string2 \"Chasing %s\"",
             targ->client->pers.netname);
         gi.WriteByte (svc_layout);
         gi.WriteString (s);
         gi.unicast(ent, false);
     }
 }
Variable Documentation
ctf
cvar_t* ctf
Definition at line 65 of file g_ctf.c.
Referenced by BeginIntermission(), bfg_think(), CheckDMRules(), CheckTeamDamage(), ClientUserinfoChanged(), Cmd_Inven_f(), CTFInit(), DeathmatchScoreboardMessage(), DoRespawn(), InitClientResp(), player_die(), SelectSpawnPoint(), SP_worldspawn(), SpawnItem(), and T_Damage().
ctf_statusbar
char* ctf_statusbar
Definition at line 95 of file g_ctf.c.
Referenced by SP_worldspawn().