vq2 doxygen: C:/entry/syn/github/vq2/ref_gl/gl_draw.c File Reference
gl_draw.c File Reference
#include "gl_local.h"
Functions
void Scrap_Upload (void)
void Draw_InitLocal (void)
void Draw_Char (int x, int y, int num)
image_t * Draw_FindPic (char *name)
void Draw_GetPicSize (int *w, int *h, char *pic)
void Draw_StretchPic (int x, int y, int w, int h, char *pic)
void Draw_Pic (int x, int y, char *pic)
void Draw_TileClear (int x, int y, int w, int h, char *pic)
void Draw_Fill (int x, int y, int w, int h, int c)
void Draw_FadeScreen (void)
void Draw_StretchRaw (int x, int y, int w, int h, int cols, int rows, byte *data)
Variables
image_t * draw_chars
qboolean scrap_dirty
unsigned r_rawpalette [256]
Function Documentation
Draw_Char()
void Draw_Char (int x, int y, int num)
Definition at line 56 of file gl_draw.c.
 {
     int             row, col;
     float           frow, fcol, size;
     num &= 255;
     if ( (num&127) == 32 )
         return;     // space
     if (y <= -8)
         return;         // totally off screen
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     row = num>>4;
     col = num&15;
     frow = row*0.0625;
     fcol = col*0.0625;
     size = 0.0625;
     GL_Bind (draw_chars->texnum);
     qglBegin (GL_QUADS);
     qglTexCoord2f (fcol, frow);
     qglVertex2f (x, y);
     qglTexCoord2f (fcol + size, frow);
     qglVertex2f (x+8*scale->value, y);
     qglTexCoord2f (fcol + size, frow + size);
     qglVertex2f (x+8*scale->value, y+8*scale->value);
     qglTexCoord2f (fcol, frow + size);
     qglVertex2f (x, y+8*scale->value);
     qglEnd ();
 }
Draw_FadeScreen()
void Draw_FadeScreen (void)
Definition at line 296 of file gl_draw.c.
 {
     qglEnable (GL_BLEND);
     qglDisable (GL_TEXTURE_2D);
     qglColor4f (0, 0, 0, 0.8);
     qglBegin (GL_QUADS);
     qglVertex2f (0,0);
     qglVertex2f (vid.width, 0);
     qglVertex2f (vid.width, vid.height);
     qglVertex2f (0, vid.height);
     qglEnd ();
     qglColor4f (1,1,1,1);
     qglEnable (GL_TEXTURE_2D);
     qglDisable (GL_BLEND);
 }
Draw_Fill()
void Draw_Fill (int x, int y, int w, int h, int c)
Definition at line 258 of file gl_draw.c.
 {
     union
     {
         unsigned    c;
         byte        v[4];
     } color;
     if ( (unsigned)c > 255)
         ri.Sys_Error (ERR_FATAL, "Draw_Fill: bad color");
     qglDisable (GL_TEXTURE_2D);
     color.c = d_8to24table[c];
     qglColor3f (color.v[0]/255.0,
         color.v[1]/255.0,
         color.v[2]/255.0);
     qglBegin (GL_QUADS);
     qglVertex2f (x,y);
     qglVertex2f (x+w, y);
     qglVertex2f (x+w, y+h);
     qglVertex2f (x, y+h);
     qglEnd ();
     qglColor3f (1,1,1);
     qglEnable (GL_TEXTURE_2D);
 }
Draw_FindPic()
image_t* Draw_FindPic (char * name)
Definition at line 97 of file gl_draw.c.
 {
     image_t *gl;
     char    fullname[MAX_QPATH];
     if (name[0] != '/' && name[0] != '\\')
     {
         Com_sprintf (fullname, sizeof(fullname), "pics/%s.pcx", name);
         gl = GL_FindImage (fullname, it_pic);
     }
     else
         gl = GL_FindImage (name+1, it_pic);
     return gl;
 }
Referenced by Draw_GetPicSize(), Draw_Pic(), Draw_StretchPic(), and Draw_TileClear().
Draw_GetPicSize()
void Draw_GetPicSize (int * w, int * h, char * pic)
Definition at line 118 of file gl_draw.c.
 {
     image_t *gl;
     gl = Draw_FindPic (pic);
     if (!gl)
     {
         *w = *h = -1;
         return;
     }
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     *w = gl->width * scale->value;
     *h = gl->height * scale->value;
 }
Draw_InitLocal()
void Draw_InitLocal (void)
Definition at line 36 of file gl_draw.c.
 {
     // load console characters (don't bilerp characters)
     draw_chars = GL_FindImage ("pics/conchars.pcx", it_pic);
     GL_Bind( draw_chars->texnum );
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
 }
Draw_Pic()
void Draw_Pic (int x, int y, char * pic)
Definition at line 179 of file gl_draw.c.
 {
     image_t *gl;
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     gl = Draw_FindPic (pic);
     if (!gl)
     {
         ri.Con_Printf (PRINT_ALL, "Can't find pic: %s\n", pic);
         return;
     }
     if (scrap_dirty)
         Scrap_Upload ();
     if ( ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) ) && !gl->has_alpha)
         qglDisable (GL_ALPHA_TEST);
     GL_Bind (gl->texnum);
     qglBegin (GL_QUADS);
     qglTexCoord2f (gl->sl, gl->tl);
     qglVertex2f (x, y);
     qglTexCoord2f (gl->sh, gl->tl);
     qglVertex2f (x+gl->width*scale->value, y);
     qglTexCoord2f (gl->sh, gl->th);
     qglVertex2f (x+gl->width*scale->value, y+gl->height*scale->value);
     qglTexCoord2f (gl->sl, gl->th);
     qglVertex2f (x, y+gl->height*scale->value);
     qglEnd ();
     if ( ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) )  && !gl->has_alpha)
         qglEnable (GL_ALPHA_TEST);
 }
Draw_StretchPic()
void Draw_StretchPic (int x, int y, int w, int h, char * pic)
Definition at line 140 of file gl_draw.c.
 {
     image_t *gl;
     gl = Draw_FindPic (pic);
     if (!gl)
     {
         ri.Con_Printf (PRINT_ALL, "Can't find pic: %s\n", pic);
         return;
     }
     if (scrap_dirty)
         Scrap_Upload ();
     if ( ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) ) && !gl->has_alpha)
         qglDisable (GL_ALPHA_TEST);
     GL_Bind (gl->texnum);
     qglBegin (GL_QUADS);
     qglTexCoord2f (gl->sl, gl->tl);
     qglVertex2f (x, y);
     qglTexCoord2f (gl->sh, gl->tl);
     qglVertex2f (x+w, y);
     qglTexCoord2f (gl->sh, gl->th);
     qglVertex2f (x+w, y+h);
     qglTexCoord2f (gl->sl, gl->th);
     qglVertex2f (x, y+h);
     qglEnd ();
     if ( ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) ) && !gl->has_alpha)
         qglEnable (GL_ALPHA_TEST);
 }
Draw_StretchRaw()
void Draw_StretchRaw (int x, int y, int w, int h, int cols, int rows, byte * data)
Definition at line 325 of file gl_draw.c.
 {
     unsigned    image32[256*256];
     unsigned char image8[256*256];
     int         i, j, trows;
     byte        *source;
     int         frac, fracstep;
     float       hscale;
     int         row;
     float       t;
     GL_Bind (0);
     if (rows<=256)
     {
         hscale = 1;
         trows = rows;
     }
     else
     {
         hscale = rows/256.0;
         trows = 256;
     }
     t = rows*hscale / 256;
     if ( !qglColorTableEXT )
     {
         unsigned *dest;
         for (i=0 ; i<trows ; i++)
         {
             row = (int)(i*hscale);
             if (row > rows)
                 break;
             source = data + cols*row;
             dest = &image32[i*256];
             fracstep = cols*0x10000/256;
             frac = fracstep >> 1;
             for (j=0 ; j<256 ; j++)
             {
                 dest[j] = r_rawpalette[source[frac>>16]];
                 frac += fracstep;
             }
         }
         qglTexImage2D (GL_TEXTURE_2D, 0, gl_tex_solid_format, 256, 256, 0, GL_RGBA, GL_UNSIGNED_BYTE, image32);
     }
     else
     {
         unsigned char *dest;
         for (i=0 ; i<trows ; i++)
         {
             row = (int)(i*hscale);
             if (row > rows)
                 break;
             source = data + cols*row;
             dest = &image8[i*256];
             fracstep = cols*0x10000/256;
             frac = fracstep >> 1;
             for (j=0 ; j<256 ; j++)
             {
                 dest[j] = source[frac>>16];
                 frac += fracstep;
             }
         }
         qglTexImage2D( GL_TEXTURE_2D,
                        0,
                        GL_COLOR_INDEX8_EXT,
                        256, 256,
                        0,
                        GL_COLOR_INDEX,
                        GL_UNSIGNED_BYTE,
                        image8 );
     }
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     if ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) )
         qglDisable (GL_ALPHA_TEST);
     qglBegin (GL_QUADS);
     qglTexCoord2f (0, 0);
     qglVertex2f (x, y);
     qglTexCoord2f (1, 0);
     qglVertex2f (x+w, y);
     qglTexCoord2f (1, t);
     qglVertex2f (x+w, y+h);
     qglTexCoord2f (0, t);
     qglVertex2f (x, y+h);
     qglEnd ();
     if ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) )
         qglEnable (GL_ALPHA_TEST);
 }
Draw_TileClear()
void Draw_TileClear (int x, int y, int w, int h, char * pic)
Definition at line 220 of file gl_draw.c.
 {
     image_t *image;
     image = Draw_FindPic (pic);
     if (!image)
     {
         ri.Con_Printf (PRINT_ALL, "Can't find pic: %s\n", pic);
         return;
     }
     if ( ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) )  && !image->has_alpha)
         qglDisable (GL_ALPHA_TEST);
     GL_Bind (image->texnum);
     qglBegin (GL_QUADS);
     qglTexCoord2f (x/64.0, y/64.0);
     qglVertex2f (x, y);
     qglTexCoord2f ( (x+w)/64.0, y/64.0);
     qglVertex2f (x+w, y);
     qglTexCoord2f ( (x+w)/64.0, (y+h)/64.0);
     qglVertex2f (x+w, y+h);
     qglTexCoord2f ( x/64.0, (y+h)/64.0 );
     qglVertex2f (x, y+h);
     qglEnd ();
     if ( ( ( gl_config.renderer == GL_RENDERER_MCD ) || ( gl_config.renderer & GL_RENDERER_RENDITION ) )  && !image->has_alpha)
         qglEnable (GL_ALPHA_TEST);
 }
Scrap_Upload()
void Scrap_Upload (void)
Definition at line 411 of file gl_image.c.
 {
     scrap_uploads++;
     GL_Bind(TEXNUM_SCRAPS);
     GL_Upload8 (scrap_texels[0], BLOCK_WIDTH, BLOCK_HEIGHT, false, false );
     scrap_dirty = false;
 }
Referenced by Draw_Pic(), and Draw_StretchPic().
Variable Documentation
draw_chars
image_t* draw_chars
Definition at line 25 of file gl_draw.c.
Referenced by Draw_Char(), and Draw_InitLocal().
r_rawpalette
unsigned r_rawpalette[256]
Definition at line 1572 of file gl_rmain.c.
Referenced by Draw_StretchRaw().
scrap_dirty
qboolean scrap_dirty
Definition at line 365 of file gl_image.c.
Referenced by Draw_Pic(), Draw_StretchPic(), GL_LoadPic(), and Scrap_Upload().