vkQuake2 doxygen: C:/entry/dev/vq2/src/game/g_misc.c File Reference
g_misc.c File Reference
#include "g_local.h"
Macros
#define START_OFF 1
#define CLOCK_MESSAGE_SIZE 16
Functions
void Use_Areaportal (edict_t *ent, edict_t *other, edict_t *activator)
void SP_func_areaportal (edict_t *ent)
void VelocityForDamage (int damage, vec3_t v)
void ClipGibVelocity (edict_t *ent)
void gib_think (edict_t *self)
void gib_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void gib_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void ThrowGib (edict_t *self, char *gibname, int damage, int type)
void ThrowHead (edict_t *self, char *gibname, int damage, int type)
void ThrowClientHead (edict_t *self, int damage)
void debris_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void ThrowDebris (edict_t *self, char *modelname, float speed, vec3_t origin)
void BecomeExplosion1 (edict_t *self)
void BecomeExplosion2 (edict_t *self)
void path_corner_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_path_corner (edict_t *self)
void point_combat_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_point_combat (edict_t *self)
void TH_viewthing (edict_t *ent)
void SP_viewthing (edict_t *ent)
void SP_info_null (edict_t *self)
void SP_info_notnull (edict_t *self)
static void light_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_light (edict_t *self)
void func_wall_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_func_wall (edict_t *self)
void func_object_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void func_object_release (edict_t *self)
void func_object_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_func_object (edict_t *self)
void func_explosive_explode (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void func_explosive_use (edict_t *self, edict_t *other, edict_t *activator)
void func_explosive_spawn (edict_t *self, edict_t *other, edict_t *activator)
void SP_func_explosive (edict_t *self)
void barrel_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void barrel_explode (edict_t *self)
void barrel_delay (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void SP_misc_explobox (edict_t *self)
void misc_blackhole_use (edict_t *ent, edict_t *other, edict_t *activator)
void misc_blackhole_think (edict_t *self)
void SP_misc_blackhole (edict_t *ent)
void misc_eastertank_think (edict_t *self)
void SP_misc_eastertank (edict_t *ent)
void misc_easterchick_think (edict_t *self)
void SP_misc_easterchick (edict_t *ent)
void misc_easterchick2_think (edict_t *self)
void SP_misc_easterchick2 (edict_t *ent)
void commander_body_think (edict_t *self)
void commander_body_use (edict_t *self, edict_t *other, edict_t *activator)
void commander_body_drop (edict_t *self)
void SP_monster_commander_body (edict_t *self)
void misc_banner_think (edict_t *ent)
void SP_misc_banner (edict_t *ent)
void misc_deadsoldier_die (edict_t *self, edict_t *inflictor, edict_t *attacker, int damage, vec3_t point)
void SP_misc_deadsoldier (edict_t *ent)
void train_use (edict_t *self, edict_t *other, edict_t *activator)
void func_train_find (edict_t *self)
void misc_viper_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_misc_viper (edict_t *ent)
void SP_misc_bigviper (edict_t *ent)
void misc_viper_bomb_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void misc_viper_bomb_prethink (edict_t *self)
void misc_viper_bomb_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_misc_viper_bomb (edict_t *self)
void misc_strogg_ship_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_misc_strogg_ship (edict_t *ent)
void misc_satellite_dish_think (edict_t *self)
void misc_satellite_dish_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_misc_satellite_dish (edict_t *ent)
void SP_light_mine1 (edict_t *ent)
void SP_light_mine2 (edict_t *ent)
void SP_misc_gib_arm (edict_t *ent)
void SP_misc_gib_leg (edict_t *ent)
void SP_misc_gib_head (edict_t *ent)
void SP_target_character (edict_t *self)
void target_string_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_target_string (edict_t *self)
static void func_clock_reset (edict_t *self)
static void func_clock_format_countdown (edict_t *self)
void func_clock_think (edict_t *self)
void func_clock_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_func_clock (edict_t *self)
void teleporter_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_misc_teleporter (edict_t *ent)
void SP_misc_teleporter_dest (edict_t *ent)
Macro Definition Documentation
CLOCK_MESSAGE_SIZE
#define CLOCK_MESSAGE_SIZE 16
Definition at line 1628 of file g_misc.c.
START_OFF
#define START_OFF 1
Definition at line 543 of file g_misc.c.
Function Documentation
barrel_delay()
void barrel_delay (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 966 of file g_misc.c.
 {
     self->takedamage = DAMAGE_NO;
     self->nextthink = level.time + 2 * FRAMETIME;
     self->think = barrel_explode;
     self->activator = attacker;
 }
Referenced by SP_misc_explobox().
barrel_explode()
void barrel_explode (edict_t * self)
Definition at line 887 of file g_misc.c.
 {
     vec3_t  org;
     float   spd;
     vec3_t  save;
     T_RadiusDamage (self, self->activator, self->dmg, NULL, self->dmg+40, MOD_BARREL);
     VectorCopy (self->s.origin, save);
     VectorMA (self->absmin, 0.5, self->size, self->s.origin);
     // a few big chunks
     spd = 1.5 * (float)self->dmg / 200.0;
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris1/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris1/tris.md2", spd, org);
     // bottom corners
     spd = 1.75 * (float)self->dmg / 200.0;
     VectorCopy (self->absmin, org);
     ThrowDebris (self, "models/objects/debris3/tris.md2", spd, org);
     VectorCopy (self->absmin, org);
     org[0] += self->size[0];
     ThrowDebris (self, "models/objects/debris3/tris.md2", spd, org);
     VectorCopy (self->absmin, org);
     org[1] += self->size[1];
     ThrowDebris (self, "models/objects/debris3/tris.md2", spd, org);
     VectorCopy (self->absmin, org);
     org[0] += self->size[0];
     org[1] += self->size[1];
     ThrowDebris (self, "models/objects/debris3/tris.md2", spd, org);
     // a bunch of little chunks
     spd = 2 * self->dmg / 200;
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     org[0] = self->s.origin[0] + crandom() * self->size[0];
     org[1] = self->s.origin[1] + crandom() * self->size[1];
     org[2] = self->s.origin[2] + crandom() * self->size[2];
     ThrowDebris (self, "models/objects/debris2/tris.md2", spd, org);
     VectorCopy (save, self->s.origin);
     if (self->groundentity)
         BecomeExplosion2 (self);
     else
         BecomeExplosion1 (self);
 }
Referenced by barrel_delay().
barrel_touch()
void barrel_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 873 of file g_misc.c.
 {
     float   ratio;
     vec3_t  v;
     if ((!other->groundentity) || (other->groundentity == self))
         return;
     ratio = (float)other->mass / (float)self->mass;
     VectorSubtract (self->s.origin, other->s.origin, v);
     M_walkmove (self, vectoyaw(v), 20 * ratio * FRAMETIME);
 }
Referenced by SP_misc_explobox().
BecomeExplosion1()
void BecomeExplosion1 (edict_t * self)
Definition at line 314 of file g_misc.c.
 {
     gi.WriteByte (svc_temp_entity);
     gi.WriteByte (TE_EXPLOSION1);
     gi.WritePosition (self->s.origin);
     gi.multicast (self->s.origin, MULTICAST_PVS);
     G_FreeEdict (self);
 }
Referenced by barrel_explode(), door_blocked(), door_secret_blocked(), floater_die(), flyer_die(), func_explosive_explode(), hover_deadthink(), plat_blocked(), and train_blocked().
BecomeExplosion2()
void BecomeExplosion2 (edict_t * self)
Definition at line 325 of file g_misc.c.
 {
     gi.WriteByte (svc_temp_entity);
     gi.WriteByte (TE_EXPLOSION2);
     gi.WritePosition (self->s.origin);
     gi.multicast (self->s.origin, MULTICAST_PVS);
     G_FreeEdict (self);
 }
Referenced by barrel_explode(), and misc_viper_bomb_touch().
ClipGibVelocity()
void ClipGibVelocity (edict_t * ent)
Definition at line 70 of file g_misc.c.
 {
     if (ent->velocity[0] < -300)
         ent->velocity[0] = -300;
     else if (ent->velocity[0] > 300)
         ent->velocity[0] = 300;
     if (ent->velocity[1] < -300)
         ent->velocity[1] = -300;
     else if (ent->velocity[1] > 300)
         ent->velocity[1] = 300;
     if (ent->velocity[2] < 200)
         ent->velocity[2] = 200; // always some upwards
     else if (ent->velocity[2] > 500)
         ent->velocity[2] = 500;
 }
Referenced by ThrowGib(), and ThrowHead().
commander_body_drop()
void commander_body_drop (edict_t * self)
Definition at line 1164 of file g_misc.c.
 {
     self->movetype = MOVETYPE_TOSS;
     self->s.origin[2] += 2;
 }
Referenced by SP_monster_commander_body().
commander_body_think()
void commander_body_think (edict_t * self)
Definition at line 1146 of file g_misc.c.
 {
     if (++self->s.frame < 24)
         self->nextthink = level.time + FRAMETIME;
     else
         self->nextthink = 0;
     if (self->s.frame == 22)
         gi.sound (self, CHAN_BODY, gi.soundindex ("tank/thud.wav"), 1, ATTN_NORM, 0);
 }
Referenced by commander_body_use().
commander_body_use()
void commander_body_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1157 of file g_misc.c.
 {
     self->think = commander_body_think;
     self->nextthink = level.time + FRAMETIME;
     gi.sound (self, CHAN_BODY, gi.soundindex ("tank/pain.wav"), 1, ATTN_NORM, 0);
 }
Referenced by SP_monster_commander_body().
debris_die()
void debris_die (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 281 of file g_misc.c.
 {
     G_FreeEdict (self);
 }
Referenced by ThrowDebris().
func_clock_format_countdown()
static void func_clock_format_countdown (edict_t * self) static
Definition at line 1648 of file g_misc.c.
 {
     if (self->style == 0)
     {
         Com_sprintf (self->message, CLOCK_MESSAGE_SIZE, "%2i", self->health);
         return;
     }
     if (self->style == 1)
     {
         Com_sprintf(self->message, CLOCK_MESSAGE_SIZE, "%2i:%2i", self->health / 60, self->health % 60);
         if (self->message[3] == ' ')
             self->message[3] = '0';
         return;
     }
     if (self->style == 2)
     {
         Com_sprintf(self->message, CLOCK_MESSAGE_SIZE, "%2i:%2i:%2i", self->health / 3600, (self->health - (self->health / 3600) * 3600) / 60, self->health % 60);
         if (self->message[3] == ' ')
             self->message[3] = '0';
         if (self->message[6] == ' ')
             self->message[6] = '0';
         return;
     }
 }
Referenced by func_clock_think().
func_clock_reset()
static void func_clock_reset (edict_t * self) static
Definition at line 1633 of file g_misc.c.
 {
     self->activator = NULL;
     if (self->spawnflags & 1)
     {
         self->health = 0;
         self->wait = self->count;
     }
     else if (self->spawnflags & 2)
     {
         self->health = self->count;
         self->wait = 0;
     }
 }
Referenced by func_clock_think(), and SP_func_clock().
func_clock_think()
void func_clock_think (edict_t * self)
Definition at line 1675 of file g_misc.c.
 {
     if (!self->enemy)
     {
         self->enemy = G_Find (NULL, FOFS(targetname), self->target);
         if (!self->enemy)
             return;
     }
     if (self->spawnflags & 1)
     {
         func_clock_format_countdown (self);
         self->health++;
     }
     else if (self->spawnflags & 2)
     {
         func_clock_format_countdown (self);
         self->health--;
     }
     else
     {
         struct tm   *ltime;
         time_t      gmtime;
         time(&gmtime);
         ltime = localtime(&gmtime);
         Com_sprintf (self->message, CLOCK_MESSAGE_SIZE, "%2i:%2i:%2i", ltime->tm_hour, ltime->tm_min, ltime->tm_sec);
         if (self->message[3] == ' ')
             self->message[3] = '0';
         if (self->message[6] == ' ')
             self->message[6] = '0';
     }
     self->enemy->message = self->message;
     self->enemy->use (self->enemy, self, self);
     if (((self->spawnflags & 1) && (self->health > self->wait)) ||
         ((self->spawnflags & 2) && (self->health < self->wait)))
     {
         if (self->pathtarget)
         {
             char *savetarget;
             char *savemessage;
             savetarget = self->target;
             savemessage = self->message;
             self->target = self->pathtarget;
             self->message = NULL;
             G_UseTargets (self, self->activator);
             self->target = savetarget;
             self->message = savemessage;
         }
         if (!(self->spawnflags & 8))
             return;
         func_clock_reset (self);
         if (self->spawnflags & 4)
             return;
     }
     self->nextthink = level.time + 1;
 }
Referenced by SP_func_clock().
func_clock_use()
void func_clock_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1740 of file g_misc.c.
 {
     if (!(self->spawnflags & 8))
         self->use = NULL;
     if (self->activator)
         return;
     self->activator = activator;
     self->think (self);
 }
Referenced by SP_func_clock().
func_explosive_explode()
void func_explosive_explode (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 745 of file g_misc.c.
 {
     vec3_t  origin;
     vec3_t  chunkorigin;
     vec3_t  size;
     int     count;
     int     mass;
     // bmodel origins are (0 0 0), we need to adjust that here
     VectorScale (self->size, 0.5, size);
     VectorAdd (self->absmin, size, origin);
     VectorCopy (origin, self->s.origin);
     self->takedamage = DAMAGE_NO;
     if (self->dmg)
         T_RadiusDamage (self, attacker, self->dmg, NULL, self->dmg+40, MOD_EXPLOSIVE);
     VectorSubtract (self->s.origin, inflictor->s.origin, self->velocity);
     VectorNormalize (self->velocity);
     VectorScale (self->velocity, 150, self->velocity);
     // start chunks towards the center
     VectorScale (size, 0.5, size);
     mass = self->mass;
     if (!mass)
         mass = 75;
     // big chunks
     if (mass >= 100)
     {
         count = mass / 100;
         if (count > 8)
             count = 8;
         while(count--)
         {
             chunkorigin[0] = origin[0] + crandom() * size[0];
             chunkorigin[1] = origin[1] + crandom() * size[1];
             chunkorigin[2] = origin[2] + crandom() * size[2];
             ThrowDebris (self, "models/objects/debris1/tris.md2", 1, chunkorigin);
         }
     }
     // small chunks
     count = mass / 25;
     if (count > 16)
         count = 16;
     while(count--)
     {
         chunkorigin[0] = origin[0] + crandom() * size[0];
         chunkorigin[1] = origin[1] + crandom() * size[1];
         chunkorigin[2] = origin[2] + crandom() * size[2];
         ThrowDebris (self, "models/objects/debris2/tris.md2", 2, chunkorigin);
     }
     G_UseTargets (self, attacker);
     if (self->dmg)
         BecomeExplosion1 (self);
     else
         G_FreeEdict (self);
 }
Referenced by func_explosive_use(), and SP_func_explosive().
func_explosive_spawn()
void func_explosive_spawn (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 814 of file g_misc.c.
 {
     self->solid = SOLID_BSP;
     self->svflags &= ~SVF_NOCLIENT;
     self->use = NULL;
     KillBox (self);
     gi.linkentity (self);
 }
Referenced by SP_func_explosive().
func_explosive_use()
void func_explosive_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 809 of file g_misc.c.
 {
     func_explosive_explode (self, self, other, self->health, vec3_origin);
 }
Referenced by SP_func_explosive().
func_object_release()
void func_object_release (edict_t * self)
Definition at line 677 of file g_misc.c.
 {
     self->movetype = MOVETYPE_TOSS;
     self->touch = func_object_touch;
 }
Referenced by func_object_use(), and SP_func_object().
func_object_touch()
void func_object_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 665 of file g_misc.c.
 {
     // only squash thing we fall on top of
     if (!plane)
         return;
     if (plane->normal[2] < 1.0)
         return;
     if (other->takedamage == DAMAGE_NO)
         return;
     T_Damage (other, self, self, vec3_origin, self->s.origin, vec3_origin, self->dmg, 1, 0, MOD_CRUSH);
 }
Referenced by func_object_release().
func_object_use()
void func_object_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 683 of file g_misc.c.
 {
     self->solid = SOLID_BSP;
     self->svflags &= ~SVF_NOCLIENT;
     self->use = NULL;
     KillBox (self);
     func_object_release (self);
 }
Referenced by SP_func_object().
func_train_find()
void func_train_find (edict_t * self)
Definition at line 1601 of file g_func.c.
 {
     edict_t *ent;
     if (!self->target)
     {
         gi.dprintf ("train_find: no target\n");
         return;
     }
     ent = G_PickTarget (self->target);
     if (!ent)
     {
         gi.dprintf ("train_find: target %s not found\n", self->target);
         return;
     }
     self->target = ent->target;
     VectorSubtract (ent->s.origin, self->mins, self->s.origin);
     gi.linkentity (self);
     // if not triggered, start immediately
     if (!self->targetname)
         self->spawnflags |= TRAIN_START_ON;
     if (self->spawnflags & TRAIN_START_ON)
     {
         self->nextthink = level.time + FRAMETIME;
         self->think = train_next;
         self->activator = self;
     }
 }
Referenced by SP_func_train(), SP_misc_strogg_ship(), and SP_misc_viper().
func_wall_use()
void func_wall_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 593 of file g_misc.c.
 {
     if (self->solid == SOLID_NOT)
     {
         self->solid = SOLID_BSP;
         self->svflags &= ~SVF_NOCLIENT;
         KillBox (self);
     }
     else
     {
         self->solid = SOLID_NOT;
         self->svflags |= SVF_NOCLIENT;
     }
     gi.linkentity (self);
     if (!(self->spawnflags & 2))
         self->use = NULL;
 }
Referenced by SP_func_wall().
gib_die()
void gib_die (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 130 of file g_misc.c.
 {
     G_FreeEdict (self);
 }
Referenced by SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), ThrowGib(), and ThrowHead().
gib_think()
void gib_think (edict_t * self)
Definition at line 92 of file g_misc.c.
 {
     self->s.frame++;
     self->nextthink = level.time + FRAMETIME;
     if (self->s.frame == 10)
     {
         self->think = G_FreeEdict;
         self->nextthink = level.time + 8 + random()*10;
     }
 }
Referenced by gib_touch().
gib_touch()
void gib_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 104 of file g_misc.c.
 {
     vec3_t  normal_angles, right;
     if (!self->groundentity)
         return;
     self->touch = NULL;
     if (plane)
     {
         gi.sound (self, CHAN_VOICE, gi.soundindex ("misc/fhit3.wav"), 1, ATTN_NORM, 0);
         vectoangles (plane->normal, normal_angles);
         AngleVectors (normal_angles, NULL, right, NULL);
         vectoangles (right, self->s.angles);
         if (self->s.modelindex == sm_meat_index)
         {
             self->s.frame++;
             self->think = gib_think;
             self->nextthink = level.time + FRAMETIME;
         }
     }
 }
Referenced by ThrowGib(), and ThrowHead().
light_use()
static void light_use (edict_t * self, edict_t * other, edict_t * activator) static
Definition at line 545 of file g_misc.c.
 {
     if (self->spawnflags & START_OFF)
     {
         gi.configstring (CS_LIGHTS+self->style, "m");
         self->spawnflags &= ~START_OFF;
     }
     else
     {
         gi.configstring (CS_LIGHTS+self->style, "a");
         self->spawnflags |= START_OFF;
     }
 }
Referenced by SP_light().
misc_banner_think()
void misc_banner_think (edict_t * ent)
Definition at line 1196 of file g_misc.c.
 {
     ent->s.frame = (ent->s.frame + 1) % 16;
     ent->nextthink = level.time + FRAMETIME;
 }
Referenced by SP_misc_banner().
misc_blackhole_think()
void misc_blackhole_think (edict_t * self)
Definition at line 1032 of file g_misc.c.
 {
     if (++self->s.frame < 19)
         self->nextthink = level.time + FRAMETIME;
     else
     {
         self->s.frame = 0;
         self->nextthink = level.time + FRAMETIME;
     }
 }
Referenced by SP_misc_blackhole().
misc_blackhole_use()
void misc_blackhole_use (edict_t * ent, edict_t * other, edict_t * activator)
Definition at line 1021 of file g_misc.c.
 {
     /*
     gi.WriteByte (svc_temp_entity);
     gi.WriteByte (TE_BOSSTPORT);
     gi.WritePosition (ent->s.origin);
     gi.multicast (ent->s.origin, MULTICAST_PVS);
     */
     G_FreeEdict (ent);
 }
Referenced by SP_misc_blackhole().
misc_deadsoldier_die()
void misc_deadsoldier_die (edict_t * self, edict_t * inflictor, edict_t * attacker, int damage, vec3_t point)
Definition at line 1217 of file g_misc.c.
 {
     int     n;
     if (self->health > -80)
         return;
     gi.sound (self, CHAN_BODY, gi.soundindex ("misc/udeath.wav"), 1, ATTN_NORM, 0);
     for (n= 0; n < 4; n++)
         ThrowGib (self, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
     ThrowHead (self, "models/objects/gibs/head2/tris.md2", damage, GIB_ORGANIC);
 }
Referenced by SP_misc_deadsoldier().
misc_easterchick2_think()
void misc_easterchick2_think (edict_t * self)
Definition at line 1116 of file g_misc.c.
 {
     if (++self->s.frame < 287)
         self->nextthink = level.time + FRAMETIME;
     else
     {
         self->s.frame = 248;
         self->nextthink = level.time + FRAMETIME;
     }
 }
Referenced by SP_misc_easterchick2().
misc_easterchick_think()
void misc_easterchick_think (edict_t * self)
Definition at line 1088 of file g_misc.c.
 {
     if (++self->s.frame < 247)
         self->nextthink = level.time + FRAMETIME;
     else
     {
         self->s.frame = 208;
         self->nextthink = level.time + FRAMETIME;
     }
 }
Referenced by SP_misc_easterchick().
misc_eastertank_think()
void misc_eastertank_think (edict_t * self)
Definition at line 1060 of file g_misc.c.
 {
     if (++self->s.frame < 293)
         self->nextthink = level.time + FRAMETIME;
     else
     {
         self->s.frame = 254;
         self->nextthink = level.time + FRAMETIME;
     }
 }
Referenced by SP_misc_eastertank().
misc_satellite_dish_think()
void misc_satellite_dish_think (edict_t * self)
Definition at line 1445 of file g_misc.c.
 {
     self->s.frame++;
     if (self->s.frame < 38)
         self->nextthink = level.time + FRAMETIME;
 }
Referenced by misc_satellite_dish_use().
misc_satellite_dish_use()
void misc_satellite_dish_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1452 of file g_misc.c.
 {
     self->s.frame = 0;
     self->think = misc_satellite_dish_think;
     self->nextthink = level.time + FRAMETIME;
 }
Referenced by SP_misc_satellite_dish().
misc_strogg_ship_use()
void misc_strogg_ship_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1408 of file g_misc.c.
 {
     self->svflags &= ~SVF_NOCLIENT;
     self->use = train_use;
     train_use (self, other, activator);
 }
Referenced by SP_misc_strogg_ship().
misc_viper_bomb_prethink()
void misc_viper_bomb_prethink (edict_t * self)
Definition at line 1339 of file g_misc.c.
 {
     vec3_t  v;
     float   diff;
     self->groundentity = NULL;
     diff = self->timestamp - level.time;
     if (diff < -1.0)
         diff = -1.0;
     VectorScale (self->moveinfo.dir, 1.0 + diff, v);
     v[2] = diff;
     diff = self->s.angles[2];
     vectoangles (v, self->s.angles);
     self->s.angles[2] = diff + 10;
 }
Referenced by misc_viper_bomb_use().
misc_viper_bomb_touch()
void misc_viper_bomb_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 1330 of file g_misc.c.
 {
     G_UseTargets (self, self->activator);
     self->s.origin[2] = self->absmin[2] + 1;
     T_RadiusDamage (self, self, self->dmg, NULL, self->dmg+40, MOD_BOMB);
     BecomeExplosion2 (self);
 }
Referenced by misc_viper_bomb_use().
misc_viper_bomb_use()
void misc_viper_bomb_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1358 of file g_misc.c.
 {
     edict_t *viper;
     self->solid = SOLID_BBOX;
     self->svflags &= ~SVF_NOCLIENT;
     self->s.effects |= EF_ROCKET;
     self->use = NULL;
     self->movetype = MOVETYPE_TOSS;
     self->prethink = misc_viper_bomb_prethink;
     self->touch = misc_viper_bomb_touch;
     self->activator = activator;
     viper = G_Find (NULL, FOFS(classname), "misc_viper");
     VectorScale (viper->moveinfo.dir, viper->moveinfo.speed, self->velocity);
     self->timestamp = level.time;
     VectorCopy (viper->moveinfo.dir, self->moveinfo.dir);
 }
Referenced by SP_misc_viper_bomb().
misc_viper_use()
void misc_viper_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1278 of file g_misc.c.
 {
     self->svflags &= ~SVF_NOCLIENT;
     self->use = train_use;
     train_use (self, other, activator);
 }
Referenced by SP_misc_viper().
path_corner_touch()
void path_corner_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 342 of file g_misc.c.
 {
     vec3_t      v;
     edict_t     *next;
     if (other->movetarget != self)
         return;
     if (other->enemy)
         return;
     if (self->pathtarget)
     {
         char *savetarget;
         savetarget = self->target;
         self->target = self->pathtarget;
         G_UseTargets (self, other);
         self->target = savetarget;
     }
     if (self->target)
         next = G_PickTarget(self->target);
     else
         next = NULL;
     if ((next) && (next->spawnflags & 1))
     {
         VectorCopy (next->s.origin, v);
         v[2] += next->mins[2];
         v[2] -= other->mins[2];
         VectorCopy (v, other->s.origin);
         next = G_PickTarget(next->target);
         other->s.event = EV_OTHER_TELEPORT;
     }
     other->goalentity = other->movetarget = next;
     if (self->wait)
     {
         other->monsterinfo.pausetime = level.time + self->wait;
         other->monsterinfo.stand (other);
         return;
     }
     if (!other->movetarget)
     {
         other->monsterinfo.pausetime = level.time + 100000000;
         other->monsterinfo.stand (other);
     }
     else
     {
         VectorSubtract (other->goalentity->s.origin, other->s.origin, v);
         other->ideal_yaw = vectoyaw (v);
     }
 }
Referenced by SP_path_corner().
point_combat_touch()
void point_combat_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 422 of file g_misc.c.
 {
     edict_t *activator;
     if (other->movetarget != self)
         return;
     if (self->target)
     {
         other->target = self->target;
         other->goalentity = other->movetarget = G_PickTarget(other->target);
         if (!other->goalentity)
         {
             gi.dprintf("%s at %s target %s does not exist\n", self->classname, vtos(self->s.origin), self->target);
             other->movetarget = self;
         }
         self->target = NULL;
     }
     else if ((self->spawnflags & 1) && !(other->flags & (FL_SWIM|FL_FLY)))
     {
         other->monsterinfo.pausetime = level.time + 100000000;
         other->monsterinfo.aiflags |= AI_STAND_GROUND;
         other->monsterinfo.stand (other);
     }
     if (other->movetarget == self)
     {
         other->target = NULL;
         other->movetarget = NULL;
         other->goalentity = other->enemy;
         other->monsterinfo.aiflags &= ~AI_COMBAT_POINT;
     }
     if (self->pathtarget)
     {
         char *savetarget;
         savetarget = self->target;
         self->target = self->pathtarget;
         if (other->enemy && other->enemy->client)
             activator = other->enemy;
         else if (other->oldenemy && other->oldenemy->client)
             activator = other->oldenemy;
         else if (other->activator && other->activator->client)
             activator = other->activator;
         else
             activator = other;
         G_UseTargets (self, activator);
         self->target = savetarget;
     }
 }
Referenced by SP_point_combat().
SP_func_areaportal()
void SP_func_areaportal (edict_t * ent)
Definition at line 44 of file g_misc.c.
 {
     ent->use = Use_Areaportal;
     ent->count = 0;     // always start closed;
 }
SP_func_clock()
void SP_func_clock (edict_t * self)
Definition at line 1750 of file g_misc.c.
 {
     if (!self->target)
     {
         gi.dprintf("%s with no target at %s\n", self->classname, vtos(self->s.origin));
         G_FreeEdict (self);
         return;
     }
     if ((self->spawnflags & 2) && (!self->count))
     {
         gi.dprintf("%s with no count at %s\n", self->classname, vtos(self->s.origin));
         G_FreeEdict (self);
         return;
     }
     if ((self->spawnflags & 1) && (!self->count))
         self->count = 60*60;;
     func_clock_reset (self);
     self->message = gi.TagMalloc (CLOCK_MESSAGE_SIZE, TAG_LEVEL);
     self->think = func_clock_think;
     if (self->spawnflags & 4)
         self->use = func_clock_use;
     else
         self->nextthink = level.time + 1;
 }
SP_func_explosive()
void SP_func_explosive (edict_t * self)
Definition at line 823 of file g_misc.c.
 {
     if (deathmatch->value)
     {   // auto-remove for deathmatch
         G_FreeEdict (self);
         return;
     }
     self->movetype = MOVETYPE_PUSH;
     gi.modelindex ("models/objects/debris1/tris.md2");
     gi.modelindex ("models/objects/debris2/tris.md2");
     gi.setmodel (self, self->model);
     if (self->spawnflags & 1)
     {
         self->svflags |= SVF_NOCLIENT;
         self->solid = SOLID_NOT;
         self->use = func_explosive_spawn;
     }
     else
     {
         self->solid = SOLID_BSP;
         if (self->targetname)
             self->use = func_explosive_use;
     }
     if (self->spawnflags & 2)
         self->s.effects |= EF_ANIM_ALL;
     if (self->spawnflags & 4)
         self->s.effects |= EF_ANIM_ALLFAST;
     if (self->use != func_explosive_use)
     {
         if (!self->health)
             self->health = 100;
         self->die = func_explosive_explode;
         self->takedamage = DAMAGE_YES;
     }
     gi.linkentity (self);
 }
SP_func_object()
void SP_func_object (edict_t * self)
Definition at line 692 of file g_misc.c.
 {
     gi.setmodel (self, self->model);
     self->mins[0] += 1;
     self->mins[1] += 1;
     self->mins[2] += 1;
     self->maxs[0] -= 1;
     self->maxs[1] -= 1;
     self->maxs[2] -= 1;
     if (!self->dmg)
         self->dmg = 100;
     if (self->spawnflags == 0)
     {
         self->solid = SOLID_BSP;
         self->movetype = MOVETYPE_PUSH;
         self->think = func_object_release;
         self->nextthink = level.time + 2 * FRAMETIME;
     }
     else
     {
         self->solid = SOLID_NOT;
         self->movetype = MOVETYPE_PUSH;
         self->use = func_object_use;
         self->svflags |= SVF_NOCLIENT;
     }
     if (self->spawnflags & 2)
         self->s.effects |= EF_ANIM_ALL;
     if (self->spawnflags & 4)
         self->s.effects |= EF_ANIM_ALLFAST;
     self->clipmask = MASK_MONSTERSOLID;
     gi.linkentity (self);
 }
SP_func_wall()
void SP_func_wall (edict_t * self)
Definition at line 612 of file g_misc.c.
 {
     self->movetype = MOVETYPE_PUSH;
     gi.setmodel (self, self->model);
     if (self->spawnflags & 8)
         self->s.effects |= EF_ANIM_ALL;
     if (self->spawnflags & 16)
         self->s.effects |= EF_ANIM_ALLFAST;
     // just a wall
     if ((self->spawnflags & 7) == 0)
     {
         self->solid = SOLID_BSP;
         gi.linkentity (self);
         return;
     }
     // it must be TRIGGER_SPAWN
     if (!(self->spawnflags & 1))
     {
 //      gi.dprintf("func_wall missing TRIGGER_SPAWN\n");
         self->spawnflags |= 1;
     }
     // yell if the spawnflags are odd
     if (self->spawnflags & 4)
     {
         if (!(self->spawnflags & 2))
         {
             gi.dprintf("func_wall START_ON without TOGGLE\n");
             self->spawnflags |= 2;
         }
     }
     self->use = func_wall_use;
     if (self->spawnflags & 4)
     {
         self->solid = SOLID_BSP;
     }
     else
     {
         self->solid = SOLID_NOT;
         self->svflags |= SVF_NOCLIENT;
     }
     gi.linkentity (self);
 }
SP_info_notnull()
void SP_info_notnull (edict_t * self)
Definition at line 528 of file g_misc.c.
 {
     VectorCopy (self->s.origin, self->absmin);
     VectorCopy (self->s.origin, self->absmax);
 };
SP_info_null()
void SP_info_null (edict_t * self)
Definition at line 519 of file g_misc.c.
 {
     G_FreeEdict (self);
 };
SP_light()
void SP_light (edict_t * self)
Definition at line 559 of file g_misc.c.
 {
     // no targeted lights in deathmatch, because they cause global messages
     if (!self->targetname || deathmatch->value)
     {
         G_FreeEdict (self);
         return;
     }
     if (self->style >= 32)
     {
         self->use = light_use;
         if (self->spawnflags & START_OFF)
             gi.configstring (CS_LIGHTS+self->style, "a");
         else
             gi.configstring (CS_LIGHTS+self->style, "m");
     }
 }
SP_light_mine1()
void SP_light_mine1 (edict_t * ent)
Definition at line 1473 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     ent->s.modelindex = gi.modelindex ("models/objects/minelite/light1/tris.md2");
     gi.linkentity (ent);
 }
SP_light_mine2()
void SP_light_mine2 (edict_t * ent)
Definition at line 1484 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     ent->s.modelindex = gi.modelindex ("models/objects/minelite/light2/tris.md2");
     gi.linkentity (ent);
 }
SP_misc_banner()
void SP_misc_banner (edict_t * ent)
Definition at line 1202 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_NOT;
     ent->s.modelindex = gi.modelindex ("models/objects/banner/tris.md2");
     ent->s.frame = rand() % 16;
     gi.linkentity (ent);
     ent->think = misc_banner_think;
     ent->nextthink = level.time + FRAMETIME;
 }
SP_misc_bigviper()
void SP_misc_bigviper (edict_t * ent)
Definition at line 1316 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     VectorSet (ent->mins, -176, -120, -24);
     VectorSet (ent->maxs, 176, 120, 72);
     ent->s.modelindex = gi.modelindex ("models/ships/bigviper/tris.md2");
     gi.linkentity (ent);
 }
SP_misc_blackhole()
void SP_misc_blackhole (edict_t * ent)
Definition at line 1043 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_NOT;
     VectorSet (ent->mins, -64, -64, 0);
     VectorSet (ent->maxs, 64, 64, 8);
     ent->s.modelindex = gi.modelindex ("models/objects/black/tris.md2");
     ent->s.renderfx = RF_TRANSLUCENT;
     ent->use = misc_blackhole_use;
     ent->think = misc_blackhole_think;
     ent->nextthink = level.time + 2 * FRAMETIME;
     gi.linkentity (ent);
 }
SP_misc_deadsoldier()
void SP_misc_deadsoldier (edict_t * ent)
Definition at line 1230 of file g_misc.c.
 {
     if (deathmatch->value)
     {   // auto-remove for deathmatch
         G_FreeEdict (ent);
         return;
     }
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     ent->s.modelindex=gi.modelindex ("models/deadbods/dude/tris.md2");
     // Defaults to frame 0
     if (ent->spawnflags & 2)
         ent->s.frame = 1;
     else if (ent->spawnflags & 4)
         ent->s.frame = 2;
     else if (ent->spawnflags & 8)
         ent->s.frame = 3;
     else if (ent->spawnflags & 16)
         ent->s.frame = 4;
     else if (ent->spawnflags & 32)
         ent->s.frame = 5;
     else
         ent->s.frame = 0;
     VectorSet (ent->mins, -16, -16, 0);
     VectorSet (ent->maxs, 16, 16, 16);
     ent->deadflag = DEAD_DEAD;
     ent->takedamage = DAMAGE_YES;
     ent->svflags |= SVF_MONSTER|SVF_DEADMONSTER;
     ent->die = misc_deadsoldier_die;
     ent->monsterinfo.aiflags |= AI_GOOD_GUY;
     gi.linkentity (ent);
 }
SP_misc_easterchick()
void SP_misc_easterchick (edict_t * ent)
Definition at line 1099 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     VectorSet (ent->mins, -32, -32, 0);
     VectorSet (ent->maxs, 32, 32, 32);
     ent->s.modelindex = gi.modelindex ("models/monsters/bitch/tris.md2");
     ent->s.frame = 208;
     ent->think = misc_easterchick_think;
     ent->nextthink = level.time + 2 * FRAMETIME;
     gi.linkentity (ent);
 }
SP_misc_easterchick2()
void SP_misc_easterchick2 (edict_t * ent)
Definition at line 1127 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     VectorSet (ent->mins, -32, -32, 0);
     VectorSet (ent->maxs, 32, 32, 32);
     ent->s.modelindex = gi.modelindex ("models/monsters/bitch/tris.md2");
     ent->s.frame = 248;
     ent->think = misc_easterchick2_think;
     ent->nextthink = level.time + 2 * FRAMETIME;
     gi.linkentity (ent);
 }
SP_misc_eastertank()
void SP_misc_eastertank (edict_t * ent)
Definition at line 1071 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     VectorSet (ent->mins, -32, -32, -16);
     VectorSet (ent->maxs, 32, 32, 32);
     ent->s.modelindex = gi.modelindex ("models/monsters/tank/tris.md2");
     ent->s.frame = 254;
     ent->think = misc_eastertank_think;
     ent->nextthink = level.time + 2 * FRAMETIME;
     gi.linkentity (ent);
 }
SP_misc_explobox()
void SP_misc_explobox (edict_t * self)
Definition at line 974 of file g_misc.c.
 {
     if (deathmatch->value)
     {   // auto-remove for deathmatch
         G_FreeEdict (self);
         return;
     }
     gi.modelindex ("models/objects/debris1/tris.md2");
     gi.modelindex ("models/objects/debris2/tris.md2");
     gi.modelindex ("models/objects/debris3/tris.md2");
     self->solid = SOLID_BBOX;
     self->movetype = MOVETYPE_STEP;
     self->model = "models/objects/barrels/tris.md2";
     self->s.modelindex = gi.modelindex (self->model);
     VectorSet (self->mins, -16, -16, 0);
     VectorSet (self->maxs, 16, 16, 40);
     if (!self->mass)
         self->mass = 400;
     if (!self->health)
         self->health = 10;
     if (!self->dmg)
         self->dmg = 150;
     self->die = barrel_delay;
     self->takedamage = DAMAGE_YES;
     self->monsterinfo.aiflags = AI_NOSTEP;
     self->touch = barrel_touch;
     self->think = M_droptofloor;
     self->nextthink = level.time + 2 * FRAMETIME;
     gi.linkentity (self);
 }
SP_misc_gib_arm()
void SP_misc_gib_arm (edict_t * ent)
Definition at line 1496 of file g_misc.c.
 {
     gi.setmodel (ent, "models/objects/gibs/arm/tris.md2");
     ent->solid = SOLID_NOT;
     ent->s.effects |= EF_GIB;
     ent->takedamage = DAMAGE_YES;
     ent->die = gib_die;
     ent->movetype = MOVETYPE_TOSS;
     ent->svflags |= SVF_MONSTER;
     ent->deadflag = DEAD_DEAD;
     ent->avelocity[0] = random()*200;
     ent->avelocity[1] = random()*200;
     ent->avelocity[2] = random()*200;
     ent->think = G_FreeEdict;
     ent->nextthink = level.time + 30;
     gi.linkentity (ent);
 }
SP_misc_gib_head()
void SP_misc_gib_head (edict_t * ent)
Definition at line 1538 of file g_misc.c.
 {
     gi.setmodel (ent, "models/objects/gibs/head/tris.md2");
     ent->solid = SOLID_NOT;
     ent->s.effects |= EF_GIB;
     ent->takedamage = DAMAGE_YES;
     ent->die = gib_die;
     ent->movetype = MOVETYPE_TOSS;
     ent->svflags |= SVF_MONSTER;
     ent->deadflag = DEAD_DEAD;
     ent->avelocity[0] = random()*200;
     ent->avelocity[1] = random()*200;
     ent->avelocity[2] = random()*200;
     ent->think = G_FreeEdict;
     ent->nextthink = level.time + 30;
     gi.linkentity (ent);
 }
SP_misc_gib_leg()
void SP_misc_gib_leg (edict_t * ent)
Definition at line 1517 of file g_misc.c.
 {
     gi.setmodel (ent, "models/objects/gibs/leg/tris.md2");
     ent->solid = SOLID_NOT;
     ent->s.effects |= EF_GIB;
     ent->takedamage = DAMAGE_YES;
     ent->die = gib_die;
     ent->movetype = MOVETYPE_TOSS;
     ent->svflags |= SVF_MONSTER;
     ent->deadflag = DEAD_DEAD;
     ent->avelocity[0] = random()*200;
     ent->avelocity[1] = random()*200;
     ent->avelocity[2] = random()*200;
     ent->think = G_FreeEdict;
     ent->nextthink = level.time + 30;
     gi.linkentity (ent);
 }
SP_misc_satellite_dish()
void SP_misc_satellite_dish (edict_t * ent)
Definition at line 1459 of file g_misc.c.
 {
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     VectorSet (ent->mins, -64, -64, 0);
     VectorSet (ent->maxs, 64, 64, 128);
     ent->s.modelindex = gi.modelindex ("models/objects/satellite/tris.md2");
     ent->use = misc_satellite_dish_use;
     gi.linkentity (ent);
 }
SP_misc_strogg_ship()
void SP_misc_strogg_ship (edict_t * ent)
Definition at line 1415 of file g_misc.c.
 {
     if (!ent->target)
     {
         gi.dprintf ("%s without a target at %s\n", ent->classname, vtos(ent->absmin));
         G_FreeEdict (ent);
         return;
     }
     if (!ent->speed)
         ent->speed = 300;
     ent->movetype = MOVETYPE_PUSH;
     ent->solid = SOLID_NOT;
     ent->s.modelindex = gi.modelindex ("models/ships/strogg1/tris.md2");
     VectorSet (ent->mins, -16, -16, 0);
     VectorSet (ent->maxs, 16, 16, 32);
     ent->think = func_train_find;
     ent->nextthink = level.time + FRAMETIME;
     ent->use = misc_strogg_ship_use;
     ent->svflags |= SVF_NOCLIENT;
     ent->moveinfo.accel = ent->moveinfo.decel = ent->moveinfo.speed = ent->speed;
     gi.linkentity (ent);
 }
SP_misc_teleporter()
void SP_misc_teleporter (edict_t * ent)
Definition at line 1832 of file g_misc.c.
 {
     edict_t     *trig;
     if (!ent->target)
     {
         gi.dprintf ("teleporter without a target.\n");
         G_FreeEdict (ent);
         return;
     }
     gi.setmodel (ent, "models/objects/dmspot/tris.md2");
     ent->s.skinnum = 1;
     ent->s.effects = EF_TELEPORTER;
     ent->s.sound = gi.soundindex ("world/amb10.wav");
     ent->solid = SOLID_BBOX;
     VectorSet (ent->mins, -32, -32, -24);
     VectorSet (ent->maxs, 32, 32, -16);
     gi.linkentity (ent);
     trig = G_Spawn ();
     trig->touch = teleporter_touch;
     trig->solid = SOLID_TRIGGER;
     trig->target = ent->target;
     trig->owner = ent;
     VectorCopy (ent->s.origin, trig->s.origin);
     VectorSet (trig->mins, -8, -8, 8);
     VectorSet (trig->maxs, 8, 8, 24);
     gi.linkentity (trig);
 }
SP_misc_teleporter_dest()
void SP_misc_teleporter_dest (edict_t * ent)
Definition at line 1868 of file g_misc.c.
 {
     gi.setmodel (ent, "models/objects/dmspot/tris.md2");
     ent->s.skinnum = 0;
     ent->solid = SOLID_BBOX;
 //  ent->s.effects |= EF_FLIES;
     VectorSet (ent->mins, -32, -32, -24);
     VectorSet (ent->maxs, 32, 32, -16);
     gi.linkentity (ent);
 }
Referenced by SP_info_player_deathmatch().
SP_misc_viper()
void SP_misc_viper (edict_t * ent)
Definition at line 1285 of file g_misc.c.
 {
     if (!ent->target)
     {
         gi.dprintf ("misc_viper without a target at %s\n", vtos(ent->absmin));
         G_FreeEdict (ent);
         return;
     }
     if (!ent->speed)
         ent->speed = 300;
     ent->movetype = MOVETYPE_PUSH;
     ent->solid = SOLID_NOT;
     ent->s.modelindex = gi.modelindex ("models/ships/viper/tris.md2");
     VectorSet (ent->mins, -16, -16, 0);
     VectorSet (ent->maxs, 16, 16, 32);
     ent->think = func_train_find;
     ent->nextthink = level.time + FRAMETIME;
     ent->use = misc_viper_use;
     ent->svflags |= SVF_NOCLIENT;
     ent->moveinfo.accel = ent->moveinfo.decel = ent->moveinfo.speed = ent->speed;
     gi.linkentity (ent);
 }
SP_misc_viper_bomb()
void SP_misc_viper_bomb (edict_t * self)
Definition at line 1378 of file g_misc.c.
 {
     self->movetype = MOVETYPE_NONE;
     self->solid = SOLID_NOT;
     VectorSet (self->mins, -8, -8, -8);
     VectorSet (self->maxs, 8, 8, 8);
     self->s.modelindex = gi.modelindex ("models/objects/bomb/tris.md2");
     if (!self->dmg)
         self->dmg = 1000;
     self->use = misc_viper_bomb_use;
     self->svflags |= SVF_NOCLIENT;
     gi.linkentity (self);
 }
SP_monster_commander_body()
void SP_monster_commander_body (edict_t * self)
Definition at line 1170 of file g_misc.c.
 {
     self->movetype = MOVETYPE_NONE;
     self->solid = SOLID_BBOX;
     self->model = "models/monsters/commandr/tris.md2";
     self->s.modelindex = gi.modelindex (self->model);
     VectorSet (self->mins, -32, -32, 0);
     VectorSet (self->maxs, 32, 32, 48);
     self->use = commander_body_use;
     self->takedamage = DAMAGE_YES;
     self->flags = FL_GODMODE;
     self->s.renderfx |= RF_FRAMELERP;
     gi.linkentity (self);
     gi.soundindex ("tank/thud.wav");
     gi.soundindex ("tank/pain.wav");
     self->think = commander_body_drop;
     self->nextthink = level.time + 5 * FRAMETIME;
 }
SP_path_corner()
void SP_path_corner (edict_t * self)
Definition at line 399 of file g_misc.c.
 {
     if (!self->targetname)
     {
         gi.dprintf ("path_corner with no targetname at %s\n", vtos(self->s.origin));
         G_FreeEdict (self);
         return;
     }
     self->solid = SOLID_TRIGGER;
     self->touch = path_corner_touch;
     VectorSet (self->mins, -8, -8, -8);
     VectorSet (self->maxs, 8, 8, 8);
     self->svflags |= SVF_NOCLIENT;
     gi.linkentity (self);
 }
SP_point_combat()
void SP_point_combat (edict_t * self)
Definition at line 474 of file g_misc.c.
 {
     if (deathmatch->value)
     {
         G_FreeEdict (self);
         return;
     }
     self->solid = SOLID_TRIGGER;
     self->touch = point_combat_touch;
     VectorSet (self->mins, -8, -8, -16);
     VectorSet (self->maxs, 8, 8, 16);
     self->svflags = SVF_NOCLIENT;
     gi.linkentity (self);
 };
SP_target_character()
void SP_target_character (edict_t * self)
Definition at line 1563 of file g_misc.c.
 {
     self->movetype = MOVETYPE_PUSH;
     gi.setmodel (self, self->model);
     self->solid = SOLID_BSP;
     self->s.frame = 12;
     gi.linkentity (self);
     return;
 }
SP_target_string()
void SP_target_string (edict_t * self)
Definition at line 1607 of file g_misc.c.
 {
     if (!self->message)
         self->message = "";
     self->use = target_string_use;
 }
SP_viewthing()
void SP_viewthing (edict_t * ent)
Definition at line 499 of file g_misc.c.
 {
     gi.dprintf ("viewthing spawned\n");
     ent->movetype = MOVETYPE_NONE;
     ent->solid = SOLID_BBOX;
     ent->s.renderfx = RF_FRAMELERP;
     VectorSet (ent->mins, -16, -16, -24);
     VectorSet (ent->maxs, 16, 16, 32);
     ent->s.modelindex = gi.modelindex ("models/objects/banner/tris.md2");
     gi.linkentity (ent);
     ent->nextthink = level.time + 0.5;
     ent->think = TH_viewthing;
     return;
 }
target_string_use()
void target_string_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1577 of file g_misc.c.
 {
     edict_t *e;
     int     n, l;
     char    c;
     l = (int)strlen(self->message);
     for (e = self->teammaster; e; e = e->teamchain)
     {
         if (!e->count)
             continue;
         n = e->count - 1;
         if (n > l)
         {
             e->s.frame = 12;
             continue;
         }
         c = self->message[n];
         if (c >= '0' && c <= '9')
             e->s.frame = c - '0';
         else if (c == '-')
             e->s.frame = 10;
         else if (c == ':')
             e->s.frame = 11;
         else
             e->s.frame = 12;
     }
 }
Referenced by SP_target_string().
teleporter_touch()
void teleporter_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 1783 of file g_misc.c.
 {
     edict_t     *dest;
     int         i;
     if (!other->client)
         return;
     dest = G_Find (NULL, FOFS(targetname), self->target);
     if (!dest)
     {
         gi.dprintf ("Couldn't find destination\n");
         return;
     }
     // unlink to make sure it can't possibly interfere with KillBox
     gi.unlinkentity (other);
     VectorCopy (dest->s.origin, other->s.origin);
     VectorCopy (dest->s.origin, other->s.old_origin);
     other->s.origin[2] += 10;
     // clear the velocity and hold them in place briefly
     VectorClear (other->velocity);
     other->client->ps.pmove.pm_time = 160>>3;       // hold time
     other->client->ps.pmove.pm_flags |= PMF_TIME_TELEPORT;
     // draw the teleport splash at source and on the player
     self->owner->s.event = EV_PLAYER_TELEPORT;
     other->s.event = EV_PLAYER_TELEPORT;
     // set angles
     for (i=0 ; i<3 ; i++)
     {
         other->client->ps.pmove.delta_angles[i] = ANGLE2SHORT(dest->s.angles[i] - other->client->resp.cmd_angles[i]);
     }
     VectorClear (other->s.angles);
     VectorClear (other->client->ps.viewangles);
     VectorClear (other->client->v_angle);
     // kill anything at the destination
     KillBox (other);
     gi.linkentity (other);
 }
Referenced by SP_misc_teleporter().
TH_viewthing()
void TH_viewthing (edict_t * ent)
Definition at line 493 of file g_misc.c.
 {
     ent->s.frame = (ent->s.frame + 1) % 7;
     ent->nextthink = level.time + FRAMETIME;
 }
Referenced by SP_viewthing().
ThrowClientHead()
void ThrowClientHead (edict_t * self, int damage)
Definition at line 229 of file g_misc.c.
 {
     vec3_t  vd;
     char    *gibname;
     if (rand()&1)
     {
         gibname = "models/objects/gibs/head2/tris.md2";
         self->s.skinnum = 1;        // second skin is player
     }
     else
     {
         gibname = "models/objects/gibs/skull/tris.md2";
         self->s.skinnum = 0;
     }
     self->s.origin[2] += 32;
     self->s.frame = 0;
     gi.setmodel (self, gibname);
     VectorSet (self->mins, -16, -16, 0);
     VectorSet (self->maxs, 16, 16, 16);
     self->takedamage = DAMAGE_NO;
     self->solid = SOLID_NOT;
     self->s.effects = EF_GIB;
     self->s.sound = 0;
     self->flags |= FL_NO_KNOCKBACK;
     self->movetype = MOVETYPE_BOUNCE;
     VelocityForDamage (damage, vd);
     VectorAdd (self->velocity, vd, self->velocity);
     if (self->client)   // bodies in the queue don't have a client anymore
     {
         self->client->anim_priority = ANIM_DEATH;
         self->client->anim_end = self->s.frame;
     }
     else
     {
         self->think = NULL;
         self->nextthink = 0;
     }
     gi.linkentity (self);
 }
Referenced by body_die(), and player_die().
ThrowDebris()
void ThrowDebris (edict_t * self, char * modelname, float speed, vec3_t origin)
Definition at line 286 of file g_misc.c.
 {
     edict_t *chunk;
     vec3_t  v;
     chunk = G_Spawn();
     VectorCopy (origin, chunk->s.origin);
     gi.setmodel (chunk, modelname);
     v[0] = 100 * crandom();
     v[1] = 100 * crandom();
     v[2] = 100 + 100 * crandom();
     VectorMA (self->velocity, speed, v, chunk->velocity);
     chunk->movetype = MOVETYPE_BOUNCE;
     chunk->solid = SOLID_NOT;
     chunk->avelocity[0] = random()*600;
     chunk->avelocity[1] = random()*600;
     chunk->avelocity[2] = random()*600;
     chunk->think = G_FreeEdict;
     chunk->nextthink = level.time + 5 + random()*5;
     chunk->s.frame = 0;
     chunk->flags = 0;
     chunk->classname = "debris";
     chunk->takedamage = DAMAGE_YES;
     chunk->die = debris_die;
     gi.linkentity (chunk);
 }
Referenced by barrel_explode(), func_explosive_explode(), and rocket_touch().
ThrowGib()
void ThrowGib (edict_t * self, char * gibname, int damage, int type)
Definition at line 135 of file g_misc.c.
 {
     edict_t *gib;
     vec3_t  vd;
     vec3_t  origin;
     vec3_t  size;
     float   vscale;
     gib = G_Spawn();
     VectorScale (self->size, 0.5, size);
     VectorAdd (self->absmin, size, origin);
     gib->s.origin[0] = origin[0] + crandom() * size[0];
     gib->s.origin[1] = origin[1] + crandom() * size[1];
     gib->s.origin[2] = origin[2] + crandom() * size[2];
     gi.setmodel (gib, gibname);
     gib->solid = SOLID_NOT;
     gib->s.effects |= EF_GIB;
     gib->flags |= FL_NO_KNOCKBACK;
     gib->takedamage = DAMAGE_YES;
     gib->die = gib_die;
     if (type == GIB_ORGANIC)
     {
         gib->movetype = MOVETYPE_TOSS;
         gib->touch = gib_touch;
         vscale = 0.5;
     }
     else
     {
         gib->movetype = MOVETYPE_BOUNCE;
         vscale = 1.0;
     }
     VelocityForDamage (damage, vd);
     VectorMA (self->velocity, vscale, vd, gib->velocity);
     ClipGibVelocity (gib);
     gib->avelocity[0] = random()*600;
     gib->avelocity[1] = random()*600;
     gib->avelocity[2] = random()*600;
     gib->think = G_FreeEdict;
     gib->nextthink = level.time + 10 + random()*10;
     gi.linkentity (gib);
 }
Referenced by actor_die(), berserk_die(), body_die(), boss2_die(), BossExplode(), brain_die(), chick_die(), flipper_die(), gladiator_die(), gunner_die(), hover_die(), infantry_die(), insane_die(), makron_die(), medic_die(), misc_deadsoldier_die(), mutant_die(), parasite_die(), player_die(), soldier_die(), and tank_die().
ThrowHead()
void ThrowHead (edict_t * self, char * gibname, int damage, int type)
Definition at line 183 of file g_misc.c.
 {
     vec3_t  vd;
     float   vscale;
     self->s.skinnum = 0;
     self->s.frame = 0;
     VectorClear (self->mins);
     VectorClear (self->maxs);
     self->s.modelindex2 = 0;
     gi.setmodel (self, gibname);
     self->solid = SOLID_NOT;
     self->s.effects |= EF_GIB;
     self->s.effects &= ~EF_FLIES;
     self->s.sound = 0;
     self->flags |= FL_NO_KNOCKBACK;
     self->svflags &= ~SVF_MONSTER;
     self->takedamage = DAMAGE_YES;
     self->die = gib_die;
     if (type == GIB_ORGANIC)
     {
         self->movetype = MOVETYPE_TOSS;
         self->touch = gib_touch;
         vscale = 0.5;
     }
     else
     {
         self->movetype = MOVETYPE_BOUNCE;
         vscale = 1.0;
     }
     VelocityForDamage (damage, vd);
     VectorMA (self->velocity, vscale, vd, self->velocity);
     ClipGibVelocity (self);
     self->avelocity[YAW] = crandom()*600;
     self->think = G_FreeEdict;
     self->nextthink = level.time + 10 + random()*10;
     gi.linkentity (self);
 }
Referenced by actor_die(), berserk_die(), boss2_die(), BossExplode(), brain_die(), chick_die(), flipper_die(), gladiator_die(), gunner_die(), hover_die(), infantry_die(), insane_die(), makron_die(), medic_die(), misc_deadsoldier_die(), mutant_die(), parasite_die(), soldier_die(), and tank_die().
train_use()
void train_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 1633 of file g_func.c.
 {
     self->activator = activator;
     if (self->spawnflags & TRAIN_START_ON)
     {
         if (!(self->spawnflags & TRAIN_TOGGLE))
             return;
         self->spawnflags &= ~TRAIN_START_ON;
         VectorClear (self->velocity);
         self->nextthink = 0;
     }
     else
     {
         if (self->target_ent)
             train_resume(self);
         else
             train_next(self);
     }
 }
Referenced by misc_strogg_ship_use(), misc_viper_use(), and SP_func_train().
Use_Areaportal()
void Use_Areaportal (edict_t * ent, edict_t * other, edict_t * activator)
Definition at line 31 of file g_misc.c.
 {
     ent->count ^= 1;        // toggle state
 //  gi.dprintf ("portalstate: %i = %i\n", ent->style, ent->count);
     gi.SetAreaPortalState (ent->style, ent->count);
 }
Referenced by SP_func_areaportal().
VelocityForDamage()
void VelocityForDamage (int damage, vec3_t v)
Definition at line 58 of file g_misc.c.
 {
     v[0] = 100.0 * crandom();
     v[1] = 100.0 * crandom();
     v[2] = 200.0 + 100.0 * random();
     if (damage < 50)
         VectorScale (v, 0.7, v);
     else
         VectorScale (v, 1.2, v);
 }
Referenced by ThrowClientHead(), ThrowGib(), and ThrowHead().