vkQuake2 doxygen: C:/entry/dev/vq2/src/qcommon/common.c File Reference
common.c File Reference
#include "qcommon.h"
#include <setjmp.h>
#include "../client/anorms.h"
Classes
struct zhead_s
Macros
#define MAXPRINTMSG 8192
#define MAX_NUM_ARGVS 50
#define Z_MAGIC 0x1d1d
Typedefs
typedef struct zhead_s zhead_t
Functions
void SV_ShutdownGameProgs (void)
void Com_BeginRedirect (int target, char *buffer, int buffersize, void(*flush))
void Com_EndRedirect (void)
void Com_Printf (char *fmt,...)
void Com_DPrintf (char *fmt,...)
void Com_Error (int code, char *fmt,...)
void Com_Quit (void)
int Com_ServerState (void)
void Com_SetServerState (int state)
void MSG_WriteChar (sizebuf_t *sb, int c)
void MSG_WriteByte (sizebuf_t *sb, int c)
void MSG_WriteShort (sizebuf_t *sb, int c)
void MSG_WriteLong (sizebuf_t *sb, int c)
void MSG_WriteFloat (sizebuf_t *sb, float f)
void MSG_WriteString (sizebuf_t *sb, char *s)
void MSG_WriteCoord (sizebuf_t *sb, float f)
void MSG_WritePos (sizebuf_t *sb, vec3_t pos)
void MSG_WriteAngle (sizebuf_t *sb, float f)
void MSG_WriteAngle16 (sizebuf_t *sb, float f)
void MSG_WriteDeltaUsercmd (sizebuf_t *buf, usercmd_t *from, usercmd_t *cmd)
void MSG_WriteDir (sizebuf_t *sb, vec3_t dir)
void MSG_ReadDir (sizebuf_t *sb, vec3_t dir)
void MSG_WriteDeltaEntity (entity_state_t *from, entity_state_t *to, sizebuf_t *msg, qboolean force, qboolean newentity)
void MSG_BeginReading (sizebuf_t *msg)
int MSG_ReadChar (sizebuf_t *msg_read)
int MSG_ReadByte (sizebuf_t *msg_read)
int MSG_ReadShort (sizebuf_t *msg_read)
int MSG_ReadLong (sizebuf_t *msg_read)
float MSG_ReadFloat (sizebuf_t *msg_read)
char * MSG_ReadString (sizebuf_t *msg_read)
char * MSG_ReadStringLine (sizebuf_t *msg_read)
float MSG_ReadCoord (sizebuf_t *msg_read)
void MSG_ReadPos (sizebuf_t *msg_read, vec3_t pos)
float MSG_ReadAngle (sizebuf_t *msg_read)
float MSG_ReadAngle16 (sizebuf_t *msg_read)
void MSG_ReadDeltaUsercmd (sizebuf_t *msg_read, usercmd_t *from, usercmd_t *move)
void MSG_ReadData (sizebuf_t *msg_read, void *data, int len)
void SZ_Init (sizebuf_t *buf, byte *data, int length)
void SZ_Clear (sizebuf_t *buf)
void * SZ_GetSpace (sizebuf_t *buf, int length)
void SZ_Write (sizebuf_t *buf, void *data, int length)
void SZ_Print (sizebuf_t *buf, char *data)
int COM_CheckParm (char *parm)
int COM_Argc (void)
char * COM_Argv (int arg)
void COM_ClearArgv (int arg)
void COM_InitArgv (int argc, char **argv)
void COM_AddParm (char *parm)
int memsearch (byte *start, int count, int search)
just for debugging
char * CopyString (char *in)
void Info_Print (char *s)
void Z_Free (void *ptr)
void Z_Stats_f (void)
void Z_FreeTags (int tag)
void * Z_TagMalloc (int size, int tag)
void * Z_Malloc (int size)
byte COM_BlockSequenceCheckByte (byte *base, int length, int sequence, int challenge)
byte COM_BlockSequenceCRCByte (byte *base, int length, int sequence)
float frand (void)
float crand (void)
void Key_Init (void)
void SCR_EndLoadingPlaque (void)
void Com_Error_f (void)
void Qcommon_Init (int argc, char **argv)
void Qcommon_Frame (int msec)
void Qcommon_Shutdown (void)
Variables
int com_argc
char * com_argv [MAX_NUM_ARGVS+1]
int realtime
jmp_buf abortframe
static qboolean shutdown_game = false
FILE * log_stats_file
cvar_t * host_speeds
cvar_t * log_stats
cvar_t * developer
cvar_t * timescale
cvar_t * fixedtime
cvar_t * logfile_active
cvar_t * showtrace
cvar_t * dedicated
FILE * logfile
int server_state
int time_before_game
int time_after_game
int time_before_ref
int time_after_ref
static int rd_target
static char * rd_buffer
static int rd_buffersize
static void(* rd_flush)(int target, char *buffer)
vec3_t bytedirs [NUMVERTEXNORMALS]
zhead_t z_chain
int z_count
int z_bytes
static byte chktbl [1024]
Macro Definition Documentation
MAX_NUM_ARGVS
#define MAX_NUM_ARGVS 50
Definition at line 27 of file common.c.
MAXPRINTMSG
#define MAXPRINTMSG 8192
Definition at line 25 of file common.c.
Z_MAGIC
#define Z_MAGIC 0x1d1d
Definition at line 1103 of file common.c.
Typedef Documentation
zhead_t
typedef struct zhead_s zhead_t
Function Documentation
COM_AddParm()
void COM_AddParm (char * parm)
Definition at line 1016 of file common.c.
 {
     if (com_argc == MAX_NUM_ARGVS)
         Com_Error (ERR_FATAL, "COM_AddParm: MAX_NUM)ARGS");
     com_argv[com_argc++] = parm;
 }
COM_Argc()
int COM_Argc (void)
Definition at line 968 of file common.c.
 {
     return com_argc;
 }
Referenced by Cbuf_AddEarlyCommands(), and Cbuf_AddLateCommands().
COM_Argv()
char* COM_Argv (int arg)
Definition at line 973 of file common.c.
 {
     if (arg < 0 || arg >= com_argc || !com_argv[arg])
         return "";
     return com_argv[arg];
 }
Referenced by Cbuf_AddEarlyCommands(), and Cbuf_AddLateCommands().
Com_BeginRedirect()
void Com_BeginRedirect (int target, char * buffer, int buffersize, void * flush)
Definition at line 74 of file common.c.
 {
     if (!target || !buffer || !buffersize || !flush)
         return;
     rd_target = target;
     rd_buffer = buffer;
     rd_buffersize = buffersize;
     rd_flush = flush;
     *rd_buffer = 0;
 }
Referenced by SVC_RemoteCommand(), and SVC_Status().
COM_BlockSequenceCheckByte()
byte COM_BlockSequenceCheckByte (byte * base, int length, int sequence, int challenge)
Definition at line 1220 of file common.c.
 {
     Sys_Error("COM_BlockSequenceCheckByte called\n");
 #if 0
     int     checksum;
     byte    buf[68];
     byte    *p;
     float temp;
     byte c;
     temp = bytedirs[(sequence/3) % NUMVERTEXNORMALS][sequence % 3];
     temp = LittleFloat(temp);
     p = ((byte *)&temp);
     if (length > 60)
         length = 60;
     memcpy (buf, base, length);
     buf[length] = (sequence & 0xff) ^ p[0];
     buf[length+1] = p[1];
     buf[length+2] = ((sequence>>8) & 0xff) ^ p[2];
     buf[length+3] = p[3];
     temp = bytedirs[((sequence+challenge)/3) % NUMVERTEXNORMALS][(sequence+challenge) % 3];
     temp = LittleFloat(temp);
     p = ((byte *)&temp);
     buf[length+4] = (sequence & 0xff) ^ p[3];
     buf[length+5] = (challenge & 0xff) ^ p[2];
     buf[length+6] = ((sequence>>8) & 0xff) ^ p[1];
     buf[length+7] = ((challenge >> 7) & 0xff) ^ p[0];
     length += 8;
     checksum = LittleLong(Com_BlockChecksum (buf, length));
     checksum &= 0xff;
     return checksum;
 #endif
     return 0;
 }
COM_BlockSequenceCRCByte()
byte COM_BlockSequenceCRCByte (byte * base, int length, int sequence)
Definition at line 1338 of file common.c.
 {
     int     n;
     byte    *p;
     int     x;
     byte chkb[60 + 4];
     unsigned short crc;
     if (sequence < 0)
         Sys_Error("sequence < 0, this shouldn't happen\n");
     p = chktbl + (sequence % (sizeof(chktbl) - 4));
     if (length > 60)
         length = 60;
     memcpy (chkb, base, length);
     chkb[length] = p[0];
     chkb[length+1] = p[1];
     chkb[length+2] = p[2];
     chkb[length+3] = p[3];
     length += 4;
     crc = CRC_Block(chkb, length);
     for (x=0, n=0; n<length; n++)
         x += chkb[n];
     crc = (crc ^ x) & 0xff;
     return crc;
 }
Referenced by CL_SendCmd(), and SV_ExecuteClientMessage().
COM_CheckParm()
int COM_CheckParm (char * parm)
Definition at line 955 of file common.c.
 {
     int     i;
     for (i=1 ; i<com_argc ; i++)
     {
         if (!strcmp (parm,com_argv[i]))
             return i;
     }
     return 0;
 }
COM_ClearArgv()
void COM_ClearArgv (int arg)
Definition at line 980 of file common.c.
 {
     if (arg < 0 || arg >= com_argc || !com_argv[arg])
         return;
     com_argv[arg] = "";
 }
Referenced by Cbuf_AddEarlyCommands().
Com_DPrintf()
void Com_DPrintf (char * fmt, ...)
Definition at line 157 of file common.c.
 {
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     if (!developer || !developer->value)
         return;         // don't confuse non-developers with techie stuff...
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     Com_Printf ("%s", msg);
 }
Referenced by CDAudio_CloseDoor(), CDAudio_Eject(), CDAudio_GetAudioDiskInfo(), CDAudio_MessageHandler(), CDAudio_Pause(), CDAudio_Play2(), CDAudio_Resume(), CDAudio_Shutdown(), CDAudio_Stop(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ReadPackets(), CM_DecompressVis(), CopyFile(), DS_CreateBuffers(), DS_DestroyBuffers(), FreeSound(), FS_FOpenFile(), NET_SendPacket(), PM_InitialSnapPosition(), S_LoadSound(), S_Update_(), SNDDMA_InitDirect(), SNDDMA_InitWav(), SNDDMA_Submit(), SV_Baselines_f(), SV_Begin_f(), SV_BeginDownload_f(), SV_BuildClientFrame(), SV_ClientThink(), SV_Configstrings_f(), SV_ConnectionlessPacket(), SV_CopySaveGame(), SV_ExecuteClientMessage(), SV_GameMap_f(), SV_LinkEdict(), SV_New_f(), SV_Nextserver_f(), SV_ReadLevelFile(), SV_ReadServerFile(), SV_ServerRecord_f(), SV_SpawnServer(), SV_WipeSavegame(), SV_WriteLevelFile(), SV_WriteServerFile(), SVC_DirectConnect(), Sys_GetGameAPI(), and VID_Printf().
Com_EndRedirect()
void Com_EndRedirect (void)
Definition at line 86 of file common.c.
 {
     rd_flush(rd_target, rd_buffer);
     rd_target = 0;
     rd_buffer = NULL;
     rd_buffersize = 0;
     rd_flush = NULL;
 }
Referenced by SVC_RemoteCommand(), and SVC_Status().
Com_Error()
void Com_Error (int code, char * fmt, ...)
Definition at line 181 of file common.c.
 {
     va_list     argptr;
     static char     msg[MAXPRINTMSG];
     static  qboolean    recursive;
     if (recursive)
         Sys_Error ("recursive error after: %s", msg);
     recursive = true;
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     if (code == ERR_DISCONNECT)
     {
         CL_Drop ();
         recursive = false;
         longjmp (abortframe, -1);
     }
     else if (code == ERR_DROP)
     {
         Com_Printf ("********************\nERROR: %s\n********************\n", msg);
         SV_Shutdown (va("Server crashed: %s\n", msg), false);
         CL_Drop ();
         recursive = false;
         shutdown_game = true;
         longjmp (abortframe, -1);
     }
     else
     {
         SV_Shutdown (va("Server fatal crashed: %s\n", msg), false);
         SV_ShutdownGameProgs();
         CL_Shutdown ();
     }
     if (logfile)
     {
         fclose (logfile);
         logfile = NULL;
     }
     Sys_Error ("%s", msg);
 }
Referenced by CalcFov(), Cbuf_ExecuteText(), CL_Disconnect_f(), CL_GetEntitySoundOrigin(), CL_ParseConfigString(), CL_ParseFrame(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParsePacketEntities(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStartSoundPacket(), CL_ParseTEnt(), CL_RequestNextDownload(), CL_SetLightstyle(), CM_AreasConnected(), CM_InitBoxHull(), CM_InlineModel(), CM_LeafArea(), CM_LeafCluster(), CM_LeafContents(), CM_LoadMap(), CM_SetAreaPortalState(), CMod_LoadAreaPortals(), CMod_LoadAreas(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadEntityString(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadSubmodels(), CMod_LoadSurfaces(), CMod_LoadVisibility(), COM_AddParm(), Com_Error_f(), COM_InitArgv(), FloodArea_r(), FS_FOpenFile(), FS_LoadPackFile(), FS_Read(), GetWavinfo(), Key_Event(), M_PopMenu(), M_PushMenu(), MSG_ReadDir(), MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDeltaEntity(), MSG_WriteShort(), NET_GetPacket(), NET_Init(), NET_OpenIP(), NET_SendPacket(), PF_Configstring(), PF_cprintf(), PF_error(), PF_setmodel(), S_AliasName(), S_FindName(), S_PickChannel(), SCR_ExecuteLayoutString(), SCR_ReadNextFrame(), StartServer_MenuInit(), SV_BeginDemoserver(), SV_FatPVS(), SV_FindIndex(), SV_HullForEntity(), SV_InitGameProgs(), SV_Multicast(), SV_SendClientMessages(), SV_StartSound(), Sys_CopyProtect(), Sys_GetGameAPI(), Sys_UnloadGame(), SZ_GetSpace(), V_AddLightStyle(), VID_CheckChanges(), VID_Error(), VID_FreeReflib(), VID_LoadRefresh(), Z_Free(), and Z_TagMalloc().
Com_Error_f()
void Com_Error_f (void)
Definition at line 1396 of file common.c.
 {
     Com_Error (ERR_FATAL, "%s", Cmd_Argv(1));
 }
Referenced by Qcommon_Init().
COM_InitArgv()
void COM_InitArgv (int argc, char ** argv)
Definition at line 993 of file common.c.
 {
     int     i;
     if (argc > MAX_NUM_ARGVS)
         Com_Error (ERR_FATAL, "argc > MAX_NUM_ARGVS");
     com_argc = argc;
     for (i=0 ; i<argc ; i++)
     {
         if (!argv[i] || strlen(argv[i]) >= MAX_TOKEN_CHARS )
             com_argv[i] = "";
         else
             com_argv[i] = argv[i];
     }
 }
Referenced by Qcommon_Init().
Com_Printf()
void Com_Printf (char * fmt, ...)
Definition at line 104 of file common.c.
 {
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     if (rd_target)
     {
         if ((strlen (msg) + strlen(rd_buffer)) > (rd_buffersize - 1))
         {
             rd_flush(rd_target, rd_buffer);
             *rd_buffer = 0;
         }
         strcat (rd_buffer, msg);
         return;
     }
     Con_Print (msg);
     // also echo to debugging console
     Sys_ConsoleOutput (msg);
     // logfile
     if (logfile_active && logfile_active->value)
     {
         char    name[MAX_QPATH];
         if (!logfile)
         {
             Com_sprintf (name, sizeof(name), "%s/qconsole.log", FS_Gamedir ());
             if (logfile_active->value > 2)
                 logfile = fopen (name, "a");
             else
                 logfile = fopen (name, "w");
         }
         if (logfile)
             fprintf (logfile, "%s", msg);
         if (logfile_active->value > 1)
             fflush (logfile);       // force it to save every time
     }
 }
Referenced by Cbuf_AddText(), CD_f(), CDAudio_Init(), CDAudio_Play2(), CL_AddEntities(), CL_Changing_f(), CL_CheckForResend(), CL_CheckOrDownloadFile(), CL_CheckPredictionError(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_Disconnect(), CL_Download_f(), CL_DumpPackets(), CL_ForwardToServer_f(), CL_KeyState(), CL_Packet_f(), CL_ParseBeam(), CL_ParseBeam2(), CL_ParseDownload(), CL_ParseFrame(), CL_ParseLightning(), CL_ParsePacketEntities(), CL_ParsePlayerBeam(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStatusMessage(), CL_PingServers_f(), CL_PredictMovement(), CL_PrepRefresh(), CL_Rcon_f(), CL_ReadPackets(), CL_Reconnect_f(), CL_Record_f(), CL_SendConnectPacket(), CL_Setenv_f(), CL_Skins_f(), CL_Stop_f(), CL_Userinfo_f(), CL_WriteConfiguration(), Cmd_AddCommand(), Cmd_Alias_f(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_ForwardToServer(), Cmd_List_f(), Cmd_MacroExpandString(), Cmd_RemoveCommand(), Com_DPrintf(), Com_Error(), Com_sprintf(), Con_Dump_f(), Con_Init(), Cvar_Command(), Cvar_Get(), Cvar_List_f(), Cvar_Set2(), Cvar_Set_f(), DS_CreateBuffers(), DumpChunks(), FS_Dir_f(), FS_Link_f(), FS_LoadPackFile(), FS_Path_f(), FS_SetGamedir(), GetWavinfo(), Huff1Decompress(), IN_StartupJoystick(), Info_Print(), Info_SetValueForKey(), Joy_AdvancedUpdate_f(), Key_Bind_f(), Key_Bindlist_f(), Key_Console(), Key_Event(), Key_Unbind_f(), KeyDown(), Master_Heartbeat(), Master_Shutdown(), Miniaudio_f(), Miniaudio_Play(), NET_GetPacket(), NET_Init(), NET_IPSocket(), NET_IPXSocket(), NET_SendPacket(), Netchan_Process(), Netchan_Transmit(), PF_cprintf(), PF_dprintf(), PrintPmove(), Qcommon_Frame(), Qcommon_Init(), S_Init(), S_IssuePlaysound(), S_LoadSound(), S_SoundInfo_f(), S_SoundList(), S_StartLocalSound(), S_Update(), SCR_CenterPrint(), SCR_LoadPCX(), SCR_PlayCinematic(), SCR_RunCinematic(), SCR_Sky_f(), SCR_TimeRefresh_f(), SCR_UpdateScreen(), SHOWNET(), SNDDMA_BeginPainting(), SNDDMA_Init(), SNDDMA_InitDirect(), SNDDMA_InitWav(), SNDDMA_Submit(), SV_AreaEdicts_r(), SV_Baselines_f(), SV_Begin_f(), SV_BroadcastPrintf(), SV_Configstrings_f(), SV_ConnectionlessPacket(), SV_DumpUser_f(), SV_ExecuteClientMessage(), SV_Frame(), SV_GameMap_f(), SV_InitGame(), SV_Kick_f(), SV_Loadgame_f(), SV_Map_f(), SV_New_f(), SV_ReadLevelFile(), SV_ReadPackets(), SV_ReadServerFile(), SV_RunGameFrame(), SV_Savegame_f(), SV_SendClientDatagram(), SV_ServerCommand_f(), SV_Serverinfo_f(), SV_ServerRecord_f(), SV_ServerStop_f(), SV_SetMaster_f(), SV_SetPlayer(), SV_SpawnServer(), SV_Status_f(), SV_WriteLevelFile(), SV_WriteServerFile(), SVC_Ack(), SVC_DirectConnect(), SVC_RemoteCommand(), SVC_Status(), SZ_GetSpace(), V_Gun_Next_f(), V_Gun_Prev_f(), V_RenderView(), V_Viewpos_f(), VID_LoadRefresh(), VID_Printf(), and Z_Stats_f().
Com_Quit()
void Com_Quit (void)
Definition at line 235 of file common.c.
 {
     SV_Shutdown ("Server quit\n", false);
     SV_ShutdownGameProgs();
     CL_Shutdown ();
     if (logfile)
     {
         fclose (logfile);
         logfile = NULL;
     }
     Sys_Quit ();
 }
Referenced by CL_Quit_f(), MainWndProc(), Qcommon_Init(), and WinMain().
Com_ServerState()
int Com_ServerState (void)
Definition at line 256 of file common.c.
 {
     return server_state;
 }
Referenced by CL_CheckForResend(), CL_Connect_f(), CL_ParseServerData(), CL_Pause_f(), Con_ToggleConsole_f(), Cvar_Set2(), M_Menu_SaveGame_f(), M_PushMenu(), and StartServerActionFunc().
Com_SetServerState()
void Com_SetServerState (int state)
Definition at line 266 of file common.c.
 {
     server_state = state;
 }
Referenced by SV_Shutdown(), and SV_SpawnServer().
CopyString()
char* CopyString (char * in)
Definition at line 1038 of file common.c.
 {
     char    *out;
     out = Z_Malloc ((int)strlen(in)+1);
     strcpy (out, in);
     return out;
 }
Referenced by Cmd_Alias_f(), Cvar_FullSet(), Cvar_Get(), Cvar_Set2(), and FS_Link_f().
crand()
float crand (void)
Definition at line 1380 of file common.c.
 {
     return (rand()&32767)* (2.0/32767) - 1;
 }
Referenced by CL_BlasterParticles(), CL_BlasterParticles2(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DiminishingTrail(), CL_FlagTrail(), CL_FlameEffects(), CL_ForceWall(), CL_GenericParticleEffect(), CL_ItemRespawnParticles(), CL_LogoutEffect(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleporterParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrapParticles(), CL_Widowbeamout(), and CL_WidowSplash().
frand()
float frand (void)
Definition at line 1375 of file common.c.
 {
     return (rand()&32767)* (1.0/32767);
 }
Referenced by CL_BFGExplosionParticles(), CL_BigTeleportParticles(), CL_BlasterParticles(), CL_BlasterParticles2(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_ColorExplosionParticles(), CL_DiminishingTrail(), CL_ExplosionParticles(), CL_FlagTrail(), CL_FlameEffects(), CL_ForceWall(), CL_GenericParticleEffect(), CL_IonripperTrail(), CL_ItemRespawnParticles(), CL_LogoutEffect(), CL_ParseTEnt(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TrapParticles(), and CL_WidowSplash().
Info_Print()
void Info_Print (char * s)
Definition at line 1049 of file common.c.
 {
     char    key[512];
     char    value[512];
     char    *o;
     int     l;
     if (*s == '\\')
         s++;
     while (*s)
     {
         o = key;
         while (*s && *s != '\\')
             *o++ = *s++;
         l = o - key;
         if (l < 20)
         {
             memset (o, ' ', 20-l);
             key[20] = 0;
         }
         else
             *o = 0;
         Com_Printf ("%s", key);
         if (!*s)
         {
             Com_Printf ("MISSING VALUE\n");
             return;
         }
         o = value;
         s++;
         while (*s && *s != '\\')
             *o++ = *s++;
         *o = 0;
         if (*s)
             s++;
         Com_Printf ("%s\n", value);
     }
 }
Referenced by CL_Userinfo_f(), SV_DumpUser_f(), SV_Serverinfo_f(), and SV_ShowServerinfo_f().
Key_Init()
void Key_Init (void)
Definition at line 647 of file keys.c.
 {
     int     i;
     for (i=0 ; i<128 ; i++)
     {
         key_lines[i][0] = ']';
         key_lines[i][1] = 0;
     }
     key_linepos = 1;
 //
 // init ascii characters in console mode
 //
     for (i=32 ; i<128 ; i++)
         consolekeys[i] = true;
     consolekeys[K_ENTER] = true;
     consolekeys[K_KP_ENTER] = true;
     consolekeys[K_TAB] = true;
     consolekeys[K_LEFTARROW] = true;
     consolekeys[K_KP_LEFTARROW] = true;
     consolekeys[K_RIGHTARROW] = true;
     consolekeys[K_KP_RIGHTARROW] = true;
     consolekeys[K_UPARROW] = true;
     consolekeys[K_KP_UPARROW] = true;
     consolekeys[K_DOWNARROW] = true;
     consolekeys[K_KP_DOWNARROW] = true;
     consolekeys[K_BACKSPACE] = true;
     consolekeys[K_HOME] = true;
     consolekeys[K_KP_HOME] = true;
     consolekeys[K_END] = true;
     consolekeys[K_KP_END] = true;
     consolekeys[K_PGUP] = true;
     consolekeys[K_KP_PGUP] = true;
     consolekeys[K_PGDN] = true;
     consolekeys[K_KP_PGDN] = true;
     consolekeys[K_MWHEELUP] = true;
     consolekeys[K_MWHEELDOWN] = true;
     consolekeys[K_SHIFT] = true;
     consolekeys[K_INS] = true;
     consolekeys[K_KP_INS] = true;
     consolekeys[K_KP_DEL] = true;
     consolekeys[K_KP_SLASH] = true;
     consolekeys[K_KP_PLUS] = true;
     consolekeys[K_KP_MINUS] = true;
     consolekeys[K_KP_5] = true;
     consolekeys['`'] = false;
     consolekeys['~'] = false;
     for (i=0 ; i<256 ; i++)
         keyshift[i] = i;
     for (i='a' ; i<='z' ; i++)
         keyshift[i] = i - 'a' + 'A';
     keyshift['1'] = '!';
     keyshift['2'] = '@';
     keyshift['3'] = '#';
     keyshift['4'] = '$';
     keyshift['5'] = '%';
     keyshift['6'] = '^';
     keyshift['7'] = '&';
     keyshift['8'] = '*';
     keyshift['9'] = '(';
     keyshift['0'] = ')';
     keyshift['-'] = '_';
     keyshift['='] = '+';
     keyshift[','] = '<';
     keyshift['.'] = '>';
     keyshift['/'] = '?';
     keyshift[';'] = ':';
     keyshift['\''] = '"';
     keyshift['['] = '{';
     keyshift[']'] = '}';
     keyshift['`'] = '~';
     keyshift['\\'] = '|';
     menubound[K_ESCAPE] = true;
     for (i=0 ; i<12 ; i++)
         menubound[K_F1+i] = true;
 //
 // register our functions
 //
     Cmd_AddCommand ("bind",Key_Bind_f);
     Cmd_AddCommand ("unbind",Key_Unbind_f);
     Cmd_AddCommand ("unbindall",Key_Unbindall_f);
     Cmd_AddCommand ("bindlist",Key_Bindlist_f);
 }
Referenced by Qcommon_Init().
memsearch()
int memsearch (byte * start, int count, int search)
just for debugging
Definition at line 1027 of file common.c.
 {
     int     i;
     for (i=0 ; i<count ; i++)
         if (start[i] == search)
             return i;
     return -1;
 }
MSG_BeginReading()
void MSG_BeginReading (sizebuf_t * msg)
Definition at line 684 of file common.c.
 {
     msg->readcount = 0;
 }
Referenced by CL_ConnectionlessPacket(), Netchan_Process(), SV_ConnectionlessPacket(), and SV_ReadPackets().
MSG_ReadAngle()
float MSG_ReadAngle (sizebuf_t * msg_read)
Definition at line 825 of file common.c.
 {
     return MSG_ReadChar(msg_read) * (360.0/256);
 }
Referenced by CL_ParseDelta().
MSG_ReadAngle16()
float MSG_ReadAngle16 (sizebuf_t * msg_read)
Definition at line 830 of file common.c.
 {
     return SHORT2ANGLE(MSG_ReadShort(msg_read));
 }
Referenced by CL_ParsePlayerstate().
MSG_ReadByte()
int MSG_ReadByte (sizebuf_t * msg_read)
Definition at line 703 of file common.c.
 {
     int c;
     if (msg_read->readcount+1 > msg_read->cursize)
         c = -1;
     else
         c = (unsigned char)msg_read->data[msg_read->readcount];
     msg_read->readcount++;
     return c;
 }
Referenced by CL_ParseDelta(), CL_ParseDownload(), CL_ParseEntityBits(), CL_ParseFrame(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParseParticles(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), MSG_ReadData(), MSG_ReadDeltaUsercmd(), MSG_ReadDir(), and SV_ExecuteClientMessage().
MSG_ReadChar()
int MSG_ReadChar (sizebuf_t * msg_read)
Definition at line 690 of file common.c.
 {
     int c;
     if (msg_read->readcount+1 > msg_read->cursize)
         c = -1;
     else
         c = (signed char)msg_read->data[msg_read->readcount];
     msg_read->readcount++;
     return c;
 }
Referenced by CL_ParsePlayerstate(), MSG_ReadAngle(), MSG_ReadString(), and MSG_ReadStringLine().
MSG_ReadCoord()
float MSG_ReadCoord (sizebuf_t * msg_read)
Definition at line 813 of file common.c.
 {
     return MSG_ReadShort(msg_read) * (1.0/8);
 }
Referenced by CL_ParseDelta().
MSG_ReadData()
void MSG_ReadData (sizebuf_t * msg_read, void * data, int len)
Definition at line 874 of file common.c.
 {
     int     i;
     for (i=0 ; i<len ; i++)
         ((byte *)data)[i] = MSG_ReadByte (msg_read);
 }
Referenced by CL_ParseFrame().
MSG_ReadDeltaUsercmd()
void MSG_ReadDeltaUsercmd (sizebuf_t * msg_read, usercmd_t * from, usercmd_t * move)
Definition at line 835 of file common.c.
 {
     int bits;
     memcpy (move, from, sizeof(*move));
     bits = MSG_ReadByte (msg_read);
 // read current angles
     if (bits & CM_ANGLE1)
         move->angles[0] = MSG_ReadShort (msg_read);
     if (bits & CM_ANGLE2)
         move->angles[1] = MSG_ReadShort (msg_read);
     if (bits & CM_ANGLE3)
         move->angles[2] = MSG_ReadShort (msg_read);
 // read movement
     if (bits & CM_FORWARD)
         move->forwardmove = MSG_ReadShort (msg_read);
     if (bits & CM_SIDE)
         move->sidemove = MSG_ReadShort (msg_read);
     if (bits & CM_UP)
         move->upmove = MSG_ReadShort (msg_read);
 // read buttons
     if (bits & CM_BUTTONS)
         move->buttons = MSG_ReadByte (msg_read);
     if (bits & CM_IMPULSE)
         move->impulse = MSG_ReadByte (msg_read);
 // read time to run command
     move->msec = MSG_ReadByte (msg_read);
 // read the light level
     move->lightlevel = MSG_ReadByte (msg_read);
 }
Referenced by SV_ExecuteClientMessage().
MSG_ReadDir()
void MSG_ReadDir (sizebuf_t * sb, vec3_t dir)
Definition at line 464 of file common.c.
 {
     int     b;
     b = MSG_ReadByte (sb);
     if (b >= NUMVERTEXNORMALS)
         Com_Error (ERR_DROP, "MSF_ReadDir: out of range");
     VectorCopy (bytedirs[b], dir);
 }
Referenced by CL_ParseParticles(), CL_ParseSteam(), and CL_ParseTEnt().
MSG_ReadFloat()
float MSG_ReadFloat (sizebuf_t * msg_read)
Definition at line 748 of file common.c.
 {
     union
     {
         byte    b[4];
         float   f;
         int l;
     } dat;
     if (msg_read->readcount+4 > msg_read->cursize)
         dat.f = -1;
     else
     {
         dat.b[0] =  msg_read->data[msg_read->readcount];
         dat.b[1] =  msg_read->data[msg_read->readcount+1];
         dat.b[2] =  msg_read->data[msg_read->readcount+2];
         dat.b[3] =  msg_read->data[msg_read->readcount+3];
     }
     msg_read->readcount += 4;
     dat.l = LittleLong (dat.l);
     return dat.f;
 }
MSG_ReadLong()
int MSG_ReadLong (sizebuf_t * msg_read)
Definition at line 731 of file common.c.
 {
     int c;
     if (msg_read->readcount+4 > msg_read->cursize)
         c = -1;
     else
         c = msg_read->data[msg_read->readcount]
         + (msg_read->data[msg_read->readcount+1]<<8)
         + (msg_read->data[msg_read->readcount+2]<<16)
         + (msg_read->data[msg_read->readcount+3]<<24);
     msg_read->readcount += 4;
     return c;
 }
Referenced by CL_ConnectionlessPacket(), CL_ParseDelta(), CL_ParseFrame(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseSteam(), Netchan_Process(), SV_ConnectionlessPacket(), SV_ExecuteClientMessage(), and SV_ReadPackets().
MSG_ReadPos()
void MSG_ReadPos (sizebuf_t * msg_read, vec3_t pos)
Definition at line 818 of file common.c.
 {
     pos[0] = MSG_ReadShort(msg_read) * (1.0/8);
     pos[1] = MSG_ReadShort(msg_read) * (1.0/8);
     pos[2] = MSG_ReadShort(msg_read) * (1.0/8);
 }
Referenced by CL_ParseBeam(), CL_ParseBeam2(), CL_ParseDelta(), CL_ParseLaser(), CL_ParseLightning(), CL_ParseNuke(), CL_ParseParticles(), CL_ParsePlayerBeam(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), and CL_ParseWidow().
MSG_ReadShort()
int MSG_ReadShort (sizebuf_t * msg_read)
Definition at line 716 of file common.c.
 {
     int c;
     if (msg_read->readcount+2 > msg_read->cursize)
         c = -1;
     else
         c = (short)(msg_read->data[msg_read->readcount]
         + (msg_read->data[msg_read->readcount+1]<<8));
     msg_read->readcount += 2;
     return c;
 }
Referenced by CL_ParseBeam(), CL_ParseBeam2(), CL_ParseConfigString(), CL_ParseDelta(), CL_ParseDownload(), CL_ParseEntityBits(), CL_ParseInventory(), CL_ParseLightning(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParsePlayerBeam(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), CL_ParseWidow(), MSG_ReadAngle16(), MSG_ReadCoord(), MSG_ReadDeltaUsercmd(), MSG_ReadPos(), Netchan_Process(), and SV_ReadPackets().
MSG_ReadString()
char* MSG_ReadString (sizebuf_t * msg_read)
Definition at line 773 of file common.c.
 {
     static char string[2048];
     int     l,c;
     l = 0;
     do
     {
         c = MSG_ReadChar (msg_read);
         if (c == -1 || c == 0)
             break;
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
Referenced by CL_ConnectionlessPacket(), CL_ParseConfigString(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStatusMessage(), and SV_ExecuteClientMessage().
MSG_ReadStringLine()
char* MSG_ReadStringLine (sizebuf_t * msg_read)
Definition at line 793 of file common.c.
 {
     static char string[2048];
     int     l,c;
     l = 0;
     do
     {
         c = MSG_ReadChar (msg_read);
         if (c == -1 || c == 0 || c == '\n')
             break;
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
Referenced by CL_ConnectionlessPacket(), and SV_ConnectionlessPacket().
MSG_WriteAngle()
void MSG_WriteAngle (sizebuf_t * sb, float f)
Definition at line 376 of file common.c.
 {
     MSG_WriteByte (sb, (int)(f*256/360) & 255);
 }
Referenced by MSG_WriteDeltaEntity(), and PF_WriteAngle().
MSG_WriteAngle16()
void MSG_WriteAngle16 (sizebuf_t * sb, float f)
Definition at line 381 of file common.c.
 {
     MSG_WriteShort (sb, ANGLE2SHORT(f));
 }
Referenced by SV_WritePlayerstateToClient().
MSG_WriteByte()
void MSG_WriteByte (sizebuf_t * sb, int c)
Definition at line 303 of file common.c.
 {
     byte    *buf;
 #ifdef PARANOID
     if (c < 0 || c > 255)
         Com_Error (ERR_FATAL, "MSG_WriteByte: range error");
 #endif
     buf = SZ_GetSpace (sb, 1);
     buf[0] = c;
 }
Referenced by CL_CheckOrDownloadFile(), CL_Download_f(), CL_ForwardToServer_f(), CL_ParseDownload(), CL_Record_f(), CL_RequestNextDownload(), CL_SendCmd(), Cmd_ForwardToServer(), MSG_WriteAngle(), MSG_WriteDeltaEntity(), MSG_WriteDeltaUsercmd(), MSG_WriteDir(), PF_centerprintf(), PF_WriteByte(), SCR_FinishCinematic(), SV_Baselines_f(), SV_BeginDownload_f(), SV_BroadcastCommand(), SV_BroadcastPrintf(), SV_ClientPrintf(), SV_Configstrings_f(), SV_DropClient(), SV_EmitPacketEntities(), SV_FinalMessage(), SV_FlushRedirect(), SV_New_f(), SV_NextDownload_f(), SV_RecordDemoMessage(), SV_ServerRecord_f(), SV_StartSound(), SV_WriteFrameToClient(), and SV_WritePlayerstateToClient().
MSG_WriteChar()
void MSG_WriteChar (sizebuf_t * sb, int c)
Definition at line 290 of file common.c.
 {
     byte    *buf;
 #ifdef PARANOID
     if (c < -128 || c > 127)
         Com_Error (ERR_FATAL, "MSG_WriteChar: range error");
 #endif
     buf = SZ_GetSpace (sb, 1);
     buf[0] = c;
 }
Referenced by CL_ConnectionlessPacket(), CL_Reconnect_f(), PF_Configstring(), PF_WriteChar(), SV_FindIndex(), and SV_WritePlayerstateToClient().
MSG_WriteCoord()
void MSG_WriteCoord (sizebuf_t * sb, float f)
Definition at line 364 of file common.c.
 {
     MSG_WriteShort (sb, (int)(f*8));
 }
Referenced by MSG_WriteDeltaEntity().
MSG_WriteDeltaEntity()
void MSG_WriteDeltaEntity (entity_state_t * from, entity_state_t * to, sizebuf_t * msg, qboolean force, qboolean newentity)
Definition at line 483 of file common.c.
 {
     int     bits;
     if (!to->number)
         Com_Error (ERR_FATAL, "Unset entity number");
     if (to->number >= MAX_EDICTS)
         Com_Error (ERR_FATAL, "Entity number >= MAX_EDICTS");
 // send an update
     bits = 0;
     if (to->number >= 256)
         bits |= U_NUMBER16;     // number8 is implicit otherwise
     if (to->origin[0] != from->origin[0])
         bits |= U_ORIGIN1;
     if (to->origin[1] != from->origin[1])
         bits |= U_ORIGIN2;
     if (to->origin[2] != from->origin[2])
         bits |= U_ORIGIN3;
     if ( to->angles[0] != from->angles[0] )
         bits |= U_ANGLE1;
     if ( to->angles[1] != from->angles[1] )
         bits |= U_ANGLE2;
     if ( to->angles[2] != from->angles[2] )
         bits |= U_ANGLE3;
     if ( to->skinnum != from->skinnum )
     {
         if ((unsigned)to->skinnum < 256)
             bits |= U_SKIN8;
         else if ((unsigned)to->skinnum < 0x10000)
             bits |= U_SKIN16;
         else
             bits |= (U_SKIN8|U_SKIN16);
     }
     if ( to->frame != from->frame )
     {
         if (to->frame < 256)
             bits |= U_FRAME8;
         else
             bits |= U_FRAME16;
     }
     if ( to->effects != from->effects )
     {
         if (to->effects < 256)
             bits |= U_EFFECTS8;
         else if (to->effects < 0x8000)
             bits |= U_EFFECTS16;
         else
             bits |= U_EFFECTS8|U_EFFECTS16;
     }
     if ( to->renderfx != from->renderfx )
     {
         if (to->renderfx < 256)
             bits |= U_RENDERFX8;
         else if (to->renderfx < 0x8000)
             bits |= U_RENDERFX16;
         else
             bits |= U_RENDERFX8|U_RENDERFX16;
     }
     if ( to->solid != from->solid )
         bits |= U_SOLID;
     // event is not delta compressed, just 0 compressed
     if ( to->event  )
         bits |= U_EVENT;
     if ( to->modelindex != from->modelindex )
         bits |= U_MODEL;
     if ( to->modelindex2 != from->modelindex2 )
         bits |= U_MODEL2;
     if ( to->modelindex3 != from->modelindex3 )
         bits |= U_MODEL3;
     if ( to->modelindex4 != from->modelindex4 )
         bits |= U_MODEL4;
     if ( to->sound != from->sound )
         bits |= U_SOUND;
     if (newentity || (to->renderfx & RF_BEAM))
         bits |= U_OLDORIGIN;
     //
     // write the message
     //
     if (!bits && !force)
         return;     // nothing to send!
     //----------
     if (bits & 0xff000000)
         bits |= U_MOREBITS3 | U_MOREBITS2 | U_MOREBITS1;
     else if (bits & 0x00ff0000)
         bits |= U_MOREBITS2 | U_MOREBITS1;
     else if (bits & 0x0000ff00)
         bits |= U_MOREBITS1;
     MSG_WriteByte (msg, bits&255 );
     if (bits & 0xff000000)
     {
         MSG_WriteByte (msg, (bits>>8)&255 );
         MSG_WriteByte (msg, (bits>>16)&255 );
         MSG_WriteByte (msg, (bits>>24)&255 );
     }
     else if (bits & 0x00ff0000)
     {
         MSG_WriteByte (msg, (bits>>8)&255 );
         MSG_WriteByte (msg, (bits>>16)&255 );
     }
     else if (bits & 0x0000ff00)
     {
         MSG_WriteByte (msg, (bits>>8)&255 );
     }
     //----------
     if (bits & U_NUMBER16)
         MSG_WriteShort (msg, to->number);
     else
         MSG_WriteByte (msg, to->number);
     if (bits & U_MODEL)
         MSG_WriteByte (msg, to->modelindex);
     if (bits & U_MODEL2)
         MSG_WriteByte (msg, to->modelindex2);
     if (bits & U_MODEL3)
         MSG_WriteByte (msg, to->modelindex3);
     if (bits & U_MODEL4)
         MSG_WriteByte (msg, to->modelindex4);
     if (bits & U_FRAME8)
         MSG_WriteByte (msg, to->frame);
     if (bits & U_FRAME16)
         MSG_WriteShort (msg, to->frame);
     if ((bits & U_SKIN8) && (bits & U_SKIN16))      //used for laser colors
         MSG_WriteLong (msg, to->skinnum);
     else if (bits & U_SKIN8)
         MSG_WriteByte (msg, to->skinnum);
     else if (bits & U_SKIN16)
         MSG_WriteShort (msg, to->skinnum);
     if ( (bits & (U_EFFECTS8|U_EFFECTS16)) == (U_EFFECTS8|U_EFFECTS16) )
         MSG_WriteLong (msg, to->effects);
     else if (bits & U_EFFECTS8)
         MSG_WriteByte (msg, to->effects);
     else if (bits & U_EFFECTS16)
         MSG_WriteShort (msg, to->effects);
     if ( (bits & (U_RENDERFX8|U_RENDERFX16)) == (U_RENDERFX8|U_RENDERFX16) )
         MSG_WriteLong (msg, to->renderfx);
     else if (bits & U_RENDERFX8)
         MSG_WriteByte (msg, to->renderfx);
     else if (bits & U_RENDERFX16)
         MSG_WriteShort (msg, to->renderfx);
     if (bits & U_ORIGIN1)
         MSG_WriteCoord (msg, to->origin[0]);
     if (bits & U_ORIGIN2)
         MSG_WriteCoord (msg, to->origin[1]);
     if (bits & U_ORIGIN3)
         MSG_WriteCoord (msg, to->origin[2]);
     if (bits & U_ANGLE1)
         MSG_WriteAngle(msg, to->angles[0]);
     if (bits & U_ANGLE2)
         MSG_WriteAngle(msg, to->angles[1]);
     if (bits & U_ANGLE3)
         MSG_WriteAngle(msg, to->angles[2]);
     if (bits & U_OLDORIGIN)
     {
         MSG_WriteCoord (msg, to->old_origin[0]);
         MSG_WriteCoord (msg, to->old_origin[1]);
         MSG_WriteCoord (msg, to->old_origin[2]);
     }
     if (bits & U_SOUND)
         MSG_WriteByte (msg, to->sound);
     if (bits & U_EVENT)
         MSG_WriteByte (msg, to->event);
     if (bits & U_SOLID)
         MSG_WriteShort (msg, to->solid);
 }
Referenced by CL_Record_f(), SV_Baselines_f(), SV_EmitPacketEntities(), and SV_RecordDemoMessage().
MSG_WriteDeltaUsercmd()
void MSG_WriteDeltaUsercmd (sizebuf_t * buf, usercmd_t * from, usercmd_t * cmd)
Definition at line 387 of file common.c.
 {
     int     bits;
 //
 // send the movement message
 //
     bits = 0;
     if (cmd->angles[0] != from->angles[0])
         bits |= CM_ANGLE1;
     if (cmd->angles[1] != from->angles[1])
         bits |= CM_ANGLE2;
     if (cmd->angles[2] != from->angles[2])
         bits |= CM_ANGLE3;
     if (cmd->forwardmove != from->forwardmove)
         bits |= CM_FORWARD;
     if (cmd->sidemove != from->sidemove)
         bits |= CM_SIDE;
     if (cmd->upmove != from->upmove)
         bits |= CM_UP;
     if (cmd->buttons != from->buttons)
         bits |= CM_BUTTONS;
     if (cmd->impulse != from->impulse)
         bits |= CM_IMPULSE;
     MSG_WriteByte (buf, bits);
     if (bits & CM_ANGLE1)
         MSG_WriteShort (buf, cmd->angles[0]);
     if (bits & CM_ANGLE2)
         MSG_WriteShort (buf, cmd->angles[1]);
     if (bits & CM_ANGLE3)
         MSG_WriteShort (buf, cmd->angles[2]);
     if (bits & CM_FORWARD)
         MSG_WriteShort (buf, cmd->forwardmove);
     if (bits & CM_SIDE)
         MSG_WriteShort (buf, cmd->sidemove);
     if (bits & CM_UP)
         MSG_WriteShort (buf, cmd->upmove);
     if (bits & CM_BUTTONS)
         MSG_WriteByte (buf, cmd->buttons);
     if (bits & CM_IMPULSE)
         MSG_WriteByte (buf, cmd->impulse);
     MSG_WriteByte (buf, cmd->msec);
     MSG_WriteByte (buf, cmd->lightlevel);
 }
Referenced by CL_SendCmd().
MSG_WriteDir()
void MSG_WriteDir (sizebuf_t * sb, vec3_t dir)
Definition at line 438 of file common.c.
 {
     int     i, best;
     float   d, bestd;
     if (!dir)
     {
         MSG_WriteByte (sb, 0);
         return;
     }
     bestd = 0;
     best = 0;
     for (i=0 ; i<NUMVERTEXNORMALS ; i++)
     {
         d = DotProduct (dir, bytedirs[i]);
         if (d > bestd)
         {
             bestd = d;
             best = i;
         }
     }
     MSG_WriteByte (sb, best);
 }
Referenced by PF_WriteDir().
MSG_WriteFloat()
void MSG_WriteFloat (sizebuf_t * sb, float f)
Definition at line 341 of file common.c.
 {
     union
     {
         float   f;
         int l;
     } dat;
     dat.f = f;
     dat.l = LittleLong (dat.l);
     SZ_Write (sb, &dat.l, 4);
 }
Referenced by PF_WriteFloat().
MSG_WriteLong()
void MSG_WriteLong (sizebuf_t * sb, int c)
Definition at line 330 of file common.c.
 {
     byte    *buf;
     buf = SZ_GetSpace (sb, 4);
     buf[0] = c&0xff;
     buf[1] = (c>>8)&0xff;
     buf[2] = (c>>16)&0xff;
     buf[3] = c>>24;
 }
Referenced by CL_Record_f(), CL_SendCmd(), MSG_WriteDeltaEntity(), Netchan_OutOfBand(), Netchan_Transmit(), PF_WriteLong(), SV_New_f(), SV_RecordDemoMessage(), SV_ServerRecord_f(), SV_WriteFrameToClient(), and SV_WritePlayerstateToClient().
MSG_WritePos()
void MSG_WritePos (sizebuf_t * sb, vec3_t pos)
Definition at line 369 of file common.c.
 {
     MSG_WriteShort (sb, (int)(pos[0]*8));
     MSG_WriteShort (sb, (int)(pos[1]*8));
     MSG_WriteShort (sb, (int)(pos[2]*8));
 }
Referenced by PF_WritePos(), and SV_StartSound().
MSG_WriteShort()
void MSG_WriteShort (sizebuf_t * sb, int c)
Definition at line 316 of file common.c.
 {
     byte    *buf;
 #ifdef PARANOID
     if (c < ((short)0x8000) || c > (short)0x7fff)
         Com_Error (ERR_FATAL, "MSG_WriteShort: range error");
 #endif
     buf = SZ_GetSpace (sb, 2);
     buf[0] = c&0xff;
     buf[1] = c>>8;
 }
Referenced by CL_Record_f(), MSG_WriteAngle16(), MSG_WriteCoord(), MSG_WriteDeltaEntity(), MSG_WriteDeltaUsercmd(), MSG_WritePos(), Netchan_Transmit(), PF_Configstring(), PF_WriteShort(), SV_BeginDownload_f(), SV_Configstrings_f(), SV_EmitPacketEntities(), SV_FindIndex(), SV_New_f(), SV_NextDownload_f(), SV_RecordDemoMessage(), SV_ServerRecord_f(), SV_StartSound(), and SV_WritePlayerstateToClient().
MSG_WriteString()
void MSG_WriteString (sizebuf_t * sb, char * s)
Definition at line 356 of file common.c.
 {
     if (!s)
         SZ_Write (sb, "", 1);
     else
         SZ_Write (sb, s, (int)strlen(s)+1);
 }
Referenced by CL_CheckOrDownloadFile(), CL_ConnectionlessPacket(), CL_Download_f(), CL_Reconnect_f(), CL_Record_f(), CL_RequestNextDownload(), CL_SendCmd(), PF_centerprintf(), PF_Configstring(), PF_WriteString(), SV_Baselines_f(), SV_BroadcastCommand(), SV_BroadcastPrintf(), SV_ClientPrintf(), SV_Configstrings_f(), SV_FinalMessage(), SV_FindIndex(), SV_FlushRedirect(), SV_New_f(), and SV_ServerRecord_f().
Qcommon_Frame()
void Qcommon_Frame (int msec)
Definition at line 1500 of file common.c.
 {
     char    *s;
     int     time_before, time_between, time_after;
     if (setjmp (abortframe) )
     {
         if (shutdown_game)
             SV_ShutdownGameProgs();
         shutdown_game = false;
         return;         // an ERR_DROP was thrown
     }
     if ( log_stats->modified )
     {
         log_stats->modified = false;
         if ( log_stats->value )
         {
             if ( log_stats_file )
             {
                 fclose( log_stats_file );
                 log_stats_file = 0;
             }
             log_stats_file = fopen( "stats.log", "w" );
             if ( log_stats_file )
                 fprintf( log_stats_file, "entities,dlights,parts,frame time\n" );
         }
         else
         {
             if ( log_stats_file )
             {
                 fclose( log_stats_file );
                 log_stats_file = 0;
             }
         }
     }
     if (fixedtime->value)
         msec = fixedtime->value;
     else if (timescale->value)
     {
         msec *= timescale->value;
         if (msec < 1)
             msec = 1;
     }
     if (showtrace->value)
     {
         extern  int c_traces, c_brush_traces;
         extern  int c_pointcontents;
         Com_Printf ("%4i traces  %4i points\n", c_traces, c_pointcontents);
         c_traces = 0;
         c_brush_traces = 0;
         c_pointcontents = 0;
     }
     do
     {
         s = Sys_ConsoleInput ();
         if (s)
             Cbuf_AddText (va("%s\n",s));
     } while (s);
     Cbuf_Execute ();
     if (host_speeds->value)
         time_before = Sys_Milliseconds ();
     SV_Frame (msec);
     if (host_speeds->value)
         time_between = Sys_Milliseconds ();
     CL_Frame (msec);
     if (host_speeds->value)
         time_after = Sys_Milliseconds ();
     if (host_speeds->value)
     {
         int         all, sv, gm, cl, rf;
         all = time_after - time_before;
         sv = time_between - time_before;
         cl = time_after - time_between;
         gm = time_after_game - time_before_game;
         rf = time_after_ref - time_before_ref;
         sv -= gm;
         cl -= rf;
         Com_Printf ("all:%3i sv:%3i gm:%3i cl:%3i rf:%3i\n",
             all, sv, gm, cl, rf);
     }
 }
Referenced by WinMain().
Qcommon_Init()
void Qcommon_Init (int argc, char ** argv)
Definition at line 1407 of file common.c.
 {
     char    *s;
     if (setjmp (abortframe) )
         Sys_Error ("Error during initialization");
     z_chain.next = z_chain.prev = &z_chain;
     // prepare enough of the subsystems to handle
     // cvar and command buffer management
     COM_InitArgv (argc, argv);
     Swap_Init ();
     Cbuf_Init ();
     Cmd_Init ();
     Cvar_Init ();
     Key_Init ();
     // we need to add the early commands twice, because
     // a basedir or cddir needs to be set before execing
     // config files, but we want other parms to override
     // the settings of the config files
     Cbuf_AddEarlyCommands (false);
     Cbuf_Execute ();
     FS_InitFilesystem ();
     Cbuf_AddText ("exec default.cfg\n");
     Cbuf_AddText ("exec config.cfg\n");
     Cbuf_AddEarlyCommands (true);
     Cbuf_Execute ();
     //
     // init commands and vars
     //
     Cmd_AddCommand ("z_stats", Z_Stats_f);
     Cmd_AddCommand ("error", Com_Error_f);
     host_speeds = Cvar_Get ("host_speeds", "0", 0);
     log_stats = Cvar_Get ("log_stats", "0", 0);
     developer = Cvar_Get ("developer", "0", 0);
     timescale = Cvar_Get ("timescale", "1", 0);
     fixedtime = Cvar_Get ("fixedtime", "0", 0);
     logfile_active = Cvar_Get ("logfile", "0", 0);
     showtrace = Cvar_Get ("showtrace", "0", 0);
 #ifdef DEDICATED_ONLY
     dedicated = Cvar_Get ("dedicated", "1", CVAR_NOSET);
 #else
     dedicated = Cvar_Get ("dedicated", "0", CVAR_NOSET);
 #endif
     s = va("%4.2f %s %s %s", VERSION, CPUSTRING, __DATE__, BUILDSTRING);
     Cvar_Get ("version", s, CVAR_SERVERINFO|CVAR_NOSET);
     if (dedicated->value)
         Cmd_AddCommand ("quit", Com_Quit);
     Sys_Init ();
     NET_Init ();
     Netchan_Init ();
     SV_Init ();
     CL_Init ();
     // add + commands from command line
     if (!Cbuf_AddLateCommands ())
     {   // if the user didn't give any commands, run default action
         if (!dedicated->value)
             Cbuf_AddText ("d1\n");
         else
             Cbuf_AddText ("dedicated_start\n");
         Cbuf_Execute ();
     }
     else
     {   // the user asked for something explicit
         // so drop the loading plaque
         SCR_EndLoadingPlaque ();
     }
     Com_Printf ("====== Quake2 Initialized ======\n\n");
 }
Referenced by WinMain().
Qcommon_Shutdown()
void Qcommon_Shutdown (void)
Definition at line 1600 of file common.c.
 {
 }
Referenced by Sys_Error(), and Sys_Quit().
SCR_EndLoadingPlaque()
void SCR_EndLoadingPlaque (void)
Definition at line 590 of file cl_scrn.c.
 {
     cls.disable_screen = 0;
     Con_ClearNotify ();
 }
Referenced by CL_Drop(), CL_ParseFrame(), Con_ToggleConsole_f(), Qcommon_Init(), and SCR_PlayCinematic().
SV_ShutdownGameProgs()
void SV_ShutdownGameProgs (void)
Definition at line 305 of file sv_game.c.
 {
     if (!ge)
         return;
     ge->Shutdown ();
     Sys_UnloadGame ();
     ge = NULL;
 }
Referenced by Com_Error(), Com_Quit(), Qcommon_Frame(), SV_InitGame(), and SV_KillServer_f().
SZ_Clear()
void SZ_Clear (sizebuf_t * buf)
Definition at line 892 of file common.c.
 {
     buf->cursize = 0;
     buf->overflowed = false;
 }
Referenced by Cbuf_InsertText(), CL_ClearState(), PF_Configstring(), PF_Unicast(), SV_FinalMessage(), SV_FindIndex(), SV_Multicast(), SV_RecordDemoMessage(), SV_SendClientDatagram(), SV_SendClientMessages(), and SZ_GetSpace().
SZ_GetSpace()
void* SZ_GetSpace (sizebuf_t * buf, int length)
Definition at line 898 of file common.c.
 {
     void    *data;
     if (buf->cursize + length > buf->maxsize)
     {
         if (!buf->allowoverflow)
             Com_Error (ERR_FATAL, "SZ_GetSpace: overflow without allowoverflow set");
         if (length > buf->maxsize)
             Com_Error (ERR_FATAL, "SZ_GetSpace: %i is > full buffer size", length);
         Com_Printf ("SZ_GetSpace: overflow\n");
         SZ_Clear (buf);
         buf->overflowed = true;
     }
     data = buf->data + buf->cursize;
     buf->cursize += length;
     return data;
 }
Referenced by MSG_WriteByte(), MSG_WriteChar(), MSG_WriteLong(), MSG_WriteShort(), SZ_Print(), and SZ_Write().
SZ_Init()
void SZ_Init (sizebuf_t * buf, byte * data, int length)
Definition at line 885 of file common.c.
 {
     memset (buf, 0, sizeof(*buf));
     buf->data = data;
     buf->maxsize = length;
 }
Referenced by Cbuf_Init(), CL_Record_f(), CL_SendCmd(), Netchan_OutOfBand(), Netchan_Setup(), Netchan_Transmit(), SV_Init(), SV_RecordDemoMessage(), SV_SendClientDatagram(), SV_ServerRecord_f(), SV_SpawnServer(), and SVC_DirectConnect().
SZ_Print()
void SZ_Print (sizebuf_t * buf, char * data)
Definition at line 926 of file common.c.
 {
     int     len;
     len = (int)strlen(data)+1;
     if (buf->cursize)
     {
         if (buf->data[buf->cursize-1])
             memcpy ((byte *)SZ_GetSpace(buf, len),data,len); // no trailing 0
         else
             memcpy ((byte *)SZ_GetSpace(buf, len-1)-1,data,len); // write over trailing 0
     }
     else
         memcpy ((byte *)SZ_GetSpace(buf, len),data,len);
 }
Referenced by CL_ForwardToServer_f(), CL_ParseDownload(), Cmd_ForwardToServer(), and SCR_FinishCinematic().
SZ_Write()
void SZ_Write (sizebuf_t * buf, void * data, int length)
Definition at line 921 of file common.c.
 {
     memcpy (SZ_GetSpace(buf,length),data,length);
 }
Referenced by Cbuf_AddText(), Cbuf_InsertText(), MSG_WriteFloat(), MSG_WriteString(), Netchan_OutOfBand(), Netchan_Transmit(), PF_Unicast(), SV_Multicast(), SV_NextDownload_f(), SV_RecordDemoMessage(), SV_SendClientDatagram(), and SV_WriteFrameToClient().
Z_Free()
void Z_Free (void * ptr)
Definition at line 1122 of file common.c.
 {
     zhead_t *z;
     z = ((zhead_t *)ptr) - 1;
     if (z->magic != Z_MAGIC)
         Com_Error (ERR_FATAL, "Z_Free: bad magic");
     z->prev->next = z->next;
     z->next->prev = z->prev;
     z_count--;
     z_bytes -= z->size;
     free (z);
 }
Referenced by Cbuf_AddLateCommands(), Cbuf_InsertText(), Cmd_Alias_f(), Cmd_Exec_f(), Cmd_RemoveCommand(), Cmd_TokenizeString(), Cvar_FullSet(), Cvar_GetLatchedVars(), Cvar_Set2(), FS_FreeFile(), FS_Link_f(), FS_SetGamedir(), Key_SetBinding(), S_EndRegistration(), S_Shutdown(), SCR_LoadPCX(), SCR_PlayCinematic(), SCR_RunCinematic(), SCR_StopCinematic(), SV_InitGameProgs(), SV_Shutdown(), and Z_FreeTags().
Z_FreeTags()
void Z_FreeTags (int tag)
Definition at line 1155 of file common.c.
 {
     zhead_t *z, *next;
     for (z=z_chain.next ; z != &z_chain ; z=next)
     {
         next = z->next;
         if (z->tag == tag)
             Z_Free ((void *)(z+1));
     }
 }
Referenced by SV_InitGameProgs().
Z_Malloc()
void* Z_Malloc (int size)
Definition at line 1200 of file common.c.
 {
     return Z_TagMalloc (size, 0);
 }
Referenced by Cbuf_AddLateCommands(), Cbuf_InsertText(), Cmd_AddCommand(), Cmd_Alias_f(), Cmd_Exec_f(), Cmd_TokenizeString(), CopyString(), Cvar_Get(), FS_AddGameDirectory(), FS_Link_f(), FS_LoadFile(), FS_LoadPackFile(), Huff1Decompress(), Huff1TableInit(), Key_SetBinding(), S_AliasName(), S_LoadSound(), SCR_LoadPCX(), and SV_InitGame().
Z_Stats_f()
void Z_Stats_f (void)
Definition at line 1145 of file common.c.
 {
     Com_Printf ("%i bytes in %i blocks\n", z_bytes, z_count);
 }
Referenced by Qcommon_Init().
Z_TagMalloc()
void* Z_TagMalloc (int size, int tag)
Definition at line 1172 of file common.c.
 {
     zhead_t *z;
     size = size + sizeof(zhead_t);
     z = malloc(size);
     if (!z)
         Com_Error (ERR_FATAL, "Z_Malloc: failed on allocation of %i bytes",size);
     memset (z, 0, size);
     z_count++;
     z_bytes += size;
     z->magic = Z_MAGIC;
     z->tag = tag;
     z->size = size;
     z->next = z_chain.next;
     z->prev = &z_chain;
     z_chain.next->prev = z;
     z_chain.next = z;
     return (void *)(z+1);
 }
Referenced by SV_InitGameProgs(), and Z_Malloc().
Variable Documentation
abortframe
jmp_buf abortframe
Definition at line 35 of file common.c.
Referenced by Com_Error(), Qcommon_Frame(), and Qcommon_Init().
bytedirs
vec3_t bytedirs[NUMVERTEXNORMALS]
Initial value:
=
{
}
Definition at line 281 of file common.c.
Referenced by CL_BfgParticles(), CL_FlyParticles(), COM_BlockSequenceCheckByte(), MSG_ReadDir(), and MSG_WriteDir().
chktbl
byte chktbl[1024] static
Definition at line 1264 of file common.c.
Referenced by COM_BlockSequenceCRCByte().
com_argc
int com_argc
Definition at line 30 of file common.c.
Referenced by COM_AddParm(), COM_Argc(), COM_Argv(), COM_CheckParm(), COM_ClearArgv(), and COM_InitArgv().
com_argv
char* com_argv[MAX_NUM_ARGVS+1]
Definition at line 31 of file common.c.
Referenced by COM_AddParm(), COM_Argv(), COM_CheckParm(), COM_ClearArgv(), and COM_InitArgv().
dedicated
cvar_t* dedicated
Definition at line 47 of file common.c.
Referenced by CL_Frame(), CL_Init(), Cmd_Say_f(), FS_SetGamedir(), InitGame(), Master_Heartbeat(), Master_Shutdown(), NET_GetPacket(), NET_OpenIP(), NET_OpenIPX(), NET_SendPacket(), NET_Sleep(), Qcommon_Init(), SV_BroadcastPrintf(), SV_GameMap_f(), SV_InitGame(), SV_InitOperatorCommands(), SV_SetMaster_f(), Sys_ConsoleInput(), Sys_ConsoleOutput(), Sys_Init(), Sys_Quit(), and WinMain().
developer
cvar_t* developer
Definition at line 42 of file common.c.
Referenced by Com_DPrintf(), Qcommon_Init(), and SCR_BeginLoadingPlaque().
fixedtime
cvar_t* fixedtime
Definition at line 44 of file common.c.
Referenced by Qcommon_Frame(), and Qcommon_Init().
host_speeds
cvar_t* host_speeds
Definition at line 40 of file common.c.
Referenced by CL_Frame(), Qcommon_Frame(), Qcommon_Init(), and SV_RunGameFrame().
log_stats
cvar_t* log_stats
Definition at line 41 of file common.c.
Referenced by CL_Frame(), Qcommon_Frame(), Qcommon_Init(), and V_RenderView().
log_stats_file
FILE* log_stats_file
Definition at line 38 of file common.c.
Referenced by CL_Frame(), Qcommon_Frame(), and V_RenderView().
logfile
FILE* logfile
Definition at line 49 of file common.c.
Referenced by Com_Error(), Com_Printf(), and Com_Quit().
logfile_active
cvar_t* logfile_active
Definition at line 45 of file common.c.
Referenced by Com_Printf(), and Qcommon_Init().
rd_buffer
char* rd_buffer static
Definition at line 68 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
rd_buffersize
int rd_buffersize static
Definition at line 69 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
rd_flush
void(* rd_flush) (int target, char *buffer) static
Definition at line 70 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
rd_target
int rd_target static
Definition at line 67 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
realtime
int realtime
Definition at line 33 of file common.c.
server_state
int server_state
Definition at line 51 of file common.c.
Referenced by Com_ServerState(), and Com_SetServerState().
showtrace
cvar_t* showtrace
Definition at line 46 of file common.c.
Referenced by Qcommon_Frame(), and Qcommon_Init().
shutdown_game
qboolean shutdown_game = false static
Definition at line 36 of file common.c.
Referenced by Com_Error(), and Qcommon_Frame().
time_after_game
int time_after_game
Definition at line 55 of file common.c.
Referenced by Qcommon_Frame(), SV_Frame(), and SV_RunGameFrame().
time_after_ref
int time_after_ref
Definition at line 57 of file common.c.
Referenced by CL_Frame(), and Qcommon_Frame().
time_before_game
int time_before_game
Definition at line 54 of file common.c.
Referenced by Qcommon_Frame(), SV_Frame(), and SV_RunGameFrame().
time_before_ref
int time_before_ref
Definition at line 56 of file common.c.
Referenced by CL_Frame(), and Qcommon_Frame().
timescale
cvar_t* timescale
Definition at line 43 of file common.c.
Referenced by Qcommon_Frame(), and Qcommon_Init().
z_bytes
int z_bytes
Definition at line 1115 of file common.c.
Referenced by Z_Free(), Z_Stats_f(), and Z_TagMalloc().
z_chain
zhead_t z_chain
Definition at line 1114 of file common.c.
Referenced by Qcommon_Init(), Z_FreeTags(), and Z_TagMalloc().
z_count
int z_count
Definition at line 1115 of file common.c.
Referenced by Z_Free(), Z_Stats_f(), and Z_TagMalloc().