vkQuake2 doxygen: C:/entry/dev/vq2/src/client/cdaudio.h File Reference
cdaudio.h File Reference
Functions
int CDAudio_Init (void)
void CDAudio_Shutdown (void)
qboolean CDAudio_Play (int track, qboolean looping)
void CDAudio_Stop (void)
void CDAudio_Update (void)
void CDAudio_Activate (qboolean active)
Function Documentation
CDAudio_Activate()
void CDAudio_Activate (qboolean active)
Definition at line 506 of file cd_win.c.
 {
     if (active)
         CDAudio_Resume ();
     else
         CDAudio_Pause ();
 }
Referenced by AppActivate().
CDAudio_Init()
int CDAudio_Init (void)
Definition at line 437 of file cd_win.c.
 {
     DWORD   dwReturn;
     MCI_OPEN_PARMS  mciOpenParms;
     MCI_SET_PARMS   mciSetParms;
     int             n;
     cd_nocd = Cvar_Get ("cd_nocd", "0", CVAR_ARCHIVE );
     cd_loopcount = Cvar_Get ("cd_loopcount", "4", 0);
     cd_looptrack = Cvar_Get ("cd_looptrack", "11", 0);
     if ( cd_nocd->value)
         return -1;
     mciOpenParms.lpstrDeviceType = "cdaudio";
     if (dwReturn = mciSendCommand(0, MCI_OPEN, MCI_OPEN_TYPE | MCI_OPEN_SHAREABLE, (DWORD_PTR) (LPVOID) &mciOpenParms))
     {
         Com_Printf("CDAudio_Init: MCI_OPEN failed (%i)\n", dwReturn);
         return -1;
     }
     wDeviceID = mciOpenParms.wDeviceID;
     // Set the time format to track/minute/second/frame (TMSF).
     mciSetParms.dwTimeFormat = MCI_FORMAT_TMSF;
     if (dwReturn = mciSendCommand(wDeviceID, MCI_SET, MCI_SET_TIME_FORMAT, (DWORD_PTR)(LPVOID) &mciSetParms))
     {
         Com_Printf("MCI_SET_TIME_FORMAT failed (%i)\n", dwReturn);
         mciSendCommand(wDeviceID, MCI_CLOSE, 0, (DWORD_PTR)NULL);
         return -1;
     }
     for (n = 0; n < 100; n++)
         remap[n] = n;
     initialized = true;
     enabled = true;
     if (CDAudio_GetAudioDiskInfo())
     {
 //      Com_Printf("CDAudio_Init: No CD in player.\n");
         cdValid = false;
         enabled = false;
     }
     Cmd_AddCommand ("cd", CD_f);
     Com_Printf("CD Audio Initialized\n");
     return 0;
 }
Referenced by CL_Init().
CDAudio_Play()
qboolean CDAudio_Play (int track, qboolean looping)
Definition at line 186 of file cd_win.c.
 {
     // set a loop counter so that this track will change to the
     // looptrack later
     loopcounter = 0;
     return CDAudio_Play2(track, looping);
 }
Referenced by CD_f(), CDAudio_Update(), CL_ParseConfigString(), and CL_PrepRefresh().
CDAudio_Shutdown()
void CDAudio_Shutdown (void)
Definition at line 487 of file cd_win.c.
 {
     if (!initialized)
         return;
     CDAudio_Stop();
     if (mciSendCommand(wDeviceID, MCI_CLOSE, MCI_WAIT, (DWORD_PTR)NULL))
         Com_DPrintf("CDAudio_Shutdown: MCI_CLOSE failed\n");
 }
Referenced by CL_Shutdown().
CDAudio_Stop()
void CDAudio_Stop (void)
Definition at line 194 of file cd_win.c.
 {
     DWORD   dwReturn;
     if (!enabled)
         return;
     if (!playing)
         return;
     if (dwReturn = mciSendCommand(wDeviceID, MCI_STOP, 0, (DWORD_PTR)NULL))
         Com_DPrintf("MCI_STOP failed (%i)", dwReturn);
     wasPlaying = false;
     playing = false;
 }
Referenced by CD_f(), CDAudio_MessageHandler(), CDAudio_Play2(), CDAudio_Shutdown(), and CDAudio_Update().
CDAudio_Update()
void CDAudio_Update (void)
Definition at line 419 of file cd_win.c.
 {
     if ( cd_nocd->value != !enabled )
     {
         if ( cd_nocd->value )
         {
             CDAudio_Stop ();
             enabled = false;
         }
         else
         {
             enabled = true;
             CDAudio_Play (playTrack, playLooping);
         }
     }
 }
Referenced by CL_Frame().