vq2 doxygen: game_export_t Struct Reference
game_export_t Struct Reference
#include <game.h>
Public Attributes
int apiversion
void(* Init)(void)
void(* Shutdown)(void)
void(* SpawnEntities)(char *mapname, char *entstring, char *spawnpoint)
void(* WriteGame)(char *filename, qboolean autosave)
void(* ReadGame)(char *filename)
void(* WriteLevel)(char *filename)
void(* ReadLevel)(char *filename)
qboolean(* ClientConnect)(edict_t *ent, char *userinfo)
void(* ClientBegin)(edict_t *ent)
void(* ClientUserinfoChanged)(edict_t *ent, char *userinfo)
void(* ClientDisconnect)(edict_t *ent)
void(* ClientCommand)(edict_t *ent)
void(* ClientThink)(edict_t *ent, usercmd_t *cmd)
void(* RunFrame)(void)
void(* ServerCommand)(void)
struct edict_s * edicts
int edict_size
int num_edicts
int max_edicts
Detailed Description
Definition at line 188 of file game.h.
Member Data Documentation
apiversion
int game_export_t::apiversion
Definition at line 190 of file game.h.
Referenced by GetGameAPI(), and SV_InitGameProgs().
ClientBegin
void(* game_export_t::ClientBegin)(edict_t *ent)
Definition at line 214 of file game.h.
Referenced by GetGameAPI(), and SV_Begin_f().
ClientCommand
void(* game_export_t::ClientCommand)(edict_t *ent)
Definition at line 217 of file game.h.
Referenced by GetGameAPI(), and SV_ExecuteUserCommand().
ClientConnect
qboolean(* game_export_t::ClientConnect)(edict_t *ent, char *userinfo)
Definition at line 213 of file game.h.
Referenced by GetGameAPI(), and SVC_DirectConnect().
ClientDisconnect
void(* game_export_t::ClientDisconnect)(edict_t *ent)
Definition at line 216 of file game.h.
Referenced by GetGameAPI(), and SV_DropClient().
ClientThink
void(* game_export_t::ClientThink)(edict_t *ent, usercmd_t *cmd)
Definition at line 218 of file game.h.
Referenced by GetGameAPI(), and SV_ClientThink().
ClientUserinfoChanged
void(* game_export_t::ClientUserinfoChanged)(edict_t *ent, char *userinfo)
Definition at line 215 of file game.h.
Referenced by GetGameAPI(), and SV_UserinfoChanged().
edict_size
int game_export_t::edict_size
Definition at line 237 of file game.h.
Referenced by GetGameAPI().
edicts
struct edict_s * game_export_t::edicts
Definition at line 236 of file game.h.
Referenced by InitGame(), ReadGame(), SV_LinkEdict(), and SV_Trace().
Init
void(* game_export_t::Init)(void)
Definition at line 195 of file game.h.
Referenced by GetGameAPI(), and SV_InitGameProgs().
max_edicts
int game_export_t::max_edicts
Definition at line 239 of file game.h.
Referenced by InitGame().
num_edicts
int game_export_t::num_edicts
Definition at line 238 of file game.h.
Referenced by CTFResetAllPlayers(), CTFResetTech(), findradius(), G_Find(), G_FindTeams(), G_RunFrame(), G_Spawn(), InitGame(), loc_findradius(), ReadLevel(), SV_BuildClientFrame(), SV_CreateBaseline(), SV_PrepWorldFrame(), SV_Push(), target_earthquake_think(), and WriteLevel().
ReadGame
void(* game_export_t::ReadGame)(char *filename)
Definition at line 206 of file game.h.
Referenced by GetGameAPI(), and SV_ReadServerFile().
ReadLevel
void(* game_export_t::ReadLevel)(char *filename)
Definition at line 211 of file game.h.
Referenced by GetGameAPI(), and SV_ReadLevelFile().
RunFrame
void(* game_export_t::RunFrame)(void)
Definition at line 220 of file game.h.
Referenced by GetGameAPI(), SV_CheckForSavegame(), SV_RunGameFrame(), and SV_SpawnServer().
ServerCommand
void(* game_export_t::ServerCommand)(void)
Definition at line 226 of file game.h.
Referenced by GetGameAPI(), and SV_ServerCommand_f().
Shutdown
void(* game_export_t::Shutdown)(void)
Definition at line 196 of file game.h.
Referenced by GetGameAPI(), and SV_ShutdownGameProgs().
SpawnEntities
void(* game_export_t::SpawnEntities)(char *mapname, char *entstring, char *spawnpoint)
Definition at line 199 of file game.h.
Referenced by GetGameAPI(), and SV_SpawnServer().
WriteGame
void(* game_export_t::WriteGame)(char *filename, qboolean autosave)
Definition at line 205 of file game.h.
Referenced by GetGameAPI(), and SV_WriteServerFile().
WriteLevel
void(* game_export_t::WriteLevel)(char *filename)
Definition at line 210 of file game.h.
Referenced by GetGameAPI(), and SV_WriteLevelFile().
The documentation for this struct was generated from the following file:
C:/entry/syn/github/vq2/ctf/game.h