vq2 doxygen: C:/entry/syn/github/vq2/ctf/g_save.c File Reference
g_save.c File Reference
#include "g_local.h"
Functions
void InitGame (void)
void WriteField1 (FILE *f, field_t *field, byte *base)
void WriteField2 (FILE *f, field_t *field, byte *base)
void ReadField (FILE *f, field_t *field, byte *base)
void WriteClient (FILE *f, gclient_t *client)
void ReadClient (FILE *f, gclient_t *client)
void WriteGame (char *filename, qboolean autosave)
void ReadGame (char *filename)
void WriteEdict (FILE *f, edict_t *ent)
void WriteLevelLocals (FILE *f)
void ReadEdict (FILE *f, edict_t *ent)
void ReadLevelLocals (FILE *f)
void WriteLevel (char *filename)
void ReadLevel (char *filename)
Variables
field_t fields []
field_t savefields []
field_t levelfields []
field_t clientfields []
Function Documentation
InitGame()
void InitGame (void)
Definition at line 147 of file g_save.c.
 {
     gi.dprintf ("==== InitGame ====\n");
     gun_x = gi.cvar ("gun_x", "0", 0);
     gun_y = gi.cvar ("gun_y", "0", 0);
     gun_z = gi.cvar ("gun_z", "0", 0);
     //FIXME: sv_ prefix is wrong for these
     sv_rollspeed = gi.cvar ("sv_rollspeed", "200", 0);
     sv_rollangle = gi.cvar ("sv_rollangle", "2", 0);
     sv_maxvelocity = gi.cvar ("sv_maxvelocity", "2000", 0);
     sv_gravity = gi.cvar ("sv_gravity", "800", 0);
     // noset vars
     dedicated = gi.cvar ("dedicated", "0", CVAR_NOSET);
     // latched vars
     sv_cheats = gi.cvar ("cheats", "0", CVAR_SERVERINFO|CVAR_LATCH);
     gi.cvar ("gamename", GAMEVERSION , CVAR_SERVERINFO | CVAR_LATCH);
     gi.cvar ("gamedate", __DATE__ , CVAR_SERVERINFO | CVAR_LATCH);
     maxclients = gi.cvar ("maxclients", "4", CVAR_SERVERINFO | CVAR_LATCH);
     deathmatch = gi.cvar ("deathmatch", "0", CVAR_LATCH);
     coop = gi.cvar ("coop", "0", CVAR_LATCH);
     skill = gi.cvar ("skill", "1", CVAR_LATCH);
     maxentities = gi.cvar ("maxentities", "1024", CVAR_LATCH);
 //ZOID
 //This game.dll only supports deathmatch
     if (!deathmatch->value) {
         gi.dprintf("Forcing deathmatch.");
         gi.cvar_set("deathmatch", "1");
     }
     //force coop off
     if (coop->value)
         gi.cvar_set("coop", "0");
 //ZOID
     // change anytime vars
     dmflags = gi.cvar ("dmflags", "0", CVAR_SERVERINFO);
     fraglimit = gi.cvar ("fraglimit", "0", CVAR_SERVERINFO);
     timelimit = gi.cvar ("timelimit", "0", CVAR_SERVERINFO);
 //ZOID
     capturelimit = gi.cvar ("capturelimit", "0", CVAR_SERVERINFO);
     instantweap = gi.cvar ("instantweap", "0", CVAR_SERVERINFO);
 //ZOID
     password = gi.cvar ("password", "", CVAR_USERINFO);
     filterban = gi.cvar ("filterban", "1", 0);
     g_select_empty = gi.cvar ("g_select_empty", "0", CVAR_ARCHIVE);
     run_pitch = gi.cvar ("run_pitch", "0.002", 0);
     run_roll = gi.cvar ("run_roll", "0.005", 0);
     bob_up  = gi.cvar ("bob_up", "0.005", 0);
     bob_pitch = gi.cvar ("bob_pitch", "0.002", 0);
     bob_roll = gi.cvar ("bob_roll", "0.002", 0);
     // flood control
     flood_msgs = gi.cvar ("flood_msgs", "4", 0);
     flood_persecond = gi.cvar ("flood_persecond", "4", 0);
     flood_waitdelay = gi.cvar ("flood_waitdelay", "10", 0);
     // dm map list
     sv_maplist = gi.cvar ("sv_maplist", "", 0);
     // items
     InitItems ();
     Com_sprintf (game.helpmessage1, sizeof(game.helpmessage1), "");
     Com_sprintf (game.helpmessage2, sizeof(game.helpmessage2), "");
     // initialize all entities for this game
     game.maxentities = maxentities->value;
     g_edicts =  gi.TagMalloc (game.maxentities * sizeof(g_edicts[0]), TAG_GAME);
     globals.edicts = g_edicts;
     globals.max_edicts = game.maxentities;
     // initialize all clients for this game
     game.maxclients = maxclients->value;
     game.clients = gi.TagMalloc (game.maxclients * sizeof(game.clients[0]), TAG_GAME);
     globals.num_edicts = game.maxclients+1;
 //ZOID
     CTFInit();
 //ZOID
 }
Referenced by ReadField(), ReadLevel(), WriteField1(), and WriteLevel().
ReadClient()
void ReadClient (FILE * f, gclient_t * client)
Definition at line 414 of file g_save.c.
 {
     field_t     *field;
     fread (client, sizeof(*client), 1, f);
     for (field=clientfields ; field->name ; field++)
     {
         ReadField (f, field, (byte *)client);
     }
 }
Referenced by ReadGame().
ReadEdict()
void ReadEdict (FILE * f, edict_t * ent)
Definition at line 571 of file g_save.c.
 {
     field_t     *field;
     fread (ent, sizeof(*ent), 1, f);
     for (field=savefields ; field->name ; field++)
     {
         ReadField (f, field, (byte *)ent);
     }
 }
Referenced by ReadLevel().
ReadField()
void ReadField (FILE * f, field_t * field, byte * base)
Definition at line 311 of file g_save.c.
 {
     void        *p;
     int         len;
     int         index;
     p = (void *)(base + field->ofs);
     switch (field->type)
     {
     case F_INT:
     case F_FLOAT:
     case F_ANGLEHACK:
     case F_VECTOR:
     case F_IGNORE:
         break;
     case F_LSTRING:
         len = *(int *)p;
         if (!len)
             *(char **)p = NULL;
         else
         {
             *(char **)p = gi.TagMalloc (len, TAG_LEVEL);
             fread (*(char **)p, len, 1, f);
         }
         break;
     case F_GSTRING:
         len = *(int *)p;
         if (!len)
             *(char **)p = NULL;
         else
         {
             *(char **)p = gi.TagMalloc (len, TAG_GAME);
             fread (*(char **)p, len, 1, f);
         }
         break;
     case F_EDICT:
         index = *(int *)p;
         if ( index == -1 )
             *(edict_t **)p = NULL;
         else
             *(edict_t **)p = &g_edicts[index];
         break;
     case F_CLIENT:
         index = *(int *)p;
         if ( index == -1 )
             *(gclient_t **)p = NULL;
         else
             *(gclient_t **)p = &game.clients[index];
         break;
     case F_ITEM:
         index = *(int *)p;
         if ( index == -1 )
             *(gitem_t **)p = NULL;
         else
             *(gitem_t **)p = &itemlist[index];
         break;
     default:
         gi.error ("ReadEdict: unknown field type");
     }
 }
Referenced by ReadClient(), ReadEdict(), and ReadLevelLocals().
ReadGame()
void ReadGame (char * filename)
Definition at line 467 of file g_save.c.
 {
     FILE    *f;
     int     i;
     char    str[16];
     gi.FreeTags (TAG_GAME);
     f = fopen (filename, "rb");
     if (!f)
         gi.error ("Couldn't open %s", filename);
     fread (str, sizeof(str), 1, f);
     if (strcmp (str, __DATE__))
     {
         fclose (f);
         gi.error ("Savegame from an older version.\n");
     }
     g_edicts =  gi.TagMalloc (game.maxentities * sizeof(g_edicts[0]), TAG_GAME);
     globals.edicts = g_edicts;
     fread (&game, sizeof(game), 1, f);
     game.clients = gi.TagMalloc (game.maxclients * sizeof(game.clients[0]), TAG_GAME);
     for (i=0 ; i<game.maxclients ; i++)
         ReadClient (f, &game.clients[i]);
     fclose (f);
 }
ReadLevel()
void ReadLevel (char * filename)
Definition at line 662 of file g_save.c.
 {
     int     entnum;
     FILE    *f;
     int     i;
     void    *base;
     edict_t *ent;
     f = fopen (filename, "rb");
     if (!f)
         gi.error ("Couldn't open %s", filename);
     // free any dynamic memory allocated by loading the level
     // base state
     gi.FreeTags (TAG_LEVEL);
     // wipe all the entities
     memset (g_edicts, 0, game.maxentities*sizeof(g_edicts[0]));
     globals.num_edicts = maxclients->value+1;
     // check edict size
     fread (&i, sizeof(i), 1, f);
     if (i != sizeof(edict_t))
     {
         fclose (f);
         gi.error ("ReadLevel: mismatched edict size");
     }
     // check function pointer base address
     fread (&base, sizeof(base), 1, f);
     if (base != (void *)InitGame)
     {
         fclose (f);
         gi.error ("ReadLevel: function pointers have moved");
     }
     // load the level locals
     ReadLevelLocals (f);
     // load all the entities
     while (1)
     {
         if (fread (&entnum, sizeof(entnum), 1, f) != 1)
         {
             fclose (f);
             gi.error ("ReadLevel: failed to read entnum");
         }
         if (entnum == -1)
             break;
         if (entnum >= globals.num_edicts)
             globals.num_edicts = entnum+1;
         ent = &g_edicts[entnum];
         ReadEdict (f, ent);
         // let the server rebuild world links for this ent
         memset (&ent->area, 0, sizeof(ent->area));
         gi.linkentity (ent);
     }
     fclose (f);
     // mark all clients as unconnected
     for (i=0 ; i<maxclients->value ; i++)
     {
         ent = &g_edicts[i+1];
         ent->client = game.clients + i;
         ent->client->pers.connected = false;
     }
     // do any load time things at this point
     for (i=0 ; i<globals.num_edicts ; i++)
     {
         ent = &g_edicts[i];
         if (!ent->inuse)
             continue;
         // fire any cross-level triggers
         if (ent->classname)
             if (strcmp(ent->classname, "target_crosslevel_target") == 0)
                 ent->nextthink = level.time + ent->delay;
     }
 }
ReadLevelLocals()
void ReadLevelLocals (FILE * f)
Definition at line 590 of file g_save.c.
 {
     field_t     *field;
     fread (&level, sizeof(level), 1, f);
     for (field=levelfields ; field->name ; field++)
     {
         ReadField (f, field, (byte *)&level);
     }
 }
Referenced by ReadLevel().
WriteClient()
void WriteClient (FILE * f, gclient_t * client)
Definition at line 383 of file g_save.c.
 {
     field_t     *field;
     gclient_t   temp;
     // all of the ints, floats, and vectors stay as they are
     temp = *client;
     // change the pointers to lengths or indexes
     for (field=clientfields ; field->name ; field++)
     {
         WriteField1 (f, field, (byte *)&temp);
     }
     // write the block
     fwrite (&temp, sizeof(temp), 1, f);
     // now write any allocated data following the edict
     for (field=clientfields ; field->name ; field++)
     {
         WriteField2 (f, field, (byte *)client);
     }
 }
Referenced by WriteGame().
WriteEdict()
void WriteEdict (FILE * f, edict_t * ent)
Definition at line 507 of file g_save.c.
 {
     field_t     *field;
     edict_t     temp;
     // all of the ints, floats, and vectors stay as they are
     temp = *ent;
     // change the pointers to lengths or indexes
     for (field=savefields ; field->name ; field++)
     {
         WriteField1 (f, field, (byte *)&temp);
     }
     // write the block
     fwrite (&temp, sizeof(temp), 1, f);
     // now write any allocated data following the edict
     for (field=savefields ; field->name ; field++)
     {
         WriteField2 (f, field, (byte *)ent);
     }
 }
Referenced by WriteLevel().
WriteField1()
void WriteField1 (FILE * f, field_t * field, byte * base)
Definition at line 239 of file g_save.c.
 {
     void        *p;
     int         len;
     int         index;
     p = (void *)(base + field->ofs);
     switch (field->type)
     {
     case F_INT:
     case F_FLOAT:
     case F_ANGLEHACK:
     case F_VECTOR:
     case F_IGNORE:
         break;
     case F_LSTRING:
     case F_GSTRING:
         if ( *(char **)p )
             len = (int)strlen(*(char **)p) + 1;
         else
             len = 0;
         *(int *)p = len;
         break;
     case F_EDICT:
         if ( *(edict_t **)p == NULL)
             index = -1;
         else
             index = *(edict_t **)p - g_edicts;
         *(int *)p = index;
         break;
     case F_CLIENT:
         if ( *(gclient_t **)p == NULL)
             index = -1;
         else
             index = *(gclient_t **)p - game.clients;
         *(int *)p = index;
         break;
     case F_ITEM:
         if ( *(edict_t **)p == NULL)
             index = -1;
         else
             index = *(gitem_t **)p - itemlist;
         *(int *)p = index;
         break;
     default:
         gi.error ("WriteEdict: unknown field type");
     }
 }
Referenced by WriteClient(), WriteEdict(), and WriteLevelLocals().
WriteField2()
void WriteField2 (FILE * f, field_t * field, byte * base)
Definition at line 290 of file g_save.c.
 {
     int         len;
     void        *p;
     p = (void *)(base + field->ofs);
     switch (field->type)
     {
     case F_LSTRING:
     case F_GSTRING:
         if ( *(char **)p )
         {
             len = (int)strlen(*(char **)p) + 1;
             fwrite (*(char **)p, len, 1, f);
         }
         break;
     default:
         break;
     }
 }
Referenced by WriteClient(), WriteEdict(), and WriteLevelLocals().
WriteGame()
void WriteGame (char * filename, qboolean autosave)
Definition at line 440 of file g_save.c.
 {
     FILE    *f;
     int     i;
     char    str[16];
     if (!autosave)
         SaveClientData ();
     f = fopen (filename, "wb");
     if (!f)
         gi.error ("Couldn't open %s", filename);
     memset (str, 0, sizeof(str));
     strcpy (str, __DATE__);
     fwrite (str, sizeof(str), 1, f);
     game.autosaved = autosave;
     fwrite (&game, sizeof(game), 1, f);
     game.autosaved = false;
     for (i=0 ; i<game.maxclients ; i++)
         WriteClient (f, &game.clients[i]);
     fclose (f);
 }
WriteLevel()
void WriteLevel (char * filename)
Definition at line 608 of file g_save.c.
 {
     int     i;
     edict_t *ent;
     FILE    *f;
     void    *base;
     f = fopen (filename, "wb");
     if (!f)
         gi.error ("Couldn't open %s", filename);
     // write out edict size for checking
     i = sizeof(edict_t);
     fwrite (&i, sizeof(i), 1, f);
     // write out a function pointer for checking
     base = (void *)InitGame;
     fwrite (&base, sizeof(base), 1, f);
     // write out level_locals_t
     WriteLevelLocals (f);
     // write out all the entities
     for (i=0 ; i<globals.num_edicts ; i++)
     {
         ent = &g_edicts[i];
         if (!ent->inuse)
             continue;
         fwrite (&i, sizeof(i), 1, f);
         WriteEdict (f, ent);
     }
     i = -1;
     fwrite (&i, sizeof(i), 1, f);
     fclose (f);
 }
WriteLevelLocals()
void WriteLevelLocals (FILE * f)
Definition at line 539 of file g_save.c.
 {
     field_t     *field;
     level_locals_t      temp;
     // all of the ints, floats, and vectors stay as they are
     temp = level;
     // change the pointers to lengths or indexes
     for (field=levelfields ; field->name ; field++)
     {
         WriteField1 (f, field, (byte *)&temp);
     }
     // write the block
     fwrite (&temp, sizeof(temp), 1, f);
     // now write any allocated data following the edict
     for (field=levelfields ; field->name ; field++)
     {
         WriteField2 (f, field, (byte *)&level);
     }
 }
Referenced by WriteLevel().
Variable Documentation
clientfields
field_t clientfields[]
Initial value:
=
{
    {"", CLOFS(pers.weapon), F_ITEM},
    {"", CLOFS(pers.lastweapon), F_ITEM},
    {"", CLOFS(newweapon), F_ITEM},
    {NULL, 0, F_INT}
}
Definition at line 129 of file g_save.c.
Referenced by ReadClient(), and WriteClient().
fields
field_t fields[]
Definition at line 23 of file g_save.c.
Referenced by ReadEdict(), and WriteEdict().
levelfields
field_t levelfields[]
Initial value:
=
{
    {"", LLOFS(changemap), F_LSTRING},
    {"", LLOFS(sight_client), F_EDICT},
    {"", LLOFS(sight_entity), F_EDICT},
    {"", LLOFS(sound_entity), F_EDICT},
    {"", LLOFS(sound2_entity), F_EDICT},
    {NULL, 0, F_INT}
}
Definition at line 117 of file g_save.c.
Referenced by ReadLevelLocals(), and WriteLevelLocals().
savefields
field_t savefields[]
Definition at line 83 of file g_save.c.
Referenced by ReadEdict(), and WriteEdict().