vkQuake2 doxygen: C:/entry/dev/vq2/src/client/qmenu.h File Reference
qmenu.h File Reference
Classes
struct _tag_menuframework
struct menucommon_s
struct menufield_s
struct menuslider_s
struct menulist_s
struct menuaction_s
struct menuseparator_s
Macros
#define MAXMENUITEMS 64
#define MTYPE_SLIDER 0
#define MTYPE_LIST 1
#define MTYPE_ACTION 2
#define MTYPE_SPINCONTROL 3
#define MTYPE_SEPARATOR 4
#define MTYPE_FIELD 5
#define K_TAB 9
#define K_ENTER 13
#define K_ESCAPE 27
#define K_SPACE 32
#define K_BACKSPACE 127
#define K_UPARROW 128
#define K_DOWNARROW 129
#define K_LEFTARROW 130
#define K_RIGHTARROW 131
#define QMF_LEFT_JUSTIFY 0x00000001
#define QMF_GRAYED 0x00000002
#define QMF_NUMBERSONLY 0x00000004
Typedefs
typedef struct _tag_menuframework menuframework_s
Functions
qboolean Field_Key (menufield_s *field, int key)
void Menu_AddItem (menuframework_s *menu, void *item)
void Menu_AdjustCursor (menuframework_s *menu, int dir)
void Menu_Center (menuframework_s *menu)
void Menu_Draw (menuframework_s *menu)
void * Menu_ItemAtCursor (menuframework_s *m)
qboolean Menu_SelectItem (menuframework_s *s)
void Menu_SetStatusBar (menuframework_s *s, const char *string)
void Menu_SlideItem (menuframework_s *s, int dir)
int Menu_TallySlots (menuframework_s *menu)
void Menu_DrawString (int, int, const char *)
void Menu_DrawStringDark (int, int, const char *)
void Menu_DrawStringR2L (int, int, const char *)
void Menu_DrawStringR2LDark (int, int, const char *)
Macro Definition Documentation
K_BACKSPACE
#define K_BACKSPACE 127
Definition at line 39 of file qmenu.h.
K_DOWNARROW
#define K_DOWNARROW 129
Definition at line 41 of file qmenu.h.
K_ENTER
#define K_ENTER 13
Definition at line 33 of file qmenu.h.
K_ESCAPE
#define K_ESCAPE 27
Definition at line 34 of file qmenu.h.
K_LEFTARROW
#define K_LEFTARROW 130
Definition at line 42 of file qmenu.h.
K_RIGHTARROW
#define K_RIGHTARROW 131
Definition at line 43 of file qmenu.h.
K_SPACE
#define K_SPACE 32
Definition at line 35 of file qmenu.h.
K_TAB
#define K_TAB 9
Definition at line 32 of file qmenu.h.
K_UPARROW
#define K_UPARROW 128
Definition at line 40 of file qmenu.h.
MAXMENUITEMS
#define MAXMENUITEMS 64
Definition at line 23 of file qmenu.h.
MTYPE_ACTION
#define MTYPE_ACTION 2
Definition at line 27 of file qmenu.h.
MTYPE_FIELD
#define MTYPE_FIELD 5
Definition at line 30 of file qmenu.h.
MTYPE_LIST
#define MTYPE_LIST 1
Definition at line 26 of file qmenu.h.
MTYPE_SEPARATOR
#define MTYPE_SEPARATOR 4
Definition at line 29 of file qmenu.h.
MTYPE_SLIDER
#define MTYPE_SLIDER 0
Definition at line 25 of file qmenu.h.
MTYPE_SPINCONTROL
#define MTYPE_SPINCONTROL 3
Definition at line 28 of file qmenu.h.
QMF_GRAYED
#define QMF_GRAYED 0x00000002
Definition at line 46 of file qmenu.h.
QMF_LEFT_JUSTIFY
#define QMF_LEFT_JUSTIFY 0x00000001
Definition at line 45 of file qmenu.h.
QMF_NUMBERSONLY
#define QMF_NUMBERSONLY 0x00000004
Definition at line 47 of file qmenu.h.
Typedef Documentation
menuframework_s
typedef struct _tag_menuframework menuframework_s
Function Documentation
Field_Key()
qboolean Field_Key (menufield_s * field, int key)
Definition at line 135 of file qmenu.c.
 {
     extern int keydown[];
     switch ( key )
     {
     case K_KP_SLASH:
         key = '/';
         break;
     case K_KP_MINUS:
         key = '-';
         break;
     case K_KP_PLUS:
         key = '+';
         break;
     case K_KP_HOME:
         key = '7';
         break;
     case K_KP_UPARROW:
         key = '8';
         break;
     case K_KP_PGUP:
         key = '9';
         break;
     case K_KP_LEFTARROW:
         key = '4';
         break;
     case K_KP_5:
         key = '5';
         break;
     case K_KP_RIGHTARROW:
         key = '6';
         break;
     case K_KP_END:
         key = '1';
         break;
     case K_KP_DOWNARROW:
         key = '2';
         break;
     case K_KP_PGDN:
         key = '3';
         break;
     case K_KP_INS:
         key = '0';
         break;
     case K_KP_DEL:
         key = '.';
         break;
     }
     if ( key > 127 )
     {
         switch ( key )
         {
         case K_DEL:
         default:
             return false;
         }
     }
     /*
     ** support pasting from the clipboard
     */
     if ( ( toupper( key ) == 'V' && keydown[K_CTRL] ) ||
          ( ( ( key == K_INS ) || ( key == K_KP_INS ) ) && keydown[K_SHIFT] ) )
     {
         char *cbd;
         if ( ( cbd = Sys_GetClipboardData() ) != 0 )
         {
             strtok( cbd, "\n\r\b" );
             strncpy( f->buffer, cbd, f->length - 1 );
             f->cursor = (int)strlen( f->buffer );
             f->visible_offset = f->cursor - f->visible_length;
             if ( f->visible_offset < 0 )
                 f->visible_offset = 0;
             free( cbd );
         }
         return true;
     }
     switch ( key )
     {
     case K_KP_LEFTARROW:
     case K_LEFTARROW:
     case K_BACKSPACE:
         if ( f->cursor > 0 )
         {
             memmove( &f->buffer[f->cursor-1], &f->buffer[f->cursor], strlen( &f->buffer[f->cursor] ) + 1 );
             f->cursor--;
             if ( f->visible_offset )
             {
                 f->visible_offset--;
             }
         }
         break;
     case K_KP_DEL:
     case K_DEL:
         memmove( &f->buffer[f->cursor], &f->buffer[f->cursor+1], strlen( &f->buffer[f->cursor+1] ) + 1 );
         break;
     case K_KP_ENTER:
     case K_ENTER:
     case K_ESCAPE:
     case K_TAB:
         return false;
     case K_SPACE:
     default:
         if ( !isdigit( key ) && ( f->generic.flags & QMF_NUMBERSONLY ) )
             return false;
         if ( f->cursor < f->length )
         {
             f->buffer[f->cursor++] = key;
             f->buffer[f->cursor] = 0;
             if ( f->cursor > f->visible_length )
             {
                 f->visible_offset++;
             }
         }
     }
     return true;
 }
Referenced by Default_MenuKey().
Menu_AddItem()
void Menu_AddItem (menuframework_s * menu, void * item)
Definition at line 266 of file qmenu.c.
 {
     if ( menu->nitems == 0 )
         menu->nslots = 0;
     if ( menu->nitems < MAXMENUITEMS )
     {
         menu->items[menu->nitems] = item;
         ( ( menucommon_s * ) menu->items[menu->nitems] )->parent = menu;
         menu->nitems++;
     }
     menu->nslots = Menu_TallySlots( menu );
 }
Referenced by AddressBook_MenuInit(), DMOptions_MenuInit(), DownloadOptions_MenuInit(), Game_MenuInit(), JoinServer_MenuInit(), Keys_MenuInit(), LoadGame_MenuInit(), Multiplayer_MenuInit(), Options_MenuInit(), PlayerConfig_MenuInit(), SaveGame_MenuInit(), StartServer_MenuInit(), and VID_MenuInit().
Menu_AdjustCursor()
void Menu_AdjustCursor (menuframework_s * menu, int dir)
Definition at line 288 of file qmenu.c.
 {
     menucommon_s *citem;
     /*
     ** see if it's in a valid spot
     */
     if ( m->cursor >= 0 && m->cursor < m->nitems )
     {
         if ( ( citem = Menu_ItemAtCursor( m ) ) != 0 )
         {
             if ( citem->type != MTYPE_SEPARATOR )
                 return;
         }
     }
     /*
     ** it's not in a valid spot, so crawl in the direction indicated until we
     ** find a valid spot
     */
     if ( dir == 1 )
     {
         while ( 1 )
         {
             citem = Menu_ItemAtCursor( m );
             if ( citem )
                 if ( citem->type != MTYPE_SEPARATOR )
                     break;
             m->cursor += dir;
             if ( m->cursor >= m->nitems )
                 m->cursor = 0;
         }
     }
     else
     {
         while ( 1 )
         {
             citem = Menu_ItemAtCursor( m );
             if ( citem )
                 if ( citem->type != MTYPE_SEPARATOR )
                     break;
             m->cursor += dir;
             if ( m->cursor < 0 )
                 m->cursor = m->nitems - 1;
         }
     }
 }
Referenced by Default_MenuKey(), Game_MenuDraw(), Keys_MenuDraw(), Multiplayer_MenuDraw(), Options_MenuDraw(), SaveGame_MenuDraw(), VID_MenuDraw(), and VID_MenuKey().
Menu_Center()
void Menu_Center (menuframework_s * menu)
Definition at line 336 of file qmenu.c.
 {
     int height;
     height = ( ( menucommon_s * ) menu->items[menu->nitems-1])->y;
     height += 10;
     menu->y = ( VID_HEIGHT - height ) / 2;
 }
Referenced by DMOptions_MenuInit(), DownloadOptions_MenuInit(), Game_MenuInit(), JoinServer_MenuInit(), Keys_MenuInit(), Multiplayer_MenuInit(), StartServer_MenuInit(), and VID_MenuInit().
Menu_Draw()
void Menu_Draw (menuframework_s * menu)
Definition at line 346 of file qmenu.c.
 {
     int i;
     menucommon_s *item;
     /*
     ** draw contents
     */
     for ( i = 0; i < menu->nitems; i++ )
     {
         switch ( ( ( menucommon_s * ) menu->items[i] )->type )
         {
         case MTYPE_FIELD:
             Field_Draw( ( menufield_s * ) menu->items[i] );
             break;
         case MTYPE_SLIDER:
             Slider_Draw( ( menuslider_s * ) menu->items[i] );
             break;
         case MTYPE_LIST:
             MenuList_Draw( ( menulist_s * ) menu->items[i] );
             break;
         case MTYPE_SPINCONTROL:
             SpinControl_Draw( ( menulist_s * ) menu->items[i] );
             break;
         case MTYPE_ACTION:
             Action_Draw( ( menuaction_s * ) menu->items[i] );
             break;
         case MTYPE_SEPARATOR:
             Separator_Draw( ( menuseparator_s * ) menu->items[i] );
             break;
         }
     }
     item = Menu_ItemAtCursor( menu );
     if ( item && item->cursordraw )
     {
         item->cursordraw( item );
     }
     else if ( menu->cursordraw )
     {
         menu->cursordraw( menu );
     }
     else if ( item && item->type != MTYPE_FIELD )
     {
         if ( item->flags & QMF_LEFT_JUSTIFY )
         {
             Draw_Char( menu->x + item->x - 24*vid_hudscale->value + item->cursor_offset*vid_hudscale->value, menu->y + item->y, 12 + ( ( int ) ( Sys_Milliseconds()/250 ) & 1 ) );
         }
         else
         {
             Draw_Char( menu->x + item->cursor_offset*vid_hudscale->value, menu->y + item->y, 12 + ( ( int ) ( Sys_Milliseconds()/250 ) & 1 ) );
         }
     }
     if ( item )
     {
         if ( item->statusbarfunc )
             item->statusbarfunc( ( void * ) item );
         else if ( item->statusbar )
             Menu_DrawStatusBar( item->statusbar );
         else
             Menu_DrawStatusBar( menu->statusbar );
     }
     else
     {
         Menu_DrawStatusBar( menu->statusbar );
     }
 }
Referenced by AddressBook_MenuDraw(), DMOptions_MenuDraw(), DownloadOptions_MenuDraw(), Game_MenuDraw(), JoinServer_MenuDraw(), Keys_MenuDraw(), LoadGame_MenuDraw(), Multiplayer_MenuDraw(), Options_MenuDraw(), PlayerConfig_MenuDraw(), SaveGame_MenuDraw(), StartServer_MenuDraw(), and VID_MenuDraw().
Menu_DrawString()
void Menu_DrawString (int , int , const char *)
Definition at line 434 of file qmenu.c.
 {
     unsigned i;
     for ( i = 0; i < strlen( string ); i++ )
     {
         Draw_Char( ( x + i*8*vid_hudscale->value ), y, string[i] );
     }
 }
Referenced by Action_Draw(), DrawKeyBindingFunc(), Field_Draw(), Menu_DrawStatusBar(), and SpinControl_Draw().
Menu_DrawStringDark()
void Menu_DrawStringDark (int , int , const char *)
Definition at line 444 of file qmenu.c.
 {
     unsigned i;
     for ( i = 0; i < strlen( string ); i++ )
     {
         Draw_Char( ( x + i*8*vid_hudscale->value ), y, string[i] + 128 );
     }
 }
Referenced by Action_Draw().
Menu_DrawStringR2L()
void Menu_DrawStringR2L (int , int , const char *)
Definition at line 454 of file qmenu.c.
 {
     unsigned i;
     for ( i = 0; i < strlen( string ); i++ )
     {
         Draw_Char( ( x - i*8*vid_hudscale->value), y, string[strlen(string)-i-1] );
     }
 }
Referenced by Action_Draw().
Menu_DrawStringR2LDark()
void Menu_DrawStringR2LDark (int , int , const char *)
Definition at line 464 of file qmenu.c.
 {
     unsigned i;
     for ( i = 0; i < strlen( string ); i++ )
     {
         Draw_Char( ( x - i*8*vid_hudscale->value ), y, string[strlen(string)-i-1]+128 );
     }
 }
Referenced by Action_Draw(), Field_Draw(), MenuList_Draw(), Separator_Draw(), Slider_Draw(), and SpinControl_Draw().
Menu_ItemAtCursor()
void* Menu_ItemAtCursor (menuframework_s * m)
Definition at line 474 of file qmenu.c.
 {
     if ( m->cursor < 0 || m->cursor >= m->nitems )
         return 0;
     return m->items[m->cursor];
 }
Referenced by Default_MenuKey(), Field_Draw(), Keys_MenuKey(), Menu_AdjustCursor(), Menu_Draw(), Menu_SelectItem(), and Menu_SlideItem().
Menu_SelectItem()
qboolean Menu_SelectItem (menuframework_s * s)
Definition at line 482 of file qmenu.c.
 {
     menucommon_s *item = ( menucommon_s * ) Menu_ItemAtCursor( s );
     if ( item )
     {
         switch ( item->type )
         {
         case MTYPE_FIELD:
             return Field_DoEnter( ( menufield_s * ) item ) ;
         case MTYPE_ACTION:
             Action_DoEnter( ( menuaction_s * ) item );
             return true;
         case MTYPE_LIST:
 //          Menulist_DoEnter( ( menulist_s * ) item );
             return false;
         case MTYPE_SPINCONTROL:
 //          SpinControl_DoEnter( ( menulist_s * ) item );
             return false;
         }
     }
     return false;
 }
Referenced by Default_MenuKey(), and VID_MenuKey().
Menu_SetStatusBar()
void Menu_SetStatusBar (menuframework_s * s, const char * string)
Definition at line 506 of file qmenu.c.
 {
     m->statusbar = string;
 }
Referenced by DMOptions_MenuInit(), KeyBindingFunc(), Keys_MenuInit(), Keys_MenuKey(), M_Menu_PlayerConfig_f(), and Multiplayer_MenuInit().
Menu_SlideItem()
void Menu_SlideItem (menuframework_s * s, int dir)
Definition at line 511 of file qmenu.c.
 {
     menucommon_s *item = ( menucommon_s * ) Menu_ItemAtCursor( s );
     if ( item )
     {
         switch ( item->type )
         {
         case MTYPE_SLIDER:
             Slider_DoSlide( ( menuslider_s * ) item, dir );
             break;
         case MTYPE_SPINCONTROL:
             SpinControl_DoSlide( ( menulist_s * ) item, dir );
             break;
         }
     }
 }
Referenced by Default_MenuKey(), and VID_MenuKey().
Menu_TallySlots()
int Menu_TallySlots (menuframework_s * menu)
Definition at line 529 of file qmenu.c.
 {
     int i;
     int total = 0;
     for ( i = 0; i < menu->nitems; i++ )
     {
         if ( ( ( menucommon_s * ) menu->items[i] )->type == MTYPE_LIST )
         {
             int nitems = 0;
             const char **n = ( ( menulist_s * ) menu->items[i] )->itemnames;
             while (*n)
                 nitems++, n++;
             total += nitems;
         }
         else
         {
             total++;
         }
     }
     return total;
 }
Referenced by Menu_AddItem().