vq2 doxygen: C:/entry/syn/github/vq2/qcommon/qcommon.h File Reference
qcommon.h File Reference
#include "../game/q_shared.h"
#include "../qcommon/qfiles.h"
Classes
struct sizebuf_s
struct netadr_t
struct netchan_t
Macros
#define VERSION 3.21
#define BASEDIRNAME "baseq2"
#define BUILDSTRING "NON-WIN32"
#define CPUSTRING "NON-WIN32"
#define PROTOCOL_VERSION 34
#define PORT_MASTER 27900
#define PORT_CLIENT 27901
#define PORT_SERVER 27910
#define UPDATE_BACKUP 16
#define UPDATE_MASK (UPDATE_BACKUP-1)
#define PS_M_TYPE (1<<0)
#define PS_M_ORIGIN (1<<1)
#define PS_M_VELOCITY (1<<2)
#define PS_M_TIME (1<<3)
#define PS_M_FLAGS (1<<4)
#define PS_M_GRAVITY (1<<5)
#define PS_M_DELTA_ANGLES (1<<6)
#define PS_VIEWOFFSET (1<<7)
#define PS_VIEWANGLES (1<<8)
#define PS_KICKANGLES (1<<9)
#define PS_BLEND (1<<10)
#define PS_FOV (1<<11)
#define PS_WEAPONINDEX (1<<12)
#define PS_WEAPONFRAME (1<<13)
#define PS_RDFLAGS (1<<14)
#define CM_ANGLE1 (1<<0)
#define CM_ANGLE2 (1<<1)
#define CM_ANGLE3 (1<<2)
#define CM_FORWARD (1<<3)
#define CM_SIDE (1<<4)
#define CM_UP (1<<5)
#define CM_BUTTONS (1<<6)
#define CM_IMPULSE (1<<7)
#define SND_VOLUME (1<<0)
#define SND_ATTENUATION (1<<1)
#define SND_POS (1<<2)
#define SND_ENT (1<<3)
#define SND_OFFSET (1<<4)
#define DEFAULT_SOUND_PACKET_VOLUME 1.0
#define DEFAULT_SOUND_PACKET_ATTENUATION 1.0
#define U_ORIGIN1 (1<<0)
#define U_ORIGIN2 (1<<1)
#define U_ANGLE2 (1<<2)
#define U_ANGLE3 (1<<3)
#define U_FRAME8 (1<<4)
#define U_EVENT (1<<5)
#define U_REMOVE (1<<6)
#define U_MOREBITS1 (1<<7)
#define U_NUMBER16 (1<<8)
#define U_ORIGIN3 (1<<9)
#define U_ANGLE1 (1<<10)
#define U_MODEL (1<<11)
#define U_RENDERFX8 (1<<12)
#define U_EFFECTS8 (1<<14)
#define U_MOREBITS2 (1<<15)
#define U_SKIN8 (1<<16)
#define U_FRAME16 (1<<17)
#define U_RENDERFX16 (1<<18)
#define U_EFFECTS16 (1<<19)
#define U_MODEL2 (1<<20)
#define U_MODEL3 (1<<21)
#define U_MODEL4 (1<<22)
#define U_MOREBITS3 (1<<23)
#define U_OLDORIGIN (1<<24)
#define U_SKIN16 (1<<25)
#define U_SOUND (1<<26)
#define U_SOLID (1<<27)
#define EXEC_NOW 0
#define EXEC_INSERT 1
#define EXEC_APPEND 2
#define PORT_ANY -1
#define MAX_MSGLEN 1400
#define PACKET_HEADER 10
#define OLD_AVG 0.99
#define MAX_LATENT 32
#define ERR_FATAL 0
#define ERR_DROP 1
#define ERR_QUIT 2
#define EXEC_NOW 0
#define EXEC_INSERT 1
#define EXEC_APPEND 2
#define PRINT_ALL 0
#define PRINT_DEVELOPER 1
#define NUMVERTEXNORMALS 162
Typedefs
typedef struct sizebuf_s sizebuf_t
typedef void(* xcommand_t) (void)
Enumerations
enum svc_ops_e {
svc_bad, svc_muzzleflash, svc_muzzleflash2, svc_temp_entity,
svc_layout, svc_inventory, svc_nop, svc_disconnect,
svc_reconnect, svc_sound, svc_print, svc_stufftext,
svc_serverdata, svc_configstring, svc_spawnbaseline, svc_centerprint,
svc_download, svc_playerinfo, svc_packetentities, svc_deltapacketentities,
svc_frame
}
enum clc_ops_e {
clc_bad, clc_nop, clc_move, clc_userinfo,
clc_stringcmd
}
enum netadrtype_t {
NA_LOOPBACK, NA_BROADCAST, NA_IP, NA_IPX,
NA_BROADCAST_IPX
}
enum netsrc_t { NS_CLIENT, NS_SERVER }
Functions
void SZ_Init (sizebuf_t *buf, byte *data, int length)
void SZ_Clear (sizebuf_t *buf)
void * SZ_GetSpace (sizebuf_t *buf, int length)
void SZ_Write (sizebuf_t *buf, void *data, int length)
void SZ_Print (sizebuf_t *buf, char *data)
void MSG_WriteChar (sizebuf_t *sb, int c)
void MSG_WriteByte (sizebuf_t *sb, int c)
void MSG_WriteShort (sizebuf_t *sb, int c)
void MSG_WriteLong (sizebuf_t *sb, int c)
void MSG_WriteFloat (sizebuf_t *sb, float f)
void MSG_WriteString (sizebuf_t *sb, char *s)
void MSG_WriteCoord (sizebuf_t *sb, float f)
void MSG_WritePos (sizebuf_t *sb, vec3_t pos)
void MSG_WriteAngle (sizebuf_t *sb, float f)
void MSG_WriteAngle16 (sizebuf_t *sb, float f)
void MSG_WriteDeltaUsercmd (sizebuf_t *sb, struct usercmd_s *from, struct usercmd_s *cmd)
void MSG_WriteDeltaEntity (struct entity_state_s *from, struct entity_state_s *to, sizebuf_t *msg, qboolean force, qboolean newentity)
void MSG_WriteDir (sizebuf_t *sb, vec3_t vector)
void MSG_BeginReading (sizebuf_t *sb)
int MSG_ReadChar (sizebuf_t *sb)
int MSG_ReadByte (sizebuf_t *sb)
int MSG_ReadShort (sizebuf_t *sb)
int MSG_ReadLong (sizebuf_t *sb)
float MSG_ReadFloat (sizebuf_t *sb)
char * MSG_ReadString (sizebuf_t *sb)
char * MSG_ReadStringLine (sizebuf_t *sb)
float MSG_ReadCoord (sizebuf_t *sb)
void MSG_ReadPos (sizebuf_t *sb, vec3_t pos)
float MSG_ReadAngle (sizebuf_t *sb)
float MSG_ReadAngle16 (sizebuf_t *sb)
void MSG_ReadDeltaUsercmd (sizebuf_t *sb, struct usercmd_s *from, struct usercmd_s *cmd)
void MSG_ReadDir (sizebuf_t *sb, vec3_t vector)
void MSG_ReadData (sizebuf_t *sb, void *buffer, int size)
short BigShort (short l)
short LittleShort (short l)
int BigLong (int l)
int LittleLong (int l)
float BigFloat (float l)
float LittleFloat (float l)
int COM_Argc (void)
char * COM_Argv (int arg)
void COM_ClearArgv (int arg)
int COM_CheckParm (char *parm)
void COM_AddParm (char *parm)
void COM_Init (void)
void COM_InitArgv (int argc, char **argv)
char * CopyString (char *in)
void Info_Print (char *s)
void CRC_Init (unsigned short *crcvalue)
void CRC_ProcessByte (unsigned short *crcvalue, byte data)
unsigned short CRC_Value (unsigned short crcvalue)
unsigned short CRC_Block (byte *start, int count)
void Cbuf_Init (void)
void Cbuf_AddText (char *text)
void Cbuf_InsertText (char *text)
void Cbuf_ExecuteText (int exec_when, char *text)
void Cbuf_AddEarlyCommands (qboolean clear)
qboolean Cbuf_AddLateCommands (void)
void Cbuf_Execute (void)
void Cbuf_CopyToDefer (void)
void Cbuf_InsertFromDefer (void)
void Cmd_Init (void)
void Cmd_AddCommand (char *cmd_name, xcommand_t function)
void Cmd_RemoveCommand (char *cmd_name)
qboolean Cmd_Exists (char *cmd_name)
char * Cmd_CompleteCommand (char *partial)
int Cmd_Argc (void)
char * Cmd_Argv (int arg)
char * Cmd_Args (void)
void Cmd_TokenizeString (char *text, qboolean macroExpand)
void Cmd_ExecuteString (char *text)
void Cmd_ForwardToServer (void)
cvar_t * Cvar_Get (char *var_name, char *value, int flags)
cvar_t * Cvar_Set (char *var_name, char *value)
cvar_t * Cvar_ForceSet (char *var_name, char *value)
cvar_t * Cvar_FullSet (char *var_name, char *value, int flags)
void Cvar_SetValue (char *var_name, float value)
float Cvar_VariableValue (char *var_name)
char * Cvar_VariableString (char *var_name)
char * Cvar_CompleteVariable (char *partial)
void Cvar_GetLatchedVars (void)
qboolean Cvar_Command (void)
void Cvar_WriteVariables (char *path)
void Cvar_Init (void)
char * Cvar_Userinfo (void)
char * Cvar_Serverinfo (void)
void NET_Init (void)
void NET_Shutdown (void)
void NET_Config (qboolean multiplayer)
qboolean NET_GetPacket (netsrc_t sock, netadr_t *net_from, sizebuf_t *net_message)
void NET_SendPacket (netsrc_t sock, int length, void *data, netadr_t to)
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
qboolean NET_IsLocalAddress (netadr_t adr)
char * NET_AdrToString (netadr_t a)
qboolean NET_StringToAdr (char *s, netadr_t *a)
void NET_Sleep (int msec)
void Netchan_Init (void)
void Netchan_Setup (netsrc_t sock, netchan_t *chan, netadr_t adr, int qport)
qboolean Netchan_NeedReliable (netchan_t *chan)
void Netchan_Transmit (netchan_t *chan, int length, byte *data)
void Netchan_OutOfBand (int net_socket, netadr_t adr, int length, byte *data)
void Netchan_OutOfBandPrint (int net_socket, netadr_t adr, char *format,...)
qboolean Netchan_Process (netchan_t *chan, sizebuf_t *msg)
qboolean Netchan_CanReliable (netchan_t *chan)
cmodel_t * CM_LoadMap (char *name, qboolean clientload, unsigned *checksum)
cmodel_t * CM_InlineModel (char *name)
int CM_NumClusters (void)
int CM_NumInlineModels (void)
char * CM_EntityString (void)
int CM_HeadnodeForBox (vec3_t mins, vec3_t maxs)
int CM_PointContents (vec3_t p, int headnode)
int CM_TransformedPointContents (vec3_t p, int headnode, vec3_t origin, vec3_t angles)
trace_t CM_BoxTrace (vec3_t start, vec3_t end, vec3_t mins, vec3_t maxs, int headnode, int brushmask)
trace_t CM_TransformedBoxTrace (vec3_t start, vec3_t end, vec3_t mins, vec3_t maxs, int headnode, int brushmask, vec3_t origin, vec3_t angles)
byte * CM_ClusterPVS (int cluster)
byte * CM_ClusterPHS (int cluster)
int CM_PointLeafnum (vec3_t p)
int CM_BoxLeafnums (vec3_t mins, vec3_t maxs, int *list, int listsize, int *topnode)
int CM_LeafContents (int leafnum)
int CM_LeafCluster (int leafnum)
int CM_LeafArea (int leafnum)
void CM_SetAreaPortalState (int portalnum, qboolean open)
qboolean CM_AreasConnected (int area1, int area2)
int CM_WriteAreaBits (byte *buffer, int area)
qboolean CM_HeadnodeVisible (int headnode, byte *visbits)
void CM_WritePortalState (FILE *f)
void CM_ReadPortalState (FILE *f)
void Pmove (pmove_t *pmove)
void FS_InitFilesystem (void)
void FS_SetGamedir (char *dir)
char * FS_Gamedir (void)
char * FS_NextPath (char *prevpath)
void FS_ExecAutoexec (void)
int FS_FOpenFile (char *filename, FILE **file)
void FS_FCloseFile (FILE *f)
int FS_LoadFile (char *path, void **buffer)
void FS_Read (void *buffer, int len, FILE *f)
void FS_FreeFile (void *buffer)
void FS_CreatePath (char *path)
void Com_BeginRedirect (int target, char *buffer, int buffersize, void(*flush))
void Com_EndRedirect (void)
void Com_Printf (char *fmt,...)
void Com_DPrintf (char *fmt,...)
void Com_Error (int code, char *fmt,...)
void Com_Quit (void)
int Com_ServerState (void)
void Com_SetServerState (int state)
unsigned Com_BlockChecksum (void *buffer, int length)
byte COM_BlockSequenceCRCByte (byte *base, int length, int sequence)
float frand (void)
float crand (void)
void Z_Free (void *ptr)
void * Z_Malloc (int size)
void * Z_TagMalloc (int size, int tag)
void Z_FreeTags (int tag)
void Qcommon_Init (int argc, char **argv)
void Qcommon_Frame (int msec)
void Qcommon_Shutdown (void)
void SCR_DebugGraph (float value, int color)
void Sys_Init (void)
void Sys_AppActivate (void)
void Sys_UnloadGame (void)
void * Sys_GetGameAPI (void *parms)
char * Sys_ConsoleInput (void)
void Sys_ConsoleOutput (char *string)
void Sys_SendKeyEvents (void)
void Sys_Error (char *error,...)
void Sys_Quit (void)
char * Sys_GetClipboardData (void)
void Sys_CopyProtect (void)
void CL_Init (void)
void CL_Drop (void)
void CL_Shutdown (void)
void CL_Frame (int msec)
void Con_Print (char *text)
void SCR_BeginLoadingPlaque (void)
void SV_Init (void)
void SV_Shutdown (char *finalmsg, qboolean reconnect)
void SV_Frame (int msec)
Variables
qboolean bigendien
cvar_t * cvar_vars
qboolean userinfo_modified
netadr_t net_from
sizebuf_t net_message
byte net_message_buffer [MAX_MSGLEN]
float pm_airaccelerate
cvar_t * developer
cvar_t * dedicated
cvar_t * host_speeds
cvar_t * log_stats
FILE * log_stats_file
int time_before_game
int time_after_game
int time_before_ref
int time_after_ref
vec3_t bytedirs [NUMVERTEXNORMALS]
Macro Definition Documentation
BASEDIRNAME
#define BASEDIRNAME "baseq2"
Definition at line 28 of file qcommon.h.
BUILDSTRING
#define BUILDSTRING "NON-WIN32"
Definition at line 85 of file qcommon.h.
CM_ANGLE1
#define CM_ANGLE1 (1<<0)
Definition at line 289 of file qcommon.h.
CM_ANGLE2
#define CM_ANGLE2 (1<<1)
Definition at line 290 of file qcommon.h.
CM_ANGLE3
#define CM_ANGLE3 (1<<2)
Definition at line 291 of file qcommon.h.
CM_BUTTONS
#define CM_BUTTONS (1<<6)
Definition at line 295 of file qcommon.h.
CM_FORWARD
#define CM_FORWARD (1<<3)
Definition at line 292 of file qcommon.h.
CM_IMPULSE
#define CM_IMPULSE (1<<7)
Definition at line 296 of file qcommon.h.
CM_SIDE
#define CM_SIDE (1<<4)
Definition at line 293 of file qcommon.h.
CM_UP
#define CM_UP (1<<5)
Definition at line 294 of file qcommon.h.
CPUSTRING
#define CPUSTRING "NON-WIN32"
Definition at line 86 of file qcommon.h.
DEFAULT_SOUND_PACKET_ATTENUATION
#define DEFAULT_SOUND_PACKET_ATTENUATION 1.0
Definition at line 308 of file qcommon.h.
DEFAULT_SOUND_PACKET_VOLUME
#define DEFAULT_SOUND_PACKET_VOLUME 1.0
Definition at line 307 of file qcommon.h.
ERR_DROP
#define ERR_DROP 1
Definition at line 744 of file qcommon.h.
ERR_FATAL
#define ERR_FATAL 0
Definition at line 743 of file qcommon.h.
ERR_QUIT
#define ERR_QUIT 2
Definition at line 745 of file qcommon.h.
EXEC_APPEND [1/2]
#define EXEC_APPEND 2
Definition at line 749 of file qcommon.h.
EXEC_APPEND [2/2]
#define EXEC_APPEND 2
Definition at line 749 of file qcommon.h.
EXEC_INSERT [1/2]
#define EXEC_INSERT 1
Definition at line 748 of file qcommon.h.
EXEC_INSERT [2/2]
#define EXEC_INSERT 1
Definition at line 748 of file qcommon.h.
EXEC_NOW [1/2]
#define EXEC_NOW 0
Definition at line 747 of file qcommon.h.
EXEC_NOW [2/2]
#define EXEC_NOW 0
Definition at line 747 of file qcommon.h.
MAX_LATENT
#define MAX_LATENT 32
Definition at line 580 of file qcommon.h.
MAX_MSGLEN
#define MAX_MSGLEN 1400
Definition at line 544 of file qcommon.h.
NUMVERTEXNORMALS
#define NUMVERTEXNORMALS 162
Definition at line 792 of file qcommon.h.
OLD_AVG
#define OLD_AVG 0.99
Definition at line 578 of file qcommon.h.
PACKET_HEADER
#define PACKET_HEADER 10
Definition at line 545 of file qcommon.h.
PORT_ANY
#define PORT_ANY -1
Definition at line 542 of file qcommon.h.
PORT_CLIENT
#define PORT_CLIENT 27901
Definition at line 202 of file qcommon.h.
PORT_MASTER
#define PORT_MASTER 27900
Definition at line 201 of file qcommon.h.
PORT_SERVER
#define PORT_SERVER 27910
Definition at line 203 of file qcommon.h.
PRINT_ALL
#define PRINT_ALL 0
Definition at line 751 of file qcommon.h.
PRINT_DEVELOPER
#define PRINT_DEVELOPER 1
Definition at line 752 of file qcommon.h.
PROTOCOL_VERSION
#define PROTOCOL_VERSION 34
Definition at line 197 of file qcommon.h.
PS_BLEND
#define PS_BLEND (1<<10)
Definition at line 278 of file qcommon.h.
PS_FOV
#define PS_FOV (1<<11)
Definition at line 279 of file qcommon.h.
PS_KICKANGLES
#define PS_KICKANGLES (1<<9)
Definition at line 277 of file qcommon.h.
PS_M_DELTA_ANGLES
#define PS_M_DELTA_ANGLES (1<<6)
Definition at line 273 of file qcommon.h.
PS_M_FLAGS
#define PS_M_FLAGS (1<<4)
Definition at line 271 of file qcommon.h.
PS_M_GRAVITY
#define PS_M_GRAVITY (1<<5)
Definition at line 272 of file qcommon.h.
PS_M_ORIGIN
#define PS_M_ORIGIN (1<<1)
Definition at line 268 of file qcommon.h.
PS_M_TIME
#define PS_M_TIME (1<<3)
Definition at line 270 of file qcommon.h.
PS_M_TYPE
#define PS_M_TYPE (1<<0)
Definition at line 267 of file qcommon.h.
PS_M_VELOCITY
#define PS_M_VELOCITY (1<<2)
Definition at line 269 of file qcommon.h.
PS_RDFLAGS
#define PS_RDFLAGS (1<<14)
Definition at line 282 of file qcommon.h.
PS_VIEWANGLES
#define PS_VIEWANGLES (1<<8)
Definition at line 276 of file qcommon.h.
PS_VIEWOFFSET
#define PS_VIEWOFFSET (1<<7)
Definition at line 275 of file qcommon.h.
PS_WEAPONFRAME
#define PS_WEAPONFRAME (1<<13)
Definition at line 281 of file qcommon.h.
PS_WEAPONINDEX
#define PS_WEAPONINDEX (1<<12)
Definition at line 280 of file qcommon.h.
SND_ATTENUATION
#define SND_ATTENUATION (1<<1)
Definition at line 302 of file qcommon.h.
SND_ENT
#define SND_ENT (1<<3)
Definition at line 304 of file qcommon.h.
SND_OFFSET
#define SND_OFFSET (1<<4)
Definition at line 305 of file qcommon.h.
SND_POS
#define SND_POS (1<<2)
Definition at line 303 of file qcommon.h.
SND_VOLUME
#define SND_VOLUME (1<<0)
Definition at line 301 of file qcommon.h.
U_ANGLE1
#define U_ANGLE1 (1<<10)
Definition at line 327 of file qcommon.h.
U_ANGLE2
#define U_ANGLE2 (1<<2)
Definition at line 317 of file qcommon.h.
U_ANGLE3
#define U_ANGLE3 (1<<3)
Definition at line 318 of file qcommon.h.
U_EFFECTS16
#define U_EFFECTS16 (1<<19)
Definition at line 337 of file qcommon.h.
U_EFFECTS8
#define U_EFFECTS8 (1<<14)
Definition at line 330 of file qcommon.h.
U_EVENT
#define U_EVENT (1<<5)
Definition at line 320 of file qcommon.h.
U_FRAME16
#define U_FRAME16 (1<<17)
Definition at line 335 of file qcommon.h.
U_FRAME8
#define U_FRAME8 (1<<4)
Definition at line 319 of file qcommon.h.
U_MODEL
#define U_MODEL (1<<11)
Definition at line 328 of file qcommon.h.
U_MODEL2
#define U_MODEL2 (1<<20)
Definition at line 338 of file qcommon.h.
U_MODEL3
#define U_MODEL3 (1<<21)
Definition at line 339 of file qcommon.h.
U_MODEL4
#define U_MODEL4 (1<<22)
Definition at line 340 of file qcommon.h.
U_MOREBITS1
#define U_MOREBITS1 (1<<7)
Definition at line 322 of file qcommon.h.
U_MOREBITS2
#define U_MOREBITS2 (1<<15)
Definition at line 331 of file qcommon.h.
U_MOREBITS3
#define U_MOREBITS3 (1<<23)
Definition at line 341 of file qcommon.h.
U_NUMBER16
#define U_NUMBER16 (1<<8)
Definition at line 325 of file qcommon.h.
U_OLDORIGIN
#define U_OLDORIGIN (1<<24)
Definition at line 344 of file qcommon.h.
U_ORIGIN1
#define U_ORIGIN1 (1<<0)
Definition at line 315 of file qcommon.h.
U_ORIGIN2
#define U_ORIGIN2 (1<<1)
Definition at line 316 of file qcommon.h.
U_ORIGIN3
#define U_ORIGIN3 (1<<9)
Definition at line 326 of file qcommon.h.
U_REMOVE
#define U_REMOVE (1<<6)
Definition at line 321 of file qcommon.h.
U_RENDERFX16
#define U_RENDERFX16 (1<<18)
Definition at line 336 of file qcommon.h.
U_RENDERFX8
#define U_RENDERFX8 (1<<12)
Definition at line 329 of file qcommon.h.
U_SKIN16
#define U_SKIN16 (1<<25)
Definition at line 345 of file qcommon.h.
U_SKIN8
#define U_SKIN8 (1<<16)
Definition at line 334 of file qcommon.h.
U_SOLID
#define U_SOLID (1<<27)
Definition at line 347 of file qcommon.h.
U_SOUND
#define U_SOUND (1<<26)
Definition at line 346 of file qcommon.h.
UPDATE_BACKUP
#define UPDATE_BACKUP 16
Definition at line 207 of file qcommon.h.
UPDATE_MASK
#define UPDATE_MASK (UPDATE_BACKUP-1)
Definition at line 209 of file qcommon.h.
VERSION
#define VERSION 3.21
Definition at line 26 of file qcommon.h.
Typedef Documentation
sizebuf_t
typedef struct sizebuf_s sizebuf_t
xcommand_t
typedef void(* xcommand_t) (void)
Definition at line 419 of file qcommon.h.
Enumeration Type Documentation
clc_ops_e
enum clc_ops_e
Enumerator
clc_bad
clc_nop
clc_move
clc_userinfo
clc_stringcmd
Definition at line 254 of file qcommon.h.
 {
     clc_bad,
     clc_nop,
     clc_move,               // [[usercmd_t]
     clc_userinfo,           // [[userinfo string]
     clc_stringcmd           // [string] message
 };
netadrtype_t
enum netadrtype_t
Enumerator
NA_LOOPBACK
NA_BROADCAST
NA_IP
NA_IPX
NA_BROADCAST_IPX
Definition at line 547 of file qcommon.h.
 {NA_LOOPBACK, NA_BROADCAST, NA_IP, NA_IPX, NA_BROADCAST_IPX} netadrtype_t;
netsrc_t
enum netsrc_t
Enumerator
NS_CLIENT
NS_SERVER
Definition at line 549 of file qcommon.h.
 {NS_CLIENT, NS_SERVER} netsrc_t;
svc_ops_e
enum svc_ops_e
Enumerator
svc_bad
svc_muzzleflash
svc_muzzleflash2
svc_temp_entity
svc_layout
svc_inventory
svc_nop
svc_disconnect
svc_reconnect
svc_sound
svc_print
svc_stufftext
svc_serverdata
svc_configstring
svc_spawnbaseline
svc_centerprint
svc_download
svc_playerinfo
svc_packetentities
svc_deltapacketentities
svc_frame
Definition at line 220 of file qcommon.h.
 {
     svc_bad,
     // these ops are known to the game dll
     svc_muzzleflash,
     svc_muzzleflash2,
     svc_temp_entity,
     svc_layout,
     svc_inventory,
     // the rest are private to the client and server
     svc_nop,
     svc_disconnect,
     svc_reconnect,
     svc_sound,                  // <see code>
     svc_print,                  // [byte] id [string] null terminated string
     svc_stufftext,              // [string] stuffed into client's console buffer, should be \n terminated
     svc_serverdata,             // [long] protocol ...
     svc_configstring,           // [short] [string]
     svc_spawnbaseline,
     svc_centerprint,            // [string] to put in center of the screen
     svc_download,               // [short] size [size bytes]
     svc_playerinfo,             // variable
     svc_packetentities,         // [...]
     svc_deltapacketentities,    // [...]
     svc_frame
 };
Function Documentation
BigFloat()
float BigFloat (float l)
Definition at line 949 of file q_shared.c.
 {return _BigFloat(l);}
BigLong()
int BigLong (int l)
Definition at line 947 of file q_shared.c.
 {return _BigLong(l);}
BigShort()
short BigShort (short l)
Definition at line 945 of file q_shared.c.
 {return _BigShort(l);}
Referenced by CL_CheckForResend(), CL_Packet_f(), CL_PingServers_f(), CL_Rcon_f(), CL_SendConnectPacket(), and SV_SetMaster_f().
Cbuf_AddEarlyCommands()
void Cbuf_AddEarlyCommands (qboolean clear)
Definition at line 263 of file cmd.c.
 {
     int     i;
     char    *s;
     for (i=0 ; i<COM_Argc() ; i++)
     {
         s = COM_Argv(i);
         if (strcmp (s, "+set"))
             continue;
         Cbuf_AddText (va("set %s %s\n", COM_Argv(i+1), COM_Argv(i+2)));
         if (clear)
         {
             COM_ClearArgv(i);
             COM_ClearArgv(i+1);
             COM_ClearArgv(i+2);
         }
         i+=2;
     }
 }
Referenced by Qcommon_Init().
Cbuf_AddLateCommands()
qboolean Cbuf_AddLateCommands (void)
Definition at line 296 of file cmd.c.
 {
     int     i, j;
     int     s;
     char    *text, *build, c;
     int     argc;
     qboolean    ret;
 // build the combined string to parse from
     s = 0;
     argc = COM_Argc();
     for (i=1 ; i<argc ; i++)
     {
         s += (int)strlen (COM_Argv(i)) + 1;
     }
     if (!s)
         return false;
     text = Z_Malloc (s+1);
     text[0] = 0;
     for (i=1 ; i<argc ; i++)
     {
         strcat (text,COM_Argv(i));
         if (i != argc-1)
             strcat (text, " ");
     }
 // pull out the commands
     build = Z_Malloc (s+1);
     build[0] = 0;
     for (i=0 ; i<s-1 ; i++)
     {
         if (text[i] == '+')
         {
             i++;
             for (j=i ; (text[j] != '+') && (text[j] != '-') && (text[j] != 0) ; j++)
                 ;
             c = text[j];
             text[j] = 0;
             strcat (build, text+i);
             strcat (build, "\n");
             text[j] = c;
             i = j-1;
         }
     }
     ret = (build[0] != 0);
     if (ret)
         Cbuf_AddText (build);
     Z_Free (text);
     Z_Free (build);
     return ret;
 }
Referenced by Qcommon_Init().
Cbuf_AddText()
void Cbuf_AddText (char * text)
Definition at line 90 of file cmd.c.
 {
     int     l;
     l = (int)strlen (text);
     if (cmd_text.cursize + l >= cmd_text.maxsize)
     {
         Com_Printf ("Cbuf_AddText: overflow\n");
         return;
     }
     SZ_Write (&cmd_text, text, (int)strlen (text));
 }
Referenced by Cbuf_AddEarlyCommands(), Cbuf_AddLateCommands(), Cbuf_ExecuteText(), Cbuf_InsertText(), CL_ConnectionlessPacket(), CL_ParseServerMessage(), Con_ToggleConsole_f(), ConsoleFunc(), ControlsResetDefaultsFunc(), FS_ExecAutoexec(), FS_SetGamedir(), JoinServerFunc(), Key_Console(), Key_Event(), Key_Message(), LoadGameCallback(), Qcommon_Frame(), Qcommon_Init(), SaveGameCallback(), StartGame(), StartServerActionFunc(), SV_InitGameProgs(), and SV_Nextserver().
Cbuf_CopyToDefer()
void Cbuf_CopyToDefer (void)
Definition at line 147 of file cmd.c.
 {
     memcpy(defer_text_buf, cmd_text_buf, cmd_text.cursize);
     defer_text_buf[cmd_text.cursize] = 0;
     cmd_text.cursize = 0;
 }
Referenced by SV_Map().
Cbuf_Execute()
void Cbuf_Execute (void)
Definition at line 194 of file cmd.c.
 {
     int     i;
     char    *text;
     char    line[1024];
     int     quotes;
     alias_count = 0;        // don't allow infinite alias loops
     while (cmd_text.cursize)
     {
 // find a \n or ; line break
         text = (char *)cmd_text.data;
         quotes = 0;
         for (i=0 ; i< cmd_text.cursize ; i++)
         {
             if (text[i] == '"')
                 quotes++;
             if ( !(quotes&1) &&  text[i] == ';')
                 break;  // don't break if inside a quoted string
             if (text[i] == '\n')
                 break;
         }
         memcpy (line, text, i);
         line[i] = 0;
 // delete the text from the command buffer and move remaining commands down
 // this is necessary because commands (exec, alias) can insert data at the
 // beginning of the text buffer
         if (i == cmd_text.cursize)
             cmd_text.cursize = 0;
         else
         {
             i++;
             cmd_text.cursize -= i;
             memmove (text, text+i, cmd_text.cursize);
         }
 // execute the command line
         Cmd_ExecuteString (line);
         if (cmd_wait)
         {
             // skip out while text still remains in buffer, leaving it
             // for next frame
             cmd_wait = false;
             break;
         }
     }
 }
Referenced by CL_Init(), CL_ParseServerMessage(), CL_SendCommand(), ControlsResetDefaultsFunc(), Qcommon_Frame(), and Qcommon_Init().
Cbuf_ExecuteText()
void Cbuf_ExecuteText (int exec_when, char * text)
Definition at line 171 of file cmd.c.
 {
     switch (exec_when)
     {
     case EXEC_NOW:
         Cmd_ExecuteString (text);
         break;
     case EXEC_INSERT:
         Cbuf_InsertText (text);
         break;
     case EXEC_APPEND:
         Cbuf_AddText (text);
         break;
     default:
         Com_Error (ERR_FATAL, "Cbuf_ExecuteText: bad exec_when");
     }
 }
Referenced by VID_LoadRefresh().
Cbuf_Init()
void Cbuf_Init (void)
Definition at line 78 of file cmd.c.
 {
     SZ_Init (&cmd_text, cmd_text_buf, sizeof(cmd_text_buf));
 }
Referenced by Qcommon_Init().
Cbuf_InsertFromDefer()
void Cbuf_InsertFromDefer (void)
Definition at line 159 of file cmd.c.
 {
     Cbuf_InsertText (defer_text_buf);
     defer_text_buf[0] = 0;
 }
Referenced by SV_Begin_f().
Cbuf_InsertText()
void Cbuf_InsertText (char * text)
Definition at line 114 of file cmd.c.
 {
     char    *temp;
     int     templen;
 // copy off any commands still remaining in the exec buffer
     templen = cmd_text.cursize;
     if (templen)
     {
         temp = Z_Malloc (templen);
         memcpy (temp, cmd_text.data, templen);
         SZ_Clear (&cmd_text);
     }
     else
         temp = NULL;    // shut up compiler
 // add the entire text of the file
     Cbuf_AddText (text);
 // add the copied off data
     if (templen)
     {
         SZ_Write (&cmd_text, temp, templen);
         Z_Free (temp);
     }
 }
Referenced by Cbuf_ExecuteText(), Cbuf_InsertFromDefer(), Cmd_Exec_f(), Cmd_ExecuteString(), and Keys_MenuKey().
CL_Drop()
void CL_Drop (void)
Definition at line 399 of file cl_main.c.
 {
     if (cls.state == ca_uninitialized)
         return;
     if (cls.state == ca_disconnected)
         return;
     CL_Disconnect ();
     // drop loading plaque unless this is the initial game start
     if (cls.disable_servercount != -1)
         SCR_EndLoadingPlaque ();    // get rid of loading plaque
 }
Referenced by Com_Error(), and SV_InitGame().
CL_Frame()
void CL_Frame (int msec)
Definition at line 1681 of file cl_main.c.
 {
     static int  extratime;
     static int  lasttimecalled;
     if (dedicated->value)
         return;
     extratime += msec;
     if (!cl_timedemo->value)
     {
         if (cls.state == ca_connected && extratime < 100)
             return;         // don't flood packets out while connecting
         if (extratime < 1000/cl_maxfps->value)
             return;         // framerate is too high
     }
     // let the mouse activate or deactivate
     IN_Frame ();
     // decide the simulation time
     cls.frametime = extratime/1000.0;
     cl.time += extratime;
     cls.realtime = curtime;
     extratime = 0;
 #if 0
     if (cls.frametime > (1.0 / cl_minfps->value))
         cls.frametime = (1.0 / cl_minfps->value);
 #else
     if (cls.frametime > (1.0 / 5))
         cls.frametime = (1.0 / 5);
 #endif
     // if in the debugger last frame, don't timeout
     if (msec > 5000)
         cls.netchan.last_received = Sys_Milliseconds ();
     // fetch results from server
     CL_ReadPackets ();
     // send a new command message to the server
     CL_SendCommand ();
     // predict all unacknowledged movements
     CL_PredictMovement ();
     // allow rendering DLL change
     VID_CheckChanges ();
     if (!cl.refresh_prepped && cls.state == ca_active)
         CL_PrepRefresh ();
     // update the screen
     if (host_speeds->value)
         time_before_ref = Sys_Milliseconds ();
     SCR_UpdateScreen ();
     if (host_speeds->value)
         time_after_ref = Sys_Milliseconds ();
     // update audio
     S_Update (cl.refdef.vieworg, cl.v_forward, cl.v_right, cl.v_up);
     CDAudio_Update();
     Miniaudio_Update();
     // advance local effects for next frame
     CL_RunDLights ();
     CL_RunLightStyles ();
     SCR_RunCinematic ();
     SCR_RunConsole ();
     cls.framecount++;
     if ( log_stats->value )
     {
         if ( cls.state == ca_active )
         {
             if ( !lasttimecalled )
             {
                 lasttimecalled = Sys_Milliseconds();
                 if ( log_stats_file )
                     fprintf( log_stats_file, "0\n" );
             }
             else
             {
                 int now = Sys_Milliseconds();
                 if ( log_stats_file )
                     fprintf( log_stats_file, "%d\n", now - lasttimecalled );
                 lasttimecalled = now;
             }
         }
     }
 }
Referenced by Qcommon_Frame().
CL_Init()
void CL_Init (void)
Definition at line 1785 of file cl_main.c.
 {
     if (dedicated->value)
         return;     // nothing running on the client
     // all archived variables will now be loaded
     Con_Init ();
 #if defined __linux__ || defined __sgi
     S_Init ();
     VID_Init ();
 #else
     VID_Init ();
     S_Init ();  // sound must be initialized after window is created
 #endif
     V_Init ();
     net_message.data = net_message_buffer;
     net_message.maxsize = sizeof(net_message_buffer);
     M_Init ();
     SCR_Init ();
     cls.disable_screen = true;  // don't draw yet
     CDAudio_Init ();
     Miniaudio_Init ();
     CL_InitLocal ();
     IN_Init ();
 //  Cbuf_AddText ("exec autoexec.cfg\n");
     FS_ExecAutoexec ();
     Cbuf_Execute ();
 }
Referenced by Qcommon_Init().
CL_Shutdown()
void CL_Shutdown (void)
Definition at line 1831 of file cl_main.c.
 {
     static qboolean isdown = false;
     if (isdown)
     {
         printf ("recursive shutdown\n");
         return;
     }
     isdown = true;
     CL_WriteConfiguration ();
     CDAudio_Shutdown ();
     Miniaudio_Shutdown();
     S_Shutdown();
     IN_Shutdown ();
     VID_Shutdown();
 }
Referenced by Com_Error(), Com_Quit(), Sys_Error(), and Sys_Quit().
CM_AreasConnected()
qboolean CM_AreasConnected (int area1, int area2)
Definition at line 1662 of file cmodel.c.
 {
     if (map_noareas->value)
         return true;
     if (area1 > numareas || area2 > numareas)
         Com_Error (ERR_DROP, "area > numareas");
     if (map_areas[area1].floodnum == map_areas[area2].floodnum)
         return true;
     return false;
 }
Referenced by PF_inPHS(), PF_inPVS(), SV_BuildClientFrame(), SV_InitGameProgs(), and SV_Multicast().
CM_BoxLeafnums()
int CM_BoxLeafnums (vec3_t mins, vec3_t maxs, int * list, int listsize, int * topnode)
Definition at line 903 of file cmodel.c.
 {
     return CM_BoxLeafnums_headnode (mins, maxs, list,
         listsize, map_cmodels[0].headnode, topnode);
 }
Referenced by SV_FatPVS(), and SV_LinkEdict().
CM_BoxTrace()
trace_t CM_BoxTrace (vec3_t start, vec3_t end, vec3_t mins, vec3_t maxs, int headnode, int brushmask)
Definition at line 1350 of file cmodel.c.
 {
     int     i;
     checkcount++;       // for multi-check avoidance
     c_traces++;         // for statistics, may be zeroed
     // fill in a default trace
     memset (&trace_trace, 0, sizeof(trace_trace));
     trace_trace.fraction = 1;
     trace_trace.surface = &(nullsurface.c);
     if (!numnodes)  // map not loaded
         return trace_trace;
     trace_contents = brushmask;
     VectorCopy (start, trace_start);
     VectorCopy (end, trace_end);
     VectorCopy (mins, trace_mins);
     VectorCopy (maxs, trace_maxs);
     //
     // check for position test special case
     //
     if (start[0] == end[0] && start[1] == end[1] && start[2] == end[2])
     {
         int     leafs[1024];
         int     i, numleafs;
         vec3_t  c1, c2;
         int     topnode;
         VectorAdd (start, mins, c1);
         VectorAdd (start, maxs, c2);
         for (i=0 ; i<3 ; i++)
         {
             c1[i] -= 1;
             c2[i] += 1;
         }
         numleafs = CM_BoxLeafnums_headnode (c1, c2, leafs, 1024, headnode, &topnode);
         for (i=0 ; i<numleafs ; i++)
         {
             CM_TestInLeaf (leafs[i]);
             if (trace_trace.allsolid)
                 break;
         }
         VectorCopy (start, trace_trace.endpos);
         return trace_trace;
     }
     //
     // check for point special case
     //
     if (mins[0] == 0 && mins[1] == 0 && mins[2] == 0
         && maxs[0] == 0 && maxs[1] == 0 && maxs[2] == 0)
     {
         trace_ispoint = true;
         VectorClear (trace_extents);
     }
     else
     {
         trace_ispoint = false;
         trace_extents[0] = -mins[0] > maxs[0] ? -mins[0] : maxs[0];
         trace_extents[1] = -mins[1] > maxs[1] ? -mins[1] : maxs[1];
         trace_extents[2] = -mins[2] > maxs[2] ? -mins[2] : maxs[2];
     }
     //
     // general sweeping through world
     //
     CM_RecursiveHullCheck (headnode, 0, 1, start, end);
     if (trace_trace.fraction == 1)
     {
         VectorCopy (end, trace_trace.endpos);
     }
     else
     {
         for (i=0 ; i<3 ; i++)
             trace_trace.endpos[i] = start[i] + trace_trace.fraction * (end[i] - start[i]);
     }
     return trace_trace;
 }
Referenced by CL_PMTrace(), CM_TransformedBoxTrace(), and SV_Trace().
CM_ClusterPHS()
byte* CM_ClusterPHS (int cluster)
Definition at line 1584 of file cmodel.c.
 {
     if (cluster == -1)
         memset (phsrow, 0, (numclusters+7)>>3);
     else
         CM_DecompressVis (map_visibility + map_vis->bitofs[cluster][DVIS_PHS], phsrow);
     return phsrow;
 }
Referenced by PF_inPHS(), SV_BuildClientFrame(), and SV_Multicast().
CM_ClusterPVS()
byte* CM_ClusterPVS (int cluster)
Definition at line 1575 of file cmodel.c.
 {
     if (cluster == -1)
         memset (pvsrow, 0, (numclusters+7)>>3);
     else
         CM_DecompressVis (map_visibility + map_vis->bitofs[cluster][DVIS_PVS], pvsrow);
     return pvsrow;
 }
Referenced by PF_inPVS(), SV_FatPVS(), and SV_Multicast().
CM_EntityString()
char* CM_EntityString (void)
Definition at line 662 of file cmodel.c.
 {
     return map_entitystring;
 }
Referenced by SV_SpawnServer().
CM_HeadnodeForBox()
int CM_HeadnodeForBox (vec3_t mins, vec3_t maxs)
Definition at line 775 of file cmodel.c.
 {
     box_planes[0].dist = maxs[0];
     box_planes[1].dist = -maxs[0];
     box_planes[2].dist = mins[0];
     box_planes[3].dist = -mins[0];
     box_planes[4].dist = maxs[1];
     box_planes[5].dist = -maxs[1];
     box_planes[6].dist = mins[1];
     box_planes[7].dist = -mins[1];
     box_planes[8].dist = maxs[2];
     box_planes[9].dist = -maxs[2];
     box_planes[10].dist = mins[2];
     box_planes[11].dist = -mins[2];
     return box_headnode;
 }
Referenced by CL_ClipMoveToEntities(), and SV_HullForEntity().
CM_HeadnodeVisible()
qboolean CM_HeadnodeVisible (int headnode, byte * visbits)
Definition at line 1748 of file cmodel.c.
 {
     int     leafnum;
     int     cluster;
     cnode_t *node;
     if (nodenum < 0)
     {
         leafnum = -1-nodenum;
         cluster = map_leafs[leafnum].cluster;
         if (cluster == -1)
             return false;
         if (visbits[cluster>>3] & (1<<(cluster&7)))
             return true;
         return false;
     }
     node = &map_nodes[nodenum];
     if (CM_HeadnodeVisible(node->children[0], visbits))
         return true;
     return CM_HeadnodeVisible(node->children[1], visbits);
 }
Referenced by CM_HeadnodeVisible(), and SV_BuildClientFrame().
CM_InlineModel()
cmodel_t* CM_InlineModel (char * name)
Definition at line 639 of file cmodel.c.
 {
     int     num;
     if (!name || name[0] != '*')
         Com_Error (ERR_DROP, "CM_InlineModel: bad name");
     num = atoi (name+1);
     if (num < 1 || num >= numcmodels)
         Com_Error (ERR_DROP, "CM_InlineModel: bad number");
     return &map_cmodels[num];
 }
Referenced by CL_ParseConfigString(), CL_PrepRefresh(), PF_setmodel(), and SV_SpawnServer().
CM_LeafArea()
int CM_LeafArea (int leafnum)
Definition at line 681 of file cmodel.c.
 {
     if (leafnum < 0 || leafnum >= numleafs)
         Com_Error (ERR_DROP, "CM_LeafArea: bad number");
     return map_leafs[leafnum].area;
 }
Referenced by PF_inPHS(), PF_inPVS(), SV_BuildClientFrame(), SV_LinkEdict(), and SV_Multicast().
CM_LeafCluster()
int CM_LeafCluster (int leafnum)
Definition at line 674 of file cmodel.c.
 {
     if (leafnum < 0 || leafnum >= numleafs)
         Com_Error (ERR_DROP, "CM_LeafCluster: bad number");
     return map_leafs[leafnum].cluster;
 }
Referenced by PF_inPHS(), PF_inPVS(), SV_BuildClientFrame(), SV_FatPVS(), SV_LinkEdict(), and SV_Multicast().
CM_LeafContents()
int CM_LeafContents (int leafnum)
Definition at line 667 of file cmodel.c.
 {
     if (leafnum < 0 || leafnum >= numleafs)
         Com_Error (ERR_DROP, "CM_LeafContents: bad number");
     return map_leafs[leafnum].contents;
 }
CM_LoadMap()
cmodel_t* CM_LoadMap (char * name, qboolean clientload, unsigned * checksum)
Definition at line 548 of file cmodel.c.
 {
     unsigned        *buf;
     int             i;
     dheader_t       header;
     int             length;
     static unsigned last_checksum;
     map_noareas = Cvar_Get ("map_noareas", "0", 0);
     if (  !strcmp (map_name, name) && (clientload || !Cvar_VariableValue ("flushmap")) )
     {
         *checksum = last_checksum;
         if (!clientload)
         {
             memset (portalopen, 0, sizeof(portalopen));
             FloodAreaConnections ();
         }
         return &map_cmodels[0];     // still have the right version
     }
     // free old stuff
     numplanes = 0;
     numnodes = 0;
     numleafs = 0;
     numcmodels = 0;
     numvisibility = 0;
     numentitychars = 0;
     map_entitystring[0] = 0;
     map_name[0] = 0;
     if (!name || !name[0])
     {
         numleafs = 1;
         numclusters = 1;
         numareas = 1;
         *checksum = 0;
         return &map_cmodels[0];         // cinematic servers won't have anything at all
     }
     //
     // load the file
     //
     length = FS_LoadFile (name, (void **)&buf);
     if (!buf)
         Com_Error (ERR_DROP, "Couldn't load %s", name);
     last_checksum = LittleLong (Com_BlockChecksum (buf, length));
     *checksum = last_checksum;
     header = *(dheader_t *)buf;
     for (i=0 ; i<sizeof(dheader_t)/4 ; i++)
         ((int *)&header)[i] = LittleLong ( ((int *)&header)[i]);
     if (header.version != BSPVERSION)
         Com_Error (ERR_DROP, "CMod_LoadBrushModel: %s has wrong version number (%i should be %i)"
         , name, header.version, BSPVERSION);
     cmod_base = (byte *)buf;
     // load into heap
     CMod_LoadSurfaces (&header.lumps[LUMP_TEXINFO]);
     CMod_LoadLeafs (&header.lumps[LUMP_LEAFS]);
     CMod_LoadLeafBrushes (&header.lumps[LUMP_LEAFBRUSHES]);
     CMod_LoadPlanes (&header.lumps[LUMP_PLANES]);
     CMod_LoadBrushes (&header.lumps[LUMP_BRUSHES]);
     CMod_LoadBrushSides (&header.lumps[LUMP_BRUSHSIDES]);
     CMod_LoadSubmodels (&header.lumps[LUMP_MODELS]);
     CMod_LoadNodes (&header.lumps[LUMP_NODES]);
     CMod_LoadAreas (&header.lumps[LUMP_AREAS]);
     CMod_LoadAreaPortals (&header.lumps[LUMP_AREAPORTALS]);
     CMod_LoadVisibility (&header.lumps[LUMP_VISIBILITY]);
     CMod_LoadEntityString (&header.lumps[LUMP_ENTITIES]);
     FS_FreeFile (buf);
     CM_InitBoxHull ();
     memset (portalopen, 0, sizeof(portalopen));
     FloodAreaConnections ();
     strcpy (map_name, name);
     return &map_cmodels[0];
 }
Referenced by CL_Precache_f(), CL_RequestNextDownload(), and SV_SpawnServer().
CM_NumClusters()
int CM_NumClusters (void)
Definition at line 652 of file cmodel.c.
 {
     return numclusters;
 }
Referenced by SV_FatPVS().
CM_NumInlineModels()
int CM_NumInlineModels (void)
Definition at line 657 of file cmodel.c.
 {
     return numcmodels;
 }
Referenced by SV_SpawnServer().
CM_PointContents()
int CM_PointContents (vec3_t p, int headnode)
Definition at line 917 of file cmodel.c.
 {
     int     l;
     if (!numnodes)  // map not loaded
         return 0;
     l = CM_PointLeafnum_r (p, headnode);
     return map_leafs[l].contents;
 }
Referenced by CL_PMpointcontents(), and SV_PointContents().
CM_PointLeafnum()
int CM_PointLeafnum (vec3_t p)
Definition at line 826 of file cmodel.c.
 {
     if (!numplanes)
         return 0;       // sound may call this without map loaded
     return CM_PointLeafnum_r (p, 0);
 }
Referenced by PF_inPHS(), PF_inPVS(), SV_BuildClientFrame(), and SV_Multicast().
CM_ReadPortalState()
void CM_ReadPortalState (FILE * f)
Definition at line 1734 of file cmodel.c.
 {
     FS_Read (portalopen, sizeof(portalopen), f);
     FloodAreaConnections ();
 }
Referenced by SV_ReadLevelFile().
CM_SetAreaPortalState()
void CM_SetAreaPortalState (int portalnum, qboolean open)
Definition at line 1653 of file cmodel.c.
 {
     if (portalnum > numareaportals)
         Com_Error (ERR_DROP, "areaportal > numareaportals");
     portalopen[portalnum] = open;
     FloodAreaConnections ();
 }
Referenced by SV_InitGameProgs().
CM_TransformedBoxTrace()
trace_t CM_TransformedBoxTrace (vec3_t start, vec3_t end, vec3_t mins, vec3_t maxs, int headnode, int brushmask, vec3_t origin, vec3_t angles)
Definition at line 1451 of file cmodel.c.
 {
     trace_t     trace;
     vec3_t      start_l, end_l;
     vec3_t      a;
     vec3_t      forward, right, up;
     vec3_t      temp;
     qboolean    rotated;
     // subtract origin offset
     VectorSubtract (start, origin, start_l);
     VectorSubtract (end, origin, end_l);
     // rotate start and end into the models frame of reference
     if (headnode != box_headnode &&
     (angles[0] || angles[1] || angles[2]) )
         rotated = true;
     else
         rotated = false;
     if (rotated)
     {
         AngleVectors (angles, forward, right, up);
         VectorCopy (start_l, temp);
         start_l[0] = DotProduct (temp, forward);
         start_l[1] = -DotProduct (temp, right);
         start_l[2] = DotProduct (temp, up);
         VectorCopy (end_l, temp);
         end_l[0] = DotProduct (temp, forward);
         end_l[1] = -DotProduct (temp, right);
         end_l[2] = DotProduct (temp, up);
     }
     // sweep the box through the model
     trace = CM_BoxTrace (start_l, end_l, mins, maxs, headnode, brushmask);
     if (rotated && trace.fraction != 1.0)
     {
         // FIXME: figure out how to do this with existing angles
         VectorNegate (angles, a);
         AngleVectors (a, forward, right, up);
         VectorCopy (trace.plane.normal, temp);
         trace.plane.normal[0] = DotProduct (temp, forward);
         trace.plane.normal[1] = -DotProduct (temp, right);
         trace.plane.normal[2] = DotProduct (temp, up);
     }
     trace.endpos[0] = start[0] + trace.fraction * (end[0] - start[0]);
     trace.endpos[1] = start[1] + trace.fraction * (end[1] - start[1]);
     trace.endpos[2] = start[2] + trace.fraction * (end[2] - start[2]);
     return trace;
 }
Referenced by CL_ClipMoveToEntities(), and SV_ClipMoveToEntities().
CM_TransformedPointContents()
int CM_TransformedPointContents (vec3_t p, int headnode, vec3_t origin, vec3_t angles)
Definition at line 937 of file cmodel.c.
 {
     vec3_t      p_l;
     vec3_t      temp;
     vec3_t      forward, right, up;
     int         l;
     // subtract origin offset
     VectorSubtract (p, origin, p_l);
     // rotate start and end into the models frame of reference
     if (headnode != box_headnode &&
     (angles[0] || angles[1] || angles[2]) )
     {
         AngleVectors (angles, forward, right, up);
         VectorCopy (p_l, temp);
         p_l[0] = DotProduct (temp, forward);
         p_l[1] = -DotProduct (temp, right);
         p_l[2] = DotProduct (temp, up);
     }
     l = CM_PointLeafnum_r (p_l, headnode);
     return map_leafs[l].contents;
 }
Referenced by CL_PMpointcontents(), and SV_PointContents().
CM_WriteAreaBits()
int CM_WriteAreaBits (byte * buffer, int area)
Definition at line 1686 of file cmodel.c.
 {
     int     i;
     int     floodnum;
     int     bytes;
     bytes = (numareas+7)>>3;
     if (map_noareas->value)
     {   // for debugging, send everything
         memset (buffer, 255, bytes);
     }
     else
     {
         memset (buffer, 0, bytes);
         floodnum = map_areas[area].floodnum;
         for (i=0 ; i<numareas ; i++)
         {
             if (map_areas[i].floodnum == floodnum || !area)
                 buffer[i>>3] |= 1<<(i&7);
         }
     }
     return bytes;
 }
Referenced by SV_BuildClientFrame().
CM_WritePortalState()
void CM_WritePortalState (FILE * f)
Definition at line 1721 of file cmodel.c.
 {
     fwrite (portalopen, sizeof(portalopen), 1, f);
 }
Referenced by SV_WriteLevelFile().
Cmd_AddCommand()
void Cmd_AddCommand (char * cmd_name, xcommand_t function)
Definition at line 691 of file cmd.c.
 {
     cmd_function_t  *cmd;
 // fail if the command is a variable name
     if (Cvar_VariableString(cmd_name)[0])
     {
         Com_Printf ("Cmd_AddCommand: %s already defined as a var\n", cmd_name);
         return;
     }
 // fail if the command already exists
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next)
     {
         if (!strcmp (cmd_name, cmd->name))
         {
             Com_Printf ("Cmd_AddCommand: %s already defined\n", cmd_name);
             return;
         }
     }
     cmd = Z_Malloc (sizeof(cmd_function_t));
     cmd->name = cmd_name;
     cmd->function = function;
     cmd->next = cmd_functions;
     cmd_functions = cmd;
 }
Referenced by CDAudio_Init(), CL_InitInput(), CL_InitLocal(), Cmd_Init(), Con_Init(), Cvar_Init(), FS_InitFilesystem(), IN_Init(), Key_Init(), M_Init(), Miniaudio_Init(), Qcommon_Init(), S_Init(), SCR_Init(), SV_InitOperatorCommands(), V_Init(), VID_Init(), and VID_LoadRefresh().
Cmd_Argc()
int Cmd_Argc (void)
Definition at line 507 of file cmd.c.
 {
     return cmd_argc;
 }
Referenced by CD_f(), CL_Connect_f(), CL_Download_f(), CL_ForwardToServer_f(), CL_Packet_f(), CL_Precache_f(), CL_Rcon_f(), CL_Record_f(), CL_Setenv_f(), Cmd_Alias_f(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_ForwardToServer(), Con_Dump_f(), Cvar_Command(), Cvar_Set_f(), FS_Dir_f(), FS_Link_f(), Key_Bind_f(), Key_Unbind_f(), Miniaudio_f(), S_Play(), SCR_Sky_f(), SCR_TimeRefresh_f(), SV_BeginDownload_f(), SV_ConSay_f(), SV_DumpUser_f(), SV_GameMap_f(), SV_InitGameProgs(), SV_Kick_f(), SV_Loadgame_f(), SV_Savegame_f(), SV_ServerRecord_f(), SV_SetMaster_f(), SV_SetPlayer(), SVC_RemoteCommand(), V_Gun_Model_f(), and VID_LoadRefresh().
Cmd_Args()
char* Cmd_Args (void)
Definition at line 531 of file cmd.c.
 {
     return cmd_args;
 }
Referenced by CL_ForwardToServer_f(), Cmd_ForwardToServer(), SV_ConSay_f(), and SV_InitGameProgs().
Cmd_Argv()
char* Cmd_Argv (int arg)
Definition at line 517 of file cmd.c.
 {
     if ( (unsigned)arg >= cmd_argc )
         return cmd_null_string;
     return cmd_argv[arg];
 }
Referenced by CD_f(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_Download_f(), CL_ForwardToServer_f(), CL_Packet_f(), CL_Precache_f(), CL_Rcon_f(), CL_Record_f(), CL_Setenv_f(), Cmd_Alias_f(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_ForwardToServer(), Com_Error_f(), Con_Dump_f(), Cvar_Command(), Cvar_Set_f(), FS_Dir_f(), FS_Link_f(), IN_Impulse(), Key_Bind_f(), Key_Unbind_f(), KeyDown(), KeyUp(), Miniaudio_f(), Rcon_Validate(), S_Play(), SCR_Sky_f(), SV_Baselines_f(), SV_Begin_f(), SV_BeginDownload_f(), SV_Configstrings_f(), SV_ConnectionlessPacket(), SV_DemoMap_f(), SV_ExecuteUserCommand(), SV_GameMap_f(), SV_InitGameProgs(), SV_Loadgame_f(), SV_Map_f(), SV_Nextserver_f(), SV_Savegame_f(), SV_ServerRecord_f(), SV_SetMaster_f(), SV_SetPlayer(), SVC_DirectConnect(), SVC_Info(), SVC_RemoteCommand(), V_Gun_Model_f(), and VID_LoadRefresh().
Cmd_CompleteCommand()
char* Cmd_CompleteCommand (char * partial)
Definition at line 772 of file cmd.c.
 {
     cmd_function_t  *cmd;
     int             len;
     cmdalias_t      *a;
     len = (int)strlen(partial);
     if (!len)
         return NULL;
 // check for exact match
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next)
         if (!strcmp (partial,cmd->name))
             return cmd->name;
     for (a=cmd_alias ; a ; a=a->next)
         if (!strcmp (partial, a->name))
             return a->name;
 // check for partial match
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next)
         if (!strncmp (partial,cmd->name, len))
             return cmd->name;
     for (a=cmd_alias ; a ; a=a->next)
         if (!strncmp (partial, a->name, len))
             return a->name;
     return NULL;
 }
Referenced by CompleteCommand().
Cmd_ExecuteString()
void Cmd_ExecuteString (char * text)
Definition at line 811 of file cmd.c.
 {
     cmd_function_t  *cmd;
     cmdalias_t      *a;
     Cmd_TokenizeString (text, true);
     // execute the command line
     if (!Cmd_Argc())
         return;     // no tokens
     // check functions
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next)
     {
         if (!Q_strcasecmp (cmd_argv[0],cmd->name))
         {
             if (!cmd->function)
             {   // forward to server command
                 Cmd_ExecuteString (va("cmd %s", text));
             }
             else
                 cmd->function ();
             return;
         }
     }
     // check alias
     for (a=cmd_alias ; a ; a=a->next)
     {
         if (!Q_strcasecmp (cmd_argv[0], a->name))
         {
             if (++alias_count == ALIAS_LOOP_COUNT)
             {
                 Com_Printf ("ALIAS_LOOP_COUNT\n");
                 return;
             }
             Cbuf_InsertText (a->value);
             return;
         }
     }
     // check cvars
     if (Cvar_Command ())
         return;
     // send it as a server command if we are connected
     Cmd_ForwardToServer ();
 }
Referenced by Cbuf_Execute(), Cbuf_ExecuteText(), Cmd_ExecuteString(), and SVC_RemoteCommand().
Cmd_Exists()
qboolean Cmd_Exists (char * cmd_name)
Definition at line 752 of file cmd.c.
 {
     cmd_function_t  *cmd;
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next)
     {
         if (!strcmp (cmd_name,cmd->name))
             return true;
     }
     return false;
 }
Cmd_ForwardToServer()
void Cmd_ForwardToServer (void)
Definition at line 286 of file cl_main.c.
 {
     char    *cmd;
     cmd = Cmd_Argv(0);
     if (cls.state <= ca_connected || *cmd == '-' || *cmd == '+')
     {
         Com_Printf ("Unknown command \"%s\"\n", cmd);
         return;
     }
     MSG_WriteByte (&cls.netchan.message, clc_stringcmd);
     SZ_Print (&cls.netchan.message, cmd);
     if (Cmd_Argc() > 1)
     {
         SZ_Print (&cls.netchan.message, " ");
         SZ_Print (&cls.netchan.message, Cmd_Args());
     }
 }
Cmd_Init()
void Cmd_Init (void)
Definition at line 881 of file cmd.c.
 {
 //
 // register our commands
 //
     Cmd_AddCommand ("cmdlist",Cmd_List_f);
     Cmd_AddCommand ("exec",Cmd_Exec_f);
     Cmd_AddCommand ("echo",Cmd_Echo_f);
     Cmd_AddCommand ("alias",Cmd_Alias_f);
     Cmd_AddCommand ("wait", Cmd_Wait_f);
 }
Referenced by Qcommon_Init().
Cmd_RemoveCommand()
void Cmd_RemoveCommand (char * cmd_name)
Definition at line 724 of file cmd.c.
 {
     cmd_function_t  *cmd, **back;
     back = &cmd_functions;
     while (1)
     {
         cmd = *back;
         if (!cmd)
         {
             Com_Printf ("Cmd_RemoveCommand: %s not added\n", cmd_name);
             return;
         }
         if (!strcmp (cmd_name, cmd->name))
         {
             *back = cmd->next;
             Z_Free (cmd);
             return;
         }
         back = &cmd->next;
     }
 }
Referenced by Miniaudio_Shutdown(), S_Shutdown(), and VID_LoadRefresh().
Cmd_TokenizeString()
void Cmd_TokenizeString (char * text, qboolean macroExpand)
Definition at line 620 of file cmd.c.
 {
     int     i;
     char    *com_token;
 // clear the args from the last string
     for (i=0 ; i<cmd_argc ; i++)
         Z_Free (cmd_argv[i]);
     cmd_argc = 0;
     cmd_args[0] = 0;
     // macro expand the text
     if (macroExpand)
         text = Cmd_MacroExpandString (text);
     if (!text)
         return;
     while (1)
     {
 // skip whitespace up to a /n
         while (*text && *text <= ' ' && *text != '\n')
         {
             text++;
         }
         if (*text == '\n')
         {   // a newline seperates commands in the buffer
             text++;
             break;
         }
         if (!*text)
             return;
         // set cmd_args to everything after the first arg
         if (cmd_argc == 1)
         {
             int     l;
             strcpy (cmd_args, text);
             // strip off any trailing whitespace
             l = (int)strlen(cmd_args) - 1;
             for ( ; l >= 0 ; l--)
                 if (cmd_args[l] <= ' ')
                     cmd_args[l] = 0;
                 else
                     break;
         }
         com_token = COM_Parse (&text);
         if (!text)
             return;
         if (cmd_argc < MAX_STRING_TOKENS)
         {
             cmd_argv[cmd_argc] = Z_Malloc ((int)strlen(com_token)+1);
             strcpy (cmd_argv[cmd_argc], com_token);
             cmd_argc++;
         }
     }
 }
Referenced by CL_ConnectionlessPacket(), Cmd_ExecuteString(), SV_ConnectionlessPacket(), and SV_ExecuteUserCommand().
COM_AddParm()
void COM_AddParm (char * parm)
Definition at line 1016 of file common.c.
 {
     if (com_argc == MAX_NUM_ARGVS)
         Com_Error (ERR_FATAL, "COM_AddParm: MAX_NUM)ARGS");
     com_argv[com_argc++] = parm;
 }
COM_Argc()
int COM_Argc (void)
Definition at line 968 of file common.c.
 {
     return com_argc;
 }
Referenced by Cbuf_AddEarlyCommands(), and Cbuf_AddLateCommands().
COM_Argv()
char* COM_Argv (int arg)
Definition at line 973 of file common.c.
 {
     if (arg < 0 || arg >= com_argc || !com_argv[arg])
         return "";
     return com_argv[arg];
 }
Referenced by Cbuf_AddEarlyCommands(), and Cbuf_AddLateCommands().
Com_BeginRedirect()
void Com_BeginRedirect (int target, char * buffer, int buffersize, void * flush)
Definition at line 74 of file common.c.
 {
     if (!target || !buffer || !buffersize || !flush)
         return;
     rd_target = target;
     rd_buffer = buffer;
     rd_buffersize = buffersize;
     rd_flush = flush;
     *rd_buffer = 0;
 }
Referenced by SVC_RemoteCommand(), and SVC_Status().
Com_BlockChecksum()
unsigned Com_BlockChecksum (void * buffer, int length)
Definition at line 213 of file md4.c.
 {
     uint32_t digest[4];
     unsigned val;
     PerformMD4((unsigned char *)buffer, length, (unsigned char *)digest);
     val = digest[0] ^ digest[1] ^ digest[2] ^ digest[3];
     return val;
 }
Referenced by CM_LoadMap(), COM_BlockSequenceCheckByte(), and FS_LoadPackFile().
COM_BlockSequenceCRCByte()
byte COM_BlockSequenceCRCByte (byte * base, int length, int sequence)
Definition at line 1338 of file common.c.
 {
     int     n;
     byte    *p;
     int     x;
     byte chkb[60 + 4];
     unsigned short crc;
     if (sequence < 0)
         Sys_Error("sequence < 0, this shouldn't happen\n");
     p = chktbl + (sequence % (sizeof(chktbl) - 4));
     if (length > 60)
         length = 60;
     memcpy (chkb, base, length);
     chkb[length] = p[0];
     chkb[length+1] = p[1];
     chkb[length+2] = p[2];
     chkb[length+3] = p[3];
     length += 4;
     crc = CRC_Block(chkb, length);
     for (x=0, n=0; n<length; n++)
         x += chkb[n];
     crc = (crc ^ x) & 0xff;
     return crc;
 }
Referenced by CL_SendCmd(), and SV_ExecuteClientMessage().
COM_CheckParm()
int COM_CheckParm (char * parm)
Definition at line 955 of file common.c.
 {
     int     i;
     for (i=1 ; i<com_argc ; i++)
     {
         if (!strcmp (parm,com_argv[i]))
             return i;
     }
     return 0;
 }
COM_ClearArgv()
void COM_ClearArgv (int arg)
Definition at line 980 of file common.c.
 {
     if (arg < 0 || arg >= com_argc || !com_argv[arg])
         return;
     com_argv[arg] = "";
 }
Referenced by Cbuf_AddEarlyCommands().
Com_DPrintf()
void Com_DPrintf (char * fmt, ...)
Definition at line 157 of file common.c.
 {
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     if (!developer || !developer->value)
         return;         // don't confuse non-developers with techie stuff...
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     Com_Printf ("%s", msg);
 }
Referenced by CDAudio_CloseDoor(), CDAudio_Eject(), CDAudio_GetAudioDiskInfo(), CDAudio_MessageHandler(), CDAudio_Pause(), CDAudio_Play2(), CDAudio_Resume(), CDAudio_Shutdown(), CDAudio_Stop(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ReadPackets(), CM_DecompressVis(), CopyFile(), DS_CreateBuffers(), DS_DestroyBuffers(), FreeSound(), FS_FOpenFile(), NET_SendPacket(), PM_InitialSnapPosition(), S_LoadSound(), S_Update_(), SNDDMA_InitDirect(), SNDDMA_InitWav(), SNDDMA_Submit(), SV_Baselines_f(), SV_Begin_f(), SV_BeginDownload_f(), SV_BuildClientFrame(), SV_ClientThink(), SV_Configstrings_f(), SV_ConnectionlessPacket(), SV_CopySaveGame(), SV_ExecuteClientMessage(), SV_GameMap_f(), SV_LinkEdict(), SV_New_f(), SV_Nextserver_f(), SV_ReadLevelFile(), SV_ReadServerFile(), SV_ServerRecord_f(), SV_SpawnServer(), SV_WipeSavegame(), SV_WriteLevelFile(), SV_WriteServerFile(), SVC_DirectConnect(), Sys_GetGameAPI(), and VID_Printf().
Com_EndRedirect()
void Com_EndRedirect (void)
Definition at line 86 of file common.c.
 {
     rd_flush(rd_target, rd_buffer);
     rd_target = 0;
     rd_buffer = NULL;
     rd_buffersize = 0;
     rd_flush = NULL;
 }
Referenced by SVC_RemoteCommand(), and SVC_Status().
Com_Error()
void Com_Error (int code, char * fmt, ...)
Definition at line 181 of file common.c.
 {
     va_list     argptr;
     static char     msg[MAXPRINTMSG];
     static  qboolean    recursive;
     if (recursive)
         Sys_Error ("recursive error after: %s", msg);
     recursive = true;
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     if (code == ERR_DISCONNECT)
     {
         CL_Drop ();
         recursive = false;
         longjmp (abortframe, -1);
     }
     else if (code == ERR_DROP)
     {
         Com_Printf ("********************\nERROR: %s\n********************\n", msg);
         SV_Shutdown (va("Server crashed: %s\n", msg), false);
         CL_Drop ();
         recursive = false;
         shutdown_game = true;
         longjmp (abortframe, -1);
     }
     else
     {
         SV_Shutdown (va("Server fatal crashed: %s\n", msg), false);
         SV_ShutdownGameProgs();
         CL_Shutdown ();
     }
     if (logfile)
     {
         fclose (logfile);
         logfile = NULL;
     }
     Sys_Error ("%s", msg);
 }
Referenced by CalcFov(), Cbuf_ExecuteText(), CL_Disconnect_f(), CL_GetEntitySoundOrigin(), CL_ParseConfigString(), CL_ParseFrame(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParsePacketEntities(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStartSoundPacket(), CL_ParseTEnt(), CL_RequestNextDownload(), CL_SetLightstyle(), CM_AreasConnected(), CM_InitBoxHull(), CM_InlineModel(), CM_LeafArea(), CM_LeafCluster(), CM_LeafContents(), CM_LoadMap(), CM_SetAreaPortalState(), CMod_LoadAreaPortals(), CMod_LoadAreas(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadEntityString(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadSubmodels(), CMod_LoadSurfaces(), CMod_LoadVisibility(), COM_AddParm(), Com_Error_f(), COM_InitArgv(), FloodArea_r(), FS_FOpenFile(), FS_LoadPackFile(), FS_Read(), GetWavinfo(), Key_Event(), M_PopMenu(), M_PushMenu(), MSG_ReadDir(), MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDeltaEntity(), MSG_WriteShort(), NET_GetPacket(), NET_Init(), NET_OpenIP(), NET_SendPacket(), PF_Configstring(), PF_cprintf(), PF_error(), PF_setmodel(), S_AliasName(), S_FindName(), S_PickChannel(), SCR_ExecuteLayoutString(), SCR_ReadNextFrame(), StartServer_MenuInit(), SV_BeginDemoserver(), SV_FatPVS(), SV_FindIndex(), SV_HullForEntity(), SV_InitGameProgs(), SV_Multicast(), SV_SendClientMessages(), SV_StartSound(), Sys_CopyProtect(), Sys_GetGameAPI(), Sys_UnloadGame(), SZ_GetSpace(), V_AddLightStyle(), VID_CheckChanges(), VID_Error(), VID_FreeReflib(), VID_LoadRefresh(), Z_Free(), and Z_TagMalloc().
COM_Init()
void COM_Init (void)
COM_InitArgv()
void COM_InitArgv (int argc, char ** argv)
Definition at line 993 of file common.c.
 {
     int     i;
     if (argc > MAX_NUM_ARGVS)
         Com_Error (ERR_FATAL, "argc > MAX_NUM_ARGVS");
     com_argc = argc;
     for (i=0 ; i<argc ; i++)
     {
         if (!argv[i] || strlen(argv[i]) >= MAX_TOKEN_CHARS )
             com_argv[i] = "";
         else
             com_argv[i] = argv[i];
     }
 }
Referenced by Qcommon_Init().
Com_Printf()
void Com_Printf (char * fmt, ...)
Definition at line 104 of file common.c.
 {
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     va_start (argptr,fmt);
     vsnprintf (msg,MAXPRINTMSG,fmt,argptr);
     va_end (argptr);
     if (rd_target)
     {
         if ((strlen (msg) + strlen(rd_buffer)) > (rd_buffersize - 1))
         {
             rd_flush(rd_target, rd_buffer);
             *rd_buffer = 0;
         }
         strcat (rd_buffer, msg);
         return;
     }
     Con_Print (msg);
     // also echo to debugging console
     Sys_ConsoleOutput (msg);
     // logfile
     if (logfile_active && logfile_active->value)
     {
         char    name[MAX_QPATH];
         if (!logfile)
         {
             Com_sprintf (name, sizeof(name), "%s/qconsole.log", FS_Gamedir ());
             if (logfile_active->value > 2)
                 logfile = fopen (name, "a");
             else
                 logfile = fopen (name, "w");
         }
         if (logfile)
             fprintf (logfile, "%s", msg);
         if (logfile_active->value > 1)
             fflush (logfile);       // force it to save every time
     }
 }
Com_Quit()
void Com_Quit (void)
Definition at line 235 of file common.c.
 {
     SV_Shutdown ("Server quit\n", false);
     SV_ShutdownGameProgs();
     CL_Shutdown ();
     if (logfile)
     {
         fclose (logfile);
         logfile = NULL;
     }
     Sys_Quit ();
 }
Referenced by CL_Quit_f(), MainWndProc(), Qcommon_Init(), and WinMain().
Com_ServerState()
int Com_ServerState (void)
Definition at line 256 of file common.c.
 {
     return server_state;
 }
Referenced by CL_CheckForResend(), CL_Connect_f(), CL_ParseServerData(), CL_Pause_f(), Con_ToggleConsole_f(), Cvar_Set2(), M_Menu_SaveGame_f(), M_PushMenu(), and StartServerActionFunc().
Com_SetServerState()
void Com_SetServerState (int state)
Definition at line 266 of file common.c.
 {
     server_state = state;
 }
Referenced by SV_Shutdown(), and SV_SpawnServer().
Con_Print()
void Con_Print (char * text)
Definition at line 352 of file console.c.
 {
     int     y;
     int     c, l;
     static int  cr;
     int     mask;
     if (!con.initialized)
         return;
     if (txt[0] == 1 || txt[0] == 2)
     {
         mask = 128;     // go to colored text
         txt++;
     }
     else
         mask = 0;
     while ( (c = *txt) )
     {
     // count word length
         for (l=0 ; l< con.linewidth ; l++)
             if ( txt[l] <= ' ')
                 break;
     // word wrap
         if (l != con.linewidth && (con.x + l > con.linewidth) )
             con.x = 0;
         txt++;
         if (cr)
         {
             con.current--;
             cr = false;
         }
         if (!con.x)
         {
             Con_Linefeed ();
         // mark time for transparent overlay
             if (con.current >= 0)
                 con.times[con.current % NUM_CON_TIMES] = cls.realtime;
         }
         switch (c)
         {
         case '\n':
             con.x = 0;
             break;
         case '\r':
             con.x = 0;
             cr = 1;
             break;
         default:    // display character and advance
             y = con.current % con.totallines;
             con.text[y*con.linewidth+con.x] = c | mask | con.ormask;
             con.x++;
             if (con.x >= con.linewidth)
                 con.x = 0;
             break;
         }
     }
 }
Referenced by Com_Printf().
CopyString()
char* CopyString (char * in)
Definition at line 1038 of file common.c.
 {
     char    *out;
     out = Z_Malloc ((int)strlen(in)+1);
     strcpy (out, in);
     return out;
 }
Referenced by Cmd_Alias_f(), Cvar_FullSet(), Cvar_Get(), Cvar_Set2(), and FS_Link_f().
crand()
float crand (void)
Definition at line 1380 of file common.c.
 {
     return (rand()&32767)* (2.0/32767) - 1;
 }
Referenced by CL_BlasterParticles(), CL_BlasterParticles2(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DiminishingTrail(), CL_FlagTrail(), CL_FlameEffects(), CL_ForceWall(), CL_GenericParticleEffect(), CL_ItemRespawnParticles(), CL_LogoutEffect(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleporterParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrapParticles(), CL_Widowbeamout(), and CL_WidowSplash().
CRC_Block()
unsigned short CRC_Block (byte * start, int count)
Definition at line 82 of file crc.c.
 {
     unsigned short  crc;
     CRC_Init (&crc);
     while (count--)
         crc = (crc << 8) ^ crctable[(crc >> 8) ^ *start++];
     return crc;
 }
Referenced by COM_BlockSequenceCRCByte().
CRC_Init()
void CRC_Init (unsigned short * crcvalue)
Definition at line 67 of file crc.c.
 {
     *crcvalue = CRC_INIT_VALUE;
 }
Referenced by CRC_Block().
CRC_ProcessByte()
void CRC_ProcessByte (unsigned short * crcvalue, byte data)
Definition at line 72 of file crc.c.
 {
     *crcvalue = (*crcvalue << 8) ^ crctable[(*crcvalue >> 8) ^ data];
 }
CRC_Value()
unsigned short CRC_Value (unsigned short crcvalue)
Definition at line 77 of file crc.c.
 {
     return crcvalue ^ CRC_XOR_VALUE;
 }
Cvar_Command()
qboolean Cvar_Command (void)
Definition at line 363 of file cvar.c.
 {
     cvar_t          *v;
 // check variables
     v = Cvar_FindVar (Cmd_Argv(0));
     if (!v)
         return false;
 // perform a variable print or set
     if (Cmd_Argc() == 1)
     {
         Com_Printf ("\"%s\" is \"%s\"\n", v->name, v->string);
         return true;
     }
     Cvar_Set (v->name, Cmd_Argv(1));
     return true;
 }
Referenced by Cmd_ExecuteString().
Cvar_CompleteVariable()
char* Cvar_CompleteVariable (char * partial)
Definition at line 95 of file cvar.c.
 {
     cvar_t      *cvar;
     int         len;
     len = (int)strlen(partial);
     if (!len)
         return NULL;
     // check exact match
     for (cvar=cvar_vars ; cvar ; cvar=cvar->next)
         if (!strcmp (partial,cvar->name))
             return cvar->name;
     // check partial match
     for (cvar=cvar_vars ; cvar ; cvar=cvar->next)
         if (!strncmp (partial,cvar->name, len))
             return cvar->name;
     return NULL;
 }
Referenced by CompleteCommand().
Cvar_ForceSet()
cvar_t* Cvar_ForceSet (char * var_name, char * value)
Definition at line 268 of file cvar.c.
 {
     return Cvar_Set2 (var_name, value, true);
 }
Referenced by EasyGameFunc(), HardGameFunc(), MediumGameFunc(), SV_InitGameProgs(), and SV_ReadServerFile().
Cvar_FullSet()
cvar_t* Cvar_FullSet (char * var_name, char * value, int flags)
Definition at line 288 of file cvar.c.
 {
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
     {   // create it
         return Cvar_Get (var_name, value, flags);
     }
     var->modified = true;
     if (var->flags & CVAR_USERINFO)
         userinfo_modified = true;   // transmit at next oportunity
     Z_Free (var->string);   // free the old value string
     var->string = CopyString(value);
     var->value = atof (var->string);
     var->flags = flags;
     return var;
 }
Referenced by Cvar_Set_f(), FS_SetGamedir(), SV_InitGame(), and SV_SpawnServer().
Cvar_Get()
cvar_t* Cvar_Get (char * var_name, char * value, int flags)
Definition at line 127 of file cvar.c.
 {
     cvar_t  *var;
     if (flags & (CVAR_USERINFO | CVAR_SERVERINFO))
     {
         if (!Cvar_InfoValidate (var_name))
         {
             Com_Printf("invalid info cvar name\n");
             return NULL;
         }
     }
     var = Cvar_FindVar (var_name);
     if (var)
     {
         var->flags |= flags;
         return var;
     }
     if (!var_value)
         return NULL;
     if (flags & (CVAR_USERINFO | CVAR_SERVERINFO))
     {
         if (!Cvar_InfoValidate (var_value))
         {
             Com_Printf("invalid info cvar value\n");
             return NULL;
         }
     }
     var = Z_Malloc (sizeof(*var));
     var->name = CopyString (var_name);
     var->string = CopyString (var_value);
     var->modified = true;
     var->value = atof (var->string);
     // link the variable in
     var->next = cvar_vars;
     cvar_vars = var;
     var->flags = flags;
     return var;
 }
Referenced by AddressBook_MenuInit(), CDAudio_Init(), CL_FixCvarCheats(), CL_InitInput(), CL_InitLocal(), CL_PingServers_f(), CM_LoadMap(), Con_Init(), Cvar_FullSet(), Cvar_Set2(), FS_InitFilesystem(), IN_Init(), IN_StartupJoystick(), IN_StartupMouse(), Miniaudio_Init(), NET_Init(), NET_OpenIP(), NET_OpenIPX(), Netchan_Init(), Options_MenuInit(), PlayerConfig_MenuInit(), Qcommon_Init(), S_Init(), SCR_Init(), SNDDMA_Init(), SV_Init(), SV_InitGameProgs(), V_Init(), VID_Init(), VID_LoadRefresh(), and VID_MenuInit().
Cvar_GetLatchedVars()
void Cvar_GetLatchedVars (void)
Definition at line 336 of file cvar.c.
 {
     cvar_t  *var;
     for (var = cvar_vars ; var ; var = var->next)
     {
         if (!var->latched_string)
             continue;
         Z_Free (var->string);
         var->string = var->latched_string;
         var->latched_string = NULL;
         var->value = atof(var->string);
         if (!strcmp(var->name, "game"))
         {
             FS_SetGamedir (var->string);
             FS_ExecAutoexec ();
         }
     }
 }
Referenced by SV_InitGame().
Cvar_Init()
void Cvar_Init (void)
Definition at line 522 of file cvar.c.
 {
     Cmd_AddCommand ("set", Cvar_Set_f);
     Cmd_AddCommand ("cvarlist", Cvar_List_f);
 }
Referenced by Qcommon_Init().
Cvar_Serverinfo()
char* Cvar_Serverinfo (void)
Definition at line 510 of file cvar.c.
 {
     return Cvar_BitInfo (CVAR_SERVERINFO);
 }
Referenced by SV_Serverinfo_f(), SV_ShowServerinfo_f(), and SV_StatusString().
Cvar_Set()
cvar_t* Cvar_Set (char * var_name, char * value)
Definition at line 278 of file cvar.c.
 {
     return Cvar_Set2 (var_name, value, false);
 }
Referenced by AddressBook_MenuKey(), ApplyChanges(), CL_FixCvarCheats(), CL_FixUpGender(), CL_ParseServerData(), Con_ToggleConsole_f(), Cvar_Command(), Cvar_Set_f(), Cvar_SetValue(), Key_Event(), M_ForceMenuOff(), M_PushMenu(), PlayerConfig_MenuKey(), SCR_CalcVrect(), StartServerActionFunc(), SV_InitGameProgs(), SV_Map(), SV_Nextserver(), SV_SetMaster_f(), SV_SpawnServer(), VID_CheckChanges(), VID_LoadRefresh(), and VID_NewWindow().
Cvar_SetValue()
void Cvar_SetValue (char * var_name, float value)
Definition at line 317 of file cvar.c.
 {
     char    val[32];
     if (value == (int)value)
         Com_sprintf (val, sizeof(val), "%i",(int)value);
     else
         Com_sprintf (val, sizeof(val), "%f",value);
     Cvar_Set (var_name, val);
 }
Referenced by AlwaysRunFunc(), ApplyChanges(), BrightnessCallback(), CL_Pause_f(), ControlsSetMenuItemValues(), CrosshairFunc(), DMFlagCallback(), DownloadCallback(), FreeLookFunc(), HandednessCallback(), InvertMouseFunc(), JoystickFunc(), LookspringFunc(), LookstrafeFunc(), MainWndProc(), MouseSpeedFunc(), NoAltTabFunc(), PlayerConfig_MenuInit(), RateCallback(), SCR_PlayCinematic(), SCR_SizeDown_f(), SCR_SizeUp_f(), SCR_UpdateScreen(), ScreenSizeCallback(), StartGame(), StartServerActionFunc(), UpdateCDVolumeFunc(), UpdateSoundQualityFunc(), UpdateVolumeFunc(), and VID_LoadRefresh().
Cvar_Userinfo()
char* Cvar_Userinfo (void)
Definition at line 504 of file cvar.c.
 {
     return Cvar_BitInfo (CVAR_USERINFO);
 }
Referenced by CL_SendCmd(), CL_SendConnectPacket(), and CL_Userinfo_f().
Cvar_VariableString()
char* Cvar_VariableString (char * var_name)
Definition at line 79 of file cvar.c.
 {
     cvar_t *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return "";
     return var->string;
 }
Referenced by CL_PingServers_f(), Cmd_AddCommand(), Cmd_MacroExpandString(), FS_ExecAutoexec(), StartServer_MenuInit(), SV_New_f(), SV_Nextserver(), and SV_ServerRecord_f().
Cvar_VariableValue()
float Cvar_VariableValue (char * var_name)
Definition at line 63 of file cvar.c.
 {
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return 0;
     return atof (var->string);
 }
Referenced by CDAudio_Play2(), CL_Pause_f(), CL_SendConnectPacket(), CM_LoadMap(), Con_ToggleConsole_f(), ControlsSetMenuItemValues(), DMFlagCallback(), DMOptions_MenuInit(), DownloadOptions_MenuInit(), IN_Frame(), M_PushMenu(), Miniaudio_Init(), Miniaudio_Play(), NET_OpenIP(), NET_OpenIPX(), Options_MenuInit(), PlayerConfig_MenuInit(), SCR_PlayCinematic(), StartServer_MenuInit(), SV_CheckForSavegame(), SV_InitGame(), SV_Map(), SV_Nextserver(), SV_Savegame_f(), and SV_SpawnServer().
Cvar_WriteVariables()
void Cvar_WriteVariables (char * path)
Definition at line 429 of file cvar.c.
 {
     cvar_t  *var;
     char    buffer[1024];
     FILE    *f;
     f = fopen (path, "a");
     for (var = cvar_vars ; var ; var = var->next)
     {
         if (var->flags & CVAR_ARCHIVE)
         {
             Com_sprintf (buffer, sizeof(buffer), "set %s \"%s\"\n", var->name, var->string);
             fprintf (f, "%s", buffer);
         }
     }
     fclose (f);
 }
Referenced by CL_WriteConfiguration().
frand()
float frand (void)
Definition at line 1375 of file common.c.
 {
     return (rand()&32767)* (1.0/32767);
 }
Referenced by CL_BFGExplosionParticles(), CL_BigTeleportParticles(), CL_BlasterParticles(), CL_BlasterParticles2(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_ColorExplosionParticles(), CL_DiminishingTrail(), CL_ExplosionParticles(), CL_FlagTrail(), CL_FlameEffects(), CL_ForceWall(), CL_GenericParticleEffect(), CL_IonripperTrail(), CL_ItemRespawnParticles(), CL_LogoutEffect(), CL_ParseTEnt(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TrapParticles(), and CL_WidowSplash().
FS_CreatePath()
void FS_CreatePath (char * path)
Definition at line 125 of file files.c.
 {
     char    *ofs;
     for (ofs = path+1 ; *ofs ; ofs++)
     {
         if (*ofs == '/')
         {   // create the directory
             *ofs = 0;
             Sys_Mkdir (path);
             *ofs = '/';
         }
     }
 }
Referenced by CL_ParseDownload(), CL_Record_f(), Con_Dump_f(), SV_CopySaveGame(), SV_GameMap_f(), and SV_ServerRecord_f().
FS_ExecAutoexec()
void FS_ExecAutoexec (void)
Definition at line 572 of file files.c.
 {
     char *dir;
     char name [MAX_QPATH];
     dir = Cvar_VariableString("gamedir");
     if (*dir)
         Com_sprintf(name, sizeof(name), "%s/%s/autoexec.cfg", fs_basedir->string, dir);
     else
         Com_sprintf(name, sizeof(name), "%s/%s/autoexec.cfg", fs_basedir->string, BASEDIRNAME);
     if (Sys_FindFirst(name, 0, SFF_SUBDIR | SFF_HIDDEN | SFF_SYSTEM))
         Cbuf_AddText ("exec autoexec.cfg\n");
     Sys_FindClose();
 }
Referenced by CL_Init(), Cvar_GetLatchedVars(), and Cvar_Set2().
FS_FCloseFile()
void FS_FCloseFile (FILE * f)
Definition at line 149 of file files.c.
 {
     fclose (f);
 }
Referenced by S_RegisterSexedSound().
FS_FOpenFile()
int FS_FOpenFile (char * filename, FILE ** file)
Definition at line 206 of file files.c.
 {
     searchpath_t    *search;
     char            netpath[MAX_OSPATH];
     pack_t          *pak;
     int             i;
     filelink_t      *link;
     file_from_pak = 0;
     // check for links first
     for (link = fs_links ; link ; link=link->next)
     {
         if (!strncmp (filename, link->from, link->fromlength))
         {
             Com_sprintf (netpath, sizeof(netpath), "%s%s",link->to, filename+link->fromlength);
             *file = fopen (netpath, "rb");
             if (*file)
             {
                 Com_DPrintf ("link file: %s\n",netpath);
                 return FS_filelength (*file);
             }
             return -1;
         }
     }
 //
 // search through the path, one element at a time
 //
     for (search = fs_searchpaths ; search ; search = search->next)
     {
     // is the element a pak file?
         if (search->pack)
         {
         // look through all the pak file elements
             pak = search->pack;
             for (i=0 ; i<pak->numfiles ; i++)
                 if (!Q_strcasecmp (pak->files[i].name, filename))
                 {   // found it!
                     file_from_pak = 1;
                     Com_DPrintf ("PackFile: %s : %s\n",pak->filename, filename);
                 // open a new file on the pakfile
                     *file = fopen (pak->filename, "rb");
                     if (!*file)
                         Com_Error (ERR_FATAL, "Couldn't reopen %s", pak->filename);
                     fseek (*file, pak->files[i].filepos, SEEK_SET);
                     return pak->files[i].filelen;
                 }
         }
         else
         {
     // check a file in the directory tree
             Com_sprintf (netpath, sizeof(netpath), "%s/%s",search->filename, filename);
 #ifndef _WIN32
             // some expansion packs use backslashes in file paths which works only on Windows
             char *np = netpath;
             while ( *np++ ) *np = *np == '\\' ? '/' : *np;
 #endif
             *file = fopen (netpath, "rb");
             if (!*file)
                 continue;
             Com_DPrintf ("FindFile: %s\n",netpath);
             return FS_filelength (*file);
         }
     }
     Com_DPrintf ("FindFile: can't find %s\n", filename);
     *file = NULL;
     return -1;
 }
Referenced by FS_LoadFile(), S_RegisterSexedSound(), SCR_PlayCinematic(), and SV_BeginDemoserver().
FS_FreeFile()
void FS_FreeFile (void * buffer)
Definition at line 437 of file files.c.
 {
     Z_Free (buffer);
 }
Referenced by CL_RequestNextDownload(), CM_LoadMap(), Cmd_Exec_f(), M_Credits_Key(), S_LoadSound(), SCR_LoadPCX(), StartServer_MenuInit(), SV_BeginDownload_f(), SV_DropClient(), SV_NextDownload_f(), and VID_LoadRefresh().
FS_Gamedir()
char* FS_Gamedir (void)
Definition at line 559 of file files.c.
 {
     if (*fs_gamedir)
         return fs_gamedir;
     else
         return BASEDIRNAME;
 }
Referenced by CL_DownloadFileName(), CL_Record_f(), CL_WriteConfiguration(), Com_Printf(), Con_Dump_f(), Create_Savestrings(), Miniaudio_Play(), StartServer_MenuInit(), SV_CheckForSavegame(), SV_CopySaveGame(), SV_GameMap_f(), SV_Loadgame_f(), SV_ReadLevelFile(), SV_ReadServerFile(), SV_ServerRecord_f(), SV_WipeSavegame(), SV_WriteLevelFile(), SV_WriteServerFile(), and VID_LoadRefresh().
FS_InitFilesystem()
void FS_InitFilesystem (void)
Definition at line 848 of file files.c.
 {
     Cmd_AddCommand ("path", FS_Path_f);
     Cmd_AddCommand ("link", FS_Link_f);
     Cmd_AddCommand ("dir", FS_Dir_f );
     //
     // basedir <path>
     // allows the game to run from outside the data tree
     //
     fs_basedir = Cvar_Get ("basedir", ".", CVAR_NOSET);
     //
     // cddir <path>
     // Logically concatenates the cddir after the basedir for
     // allows the game to run from outside the data tree
     //
     fs_cddir = Cvar_Get ("cddir", "", CVAR_NOSET);
     if (fs_cddir->string[0])
         FS_AddGameDirectory (va("%s/"BASEDIRNAME, fs_cddir->string) );
     //
     // start up with baseq2 by default
     //
     FS_AddGameDirectory (va("%s/"BASEDIRNAME, fs_basedir->string) );
     // any set gamedirs will be freed up to here
     fs_base_searchpaths = fs_searchpaths;
     // check for game override
     fs_gamedirvar = Cvar_Get ("game", "", CVAR_LATCH|CVAR_SERVERINFO);
     if (fs_gamedirvar->string[0])
         FS_SetGamedir (fs_gamedirvar->string);
 }
Referenced by Qcommon_Init().
FS_LoadFile()
int FS_LoadFile (char * path, void ** buffer)
Definition at line 398 of file files.c.
 {
     FILE    *h;
     byte    *buf;
     int     len;
     buf = NULL; // quiet compiler warning
 // look for it in the filesystem or pack files
     len = FS_FOpenFile (path, &h);
     if (!h)
     {
         if (buffer)
             *buffer = NULL;
         return -1;
     }
     if (!buffer)
     {
         fclose (h);
         return len;
     }
     buf = Z_Malloc(len);
     *buffer = buf;
     FS_Read (buf, len, h);
     fclose (h);
     return len;
 }
Referenced by CL_CheckOrDownloadFile(), CL_Download_f(), CL_RequestNextDownload(), CM_LoadMap(), Cmd_Exec_f(), M_Menu_Credits_f(), S_LoadSound(), SCR_LoadPCX(), StartServer_MenuInit(), SV_BeginDownload_f(), SV_Map_f(), and VID_LoadRefresh().
FS_NextPath()
char* FS_NextPath (char * prevpath)
Definition at line 821 of file files.c.
 {
     searchpath_t    *s;
     char            *prev;
     if (!prevpath)
         return fs_gamedir;
     prev = fs_gamedir;
     for (s=fs_searchpaths ; s ; s=s->next)
     {
         if (s->pack)
             continue;
         if (prevpath == prev)
             return s->filename;
         prev = s->filename;
     }
     return NULL;
 }
Referenced by FS_Dir_f(), PlayerConfig_ScanDirectories(), and Sys_GetGameAPI().
FS_Read()
void FS_Read (void * buffer, int len, FILE * f)
Definition at line 350 of file files.c.
 {
     int     block, remaining;
     int     read;
     byte    *buf;
     int     tries;
     buf = (byte *)buffer;
     // read in chunks for progress bar
     remaining = len;
     tries = 0;
     while (remaining)
     {
         block = remaining;
         if (block > MAX_READ)
             block = MAX_READ;
         read = (int)fread (buf, 1, block, f);
         if (read == 0)
         {
             // we might have been trying to read from a CD
             if (!tries)
             {
                 tries = 1;
                 CDAudio_Stop();
             }
             else
                 Com_Error (ERR_FATAL, "FS_Read: 0 bytes read");
         }
         if (read == -1)
             Com_Error (ERR_FATAL, "FS_Read: -1 bytes read");
         // do some progress bar thing here...
         remaining -= read;
         buf += read;
     }
 }
Referenced by CM_ReadPortalState(), Create_Savestrings(), FS_LoadFile(), Huff1TableInit(), SCR_PlayCinematic(), SCR_ReadNextFrame(), SV_ReadLevelFile(), and SV_ReadServerFile().
FS_SetGamedir()
void FS_SetGamedir (char * dir)
Definition at line 595 of file files.c.
 {
     searchpath_t    *next;
     if (strstr(dir, "..") || strstr(dir, "/")
         || strstr(dir, "\\") || strstr(dir, ":") )
     {
         Com_Printf ("Gamedir should be a single filename, not a path\n");
         return;
     }
     //
     // free up any current game dir info
     //
     while (fs_searchpaths != fs_base_searchpaths)
     {
         if (fs_searchpaths->pack)
         {
             fclose (fs_searchpaths->pack->handle);
             Z_Free (fs_searchpaths->pack->files);
             Z_Free (fs_searchpaths->pack);
         }
         next = fs_searchpaths->next;
         Z_Free (fs_searchpaths);
         fs_searchpaths = next;
     }
     //
     // flush all data, so it will be forced to reload
     //
     if (dedicated && !dedicated->value)
         Cbuf_AddText ("vid_restart\nsnd_restart\n");
     Com_sprintf (fs_gamedir, sizeof(fs_gamedir), "%s/%s", fs_basedir->string, dir);
     if (!strcmp(dir,BASEDIRNAME) || (*dir == 0))
     {
         Cvar_FullSet ("gamedir", "", CVAR_SERVERINFO|CVAR_NOSET);
         Cvar_FullSet ("game", "", CVAR_LATCH|CVAR_SERVERINFO);
     }
     else
     {
         Cvar_FullSet ("gamedir", dir, CVAR_SERVERINFO|CVAR_NOSET);
         if (fs_cddir->string[0])
             FS_AddGameDirectory (va("%s/%s", fs_cddir->string, dir) );
         FS_AddGameDirectory (va("%s/%s", fs_basedir->string, dir) );
     }
 }
Referenced by Cvar_GetLatchedVars(), Cvar_Set2(), and FS_InitFilesystem().
Info_Print()
void Info_Print (char * s)
Definition at line 1049 of file common.c.
 {
     char    key[512];
     char    value[512];
     char    *o;
     int     l;
     if (*s == '\\')
         s++;
     while (*s)
     {
         o = key;
         while (*s && *s != '\\')
             *o++ = *s++;
         l = o - key;
         if (l < 20)
         {
             memset (o, ' ', 20-l);
             key[20] = 0;
         }
         else
             *o = 0;
         Com_Printf ("%s", key);
         if (!*s)
         {
             Com_Printf ("MISSING VALUE\n");
             return;
         }
         o = value;
         s++;
         while (*s && *s != '\\')
             *o++ = *s++;
         *o = 0;
         if (*s)
             s++;
         Com_Printf ("%s\n", value);
     }
 }
Referenced by CL_Userinfo_f(), SV_DumpUser_f(), SV_Serverinfo_f(), and SV_ShowServerinfo_f().
LittleFloat()
float LittleFloat (float l)
Definition at line 950 of file q_shared.c.
 {return _LittleFloat(l);}
Referenced by CMod_LoadPlanes(), CMod_LoadSubmodels(), COM_BlockSequenceCheckByte(), Mod_LoadAliasModel(), Mod_LoadPlanes(), Mod_LoadSubmodels(), Mod_LoadTexinfo(), and Mod_LoadVertexes().
LittleLong()
int LittleLong (int l)
Definition at line 948 of file q_shared.c.
 {return _LittleLong(l);}
Referenced by CL_Record_f(), CL_RequestNextDownload(), CL_WriteDemoMessage(), CM_LoadMap(), CMod_LoadAreaPortals(), CMod_LoadAreas(), CMod_LoadBrushes(), CMod_LoadLeafs(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadSubmodels(), CMod_LoadSurfaces(), CMod_LoadVisibility(), COM_BlockSequenceCheckByte(), Draw_GetPalette(), FS_LoadPackFile(), GL_LoadWal(), Mod_ForName(), Mod_LoadAliasModel(), Mod_LoadBrushModel(), Mod_LoadFaces(), Mod_LoadLeafs(), Mod_LoadNodes(), Mod_LoadPlanes(), Mod_LoadSpriteModel(), Mod_LoadSubmodels(), Mod_LoadSurfedges(), Mod_LoadTexinfo(), Mod_LoadVisibility(), MSG_ReadFloat(), MSG_WriteFloat(), R_LoadWal(), SCR_PlayCinematic(), SCR_ReadNextFrame(), SV_RecordDemoMessage(), SV_SendClientMessages(), SV_ServerRecord_f(), and Vk_LoadWal().
LittleShort()
short LittleShort (short l)
Definition at line 946 of file q_shared.c.
 {return _LittleShort(l);}
Referenced by CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), LoadPCX(), LoadTGA(), Mod_LoadAliasModel(), Mod_LoadEdges(), Mod_LoadFaces(), Mod_LoadLeafs(), Mod_LoadMarksurfaces(), Mod_LoadNodes(), ResampleSfx(), S_RawSamples(), and WritePCXfile().
MSG_BeginReading()
void MSG_BeginReading (sizebuf_t * sb)
Definition at line 684 of file common.c.
 {
     msg->readcount = 0;
 }
Referenced by CL_ConnectionlessPacket(), Netchan_Process(), SV_ConnectionlessPacket(), and SV_ReadPackets().
MSG_ReadAngle()
float MSG_ReadAngle (sizebuf_t * sb)
Definition at line 825 of file common.c.
 {
     return MSG_ReadChar(msg_read) * (360.0/256);
 }
Referenced by CL_ParseDelta().
MSG_ReadAngle16()
float MSG_ReadAngle16 (sizebuf_t * sb)
Definition at line 830 of file common.c.
 {
     return SHORT2ANGLE(MSG_ReadShort(msg_read));
 }
Referenced by CL_ParsePlayerstate().
MSG_ReadByte()
int MSG_ReadByte (sizebuf_t * sb)
Definition at line 703 of file common.c.
 {
     int c;
     if (msg_read->readcount+1 > msg_read->cursize)
         c = -1;
     else
         c = (unsigned char)msg_read->data[msg_read->readcount];
     msg_read->readcount++;
     return c;
 }
Referenced by CL_ParseDelta(), CL_ParseDownload(), CL_ParseEntityBits(), CL_ParseFrame(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParseParticles(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), MSG_ReadData(), MSG_ReadDeltaUsercmd(), MSG_ReadDir(), and SV_ExecuteClientMessage().
MSG_ReadChar()
int MSG_ReadChar (sizebuf_t * sb)
Definition at line 690 of file common.c.
 {
     int c;
     if (msg_read->readcount+1 > msg_read->cursize)
         c = -1;
     else
         c = (signed char)msg_read->data[msg_read->readcount];
     msg_read->readcount++;
     return c;
 }
Referenced by CL_ParsePlayerstate(), MSG_ReadAngle(), MSG_ReadString(), and MSG_ReadStringLine().
MSG_ReadCoord()
float MSG_ReadCoord (sizebuf_t * sb)
Definition at line 813 of file common.c.
 {
     return MSG_ReadShort(msg_read) * (1.0/8);
 }
Referenced by CL_ParseDelta().
MSG_ReadData()
void MSG_ReadData (sizebuf_t * sb, void * buffer, int size)
Definition at line 874 of file common.c.
 {
     int     i;
     for (i=0 ; i<len ; i++)
         ((byte *)data)[i] = MSG_ReadByte (msg_read);
 }
Referenced by CL_ParseFrame().
MSG_ReadDeltaUsercmd()
void MSG_ReadDeltaUsercmd (sizebuf_t * sb, struct usercmd_s * from, struct usercmd_s * cmd)
Definition at line 835 of file common.c.
 {
     int bits;
     memcpy (move, from, sizeof(*move));
     bits = MSG_ReadByte (msg_read);
 // read current angles
     if (bits & CM_ANGLE1)
         move->angles[0] = MSG_ReadShort (msg_read);
     if (bits & CM_ANGLE2)
         move->angles[1] = MSG_ReadShort (msg_read);
     if (bits & CM_ANGLE3)
         move->angles[2] = MSG_ReadShort (msg_read);
 // read movement
     if (bits & CM_FORWARD)
         move->forwardmove = MSG_ReadShort (msg_read);
     if (bits & CM_SIDE)
         move->sidemove = MSG_ReadShort (msg_read);
     if (bits & CM_UP)
         move->upmove = MSG_ReadShort (msg_read);
 // read buttons
     if (bits & CM_BUTTONS)
         move->buttons = MSG_ReadByte (msg_read);
     if (bits & CM_IMPULSE)
         move->impulse = MSG_ReadByte (msg_read);
 // read time to run command
     move->msec = MSG_ReadByte (msg_read);
 // read the light level
     move->lightlevel = MSG_ReadByte (msg_read);
 }
Referenced by SV_ExecuteClientMessage().
MSG_ReadDir()
void MSG_ReadDir (sizebuf_t * sb, vec3_t vector)
Definition at line 464 of file common.c.
 {
     int     b;
     b = MSG_ReadByte (sb);
     if (b >= NUMVERTEXNORMALS)
         Com_Error (ERR_DROP, "MSF_ReadDir: out of range");
     VectorCopy (bytedirs[b], dir);
 }
Referenced by CL_ParseParticles(), CL_ParseSteam(), and CL_ParseTEnt().
MSG_ReadFloat()
float MSG_ReadFloat (sizebuf_t * sb)
Definition at line 748 of file common.c.
 {
     union
     {
         byte    b[4];
         float   f;
         int l;
     } dat;
     if (msg_read->readcount+4 > msg_read->cursize)
         dat.f = -1;
     else
     {
         dat.b[0] =  msg_read->data[msg_read->readcount];
         dat.b[1] =  msg_read->data[msg_read->readcount+1];
         dat.b[2] =  msg_read->data[msg_read->readcount+2];
         dat.b[3] =  msg_read->data[msg_read->readcount+3];
     }
     msg_read->readcount += 4;
     dat.l = LittleLong (dat.l);
     return dat.f;
 }
MSG_ReadLong()
int MSG_ReadLong (sizebuf_t * sb)
Definition at line 731 of file common.c.
 {
     int c;
     if (msg_read->readcount+4 > msg_read->cursize)
         c = -1;
     else
         c = msg_read->data[msg_read->readcount]
         + (msg_read->data[msg_read->readcount+1]<<8)
         + (msg_read->data[msg_read->readcount+2]<<16)
         + (msg_read->data[msg_read->readcount+3]<<24);
     msg_read->readcount += 4;
     return c;
 }
Referenced by CL_ConnectionlessPacket(), CL_ParseDelta(), CL_ParseFrame(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseSteam(), Netchan_Process(), SV_ConnectionlessPacket(), SV_ExecuteClientMessage(), and SV_ReadPackets().
MSG_ReadPos()
void MSG_ReadPos (sizebuf_t * sb, vec3_t pos)
Definition at line 818 of file common.c.
 {
     pos[0] = MSG_ReadShort(msg_read) * (1.0/8);
     pos[1] = MSG_ReadShort(msg_read) * (1.0/8);
     pos[2] = MSG_ReadShort(msg_read) * (1.0/8);
 }
Referenced by CL_ParseBeam(), CL_ParseBeam2(), CL_ParseDelta(), CL_ParseLaser(), CL_ParseLightning(), CL_ParseNuke(), CL_ParseParticles(), CL_ParsePlayerBeam(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), and CL_ParseWidow().
MSG_ReadShort()
int MSG_ReadShort (sizebuf_t * sb)
Definition at line 716 of file common.c.
 {
     int c;
     if (msg_read->readcount+2 > msg_read->cursize)
         c = -1;
     else
         c = (short)(msg_read->data[msg_read->readcount]
         + (msg_read->data[msg_read->readcount+1]<<8));
     msg_read->readcount += 2;
     return c;
 }
Referenced by CL_ParseBeam(), CL_ParseBeam2(), CL_ParseConfigString(), CL_ParseDelta(), CL_ParseDownload(), CL_ParseEntityBits(), CL_ParseInventory(), CL_ParseLightning(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_ParsePlayerBeam(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseStartSoundPacket(), CL_ParseSteam(), CL_ParseTEnt(), CL_ParseWidow(), MSG_ReadAngle16(), MSG_ReadCoord(), MSG_ReadDeltaUsercmd(), MSG_ReadPos(), Netchan_Process(), and SV_ReadPackets().
MSG_ReadString()
char* MSG_ReadString (sizebuf_t * sb)
Definition at line 773 of file common.c.
 {
     static char string[2048];
     int     l,c;
     l = 0;
     do
     {
         c = MSG_ReadChar (msg_read);
         if (c == -1 || c == 0)
             break;
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
Referenced by CL_ConnectionlessPacket(), CL_ParseConfigString(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseStatusMessage(), and SV_ExecuteClientMessage().
MSG_ReadStringLine()
char* MSG_ReadStringLine (sizebuf_t * sb)
Definition at line 793 of file common.c.
 {
     static char string[2048];
     int     l,c;
     l = 0;
     do
     {
         c = MSG_ReadChar (msg_read);
         if (c == -1 || c == 0 || c == '\n')
             break;
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
Referenced by CL_ConnectionlessPacket(), and SV_ConnectionlessPacket().
MSG_WriteAngle()
void MSG_WriteAngle (sizebuf_t * sb, float f)
Definition at line 376 of file common.c.
 {
     MSG_WriteByte (sb, (int)(f*256/360) & 255);
 }
Referenced by MSG_WriteDeltaEntity(), and PF_WriteAngle().
MSG_WriteAngle16()
void MSG_WriteAngle16 (sizebuf_t * sb, float f)
Definition at line 381 of file common.c.
 {
     MSG_WriteShort (sb, ANGLE2SHORT(f));
 }
Referenced by SV_WritePlayerstateToClient().
MSG_WriteByte()
void MSG_WriteByte (sizebuf_t * sb, int c)
Definition at line 303 of file common.c.
 {
     byte    *buf;
 #ifdef PARANOID
     if (c < 0 || c > 255)
         Com_Error (ERR_FATAL, "MSG_WriteByte: range error");
 #endif
     buf = SZ_GetSpace (sb, 1);
     buf[0] = c;
 }
Referenced by CL_CheckOrDownloadFile(), CL_Download_f(), CL_ForwardToServer_f(), CL_ParseDownload(), CL_Record_f(), CL_RequestNextDownload(), CL_SendCmd(), Cmd_ForwardToServer(), MSG_WriteAngle(), MSG_WriteDeltaEntity(), MSG_WriteDeltaUsercmd(), MSG_WriteDir(), PF_centerprintf(), PF_WriteByte(), SCR_FinishCinematic(), SV_Baselines_f(), SV_BeginDownload_f(), SV_BroadcastCommand(), SV_BroadcastPrintf(), SV_ClientPrintf(), SV_Configstrings_f(), SV_DropClient(), SV_EmitPacketEntities(), SV_FinalMessage(), SV_FlushRedirect(), SV_New_f(), SV_NextDownload_f(), SV_RecordDemoMessage(), SV_ServerRecord_f(), SV_StartSound(), SV_WriteFrameToClient(), and SV_WritePlayerstateToClient().
MSG_WriteChar()
void MSG_WriteChar (sizebuf_t * sb, int c)
Definition at line 290 of file common.c.
 {
     byte    *buf;
 #ifdef PARANOID
     if (c < -128 || c > 127)
         Com_Error (ERR_FATAL, "MSG_WriteChar: range error");
 #endif
     buf = SZ_GetSpace (sb, 1);
     buf[0] = c;
 }
Referenced by CL_ConnectionlessPacket(), CL_Reconnect_f(), PF_Configstring(), PF_WriteChar(), SV_FindIndex(), and SV_WritePlayerstateToClient().
MSG_WriteCoord()
void MSG_WriteCoord (sizebuf_t * sb, float f)
Definition at line 364 of file common.c.
 {
     MSG_WriteShort (sb, (int)(f*8));
 }
Referenced by MSG_WriteDeltaEntity().
MSG_WriteDeltaEntity()
void MSG_WriteDeltaEntity (struct entity_state_s * from, struct entity_state_s * to, sizebuf_t * msg, qboolean force, qboolean newentity)
Definition at line 483 of file common.c.
 {
     int     bits;
     if (!to->number)
         Com_Error (ERR_FATAL, "Unset entity number");
     if (to->number >= MAX_EDICTS)
         Com_Error (ERR_FATAL, "Entity number >= MAX_EDICTS");
 // send an update
     bits = 0;
     if (to->number >= 256)
         bits |= U_NUMBER16;     // number8 is implicit otherwise
     if (to->origin[0] != from->origin[0])
         bits |= U_ORIGIN1;
     if (to->origin[1] != from->origin[1])
         bits |= U_ORIGIN2;
     if (to->origin[2] != from->origin[2])
         bits |= U_ORIGIN3;
     if ( to->angles[0] != from->angles[0] )
         bits |= U_ANGLE1;
     if ( to->angles[1] != from->angles[1] )
         bits |= U_ANGLE2;
     if ( to->angles[2] != from->angles[2] )
         bits |= U_ANGLE3;
     if ( to->skinnum != from->skinnum )
     {
         if ((unsigned)to->skinnum < 256)
             bits |= U_SKIN8;
         else if ((unsigned)to->skinnum < 0x10000)
             bits |= U_SKIN16;
         else
             bits |= (U_SKIN8|U_SKIN16);
     }
     if ( to->frame != from->frame )
     {
         if (to->frame < 256)
             bits |= U_FRAME8;
         else
             bits |= U_FRAME16;
     }
     if ( to->effects != from->effects )
     {
         if (to->effects < 256)
             bits |= U_EFFECTS8;
         else if (to->effects < 0x8000)
             bits |= U_EFFECTS16;
         else
             bits |= U_EFFECTS8|U_EFFECTS16;
     }
     if ( to->renderfx != from->renderfx )
     {
         if (to->renderfx < 256)
             bits |= U_RENDERFX8;
         else if (to->renderfx < 0x8000)
             bits |= U_RENDERFX16;
         else
             bits |= U_RENDERFX8|U_RENDERFX16;
     }
     if ( to->solid != from->solid )
         bits |= U_SOLID;
     // event is not delta compressed, just 0 compressed
     if ( to->event  )
         bits |= U_EVENT;
     if ( to->modelindex != from->modelindex )
         bits |= U_MODEL;
     if ( to->modelindex2 != from->modelindex2 )
         bits |= U_MODEL2;
     if ( to->modelindex3 != from->modelindex3 )
         bits |= U_MODEL3;
     if ( to->modelindex4 != from->modelindex4 )
         bits |= U_MODEL4;
     if ( to->sound != from->sound )
         bits |= U_SOUND;
     if (newentity || (to->renderfx & RF_BEAM))
         bits |= U_OLDORIGIN;
     //
     // write the message
     //
     if (!bits && !force)
         return;     // nothing to send!
     //----------
     if (bits & 0xff000000)
         bits |= U_MOREBITS3 | U_MOREBITS2 | U_MOREBITS1;
     else if (bits & 0x00ff0000)
         bits |= U_MOREBITS2 | U_MOREBITS1;
     else if (bits & 0x0000ff00)
         bits |= U_MOREBITS1;
     MSG_WriteByte (msg, bits&255 );
     if (bits & 0xff000000)
     {
         MSG_WriteByte (msg, (bits>>8)&255 );
         MSG_WriteByte (msg, (bits>>16)&255 );
         MSG_WriteByte (msg, (bits>>24)&255 );
     }
     else if (bits & 0x00ff0000)
     {
         MSG_WriteByte (msg, (bits>>8)&255 );
         MSG_WriteByte (msg, (bits>>16)&255 );
     }
     else if (bits & 0x0000ff00)
     {
         MSG_WriteByte (msg, (bits>>8)&255 );
     }
     //----------
     if (bits & U_NUMBER16)
         MSG_WriteShort (msg, to->number);
     else
         MSG_WriteByte (msg, to->number);
     if (bits & U_MODEL)
         MSG_WriteByte (msg, to->modelindex);
     if (bits & U_MODEL2)
         MSG_WriteByte (msg, to->modelindex2);
     if (bits & U_MODEL3)
         MSG_WriteByte (msg, to->modelindex3);
     if (bits & U_MODEL4)
         MSG_WriteByte (msg, to->modelindex4);
     if (bits & U_FRAME8)
         MSG_WriteByte (msg, to->frame);
     if (bits & U_FRAME16)
         MSG_WriteShort (msg, to->frame);
     if ((bits & U_SKIN8) && (bits & U_SKIN16))      //used for laser colors
         MSG_WriteLong (msg, to->skinnum);
     else if (bits & U_SKIN8)
         MSG_WriteByte (msg, to->skinnum);
     else if (bits & U_SKIN16)
         MSG_WriteShort (msg, to->skinnum);
     if ( (bits & (U_EFFECTS8|U_EFFECTS16)) == (U_EFFECTS8|U_EFFECTS16) )
         MSG_WriteLong (msg, to->effects);
     else if (bits & U_EFFECTS8)
         MSG_WriteByte (msg, to->effects);
     else if (bits & U_EFFECTS16)
         MSG_WriteShort (msg, to->effects);
     if ( (bits & (U_RENDERFX8|U_RENDERFX16)) == (U_RENDERFX8|U_RENDERFX16) )
         MSG_WriteLong (msg, to->renderfx);
     else if (bits & U_RENDERFX8)
         MSG_WriteByte (msg, to->renderfx);
     else if (bits & U_RENDERFX16)
         MSG_WriteShort (msg, to->renderfx);
     if (bits & U_ORIGIN1)
         MSG_WriteCoord (msg, to->origin[0]);
     if (bits & U_ORIGIN2)
         MSG_WriteCoord (msg, to->origin[1]);
     if (bits & U_ORIGIN3)
         MSG_WriteCoord (msg, to->origin[2]);
     if (bits & U_ANGLE1)
         MSG_WriteAngle(msg, to->angles[0]);
     if (bits & U_ANGLE2)
         MSG_WriteAngle(msg, to->angles[1]);
     if (bits & U_ANGLE3)
         MSG_WriteAngle(msg, to->angles[2]);
     if (bits & U_OLDORIGIN)
     {
         MSG_WriteCoord (msg, to->old_origin[0]);
         MSG_WriteCoord (msg, to->old_origin[1]);
         MSG_WriteCoord (msg, to->old_origin[2]);
     }
     if (bits & U_SOUND)
         MSG_WriteByte (msg, to->sound);
     if (bits & U_EVENT)
         MSG_WriteByte (msg, to->event);
     if (bits & U_SOLID)
         MSG_WriteShort (msg, to->solid);
 }
Referenced by CL_Record_f(), SV_Baselines_f(), SV_EmitPacketEntities(), and SV_RecordDemoMessage().
MSG_WriteDeltaUsercmd()
void MSG_WriteDeltaUsercmd (sizebuf_t * sb, struct usercmd_s * from, struct usercmd_s * cmd)
Definition at line 387 of file common.c.
 {
     int     bits;
 //
 // send the movement message
 //
     bits = 0;
     if (cmd->angles[0] != from->angles[0])
         bits |= CM_ANGLE1;
     if (cmd->angles[1] != from->angles[1])
         bits |= CM_ANGLE2;
     if (cmd->angles[2] != from->angles[2])
         bits |= CM_ANGLE3;
     if (cmd->forwardmove != from->forwardmove)
         bits |= CM_FORWARD;
     if (cmd->sidemove != from->sidemove)
         bits |= CM_SIDE;
     if (cmd->upmove != from->upmove)
         bits |= CM_UP;
     if (cmd->buttons != from->buttons)
         bits |= CM_BUTTONS;
     if (cmd->impulse != from->impulse)
         bits |= CM_IMPULSE;
     MSG_WriteByte (buf, bits);
     if (bits & CM_ANGLE1)
         MSG_WriteShort (buf, cmd->angles[0]);
     if (bits & CM_ANGLE2)
         MSG_WriteShort (buf, cmd->angles[1]);
     if (bits & CM_ANGLE3)
         MSG_WriteShort (buf, cmd->angles[2]);
     if (bits & CM_FORWARD)
         MSG_WriteShort (buf, cmd->forwardmove);
     if (bits & CM_SIDE)
         MSG_WriteShort (buf, cmd->sidemove);
     if (bits & CM_UP)
         MSG_WriteShort (buf, cmd->upmove);
     if (bits & CM_BUTTONS)
         MSG_WriteByte (buf, cmd->buttons);
     if (bits & CM_IMPULSE)
         MSG_WriteByte (buf, cmd->impulse);
     MSG_WriteByte (buf, cmd->msec);
     MSG_WriteByte (buf, cmd->lightlevel);
 }
Referenced by CL_SendCmd().
MSG_WriteDir()
void MSG_WriteDir (sizebuf_t * sb, vec3_t vector)
Definition at line 438 of file common.c.
 {
     int     i, best;
     float   d, bestd;
     if (!dir)
     {
         MSG_WriteByte (sb, 0);
         return;
     }
     bestd = 0;
     best = 0;
     for (i=0 ; i<NUMVERTEXNORMALS ; i++)
     {
         d = DotProduct (dir, bytedirs[i]);
         if (d > bestd)
         {
             bestd = d;
             best = i;
         }
     }
     MSG_WriteByte (sb, best);
 }
Referenced by PF_WriteDir().
MSG_WriteFloat()
void MSG_WriteFloat (sizebuf_t * sb, float f)
Definition at line 341 of file common.c.
 {
     union
     {
         float   f;
         int l;
     } dat;
     dat.f = f;
     dat.l = LittleLong (dat.l);
     SZ_Write (sb, &dat.l, 4);
 }
Referenced by PF_WriteFloat().
MSG_WriteLong()
void MSG_WriteLong (sizebuf_t * sb, int c)
Definition at line 330 of file common.c.
 {
     byte    *buf;
     buf = SZ_GetSpace (sb, 4);
     buf[0] = c&0xff;
     buf[1] = (c>>8)&0xff;
     buf[2] = (c>>16)&0xff;
     buf[3] = c>>24;
 }
Referenced by CL_Record_f(), CL_SendCmd(), MSG_WriteDeltaEntity(), Netchan_OutOfBand(), Netchan_Transmit(), PF_WriteLong(), SV_New_f(), SV_RecordDemoMessage(), SV_ServerRecord_f(), SV_WriteFrameToClient(), and SV_WritePlayerstateToClient().
MSG_WritePos()
void MSG_WritePos (sizebuf_t * sb, vec3_t pos)
Definition at line 369 of file common.c.
 {
     MSG_WriteShort (sb, (int)(pos[0]*8));
     MSG_WriteShort (sb, (int)(pos[1]*8));
     MSG_WriteShort (sb, (int)(pos[2]*8));
 }
Referenced by PF_WritePos(), and SV_StartSound().
MSG_WriteShort()
void MSG_WriteShort (sizebuf_t * sb, int c)
Definition at line 316 of file common.c.
 {
     byte    *buf;
 #ifdef PARANOID
     if (c < ((short)0x8000) || c > (short)0x7fff)
         Com_Error (ERR_FATAL, "MSG_WriteShort: range error");
 #endif
     buf = SZ_GetSpace (sb, 2);
     buf[0] = c&0xff;
     buf[1] = c>>8;
 }
Referenced by CL_Record_f(), MSG_WriteAngle16(), MSG_WriteCoord(), MSG_WriteDeltaEntity(), MSG_WriteDeltaUsercmd(), MSG_WritePos(), Netchan_Transmit(), PF_Configstring(), PF_WriteShort(), SV_BeginDownload_f(), SV_Configstrings_f(), SV_EmitPacketEntities(), SV_FindIndex(), SV_New_f(), SV_NextDownload_f(), SV_RecordDemoMessage(), SV_ServerRecord_f(), SV_StartSound(), and SV_WritePlayerstateToClient().
MSG_WriteString()
void MSG_WriteString (sizebuf_t * sb, char * s)
Definition at line 356 of file common.c.
 {
     if (!s)
         SZ_Write (sb, "", 1);
     else
         SZ_Write (sb, s, (int)strlen(s)+1);
 }
Referenced by CL_CheckOrDownloadFile(), CL_ConnectionlessPacket(), CL_Download_f(), CL_Reconnect_f(), CL_Record_f(), CL_RequestNextDownload(), CL_SendCmd(), PF_centerprintf(), PF_Configstring(), PF_WriteString(), SV_Baselines_f(), SV_BroadcastCommand(), SV_BroadcastPrintf(), SV_ClientPrintf(), SV_Configstrings_f(), SV_FinalMessage(), SV_FindIndex(), SV_FlushRedirect(), SV_New_f(), and SV_ServerRecord_f().
NET_AdrToString()
char* NET_AdrToString (netadr_t a)
Definition at line 161 of file net_wins.c.
 {
     static  char    s[64];
     if (a.type == NA_LOOPBACK)
         Com_sprintf (s, sizeof(s), "loopback");
     else if (a.type == NA_IP)
         Com_sprintf (s, sizeof(s), "%i.%i.%i.%i:%i", a.ip[0], a.ip[1], a.ip[2], a.ip[3], ntohs(a.port));
     else
         Com_sprintf (s, sizeof(s), "%02x%02x%02x%02x:%02x%02x%02x%02x%02x%02x:%i", a.ipx[0], a.ipx[1], a.ipx[2], a.ipx[3], a.ipx[4], a.ipx[5], a.ipx[6], a.ipx[7], a.ipx[8], a.ipx[9], ntohs(a.port));
     return s;
 }
Referenced by CL_ConnectionlessPacket(), CL_ReadPackets(), JoinServerFunc(), Master_Heartbeat(), Master_Shutdown(), NET_GetPacket(), NET_SendPacket(), Netchan_Process(), Netchan_Transmit(), SV_ConnectionlessPacket(), SV_SetMaster_f(), SV_Status_f(), SVC_Ack(), SVC_DirectConnect(), and SVC_RemoteCommand().
NET_CompareAdr()
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
Definition at line 104 of file net_wins.c.
 {
     if (a.type != b.type)
         return false;
     if (a.type == NA_LOOPBACK)
         return TRUE;
     if (a.type == NA_IP)
     {
         if (a.ip[0] == b.ip[0] && a.ip[1] == b.ip[1] && a.ip[2] == b.ip[2] && a.ip[3] == b.ip[3] && a.port == b.port)
             return true;
         return false;
     }
     if (a.type == NA_IPX)
     {
         if ((memcmp(a.ipx, b.ipx, 10) == 0) && a.port == b.port)
             return true;
         return false;
     }
     return TRUE;
 }
Referenced by CL_ReadPackets().
NET_CompareBaseAdr()
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
Definition at line 136 of file net_wins.c.
 {
     if (a.type != b.type)
         return false;
     if (a.type == NA_LOOPBACK)
         return TRUE;
     if (a.type == NA_IP)
     {
         if (a.ip[0] == b.ip[0] && a.ip[1] == b.ip[1] && a.ip[2] == b.ip[2] && a.ip[3] == b.ip[3])
             return true;
         return false;
     }
     if (a.type == NA_IPX)
     {
         if ((memcmp(a.ipx, b.ipx, 10) == 0))
             return true;
         return false;
     }
     return TRUE;
 }
Referenced by SV_ReadPackets(), SVC_DirectConnect(), and SVC_GetChallenge().
NET_Config()
void NET_Config (qboolean multiplayer)
Definition at line 695 of file net_wins.c.
 {
     int     i;
     static  qboolean    old_config;
     if (old_config == multiplayer)
         return;
     old_config = multiplayer;
     if (!multiplayer)
     {   // shut down any existing sockets
         for (i=0 ; i<2 ; i++)
         {
             if (ip_sockets[i])
             {
                 closesocket (ip_sockets[i]);
                 ip_sockets[i] = 0;
             }
             if (ipx_sockets[i])
             {
                 closesocket (ipx_sockets[i]);
                 ipx_sockets[i] = 0;
             }
         }
     }
     else
     {   // open sockets
         if (! noudp->value)
             NET_OpenIP ();
         if (! noipx->value)
             NET_OpenIPX ();
     }
 }
Referenced by CL_Connect_f(), CL_Packet_f(), CL_PingServers_f(), CL_Rcon_f(), NET_Shutdown(), SV_InitGame(), and SV_KillServer_f().
NET_GetPacket()
qboolean NET_GetPacket (netsrc_t sock, netadr_t * net_from, sizebuf_t * net_message)
Definition at line 336 of file net_wins.c.
 {
     int     ret;
     struct sockaddr from;
     int     fromlen;
     int     net_socket;
     int     protocol;
     int     err;
     if (NET_GetLoopPacket (sock, net_from, net_message))
         return true;
     for (protocol = 0 ; protocol < 2 ; protocol++)
     {
         if (protocol == 0)
             net_socket = ip_sockets[sock];
         else
             net_socket = ipx_sockets[sock];
         if (!net_socket)
             continue;
         fromlen = sizeof(from);
         ret = recvfrom (net_socket, net_message->data, net_message->maxsize
             , 0, (struct sockaddr *)&from, &fromlen);
         SockadrToNetadr (&from, net_from);
         if (ret == -1)
         {
             err = WSAGetLastError();
             if (err == WSAEWOULDBLOCK)
                 continue;
             if (err == WSAEMSGSIZE) {
                 Com_Printf ("Warning:  Oversize packet from %s\n",
                         NET_AdrToString(*net_from));
                 continue;
             }
             if (dedicated->value)   // let dedicated servers continue after errors
                 Com_Printf ("NET_GetPacket: %s from %s\n", NET_ErrorString(),
                         NET_AdrToString(*net_from));
             else
                 Com_Error (ERR_DROP, "NET_GetPacket: %s from %s",
                         NET_ErrorString(), NET_AdrToString(*net_from));
             continue;
         }
         if (ret == net_message->maxsize)
         {
             Com_Printf ("Oversize packet from %s\n", NET_AdrToString (*net_from));
             continue;
         }
         net_message->cursize = ret;
         return true;
     }
     return false;
 }
Referenced by CL_DumpPackets(), CL_ReadPackets(), and SV_ReadPackets().
NET_Init()
void NET_Init (void)
Definition at line 767 of file net_wins.c.
 {
     WORD    wVersionRequested;
     int     r;
     wVersionRequested = MAKEWORD(1, 1);
     r = WSAStartup (MAKEWORD(1, 1), &winsockdata);
     if (r)
         Com_Error (ERR_FATAL,"Winsock initialization failed.");
     Com_Printf("Winsock Initialized\n");
     noudp = Cvar_Get ("noudp", "0", CVAR_NOSET);
     noipx = Cvar_Get ("noipx", "0", CVAR_NOSET);
     net_shownet = Cvar_Get ("net_shownet", "0", 0);
 }
Referenced by Qcommon_Init().
NET_IsLocalAddress()
qboolean NET_IsLocalAddress (netadr_t adr)
Definition at line 282 of file net_wins.c.
 {
     return adr.type == NA_LOOPBACK;
 }
Referenced by CL_ConnectionlessPacket(), and SVC_DirectConnect().
NET_SendPacket()
void NET_SendPacket (netsrc_t sock, int length, void * data, netadr_t to)
Definition at line 400 of file net_wins.c.
 {
     int     ret;
     struct sockaddr addr;
     int     net_socket;
     if ( to.type == NA_LOOPBACK )
     {
         NET_SendLoopPacket (sock, length, data, to);
         return;
     }
     if (to.type == NA_BROADCAST)
     {
         net_socket = ip_sockets[sock];
         if (!net_socket)
             return;
     }
     else if (to.type == NA_IP)
     {
         net_socket = ip_sockets[sock];
         if (!net_socket)
             return;
     }
     else if (to.type == NA_IPX)
     {
         net_socket = ipx_sockets[sock];
         if (!net_socket)
             return;
     }
     else if (to.type == NA_BROADCAST_IPX)
     {
         net_socket = ipx_sockets[sock];
         if (!net_socket)
             return;
     }
     else
         Com_Error (ERR_FATAL, "NET_SendPacket: bad address type");
     NetadrToSockadr (&to, &addr);
     ret = sendto (net_socket, data, length, 0, &addr, sizeof(addr) );
     if (ret == -1)
     {
         int err = WSAGetLastError();
         // wouldblock is silent
         if (err == WSAEWOULDBLOCK)
             return;
         // some PPP links dont allow broadcasts
         if ((err == WSAEADDRNOTAVAIL) && ((to.type == NA_BROADCAST) || (to.type == NA_BROADCAST_IPX)))
             return;
         if (dedicated->value)   // let dedicated servers continue after errors
         {
             Com_Printf ("NET_SendPacket ERROR: %s to %s\n", NET_ErrorString(),
                 NET_AdrToString (to));
         }
         else
         {
             if (err == WSAEADDRNOTAVAIL)
             {
                 Com_DPrintf ("NET_SendPacket Warning: %s : %s\n",
                         NET_ErrorString(), NET_AdrToString (to));
             }
             else
             {
                 Com_Error (ERR_DROP, "NET_SendPacket ERROR: %s to %s\n",
                         NET_ErrorString(), NET_AdrToString (to));
             }
         }
     }
 }
Referenced by CL_Packet_f(), CL_Rcon_f(), Netchan_OutOfBand(), and Netchan_Transmit().
NET_Shutdown()
void NET_Shutdown (void)
Definition at line 793 of file net_wins.c.
 {
     NET_Config (false); // close sockets
     WSACleanup ();
 }
NET_Sleep()
void NET_Sleep (int msec)
Definition at line 731 of file net_wins.c.
 {
     struct timeval timeout;
     fd_set  fdset;
     extern cvar_t *dedicated;
     int i;
     if (!dedicated || !dedicated->value)
         return; // we're not a server, just run full speed
     FD_ZERO(&fdset);
     i = 0;
     if (ip_sockets[NS_SERVER]) {
         FD_SET(ip_sockets[NS_SERVER], &fdset); // network socket
         i = ip_sockets[NS_SERVER];
     }
     if (ipx_sockets[NS_SERVER]) {
         FD_SET(ipx_sockets[NS_SERVER], &fdset); // network socket
         if (ipx_sockets[NS_SERVER] > i)
             i = ipx_sockets[NS_SERVER];
     }
     timeout.tv_sec = msec/1000;
     timeout.tv_usec = (msec%1000)*1000;
     select(i+1, &fdset, NULL, NULL, &timeout);
 }
Referenced by SV_Frame().
NET_StringToAdr()
qboolean NET_StringToAdr (char * s, netadr_t * a)
Definition at line 262 of file net_wins.c.
 {
     struct sockaddr sadr;
     if (!strcmp (s, "localhost"))
     {
         memset (a, 0, sizeof(*a));
         a->type = NA_LOOPBACK;
         return true;
     }
     if (!NET_StringToSockaddr (s, &sadr))
         return false;
     SockadrToNetadr (&sadr, a);
     return true;
 }
Referenced by CL_CheckForResend(), CL_Packet_f(), CL_PingServers_f(), CL_Rcon_f(), CL_SendConnectPacket(), SV_InitGame(), and SV_SetMaster_f().
Netchan_CanReliable()
qboolean Netchan_CanReliable (netchan_t * chan)
Definition at line 175 of file net_chan.c.
 {
     if (chan->reliable_length)
         return false;           // waiting for ack
     return true;
 }
Netchan_Init()
void Netchan_Init (void)
Definition at line 91 of file net_chan.c.
 {
     int     port;
     // pick a port value that should be nice and random
     port = Sys_Milliseconds() & 0xffff;
     showpackets = Cvar_Get ("showpackets", "0", 0);
     showdrop = Cvar_Get ("showdrop", "0", 0);
     qport = Cvar_Get ("qport", va("%i", port), CVAR_NOSET);
 }
Referenced by Qcommon_Init().
Netchan_NeedReliable()
qboolean Netchan_NeedReliable (netchan_t * chan)
Definition at line 183 of file net_chan.c.
 {
     qboolean    send_reliable;
 // if the remote side dropped the last reliable message, resend it
     send_reliable = false;
     if (chan->incoming_acknowledged > chan->last_reliable_sequence
     && chan->incoming_reliable_acknowledged != chan->reliable_sequence)
         send_reliable = true;
 // if the reliable transmit buffer is empty, copy the current message out
     if (!chan->reliable_length && chan->message.cursize)
     {
         send_reliable = true;
     }
     return send_reliable;
 }
Referenced by Netchan_Transmit().
Netchan_OutOfBand()
void Netchan_OutOfBand (int net_socket, netadr_t adr, int length, byte * data)
Definition at line 110 of file net_chan.c.
 {
     sizebuf_t   send;
     byte        send_buf[MAX_MSGLEN];
 // write the packet header
     SZ_Init (&send, send_buf, sizeof(send_buf));
     MSG_WriteLong (&send, -1);  // -1 sequence means out of band
     SZ_Write (&send, data, length);
 // send the datagram
     NET_SendPacket (net_socket, send.cursize, send.data, adr);
 }
Referenced by Netchan_OutOfBandPrint().
Netchan_OutOfBandPrint()
void Netchan_OutOfBandPrint (int net_socket, netadr_t adr, char * format, ...)
Definition at line 132 of file net_chan.c.
 {
     va_list     argptr;
     static char     string[MAX_MSGLEN - 4];
     va_start (argptr, format);
     vsnprintf (string,MAX_MSGLEN-4,format,argptr);
     va_end (argptr);
     Netchan_OutOfBand (net_socket, adr, (int)strlen(string), (byte *)string);
 }
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_PingServers_f(), CL_SendConnectPacket(), Master_Heartbeat(), Master_Shutdown(), SV_FlushRedirect(), SV_SetMaster_f(), SVC_DirectConnect(), SVC_GetChallenge(), SVC_Info(), SVC_Ping(), and SVC_Status().
Netchan_Process()
qboolean Netchan_Process (netchan_t * chan, sizebuf_t * msg)
Definition at line 298 of file net_chan.c.
 {
     unsigned    sequence, sequence_ack;
     unsigned    reliable_ack, reliable_message;
     int         qport;
 // get sequence numbers
     MSG_BeginReading (msg);
     sequence = MSG_ReadLong (msg);
     sequence_ack = MSG_ReadLong (msg);
     // read the qport if we are a server
     if (chan->sock == NS_SERVER)
         qport = MSG_ReadShort (msg);
     reliable_message = sequence >> 31;
     reliable_ack = sequence_ack >> 31;
     sequence &= ~(1<<31);
     sequence_ack &= ~(1<<31);
     if (showpackets->value)
     {
         if (reliable_message)
             Com_Printf ("recv %4i : s=%i reliable=%i ack=%i rack=%i\n"
                 , msg->cursize
                 , sequence
                 , chan->incoming_reliable_sequence ^ 1
                 , sequence_ack
                 , reliable_ack);
         else
             Com_Printf ("recv %4i : s=%i ack=%i rack=%i\n"
                 , msg->cursize
                 , sequence
                 , sequence_ack
                 , reliable_ack);
     }
 //
 // discard stale or duplicated packets
 //
     if (sequence <= chan->incoming_sequence)
     {
         if (showdrop->value)
             Com_Printf ("%s:Out of order packet %i at %i\n"
                 , NET_AdrToString (chan->remote_address)
                 ,  sequence
                 , chan->incoming_sequence);
         return false;
     }
 //
 // dropped packets don't keep the message from being used
 //
     chan->dropped = sequence - (chan->incoming_sequence+1);
     if (chan->dropped > 0)
     {
         if (showdrop->value)
             Com_Printf ("%s:Dropped %i packets at %i\n"
             , NET_AdrToString (chan->remote_address)
             , chan->dropped
             , sequence);
     }
 //
 // if the current outgoing reliable message has been acknowledged
 // clear the buffer to make way for the next
 //
     if (reliable_ack == chan->reliable_sequence)
         chan->reliable_length = 0;  // it has been received
 //
 // if this message contains a reliable message, bump incoming_reliable_sequence
 //
     chan->incoming_sequence = sequence;
     chan->incoming_acknowledged = sequence_ack;
     chan->incoming_reliable_acknowledged = reliable_ack;
     if (reliable_message)
     {
         chan->incoming_reliable_sequence ^= 1;
     }
 //
 // the message can now be read from the current message pointer
 //
     chan->last_received = curtime;
     return true;
 }
Referenced by CL_ReadPackets(), and SV_ReadPackets().
Netchan_Setup()
void Netchan_Setup (netsrc_t sock, netchan_t * chan, netadr_t adr, int qport)
Definition at line 152 of file net_chan.c.
 {
     memset (chan, 0, sizeof(*chan));
     chan->sock = sock;
     chan->remote_address = adr;
     chan->qport = qport;
     chan->last_received = curtime;
     chan->incoming_sequence = 0;
     chan->outgoing_sequence = 1;
     SZ_Init (&chan->message, chan->message_buf, sizeof(chan->message_buf));
     chan->message.allowoverflow = true;
 }
Referenced by CL_ConnectionlessPacket(), and SVC_DirectConnect().
Netchan_Transmit()
void Netchan_Transmit (netchan_t * chan, int length, byte * data)
Definition at line 213 of file net_chan.c.
 {
     sizebuf_t   send;
     byte        send_buf[MAX_MSGLEN];
     qboolean    send_reliable;
     unsigned    w1, w2;
 // check for message overflow
     if (chan->message.overflowed)
     {
         chan->fatal_error = true;
         Com_Printf ("%s:Outgoing message overflow\n"
             , NET_AdrToString (chan->remote_address));
         return;
     }
     send_reliable = Netchan_NeedReliable (chan);
     if (!chan->reliable_length && chan->message.cursize)
     {
         memcpy (chan->reliable_buf, chan->message_buf, chan->message.cursize);
         chan->reliable_length = chan->message.cursize;
         chan->message.cursize = 0;
         chan->reliable_sequence ^= 1;
     }
 // write the packet header
     SZ_Init (&send, send_buf, sizeof(send_buf));
     w1 = ( chan->outgoing_sequence & ~(1<<31) ) | (send_reliable<<31);
     w2 = ( chan->incoming_sequence & ~(1<<31) ) | (chan->incoming_reliable_sequence<<31);
     chan->outgoing_sequence++;
     chan->last_sent = curtime;
     MSG_WriteLong (&send, w1);
     MSG_WriteLong (&send, w2);
     // send the qport if we are a client
     if (chan->sock == NS_CLIENT)
         MSG_WriteShort (&send, qport->value);
 // copy the reliable message to the packet first
     if (send_reliable)
     {
         SZ_Write (&send, chan->reliable_buf, chan->reliable_length);
         chan->last_reliable_sequence = chan->outgoing_sequence;
     }
 // add the unreliable part if space is available
     if (send.maxsize - send.cursize >= length)
         SZ_Write (&send, data, length);
     else
         Com_Printf ("Netchan_Transmit: dumped unreliable\n");
 // send the datagram
     NET_SendPacket (chan->sock, send.cursize, send.data, chan->remote_address);
     if (showpackets->value)
     {
         if (send_reliable)
             Com_Printf ("send %4i : s=%i reliable=%i ack=%i rack=%i\n"
                 , send.cursize
                 , chan->outgoing_sequence - 1
                 , chan->reliable_sequence
                 , chan->incoming_sequence
                 , chan->incoming_reliable_sequence);
         else
             Com_Printf ("send %4i : s=%i ack=%i rack=%i\n"
                 , send.cursize
                 , chan->outgoing_sequence - 1
                 , chan->incoming_sequence
                 , chan->incoming_reliable_sequence);
     }
 }
Referenced by CL_Disconnect(), CL_SendCmd(), SV_FinalMessage(), SV_SendClientDatagram(), and SV_SendClientMessages().
Pmove()
void Pmove (pmove_t * pmove)
Definition at line 1240 of file pmove.c.
 {
     pm = pmove;
     // clear results
     pm->numtouch = 0;
     VectorClear (pm->viewangles);
     pm->viewheight = 0;
     pm->groundentity = 0;
     pm->watertype = 0;
     pm->waterlevel = 0;
     // clear all pmove local vars
     memset (&pml, 0, sizeof(pml));
     // convert origin and velocity to float values
     pml.origin[0] = pm->s.origin[0]*0.125;
     pml.origin[1] = pm->s.origin[1]*0.125;
     pml.origin[2] = pm->s.origin[2]*0.125;
     pml.velocity[0] = pm->s.velocity[0]*0.125;
     pml.velocity[1] = pm->s.velocity[1]*0.125;
     pml.velocity[2] = pm->s.velocity[2]*0.125;
     // save old org in case we get stuck
     VectorCopy (pm->s.origin, pml.previous_origin);
     pml.frametime = pm->cmd.msec * 0.001;
     PM_ClampAngles ();
     if (pm->s.pm_type == PM_SPECTATOR)
     {
         PM_FlyMove (false);
         PM_SnapPosition ();
         return;
     }
     if (pm->s.pm_type >= PM_DEAD)
     {
         pm->cmd.forwardmove = 0;
         pm->cmd.sidemove = 0;
         pm->cmd.upmove = 0;
     }
     if (pm->s.pm_type == PM_FREEZE)
         return;     // no movement at all
     // set mins, maxs, and viewheight
     PM_CheckDuck ();
     if (pm->snapinitial)
         PM_InitialSnapPosition ();
     // set groundentity, watertype, and waterlevel
     PM_CatagorizePosition ();
     if (pm->s.pm_type == PM_DEAD)
         PM_DeadMove ();
     PM_CheckSpecialMovement ();
     // drop timing counter
     if (pm->s.pm_time)
     {
         int     msec;
         msec = pm->cmd.msec >> 3;
         if (!msec)
             msec = 1;
         if ( msec >= pm->s.pm_time)
         {
             pm->s.pm_flags &= ~(PMF_TIME_WATERJUMP | PMF_TIME_LAND | PMF_TIME_TELEPORT);
             pm->s.pm_time = 0;
         }
         else
             pm->s.pm_time -= msec;
     }
     if (pm->s.pm_flags & PMF_TIME_TELEPORT)
     {   // teleport pause stays exactly in place
     }
     else if (pm->s.pm_flags & PMF_TIME_WATERJUMP)
     {   // waterjump has no control, but falls
         pml.velocity[2] -= pm->s.gravity * pml.frametime;
         if (pml.velocity[2] < 0)
         {   // cancel as soon as we are falling down again
             pm->s.pm_flags &= ~(PMF_TIME_WATERJUMP | PMF_TIME_LAND | PMF_TIME_TELEPORT);
             pm->s.pm_time = 0;
         }
         PM_StepSlideMove ();
     }
     else
     {
         PM_CheckJump ();
         PM_Friction ();
         if (pm->waterlevel >= 2)
             PM_WaterMove ();
         else {
             vec3_t  angles;
             VectorCopy(pm->viewangles, angles);
             if (angles[PITCH] > 180)
                 angles[PITCH] = angles[PITCH] - 360;
             angles[PITCH] /= 3;
             AngleVectors (angles, pml.forward, pml.right, pml.up);
             PM_AirMove ();
         }
     }
     // set groundentity, watertype, and waterlevel for final spot
     PM_CatagorizePosition ();
     PM_SnapPosition ();
 }
Referenced by CL_PredictMovement(), and SV_InitGameProgs().
Qcommon_Frame()
void Qcommon_Frame (int msec)
Definition at line 1500 of file common.c.
 {
     char    *s;
     int     time_before, time_between, time_after;
     if (setjmp (abortframe) )
     {
         if (shutdown_game)
             SV_ShutdownGameProgs();
         shutdown_game = false;
         return;         // an ERR_DROP was thrown
     }
     if ( log_stats->modified )
     {
         log_stats->modified = false;
         if ( log_stats->value )
         {
             if ( log_stats_file )
             {
                 fclose( log_stats_file );
                 log_stats_file = 0;
             }
             log_stats_file = fopen( "stats.log", "w" );
             if ( log_stats_file )
                 fprintf( log_stats_file, "entities,dlights,parts,frame time\n" );
         }
         else
         {
             if ( log_stats_file )
             {
                 fclose( log_stats_file );
                 log_stats_file = 0;
             }
         }
     }
     if (fixedtime->value)
         msec = fixedtime->value;
     else if (timescale->value)
     {
         msec *= timescale->value;
         if (msec < 1)
             msec = 1;
     }
     if (showtrace->value)
     {
         extern  int c_traces, c_brush_traces;
         extern  int c_pointcontents;
         Com_Printf ("%4i traces  %4i points\n", c_traces, c_pointcontents);
         c_traces = 0;
         c_brush_traces = 0;
         c_pointcontents = 0;
     }
     do
     {
         s = Sys_ConsoleInput ();
         if (s)
             Cbuf_AddText (va("%s\n",s));
     } while (s);
     Cbuf_Execute ();
     if (host_speeds->value)
         time_before = Sys_Milliseconds ();
     SV_Frame (msec);
     if (host_speeds->value)
         time_between = Sys_Milliseconds ();
     CL_Frame (msec);
     if (host_speeds->value)
         time_after = Sys_Milliseconds ();
     if (host_speeds->value)
     {
         int         all, sv, gm, cl, rf;
         all = time_after - time_before;
         sv = time_between - time_before;
         cl = time_after - time_between;
         gm = time_after_game - time_before_game;
         rf = time_after_ref - time_before_ref;
         sv -= gm;
         cl -= rf;
         Com_Printf ("all:%3i sv:%3i gm:%3i cl:%3i rf:%3i\n",
             all, sv, gm, cl, rf);
     }
 }
Referenced by WinMain().
Qcommon_Init()
void Qcommon_Init (int argc, char ** argv)
Definition at line 1407 of file common.c.
 {
     char    *s;
     if (setjmp (abortframe) )
         Sys_Error ("Error during initialization");
     z_chain.next = z_chain.prev = &z_chain;
     // prepare enough of the subsystems to handle
     // cvar and command buffer management
     COM_InitArgv (argc, argv);
     Swap_Init ();
     Cbuf_Init ();
     Cmd_Init ();
     Cvar_Init ();
     Key_Init ();
     // we need to add the early commands twice, because
     // a basedir or cddir needs to be set before execing
     // config files, but we want other parms to override
     // the settings of the config files
     Cbuf_AddEarlyCommands (false);
     Cbuf_Execute ();
     FS_InitFilesystem ();
     Cbuf_AddText ("exec default.cfg\n");
     Cbuf_AddText ("exec config.cfg\n");
     Cbuf_AddEarlyCommands (true);
     Cbuf_Execute ();
     //
     // init commands and vars
     //
     Cmd_AddCommand ("z_stats", Z_Stats_f);
     Cmd_AddCommand ("error", Com_Error_f);
     host_speeds = Cvar_Get ("host_speeds", "0", 0);
     log_stats = Cvar_Get ("log_stats", "0", 0);
     developer = Cvar_Get ("developer", "0", 0);
     timescale = Cvar_Get ("timescale", "1", 0);
     fixedtime = Cvar_Get ("fixedtime", "0", 0);
     logfile_active = Cvar_Get ("logfile", "0", 0);
     showtrace = Cvar_Get ("showtrace", "0", 0);
 #ifdef DEDICATED_ONLY
     dedicated = Cvar_Get ("dedicated", "1", CVAR_NOSET);
 #else
     dedicated = Cvar_Get ("dedicated", "0", CVAR_NOSET);
 #endif
     s = va("%4.2f %s %s %s", VERSION, CPUSTRING, __DATE__, BUILDSTRING);
     Cvar_Get ("version", s, CVAR_SERVERINFO|CVAR_NOSET);
     if (dedicated->value)
         Cmd_AddCommand ("quit", Com_Quit);
     Sys_Init ();
     NET_Init ();
     Netchan_Init ();
     SV_Init ();
     CL_Init ();
     // add + commands from command line
     if (!Cbuf_AddLateCommands ())
     {   // if the user didn't give any commands, run default action
         if (!dedicated->value)
             Cbuf_AddText ("d1\n");
         else
             Cbuf_AddText ("dedicated_start\n");
         Cbuf_Execute ();
     }
     else
     {   // the user asked for something explicit
         // so drop the loading plaque
         SCR_EndLoadingPlaque ();
     }
     Com_Printf ("====== Quake2 Initialized ======\n\n");
 }
Referenced by WinMain().
Qcommon_Shutdown()
void Qcommon_Shutdown (void)
Definition at line 1600 of file common.c.
 {
 }
Referenced by Sys_Error(), and Sys_Quit().
SCR_BeginLoadingPlaque()
void SCR_BeginLoadingPlaque (void)
Definition at line 562 of file cl_scrn.c.
 {
     S_StopAllSounds ();
     cl.sound_prepped = false;       // don't play ambients
     CDAudio_Stop ();
     Miniaudio_Stop ();
     if (cls.disable_screen)
         return;
     if (developer->value)
         return;
     if (cls.state == ca_disconnected)
         return; // if at console, don't bring up the plaque
     if (cls.key_dest == key_console)
         return;
     if (cl.cinematictime > 0)
         scr_draw_loading = 2;   // clear to balack first
     else
         scr_draw_loading = 1;
     SCR_UpdateScreen ();
     cls.disable_screen = Sys_Milliseconds ();
     cls.disable_servercount = cl.servercount;
 }
Referenced by CL_Changing_f(), SCR_RunCinematic(), SV_InitGame(), and SV_Map().
SCR_DebugGraph()
void SCR_DebugGraph (float value, int color)
Definition at line 137 of file cl_scrn.c.
 {
     values[current&1023].value = value;
     values[current&1023].color = color;
     current++;
 }
SV_Frame()
void SV_Frame (int msec)
Definition at line 760 of file sv_main.c.
 {
     time_before_game = time_after_game = 0;
     // if server is not active, do nothing
     if (!svs.initialized)
         return;
     svs.realtime += msec;
     // keep the random time dependent
     rand ();
     // check timeouts
     SV_CheckTimeouts ();
     // get packets from clients
     SV_ReadPackets ();
     // move autonomous things around if enough time has passed
     if (!sv_timedemo->value && svs.realtime < sv.time)
     {
         // never let the time get too far off
         if (sv.time - svs.realtime > 100)
         {
             if (sv_showclamp->value)
                 Com_Printf ("sv lowclamp\n");
             svs.realtime = sv.time - 100;
         }
         NET_Sleep(sv.time - svs.realtime);
         return;
     }
     // update ping based on the last known frame from all clients
     SV_CalcPings ();
     // give the clients some timeslices
     SV_GiveMsec ();
     // let everything in the world think and move
     SV_RunGameFrame ();
     // send messages back to the clients that had packets read this frame
     SV_SendClientMessages ();
     // save the entire world state if recording a serverdemo
     SV_RecordDemoMessage ();
     // send a heartbeat to the master if needed
     Master_Heartbeat ();
     // clear teleport flags, etc for next frame
     SV_PrepWorldFrame ();
 }
Referenced by Qcommon_Frame().
SV_Init()
void SV_Init (void)
Definition at line 948 of file sv_main.c.
 {
     SV_InitOperatorCommands ();
     rcon_password = Cvar_Get ("rcon_password", "", 0);
     Cvar_Get ("skill", "1", 0);
     Cvar_Get ("deathmatch", "0", CVAR_LATCH);
     Cvar_Get ("coop", "0", CVAR_LATCH);
     Cvar_Get ("dmflags", va("%i", DF_INSTANT_ITEMS), CVAR_SERVERINFO);
     Cvar_Get ("fraglimit", "0", CVAR_SERVERINFO);
     Cvar_Get ("timelimit", "0", CVAR_SERVERINFO);
     Cvar_Get ("cheats", "0", CVAR_SERVERINFO|CVAR_LATCH);
     Cvar_Get ("protocol", va("%i", PROTOCOL_VERSION), CVAR_SERVERINFO|CVAR_NOSET);;
     maxclients = Cvar_Get ("maxclients", "1", CVAR_SERVERINFO | CVAR_LATCH);
     hostname = Cvar_Get ("hostname", "noname", CVAR_SERVERINFO | CVAR_ARCHIVE);
     msg_timeout = Cvar_Get ("timeout", "125", 0);
     zombietime = Cvar_Get ("zombietime", "2", 0);
     sv_showclamp = Cvar_Get ("showclamp", "0", 0);
     sv_paused = Cvar_Get ("paused", "0", 0);
     sv_timedemo = Cvar_Get ("timedemo", "0", 0);
     sv_enforcetime = Cvar_Get ("sv_enforcetime", "0", 0);
     allow_download = Cvar_Get ("allow_download", "1", CVAR_ARCHIVE);
     allow_download_players  = Cvar_Get ("allow_download_players", "0", CVAR_ARCHIVE);
     allow_download_models = Cvar_Get ("allow_download_models", "1", CVAR_ARCHIVE);
     allow_download_sounds = Cvar_Get ("allow_download_sounds", "1", CVAR_ARCHIVE);
     allow_download_maps   = Cvar_Get ("allow_download_maps", "1", CVAR_ARCHIVE);
     sv_noreload = Cvar_Get ("sv_noreload", "0", 0);
     sv_airaccelerate = Cvar_Get("sv_airaccelerate", "0", CVAR_LATCH);
     public_server = Cvar_Get ("public", "0", 0);
     sv_reconnect_limit = Cvar_Get ("sv_reconnect_limit", "3", CVAR_ARCHIVE);
     SZ_Init (&net_message, net_message_buffer, sizeof(net_message_buffer));
 }
Referenced by Qcommon_Init().
SV_Shutdown()
void SV_Shutdown (char * finalmsg, qboolean reconnect)
Definition at line 1035 of file sv_main.c.
 {
     if (svs.clients)
         SV_FinalMessage (finalmsg, reconnect);
     Master_Shutdown ();
     // calling this function here causes function stack to be corrupted on 64 bit builds when invoked from Com_Error()
     //SV_ShutdownGameProgs ();
     // free current level
     if (sv.demofile)
         fclose (sv.demofile);
     memset (&sv, 0, sizeof(sv));
     Com_SetServerState (sv.state);
     // free server static data
     if (svs.clients)
         Z_Free (svs.clients);
     if (svs.client_entities)
         Z_Free (svs.client_entities);
     if (svs.demofile)
         fclose (svs.demofile);
     memset (&svs, 0, sizeof(svs));
 }
Referenced by CL_Connect_f(), Com_Error(), Com_Quit(), SV_InitGame(), and SV_KillServer_f().
Sys_AppActivate()
void Sys_AppActivate (void)
Definition at line 467 of file sys_win.c.
 {
     ShowWindow ( cl_hwnd, SW_RESTORE);
     SetForegroundWindow ( cl_hwnd );
 }
Referenced by CL_ConnectionlessPacket().
Sys_ConsoleInput()
char* Sys_ConsoleInput (void)
Definition at line 289 of file sys_win.c.
 {
     INPUT_RECORD    recs[1024];
     int     dummy;
     int     ch, numread, numevents;
     if (!dedicated || !dedicated->value)
         return NULL;
     for ( ;; )
     {
         if (!GetNumberOfConsoleInputEvents (hinput, &numevents))
             Sys_Error ("Error getting # of console events");
         if (numevents <= 0)
             break;
         if (!ReadConsoleInput(hinput, recs, 1, &numread))
             Sys_Error ("Error reading console input");
         if (numread != 1)
             Sys_Error ("Couldn't read console input");
         if (recs[0].EventType == KEY_EVENT)
         {
             if (!recs[0].Event.KeyEvent.bKeyDown)
             {
                 ch = recs[0].Event.KeyEvent.uChar.AsciiChar;
                 switch (ch)
                 {
                     case '\r':
                         WriteFile(houtput, "\r\n", 2, &dummy, NULL);
                         if (console_textlen)
{
                             console_text[console_textlen] = 0;
                             console_textlen = 0;
                             return console_text;
                         }
                         break;
                     case '\b':
                         if (console_textlen)
{
                             console_textlen--;
                             WriteFile(houtput, "\b \b", 3, &dummy, NULL);
                         }
                         break;
                     default:
                         if (ch >= ' ')
{
                             if (console_textlen < sizeof(console_text)-2)
{
                                 WriteFile(houtput, &ch, 1, &dummy, NULL);
                                 console_text[console_textlen] = ch;
                                 console_textlen++;
                             }
                         }
                         break;
                 }
             }
         }
     }
     return NULL;
 }
Referenced by Qcommon_Frame().
Sys_ConsoleOutput()
void Sys_ConsoleOutput (char * string)
Definition at line 369 of file sys_win.c.
 {
     int     dummy;
     char    text[256];
     if (!dedicated || !dedicated->value)
     {
 #ifdef WIN_DEBUG_CONSOLE
         fputs(string, stderr);
         OutputDebugString(string);
 #endif
         return;
     }
     if (console_textlen)
     {
         text[0] = '\r';
         memset(&text[1], ' ', console_textlen);
         text[console_textlen+1] = '\r';
         text[console_textlen+2] = 0;
         WriteFile(houtput, text, console_textlen+2, &dummy, NULL);
     }
     WriteFile(houtput, string, (DWORD)strlen(string), &dummy, NULL);
     if (console_textlen)
         WriteFile(houtput, console_text, console_textlen, &dummy, NULL);
 }
Referenced by Com_Printf().
Sys_CopyProtect()
void Sys_CopyProtect (void)
Definition at line 191 of file sys_win.c.
 {
 #ifndef DEMO
     char    *cddir;
     cddir = Sys_ScanForCD();
     if (!cddir[0])
         Com_Error (ERR_FATAL, "You must have the Quake2 CD in the drive to play.");
 #endif
 }
Referenced by SV_InitGame().
Sys_Error()
void Sys_Error (char * error, ...)
Definition at line 68 of file sys_win.c.
 {
     va_list     argptr;
     char        text[1024];
     CL_Shutdown ();
     Qcommon_Shutdown ();
     va_start (argptr, error);
     vsnprintf (text, 1024, error, argptr);
     va_end (argptr);
     MessageBox(NULL, text, "Error", 0 /* MB_OK */ );
     if (qwclsemaphore)
         CloseHandle (qwclsemaphore);
 // shut down QHOST hooks if necessary
     DeinitConProc ();
     exit (1);
 }
Referenced by COM_BlockSequenceCheckByte(), COM_BlockSequenceCRCByte(), Com_Error(), Hunk_Alloc(), Hunk_Begin(), Hunk_End(), Qcommon_Init(), QVk_BeginFrame(), QVk_EndFrame(), QVk_GetStagingBuffer(), and Sys_FindFirst().
Sys_GetClipboardData()
char* Sys_GetClipboardData (void)
Definition at line 431 of file sys_win.c.
 {
     char *data = NULL;
     char *cliptext;
     if ( OpenClipboard( NULL ) != 0 )
     {
         HANDLE hClipboardData;
         if ( ( hClipboardData = GetClipboardData( CF_TEXT ) ) != 0 )
         {
             if ( ( cliptext = GlobalLock( hClipboardData ) ) != 0 )
             {
                 data = malloc( GlobalSize( hClipboardData ) + 1 );
                 strcpy( data, cliptext );
                 GlobalUnlock( hClipboardData );
             }
         }
         CloseClipboard();
     }
     return data;
 }
Referenced by Field_Key(), and Key_Console().
Sys_GetGameAPI()
void* Sys_GetGameAPI (void * parms)
Definition at line 502 of file sys_win.c.
 {
     void    *(*GetGameAPI) (void *);
     char    name[MAX_OSPATH];
     char    *path;
     char    cwd[MAX_OSPATH];
 #if defined _M_IX86
     const char *gamename = "gamex86.dll";
 #ifdef NDEBUG
     const char *debugdir = "release";
 #else
     const char *debugdir = "debug";
 #endif
 #elif defined _M_X64
     const char *gamename = "gamex64.dll";
 #ifdef NDEBUG
     const char *debugdir = "releasex64";
 #else
     const char *debugdir = "debugx64";
 #endif
 #elif defined _M_ALPHA
     const char *gamename = "gameaxp.dll";
 #ifdef NDEBUG
     const char *debugdir = "releaseaxp";
 #else
     const char *debugdir = "debugaxp";
 #endif
 #endif
     if (game_library)
         Com_Error (ERR_FATAL, "Sys_GetGameAPI without Sys_UnloadingGame");
     // check the current debug directory first for development purposes
     _getcwd (cwd, sizeof(cwd));
     Com_sprintf (name, sizeof(name), "%s/%s/%s", cwd, debugdir, gamename);
     game_library = LoadLibrary ( name );
     if (game_library)
     {
         Com_DPrintf ("LoadLibrary (%s)\n", name);
     }
     else
     {
 #ifdef DEBUG
         // check the current directory for other development purposes
         Com_sprintf (name, sizeof(name), "%s/%s", cwd, gamename);
         game_library = LoadLibrary ( name );
         if (game_library)
         {
             Com_DPrintf ("LoadLibrary (%s)\n", name);
         }
         else
 #endif
         {
             // now run through the search paths
             path = NULL;
             while (1)
             {
                 path = FS_NextPath (path);
                 if (!path)
                     return NULL;        // couldn't find one anywhere
                 Com_sprintf (name, sizeof(name), "%s/%s", path, gamename);
                 game_library = LoadLibrary (name);
                 if (game_library)
                 {
                     Com_DPrintf ("LoadLibrary (%s)\n",name);
                     break;
                 }
             }
         }
     }
     GetGameAPI = (void *)GetProcAddress (game_library, "GetGameAPI");
     if (!GetGameAPI)
     {
         Sys_UnloadGame ();
         return NULL;
     }
     return GetGameAPI (parms);
 }
Referenced by SV_InitGameProgs().
Sys_Init()
void Sys_Init (void)
Definition at line 238 of file sys_win.c.
 {
     OSVERSIONINFO   vinfo;
     timeBeginPeriod( 1 );
     vinfo.dwOSVersionInfoSize = sizeof(vinfo);
     if (!GetVersionEx (&vinfo))
         Sys_Error ("Couldn't get OS info");
     if (vinfo.dwMajorVersion < 4)
         Sys_Error ("Quake2 requires windows version 4 or greater");
     if (vinfo.dwPlatformId == VER_PLATFORM_WIN32s)
         Sys_Error ("Quake2 doesn't run on Win32s");
     else if ( vinfo.dwPlatformId == VER_PLATFORM_WIN32_WINDOWS )
         s_win95 = true;
     if (dedicated->value)
     {
         if (!AllocConsole ())
             Sys_Error ("Couldn't create dedicated server console");
         hinput = GetStdHandle (STD_INPUT_HANDLE);
         houtput = GetStdHandle (STD_OUTPUT_HANDLE);
         // let QHOST hook in
         InitConProc (argc, argv);
     }
 #ifdef WIN_DEBUG_CONSOLE
     else
     {
         AllocConsole();
         SetConsoleMode(GetStdHandle(STD_OUTPUT_HANDLE), 0x07);
         DeleteMenu(GetSystemMenu(GetConsoleWindow(), false), SC_CLOSE, MF_BYCOMMAND);
         freopen("CONOUT$", "w", stderr);
     }
 #endif
     // enable DPI awareness
     Sys_SetDPIAwareness();
 }
Referenced by Qcommon_Init().
Sys_Quit()
void Sys_Quit (void)
Definition at line 91 of file sys_win.c.
 {
     timeEndPeriod( 1 );
     CL_Shutdown();
     Qcommon_Shutdown ();
     CloseHandle (qwclsemaphore);
     if (dedicated && dedicated->value)
         FreeConsole ();
 #ifdef WIN_DEBUG_CONSOLE
     else
         FreeConsole();
 #endif
 // shut down QHOST hooks if necessary
     DeinitConProc ();
     exit (0);
 }
Referenced by Com_Quit(), and Sys_SendKeyEvents().
Sys_SendKeyEvents()
void Sys_SendKeyEvents (void)
Definition at line 406 of file sys_win.c.
 {
     MSG        msg;
     while (PeekMessage (&msg, NULL, 0, 0, PM_NOREMOVE))
     {
         if (!GetMessage (&msg, NULL, 0, 0))
             Sys_Quit ();
         sys_msg_time = msg.time;
         TranslateMessage (&msg);
         DispatchMessage (&msg);
     }
     // grab frame time
     sys_frame_time = timeGetTime(); // FIXME: should this be at start?
 }
Referenced by CL_PrepRefresh(), CL_RegisterSounds(), CL_SendCommand(), CL_Skins_f(), and Key_GetKey().
Sys_UnloadGame()
void Sys_UnloadGame (void)
Definition at line 488 of file sys_win.c.
 {
     if (!FreeLibrary (game_library))
         Com_Error (ERR_FATAL, "FreeLibrary failed for game library");
     game_library = NULL;
 }
Referenced by SV_ShutdownGameProgs(), and Sys_GetGameAPI().
SZ_Clear()
void SZ_Clear (sizebuf_t * buf)
Definition at line 892 of file common.c.
 {
     buf->cursize = 0;
     buf->overflowed = false;
 }
Referenced by Cbuf_InsertText(), CL_ClearState(), PF_Configstring(), PF_Unicast(), SV_FinalMessage(), SV_FindIndex(), SV_Multicast(), SV_RecordDemoMessage(), SV_SendClientDatagram(), SV_SendClientMessages(), and SZ_GetSpace().
SZ_GetSpace()
void* SZ_GetSpace (sizebuf_t * buf, int length)
Definition at line 898 of file common.c.
 {
     void    *data;
     if (buf->cursize + length > buf->maxsize)
     {
         if (!buf->allowoverflow)
             Com_Error (ERR_FATAL, "SZ_GetSpace: overflow without allowoverflow set");
         if (length > buf->maxsize)
             Com_Error (ERR_FATAL, "SZ_GetSpace: %i is > full buffer size", length);
         Com_Printf ("SZ_GetSpace: overflow\n");
         SZ_Clear (buf);
         buf->overflowed = true;
     }
     data = buf->data + buf->cursize;
     buf->cursize += length;
     return data;
 }
Referenced by MSG_WriteByte(), MSG_WriteChar(), MSG_WriteLong(), MSG_WriteShort(), SZ_Print(), and SZ_Write().
SZ_Init()
void SZ_Init (sizebuf_t * buf, byte * data, int length)
Definition at line 885 of file common.c.
 {
     memset (buf, 0, sizeof(*buf));
     buf->data = data;
     buf->maxsize = length;
 }
Referenced by Cbuf_Init(), CL_Record_f(), CL_SendCmd(), Netchan_OutOfBand(), Netchan_Setup(), Netchan_Transmit(), SV_Init(), SV_RecordDemoMessage(), SV_SendClientDatagram(), SV_ServerRecord_f(), SV_SpawnServer(), and SVC_DirectConnect().
SZ_Print()
void SZ_Print (sizebuf_t * buf, char * data)
Definition at line 926 of file common.c.
 {
     int     len;
     len = (int)strlen(data)+1;
     if (buf->cursize)
     {
         if (buf->data[buf->cursize-1])
             memcpy ((byte *)SZ_GetSpace(buf, len),data,len); // no trailing 0
         else
             memcpy ((byte *)SZ_GetSpace(buf, len-1)-1,data,len); // write over trailing 0
     }
     else
         memcpy ((byte *)SZ_GetSpace(buf, len),data,len);
 }
Referenced by CL_ForwardToServer_f(), CL_ParseDownload(), Cmd_ForwardToServer(), and SCR_FinishCinematic().
SZ_Write()
void SZ_Write (sizebuf_t * buf, void * data, int length)
Definition at line 921 of file common.c.
 {
     memcpy (SZ_GetSpace(buf,length),data,length);
 }
Referenced by Cbuf_AddText(), Cbuf_InsertText(), MSG_WriteFloat(), MSG_WriteString(), Netchan_OutOfBand(), Netchan_Transmit(), PF_Unicast(), SV_Multicast(), SV_NextDownload_f(), SV_RecordDemoMessage(), SV_SendClientDatagram(), and SV_WriteFrameToClient().
Z_Free()
void Z_Free (void * ptr)
Definition at line 1122 of file common.c.
 {
     zhead_t *z;
     z = ((zhead_t *)ptr) - 1;
     if (z->magic != Z_MAGIC)
         Com_Error (ERR_FATAL, "Z_Free: bad magic");
     z->prev->next = z->next;
     z->next->prev = z->prev;
     z_count--;
     z_bytes -= z->size;
     free (z);
 }
Referenced by Cbuf_AddLateCommands(), Cbuf_InsertText(), Cmd_Alias_f(), Cmd_Exec_f(), Cmd_RemoveCommand(), Cmd_TokenizeString(), Cvar_FullSet(), Cvar_GetLatchedVars(), Cvar_Set2(), FS_FreeFile(), FS_Link_f(), FS_SetGamedir(), Key_SetBinding(), S_EndRegistration(), S_Shutdown(), SCR_LoadPCX(), SCR_PlayCinematic(), SCR_RunCinematic(), SCR_StopCinematic(), SV_InitGameProgs(), SV_Shutdown(), and Z_FreeTags().
Z_FreeTags()
void Z_FreeTags (int tag)
Definition at line 1155 of file common.c.
 {
     zhead_t *z, *next;
     for (z=z_chain.next ; z != &z_chain ; z=next)
     {
         next = z->next;
         if (z->tag == tag)
             Z_Free ((void *)(z+1));
     }
 }
Referenced by SV_InitGameProgs().
Z_Malloc()
void* Z_Malloc (int size)
Definition at line 1200 of file common.c.
 {
     return Z_TagMalloc (size, 0);
 }
Referenced by Cbuf_AddLateCommands(), Cbuf_InsertText(), Cmd_AddCommand(), Cmd_Alias_f(), Cmd_Exec_f(), Cmd_TokenizeString(), CopyString(), Cvar_Get(), FS_AddGameDirectory(), FS_Link_f(), FS_LoadFile(), FS_LoadPackFile(), Huff1Decompress(), Huff1TableInit(), Key_SetBinding(), S_AliasName(), S_LoadSound(), SCR_LoadPCX(), and SV_InitGame().
Z_TagMalloc()
void* Z_TagMalloc (int size, int tag)
Definition at line 1172 of file common.c.
 {
     zhead_t *z;
     size = size + sizeof(zhead_t);
     z = malloc(size);
     if (!z)
         Com_Error (ERR_FATAL, "Z_Malloc: failed on allocation of %i bytes",size);
     memset (z, 0, size);
     z_count++;
     z_bytes += size;
     z->magic = Z_MAGIC;
     z->tag = tag;
     z->size = size;
     z->next = z_chain.next;
     z->prev = &z_chain;
     z_chain.next->prev = z;
     z_chain.next = z;
     return (void *)(z+1);
 }
Referenced by SV_InitGameProgs(), and Z_Malloc().
Variable Documentation
bigendien
qboolean bigendien
Definition at line 934 of file q_shared.c.
Referenced by Swap_Init().
bytedirs
vec3_t bytedirs[NUMVERTEXNORMALS]
Definition at line 281 of file common.c.
Referenced by CL_BfgParticles(), CL_FlyParticles(), COM_BlockSequenceCheckByte(), MSG_ReadDir(), and MSG_WriteDir().
cvar_vars
cvar_t* cvar_vars
Definition at line 24 of file cvar.c.
Referenced by Cvar_BitInfo(), Cvar_CompleteVariable(), Cvar_FindVar(), Cvar_Get(), Cvar_GetLatchedVars(), Cvar_List_f(), Cvar_WriteVariables(), and SV_WriteServerFile().
dedicated
cvar_t* dedicated
Definition at line 47 of file common.c.
developer
cvar_t* developer
Definition at line 42 of file common.c.
Referenced by Com_DPrintf(), Qcommon_Init(), and SCR_BeginLoadingPlaque().
host_speeds
cvar_t* host_speeds
Definition at line 40 of file common.c.
Referenced by CL_Frame(), Qcommon_Frame(), Qcommon_Init(), and SV_RunGameFrame().
log_stats
cvar_t* log_stats
Definition at line 41 of file common.c.
Referenced by CL_Frame(), Qcommon_Frame(), Qcommon_Init(), and V_RenderView().
log_stats_file
FILE* log_stats_file
Definition at line 38 of file common.c.
Referenced by CL_Frame(), Qcommon_Frame(), and V_RenderView().
net_from
netadr_t net_from
Definition at line 81 of file net_chan.c.
net_message
sizebuf_t net_message
Definition at line 82 of file net_chan.c.
net_message_buffer
byte net_message_buffer[MAX_MSGLEN]
Definition at line 83 of file net_chan.c.
Referenced by CL_Init(), and SV_Init().
pm_airaccelerate
float pm_airaccelerate
Definition at line 57 of file pmove.c.
Referenced by CL_PredictMovement(), PM_AirMove(), and SV_SpawnServer().
time_after_game
int time_after_game
Definition at line 55 of file common.c.
Referenced by Qcommon_Frame(), SV_Frame(), and SV_RunGameFrame().
time_after_ref
int time_after_ref
Definition at line 57 of file common.c.
Referenced by CL_Frame(), and Qcommon_Frame().
time_before_game
int time_before_game
Definition at line 54 of file common.c.
Referenced by Qcommon_Frame(), SV_Frame(), and SV_RunGameFrame().
time_before_ref
int time_before_ref
Definition at line 56 of file common.c.
Referenced by CL_Frame(), and Qcommon_Frame().
userinfo_modified
qboolean userinfo_modified
Definition at line 485 of file cvar.c.
Referenced by CL_SendCmd(), CL_SendConnectPacket(), Cvar_FullSet(), and Cvar_Set2().