vq2 doxygen: C:/entry/syn/github/vq2/win32/conproc.c File Reference
conproc.c File Reference
#include <stdio.h>
#include <process.h>
#include <windows.h>
#include "conproc.h"
Macros
#define CCOM_WRITE_TEXT 0x2
#define CCOM_GET_TEXT 0x3
#define CCOM_GET_SCR_LINES 0x4
#define CCOM_SET_SCR_LINES 0x5
Functions
unsigned _stdcall RequestProc (void *arg)
LPVOID GetMappedBuffer (HANDLE hfileBuffer)
void ReleaseMappedBuffer (LPVOID pBuffer)
BOOL GetScreenBufferLines (int *piLines)
BOOL SetScreenBufferLines (int iLines)
BOOL ReadText (LPTSTR pszText, int iBeginLine, int iEndLine)
BOOL WriteText (LPCTSTR szText)
int CharToCode (char c)
BOOL SetConsoleCXCY (HANDLE hStdout, int cx, int cy)
int CCheckParm (char *parm)
void InitConProc (int argc, char **argv)
void DeinitConProc (void)
Variables
HANDLE heventDone
HANDLE hfileBuffer
HANDLE heventChildSend
HANDLE heventParentSend
HANDLE hStdout
HANDLE hStdin
int ccom_argc
char ** ccom_argv
Macro Definition Documentation
CCOM_GET_SCR_LINES
#define CCOM_GET_SCR_LINES 0x4
Definition at line 33 of file conproc.c.
CCOM_GET_TEXT
#define CCOM_GET_TEXT 0x3
Definition at line 29 of file conproc.c.
CCOM_SET_SCR_LINES
#define CCOM_SET_SCR_LINES 0x5
Definition at line 36 of file conproc.c.
CCOM_WRITE_TEXT
#define CCOM_WRITE_TEXT 0x2
Definition at line 26 of file conproc.c.
Function Documentation
CCheckParm()
int CCheckParm (char * parm)
Definition at line 68 of file conproc.c.
 {
     int             i;
     for (i=1 ; i<ccom_argc ; i++)
     {
         if (!ccom_argv[i])
             continue;
         if (!strcmp (parm,ccom_argv[i]))
             return i;
     }
     return 0;
 }
Referenced by InitConProc().
CharToCode()
int CharToCode (char c)
Definition at line 331 of file conproc.c.
 {
     char upper;
     upper = toupper(c);
     switch (c)
     {
         case 13:
             return 28;
         default:
             break;
     }
     if (isalpha(c))
         return (30 + upper - 65);
     if (isdigit(c))
         return (1 + upper - 47);
     return c;
 }
Referenced by WriteText().
DeinitConProc()
void DeinitConProc (void)
Definition at line 153 of file conproc.c.
 {
     if (heventDone)
         SetEvent (heventDone);
 }
Referenced by Sys_Error(), and Sys_Quit().
GetMappedBuffer()
LPVOID GetMappedBuffer (HANDLE hfileBuffer)
Definition at line 223 of file conproc.c.
 {
     LPVOID pBuffer;
     pBuffer = MapViewOfFile (hfileBuffer,
                             FILE_MAP_READ | FILE_MAP_WRITE, 0, 0, 0);
     return pBuffer;
 }
Referenced by RequestProc().
GetScreenBufferLines()
BOOL GetScreenBufferLines (int * piLines)
Definition at line 240 of file conproc.c.
 {
     CONSOLE_SCREEN_BUFFER_INFO  info;
     BOOL                        bRet;
     bRet = GetConsoleScreenBufferInfo (hStdout, &info);
     if (bRet)
         *piLines = info.dwSize.Y;
     return bRet;
 }
Referenced by RequestProc().
InitConProc()
void InitConProc (int argc, char ** argv)
Definition at line 84 of file conproc.c.
 {
     unsigned    threadAddr;
     HANDLE      hFile;
     HANDLE      heventParent;
     HANDLE      heventChild;
     int         t;
     ccom_argc = argc;
     ccom_argv = argv;
 // give QHOST a chance to hook into the console
     if ((t = CCheckParm ("-HFILE")) > 0)
     {
         if (t < argc)
             hFile = (HANDLE)atoi (ccom_argv[t+1]);
     }
     if ((t = CCheckParm ("-HPARENT")) > 0)
     {
         if (t < argc)
             heventParent = (HANDLE)atoi (ccom_argv[t+1]);
     }
     if ((t = CCheckParm ("-HCHILD")) > 0)
     {
         if (t < argc)
             heventChild = (HANDLE)atoi (ccom_argv[t+1]);
     }
 // ignore if we don't have all the events.
     if (!hFile || !heventParent || !heventChild)
     {
         printf ("Qhost not present.\n");
         return;
     }
     printf ("Initializing for qhost.\n");
     hfileBuffer = hFile;
     heventParentSend = heventParent;
     heventChildSend = heventChild;
 // so we'll know when to go away.
     heventDone = CreateEvent (NULL, FALSE, FALSE, NULL);
     if (!heventDone)
     {
         printf ("Couldn't create heventDone\n");
         return;
     }
     if (!_beginthreadex (NULL, 0, RequestProc, NULL, 0, &threadAddr))
     {
         CloseHandle (heventDone);
         printf ("Couldn't create QHOST thread\n");
         return;
     }
 // save off the input/output handles.
     hStdout = GetStdHandle (STD_OUTPUT_HANDLE);
     hStdin = GetStdHandle (STD_INPUT_HANDLE);
 // force 80 character width, at least 25 character height
     SetConsoleCXCY (hStdout, 80, 25);
 }
Referenced by Sys_Init().
ReadText()
BOOL ReadText (LPTSTR pszText, int iBeginLine, int iEndLine)
Definition at line 261 of file conproc.c.
 {
     COORD   coord;
     DWORD   dwRead;
     BOOL    bRet;
     coord.X = 0;
     coord.Y = iBeginLine;
     bRet = ReadConsoleOutputCharacter(
         hStdout,
         pszText,
         80 * (iEndLine - iBeginLine + 1),
         coord,
         &dwRead);
     // Make sure it's null terminated.
     if (bRet)
         pszText[dwRead] = '\0';
     return bRet;
 }
Referenced by RequestProc().
ReleaseMappedBuffer()
void ReleaseMappedBuffer (LPVOID pBuffer)
Definition at line 234 of file conproc.c.
 {
     UnmapViewOfFile (pBuffer);
 }
Referenced by RequestProc().
RequestProc()
unsigned _stdcall RequestProc (void * arg)
Definition at line 160 of file conproc.c.
 {
     int     *pBuffer;
     DWORD   dwRet;
     HANDLE  heventWait[2];
     int     iBeginLine, iEndLine;
     heventWait[0] = heventParentSend;
     heventWait[1] = heventDone;
     while (1)
     {
         dwRet = WaitForMultipleObjects (2, heventWait, FALSE, INFINITE);
     // heventDone fired, so we're exiting.
         if (dwRet == WAIT_OBJECT_0 + 1)
             break;
         pBuffer = (int *) GetMappedBuffer (hfileBuffer);
     // hfileBuffer is invalid.  Just leave.
         if (!pBuffer)
         {
             printf ("Invalid hfileBuffer\n");
             break;
         }
         switch (pBuffer[0])
         {
             case CCOM_WRITE_TEXT:
             // Param1 : Text
                 pBuffer[0] = WriteText ((LPCTSTR) (pBuffer + 1));
                 break;
             case CCOM_GET_TEXT:
             // Param1 : Begin line
             // Param2 : End line
                 iBeginLine = pBuffer[1];
                 iEndLine = pBuffer[2];
                 pBuffer[0] = ReadText ((LPTSTR) (pBuffer + 1), iBeginLine,
                                        iEndLine);
                 break;
             case CCOM_GET_SCR_LINES:
             // No params
                 pBuffer[0] = GetScreenBufferLines (&pBuffer[1]);
                 break;
             case CCOM_SET_SCR_LINES:
             // Param1 : Number of lines
                 pBuffer[0] = SetScreenBufferLines (pBuffer[1]);
                 break;
         }
         ReleaseMappedBuffer (pBuffer);
         SetEvent (heventChildSend);
     }
     _endthreadex (0);
     return 0;
 }
Referenced by InitConProc().
SetConsoleCXCY()
BOOL SetConsoleCXCY (HANDLE hStdout, int cx, int cy)
Definition at line 356 of file conproc.c.
 {
     CONSOLE_SCREEN_BUFFER_INFO  info;
     COORD                       coordMax;
     coordMax = GetLargestConsoleWindowSize(hStdout);
     if (cy > coordMax.Y)
         cy = coordMax.Y;
     if (cx > coordMax.X)
         cx = coordMax.X;
     if (!GetConsoleScreenBufferInfo(hStdout, &info))
         return FALSE;
 // height
     info.srWindow.Left = 0;
     info.srWindow.Right = info.dwSize.X - 1;
     info.srWindow.Top = 0;
     info.srWindow.Bottom = cy - 1;
     if (cy < info.dwSize.Y)
     {
         if (!SetConsoleWindowInfo(hStdout, TRUE, &info.srWindow))
             return FALSE;
         info.dwSize.Y = cy;
         if (!SetConsoleScreenBufferSize(hStdout, info.dwSize))
             return FALSE;
     }
     else if (cy > info.dwSize.Y)
     {
         info.dwSize.Y = cy;
         if (!SetConsoleScreenBufferSize(hStdout, info.dwSize))
             return FALSE;
         if (!SetConsoleWindowInfo(hStdout, TRUE, &info.srWindow))
             return FALSE;
     }
     if (!GetConsoleScreenBufferInfo(hStdout, &info))
         return FALSE;
 // width
     info.srWindow.Left = 0;
     info.srWindow.Right = cx - 1;
     info.srWindow.Top = 0;
     info.srWindow.Bottom = info.dwSize.Y - 1;
     if (cx < info.dwSize.X)
     {
         if (!SetConsoleWindowInfo(hStdout, TRUE, &info.srWindow))
             return FALSE;
         info.dwSize.X = cx;
         if (!SetConsoleScreenBufferSize(hStdout, info.dwSize))
             return FALSE;
     }
     else if (cx > info.dwSize.X)
     {
         info.dwSize.X = cx;
         if (!SetConsoleScreenBufferSize(hStdout, info.dwSize))
             return FALSE;
         if (!SetConsoleWindowInfo(hStdout, TRUE, &info.srWindow))
             return FALSE;
     }
     return TRUE;
 }
Referenced by InitConProc(), and SetScreenBufferLines().
SetScreenBufferLines()
BOOL SetScreenBufferLines (int iLines)
Definition at line 254 of file conproc.c.
 {
     return SetConsoleCXCY (hStdout, 80, iLines);
 }
Referenced by RequestProc().
WriteText()
BOOL WriteText (LPCTSTR szText)
Definition at line 285 of file conproc.c.
 {
     DWORD           dwWritten;
     INPUT_RECORD    rec;
     char            upper, *sz;
     sz = (LPTSTR) szText;
     while (*sz)
     {
     // 13 is the code for a carriage return (\n) instead of 10.
         if (*sz == 10)
             *sz = 13;
         upper = toupper(*sz);
         rec.EventType = KEY_EVENT;
         rec.Event.KeyEvent.bKeyDown = TRUE;
         rec.Event.KeyEvent.wRepeatCount = 1;
         rec.Event.KeyEvent.wVirtualKeyCode = upper;
         rec.Event.KeyEvent.wVirtualScanCode = CharToCode (*sz);
         rec.Event.KeyEvent.uChar.AsciiChar = *sz;
         rec.Event.KeyEvent.uChar.UnicodeChar = *sz;
         rec.Event.KeyEvent.dwControlKeyState = isupper(*sz) ? 0x80 : 0x0;
         WriteConsoleInput(
             hStdin,
             &rec,
             1,
             &dwWritten);
         rec.Event.KeyEvent.bKeyDown = FALSE;
         WriteConsoleInput(
             hStdin,
             &rec,
             1,
             &dwWritten);
         sz++;
     }
     return TRUE;
 }
Referenced by RequestProc().
Variable Documentation
ccom_argc
int ccom_argc
Definition at line 57 of file conproc.c.
Referenced by CCheckParm(), and InitConProc().
ccom_argv
char** ccom_argv
Definition at line 58 of file conproc.c.
Referenced by CCheckParm(), and InitConProc().
heventChildSend
HANDLE heventChildSend
Definition at line 42 of file conproc.c.
Referenced by InitConProc(), and RequestProc().
heventDone
HANDLE heventDone
Definition at line 40 of file conproc.c.
Referenced by DeinitConProc(), InitConProc(), and RequestProc().
heventParentSend
HANDLE heventParentSend
Definition at line 43 of file conproc.c.
Referenced by InitConProc(), and RequestProc().
hfileBuffer
HANDLE hfileBuffer
Definition at line 41 of file conproc.c.
Referenced by GetMappedBuffer(), InitConProc(), and RequestProc().
hStdin
HANDLE hStdin
Definition at line 45 of file conproc.c.
Referenced by InitConProc(), and WriteText().
hStdout
HANDLE hStdout
Definition at line 44 of file conproc.c.
Referenced by GetScreenBufferLines(), InitConProc(), ReadText(), SetConsoleCXCY(), and SetScreenBufferLines().