vkQuake2 doxygen: C:/entry/dev/vq2/src/server/sv_game.c File Reference
sv_game.c File Reference
#include "server.h"
Functions
void PF_Unicast (edict_t *ent, qboolean reliable)
void PF_dprintf (char *fmt,...)
void PF_cprintf (edict_t *ent, int level, char *fmt,...)
void PF_centerprintf (edict_t *ent, char *fmt,...)
void PF_error (char *fmt,...)
void PF_setmodel (edict_t *ent, char *name)
void PF_Configstring (int index, char *val)
void PF_WriteChar (int c)
void PF_WriteByte (int c)
void PF_WriteShort (int c)
void PF_WriteLong (int c)
void PF_WriteFloat (float f)
void PF_WriteString (char *s)
void PF_WritePos (vec3_t pos)
void PF_WriteDir (vec3_t dir)
void PF_WriteAngle (float f)
qboolean PF_inPVS (vec3_t p1, vec3_t p2)
qboolean PF_inPHS (vec3_t p1, vec3_t p2)
void PF_StartSound (edict_t *entity, int channel, int sound_num, float volume, float attenuation, float timeofs)
void SV_ShutdownGameProgs (void)
void SCR_DebugGraph (float value, int color)
void SV_InitGameProgs (void)
Variables
game_export_t * ge
Function Documentation
PF_centerprintf()
void PF_centerprintf (edict_t * ent, char * fmt, ...)
Definition at line 115 of file sv_game.c.
 {
     char        msg[1024];
     va_list     argptr;
     int         n;
     n = NUM_FOR_EDICT(ent);
     if (n < 1 || n > maxclients->value)
         return; // Com_Error (ERR_DROP, "centerprintf to a non-client");
     va_start (argptr,fmt);
     vsnprintf (msg, 1024, fmt, argptr);
     va_end (argptr);
     MSG_WriteByte (&sv.multicast,svc_centerprint);
     MSG_WriteString (&sv.multicast,msg);
     PF_Unicast (ent, true);
 }
Referenced by SV_InitGameProgs().
PF_Configstring()
void PF_Configstring (int index, char * val)
Definition at line 192 of file sv_game.c.
 {
     if (index < 0 || index >= MAX_CONFIGSTRINGS)
         Com_Error (ERR_DROP, "configstring: bad index %i\n", index);
     if (!val)
         val = "";
     // change the string in sv
     strcpy (sv.configstrings[index], val);
     if (sv.state != ss_loading)
     {   // send the update to everyone
         SZ_Clear (&sv.multicast);
         MSG_WriteChar (&sv.multicast, svc_configstring);
         MSG_WriteShort (&sv.multicast, index);
         MSG_WriteString (&sv.multicast, val);
         SV_Multicast (vec3_origin, MULTICAST_ALL_R);
     }
 }
Referenced by SV_InitGameProgs().
PF_cprintf()
void PF_cprintf (edict_t * ent, int level, char * fmt, ...)
Definition at line 84 of file sv_game.c.
 {
     char        msg[1024];
     va_list     argptr;
     int         n = 0;
     if (ent)
     {
         n = NUM_FOR_EDICT(ent);
         if (n < 1 || n > maxclients->value)
             Com_Error (ERR_DROP, "cprintf to a non-client");
     }
     va_start (argptr,fmt);
     vsnprintf (msg, 1024, fmt, argptr);
     va_end (argptr);
     if (ent)
         SV_ClientPrintf (svs.clients+(n-1), level, "%s", msg);
     else
         Com_Printf ("%s", msg);
 }
Referenced by SV_InitGameProgs().
PF_dprintf()
void PF_dprintf (char * fmt, ...)
Definition at line 64 of file sv_game.c.
 {
     char        msg[1024];
     va_list     argptr;
     va_start (argptr,fmt);
     vsnprintf (msg, 1024, fmt, argptr);
     va_end (argptr);
     Com_Printf ("%s", msg);
 }
Referenced by SV_InitGameProgs().
PF_error()
void PF_error (char * fmt, ...)
Definition at line 142 of file sv_game.c.
 {
     char        msg[1024];
     va_list     argptr;
     va_start (argptr,fmt);
     vsnprintf (msg, 1024, fmt, argptr);
     va_end (argptr);
     Com_Error (ERR_DROP, "Game Error: %s", msg);
 }
Referenced by SV_InitGameProgs().
PF_inPHS()
qboolean PF_inPHS (vec3_t p1, vec3_t p2)
Definition at line 264 of file sv_game.c.
 {
     int     leafnum;
     int     cluster;
     int     area1, area2;
     byte    *mask;
     leafnum = CM_PointLeafnum (p1);
     cluster = CM_LeafCluster (leafnum);
     area1 = CM_LeafArea (leafnum);
     mask = CM_ClusterPHS (cluster);
     leafnum = CM_PointLeafnum (p2);
     cluster = CM_LeafCluster (leafnum);
     area2 = CM_LeafArea (leafnum);
     if ( mask && (!(mask[cluster>>3] & (1<<(cluster&7)) ) ) )
         return false;       // more than one bounce away
     if (!CM_AreasConnected (area1, area2))
         return false;       // a door blocks hearing
     return true;
 }
Referenced by SV_InitGameProgs().
PF_inPVS()
qboolean PF_inPVS (vec3_t p1, vec3_t p2)
Definition at line 234 of file sv_game.c.
 {
     int     leafnum;
     int     cluster;
     int     area1, area2;
     byte    *mask;
     leafnum = CM_PointLeafnum (p1);
     cluster = CM_LeafCluster (leafnum);
     area1 = CM_LeafArea (leafnum);
     mask = CM_ClusterPVS (cluster);
     leafnum = CM_PointLeafnum (p2);
     cluster = CM_LeafCluster (leafnum);
     area2 = CM_LeafArea (leafnum);
     if ( mask && (!(mask[cluster>>3] & (1<<(cluster&7)) ) ) )
         return false;
     if (!CM_AreasConnected (area1, area2))
         return false;       // a door blocks sight
     return true;
 }
Referenced by SV_InitGameProgs().
PF_setmodel()
void PF_setmodel (edict_t * ent, char * name)
Definition at line 162 of file sv_game.c.
 {
     int     i;
     cmodel_t    *mod;
     if (!name)
         Com_Error (ERR_DROP, "PF_setmodel: NULL");
     i = SV_ModelIndex (name);
 //  ent->model = name;
     ent->s.modelindex = i;
 // if it is an inline model, get the size information for it
     if (name[0] == '*')
     {
         mod = CM_InlineModel (name);
         VectorCopy (mod->mins, ent->mins);
         VectorCopy (mod->maxs, ent->maxs);
         SV_LinkEdict (ent);
     }
 }
Referenced by SV_InitGameProgs().
PF_StartSound()
void PF_StartSound (edict_t * entity, int channel, int sound_num, float volume, float attenuation, float timeofs)
Definition at line 287 of file sv_game.c.
 {
     if (!entity)
         return;
     SV_StartSound (NULL, entity, channel, sound_num, volume, attenuation, timeofs);
 }
Referenced by SV_InitGameProgs().
PF_Unicast()
void PF_Unicast (edict_t * ent, qboolean reliable)
Definition at line 34 of file sv_game.c.
 {
     int     p;
     client_t    *client;
     if (!ent)
         return;
     p = NUM_FOR_EDICT(ent);
     if (p < 1 || p > maxclients->value)
         return;
     client = svs.clients + (p-1);
     if (reliable)
         SZ_Write (&client->netchan.message, sv.multicast.data, sv.multicast.cursize);
     else
         SZ_Write (&client->datagram, sv.multicast.data, sv.multicast.cursize);
     SZ_Clear (&sv.multicast);
 }
Referenced by PF_centerprintf(), and SV_InitGameProgs().
PF_WriteAngle()
void PF_WriteAngle (float f)
Definition at line 224 of file sv_game.c.
 {MSG_WriteAngle (&sv.multicast, f);}
Referenced by SV_InitGameProgs().
PF_WriteByte()
void PF_WriteByte (int c)
Definition at line 217 of file sv_game.c.
 {MSG_WriteByte (&sv.multicast, c);}
Referenced by SV_InitGameProgs().
PF_WriteChar()
void PF_WriteChar (int c)
Definition at line 216 of file sv_game.c.
 {MSG_WriteChar (&sv.multicast, c);}
Referenced by SV_InitGameProgs().
PF_WriteDir()
void PF_WriteDir (vec3_t dir)
Definition at line 223 of file sv_game.c.
 {MSG_WriteDir (&sv.multicast, dir);}
Referenced by SV_InitGameProgs().
PF_WriteFloat()
void PF_WriteFloat (float f)
Definition at line 220 of file sv_game.c.
 {MSG_WriteFloat (&sv.multicast, f);}
Referenced by SV_InitGameProgs().
PF_WriteLong()
void PF_WriteLong (int c)
Definition at line 219 of file sv_game.c.
 {MSG_WriteLong (&sv.multicast, c);}
Referenced by SV_InitGameProgs().
PF_WritePos()
void PF_WritePos (vec3_t pos)
Definition at line 222 of file sv_game.c.
 {MSG_WritePos (&sv.multicast, pos);}
Referenced by SV_InitGameProgs().
PF_WriteShort()
void PF_WriteShort (int c)
Definition at line 218 of file sv_game.c.
 {MSG_WriteShort (&sv.multicast, c);}
Referenced by SV_InitGameProgs().
PF_WriteString()
void PF_WriteString (char * s)
Definition at line 221 of file sv_game.c.
 {MSG_WriteString (&sv.multicast, s);}
Referenced by SV_InitGameProgs().
SCR_DebugGraph()
void SCR_DebugGraph (float value, int color)
Definition at line 137 of file cl_scrn.c.
 {
     values[current&1023].value = value;
     values[current&1023].color = color;
     current++;
 }
Referenced by CL_AddNetgraph(), SCR_UpdateScreen(), and SV_InitGameProgs().
SV_InitGameProgs()
void SV_InitGameProgs (void)
Definition at line 323 of file sv_game.c.
 {
     game_import_t   import;
     // unload anything we have now
     if (ge)
         SV_ShutdownGameProgs ();
     // load a new game dll
     import.multicast = SV_Multicast;
     import.unicast = PF_Unicast;
     import.bprintf = SV_BroadcastPrintf;
     import.dprintf = PF_dprintf;
     import.cprintf = PF_cprintf;
     import.centerprintf = PF_centerprintf;
     import.error = PF_error;
     import.linkentity = SV_LinkEdict;
     import.unlinkentity = SV_UnlinkEdict;
     import.BoxEdicts = SV_AreaEdicts;
     import.trace = SV_Trace;
     import.pointcontents = SV_PointContents;
     import.setmodel = PF_setmodel;
     import.inPVS = PF_inPVS;
     import.inPHS = PF_inPHS;
     import.Pmove = Pmove;
     import.modelindex = SV_ModelIndex;
     import.soundindex = SV_SoundIndex;
     import.imageindex = SV_ImageIndex;
     import.configstring = PF_Configstring;
     import.sound = PF_StartSound;
     import.positioned_sound = SV_StartSound;
     import.WriteChar = PF_WriteChar;
     import.WriteByte = PF_WriteByte;
     import.WriteShort = PF_WriteShort;
     import.WriteLong = PF_WriteLong;
     import.WriteFloat = PF_WriteFloat;
     import.WriteString = PF_WriteString;
     import.WritePosition = PF_WritePos;
     import.WriteDir = PF_WriteDir;
     import.WriteAngle = PF_WriteAngle;
     import.TagMalloc = Z_TagMalloc;
     import.TagFree = Z_Free;
     import.FreeTags = Z_FreeTags;
     import.cvar = Cvar_Get;
     import.cvar_set = Cvar_Set;
     import.cvar_forceset = Cvar_ForceSet;
     import.argc = Cmd_Argc;
     import.argv = Cmd_Argv;
     import.args = Cmd_Args;
     import.AddCommandString = Cbuf_AddText;
     import.DebugGraph = SCR_DebugGraph;
     import.SetAreaPortalState = CM_SetAreaPortalState;
     import.AreasConnected = CM_AreasConnected;
     ge = (game_export_t *)Sys_GetGameAPI (&import);
     if (!ge)
         Com_Error (ERR_DROP, "failed to load game DLL");
     if (ge->apiversion != GAME_API_VERSION)
         Com_Error (ERR_DROP, "game is version %i, not %i", ge->apiversion,
         GAME_API_VERSION);
     ge->Init ();
 }
Referenced by SV_InitGame().
SV_ShutdownGameProgs()
void SV_ShutdownGameProgs (void)
Definition at line 305 of file sv_game.c.
 {
     if (!ge)
         return;
     ge->Shutdown ();
     Sys_UnloadGame ();
     ge = NULL;
 }
Referenced by CL_Connect_f(), Com_Error(), Com_Quit(), Qcommon_Frame(), SV_InitGame(), SV_InitGameProgs(), and SV_KillServer_f().
Variable Documentation
ge
game_export_t* ge
Definition at line 24 of file sv_game.c.
Referenced by SV_Begin_f(), SV_BuildClientFrame(), SV_CheckForSavegame(), SV_ClientThink(), SV_CreateBaseline(), SV_DropClient(), SV_ExecuteUserCommand(), SV_InitGameProgs(), SV_LinkEdict(), SV_PrepWorldFrame(), SV_ReadLevelFile(), SV_ReadServerFile(), SV_RunGameFrame(), SV_ServerCommand_f(), SV_ShutdownGameProgs(), SV_SpawnServer(), SV_Trace(), SV_UserinfoChanged(), SV_WriteLevelFile(), SV_WriteServerFile(), and SVC_DirectConnect().