vkQuake2 doxygen: C:/entry/dev/vq2/src/qcommon/cvar.c File Reference
cvar.c File Reference
#include "qcommon.h"
Functions
static qboolean Cvar_InfoValidate (char *s)
static cvar_t * Cvar_FindVar (char *var_name)
float Cvar_VariableValue (char *var_name)
char * Cvar_VariableString (char *var_name)
char * Cvar_CompleteVariable (char *partial)
cvar_t * Cvar_Get (char *var_name, char *var_value, int flags)
cvar_t * Cvar_Set2 (char *var_name, char *value, qboolean force)
cvar_t * Cvar_ForceSet (char *var_name, char *value)
cvar_t * Cvar_Set (char *var_name, char *value)
cvar_t * Cvar_FullSet (char *var_name, char *value, int flags)
void Cvar_SetValue (char *var_name, float value)
void Cvar_GetLatchedVars (void)
qboolean Cvar_Command (void)
void Cvar_Set_f (void)
void Cvar_WriteVariables (char *path)
void Cvar_List_f (void)
char * Cvar_BitInfo (int bit)
char * Cvar_Userinfo (void)
char * Cvar_Serverinfo (void)
void Cvar_Init (void)
Variables
cvar_t * cvar_vars
qboolean userinfo_modified
Function Documentation
Cvar_BitInfo()
char* Cvar_BitInfo (int bit)
Definition at line 488 of file cvar.c.
 {
     static char info[MAX_INFO_STRING];
     cvar_t  *var;
     info[0] = 0;
     for (var = cvar_vars ; var ; var = var->next)
     {
         if (var->flags & bit)
             Info_SetValueForKey (info, var->name, var->string);
     }
     return info;
 }
Referenced by Cvar_Serverinfo(), and Cvar_Userinfo().
Cvar_Command()
qboolean Cvar_Command (void)
Definition at line 363 of file cvar.c.
 {
     cvar_t          *v;
 // check variables
     v = Cvar_FindVar (Cmd_Argv(0));
     if (!v)
         return false;
 // perform a variable print or set
     if (Cmd_Argc() == 1)
     {
         Com_Printf ("\"%s\" is \"%s\"\n", v->name, v->string);
         return true;
     }
     Cvar_Set (v->name, Cmd_Argv(1));
     return true;
 }
Referenced by Cmd_ExecuteString().
Cvar_CompleteVariable()
char* Cvar_CompleteVariable (char * partial)
Definition at line 95 of file cvar.c.
 {
     cvar_t      *cvar;
     int         len;
     len = (int)strlen(partial);
     if (!len)
         return NULL;
     // check exact match
     for (cvar=cvar_vars ; cvar ; cvar=cvar->next)
         if (!strcmp (partial,cvar->name))
             return cvar->name;
     // check partial match
     for (cvar=cvar_vars ; cvar ; cvar=cvar->next)
         if (!strncmp (partial,cvar->name, len))
             return cvar->name;
     return NULL;
 }
Referenced by CompleteCommand().
Cvar_FindVar()
static cvar_t* Cvar_FindVar (char * var_name) static
Definition at line 47 of file cvar.c.
 {
     cvar_t  *var;
     for (var=cvar_vars ; var ; var=var->next)
         if (!strcmp (var_name, var->name))
             return var;
     return NULL;
 }
Referenced by Cvar_Command(), Cvar_FullSet(), Cvar_Get(), Cvar_Set2(), Cvar_VariableString(), and Cvar_VariableValue().
Cvar_ForceSet()
cvar_t* Cvar_ForceSet (char * var_name, char * value)
Definition at line 268 of file cvar.c.
 {
     return Cvar_Set2 (var_name, value, true);
 }
Referenced by EasyGameFunc(), HardGameFunc(), MediumGameFunc(), SV_InitGameProgs(), and SV_ReadServerFile().
Cvar_FullSet()
cvar_t* Cvar_FullSet (char * var_name, char * value, int flags)
Definition at line 288 of file cvar.c.
 {
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
     {   // create it
         return Cvar_Get (var_name, value, flags);
     }
     var->modified = true;
     if (var->flags & CVAR_USERINFO)
         userinfo_modified = true;   // transmit at next oportunity
     Z_Free (var->string);   // free the old value string
     var->string = CopyString(value);
     var->value = atof (var->string);
     var->flags = flags;
     return var;
 }
Referenced by Cvar_Set_f(), FS_SetGamedir(), SV_InitGame(), and SV_SpawnServer().
Cvar_Get()
cvar_t* Cvar_Get (char * var_name, char * var_value, int flags)
Definition at line 127 of file cvar.c.
 {
     cvar_t  *var;
     if (flags & (CVAR_USERINFO | CVAR_SERVERINFO))
     {
         if (!Cvar_InfoValidate (var_name))
         {
             Com_Printf("invalid info cvar name\n");
             return NULL;
         }
     }
     var = Cvar_FindVar (var_name);
     if (var)
     {
         var->flags |= flags;
         return var;
     }
     if (!var_value)
         return NULL;
     if (flags & (CVAR_USERINFO | CVAR_SERVERINFO))
     {
         if (!Cvar_InfoValidate (var_value))
         {
             Com_Printf("invalid info cvar value\n");
             return NULL;
         }
     }
     var = Z_Malloc (sizeof(*var));
     var->name = CopyString (var_name);
     var->string = CopyString (var_value);
     var->modified = true;
     var->value = atof (var->string);
     // link the variable in
     var->next = cvar_vars;
     cvar_vars = var;
     var->flags = flags;
     return var;
 }
Referenced by AddressBook_MenuInit(), CDAudio_Init(), CL_FixCvarCheats(), CL_InitInput(), CL_InitLocal(), CL_PingServers_f(), CM_LoadMap(), Con_Init(), Cvar_FullSet(), Cvar_Set2(), FS_InitFilesystem(), IN_Init(), IN_StartupJoystick(), IN_StartupMouse(), Miniaudio_Init(), NET_Init(), NET_OpenIP(), NET_OpenIPX(), Netchan_Init(), Options_MenuInit(), PlayerConfig_MenuInit(), Qcommon_Init(), S_Init(), SCR_Init(), SNDDMA_Init(), SV_Init(), SV_InitGameProgs(), V_Init(), VID_Init(), VID_LoadRefresh(), and VID_MenuInit().
Cvar_GetLatchedVars()
void Cvar_GetLatchedVars (void)
Definition at line 336 of file cvar.c.
 {
     cvar_t  *var;
     for (var = cvar_vars ; var ; var = var->next)
     {
         if (!var->latched_string)
             continue;
         Z_Free (var->string);
         var->string = var->latched_string;
         var->latched_string = NULL;
         var->value = atof(var->string);
         if (!strcmp(var->name, "game"))
         {
             FS_SetGamedir (var->string);
             FS_ExecAutoexec ();
         }
     }
 }
Referenced by SV_InitGame().
Cvar_InfoValidate()
static qboolean Cvar_InfoValidate (char * s) static
Definition at line 31 of file cvar.c.
 {
     if (strstr (s, "\\"))
         return false;
     if (strstr (s, "\""))
         return false;
     if (strstr (s, ";"))
         return false;
     return true;
 }
Referenced by Cvar_Get(), and Cvar_Set2().
Cvar_Init()
void Cvar_Init (void)
Definition at line 522 of file cvar.c.
 {
     Cmd_AddCommand ("set", Cvar_Set_f);
     Cmd_AddCommand ("cvarlist", Cvar_List_f);
 }
Referenced by Qcommon_Init().
Cvar_List_f()
void Cvar_List_f (void)
Definition at line 453 of file cvar.c.
 {
     cvar_t  *var;
     int     i;
     i = 0;
     for (var = cvar_vars ; var ; var = var->next, i++)
     {
         if (var->flags & CVAR_ARCHIVE)
             Com_Printf ("*");
         else
             Com_Printf (" ");
         if (var->flags & CVAR_USERINFO)
             Com_Printf ("U");
         else
             Com_Printf (" ");
         if (var->flags & CVAR_SERVERINFO)
             Com_Printf ("S");
         else
             Com_Printf (" ");
         if (var->flags & CVAR_NOSET)
             Com_Printf ("-");
         else if (var->flags & CVAR_LATCH)
             Com_Printf ("L");
         else
             Com_Printf (" ");
         Com_Printf (" %s \"%s\"\n", var->name, var->string);
     }
     Com_Printf ("%i cvars\n", i);
 }
Referenced by Cvar_Init().
Cvar_Serverinfo()
char* Cvar_Serverinfo (void)
Definition at line 510 of file cvar.c.
 {
     return Cvar_BitInfo (CVAR_SERVERINFO);
 }
Referenced by SV_Serverinfo_f(), SV_ShowServerinfo_f(), and SV_StatusString().
Cvar_Set()
cvar_t* Cvar_Set (char * var_name, char * value)
Definition at line 278 of file cvar.c.
 {
     return Cvar_Set2 (var_name, value, false);
 }
Referenced by AddressBook_MenuKey(), ApplyChanges(), CL_FixCvarCheats(), CL_FixUpGender(), CL_ParseServerData(), Con_ToggleConsole_f(), Cvar_Command(), Cvar_Set_f(), Cvar_SetValue(), Key_Event(), M_ForceMenuOff(), M_PushMenu(), PlayerConfig_MenuKey(), SCR_CalcVrect(), StartServerActionFunc(), SV_InitGameProgs(), SV_Map(), SV_Nextserver(), SV_SetMaster_f(), SV_SpawnServer(), VID_CheckChanges(), VID_LoadRefresh(), and VID_NewWindow().
Cvar_Set2()
cvar_t* Cvar_Set2 (char * var_name, char * value, qboolean force)
Definition at line 179 of file cvar.c.
 {
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
     {   // create it
         return Cvar_Get (var_name, value, 0);
     }
     if (var->flags & (CVAR_USERINFO | CVAR_SERVERINFO))
     {
         if (!Cvar_InfoValidate (value))
         {
             Com_Printf("invalid info cvar value\n");
             return var;
         }
     }
     if (!force)
     {
         if (var->flags & CVAR_NOSET)
         {
             Com_Printf ("%s is write protected.\n", var_name);
             return var;
         }
         if (var->flags & CVAR_LATCH)
         {
             if (var->latched_string)
             {
                 if (strcmp(value, var->latched_string) == 0)
                     return var;
                 Z_Free (var->latched_string);
             }
             else
             {
                 if (strcmp(value, var->string) == 0)
                     return var;
             }
             if (Com_ServerState())
             {
                 Com_Printf ("%s will be changed for next game.\n", var_name);
                 var->latched_string = CopyString(value);
             }
             else
             {
                 var->string = CopyString(value);
                 var->value = atof (var->string);
                 if (!strcmp(var->name, "game"))
                 {
                     FS_SetGamedir (var->string);
                     FS_ExecAutoexec ();
                 }
             }
             return var;
         }
     }
     else
     {
         if (var->latched_string)
         {
             Z_Free (var->latched_string);
             var->latched_string = NULL;
         }
     }
     if (!strcmp(value, var->string))
         return var;     // not changed
     var->modified = true;
     if (var->flags & CVAR_USERINFO)
         userinfo_modified = true;   // transmit at next oportunity
     Z_Free (var->string);   // free the old value string
     var->string = CopyString(value);
     var->value = atof (var->string);
     return var;
 }
Referenced by Cvar_ForceSet(), and Cvar_Set().
Cvar_Set_f()
void Cvar_Set_f (void)
Definition at line 391 of file cvar.c.
 {
     int     c;
     int     flags;
     c = Cmd_Argc();
     if (c != 3 && c != 4)
     {
         Com_Printf ("usage: set <variable> <value> [u / s]\n");
         return;
     }
     if (c == 4)
     {
         if (!strcmp(Cmd_Argv(3), "u"))
             flags = CVAR_USERINFO;
         else if (!strcmp(Cmd_Argv(3), "s"))
             flags = CVAR_SERVERINFO;
         else
         {
             Com_Printf ("flags can only be 'u' or 's'\n");
             return;
         }
         Cvar_FullSet (Cmd_Argv(1), Cmd_Argv(2), flags);
     }
     else
         Cvar_Set (Cmd_Argv(1), Cmd_Argv(2));
 }
Referenced by Cvar_Init().
Cvar_SetValue()
void Cvar_SetValue (char * var_name, float value)
Definition at line 317 of file cvar.c.
 {
     char    val[32];
     if (value == (int)value)
         Com_sprintf (val, sizeof(val), "%i",(int)value);
     else
         Com_sprintf (val, sizeof(val), "%f",value);
     Cvar_Set (var_name, val);
 }
Referenced by AlwaysRunFunc(), ApplyChanges(), BrightnessCallback(), CL_Pause_f(), ControlsSetMenuItemValues(), CrosshairFunc(), DMFlagCallback(), DownloadCallback(), FreeLookFunc(), HandednessCallback(), InvertMouseFunc(), JoystickFunc(), LookspringFunc(), LookstrafeFunc(), MainWndProc(), MouseSpeedFunc(), NoAltTabFunc(), PlayerConfig_MenuInit(), RateCallback(), SCR_PlayCinematic(), SCR_SizeDown_f(), SCR_SizeUp_f(), SCR_UpdateScreen(), ScreenSizeCallback(), StartGame(), StartServerActionFunc(), UpdateCDVolumeFunc(), UpdateSoundQualityFunc(), UpdateVolumeFunc(), and VID_LoadRefresh().
Cvar_Userinfo()
char* Cvar_Userinfo (void)
Definition at line 504 of file cvar.c.
 {
     return Cvar_BitInfo (CVAR_USERINFO);
 }
Referenced by CL_SendCmd(), CL_SendConnectPacket(), and CL_Userinfo_f().
Cvar_VariableString()
char* Cvar_VariableString (char * var_name)
Definition at line 79 of file cvar.c.
 {
     cvar_t *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return "";
     return var->string;
 }
Referenced by CL_PingServers_f(), Cmd_AddCommand(), Cmd_MacroExpandString(), FS_ExecAutoexec(), StartServer_MenuInit(), SV_New_f(), SV_Nextserver(), and SV_ServerRecord_f().
Cvar_VariableValue()
float Cvar_VariableValue (char * var_name)
Definition at line 63 of file cvar.c.
 {
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return 0;
     return atof (var->string);
 }
Referenced by CDAudio_Play2(), CL_Pause_f(), CL_SendConnectPacket(), CM_LoadMap(), Con_ToggleConsole_f(), ControlsSetMenuItemValues(), DMFlagCallback(), DMOptions_MenuInit(), DownloadOptions_MenuInit(), IN_Frame(), M_PushMenu(), Miniaudio_Init(), Miniaudio_Play(), NET_OpenIP(), NET_OpenIPX(), Options_MenuInit(), PlayerConfig_MenuInit(), SCR_PlayCinematic(), StartServer_MenuInit(), SV_CheckForSavegame(), SV_InitGame(), SV_Map(), SV_Nextserver(), SV_Savegame_f(), and SV_SpawnServer().
Cvar_WriteVariables()
void Cvar_WriteVariables (char * path)
Definition at line 429 of file cvar.c.
 {
     cvar_t  *var;
     char    buffer[1024];
     FILE    *f;
     f = fopen (path, "a");
     for (var = cvar_vars ; var ; var = var->next)
     {
         if (var->flags & CVAR_ARCHIVE)
         {
             Com_sprintf (buffer, sizeof(buffer), "set %s \"%s\"\n", var->name, var->string);
             fprintf (f, "%s", buffer);
         }
     }
     fclose (f);
 }
Referenced by CL_WriteConfiguration().
Variable Documentation
cvar_vars
cvar_t* cvar_vars
Definition at line 24 of file cvar.c.
Referenced by Cvar_BitInfo(), Cvar_CompleteVariable(), Cvar_FindVar(), Cvar_Get(), Cvar_GetLatchedVars(), Cvar_List_f(), Cvar_WriteVariables(), and SV_WriteServerFile().
userinfo_modified
qboolean userinfo_modified
Definition at line 485 of file cvar.c.
Referenced by CL_SendCmd(), CL_SendConnectPacket(), Cvar_FullSet(), and Cvar_Set2().