vq2 doxygen: C:/entry/syn/github/vq2/game/g_utils.c File Reference
g_utils.c File Reference
#include "g_local.h"
Macros
#define MAXCHOICES 8
Functions
void G_ProjectSource (vec3_t point, vec3_t distance, vec3_t forward, vec3_t right, vec3_t result)
edict_t * G_Find (edict_t *from, int fieldofs, char *match)
edict_t * findradius (edict_t *from, vec3_t org, float rad)
edict_t * G_PickTarget (char *targetname)
void Think_Delay (edict_t *ent)
void G_UseTargets (edict_t *ent, edict_t *activator)
float * tv (float x, float y, float z)
char * vtos (vec3_t v)
void G_SetMovedir (vec3_t angles, vec3_t movedir)
float vectoyaw (vec3_t vec)
void vectoangles (vec3_t value1, vec3_t angles)
char * G_CopyString (char *in)
void G_InitEdict (edict_t *e)
edict_t * G_Spawn (void)
void G_FreeEdict (edict_t *ed)
void G_TouchTriggers (edict_t *ent)
void G_TouchSolids (edict_t *ent)
qboolean KillBox (edict_t *ent)
Variables
vec3_t VEC_UP = {0, -1, 0}
vec3_t MOVEDIR_UP = {0, 0, 1}
vec3_t VEC_DOWN = {0, -2, 0}
vec3_t MOVEDIR_DOWN = {0, 0, -1}
Macro Definition Documentation
MAXCHOICES
#define MAXCHOICES 8
Definition at line 116 of file g_utils.c.
Function Documentation
findradius()
edict_t* findradius (edict_t * from, vec3_t org, float rad)
Definition at line 78 of file g_utils.c.
 {
     vec3_t  eorg;
     int     j;
     if (!from)
         from = g_edicts;
     else
         from++;
     for ( ; from < &g_edicts[globals.num_edicts]; from++)
     {
         if (!from->inuse)
             continue;
         if (from->solid == SOLID_NOT)
             continue;
         for (j=0 ; j<3 ; j++)
             eorg[j] = org[j] - (from->s.origin[j] + (from->mins[j] + from->maxs[j])*0.5);
         if (VectorLength(eorg) > rad)
             continue;
         return from;
     }
     return NULL;
 }
Referenced by bfg_explode(), bfg_think(), medic_FindDeadMonster(), and T_RadiusDamage().
G_CopyString()
char* G_CopyString (char * in)
Definition at line 391 of file g_utils.c.
 {
     char    *out;
     out = gi.TagMalloc ((int)strlen(in)+1, TAG_LEVEL);
     strcpy (out, in);
     return out;
 }
G_Find()
edict_t* G_Find (edict_t * from, int fieldofs, char * match)
Definition at line 45 of file g_utils.c.
 {
     char    *s;
     if (!from)
         from = g_edicts;
     else
         from++;
     for ( ; from < &g_edicts[globals.num_edicts] ; from++)
     {
         if (!from->inuse)
             continue;
         s = *(char **) ((byte *)from + fieldofs);
         if (!s)
             continue;
         if (!Q_stricmp (s, match))
             return from;
     }
     return NULL;
 }
Referenced by BeginIntermission(), CTFFragBonuses(), CTFResetFlag(), CTFSay_Team_Location(), door_use_areaportals(), EndDMLevel(), FindTechSpawn(), func_clock_think(), misc_viper_bomb_use(), monster_start_go(), old_teleporter_touch(), SelectCoopSpawnPoint(), SelectCTFSpawnPoint(), SelectFarthestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectSpawnPoint(), SetCTFStats(), SP_FixCoopSpots(), target_laser_start(), target_lightramp_use(), and teleporter_touch().
G_FreeEdict()
void G_FreeEdict (edict_t * ed)
Definition at line 452 of file g_utils.c.
 {
     gi.unlinkentity (ed);       // unlink from world
     if ((ed - g_edicts) <= (maxclients->value + BODY_QUEUE_SIZE))
     {
 //      gi.dprintf("tried to free special edict\n");
         return;
     }
     memset (ed, 0, sizeof(*ed));
     ed->classname = "freed";
     ed->freetime = level.time;
     ed->inuse = false;
 }
Referenced by ai_run(), BecomeExplosion1(), BecomeExplosion2(), bfg_explode(), bfg_touch(), blaster_touch(), Cmd_Give_f(), CTFFlagSetup(), CTFResetFlag(), CTFResetGrapple(), CTFResetTech(), CTFRespawnTech(), debris_die(), Drop_Ammo(), drop_make_touchable(), droptofloor(), fire_bfg(), fire_blaster(), fire_rocket(), func_explosive_explode(), gib_die(), gib_think(), Grenade_Explode(), Grenade_Touch(), MegaHealth_think(), misc_blackhole_use(), monster_start(), multi_trigger(), rocket_touch(), SP_func_clock(), SP_func_explosive(), SP_info_null(), SP_info_player_coop(), SP_info_player_deathmatch(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SP_light(), SP_misc_actor(), SP_misc_deadsoldier(), SP_misc_explobox(), SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), SP_misc_insane(), SP_misc_strogg_ship(), SP_misc_teleporter(), SP_misc_viper(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier(), SP_monster_soldier_light(), SP_monster_soldier_ss(), SP_monster_supertank(), SP_monster_tank(), SP_path_corner(), SP_point_combat(), SP_target_changelevel(), SP_target_goal(), SP_target_help(), SP_target_lightramp(), SP_target_secret(), SP_trigger_gravity(), SP_trigger_teleport(), SP_turret_driver(), SpawnEntities(), SpawnItem(), SpawnTechs(), target_crosslevel_target_think(), target_lightramp_use(), TechThink(), ThrowDebris(), ThrowGib(), ThrowHead(), TossClientWeapon(), Touch_Item(), trigger_crosslevel_trigger_use(), trigger_push_touch(), turret_breach_finish_init(), Use_Boss3(), use_target_goal(), and use_target_secret().
G_InitEdict()
void G_InitEdict (edict_t * e)
Definition at line 401 of file g_utils.c.
 {
     e->inuse = true;
     e->classname = "noclass";
     e->gravity = 1.0;
     e->s.number = e - g_edicts;
 }
Referenced by ClientBegin(), and ClientBeginDeathmatch().
G_PickTarget()
edict_t* G_PickTarget (char * targetname)
Definition at line 118 of file g_utils.c.
 {
     edict_t *ent = NULL;
     int     num_choices = 0;
     edict_t *choice[MAXCHOICES];
     if (!targetname)
     {
         gi.dprintf("G_PickTarget called with NULL targetname\n");
         return NULL;
     }
     while(1)
     {
         ent = G_Find (ent, FOFS(targetname), targetname);
         if (!ent)
             break;
         choice[num_choices++] = ent;
         if (num_choices == MAXCHOICES)
             break;
     }
     if (!num_choices)
     {
         gi.dprintf("G_PickTarget: target %s not found\n", targetname);
         return NULL;
     }
     return choice[rand() % num_choices];
 }
Referenced by actor_use(), FoundTarget(), func_train_find(), monster_start_go(), path_corner_touch(), point_combat_touch(), target_actor_touch(), train_next(), trigger_elevator_init(), trigger_elevator_use(), turret_breach_finish_init(), and turret_driver_link().
G_ProjectSource()
void G_ProjectSource (vec3_t point, vec3_t distance, vec3_t forward, vec3_t right, vec3_t result)
Definition at line 25 of file g_utils.c.
 {
     result[0] = point[0] + forward[0] * distance[0] + right[0] * distance[1];
     result[1] = point[1] + forward[1] * distance[0] + right[1] * distance[1];
     result[2] = point[2] + forward[2] * distance[0] + right[2] * distance[1] + distance[2];
 }
Referenced by actorMachineGun(), ai_run(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), ChickRocket(), Drop_Item(), floater_fire_blaster(), floater_zap(), flyer_fire(), GladiatorGun(), GunnerFire(), GunnerGrenade(), hover_fire_blaster(), InfantryMachineGun(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), makronBFG(), MakronHyperblaster(), MakronRailgun(), medic_cable_attack(), medic_fire_blaster(), P_ProjectSource(), parasite_drain_attack(), soldier_fire(), supertankMachineGun(), supertankRocket(), TankBlaster(), TankMachineGun(), and TankRocket().
G_SetMovedir()
void G_SetMovedir (vec3_t angles, vec3_t movedir)
Definition at line 314 of file g_utils.c.
 {
     if (VectorCompare (angles, VEC_UP))
     {
         VectorCopy (MOVEDIR_UP, movedir);
     }
     else if (VectorCompare (angles, VEC_DOWN))
     {
         VectorCopy (MOVEDIR_DOWN, movedir);
     }
     else
     {
         AngleVectors (angles, movedir, NULL, NULL);
     }
     VectorClear (angles);
 }
Referenced by InitTrigger(), SP_func_button(), SP_func_door(), SP_func_water(), SP_target_actor(), SP_target_blaster(), SP_target_spawner(), SP_target_splash(), SP_trigger_multiple(), and target_laser_start().
G_Spawn()
edict_t* G_Spawn (void)
Definition at line 420 of file g_utils.c.
 {
     int         i;
     edict_t     *e;
     e = &g_edicts[(int)maxclients->value+1];
     for ( i=maxclients->value+1 ; i<globals.num_edicts ; i++, e++)
     {
         // the first couple seconds of server time can involve a lot of
         // freeing and allocating, so relax the replacement policy
         if (!e->inuse && ( e->freetime < 2 || level.time - e->freetime > 0.5 ) )
         {
             G_InitEdict (e);
             return e;
         }
     }
     if (i == game.maxentities)
         gi.error ("ED_Alloc: no free edicts");
     globals.num_edicts++;
     G_InitEdict (e);
     return e;
 }
Referenced by ai_run(), Cmd_Give_f(), CreateTargetChangeLevel(), CTFFireGrapple(), CTFSetupTechSpawn(), Drop_Item(), fire_bfg(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_rocket(), InitBodyQue(), jorg_dead(), makron_die(), MakronToss(), plat_spawn_inside_trigger(), PlayerNoise(), PlayerTrail_Init(), SP_CreateCoopSpots(), SP_misc_teleporter(), SP_trigger_teleport(), SpawnEntities(), SpawnTech(), Think_SpawnDoorTrigger(), ThrowDebris(), ThrowGib(), and use_target_spawner().
G_TouchSolids()
void G_TouchSolids (edict_t * ent)
Definition at line 508 of file g_utils.c.
 {
     int         i, num;
     edict_t     *touch[MAX_EDICTS], *hit;
     num = gi.BoxEdicts (ent->absmin, ent->absmax, touch
         , MAX_EDICTS, AREA_SOLID);
     // be careful, it is possible to have an entity in this
     // list removed before we get to it (killtriggered)
     for (i=0 ; i<num ; i++)
     {
         hit = touch[i];
         if (!hit->inuse)
             continue;
         if (ent->touch)
             ent->touch (hit, ent, NULL, NULL);
         if (!ent->inuse)
             break;
     }
 }
G_TouchTriggers()
void G_TouchTriggers (edict_t * ent)
Definition at line 475 of file g_utils.c.
 {
     int         i, num;
     edict_t     *touch[MAX_EDICTS], *hit;
     // dead things don't activate triggers!
     if ((ent->client || (ent->svflags & SVF_MONSTER)) && (ent->health <= 0))
         return;
     num = gi.BoxEdicts (ent->absmin, ent->absmax, touch
         , MAX_EDICTS, AREA_TRIGGERS);
     // be careful, it is possible to have an entity in this
     // list removed before we get to it (killtriggered)
     for (i=0 ; i<num ; i++)
     {
         hit = touch[i];
         if (!hit->inuse)
             continue;
         if (!hit->touch)
             continue;
         hit->touch (hit, ent, NULL, NULL);
     }
 }
Referenced by ClientThink(), SV_movestep(), SV_Physics_Step(), SV_Push(), SV_PushEntity(), and SV_StepDirection().
G_UseTargets()
void G_UseTargets (edict_t * ent, edict_t * activator)
Definition at line 173 of file g_utils.c.
 {
     edict_t     *t;
 //
 // check for a delay
 //
     if (ent->delay)
     {
     // create a temp object to fire at a later time
         t = G_Spawn();
         t->classname = "DelayedUse";
         t->nextthink = level.time + ent->delay;
         t->think = Think_Delay;
         t->activator = activator;
         if (!activator)
             gi.dprintf ("Think_Delay with no activator\n");
         t->message = ent->message;
         t->target = ent->target;
         t->killtarget = ent->killtarget;
         return;
     }
 //
 // print the message
 //
     if ((ent->message) && !(activator->svflags & SVF_MONSTER))
     {
         gi.centerprintf (activator, "%s", ent->message);
         if (ent->noise_index)
             gi.sound (activator, CHAN_AUTO, ent->noise_index, 1, ATTN_NORM, 0);
         else
             gi.sound (activator, CHAN_AUTO, gi.soundindex ("misc/talk1.wav"), 1, ATTN_NORM, 0);
     }
 //
 // kill killtargets
 //
     if (ent->killtarget)
     {
         t = NULL;
         while ((t = G_Find (t, FOFS(targetname), ent->killtarget)))
         {
             G_FreeEdict (t);
             if (!ent->inuse)
             {
                 gi.dprintf("entity was removed while using killtargets\n");
                 return;
             }
         }
     }
 //
 // fire targets
 //
     if (ent->target)
     {
         t = NULL;
         while ((t = G_Find (t, FOFS(targetname), ent->target)))
         {
             // doors fire area portals in a specific way
             if (!Q_stricmp(t->classname, "func_areaportal") &&
                 (!Q_stricmp(ent->classname, "func_door") || !Q_stricmp(ent->classname, "func_door_rotating")))
                 continue;
             if (t == ent)
             {
                 gi.dprintf ("WARNING: Entity used itself.\n");
             }
             else
             {
                 if (t->use)
                     t->use (t, ent, activator);
             }
             if (!ent->inuse)
             {
                 gi.dprintf("entity was removed while using targets\n");
                 return;
             }
         }
     }
 }
Referenced by button_wait(), door_go_up(), func_clock_think(), func_explosive_explode(), func_timer_think(), misc_viper_bomb_touch(), monster_death_use(), multi_trigger(), path_corner_touch(), point_combat_touch(), SP_trigger_always(), target_actor_touch(), target_crosslevel_target_think(), target_explosion_explode(), Touch_Item(), train_wait(), trigger_key_use(), trigger_relay_use(), use_target_goal(), and use_target_secret().
KillBox()
qboolean KillBox (edict_t * ent)
Definition at line 549 of file g_utils.c.
 {
     trace_t     tr;
     while (1)
     {
         tr = gi.trace (ent->s.origin, ent->mins, ent->maxs, ent->s.origin, NULL, MASK_PLAYERSOLID);
         if (!tr.ent)
             break;
         // nail it
         T_Damage (tr.ent, ent, ent, vec3_origin, ent->s.origin, vec3_origin, 100000, 0, DAMAGE_NO_PROTECTION, MOD_TELEFRAG);
         // if we didn't kill it, fail
         if (tr.ent->solid)
             return false;
     }
     return true;        // all clear
 }
Referenced by func_explosive_spawn(), func_object_use(), func_wall_use(), monster_triggered_spawn(), old_teleporter_touch(), PutClientInServer(), teleporter_touch(), use_killbox(), and use_target_spawner().
Think_Delay()
void Think_Delay (edict_t * ent)
Definition at line 151 of file g_utils.c.
 {
     G_UseTargets (ent, ent->activator);
     G_FreeEdict (ent);
 }
tv()
float* tv (float x, float y, float z)
Definition at line 266 of file g_utils.c.
 {
     static  int     index;
     static  vec3_t  vecs[8];
     float   *v;
     // use an array so that multiple tempvectors won't collide
     // for a while
     v = vecs[index];
     index = (index + 1)&7;
     v[0] = x;
     v[1] = y;
     v[2] = z;
     return v;
 }
Referenced by CTFFlagSetup(), and droptofloor().
vectoangles()
void vectoangles (vec3_t value1, vec3_t angles)
Definition at line 356 of file g_utils.c.
 {
     float   forward;
     float   yaw, pitch;
     if (value1[1] == 0 && value1[0] == 0)
     {
         yaw = 0;
         if (value1[2] > 0)
             pitch = 90;
         else
             pitch = 270;
     }
     else
     {
         if (value1[0])
             yaw = (int) (atan2(value1[1], value1[0]) * 180 / M_PI);
         else if (value1[1] > 0)
             yaw = 90;
         else
             yaw = -90;
         if (yaw < 0)
             yaw += 360;
         forward = sqrt (value1[0]*value1[0] + value1[1]*value1[1]);
         pitch = (int) (atan2(value1[2], forward) * 180 / M_PI);
         if (pitch < 0)
             pitch += 360;
     }
     angles[PITCH] = -pitch;
     angles[YAW] = yaw;
     angles[ROLL] = 0;
 }
Referenced by CTFFireGrapple(), CTFGrappleDrawCable(), fire_bfg(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_lead(), fire_rocket(), gib_touch(), MakronHyperblaster(), medic_cable_attack(), misc_viper_bomb_prethink(), parasite_drain_attack_ok(), soldier_fire(), TankMachineGun(), turret_driver_link(), and turret_driver_think().
vectoyaw()
float vectoyaw (vec3_t vec)
Definition at line 333 of file g_utils.c.
 {
     float   yaw;
     if (/*vec[YAW] == 0 &&*/ vec[PITCH] == 0)
     {
         yaw = 0;
         if (vec[YAW] > 0)
             yaw = 90;
         else if (vec[YAW] < 0)
             yaw = -90;
     }
     else
     {
         yaw = (int) (atan2(vec[YAW], vec[PITCH]) * 180 / M_PI);
         if (yaw < 0)
             yaw += 360;
     }
     return yaw;
 }
Referenced by actor_pain(), actor_use(), ai_charge(), ai_checkattack(), ai_run(), ai_stand(), barrel_touch(), Boss2_CheckAttack(), FindTarget(), HuntTarget(), Jorg_CheckAttack(), Makron_CheckAttack(), MakronSpawn(), monster_start_go(), path_corner_touch(), PlayerTrail_Add(), and target_actor_touch().
vtos()
char* vtos (vec3_t v)
Definition at line 293 of file g_utils.c.
 {
     static  int     index;
     static  char    str[8][32];
     char    *s;
     // use an array so that multiple vtos won't collide
     s = str[index];
     index = (index + 1)&7;
     Com_sprintf (s, 32, "(%i %i %i)", (int)v[0], (int)v[1], (int)v[2]);
     return s;
 }
Referenced by actor_use(), CTFFlagSetup(), droptofloor(), flymonster_start_go(), FoundTarget(), monster_start(), monster_start_go(), point_combat_touch(), SP_func_clock(), SP_func_door_rotating(), SP_func_timer(), SP_func_train(), SP_misc_actor(), SP_misc_strogg_ship(), SP_misc_viper(), SP_path_corner(), SP_target_actor(), SP_target_changelevel(), SP_target_earthquake(), SP_target_help(), SP_target_lightramp(), SP_target_speaker(), SP_trigger_gravity(), SP_trigger_key(), SP_trigger_once(), SP_turret_driver(), SpawnItem(), target_laser_start(), target_lightramp_use(), train_next(), turret_breach_finish_init(), and walkmonster_start_go().
Variable Documentation
MOVEDIR_DOWN
vec3_t MOVEDIR_DOWN = {0, 0, -1}
Definition at line 312 of file g_utils.c.
MOVEDIR_UP
vec3_t MOVEDIR_UP = {0, 0, 1}
Definition at line 310 of file g_utils.c.
VEC_DOWN
vec3_t VEC_DOWN = {0, -2, 0}
Definition at line 311 of file g_utils.c.
VEC_UP
vec3_t VEC_UP = {0, -1, 0}
Definition at line 309 of file g_utils.c.