vkQuake2 doxygen: C:/entry/dev/vq2/src/win32/rw_dib.c File Reference
rw_dib.c File Reference
#include "..\ref_soft\r_local.h"
#include "rw_win.h"
Classes
struct dibinfo
struct identitypalette_t
Macros
#define NUM_SYS_COLORS (sizeof(s_syspalindices) / sizeof(int))
Typedefs
typedef struct dibinfo dibinfo_t
Functions
static void DIB_SaveSystemColors (void)
static void DIB_RestoreSystemColors (void)
qboolean DIB_Init (unsigned char **ppbuffer, int *ppitch)
void DIB_SetPalette (const unsigned char *_pal)
void DIB_Shutdown (void)
Variables
static qboolean s_systemcolors_saved
static HGDIOBJ previously_selected_GDI_obj
static int s_syspalindices []
static int s_oldsyscolors [NUM_SYS_COLORS]
static identitypalette_t s_ipal
Macro Definition Documentation
NUM_SYS_COLORS
#define NUM_SYS_COLORS (sizeof(s_syspalindices) / sizeof(int))
Definition at line 61 of file rw_dib.c.
Typedef Documentation
dibinfo_t
typedef struct dibinfo dibinfo_t
Function Documentation
DIB_Init()
qboolean DIB_Init (unsigned char ** ppbuffer, int * ppitch)
Definition at line 88 of file rw_dib.c.
 {
     dibinfo_t   dibheader;
     BITMAPINFO *pbmiDIB = ( BITMAPINFO * ) &dibheader;
     DEVMODE gdevmode;  //qb: for fullscreen
     int i;
     memset( &dibheader, 0, sizeof( dibheader ) );
     /*
     ** grab a DC
     */
     if ( !sww_state.hDC )
     {
         if ( ( sww_state.hDC = GetDC( sww_state.hWnd ) ) == NULL )
             return false;
     }
     /*
     ** figure out if we're running in an 8-bit display mode
     */
     if ( GetDeviceCaps( sww_state.hDC, RASTERCAPS ) & RC_PALETTE )
     {
         sww_state.palettized = true;
         // save system colors
         if ( !s_systemcolors_saved )
         {
             DIB_SaveSystemColors();
             s_systemcolors_saved = true;
         }
     }
     else
     {
         sww_state.palettized = false;
     }
     vid.width = (int)(vid.width / 4) * 4; //qb: multiple of 4 required for DIB
     /*
     ** fill in the BITMAPINFO struct
     */
     pbmiDIB->bmiHeader.biSize          = sizeof(BITMAPINFOHEADER);
     pbmiDIB->bmiHeader.biWidth         = vid.width;
     pbmiDIB->bmiHeader.biHeight        = vid.height;
     pbmiDIB->bmiHeader.biPlanes        = 1;
     pbmiDIB->bmiHeader.biBitCount      = 8;
     pbmiDIB->bmiHeader.biCompression   = BI_RGB;
     pbmiDIB->bmiHeader.biSizeImage     = 0;
     pbmiDIB->bmiHeader.biXPelsPerMeter = 0;
     pbmiDIB->bmiHeader.biYPelsPerMeter = 0;
     pbmiDIB->bmiHeader.biClrUsed       = 256;
     pbmiDIB->bmiHeader.biClrImportant  = 256;
     /*
     ** fill in the palette
     */
     for ( i = 0; i < 256; i++ )
     {
         dibheader.acolors[i].rgbRed   = ( d_8to24table[i] >> 0 )  & 0xff;
         dibheader.acolors[i].rgbGreen = ( d_8to24table[i] >> 8 )  & 0xff;
         dibheader.acolors[i].rgbBlue  = ( d_8to24table[i] >> 16 ) & 0xff;
     }
     /*
     ** create the DIB section
     */
     sww_state.hDIBSection = CreateDIBSection( sww_state.hDC,
                                              pbmiDIB,
                                              DIB_RGB_COLORS,
                                              &sww_state.pDIBBase,
                                              NULL,
                                              0 );
     if ( sww_state.hDIBSection == NULL )
     {
         ri.Con_Printf( PRINT_ALL, "DIB_Init() - CreateDIBSection failed\n" );
         goto fail;
     }
     if ( pbmiDIB->bmiHeader.biHeight > 0 )
     {
         // bottom up
         *ppbuffer   = sww_state.pDIBBase + ( vid.height - 1 ) * vid.width;
         *ppitch     = -vid.width;
     }
     else
     {
         // top down
         *ppbuffer   = sww_state.pDIBBase;
         *ppitch     = vid.width;
     }
     MONITORINFOEX monInfo;
     memset(&monInfo, 0, sizeof(MONITORINFOEX));
     monInfo.cbSize = sizeof(MONITORINFOEX);
     GetMonitorInfo( MonitorFromWindow(sww_state.hWnd, MONITOR_DEFAULTTOPRIMARY), (LPMONITORINFO)&monInfo );
     ChangeDisplaySettingsEx(monInfo.szDevice, NULL, NULL, 0, NULL);
     if (vid_fullscreen->value) //qb: fullscreen dib
     {
         RECT        WindowRect;
         DWORD       WindowStyle, ExWindowStyle;
         WindowRect.top = monInfo.rcMonitor.top;
         WindowRect.left = monInfo.rcMonitor.left;
         WindowRect.right = vid.width;
         WindowRect.bottom = vid.height;
         memset(&gdevmode, 0, sizeof(gdevmode));
         gdevmode.dmFields = DM_PELSWIDTH | DM_PELSHEIGHT;
         gdevmode.dmPelsWidth = vid.width;
         gdevmode.dmPelsHeight = vid.height;
         gdevmode.dmSize = sizeof (gdevmode);
         if ( ChangeDisplaySettingsEx( monInfo.szDevice, &gdevmode, NULL, CDS_FULLSCREEN, NULL ) != DISP_CHANGE_SUCCESSFUL )
         {
             //ri.Sys_Error(ERR_FATAL, "Couldn't set fullscreen DIB mode");
             goto fail; //qb: don't panic
         }
         GetMonitorInfo( MonitorFromWindow(sww_state.hWnd, MONITOR_DEFAULTTOPRIMARY), (LPMONITORINFO)&monInfo );
         if (!SetWindowPos(sww_state.hWnd,
             NULL,
             monInfo.rcMonitor.left, monInfo.rcMonitor.top,
             WindowRect.right,
             WindowRect.bottom,
             SWP_NOACTIVATE | SWP_NOCOPYBITS | SWP_NOOWNERZORDER | SWP_NOREPOSITION | SWP_NOZORDER))
         {
             //ri.Sys_Error(ERR_FATAL, "Couldn't resize DIB window");
             goto fail; //qb: don't panic
         }
         WindowStyle = WS_POPUP | WS_SYSMENU | WS_CLIPSIBLINGS | WS_CLIPCHILDREN;
         ExWindowStyle = 0;
         AdjustWindowRectEx(&WindowRect, WindowStyle, FALSE, 0);
         SetWindowLong(sww_state.hWnd, GWL_STYLE, WindowStyle | WS_VISIBLE);
         SetWindowLong(sww_state.hWnd, GWL_EXSTYLE, ExWindowStyle);
     }
     /*
     ** clear the DIB memory buffer
     */
     memset(sww_state.pDIBBase, 0x00, vid.width * vid.height);  //qb: do black, was 0xff
     if ( ( sww_state.hdcDIBSection = CreateCompatibleDC( sww_state.hDC ) ) == NULL )
     {
         ri.Con_Printf( PRINT_ALL, "DIB_Init() - CreateCompatibleDC failed\n" );
         goto fail;
     }
     if ( ( previously_selected_GDI_obj = SelectObject( sww_state.hdcDIBSection, sww_state.hDIBSection ) ) == NULL )
     {
         ri.Con_Printf( PRINT_ALL, "DIB_Init() - SelectObject failed\n" );
         goto fail;
     }
     return true;
 fail:
     DIB_Shutdown();
     return false;
 }
Referenced by SWimp_InitGraphics().
DIB_RestoreSystemColors()
static void DIB_RestoreSystemColors (void) static
Definition at line 417 of file rw_dib.c.
 {
     SetSystemPaletteUse( sww_state.hDC, SYSPAL_STATIC );
     SetSysColors( NUM_SYS_COLORS, s_syspalindices, s_oldsyscolors );
 }
Referenced by DIB_Shutdown().
DIB_SaveSystemColors()
static void DIB_SaveSystemColors (void) static
Definition at line 423 of file rw_dib.c.
 {
     int i;
     for ( i = 0; i < NUM_SYS_COLORS; i++ )
         s_oldsyscolors[i] = GetSysColor( s_syspalindices[i] );
 }
Referenced by DIB_Init().
DIB_SetPalette()
void DIB_SetPalette (const unsigned char * _pal)
Definition at line 269 of file rw_dib.c.
 {
     const unsigned char *pal = _pal;
     LOGPALETTE      *pLogPal = ( LOGPALETTE * ) &s_ipal;
     RGBQUAD         colors[256];
     int             i;
     int             ret;
     HDC             hDC = sww_state.hDC;
     /*
     ** set the DIB color table
     */
     if ( sww_state.hdcDIBSection )
     {
         for ( i = 0; i < 256; i++, pal += 4 )
         {
             colors[i].rgbRed   = pal[0];
             colors[i].rgbGreen = pal[1];
             colors[i].rgbBlue  = pal[2];
             colors[i].rgbReserved = 0;
         }
         colors[0].rgbRed = 0;
         colors[0].rgbGreen = 0;
         colors[0].rgbBlue = 0;
         colors[255].rgbRed = 0xff;
         colors[255].rgbGreen = 0xff;
         colors[255].rgbBlue = 0xff;
         if ( SetDIBColorTable( sww_state.hdcDIBSection, 0, 256, colors ) == 0 )
         {
             ri.Con_Printf( PRINT_ALL, "DIB_SetPalette() - SetDIBColorTable failed\n" );
         }
     }
     /*
     ** for 8-bit color desktop modes we set up the palette for maximum
     ** speed by going into an identity palette mode.
     */
     if ( sww_state.palettized )
     {
         int i;
         HPALETTE hpalOld;
         if ( SetSystemPaletteUse( hDC, SYSPAL_NOSTATIC ) == SYSPAL_ERROR )
         {
             ri.Sys_Error( ERR_FATAL, "DIB_SetPalette() - SetSystemPaletteUse() failed\n" );
         }
         /*
         ** destroy our old palette
         */
         if ( sww_state.hPal )
         {
             DeleteObject( sww_state.hPal );
             sww_state.hPal = 0;
         }
         /*
         ** take up all physical palette entries to flush out anything that's currently
         ** in the palette
         */
         pLogPal->palVersion     = 0x300;
         pLogPal->palNumEntries  = 256;
         for ( i = 0, pal = _pal; i < 256; i++, pal += 4 )
         {
             pLogPal->palPalEntry[i].peRed   = pal[0];
             pLogPal->palPalEntry[i].peGreen = pal[1];
             pLogPal->palPalEntry[i].peBlue  = pal[2];
             pLogPal->palPalEntry[i].peFlags = PC_RESERVED | PC_NOCOLLAPSE;
         }
         pLogPal->palPalEntry[0].peRed       = 0;
         pLogPal->palPalEntry[0].peGreen     = 0;
         pLogPal->palPalEntry[0].peBlue      = 0;
         pLogPal->palPalEntry[0].peFlags     = 0;
         pLogPal->palPalEntry[255].peRed     = 0xff;
         pLogPal->palPalEntry[255].peGreen   = 0xff;
         pLogPal->palPalEntry[255].peBlue    = 0xff;
         pLogPal->palPalEntry[255].peFlags   = 0;
         if ( ( sww_state.hPal = CreatePalette( pLogPal ) ) == NULL )
         {
             ri.Sys_Error( ERR_FATAL, "DIB_SetPalette() - CreatePalette failed(%x)\n", GetLastError() );
         }
         if ( ( hpalOld = SelectPalette( hDC, sww_state.hPal, FALSE ) ) == NULL )
         {
             ri.Sys_Error( ERR_FATAL, "DIB_SetPalette() - SelectPalette failed(%x)\n",GetLastError() );
         }
         if ( sww_state.hpalOld == NULL )
             sww_state.hpalOld = hpalOld;
         if ( ( ret = RealizePalette( hDC ) ) != pLogPal->palNumEntries )
         {
             ri.Sys_Error( ERR_FATAL, "DIB_SetPalette() - RealizePalette set %d entries\n", ret );
         }
     }
 }
Referenced by SWimp_SetPalette().
DIB_Shutdown()
void DIB_Shutdown (void)
Definition at line 374 of file rw_dib.c.
 {
     if ( sww_state.palettized && s_systemcolors_saved )
         DIB_RestoreSystemColors();
     if ( sww_state.hPal )
     {
         DeleteObject( sww_state.hPal );
         sww_state.hPal = 0;
     }
     if ( sww_state.hpalOld )
     {
         SelectPalette( sww_state.hDC, sww_state.hpalOld, FALSE );
         RealizePalette( sww_state.hDC );
         sww_state.hpalOld = NULL;
     }
     if ( sww_state.hdcDIBSection )
     {
         SelectObject( sww_state.hdcDIBSection, previously_selected_GDI_obj );
         DeleteDC( sww_state.hdcDIBSection );
         sww_state.hdcDIBSection = NULL;
     }
     if ( sww_state.hDIBSection )
     {
         DeleteObject( sww_state.hDIBSection );
         sww_state.hDIBSection = NULL;
         sww_state.pDIBBase = NULL;
     }
     if ( sww_state.hDC )
     {
         ReleaseDC( sww_state.hWnd, sww_state.hDC );
         sww_state.hDC = 0;
     }
 }
Referenced by DIB_Init(), and SWimp_Shutdown().
Variable Documentation
previously_selected_GDI_obj
HGDIOBJ previously_selected_GDI_obj static
Definition at line 35 of file rw_dib.c.
Referenced by DIB_Init(), and DIB_Shutdown().
s_ipal
identitypalette_t s_ipal static
Definition at line 78 of file rw_dib.c.
Referenced by DIB_SetPalette().
s_oldsyscolors
int s_oldsyscolors[NUM_SYS_COLORS] static
Definition at line 63 of file rw_dib.c.
Referenced by DIB_RestoreSystemColors(), and DIB_SaveSystemColors().
s_syspalindices
int s_syspalindices[] static
Initial value:
=
{
  COLOR_ACTIVEBORDER,
  COLOR_ACTIVECAPTION,
  COLOR_APPWORKSPACE,
  COLOR_BACKGROUND,
  COLOR_BTNFACE,
  COLOR_BTNSHADOW,
  COLOR_BTNTEXT,
  COLOR_CAPTIONTEXT,
  COLOR_GRAYTEXT,
  COLOR_HIGHLIGHT,
  COLOR_HIGHLIGHTTEXT,
  COLOR_INACTIVEBORDER,
  COLOR_INACTIVECAPTION,
  COLOR_MENU,
  COLOR_MENUTEXT,
  COLOR_SCROLLBAR,
  COLOR_WINDOW,
  COLOR_WINDOWFRAME,
  COLOR_WINDOWTEXT
}
Definition at line 37 of file rw_dib.c.
Referenced by DIB_RestoreSystemColors(), and DIB_SaveSystemColors().
s_systemcolors_saved
qboolean s_systemcolors_saved static
Definition at line 33 of file rw_dib.c.
Referenced by DIB_Init(), and DIB_Shutdown().