vq2 doxygen: C:/entry/syn/github/vq2/client/snd_miniaudio.h File Reference
snd_miniaudio.h File Reference
Functions
void Miniaudio_Init (void)
void Miniaudio_Play (int track, qboolean looping)
void Miniaudio_Stop (void)
void Miniaudio_Update (void)
void Miniaudio_Shutdown (void)
Function Documentation
Miniaudio_Init()
void Miniaudio_Init (void)
Definition at line 195 of file snd_miniaudio.c.
 {
     cd_nocd = Cvar_Get("cd_nocd", "0", CVAR_ARCHIVE);
     cd_loopcount = Cvar_Get("cd_loopcount", "4", 0);
     cd_looptrack = Cvar_Get("cd_looptrack", "11", 0);
     enabled = true;
     paused = false;
 #ifdef __APPLE__
     bufferSizeInFrames = Cvar_VariableValue("s_chunksize") * sizeof(float) / GetBytesPerSampleFrame();
 #endif
     Cmd_AddCommand("miniaudio", Miniaudio_f);
 }
Referenced by CL_Init().
Miniaudio_Play()
void Miniaudio_Play (int track, qboolean looping)
Definition at line 225 of file snd_miniaudio.c.
 {
     ma_result result;
     ma_device_config deviceConfig;
     if (!enabled || playTrack == track)
         return;
     Miniaudio_Stop();
     // ignore invalid tracks
     if (track < 1)
         return;
     result = LoadTrack(FS_Gamedir(), track);
     // try the baseq2 folder if loading the track from a custom gamedir failed
     if (result != MA_SUCCESS && Q_stricmp(FS_Gamedir(), "./"BASEDIRNAME) != 0)
     {
         result = LoadTrack(BASEDIRNAME, track);
     }
     if (result != MA_SUCCESS)
     {
         Com_Printf("Failed to open %s/music/track%s%i.[ogg/flac/mp3/wav]: error %i\n", FS_Gamedir(), track < 10 ? "0" : "", track, result);
         return;
     }
     deviceConfig = ma_device_config_init(ma_device_type_playback);
     deviceConfig.playback.format = decoder.outputFormat;
     deviceConfig.playback.channels = decoder.outputChannels;
     deviceConfig.sampleRate = decoder.outputSampleRate;
     deviceConfig.dataCallback = data_callback;
     deviceConfig.pUserData = &decoder;
 #ifdef __APPLE__
     deviceConfig.bufferSizeInFrames = bufferSizeInFrames;
     deviceConfig.periods = 1;
 #endif
     if (ma_device_init(NULL, &deviceConfig, &device) != MA_SUCCESS) {
         Com_Printf("Failed to open playback device: error %i\n", result);
         ma_decoder_uninit(&decoder);
         return;
     }
     if (ma_device_start(&device) != MA_SUCCESS) {
         Com_Printf("Failed to start playback device: error %i\n", result);
         ma_device_uninit(&device);
         ma_decoder_uninit(&decoder);
         return;
     }
     loopcounter = 0;
     playTrack = track;
     playLooping = looping;
     paused = false;
     trackFinished = false;
     if (Cvar_VariableValue("cd_nocd"))
         Miniaudio_Pause();
 }
Referenced by CL_ParseConfigString(), CL_PrepRefresh(), Miniaudio_f(), and Miniaudio_Update().
Miniaudio_Shutdown()
void Miniaudio_Shutdown (void)
Definition at line 352 of file snd_miniaudio.c.
 {
     Miniaudio_Stop();
     Cmd_RemoveCommand("miniaudio");
 }
Referenced by CL_Shutdown().
Miniaudio_Stop()
void Miniaudio_Stop (void)
Definition at line 287 of file snd_miniaudio.c.
 {
     if (!enabled || !ma_device_is_started(&device))
         return;
     paused = false;
     playTrack = 0;
     ma_device_uninit(&device);
     ma_decoder_uninit(&decoder);
 }
Referenced by Miniaudio_f(), Miniaudio_Play(), Miniaudio_Shutdown(), Miniaudio_Update(), SCR_BeginLoadingPlaque(), and SCR_PlayCinematic().
Miniaudio_Update()
void Miniaudio_Update (void)
Definition at line 299 of file snd_miniaudio.c.
 {
     if (cd_nocd->value != !enabled)
     {
         if (cd_nocd->value)
         {
             Miniaudio_Pause();
             enabled = false;
         }
         else
         {
             enabled = true;
             int track = atoi(cl.configstrings[CS_CDTRACK]);
             if (!paused || playTrack != track)
             {
                 if ((playTrack == 0 && !playLooping) || (playTrack > 0 && playTrack != track))
                     Miniaudio_Play(track, true);
                 else
                     Miniaudio_Play(playTrack, playLooping);
             }
             else
                 Miniaudio_Resume();
         }
     }
     if (enabled && ma_device_is_started(&device) && trackFinished)
     {
         trackFinished = false;
         if (playLooping)
         {
             // if the track has played the given number of times,
             // go to the ambient track
             if (++loopcounter >= cd_loopcount->value)
             {
                 // ambient track will be played for the first time, so we need to load it
                 if (loopcounter == cd_loopcount->value)
                 {
                     Miniaudio_Stop();
                     Miniaudio_Play(cd_looptrack->value, true);
                 }
                 else
                 {
                     ma_decoder_seek_to_pcm_frame(&decoder, 0);
                 }
             }
             else
             {
                 ma_decoder_seek_to_pcm_frame(&decoder, 0);
             }
         }
     }
 }
Referenced by CL_Frame().