vq2 doxygen: C:/entry/syn/github/vq2/win32/rw_imp.c File Reference
rw_imp.c File Reference
#include "..\ref_soft\r_local.h"
#include "rw_win.h"
#include "winquake.h"
Macros
#define WINDOW_CLASS_NAME "Quake 2"
Functions
void VID_CreateWindow (int width, int height, int stylebits)
int SWimp_Init (void *hInstance, void *wndProc)
static qboolean SWimp_InitGraphics (void)
void SWimp_EndFrame (void)
rserr_t SWimp_SetMode (int *pwidth, int *pheight, int mode, qboolean fullscreen)
void SWimp_SetPalette (const unsigned char *palette)
void SWimp_Shutdown (void)
void SWimp_AppActivate (qboolean active)
void Sys_MakeCodeWriteable (unsigned long startaddr, unsigned long length)
void Sys_SetFPCW (void)
Variables
swwstate_t sww_state
Macro Definition Documentation
WINDOW_CLASS_NAME
#define WINDOW_CLASS_NAME "Quake 2"
Definition at line 43 of file rw_imp.c.
Function Documentation
SWimp_AppActivate()
void SWimp_AppActivate (qboolean active)
Definition at line 292 of file rw_imp.c.
 {
     if ( active )
     {
         if ( sww_state.hWnd )
         {
             SetForegroundWindow( sww_state.hWnd );
             ShowWindow( sww_state.hWnd, SW_RESTORE );
         }
     }
     else
     {
         if ( sww_state.hWnd )
         {
             if ( sww_state.initializing )
                 return;
             if ( vid_fullscreen->value )
                 ShowWindow( sww_state.hWnd, SW_MINIMIZE );
         }
     }
 }
Referenced by GetRefAPI().
SWimp_EndFrame()
void SWimp_EndFrame (void)
Definition at line 163 of file rw_imp.c.
 {
     if (sww_state.palettized)
     {
         //          holdpal = SelectPalette(hdcScreen, hpalDIB, FALSE);
         //          RealizePalette(hdcScreen);
     }
     BitBlt(sww_state.hDC,
         0, 0,
         vid.width,
         vid.height,
         sww_state.hdcDIBSection,
         0, 0,
         SRCCOPY);
     if (sww_state.palettized)
     {
         //          SelectPalette(hdcScreen, holdpal, FALSE);
     }
 }
Referenced by GetRefAPI(), and R_CinematicSetPalette().
SWimp_Init()
int SWimp_Init (void * hInstance, void * wndProc)
Definition at line 118 of file rw_imp.c.
 {
     sww_state.hInstance = ( HINSTANCE ) hInstance;
     sww_state.wndproc = wndProc;
     return true;
 }
Referenced by R_Init().
SWimp_InitGraphics()
static qboolean SWimp_InitGraphics (void) static
Definition at line 135 of file rw_imp.c.
 {
     // free resources in use
     SWimp_Shutdown ();
     // create a new window
     VID_CreateWindow (vid.width, vid.height, WINDOW_STYLE);
     // initialize the appropriate subsystem
     //qb: nuke ddraw
     if (!DIB_Init(&vid.buffer, &vid.rowbytes))
     {
         vid.buffer = 0;
         vid.rowbytes = 0;
         return false;
     }
     return true;
 }
Referenced by SWimp_SetMode().
SWimp_SetMode()
rserr_t SWimp_SetMode (int * pwidth, int * pheight, int mode, qboolean fullscreen)
Definition at line 189 of file rw_imp.c.
 {
     const char *win_fs[] = { "W", "FS" };
     rserr_t retval = rserr_ok;
     ri.Con_Printf (PRINT_ALL, "setting mode %d:", mode );
     if ( !ri.Vid_GetModeInfo( pwidth, pheight, mode ) )
     {
         ri.Con_Printf( PRINT_ALL, " invalid mode\n" );
         return rserr_invalid_mode;
     }
     ri.Con_Printf(PRINT_ALL, " %d %d %s\n", *pwidth, *pheight, win_fs[fullscreen]);
     sww_state.initializing = true;
     if (fullscreen) //qb: get rid of 'fullscreen'.
     {
         if (!SWimp_InitGraphics())
         {
             ri.Cvar_SetValue("vid_fullscreen", !fullscreen);  //qb: added
             vid_fullscreen->modified = true;
             if (SWimp_InitGraphics())
             {
                 // mode is legal but not as fullscreen
                 retval = rserr_invalid_fullscreen;
             }
             else
             {
                 // failed to set a valid mode in windowed mode
                 retval = rserr_unknown;
             }
         }
     }
     else
     {
         // failure to set a valid mode in windowed mode
         if (!SWimp_InitGraphics())
         {
             sww_state.initializing = true;
             return rserr_unknown;
         }
     }
     sw_state.fullscreen = fullscreen;
 #if 0
     if ( retval != rserr_unknown )
     {
         if ( retval == rserr_invalid_fullscreen ||
              ( retval == rserr_ok && !fullscreen ) )
         {
             SetWindowLong( sww_state.hWnd, GWL_STYLE, WINDOW_STYLE );
         }
     }
 #endif
     R_GammaCorrectAndSetPalette( ( const unsigned char * ) d_8to24table );
     sww_state.initializing = true;
     return retval;
 }
Referenced by R_BeginFrame().
SWimp_SetPalette()
void SWimp_SetPalette (const unsigned char * palette)
Definition at line 257 of file rw_imp.c.
 {
     // MGL - what the fuck was kendall doing here?!
     // clear screen to black and change palette
     //  for (i=0 ; i<vid.height ; i++)
     //      memset (vid.buffer + i*vid.rowbytes, 0, vid.width);
     if ( !palette )
         palette = ( const unsigned char * ) sw_state.currentpalette;
     DIB_SetPalette((const unsigned char *)palette);
 }
Referenced by R_GammaCorrectAndSetPalette().
SWimp_Shutdown()
void SWimp_Shutdown (void)
Definition at line 274 of file rw_imp.c.
 {
     ri.Con_Printf( PRINT_ALL, "Shutting down SW imp\n" );
     DIB_Shutdown();
     if ( sww_state.hWnd )
     {
         ri.Con_Printf( PRINT_ALL, "...destroying window\n" );
         ShowWindow( sww_state.hWnd, SW_SHOWNORMAL );    // prevents leaving empty slots in the taskbar
         DestroyWindow (sww_state.hWnd);
         sww_state.hWnd = NULL;
         UnregisterClass (WINDOW_CLASS_NAME, sww_state.hInstance);
     }
 }
Referenced by R_Shutdown(), and SWimp_InitGraphics().
Sys_MakeCodeWriteable()
void Sys_MakeCodeWriteable (unsigned long startaddr, unsigned long length)
Definition at line 322 of file rw_imp.c.
 {
     DWORD  flOldProtect;
     if (!VirtualProtect((LPVOID)startaddr, length, PAGE_READWRITE, &flOldProtect))
         ri.Sys_Error(ERR_FATAL, "Protection change failed\n");
 }
Referenced by D_Patch(), and R_Init().
Sys_SetFPCW()
void Sys_SetFPCW (void)
Definition at line 351 of file rw_imp.c.
 {
 }
Referenced by R_Init().
VID_CreateWindow()
void VID_CreateWindow (int width, int height, int stylebits)
Definition at line 45 of file rw_imp.c.
 {
     WNDCLASS        wc;
     RECT            r;
     cvar_t          *vid_xpos, *vid_ypos, *vid_fullscreen;
     int             x, y, w, h;
     int             exstyle;
     vid_xpos = ri.Cvar_Get ("vid_xpos", "0", 0);
     vid_ypos = ri.Cvar_Get ("vid_ypos", "0", 0);
     vid_fullscreen = ri.Cvar_Get ("vid_fullscreen", "0", CVAR_ARCHIVE );
     if ( vid_fullscreen->value )
         exstyle = WS_EX_TOPMOST;
     else
         exstyle = 0;
     /* Register the frame class */
     wc.style         = 0;
     wc.lpfnWndProc   = (WNDPROC)sww_state.wndproc;
     wc.cbClsExtra    = 0;
     wc.cbWndExtra    = 0;
     wc.hInstance     = sww_state.hInstance;
     wc.hIcon         = 0;
     wc.hCursor       = LoadCursor (NULL,IDC_ARROW);
     wc.hbrBackground = (void *)COLOR_GRAYTEXT;
     wc.lpszMenuName  = 0;
     wc.lpszClassName = WINDOW_CLASS_NAME;
     if (!RegisterClass (&wc) )
         ri.Sys_Error (ERR_FATAL, "Couldn't register window class");
     r.left = 0;
     r.top = 0;
     r.right  = width;
     r.bottom = height;
     AdjustWindowRect (&r, stylebits, FALSE);
     w = r.right - r.left;
     h = r.bottom - r.top;
     x = vid_xpos->value;
     y = vid_ypos->value;
     sww_state.hWnd = CreateWindowEx (
         exstyle,
          WINDOW_CLASS_NAME,
          "Quake 2 (Software) "CPUSTRING,
          stylebits,
          x, y, w, h,
          NULL,
          NULL,
          sww_state.hInstance,
          NULL);
     if (!sww_state.hWnd)
         ri.Sys_Error (ERR_FATAL, "Couldn't create window");
     ShowWindow( sww_state.hWnd, SW_SHOWNORMAL );
     UpdateWindow( sww_state.hWnd );
     SetForegroundWindow( sww_state.hWnd );
     SetFocus( sww_state.hWnd );
     // let the sound and input subsystems know about the new window
     ri.Vid_NewWindow (width, height);
 }
Referenced by SWimp_InitGraphics().
Variable Documentation
sww_state
swwstate_t sww_state
Definition at line 38 of file rw_imp.c.
Referenced by DDRAW_Init(), DDRAW_SetPalette(), DDRAW_Shutdown(), DIB_Init(), DIB_RestoreSystemColors(), DIB_SetPalette(), DIB_Shutdown(), SWimp_AppActivate(), SWimp_EndFrame(), SWimp_Init(), SWimp_SetMode(), SWimp_Shutdown(), and VID_CreateWindow().