vq2 doxygen: C:/entry/syn/github/vq2/win32/vk_imp.c File Reference
vk_imp.c File Reference
#include <assert.h>
#include <windows.h>
#include "../ref_vk/vk_local.h"
#include "vk_win.h"
#include "winquake.h"
Macros
#define WINDOW_CLASS_NAME "Quake 2"
#define OSR2_BUILD_NUMBER 1111
Functions
qboolean VID_CreateWindow (int width, int height, qboolean fullscreen)
void Vkimp_GetSurfaceExtensions (char **extensions, uint32_t *extCount)
VkResult Vkimp_CreateSurface ()
rserr_t Vkimp_SetMode (int *pwidth, int *pheight, int mode, qboolean fullscreen)
void Vkimp_Shutdown (void)
qboolean Vkimp_Init (void *hinstance, void *wndproc)
void Vkimp_BeginFrame (float camera_separation)
void Vkimp_EndFrame (void)
void Vkimp_AppActivate (qboolean active)
Variables
vkwstate_t vkw_state
cvar_t * vid_fullscreen
cvar_t * vid_ref
Macro Definition Documentation
OSR2_BUILD_NUMBER
#define OSR2_BUILD_NUMBER 1111
WINDOW_CLASS_NAME
#define WINDOW_CLASS_NAME "Quake 2"
Definition at line 47 of file vk_imp.c.
Function Documentation
VID_CreateWindow()
qboolean VID_CreateWindow (int width, int height, qboolean fullscreen)
Definition at line 49 of file vk_imp.c.
 {
     WNDCLASS        wc;
     RECT            r;
     cvar_t          *vid_xpos, *vid_ypos;
     int             stylebits;
     int             x, y, w, h;
     int             exstyle;
     /* Register the frame class */
     wc.style         = 0;
     wc.lpfnWndProc   = (WNDPROC)vkw_state.wndproc;
     wc.cbClsExtra    = 0;
     wc.cbWndExtra    = 0;
     wc.hInstance     = vkw_state.hInstance;
     wc.hIcon         = 0;
     wc.hCursor       = LoadCursor (NULL,IDC_ARROW);
     wc.hbrBackground = (void *)COLOR_GRAYTEXT;
     wc.lpszMenuName  = 0;
     wc.lpszClassName = WINDOW_CLASS_NAME;
     if (!RegisterClass (&wc) )
         ri.Sys_Error (ERR_FATAL, "Couldn't register window class");
     if (fullscreen)
     {
         exstyle = WS_EX_TOPMOST;
         stylebits = WS_POPUP|WS_VISIBLE;
     }
     else
     {
         exstyle = 0;
         stylebits = WINDOW_STYLE;
     }
     r.left = 0;
     r.top = 0;
     r.right  = width;
     r.bottom = height;
     AdjustWindowRect (&r, stylebits, FALSE);
     w = r.right - r.left;
     h = r.bottom - r.top;
     vid_xpos = ri.Cvar_Get ("vid_xpos", "0", 0);
     vid_ypos = ri.Cvar_Get ("vid_ypos", "0", 0);
     x = vid_xpos->value;
     y = vid_ypos->value;
     vkw_state.hWnd = CreateWindowEx (
          exstyle,
          WINDOW_CLASS_NAME,
          "Quake 2 (Vulkan) "CPUSTRING,
          stylebits,
          x, y, w, h,
          NULL,
          NULL,
          vkw_state.hInstance,
          NULL);
     if (!vkw_state.hWnd)
         ri.Sys_Error (ERR_FATAL, "Couldn't create window");
     memset( &vkw_state.monInfo, 0, sizeof(MONITORINFOEX) );
     vkw_state.monInfo.cbSize = sizeof(MONITORINFOEX);
     GetMonitorInfo( MonitorFromWindow(vkw_state.hWnd, MONITOR_DEFAULTTOPRIMARY), (LPMONITORINFO)&vkw_state.monInfo );
     if (fullscreen)
     {
         DEVMODE dm;
         memset(&dm, 0, sizeof(dm));
         dm.dmSize = sizeof(dm);
         dm.dmPelsWidth = width;
         dm.dmPelsHeight = height;
         dm.dmFields = DM_PELSWIDTH | DM_PELSHEIGHT;
         if (vk_bitdepth->value != 0)
         {
             dm.dmBitsPerPel = vk_bitdepth->value;
             dm.dmFields |= DM_BITSPERPEL;
         }
         if ( ChangeDisplaySettingsEx( vkw_state.monInfo.szDevice, &dm, NULL, CDS_FULLSCREEN, NULL ) != DISP_CHANGE_SUCCESSFUL )
         {
             return false;
         }
         GetMonitorInfo( MonitorFromWindow(vkw_state.hWnd, MONITOR_DEFAULTTOPRIMARY), (LPMONITORINFO)&vkw_state.monInfo );
         SetWindowPos( vkw_state.hWnd, NULL, vkw_state.monInfo.rcMonitor.left, vkw_state.monInfo.rcMonitor.top, width, height,
             SWP_NOACTIVATE | SWP_NOCOPYBITS | SWP_NOOWNERZORDER | SWP_NOREPOSITION | SWP_NOZORDER );
     }
     else
     {
         ChangeDisplaySettingsEx( vkw_state.monInfo.szDevice, NULL, NULL, 0, NULL );
     }
     ShowWindow( vkw_state.hWnd, SW_SHOW );
     UpdateWindow( vkw_state.hWnd );
     SetForegroundWindow( vkw_state.hWnd );
     SetFocus( vkw_state.hWnd );
     // let the sound and input subsystems know about the new window
     ri.Vid_NewWindow (width, height);
     return true;
 }
Referenced by Vkimp_SetMode().
Vkimp_AppActivate()
void Vkimp_AppActivate (qboolean active)
Definition at line 376 of file vk_imp.c.
 {
     if ( active )
     {
         SetForegroundWindow( vkw_state.hWnd );
         ShowWindow( vkw_state.hWnd, SW_RESTORE );
     }
     else
     {
         if ( vid_fullscreen->value )
             ShowWindow( vkw_state.hWnd, SW_MINIMIZE );
     }
 }
Referenced by GetRefAPI().
Vkimp_BeginFrame()
void Vkimp_BeginFrame (float camera_separation)
Definition at line 350 of file vk_imp.c.
 {
     if (vk_bitdepth->modified)
     {
         if (vk_bitdepth->value != 0 && !vkw_state.allowdisplaydepthchange)
         {
             ri.Cvar_SetValue("vk_bitdepth", 0);
             ri.Con_Printf(PRINT_ALL, "vk_bitdepth requires Win95 OSR2.x or WinNT 4.x\n");
         }
         vk_bitdepth->modified = false;
     }
 }
Referenced by R_BeginFrame().
Vkimp_CreateSurface()
VkResult Vkimp_CreateSurface ()
Definition at line 170 of file vk_imp.c.
 {
     VkWin32SurfaceCreateInfoKHR surfaceCreateInfo = {
         .sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR,
         .pNext = NULL,
         .flags = 0,
         .hinstance = GetModuleHandle(NULL),
         .hwnd = vkw_state.hWnd,
     };
     return vkCreateWin32SurfaceKHR(vk_instance, &surfaceCreateInfo, NULL, &vk_surface);
 }
Referenced by QVk_Init().
Vkimp_EndFrame()
void Vkimp_EndFrame (void)
Definition at line 369 of file vk_imp.c.
 {
 }
Vkimp_GetSurfaceExtensions()
void Vkimp_GetSurfaceExtensions (char ** extensions, uint32_t * extCount)
Definition at line 158 of file vk_imp.c.
 {
     if (extensions)
     {
         extensions[0] = VK_KHR_SURFACE_EXTENSION_NAME;
         extensions[1] = VK_KHR_WIN32_SURFACE_EXTENSION_NAME;
     }
     if (extCount)
         *extCount = 2;
 }
Referenced by QVk_Init().
Vkimp_Init()
qboolean Vkimp_Init (void * hinstance, void * wndproc)
Definition at line 304 of file vk_imp.c.
 {
 #define OSR2_BUILD_NUMBER 1111
     OSVERSIONINFO   vinfo;
     vinfo.dwOSVersionInfoSize = sizeof(vinfo);
     vkw_state.allowdisplaydepthchange = false;
     if ( GetVersionEx( &vinfo) )
     {
         if ( vinfo.dwMajorVersion > 4 )
         {
             vkw_state.allowdisplaydepthchange = true;
         }
         else if ( vinfo.dwMajorVersion == 4 )
         {
             if ( vinfo.dwPlatformId == VER_PLATFORM_WIN32_NT )
             {
                 vkw_state.allowdisplaydepthchange = true;
             }
             else if ( vinfo.dwPlatformId == VER_PLATFORM_WIN32_WINDOWS )
             {
                 if ( LOWORD( vinfo.dwBuildNumber ) >= OSR2_BUILD_NUMBER )
                 {
                     vkw_state.allowdisplaydepthchange = true;
                 }
             }
         }
     }
     else
     {
         ri.Con_Printf( PRINT_ALL, "Vkimp_Init() - GetVersionEx failed\n" );
         return false;
     }
     vkw_state.hInstance = ( HINSTANCE ) hinstance;
     vkw_state.wndproc = wndproc;
     return true;
 }
Referenced by R_Init().
Vkimp_SetMode()
rserr_t Vkimp_SetMode (int * pwidth, int * pheight, int mode, qboolean fullscreen)
Definition at line 186 of file vk_imp.c.
 {
     int width, height;
     const char *win_fs[] = { "W", "FS" };
     ri.Con_Printf( PRINT_ALL, "Initializing Vulkan display\n");
     ri.Con_Printf (PRINT_ALL, "...setting mode %d:", mode );
     if ( !ri.Vid_GetModeInfo( &width, &height, mode ) )
     {
         ri.Con_Printf( PRINT_ALL, " invalid mode\n" );
         return rserr_invalid_mode;
     }
     ri.Con_Printf( PRINT_ALL, " %d %d %s\n", width, height, win_fs[fullscreen] );
     // destroy the existing window
     if (vkw_state.hWnd)
     {
         Vkimp_Shutdown ();
     }
     // do a CDS if needed
     if ( fullscreen )
     {
         ri.Con_Printf( PRINT_ALL, "...attempting fullscreen\n" );
         if ( vk_bitdepth->value != 0 )
         {
             ri.Con_Printf( PRINT_ALL, "...using vk_bitdepth of %d\n", ( int ) vk_bitdepth->value );
         }
         else
         {
             HDC hdc = GetDC( NULL );
             int bitspixel = GetDeviceCaps( hdc, BITSPIXEL );
             ri.Con_Printf( PRINT_ALL, "...using desktop display depth of %d\n", bitspixel );
             ReleaseDC( 0, hdc );
         }
         ri.Con_Printf( PRINT_ALL, "...calling CDS: " );
         if ( VID_CreateWindow(width, height, true) )
         {
             *pwidth = width;
             *pheight = height;
             vk_state.fullscreen = true;
             ri.Con_Printf( PRINT_ALL, "ok\n" );
             return rserr_ok;
         }
         else
         {
             ri.Con_Printf( PRINT_ALL, " failed\n" );
             ri.Con_Printf( PRINT_ALL, "...setting windowed mode\n" );
             DestroyWindow(vkw_state.hWnd);
             UnregisterClass(WINDOW_CLASS_NAME, vkw_state.hInstance);
             VID_CreateWindow(width, height, false);
             *pwidth = width;
             *pheight = height;
             vk_state.fullscreen = false;
             return rserr_invalid_fullscreen;
         }
     }
     else
     {
         ri.Con_Printf( PRINT_ALL, "...setting windowed mode\n" );
         *pwidth = width;
         *pheight = height;
         vk_state.fullscreen = false;
         if ( !VID_CreateWindow (width, height, false) )
             return rserr_invalid_mode;
     }
     return rserr_ok;
 }
Referenced by R_SetMode().
Vkimp_Shutdown()
void Vkimp_Shutdown (void)
Definition at line 274 of file vk_imp.c.
 {
     if (vkw_state.hWnd)
     {
         DestroyWindow(vkw_state.hWnd);
         vkw_state.hWnd = NULL;
     }
     if (vkw_state.log_fp)
     {
         fclose(vkw_state.log_fp);
         vkw_state.log_fp = 0;
     }
     UnregisterClass(WINDOW_CLASS_NAME, vkw_state.hInstance);
     if (vk_state.fullscreen)
     {
         ChangeDisplaySettingsEx( vkw_state.monInfo.szDevice, NULL, NULL, 0, NULL );
         vk_state.fullscreen = false;
     }
 }
Referenced by R_Shutdown(), and Vkimp_SetMode().
Variable Documentation
vid_fullscreen
cvar_t* vid_fullscreen
Definition at line 47 of file vid_dll.c.
Referenced by Vkimp_AppActivate().
vid_ref
cvar_t* vid_ref
Definition at line 44 of file vid_dll.c.
vkw_state
vkwstate_t vkw_state
Definition at line 39 of file vk_imp.c.
Referenced by VID_CreateWindow(), Vkimp_AppActivate(), Vkimp_BeginFrame(), Vkimp_CreateSurface(), Vkimp_EnableLogging(), Vkimp_Init(), Vkimp_LogNewFrame(), Vkimp_SetMode(), and Vkimp_Shutdown().