vkQuake2 doxygen: C:/entry/dev/vq2/src/ref_vk/vk_validation.c File Reference
vk_validation.c File Reference
#include "vk_local.h"
Macros
#define VK_FILELOG(msg, ...)
Functions
static const char * msgToString (VkDebugUtilsMessageTypeFlagsEXT type)
static VKAPI_ATTR VkBool32 VKAPI_CALL debugUtilsCallback (VkDebugUtilsMessageSeverityFlagBitsEXT msgSeverity, VkDebugUtilsMessageTypeFlagsEXT msgType, const VkDebugUtilsMessengerCallbackDataEXT *callbackData, void *userData)
void QVk_CreateValidationLayers ()
void QVk_DestroyValidationLayers ()
Variables
static VkDebugUtilsMessengerEXT validationMessenger = VK_NULL_HANDLE
FILE * vk_logfp
Macro Definition Documentation
VK_FILELOG
#define VK_FILELOG (msg, ...)
Value:
    if(vk_log->value && vk_logfp) { \
    fprintf(vk_logfp, msg, __VA_ARGS__); \
}
Definition at line 26 of file vk_validation.c.
Function Documentation
debugUtilsCallback()
static VKAPI_ATTR VkBool32 VKAPI_CALL debugUtilsCallback (VkDebugUtilsMessageSeverityFlagBitsEXT msgSeverity, VkDebugUtilsMessageTypeFlagsEXT msgType, const VkDebugUtilsMessengerCallbackDataEXT * callbackData, void * userData) static
Definition at line 46 of file vk_validation.c.
 {
     switch (msgSeverity)
     {
     case VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT:
         ri.Con_Printf(PRINT_ALL, "VK_INFO: %s %s\n", callbackData->pMessage, msgToString(msgType));
         VK_FILELOG("VK_INFO: %s %s\n", callbackData->pMessage, msgToString(msgType));
         break;
     case VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT:
         ri.Con_Printf(PRINT_ALL, "VK_VERBOSE: %s %s\n", callbackData->pMessage, msgToString(msgType));
         VK_FILELOG("VK_VERBOSE: %s %s\n", callbackData->pMessage, msgToString(msgType));
         break;
     case VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT:
         ri.Con_Printf(PRINT_ALL, "VK_WARNING: %s %s\n", callbackData->pMessage, msgToString(msgType));
         VK_FILELOG("VK_WARNING: %s %s\n", callbackData->pMessage, msgToString(msgType));
         assert(!"Vulkan warning occured!");
         break;
     default:
         ri.Con_Printf(PRINT_ALL, "VK_ERROR: %s %s\n", callbackData->pMessage, msgToString(msgType));
         VK_FILELOG("VK_ERROR: %s %s\n", callbackData->pMessage, msgToString(msgType));
         assert(!"Vulkan error occured!");
     }
     return VK_FALSE;
 }
Referenced by QVk_CreateValidationLayers().
msgToString()
static const char* msgToString (VkDebugUtilsMessageTypeFlagsEXT type) static
Definition at line 31 of file vk_validation.c.
 {
     int g = (type & VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT) != 0 ? 1 : 0;
     int p = (type & VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT) != 0 ? 1 : 0;
     int v = (type & VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT) != 0 ? 1 : 0;
     if (g) return "";
     if (p && !v) return "(performance)";
     if (p &&  v) return "(performance and validation)";
     if (v) return "(validation)";
     return "?";
 }
Referenced by debugUtilsCallback().
QVk_CreateValidationLayers()
void QVk_CreateValidationLayers ()
Definition at line 74 of file vk_validation.c.
 {
     VkDebugUtilsMessengerCreateInfoEXT callbackInfo = {
         .sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT,
         .pNext = NULL,
         .flags = 0,
         .messageSeverity =  VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
                             VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT,
         .messageType =  VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
                         VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT |
                         VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT,
         .pfnUserCallback = debugUtilsCallback,
         .pUserData = NULL
     };
     if( vk_validation->value > 1 )
     {
         callbackInfo.messageSeverity |= VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT |
                                         VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT;
     }
     VK_VERIFY(qvkCreateDebugUtilsMessengerEXT(vk_instance, &callbackInfo, NULL, &validationMessenger));
     ri.Con_Printf(PRINT_ALL, "...Vulkan validation layers enabled\n");
 }
Referenced by QVk_Init().
QVk_DestroyValidationLayers()
void QVk_DestroyValidationLayers ()
Definition at line 99 of file vk_validation.c.
 {
     if( validationMessenger != VK_NULL_HANDLE )
     {
         qvkDestroyDebugUtilsMessengerEXT( vk_instance, validationMessenger, NULL );
         validationMessenger = VK_NULL_HANDLE;
     }
 }
Referenced by QVk_Shutdown().
Variable Documentation
validationMessenger
VkDebugUtilsMessengerEXT validationMessenger = VK_NULL_HANDLE static
Definition at line 23 of file vk_validation.c.
Referenced by QVk_CreateValidationLayers(), and QVk_DestroyValidationLayers().
vk_logfp
FILE* vk_logfp
Definition at line 43 of file vk_common.c.
Referenced by Vkimp_EnableLogging().