vq2 doxygen: C:/entry/syn/github/vq2/client/input.h File Reference
input.h File Reference
Functions
void IN_Init (void)
void IN_Shutdown (void)
void IN_Commands (void)
void IN_Frame (void)
void IN_Move (usercmd_t *cmd)
void IN_Activate (qboolean active)
Function Documentation
IN_Activate()
void IN_Activate (qboolean active)
Definition at line 399 of file in_win.c.
 {
     in_appactive = active;
     mouseactive = !active;      // force a new window check or turn off
 }
Referenced by AppActivate(), and MainWndProc().
IN_Commands()
void IN_Commands (void)
Definition at line 649 of file in_win.c.
 {
     int     i, key_index;
     DWORD   buttonstate, povstate;
     if (!joy_avail)
     {
         return;
     }
     // loop through the joystick buttons
     // key a joystick event or auxillary event for higher number buttons for each state change
     buttonstate = ji.dwButtons;
     for (i=0 ; i < joy_numbuttons ; i++)
     {
         if ( (buttonstate & (1<<i)) && !(joy_oldbuttonstate & (1<<i)) )
         {
             key_index = (i < 4) ? K_JOY1 : K_AUX1;
             Key_Event (key_index + i, true, 0);
         }
         if ( !(buttonstate & (1<<i)) && (joy_oldbuttonstate & (1<<i)) )
         {
             key_index = (i < 4) ? K_JOY1 : K_AUX1;
             Key_Event (key_index + i, false, 0);
         }
     }
     joy_oldbuttonstate = buttonstate;
     if (joy_haspov)
     {
         // convert POV information into 4 bits of state information
         // this avoids any potential problems related to moving from one
         // direction to another without going through the center position
         povstate = 0;
         if(ji.dwPOV != JOY_POVCENTERED)
         {
             if (ji.dwPOV == JOY_POVFORWARD)
                 povstate |= 0x01;
             if (ji.dwPOV == JOY_POVRIGHT)
                 povstate |= 0x02;
             if (ji.dwPOV == JOY_POVBACKWARD)
                 povstate |= 0x04;
             if (ji.dwPOV == JOY_POVLEFT)
                 povstate |= 0x08;
         }
         // determine which bits have changed and key an auxillary event for each change
         for (i=0 ; i < 4 ; i++)
         {
             if ( (povstate & (1<<i)) && !(joy_oldpovstate & (1<<i)) )
             {
                 Key_Event (K_AUX29 + i, true, 0);
             }
             if ( !(povstate & (1<<i)) && (joy_oldpovstate & (1<<i)) )
             {
                 Key_Event (K_AUX29 + i, false, 0);
             }
         }
         joy_oldpovstate = povstate;
     }
 }
Referenced by CL_SendCommand().
IN_Frame()
void IN_Frame (void)
Definition at line 413 of file in_win.c.
 {
     if (!mouseinitialized)
         return;
     if (!in_mouse || !in_appactive)
     {
         IN_DeactivateMouse ();
         return;
     }
     if ( !cl.refresh_prepped
         || cls.key_dest == key_console
         || cls.key_dest == key_menu)
     {
         // temporarily deactivate if in fullscreen
         if (Cvar_VariableValue ("vid_fullscreen") == 0)
         {
             IN_DeactivateMouse ();
             return;
         }
     }
     IN_ActivateMouse ();
 }
Referenced by CL_Frame().
IN_Init()
void IN_Init (void)
Definition at line 339 of file in_win.c.
 {
     // mouse variables
     m_filter                = Cvar_Get ("m_filter",                 "0",        0);
     in_mouse                = Cvar_Get ("in_mouse",                 "1",        CVAR_ARCHIVE);
     // joystick variables
     in_joystick             = Cvar_Get ("in_joystick",              "0",        CVAR_ARCHIVE);
     joy_name                = Cvar_Get ("joy_name",                 "joystick", 0);
     joy_advanced            = Cvar_Get ("joy_advanced",             "0",        0);
     joy_advaxisx            = Cvar_Get ("joy_advaxisx",             "0",        0);
     joy_advaxisy            = Cvar_Get ("joy_advaxisy",             "0",        0);
     joy_advaxisz            = Cvar_Get ("joy_advaxisz",             "0",        0);
     joy_advaxisr            = Cvar_Get ("joy_advaxisr",             "0",        0);
     joy_advaxisu            = Cvar_Get ("joy_advaxisu",             "0",        0);
     joy_advaxisv            = Cvar_Get ("joy_advaxisv",             "0",        0);
     joy_forwardthreshold    = Cvar_Get ("joy_forwardthreshold",     "0.15",     0);
     joy_sidethreshold       = Cvar_Get ("joy_sidethreshold",        "0.15",     0);
     joy_upthreshold         = Cvar_Get ("joy_upthreshold",          "0.15",     0);
     joy_pitchthreshold      = Cvar_Get ("joy_pitchthreshold",       "0.15",     0);
     joy_yawthreshold        = Cvar_Get ("joy_yawthreshold",         "0.15",     0);
     joy_forwardsensitivity  = Cvar_Get ("joy_forwardsensitivity",   "-1",       0);
     joy_sidesensitivity     = Cvar_Get ("joy_sidesensitivity",      "-1",       0);
     joy_upsensitivity       = Cvar_Get ("joy_upsensitivity",        "-1",       0);
     joy_pitchsensitivity    = Cvar_Get ("joy_pitchsensitivity",     "1",        0);
     joy_yawsensitivity      = Cvar_Get ("joy_yawsensitivity",       "-1",       0);
     // centering
     v_centermove            = Cvar_Get ("v_centermove",             "0.15",     0);
     v_centerspeed           = Cvar_Get ("v_centerspeed",            "500",      0);
     Cmd_AddCommand ("+mlook", IN_MLookDown);
     Cmd_AddCommand ("-mlook", IN_MLookUp);
     Cmd_AddCommand ("joy_advancedupdate", Joy_AdvancedUpdate_f);
     IN_StartupMouse ();
     IN_StartupJoystick ();
 }
Referenced by CL_Init().
IN_Move()
void IN_Move (usercmd_t * cmd)
Definition at line 444 of file in_win.c.
 {
     IN_MouseMove (cmd);
     if (ActiveApp)
         IN_JoyMove (cmd);
 }
Referenced by CL_CreateCmd().
IN_Shutdown()
void IN_Shutdown (void)
Definition at line 384 of file in_win.c.
 {
     IN_DeactivateMouse ();
 }
Referenced by CL_Shutdown().