vq2 doxygen: refimport_t Struct Reference
refimport_t Struct Reference
#include <ref.h>
Public Attributes
void(* Sys_Error)(int err_level, char *str,...)
void(* Cmd_AddCommand)(char *name, void(*cmd)(void))
void(* Cmd_RemoveCommand)(char *name)
int(* Cmd_Argc)(void)
char *(* Cmd_Argv)(int i)
void(* Cmd_ExecuteText)(int exec_when, char *text)
void(* Con_Printf)(int print_level, char *str,...)
int(* FS_LoadFile)(char *name, void **buf)
void(* FS_FreeFile)(void *buf)
char *(* FS_Gamedir)(void)
cvar_t *(* Cvar_Get)(char *name, char *value, int flags)
cvar_t *(* Cvar_Set)(char *name, char *value)
void(* Cvar_SetValue)(char *name, float value)
qboolean(* Vid_GetModeInfo)(int *width, int *height, int mode)
void(* Vid_MenuInit)(void)
void(* Vid_NewWindow)(int width, int height)
Detailed Description
Definition at line 192 of file ref.h.
Member Data Documentation
Cmd_AddCommand
void(* refimport_t::Cmd_AddCommand) (char *name, void(*cmd)(void))
Definition at line 196 of file ref.h.
Referenced by R_Register(), and VID_LoadRefresh().
Cmd_Argc
int(* refimport_t::Cmd_Argc) (void)
Definition at line 198 of file ref.h.
Referenced by VID_LoadRefresh().
Cmd_Argv
char*(* refimport_t::Cmd_Argv) (int i)
Definition at line 199 of file ref.h.
Referenced by VID_LoadRefresh().
Cmd_ExecuteText
void(* refimport_t::Cmd_ExecuteText) (int exec_when, char *text)
Definition at line 200 of file ref.h.
Referenced by VID_LoadRefresh().
Cmd_RemoveCommand
void(* refimport_t::Cmd_RemoveCommand) (char *name)
Definition at line 197 of file ref.h.
Referenced by R_Shutdown(), R_UnRegister(), and VID_LoadRefresh().
Con_Printf
void(* refimport_t::Con_Printf) (int print_level, char *str,...)
Definition at line 202 of file ref.h.
Referenced by Com_Printf(), CreateDrawBuffers(), CreateFramebuffers(), CreateRenderpasses(), D_SCDump(), DDRAW_Init(), DDRAW_SetPalette(), DDRAW_Shutdown(), debugUtilsCallback(), DIB_Init(), DIB_SetPalette(), Draw_Pic(), Draw_StretchPic(), Draw_TileClear(), getSwapPresentMode(), GL_ImageList_f(), GL_LoadWal(), GL_ScreenShot_f(), GL_Strings_f(), GL_TextureAlphaMode(), GL_TextureMode(), GL_TextureSolidMode(), GL_Upload32(), GLimp_BeginFrame(), GLimp_Init(), GLimp_InitGL(), GLimp_SetMode(), GLimp_Shutdown(), LoadPCX(), LoadTGA(), Mod_LoadTexinfo(), Mod_Modellist_f(), QGL_Init(), QVk_BeginFrame(), QVk_CreateDevice(), QVk_CreateSwapchain(), QVk_CreateValidationLayers(), QVk_EndFrame(), QVk_GetIndexBuffer(), QVk_GetTriangleFanIbo(), QVk_GetUniformBuffer(), QVk_GetVertexBuffer(), QVk_Init(), QVk_Shutdown(), R_AliasDrawModel(), R_AliasSetupFrames(), R_AliasSetupSkin(), R_BeginFrame(), R_CullAliasModel(), R_DrawAliasModel(), R_DrawSprite(), R_DrawSpriteModel(), R_ImageList_f(), R_Init(), R_InitCaches(), R_LoadWal(), R_PrintAliasStats(), R_PrintDSpeeds(), R_PrintTimes(), R_RecursiveClipBPoly(), R_RenderFrame(), R_RenderView(), R_ScreenShot_f(), R_SetMode(), selectPhysicalDevice(), SWimp_SetMode(), SWimp_Shutdown(), VID_CreateWindow(), VID_LoadRefresh(), Vk_ImageList_f(), Vk_LmapTextureMode(), Vk_LoadWal(), Vk_Mem_f(), Vk_ScreenShot_f(), Vk_Strings_f(), Vk_TextureMode(), Vkimp_BeginFrame(), Vkimp_Init(), Vkimp_SetMode(), and WritePCXfile().
Cvar_Get
cvar_t*(* refimport_t::Cvar_Get) (char *name, char *value, int flags)
Definition at line 216 of file ref.h.
Referenced by Draw_Char(), Draw_GetPicSize(), Draw_Pic(), GL_InitImages(), GLimp_InitGL(), R_BeginFrame(), R_BeginRegistration(), R_DrawParticles(), R_Register(), VID_CreateWindow(), VID_LoadRefresh(), Vk_InitImages(), and Vk_Strings_f().
Cvar_Set
cvar_t*(* refimport_t::Cvar_Set) (char *name, char *value)
Definition at line 217 of file ref.h.
Referenced by GL_InitImages(), QVk_Init(), R_Init(), R_Register(), VID_LoadRefresh(), Vk_InitImages(), Vk_LmapTextureMode(), and Vk_TextureMode().
Cvar_SetValue
void(* refimport_t::Cvar_SetValue) (char *name, float value)
Definition at line 218 of file ref.h.
Referenced by GLimp_BeginFrame(), GLimp_InitGL(), R_BeginFrame(), R_Init(), R_SetMode(), SWimp_SetMode(), VID_LoadRefresh(), and Vkimp_BeginFrame().
FS_FreeFile
void(* refimport_t::FS_FreeFile) (void *buf)
Definition at line 210 of file ref.h.
Referenced by GL_LoadWal(), LoadPCX(), LoadTGA(), Mod_ForName(), R_LoadWal(), VID_LoadRefresh(), and Vk_LoadWal().
FS_Gamedir
char*(* refimport_t::FS_Gamedir) (void)
Definition at line 214 of file ref.h.
Referenced by GL_ScreenShot_f(), GLimp_EnableLogging(), R_ScreenShot_f(), VID_LoadRefresh(), Vk_ScreenShot_f(), and Vkimp_EnableLogging().
FS_LoadFile
int(* refimport_t::FS_LoadFile) (char *name, void **buf)
Definition at line 209 of file ref.h.
Referenced by GL_InitImages(), GL_LoadWal(), LoadPCX(), LoadTGA(), Mod_ForName(), R_LoadWal(), VID_LoadRefresh(), and Vk_LoadWal().
Sys_Error
void(* refimport_t::Sys_Error) (int err_level, char *str,...)
Definition at line 194 of file ref.h.
Referenced by CalcSurfaceExtents(), ClipSkyPolygon(), D_SCAlloc(), DIB_SetPalette(), Draw_Char(), Draw_Fill(), Draw_GetPalette(), Draw_InitLocal(), Draw_StretchPicImplementation(), GL_CreateSurfaceLightmap(), GL_InitImages(), GL_LoadPic(), GL_Upload32(), GL_Upload8(), GLimp_EndFrame(), LM_UploadBlock(), LoadTGA(), Mod_ForName(), Mod_LoadAliasModel(), Mod_LoadBrushModel(), Mod_LoadEdges(), Mod_LoadFaces(), Mod_LoadLeafs(), Mod_LoadMarksurfaces(), Mod_LoadNodes(), Mod_LoadPlanes(), Mod_LoadSpriteModel(), Mod_LoadSubmodels(), Mod_LoadSurfedges(), Mod_LoadTexinfo(), Mod_LoadVertexes(), Mod_PointInLeaf(), R_BeginFrame(), R_BlendLightmaps(), R_BuildLightMap(), R_ClipAndDrawPoly(), R_DrawEntitiesOnList(), R_FindFreeImage(), R_InitSkyBox(), R_RenderFrame(), R_RenderView(), SubdividePolygon(), Sys_Error(), Sys_MakeCodeWriteable(), VID_CreateWindow(), VID_LoadRefresh(), Vk_CreateSurfaceLightmap(), Vk_LoadPic(), Vk_Upload32(), and Vk_Upload8().
Vid_GetModeInfo
qboolean(* refimport_t::Vid_GetModeInfo) (int *width, int *height, int mode)
Definition at line 220 of file ref.h.
Referenced by GLimp_SetMode(), SWimp_SetMode(), VID_LoadRefresh(), and Vkimp_SetMode().
Vid_MenuInit
void(* refimport_t::Vid_MenuInit) (void)
Definition at line 221 of file ref.h.
Referenced by R_Init(), and VID_LoadRefresh().
Vid_NewWindow
void(* refimport_t::Vid_NewWindow) (int width, int height)
Definition at line 222 of file ref.h.
Referenced by VID_CreateWindow(), and VID_LoadRefresh().
The documentation for this struct was generated from the following file:
C:/entry/syn/github/vq2/client/ref.h