vkQuake2 doxygen: C:/entry/dev/vq2/src/game/g_trigger.c File Reference
g_trigger.c File Reference
#include "g_local.h"
Macros
#define PUSH_ONCE 1
Functions
void InitTrigger (edict_t *self)
void multi_wait (edict_t *ent)
void multi_trigger (edict_t *ent)
void Use_Multi (edict_t *ent, edict_t *other, edict_t *activator)
void Touch_Multi (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void trigger_enable (edict_t *self, edict_t *other, edict_t *activator)
void SP_trigger_multiple (edict_t *ent)
void SP_trigger_once (edict_t *ent)
void trigger_relay_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_trigger_relay (edict_t *self)
void trigger_key_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_trigger_key (edict_t *self)
void trigger_counter_use (edict_t *self, edict_t *other, edict_t *activator)
void SP_trigger_counter (edict_t *self)
void SP_trigger_always (edict_t *ent)
void trigger_push_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_trigger_push (edict_t *self)
void hurt_use (edict_t *self, edict_t *other, edict_t *activator)
void hurt_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_trigger_hurt (edict_t *self)
void trigger_gravity_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_trigger_gravity (edict_t *self)
void trigger_monsterjump_touch (edict_t *self, edict_t *other, cplane_t *plane, csurface_t *surf)
void SP_trigger_monsterjump (edict_t *self)
Variables
static int windsound
Macro Definition Documentation
PUSH_ONCE
#define PUSH_ONCE 1
Definition at line 390 of file g_trigger.c.
Function Documentation
hurt_touch()
void hurt_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 468 of file g_trigger.c.
 {
     int     dflags;
     if (!other->takedamage)
         return;
     if (self->timestamp > level.time)
         return;
     if (self->spawnflags & 16)
         self->timestamp = level.time + 1;
     else
         self->timestamp = level.time + FRAMETIME;
     if (!(self->spawnflags & 4))
     {
         if ((level.framenum % 10) == 0)
             gi.sound (other, CHAN_AUTO, self->noise_index, 1, ATTN_NORM, 0);
     }
     if (self->spawnflags & 8)
         dflags = DAMAGE_NO_PROTECTION;
     else
         dflags = 0;
     T_Damage (other, self, self, vec3_origin, other->s.origin, vec3_origin, self->dmg, self->dmg, dflags, MOD_TRIGGER_HURT);
 }
Referenced by SP_trigger_hurt().
hurt_use()
void hurt_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 455 of file g_trigger.c.
 {
     if (self->solid == SOLID_NOT)
         self->solid = SOLID_TRIGGER;
     else
         self->solid = SOLID_NOT;
     gi.linkentity (self);
     if (!(self->spawnflags & 2))
         self->use = NULL;
 }
Referenced by SP_trigger_hurt().
InitTrigger()
void InitTrigger (edict_t * self)
Definition at line 23 of file g_trigger.c.
 {
     if (!VectorCompare (self->s.angles, vec3_origin))
         G_SetMovedir (self->s.angles, self->movedir);
     self->solid = SOLID_TRIGGER;
     self->movetype = MOVETYPE_NONE;
     gi.setmodel (self, self->model);
     self->svflags = SVF_NOCLIENT;
 }
Referenced by SP_trigger_gravity(), SP_trigger_hurt(), SP_trigger_monsterjump(), and SP_trigger_push().
multi_trigger()
void multi_trigger (edict_t * ent)
Definition at line 45 of file g_trigger.c.
 {
     if (ent->nextthink)
         return;     // already been triggered
     G_UseTargets (ent, ent->activator);
     if (ent->wait > 0)
     {
         ent->think = multi_wait;
         ent->nextthink = level.time + ent->wait;
     }
     else
     {   // we can't just remove (self) here, because this is a touch function
         // called while looping through area links...
         ent->touch = NULL;
         ent->nextthink = level.time + FRAMETIME;
         ent->think = G_FreeEdict;
     }
 }
Referenced by Touch_Multi(), trigger_counter_use(), and Use_Multi().
multi_wait()
void multi_wait (edict_t * ent)
Definition at line 36 of file g_trigger.c.
 {
     ent->nextthink = 0;
 }
Referenced by multi_trigger().
SP_trigger_always()
void SP_trigger_always (edict_t * ent)
Definition at line 373 of file g_trigger.c.
 {
     // we must have some delay to make sure our use targets are present
     if (ent->delay < 0.2)
         ent->delay = 0.2;
     G_UseTargets(ent, ent);
 }
SP_trigger_counter()
void SP_trigger_counter (edict_t * self)
Definition at line 352 of file g_trigger.c.
 {
     self->wait = -1;
     if (!self->count)
         self->count = 2;
     self->use = trigger_counter_use;
 }
SP_trigger_gravity()
void SP_trigger_gravity (edict_t * self)
Definition at line 537 of file g_trigger.c.
 {
     if (st.gravity == 0)
     {
         gi.dprintf("trigger_gravity without gravity set at %s\n", vtos(self->s.origin));
         G_FreeEdict  (self);
         return;
     }
     InitTrigger (self);
     self->gravity = atoi(st.gravity);
     self->touch = trigger_gravity_touch;
 }
SP_trigger_hurt()
void SP_trigger_hurt (edict_t * self)
Definition at line 496 of file g_trigger.c.
 {
     InitTrigger (self);
     self->noise_index = gi.soundindex ("world/electro.wav");
     self->touch = hurt_touch;
     if (!self->dmg)
         self->dmg = 5;
     if (self->spawnflags & 1)
         self->solid = SOLID_NOT;
     else
         self->solid = SOLID_TRIGGER;
     if (self->spawnflags & 2)
         self->use = hurt_use;
     gi.linkentity (self);
 }
SP_trigger_key()
void SP_trigger_key (edict_t * self)
Definition at line 282 of file g_trigger.c.
 {
     if (!st.item)
     {
         gi.dprintf("no key item for trigger_key at %s\n", vtos(self->s.origin));
         return;
     }
     self->item = FindItemByClassname (st.item);
     if (!self->item)
     {
         gi.dprintf("item %s not found for trigger_key at %s\n", st.item, vtos(self->s.origin));
         return;
     }
     if (!self->target)
     {
         gi.dprintf("%s at %s has no target\n", self->classname, vtos(self->s.origin));
         return;
     }
     gi.soundindex ("misc/keytry.wav");
     gi.soundindex ("misc/keyuse.wav");
     self->use = trigger_key_use;
 }
SP_trigger_monsterjump()
void SP_trigger_monsterjump (edict_t * self)
Definition at line 586 of file g_trigger.c.
 {
     if (!self->speed)
         self->speed = 200;
     if (!st.height)
         st.height = 200;
     if (self->s.angles[YAW] == 0)
         self->s.angles[YAW] = 360;
     InitTrigger (self);
     self->touch = trigger_monsterjump_touch;
     self->movedir[2] = st.height;
 }
SP_trigger_multiple()
void SP_trigger_multiple (edict_t * ent)
Definition at line 118 of file g_trigger.c.
 {
     if (ent->sounds == 1)
         ent->noise_index = gi.soundindex ("misc/secret.wav");
     else if (ent->sounds == 2)
         ent->noise_index = gi.soundindex ("misc/talk.wav");
     else if (ent->sounds == 3)
         ent->noise_index = gi.soundindex ("misc/trigger1.wav");
     if (!ent->wait)
         ent->wait = 0.2;
     ent->touch = Touch_Multi;
     ent->movetype = MOVETYPE_NONE;
     ent->svflags |= SVF_NOCLIENT;
     if (ent->spawnflags & 4)
     {
         ent->solid = SOLID_NOT;
         ent->use = trigger_enable;
     }
     else
     {
         ent->solid = SOLID_TRIGGER;
         ent->use = Use_Multi;
     }
     if (!VectorCompare(ent->s.angles, vec3_origin))
         G_SetMovedir (ent->s.angles, ent->movedir);
     gi.setmodel (ent, ent->model);
     gi.linkentity (ent);
 }
Referenced by SP_trigger_once().
SP_trigger_once()
void SP_trigger_once (edict_t * ent)
Definition at line 168 of file g_trigger.c.
 {
     // make old maps work because I messed up on flag assignments here
     // triggered was on bit 1 when it should have been on bit 4
     if (ent->spawnflags & 1)
     {
         vec3_t  v;
         VectorMA (ent->mins, 0.5, ent->size, v);
         ent->spawnflags &= ~1;
         ent->spawnflags |= 4;
         gi.dprintf("fixed TRIGGERED flag on %s at %s\n", ent->classname, vtos(v));
     }
     ent->wait = -1;
     SP_trigger_multiple (ent);
 }
SP_trigger_push()
void SP_trigger_push (edict_t * self)
Definition at line 424 of file g_trigger.c.
 {
     InitTrigger (self);
     windsound = gi.soundindex ("misc/windfly.wav");
     self->touch = trigger_push_touch;
     if (!self->speed)
         self->speed = 1000;
     gi.linkentity (self);
 }
SP_trigger_relay()
void SP_trigger_relay (edict_t * self)
Definition at line 194 of file g_trigger.c.
 {
     self->use = trigger_relay_use;
 }
Touch_Multi()
void Touch_Multi (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 72 of file g_trigger.c.
 {
     if(other->client)
     {
         if (self->spawnflags & 2)
             return;
     }
     else if (other->svflags & SVF_MONSTER)
     {
         if (!(self->spawnflags & 1))
             return;
     }
     else
         return;
     if (!VectorCompare(self->movedir, vec3_origin))
     {
         vec3_t  forward;
         AngleVectors(other->s.angles, forward, NULL, NULL);
         if (_DotProduct(forward, self->movedir) < 0)
             return;
     }
     self->activator = other;
     multi_trigger (self);
 }
Referenced by SP_trigger_multiple().
trigger_counter_use()
void trigger_counter_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 326 of file g_trigger.c.
 {
     if (self->count == 0)
         return;
     self->count--;
     if (self->count)
     {
         if (! (self->spawnflags & 1))
         {
             gi.centerprintf(activator, "%i more to go...", self->count);
             gi.sound (activator, CHAN_AUTO, gi.soundindex ("misc/talk1.wav"), 1, ATTN_NORM, 0);
         }
         return;
     }
     if (! (self->spawnflags & 1))
     {
         gi.centerprintf(activator, "Sequence completed!");
         gi.sound (activator, CHAN_AUTO, gi.soundindex ("misc/talk1.wav"), 1, ATTN_NORM, 0);
     }
     self->activator = activator;
     multi_trigger (self);
 }
Referenced by SP_trigger_counter().
trigger_enable()
void trigger_enable (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 111 of file g_trigger.c.
 {
     self->solid = SOLID_TRIGGER;
     self->use = Use_Multi;
     gi.linkentity (self);
 }
Referenced by SP_trigger_multiple().
trigger_gravity_touch()
void trigger_gravity_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 532 of file g_trigger.c.
 {
     other->gravity = self->gravity;
 }
Referenced by SP_trigger_gravity().
trigger_key_use()
void trigger_key_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 212 of file g_trigger.c.
 {
     int         index;
     if (!self->item)
         return;
     if (!activator->client)
         return;
     index = ITEM_INDEX(self->item);
     if (!activator->client->pers.inventory[index])
     {
         if (level.time < self->touch_debounce_time)
             return;
         self->touch_debounce_time = level.time + 5.0;
         gi.centerprintf (activator, "You need the %s", self->item->pickup_name);
         gi.sound (activator, CHAN_AUTO, gi.soundindex ("misc/keytry.wav"), 1, ATTN_NORM, 0);
         return;
     }
     gi.sound (activator, CHAN_AUTO, gi.soundindex ("misc/keyuse.wav"), 1, ATTN_NORM, 0);
     if (coop->value)
     {
         int     player;
         edict_t *ent;
         if (strcmp(self->item->classname, "key_power_cube") == 0)
         {
             int cube;
             for (cube = 0; cube < 8; cube++)
                 if (activator->client->pers.power_cubes & (1 << cube))
                     break;
             for (player = 1; player <= game.maxclients; player++)
             {
                 ent = &g_edicts[player];
                 if (!ent->inuse)
                     continue;
                 if (!ent->client)
                     continue;
                 if (ent->client->pers.power_cubes & (1 << cube))
                 {
                     ent->client->pers.inventory[index]--;
                     ent->client->pers.power_cubes &= ~(1 << cube);
                 }
             }
         }
         else
         {
             for (player = 1; player <= game.maxclients; player++)
             {
                 ent = &g_edicts[player];
                 if (!ent->inuse)
                     continue;
                 if (!ent->client)
                     continue;
                 ent->client->pers.inventory[index] = 0;
             }
         }
     }
     else
     {
         activator->client->pers.inventory[index]--;
     }
     G_UseTargets (self, activator);
     self->use = NULL;
 }
Referenced by SP_trigger_key().
trigger_monsterjump_touch()
void trigger_monsterjump_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 566 of file g_trigger.c.
 {
     if (other->flags & (FL_FLY | FL_SWIM) )
         return;
     if (other->svflags & SVF_DEADMONSTER)
         return;
     if ( !(other->svflags & SVF_MONSTER))
         return;
 // set XY even if not on ground, so the jump will clear lips
     other->velocity[0] = self->movedir[0] * self->speed;
     other->velocity[1] = self->movedir[1] * self->speed;
     if (!other->groundentity)
         return;
     other->groundentity = NULL;
     other->velocity[2] = self->movedir[2];
 }
Referenced by SP_trigger_monsterjump().
trigger_push_touch()
void trigger_push_touch (edict_t * self, edict_t * other, cplane_t * plane, csurface_t * surf)
Definition at line 394 of file g_trigger.c.
 {
     if (strcmp(other->classname, "grenade") == 0)
     {
         VectorScale (self->movedir, self->speed * 10, other->velocity);
     }
     else if (other->health > 0)
     {
         VectorScale (self->movedir, self->speed * 10, other->velocity);
         if (other->client)
         {
             // don't take falling damage immediately from this
             VectorCopy (other->velocity, other->client->oldvelocity);
             if (other->fly_sound_debounce_time < level.time)
             {
                 other->fly_sound_debounce_time = level.time + 1.5;
                 gi.sound (other, CHAN_AUTO, windsound, 1, ATTN_NORM, 0);
             }
         }
     }
     if (self->spawnflags & PUSH_ONCE)
         G_FreeEdict (self);
 }
Referenced by SP_trigger_push().
trigger_relay_use()
void trigger_relay_use (edict_t * self, edict_t * other, edict_t * activator)
Definition at line 189 of file g_trigger.c.
 {
     G_UseTargets (self, activator);
 }
Referenced by SP_trigger_relay().
Use_Multi()
void Use_Multi (edict_t * ent, edict_t * other, edict_t * activator)
Definition at line 66 of file g_trigger.c.
 {
     ent->activator = activator;
     multi_trigger (ent);
 }
Referenced by SP_trigger_multiple(), and trigger_enable().
Variable Documentation
windsound
int windsound static
Definition at line 392 of file g_trigger.c.
Referenced by SP_trigger_push(), and trigger_push_touch().