vkQuake2 doxygen: C:/entry/dev/vq2/src/game/q_shared.c File Reference
q_shared.c File Reference
#include "q_shared.h"
Macros
#define DEG2RAD(a) (a * M_PI) / 180.0F
Functions
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
void AngleVectors (vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
void PerpendicularVector (vec3_t dst, const vec3_t src)
void R_ConcatRotations (float in1[3][3], float in2[3][3], float out[3][3])
void R_ConcatTransforms (float in1[3][4], float in2[3][4], float out[3][4])
float Q_fabs (float f)
float LerpAngle (float a2, float a1, float frac)
float anglemod (float a)
int BoxOnPlaneSide2 (vec3_t emins, vec3_t emaxs, struct cplane_s *p)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s *p)
void ClearBounds (vec3_t mins, vec3_t maxs)
void AddPointToBounds (vec3_t v, vec3_t mins, vec3_t maxs)
int VectorCompare (vec3_t v1, vec3_t v2)
vec_t VectorNormalize (vec3_t v)
vec_t VectorNormalize2 (vec3_t v, vec3_t out)
void VectorMA (vec3_t veca, float scale, vec3_t vecb, vec3_t vecc)
vec_t _DotProduct (vec3_t v1, vec3_t v2)
void _VectorSubtract (vec3_t veca, vec3_t vecb, vec3_t out)
void _VectorAdd (vec3_t veca, vec3_t vecb, vec3_t out)
void _VectorCopy (vec3_t in, vec3_t out)
void CrossProduct (vec3_t v1, vec3_t v2, vec3_t cross)
double sqrt (double x)
vec_t VectorLength (vec3_t v)
void VectorInverse (vec3_t v)
void VectorScale (vec3_t in, vec_t scale, vec3_t out)
int Q_log2 (int val)
char * COM_SkipPath (char *pathname)
void COM_StripExtension (char *in, char *out)
char * COM_FileExtension (char *in)
void COM_FileBase (char *in, char *out)
void COM_FilePath (char *in, char *out)
void COM_DefaultExtension (char *path, char *extension)
short BigShort (short l)
short LittleShort (short l)
int BigLong (int l)
int LittleLong (int l)
float BigFloat (float l)
float LittleFloat (float l)
short ShortSwap (short l)
short ShortNoSwap (short l)
int LongSwap (int l)
int LongNoSwap (int l)
float FloatSwap (float f)
float FloatNoSwap (float f)
void Swap_Init (void)
char * va (char *format,...)
char * COM_Parse (char **data_p)
void Com_PageInMemory (byte *buffer, int size)
int Q_stricmp (char *s1, char *s2)
int Q_strncasecmp (char *s1, char *s2, int n)
int Q_strcasecmp (char *s1, char *s2)
void Com_sprintf (char *dest, int size, char *fmt,...)
char * Info_ValueForKey (char *s, char *key)
void Info_RemoveKey (char *s, char *key)
qboolean Info_Validate (char *s)
void Info_SetValueForKey (char *s, char *key, char *value)
Variables
vec3_t vec3_origin = {0,0,0}
int i
vec3_t corners [2]
qboolean bigendien
short(* _BigShort)(short l)
short(* _LittleShort)(short l)
int(* _BigLong)(int l)
int(* _LittleLong)(int l)
float(* _BigFloat)(float l)
float(* _LittleFloat)(float l)
char com_token [MAX_TOKEN_CHARS]
int paged_total
Macro Definition Documentation
DEG2RAD
#define DEG2RAD (a) (a * M_PI) / 180.0F
Definition at line 22 of file q_shared.c.
Function Documentation
_DotProduct()
vec_t _DotProduct (vec3_t v1, vec3_t v2)
Definition at line 727 of file q_shared.c.
 {
     return v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2];
 }
Referenced by Touch_Multi().
_VectorAdd()
void _VectorAdd (vec3_t veca, vec3_t vecb, vec3_t out)
Definition at line 739 of file q_shared.c.
 {
     out[0] = veca[0]+vecb[0];
     out[1] = veca[1]+vecb[1];
     out[2] = veca[2]+vecb[2];
 }
_VectorCopy()
void _VectorCopy (vec3_t in, vec3_t out)
Definition at line 746 of file q_shared.c.
 {
     out[0] = in[0];
     out[1] = in[1];
     out[2] = in[2];
 }
_VectorSubtract()
void _VectorSubtract (vec3_t veca, vec3_t vecb, vec3_t out)
Definition at line 732 of file q_shared.c.
 {
     out[0] = veca[0]-vecb[0];
     out[1] = veca[1]-vecb[1];
     out[2] = veca[2]-vecb[2];
 }
AddPointToBounds()
void AddPointToBounds (vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 656 of file q_shared.c.
 {
     int     i;
     vec_t   val;
     for (i=0 ; i<3 ; i++)
     {
         val = v[i];
         if (val < mins[i])
             mins[i] = val;
         if (val > maxs[i])
             maxs[i] = val;
     }
 }
Referenced by Think_SpawnDoorTrigger().
anglemod()
float anglemod (float a)
Definition at line 293 of file q_shared.c.
 {
 #if 0
     if (a >= 0)
         a -= 360*(int)(a/360);
     else
         a += 360*( 1 + (int)(-a/360) );
 #endif
     a = (360.0/65536) * ((int)(a*(65536/360.0)) & 65535);
     return a;
 }
Referenced by CL_AddPacketEntities(), FacingIdeal(), M_ChangeYaw(), and SV_NewChaseDir().
AngleVectors()
void AngleVectors (vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 93 of file q_shared.c.
 {
     float       angle;
     static float        sr, sp, sy, cr, cp, cy;
     // static to help MS compiler fp bugs
     angle = angles[YAW] * (M_PI*2 / 360);
     sy = sin(angle);
     cy = cos(angle);
     angle = angles[PITCH] * (M_PI*2 / 360);
     sp = sin(angle);
     cp = cos(angle);
     angle = angles[ROLL] * (M_PI*2 / 360);
     sr = sin(angle);
     cr = cos(angle);
     if (forward)
     {
         forward[0] = cp*cy;
         forward[1] = cp*sy;
         forward[2] = -sp;
     }
     if (right)
     {
         right[0] = (-1*sr*sp*cy+-1*cr*-sy);
         right[1] = (-1*sr*sp*sy+-1*cr*cy);
         right[2] = -1*sr*cp;
     }
     if (up)
     {
         up[0] = (cr*sp*cy+-sr*-sy);
         up[1] = (cr*sp*sy+-sr*cy);
         up[2] = cr*cp;
     }
 }
Referenced by actorMachineGun(), ai_run(), Blaster_Fire(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), Chaingun_Fire(), CheckPowerArmor(), ChickRocket(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_CalcViewValues(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_TrackerTrail(), ClientEndServerFrame(), CM_TransformedBoxTrace(), CM_TransformedPointContents(), Drop_Item(), fire_grenade(), fire_grenade2(), fire_hit(), fire_lead(), floater_fire_blaster(), floater_zap(), flyer_fire(), G_SetMovedir(), gib_touch(), GL_DrawAliasFrameLerp(), GladiatorGun(), GunnerFire(), GunnerGrenade(), hover_fire_blaster(), InfantryMachineGun(), infront(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), Machinegun_Fire(), makronBFG(), MakronHyperblaster(), MakronRailgun(), medic_cable_attack(), medic_fire_blaster(), mutant_jump_takeoff(), parasite_drain_attack(), PM_ClampAngles(), Pmove(), R_AliasSetUpLerpData(), R_AliasSetUpTransform(), R_CullAliasModel(), R_DrawBrushModel(), R_DrawSpriteModel(), R_SetupFrame(), RotatedBBox(), soldier_fire(), SP_func_door_secret(), supertankMachineGun(), supertankRocket(), SV_Push(), TankBlaster(), TankMachineGun(), TankRocket(), Touch_Multi(), turret_breach_fire(), UpdateChaseCam(), Vk_DrawAliasFrameLerp(), weapon_bfg_fire(), weapon_grenade_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
BigFloat()
float BigFloat (float l)
Definition at line 949 of file q_shared.c.
 {return _BigFloat(l);}
BigLong()
int BigLong (int l)
Definition at line 947 of file q_shared.c.
 {return _BigLong(l);}
BigShort()
short BigShort (short l)
Definition at line 945 of file q_shared.c.
 {return _BigShort(l);}
Referenced by CL_CheckForResend(), CL_Packet_f(), CL_PingServers_f(), CL_Rcon_f(), CL_SendConnectPacket(), and SV_SetMaster_f().
BoxOnPlaneSide()
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s * p)
Definition at line 349 of file q_shared.c.
 {
     float   dist1, dist2;
     int     sides;
 // fast axial cases
     if (p->type < 3)
     {
         if (p->dist <= emins[p->type])
             return 1;
         if (p->dist >= emaxs[p->type])
             return 2;
         return 3;
     }
 // general case
     switch (p->signbits)
     {
     case 0:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
         break;
     case 1:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
         break;
     case 2:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
         break;
     case 3:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
         break;
     case 4:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
         break;
     case 5:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emaxs[2];
         break;
     case 6:
 dist1 = p->normal[0]*emaxs[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emins[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
         break;
     case 7:
 dist1 = p->normal[0]*emins[0] + p->normal[1]*emins[1] + p->normal[2]*emins[2];
 dist2 = p->normal[0]*emaxs[0] + p->normal[1]*emaxs[1] + p->normal[2]*emaxs[2];
         break;
     default:
         dist1 = dist2 = 0;      // shut up compiler
         assert( 0 );
         break;
     }
     sides = 0;
     if (dist1 >= p->dist)
         sides = 1;
     if (dist2 < p->dist)
         sides |= 2;
     assert( sides != 0 );
     return sides;
 }
BoxOnPlaneSide2()
int BoxOnPlaneSide2 (vec3_t emins, vec3_t emaxs, struct cplane_s * p)
Definition at line 310 of file q_shared.c.
 {
     int     i;
     float   dist1, dist2;
     int     sides;
     vec3_t  corners[2];
     for (i=0 ; i<3 ; i++)
     {
         if (p->normal[i] < 0)
         {
             corners[0][i] = emins[i];
             corners[1][i] = emaxs[i];
         }
         else
         {
             corners[1][i] = emins[i];
             corners[0][i] = emaxs[i];
         }
     }
     dist1 = DotProduct (p->normal, corners[0]) - p->dist;
     dist2 = DotProduct (p->normal, corners[1]) - p->dist;
     sides = 0;
     if (dist1 >= 0)
         sides = 1;
     if (dist2 < 0)
         sides |= 2;
     return sides;
 }
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 650 of file q_shared.c.
 {
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
COM_DefaultExtension()
void COM_DefaultExtension (char * path, char * extension)
Definition at line 907 of file q_shared.c.
 {
     char    *src;
 //
 // if path doesn't have a .EXT, append extension
 // (extension should include the .)
 //
     src = path + strlen(path) - 1;
     while (*src != '/' && src != path)
     {
         if (*src == '.')
             return;                 // it has an extension
         src--;
     }
     strcat (path, extension);
 }
COM_FileBase()
void COM_FileBase (char * in, char * out)
Definition at line 859 of file q_shared.c.
 {
     char *s, *s2;
     s = in + strlen(in) - 1;
     while (s != in && *s != '.')
         s--;
     for (s2 = s ; s2 != in && *s2 != '/' ; s2--)
     ;
     if (s-s2 < 2)
         out[0] = 0;
     else
     {
         s--;
         strncpy (out,s2+1, s-s2);
         out[s-s2] = 0;
     }
 }
COM_FileExtension()
char* COM_FileExtension (char * in)
Definition at line 838 of file q_shared.c.
 {
     static char exten[8];
     int     i;
     while (*in && *in != '.')
         in++;
     if (!*in)
         return "";
     in++;
     for (i=0 ; i<7 && *in ; i++,in++)
         exten[i] = *in;
     exten[i] = 0;
     return exten;
 }
COM_FilePath()
void COM_FilePath (char * in, char * out)
Definition at line 888 of file q_shared.c.
 {
     char *s;
     s = in + strlen(in) - 1;
     while (s != in && *s != '/')
         s--;
     strncpy (out,in, s-in);
     out[s-in] = 0;
 }
Referenced by Sys_FindFirst().
Com_PageInMemory()
void Com_PageInMemory (byte * buffer, int size)
Definition at line 1161 of file q_shared.c.
 {
     int     i;
     for (i=size-1 ; i>0 ; i-=4096)
         paged_total += buffer[i];
 }
Referenced by R_EndRegistration(), R_FreeUnusedImages(), and S_EndRegistration().
COM_Parse()
char* COM_Parse (char ** data_p)
Definition at line 1072 of file q_shared.c.
 {
     int     c;
     int     len;
     char    *data;
     data = *data_p;
     len = 0;
     com_token[0] = 0;
     if (!data)
     {
         *data_p = NULL;
         return "";
     }
 // skip whitespace
 skipwhite:
     while ( (c = *data) <= ' ')
     {
         if (c == 0)
         {
             *data_p = NULL;
             return "";
         }
         data++;
     }
 // skip // comments
     if (c=='/' && data[1] == '/')
     {
         while (*data && *data != '\n')
             data++;
         goto skipwhite;
     }
 // handle quoted strings specially
     if (c == '\"')
     {
         data++;
         while (1)
         {
             c = *data++;
             if (c=='\"' || !c)
             {
                 com_token[len] = 0;
                 *data_p = data;
                 return com_token;
             }
             if (len < MAX_TOKEN_CHARS)
             {
                 com_token[len] = c;
                 len++;
             }
         }
     }
 // parse a regular word
     do
     {
         if (len < MAX_TOKEN_CHARS)
         {
             com_token[len] = c;
             len++;
         }
         data++;
         c = *data;
     } while (c>32);
     if (len == MAX_TOKEN_CHARS)
     {
 //      Com_Printf ("Token exceeded %i chars, discarded.\n", MAX_TOKEN_CHARS);
         len = 0;
     }
     com_token[len] = 0;
     *data_p = data;
     return com_token;
 }
Referenced by Cmd_MacroExpandString(), Cmd_TokenizeString(), ED_ParseEdict(), SCR_ExecuteLayoutString(), SpawnEntities(), and StartServer_MenuInit().
COM_SkipPath()
char* COM_SkipPath (char * pathname)
Definition at line 807 of file q_shared.c.
 {
     char    *last;
     last = pathname;
     while (*pathname)
     {
         if (*pathname=='/')
             last = pathname+1;
         pathname++;
     }
     return last;
 }
Com_sprintf()
void Com_sprintf (char * dest, int size, char * fmt, ...)
Definition at line 1223 of file q_shared.c.
 {
     int     len;
     va_list     argptr;
     char    bigbuffer[0x10000];
     va_start (argptr,fmt);
     len = vsnprintf (bigbuffer,0x10000,fmt,argptr);
     va_end (argptr);
     if (len >= size)
         Com_Printf ("Com_sprintf: overflow of %i in %i\n", len, size);
     strncpy (dest, bigbuffer, size-1);
 }
Referenced by AddressBook_MenuInit(), AddressBook_MenuKey(), ApplyChanges(), CL_Download_f(), CL_DownloadFileName(), CL_DrawInventory(), CL_LoadClientinfo(), CL_ParseMuzzleFlash(), CL_ParseMuzzleFlash2(), CL_PingServers_f(), CL_Record_f(), CL_RegisterTEntSounds(), CL_RequestNextDownload(), CL_WriteConfiguration(), Cmd_PlayerList_f(), Cmd_Players_f(), Cmd_Say_f(), Com_Printf(), Con_DrawConsole(), Con_Dump_f(), Create_Savestrings(), CreateTargetChangeLevel(), Cvar_SetValue(), Cvar_WriteVariables(), DeathmatchScoreboardMessage(), DMFlagCallback(), Draw_FindPic(), ExitLevel(), FS_AddGameDirectory(), FS_Dir_f(), FS_ExecAutoexec(), FS_FOpenFile(), FS_SetGamedir(), func_clock_format_countdown(), func_clock_think(), GL_ScreenShot_f(), GLimp_EnableLogging(), HelpComputer(), Info_SetValueForKey(), InitGame(), JoinServerFunc(), Key_Event(), Keys_MenuKey(), LoadTrack(), M_DrawCursor(), Mod_LoadTexinfo(), NET_AdrToString(), PlayerConfig_MenuDraw(), PlayerConfig_MenuKey(), PlayerConfig_ScanDirectories(), QGL_Init(), R_BeginFrame(), R_BeginRegistration(), R_ScreenShot_f(), R_SetSky(), S_LoadSound(), S_RegisterSexedModel(), S_RegisterSexedSound(), SCR_DrawField(), SCR_PlayCinematic(), SCR_TouchPics(), SP_target_speaker(), StartServer_MenuInit(), SV_BeginDemoserver(), SV_CheckForSavegame(), SV_CopySaveGame(), SV_InitGame(), SV_Loadgame_f(), SV_Map_f(), SV_ReadLevelFile(), SV_ReadServerFile(), SV_ServerRecord_f(), SV_SpawnServer(), SV_StatusString(), SV_WipeSavegame(), SV_WriteLevelFile(), SV_WriteServerFile(), SVC_Info(), Sys_FindFirst(), Sys_FindNext(), Sys_GetGameAPI(), V_Gun_Model_f(), VID_CheckChanges(), Vk_ScreenShot_f(), Vkimp_EnableLogging(), and vtos().
COM_StripExtension()
void COM_StripExtension (char * in, char * out)
Definition at line 826 of file q_shared.c.
 {
     while (*in && *in != '.')
         *out++ = *in++;
     *out = 0;
 }
Referenced by CL_CheckOrDownloadFile(), and CL_Download_f().
CrossProduct()
void CrossProduct (vec3_t v1, vec3_t v2, vec3_t cross)
Definition at line 753 of file q_shared.c.
 {
     cross[0] = v1[1]*v2[2] - v1[2]*v2[1];
     cross[1] = v1[2]*v2[0] - v1[0]*v2[2];
     cross[2] = v1[0]*v2[1] - v1[1]*v2[0];
 }
Referenced by MakeNormalVectors(), PM_StepSlideMove_(), R_IMFlatShadedQuad(), RotatePointAroundVector(), and SV_FlyMove().
FloatNoSwap()
float FloatNoSwap (float f)
Definition at line 1001 of file q_shared.c.
 {
     return f;
 }
Referenced by Swap_Init().
FloatSwap()
float FloatSwap (float f)
Definition at line 984 of file q_shared.c.
 {
     union
     {
         float   f;
         byte    b[4];
     } dat1, dat2;
     dat1.f = f;
     dat2.b[0] = dat1.b[3];
     dat2.b[1] = dat1.b[2];
     dat2.b[2] = dat1.b[1];
     dat2.b[3] = dat1.b[0];
     return dat2.f;
 }
Referenced by Swap_Init().
Info_RemoveKey()
void Info_RemoveKey (char * s, char * key)
Definition at line 1295 of file q_shared.c.
 {
     char    *start;
     char    pkey[512];
     char    value[512];
     char    *o;
     if (strstr (key, "\\"))
     {
 //      Com_Printf ("Can't use a key with a \\\n");
         return;
     }
     while (1)
     {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\')
         {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value;
         while (*s != '\\' && *s)
         {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp (key, pkey) )
         {
             strcpy (start, s);  // remove this part
             return;
         }
         if (!*s)
             return;
     }
 }
Referenced by Info_SetValueForKey().
Info_SetValueForKey()
void Info_SetValueForKey (char * s, char * key, char * value)
Definition at line 1362 of file q_shared.c.
 {
     char    newi[MAX_INFO_STRING], *v;
     int     c;
     int     maxsize = MAX_INFO_STRING;
     if (strstr (key, "\\") || strstr (value, "\\") )
     {
         Com_Printf ("Can't use keys or values with a \\\n");
         return;
     }
     if (strstr (key, ";") )
     {
         Com_Printf ("Can't use keys or values with a semicolon\n");
         return;
     }
     if (strstr (key, "\"") || strstr (value, "\"") )
     {
         Com_Printf ("Can't use keys or values with a \"\n");
         return;
     }
     if (strlen(key) > MAX_INFO_KEY-1 || strlen(value) > MAX_INFO_KEY-1)
     {
         Com_Printf ("Keys and values must be < 64 characters.\n");
         return;
     }
     Info_RemoveKey (s, key);
     if (!value || !strlen(value))
         return;
     Com_sprintf (newi, sizeof(newi), "\\%s\\%s", key, value);
     if (strlen(newi) + strlen(s) > maxsize)
     {
         Com_Printf ("Info string length exceeded\n");
         return;
     }
     // only copy ascii values
     s += strlen(s);
     v = newi;
     while (*v)
     {
         c = *v++;
         c &= 127;       // strip high bits
         if (c >= 32 && c < 127)
             *s++ = c;
     }
     *s = 0;
 }
Referenced by ClientConnect(), Cvar_BitInfo(), and SVC_DirectConnect().
Info_Validate()
qboolean Info_Validate (char * s)
Definition at line 1353 of file q_shared.c.
 {
     if (strstr (s, "\""))
         return false;
     if (strstr (s, ";"))
         return false;
     return true;
 }
Referenced by ClientUserinfoChanged().
Info_ValueForKey()
char* Info_ValueForKey (char * s, char * key)
Definition at line 1253 of file q_shared.c.
 {
     char    pkey[512];
     static  char value[2][512]; // use two buffers so compares
                                 // work without stomping on each other
     static  int valueindex;
     char    *o;
     valueindex ^= 1;
     if (*s == '\\')
         s++;
     while (1)
     {
         o = pkey;
         while (*s != '\\')
         {
             if (!*s)
                 return "";
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value[valueindex];
         while (*s != '\\' && *s)
         {
             if (!*s)
                 return "";
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp (key, pkey) )
             return value[valueindex];
         if (!*s)
             return "";
         s++;
     }
 }
Referenced by ClientConnect(), ClientTeam(), ClientUserinfoChanged(), IsFemale(), IsNeutral(), PutClientInServer(), spectator_respawn(), SV_UserinfoChanged(), and SVC_DirectConnect().
LerpAngle()
float LerpAngle (float a2, float a1, float frac)
Definition at line 283 of file q_shared.c.
 {
     if (a1 - a2 > 180)
         a1 -= 360;
     if (a1 - a2 < -180)
         a1 += 360;
     return a2 + frac * (a1 - a2);
 }
Referenced by CL_AddPacketEntities(), CL_AddViewWeapon(), and CL_CalcViewValues().
LittleFloat()
float LittleFloat (float l)
Definition at line 950 of file q_shared.c.
 {return _LittleFloat(l);}
Referenced by CMod_LoadPlanes(), CMod_LoadSubmodels(), COM_BlockSequenceCheckByte(), Mod_LoadAliasModel(), Mod_LoadPlanes(), Mod_LoadSubmodels(), Mod_LoadTexinfo(), and Mod_LoadVertexes().
LittleLong()
int LittleLong (int l)
Definition at line 948 of file q_shared.c.
 {return _LittleLong(l);}
Referenced by CL_Record_f(), CL_RequestNextDownload(), CL_WriteDemoMessage(), CM_LoadMap(), CMod_LoadAreaPortals(), CMod_LoadAreas(), CMod_LoadBrushes(), CMod_LoadLeafs(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadSubmodels(), CMod_LoadSurfaces(), CMod_LoadVisibility(), COM_BlockSequenceCheckByte(), Draw_GetPalette(), FS_LoadPackFile(), GL_LoadWal(), Mod_ForName(), Mod_LoadAliasModel(), Mod_LoadBrushModel(), Mod_LoadFaces(), Mod_LoadLeafs(), Mod_LoadNodes(), Mod_LoadPlanes(), Mod_LoadSpriteModel(), Mod_LoadSubmodels(), Mod_LoadSurfedges(), Mod_LoadTexinfo(), Mod_LoadVisibility(), MSG_ReadFloat(), MSG_WriteFloat(), R_LoadWal(), SCR_PlayCinematic(), SCR_ReadNextFrame(), SV_RecordDemoMessage(), SV_SendClientMessages(), SV_ServerRecord_f(), and Vk_LoadWal().
LittleShort()
short LittleShort (short l)
Definition at line 946 of file q_shared.c.
 {return _LittleShort(l);}
Referenced by CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), LoadPCX(), LoadTGA(), Mod_LoadAliasModel(), Mod_LoadEdges(), Mod_LoadFaces(), Mod_LoadLeafs(), Mod_LoadMarksurfaces(), Mod_LoadNodes(), ResampleSfx(), S_RawSamples(), and WritePCXfile().
LongNoSwap()
int LongNoSwap (int l)
Definition at line 979 of file q_shared.c.
 {
     return l;
 }
Referenced by Swap_Init().
LongSwap()
int LongSwap (int l)
Definition at line 967 of file q_shared.c.
 {
     byte    b1,b2,b3,b4;
     b1 = l&255;
     b2 = (l>>8)&255;
     b3 = (l>>16)&255;
     b4 = (l>>24)&255;
     return ((int)b1<<24) + ((int)b2<<16) + ((int)b3<<8) + b4;
 }
Referenced by Swap_Init().
PerpendicularVector()
void PerpendicularVector (vec3_t dst, const vec3_t src)
Definition at line 152 of file q_shared.c.
 {
     int pos;
     int i;
     float minelem = 1.0F;
     vec3_t tempvec;
     /*
     ** find the smallest magnitude axially aligned vector
     */
     for ( pos = 0, i = 0; i < 3; i++ )
     {
         if ( fabs( src[i] ) < minelem )
         {
             pos = i;
             minelem = fabs( src[i] );
         }
     }
     tempvec[0] = tempvec[1] = tempvec[2] = 0.0F;
     tempvec[pos] = 1.0F;
     /*
     ** project the point onto the plane defined by src
     */
     ProjectPointOnPlane( dst, tempvec, src );
     /*
     ** normalize the result
     */
     VectorNormalize( dst );
 }
Referenced by R_DrawBeam(), and RotatePointAroundVector().
ProjectPointOnPlane()
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
Definition at line 130 of file q_shared.c.
 {
     float d;
     vec3_t n;
     float inv_denom;
     inv_denom = 1.0F / DotProduct( normal, normal );
     d = DotProduct( normal, p ) * inv_denom;
     n[0] = normal[0] * inv_denom;
     n[1] = normal[1] * inv_denom;
     n[2] = normal[2] * inv_denom;
     dst[0] = p[0] - d * n[0];
     dst[1] = p[1] - d * n[1];
     dst[2] = p[2] - d * n[2];
 }
Referenced by PerpendicularVector().
Q_fabs()
float Q_fabs (float f)
Definition at line 251 of file q_shared.c.
 {
 #if 0
     if (f >= 0)
         return f;
     return -f;
 #else
     int tmp = * ( int * ) &f;
     tmp &= 0x7FFFFFFF;
     return * ( float * ) &tmp;
 #endif
 }
Q_log2()
int Q_log2 (int val)
Definition at line 790 of file q_shared.c.
 {
     int answer=0;
     while (val>>=1)
         answer++;
     return answer;
 }
Q_strcasecmp()
int Q_strcasecmp (char * s1, char * s2)
Definition at line 1216 of file q_shared.c.
 {
     return Q_strncasecmp (s1, s2, 99999);
 }
Referenced by CD_f(), CL_AddPacketEntities(), Cmd_ExecuteString(), FS_FOpenFile(), Key_StringToKeynum(), and Miniaudio_f().
Q_stricmp()
int Q_stricmp (char * s1, char * s2)
Definition at line 1180 of file q_shared.c.
 {
 #if defined(WIN32)
     return _stricmp (s1, s2);
 #else
     return strcasecmp (s1, s2);
 #endif
 }
Referenced by CheckNeedPass(), CL_DrawInventory(), CL_FixUpGender(), CL_LoadClientinfo(), ClientCommand(), Cmd_Give_f(), door_use_areaportals(), ED_ParseField(), EndDMLevel(), FindItem(), FindItemByClassname(), G_Find(), G_UseTargets(), GL_TextureAlphaMode(), GL_TextureMode(), GL_TextureSolidMode(), JoinServerFunc(), Miniaudio_Play(), PlayerConfig_MenuInit(), R_BeginFrame(), SelectCoopSpawnPoint(), SelectSpawnPoint(), ServerCommand(), SP_CreateCoopSpots(), SP_FixCoopSpots(), SP_info_player_coop(), SP_info_player_start(), SP_monster_flyer(), SP_target_changelevel(), SP_target_secret(), SpawnEntities(), StartServerActionFunc(), SV_Map(), VID_MenuInit(), Vk_LmapTextureMode(), and Vk_TextureMode().
Q_strncasecmp()
int Q_strncasecmp (char * s1, char * s2, int n)
Definition at line 1190 of file q_shared.c.
 {
     int     c1, c2;
     do
     {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--)
             return 0;       // strings are equal until end point
         if (c1 != c2)
         {
             if (c1 >= 'a' && c1 <= 'z')
                 c1 -= ('a' - 'A');
             if (c2 >= 'a' && c2 <= 'z')
                 c2 -= ('a' - 'A');
             if (c1 != c2)
                 return -1;      // strings not equal
         }
     } while (c1);
     return 0;       // strings are equal
 }
Referenced by Q_strcasecmp().
R_ConcatRotations()
void R_ConcatRotations (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 191 of file q_shared.c.
 {
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
                 in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
                 in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
                 in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
                 in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
                 in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
                 in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
                 in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
                 in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
                 in1[2][2] * in2[2][2];
 }
Referenced by R_RotateBmodel(), and RotatePointAroundVector().
R_ConcatTransforms()
void R_ConcatTransforms (float in1[3][4], float in2[3][4], float out[3][4])
Definition at line 219 of file q_shared.c.
 {
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
                 in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
                 in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
                 in1[0][2] * in2[2][2];
     out[0][3] = in1[0][0] * in2[0][3] + in1[0][1] * in2[1][3] +
                 in1[0][2] * in2[2][3] + in1[0][3];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
                 in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
                 in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
                 in1[1][2] * in2[2][2];
     out[1][3] = in1[1][0] * in2[0][3] + in1[1][1] * in2[1][3] +
                 in1[1][2] * in2[2][3] + in1[1][3];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
                 in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
                 in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
                 in1[2][2] * in2[2][2];
     out[2][3] = in1[2][0] * in2[0][3] + in1[2][1] * in2[1][3] +
                 in1[2][2] * in2[2][3] + in1[2][3];
 }
Referenced by R_AliasSetUpTransform().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 32 of file q_shared.c.
 {
     float   m[3][3];
     float   im[3][3];
     float   zrot[3][3];
     float   tmpmat[3][3];
     float   rot[3][3];
     int i;
     vec3_t vr, vup, vf;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector( vr, dir );
     CrossProduct( vr, vf, vup );
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy( im, m, sizeof( im ) );
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset( zrot, 0, sizeof( zrot ) );
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     zrot[0][0] = cos( DEG2RAD( degrees ) );
     zrot[0][1] = sin( DEG2RAD( degrees ) );
     zrot[1][0] = -sin( DEG2RAD( degrees ) );
     zrot[1][1] = cos( DEG2RAD( degrees ) );
     R_ConcatRotations( m, zrot, tmpmat );
     R_ConcatRotations( tmpmat, im, rot );
     for ( i = 0; i < 3; i++ )
     {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
Referenced by R_DrawBeam(), and R_SetFrustum().
ShortNoSwap()
short ShortNoSwap (short l)
Definition at line 962 of file q_shared.c.
 {
     return l;
 }
Referenced by Swap_Init().
ShortSwap()
short ShortSwap (short l)
Definition at line 952 of file q_shared.c.
 {
     byte    b1,b2;
     b1 = l&255;
     b2 = (l>>8)&255;
     return (b1<<8) + b2;
 }
Referenced by Swap_Init().
sqrt()
double sqrt (double x)
Referenced by bfg_explode(), CL_AddBeams(), CL_AddPlayerBeams(), ClientEndServerFrame(), plat_CalcAcceleratedMove(), PM_Friction(), SV_Physics_Step(), vectoangles(), vectoangles2(), VectorLength(), VectorNormalize(), and VectorNormalize2().
Swap_Init()
void Swap_Init (void)
Definition at line 1011 of file q_shared.c.
 {
     byte    swaptest[2] = {1,0};
 // set the byte swapping variables in a portable manner
     if ( *(short *)swaptest == 1)
     {
         bigendien = false;
         _BigShort = ShortSwap;
         _LittleShort = ShortNoSwap;
         _BigLong = LongSwap;
         _LittleLong = LongNoSwap;
         _BigFloat = FloatSwap;
         _LittleFloat = FloatNoSwap;
     }
     else
     {
         bigendien = true;
         _BigShort = ShortNoSwap;
         _LittleShort = ShortSwap;
         _BigLong = LongNoSwap;
         _LittleLong = LongSwap;
         _BigFloat = FloatNoSwap;
         _LittleFloat = FloatSwap;
     }
 }
Referenced by GetRefAPI(), and Qcommon_Init().
va()
char* va (char * format, ...)
Definition at line 1050 of file q_shared.c.
 {
     va_list     argptr;
     static char     string[1024];
     va_start (argptr, format);
     vsnprintf (string, 1024, format, argptr);
     va_end (argptr);
     return string;
 }
Referenced by Cbuf_AddEarlyCommands(), CheckNeedPass(), CL_CheckOrDownloadFile(), CL_Connect_f(), CL_Download_f(), CL_PingServers_f(), CL_RequestNextDownload(), ClientUserinfoChanged(), Cmd_ExecuteString(), Com_Error(), CreateDynamicBuffers(), CreateFramebuffers(), CreateImageViews(), CreateStagingBuffers(), FS_InitFilesystem(), FS_SetGamedir(), insane_die(), insane_pain(), LM_UploadBlock(), LoadGameCallback(), NET_OpenIP(), NET_OpenIPX(), Netchan_Init(), P_DamageFeedback(), player_die(), Qcommon_Frame(), Qcommon_Init(), QVk_GetIndexBuffer(), QVk_GetUniformBuffer(), QVk_GetVertexBuffer(), QVk_Init(), SaveGameCallback(), SCR_ExecuteLayoutString(), SCR_FinishCinematic(), SP_worldspawn(), SpawnEntities(), StartServerActionFunc(), SV_Baselines_f(), SV_Configstrings_f(), SV_GameMap_f(), SV_Init(), SV_InitGame(), SV_Map(), SV_New_f(), Vk_BeginBuildingLightmaps(), and Vk_LoadPic().
VectorCompare()
int VectorCompare (vec3_t v1, vec3_t v2)
Definition at line 672 of file q_shared.c.
 {
     if (v1[0] != v2[0] || v1[1] != v2[1] || v1[2] != v2[2])
             return 0;
     return 1;
 }
Referenced by AngleMove_Final(), CL_AddPlayerBeams(), door_secret_use(), fire_lead(), G_SetMovedir(), InitTrigger(), rotating_use(), SP_trigger_multiple(), SV_FlyMove(), target_laser_think(), and Touch_Multi().
VectorInverse()
void VectorInverse (vec3_t v)
Definition at line 775 of file q_shared.c.
 {
     v[0] = -v[0];
     v[1] = -v[1];
     v[2] = -v[2];
 }
Referenced by R_AliasSetUpTransform(), and R_DrawSprite().
VectorLength()
vec_t VectorLength (vec3_t v)
Definition at line 762 of file q_shared.c.
 {
     int     i;
     float   length;
     length = 0;
     for (i=0 ; i< 3 ; i++)
         length += v[i]*v[i];
     length = sqrt (length);     // FIXME
     return length;
 }
Referenced by ai_run(), AngleMove_Begin(), bfg_explode(), boss2_attack(), check_dodge(), CL_AddPlayerBeams(), CL_BfgParticles(), findradius(), FindTarget(), fire_hit(), gladiator_attack(), Grenade_Explode(), jorg_attack(), makron_attack(), medic_cable_attack(), Mod_LoadTexinfo(), mutant_check_jump(), mutant_jump_touch(), parasite_drain_attack_ok(), PlayersRangeFromSpot(), PM_DeadMove(), PM_FlyMove(), R_LightPoint(), R_LightPointColor(), R_RenderDlight(), RadiusFromBounds(), range(), SP_FixCoopSpots(), supertank_attack(), SV_BuildClientFrame(), T_RadiusDamage(), tank_attack(), and turret_driver_link().
VectorMA()
void VectorMA (vec3_t veca, float scale, vec3_t vecb, vec3_t vecc)
Definition at line 719 of file q_shared.c.
 {
     vecc[0] = veca[0] + scale*vecb[0];
     vecc[1] = veca[1] + scale*vecb[1];
     vecc[2] = veca[2] + scale*vecb[2];
 }
Referenced by actorMachineGun(), barrel_explode(), bfg_explode(), bfg_think(), bfg_touch(), boss2_firebullet_left(), boss2_firebullet_right(), check_dodge(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_Heatbeam(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_ParseMuzzleFlash(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_RailTrail(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_Widowbeamout(), CL_WidowSplash(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_hit(), fire_lead(), fire_rail(), Grenade_Explode(), GunnerFire(), InfantryMachineGun(), jorg_firebullet_left(), jorg_firebullet_right(), MakeNormalVectors(), MakronSpawn(), medic_cable_attack(), mutant_jump_touch(), P_DamageFeedback(), PM_AddCurrents(), PM_CheckSpecialMovement(), PM_FlyMove(), R_DrawSpriteModel(), R_LightPoint(), R_LightPointColor(), RecursiveLightPoint(), rocket_touch(), RotatedBBox(), soldier_fire(), SP_func_button(), SP_func_door(), SP_func_door_rotating(), SP_func_door_secret(), SP_func_water(), SP_trigger_once(), supertankMachineGun(), SV_AddRotationalFriction(), SV_Physics_Noclip(), SV_Physics_Toss(), T_RadiusDamage(), target_laser_think(), ThrowDebris(), ThrowGib(), ThrowHead(), turret_breach_fire(), and UpdateChaseCam().
VectorNormalize()
vec_t VectorNormalize (vec3_t v)
Definition at line 681 of file q_shared.c.
 {
     float   length, ilength;
     length = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
     length = sqrt (length);     // FIXME
     if (length)
     {
         ilength = 1/length;
         v[0] *= ilength;
         v[1] *= ilength;
         v[2] *= ilength;
     }
     return length;
 }
Referenced by actorMachineGun(), bfg_think(), boss2_firebullet_left(), boss2_firebullet_right(), Boss2Rocket(), CheckPowerArmor(), ChickRocket(), CL_AddBeams(), CL_AddPlayerBeams(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DebugTrail(), CL_DiminishingTrail(), CL_FlagTrail(), CL_ForceWall(), CL_Heatbeam(), CL_IonripperTrail(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrackerTrail(), CL_TrapParticles(), CL_Widowbeamout(), CL_WidowSplash(), fire_blaster(), fire_hit(), fire_lead(), func_explosive_explode(), GladiatorGun(), GunnerFire(), InfantryMachineGun(), infront(), jorg_firebullet_left(), jorg_firebullet_right(), jorgBFG(), MakeNormalVectors(), makronBFG(), MakronRailgun(), MakronSpawn(), Mat_Rotate(), Move_Calc(), mutant_jump_touch(), P_DamageFeedback(), PerpendicularVector(), PM_AirMove(), PM_CheckSpecialMovement(), PM_DeadMove(), PM_FlyMove(), PM_StepSlideMove_(), PM_WaterMove(), R_DrawAliasModel(), R_DrawBeam(), R_IMFlatShadedQuad(), R_SetFrustum(), R_ViewChanged(), S_SpatializeOrigin(), soldier_fire(), supertankMachineGun(), supertankRocket(), T_Damage(), TankRocket(), target_laser_think(), and UpdateChaseCam().
VectorNormalize2()
vec_t VectorNormalize2 (vec3_t v, vec3_t out)
Definition at line 700 of file q_shared.c.
 {
     float   length, ilength;
     length = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
     length = sqrt (length);     // FIXME
     if (length)
     {
         ilength = 1/length;
         out[0] = v[0]*ilength;
         out[1] = v[1]*ilength;
         out[2] = v[2]*ilength;
     }
     return length;
 }
VectorScale()
void VectorScale (vec3_t in, vec_t scale, vec3_t out)
Definition at line 782 of file q_shared.c.
 {
     out[0] = in[0]*scale;
     out[1] = in[1]*scale;
     out[2] = in[2]*scale;
 }
Referenced by AngleMove_Begin(), AngleMove_Final(), Blaster_Fire(), CanDamage(), CL_AddPlayerBeams(), CL_BlasterTrail(), CL_BlasterTrail2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_DebugTrail(), CL_DiminishingTrail(), CL_FlagTrail(), CL_ForceWall(), CL_Heatbeam(), CL_IonripperTrail(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_QuadTrail(), CL_RailTrail(), CL_RocketTrail(), CL_SmokeTrail(), CL_TagTrail(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_TrackerTrail(), CL_TrapParticles(), D_CalcGradients(), Drop_Item(), fire_bfg(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_lead(), fire_rocket(), func_explosive_explode(), GL_DrawParticles(), misc_viper_bomb_prethink(), misc_viper_bomb_use(), Move_Begin(), Move_Final(), mutant_jump_takeoff(), PM_AirMove(), PM_CheckSpecialMovement(), PM_DeadMove(), PM_FlyMove(), PM_StepSlideMove_(), PM_WaterMove(), R_DrawBeam(), R_DrawParticles(), R_DrawSprite(), R_LightPoint(), R_LightPointColor(), RotatedBBox(), rotating_use(), SP_target_spawner(), SubdividePolygon(), SV_FlyMove(), SV_Physics_Pusher(), SV_Physics_Toss(), T_Damage(), Think_AccelMove(), ThrowGib(), trigger_push_touch(), turret_breach_think(), V_RenderView(), VelocityForDamage(), Vk_DrawParticles(), weapon_bfg_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
Variable Documentation
_BigFloat
float(* _BigFloat) (float l)
Definition at line 942 of file q_shared.c.
Referenced by BigFloat(), and Swap_Init().
_BigLong
int(* _BigLong) (int l)
Definition at line 940 of file q_shared.c.
Referenced by BigLong(), and Swap_Init().
_BigShort
short(* _BigShort) (short l)
Definition at line 938 of file q_shared.c.
Referenced by BigShort(), and Swap_Init().
_LittleFloat
float(* _LittleFloat) (float l)
Definition at line 943 of file q_shared.c.
Referenced by LittleFloat(), and Swap_Init().
_LittleLong
int(* _LittleLong) (int l)
Definition at line 941 of file q_shared.c.
Referenced by LittleLong(), and Swap_Init().
_LittleShort
short(* _LittleShort) (short l)
Definition at line 939 of file q_shared.c.
Referenced by LittleShort(), and Swap_Init().
bigendien
qboolean bigendien
Definition at line 934 of file q_shared.c.
Referenced by Swap_Init().
com_token
char com_token[MAX_TOKEN_CHARS]
Definition at line 1063 of file q_shared.c.
Referenced by Cmd_TokenizeString(), COM_Parse(), ED_ParseEdict(), and SpawnEntities().
corners
vec3_t corners[2]
Definition at line 306 of file q_shared.c.
Referenced by BoxOnPlaneSide2().
i
int i
Definition at line 305 of file q_shared.c.
Referenced by AddPointToBounds(), AddressBook_MenuInit(), ApplyChanges(), BeginIntermission(), BestColor(), BoundPoly(), BoxOnPlaneSide2(), BrightnessCallback(), CalcSurfaceExtents(), Cbuf_AddEarlyCommands(), Cbuf_AddLateCommands(), Cbuf_Execute(), CCheckParm(), Chaingun_Fire(), ChangeWeapon(), ChaseNext(), ChasePrev(), CheckBlock(), CheckDMRules(), CL_AddBeams(), CL_AddDLights(), CL_AddExplosions(), CL_AddLasers(), CL_AddLightStyles(), CL_AddNetgraph(), CL_AddPacketEntities(), CL_AddPlayerBeams(), CL_AddViewWeapon(), CL_AllocDlight(), CL_AllocExplosion(), CL_BFGExplosionParticles(), CL_BfgParticles(), CL_BigTeleportParticles(), CL_BlasterParticles(), CL_BlasterParticles2(), CL_BubbleTrail(), CL_BubbleTrail2(), CL_CalcViewValues(), CL_CheckPredictionError(), CL_ClearParticles(), CL_ClipMoveToEntities(), CL_ColorExplosionParticles(), CL_DrawInventory(), CL_ExplosionParticles(), CL_FinishMove(), CL_FixCvarCheats(), CL_FlyParticles(), CL_GenericParticleEffect(), CL_Heatbeam(), CL_ItemRespawnParticles(), CL_LoadClientinfo(), CL_LogoutEffect(), CL_MonsterPlasma_Shell(), CL_Nukeblast(), CL_Packet_f(), CL_ParseBeam(), CL_ParseBeam2(), CL_ParseConfigString(), CL_ParseEntityBits(), CL_ParseInventory(), CL_ParseLaser(), CL_ParseLightning(), CL_ParseMuzzleFlash(), CL_ParseNuke(), CL_ParsePlayerBeam(), CL_ParsePlayerstate(), CL_ParseServerData(), CL_ParseServerMessage(), CL_ParseSteam(), CL_ParseWidow(), CL_ParticleEffect(), CL_ParticleEffect2(), CL_ParticleEffect3(), CL_ParticleSmokeEffect(), CL_ParticleSteamEffect(), CL_ParticleSteamEffect2(), CL_PingServers_f(), CL_PMpointcontents(), CL_PredictMovement(), CL_PrepRefresh(), CL_ProcessSustain(), CL_RailTrail(), CL_Rcon_f(), CL_Record_f(), CL_RegisterSounds(), CL_RegisterTEntSounds(), CL_RequestNextDownload(), CL_RunDLights(), CL_RunLightStyles(), CL_SendCmd(), CL_Setenv_f(), CL_SetLightstyle(), CL_Skins_f(), CL_TeleporterParticles(), CL_TeleportParticles(), CL_Tracker_Explode(), CL_Tracker_Shell(), CL_TrapParticles(), CL_Widowbeamout(), CL_WidowSplash(), ClientBegin(), ClientConnect(), ClientEndServerFrame(), ClientEndServerFrames(), ClientThink(), ClipSkyPolygon(), ClipVelocity(), CM_BoxTrace(), CM_ClipBoxToBrush(), CM_InitBoxHull(), CM_LoadMap(), CM_RecursiveHullCheck(), CM_TestBoxInBrush(), CM_WriteAreaBits(), Cmd_Alias_f(), Cmd_Echo_f(), Cmd_Give_f(), Cmd_Inven_f(), Cmd_List_f(), Cmd_MacroExpandString(), Cmd_PlayerList_f(), Cmd_Players_f(), Cmd_Say_f(), Cmd_TokenizeString(), Cmd_Wave_f(), Cmd_WeapNext_f(), Cmd_WeapPrev_f(), CMod_LoadAreaPortals(), CMod_LoadAreas(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadSubmodels(), CMod_LoadSurfaces(), CMod_LoadVisibility(), codebook_decode(), codebook_decode_deinterleave_repeat(), codebook_decode_scalar_raw(), codebook_decode_step(), COM_CheckParm(), COM_FileExtension(), COM_InitArgv(), Com_PageInMemory(), compute_accelerated_huffman(), compute_bitreverse(), compute_codewords(), compute_samples(), compute_sorted_huffman(), compute_stereo_samples(), compute_window(), Con_CheckResize(), Con_ClearNotify(), Con_DrawConsole(), Con_DrawInput(), Con_DrawNotify(), convert_channels_short_interleaved(), convert_samples_short(), copy_samples(), crc32_init(), Create_Savestrings(), CreateDynamicBuffers(), CreateFramebuffers(), CreateImageViews(), CreatePipelines(), CreateRenderpasses(), CreateStagingBuffers(), Cvar_List_f(), D_ViewChanged(), DDRAW_Init(), DDRAW_SetPalette(), DeathmatchScoreboardMessage(), decode_residue(), DestroyFramebuffers(), DestroyImageViews(), DestroySamplers(), deviceExtensionsSupported(), DIB_Init(), DIB_SaveSystemColors(), DIB_SetPalette(), do_floor(), Draw_8to24(), Draw_BuildGammaTable(), Draw_Char(), Draw_GetPalette(), Draw_StretchRaw(), Draw_TileClear(), DrawGLFlowingPoly(), DrawGLPoly(), DrawHUDString(), DrawSkyPolygon(), DrawTextureChains(), DrawVkFlowingPoly(), DrawVkPoly(), ED_CallSpawn(), ED_NewString(), EmitWaterPolys(), ExitLevel(), Field_Draw(), FindItem(), FindItemByClassname(), fire_shotgun(), FloodArea_r(), FloodAreaConnections(), FreeFileList(), FreeSound(), FS_AddGameDirectory(), FS_Dir_f(), FS_FOpenFile(), FS_LoadPackFile(), G_CheckChaseStats(), G_FindTeams(), G_RunFrame(), G_Spawn(), G_TouchSolids(), G_TouchTriggers(), generateMipmaps(), get_seek_page_info(), getBestPhysicalDevice(), GetChaseTarget(), getSupportedCompositeAlpha(), getSwapPresentMode(), getSwapSurfaceFormat(), GetWavinfo(), GL_BeginBuildingLightmaps(), GL_BuildPalettedTexture(), GL_BuildPolygonFromSurface(), GL_DrawAliasFrameLerp(), GL_DrawParticles(), GL_DrawStereoPattern(), GL_FindImage(), GL_FreeUnusedImages(), GL_ImageList_f(), GL_InitImages(), GL_LerpVerts(), GL_LightScaleTexture(), GL_LoadPic(), GL_MipMap(), GL_RenderLightmappedPoly(), GL_ResampleTexture(), GL_ScreenShot_f(), GL_SetTexturePalette(), GL_ShutdownImages(), GL_SubdivideSurface(), GL_TextureAlphaMode(), GL_TextureMode(), GL_TextureSolidMode(), GL_Upload32(), GL_Upload8(), IconOfSkinExists(), imdct_step3_inner_r_loop(), imdct_step3_inner_s_loop(), imdct_step3_iter0_loop(), IN_Commands(), IN_JoyMove(), IN_MouseEvent(), InitBodyQue(), inverse_mdct(), JoinServer_MenuInit(), Joy_AdvancedUpdate_f(), Key_Bind_f(), Key_Bindlist_f(), Key_ClearStates(), Key_Console(), Key_Init(), Key_Unbindall_f(), Key_WriteBindings(), Keys_MenuInit(), LM_AllocBlock(), LM_UploadBlock(), LoadGame_MenuInit(), logArrayElement(), logEvalPoint1(), logEvalPoint2(), M_AddToServerList(), M_Credits_MenuDraw(), M_DrawCursor(), M_Main_Draw(), M_PushMenu(), Machinegun_Fire(), make_block_array(), Master_Heartbeat(), Master_Shutdown(), memsearch(), Menu_Draw(), Menu_DrawString(), Menu_DrawStringDark(), Menu_DrawStringR2L(), Menu_DrawStringR2LDark(), Menu_TallySlots(), Mod_ForName(), Mod_FreeAll(), Mod_LoadAliasModel(), Mod_LoadBrushModel(), Mod_LoadEdges(), Mod_LoadFaces(), Mod_LoadLeafs(), Mod_LoadLighting(), Mod_LoadMarksurfaces(), Mod_LoadNodes(), Mod_LoadPlanes(), Mod_LoadSpriteModel(), Mod_LoadSubmodels(), Mod_LoadSurfedges(), Mod_LoadTexinfo(), Mod_LoadVertexes(), Mod_LoadVisibility(), Mod_Modellist_f(), MSG_ReadData(), MSG_WriteDir(), neighbors(), NET_Config(), NET_GetLoopPacket(), NET_IPSocket(), NET_SendLoopPacket(), NET_Sleep(), P_DamageFeedback(), PerformMD4(), PerpendicularVector(), PF_setmodel(), player_die(), PlayerConfig_MenuInit(), PlayerConfig_MenuKey(), PlayerConfig_ScanDirectories(), PM_Accelerate(), PM_AirAccelerate(), PM_AirMove(), PM_ClampAngles(), PM_ClipVelocity(), PM_FlyMove(), PM_GoodPosition(), PM_SnapPosition(), PM_StepSlideMove_(), PM_WaterMove(), PutClientInServer(), QVk_CreatePipeline(), QVk_CreateSwapchain(), QVk_FindDepthFormat(), QVk_GetIndexBuffer(), QVk_GetUniformBuffer(), QVk_GetVertexBuffer(), QVk_Init(), QVk_Shutdown(), QVk_SubmitStagingBuffers(), R_AddDynamicLights(), R_AddDynamicLightsRGB(), R_AddSkySurface(), R_AliasCheckFrameBBox(), R_AliasClip(), R_AliasClipTriangle(), R_AliasClipTriangleRGB(), R_AliasPreparePoints(), R_AliasSetUpLerpData(), R_AliasSetupLighting(), R_AliasSetUpTransform(), R_AliasTransformFinalVerts(), R_BlendLightmaps(), R_BmodelCheckBBox(), R_BuildLightMap(), R_BuildLightMapRGB(), R_BuildPolygonFromSurface(), R_CalcPalette(), R_CinematicSetPalette(), R_ClearSkyBox(), R_ClipAndDrawPoly(), R_ClipPolyFace(), R_CullAliasModel(), R_CullBox(), R_DrawAliasModel(), R_DrawBeam(), R_DrawBEntitiesOnList(), R_DrawBrushModel(), R_DrawEntitiesOnList(), R_DrawInlineBModel(), R_DrawNullModel(), R_DrawParticles(), R_DrawPoly(), R_DrawSkyBox(), R_DrawSolidClippedSubmodelPolygons(), R_DrawSubmodelPolygons(), R_DrawSurfaceBlock8_mip0(), R_DrawSurfaceBlock8_mip1(), R_DrawSurfaceBlock8_mip2(), R_DrawSurfaceBlock8_mip3(), R_DrawSurfaceBlock8RGBX_mip0(), R_DrawSurfaceBlock8RGBX_mip1(), R_DrawSurfaceBlock8RGBX_mip2(), R_DrawSurfaceBlock8RGBX_mip3(), R_DrawTriangleOutlines(), R_EmitSkyBox(), R_EndRegistration(), R_FindFreeImage(), R_FindImage(), R_FloodFillSkin(), R_FreeUnusedImages(), R_GammaCorrectAndSetPalette(), R_ImageList_f(), R_InitSkyBox(), R_InitTurb(), R_MarkLeaves(), R_MarkLights(), R_PolygonScanLeftEdge(), R_PolygonScanRightEdge(), R_PolysetUpdateTables(), R_PushDlights(), R_RecursiveClipBPoly(), R_RecursiveWorldNode(), R_RegisterModel(), R_RenderBmodelFace(), R_RenderDlight(), R_RenderDlights(), R_RenderFace(), R_ScreenShot_f(), R_SetFrustum(), R_SetPalette(), R_SetSky(), R_SetupFrame(), R_SetUpFrustumIndexes(), R_ShutdownImages(), R_TransformFrustum(), R_ViewChanged(), RadiusFromBounds(), ReadGame(), ReadLevel(), RebuildTriangleFanIndexBuffer(), RecursiveLightPoint(), RecursiveLightPointColor(), ReleaseSwapBuffers(), ResampleSfx(), RotatedBBox(), RotatePointAroundVector(), S_AddLoopSounds(), S_AliasName(), S_EndRegistration(), S_FindName(), S_InitScaletable(), S_PaintChannelFrom16(), S_PaintChannelFrom8(), S_PaintChannels(), S_Play(), S_RawSamples(), S_Shutdown(), S_SoundList(), S_StopAllSounds(), S_TransferPaintBuffer(), S_Update(), S_WriteLinearBlastStereo16(), SaveClientData(), SaveGame_MenuInit(), SCR_CenterPrint(), SCR_DrawDebugGraph(), SCR_TimeRefresh_f(), SCR_TouchPics(), SCR_UpdateScreen(), Scrap_AllocBlock(), SearchLocalGames(), seek_to_sample_coarse(), SelectNextItem(), SelectPrevItem(), SetItemNames(), Slider_Draw(), SmallestNode1(), SNDDMA_InitWav(), SpawnEntities(), spectator_respawn(), start_decoder(), start_page_no_capturepattern(), StartServer_MenuInit(), StartServer_MenuKey(), StartServerActionFunc(), stb_vorbis_decode_frame_pushdata(), stb_vorbis_get_frame_float(), stb_vorbis_get_samples_float(), stb_vorbis_get_samples_float_interleaved(), StringToFilter(), SubdividePolygon(), SV_BroadcastPrintf(), SV_BuildClientFrame(), SV_CalcGunOffset(), SV_CalcPings(), SV_CheckForSavegame(), SV_CheckTimeouts(), SV_CheckVelocity(), SV_ClipMoveToEntities(), SV_CloseEnough(), SV_FatPVS(), SV_FilterPacket(), SV_FinalMessage(), SV_FindIndex(), SV_FlyMove(), SV_GameMap_f(), SV_GiveMsec(), SV_InitGame(), SV_LinkEdict(), SV_movestep(), SV_PointContents(), SV_PrepWorldFrame(), SV_Push(), SV_RateDrop(), SV_ReadPackets(), SV_SendClientMessages(), SV_ServerRecord_f(), SV_SetMaster_f(), SV_SetPlayer(), SV_SpawnServer(), SV_StartSound(), SV_Status_f(), SV_StatusString(), SV_TraceBounds(), SV_UserinfoChanged(), SV_WritePlayerstateToClient(), SVC_DirectConnect(), SVC_GetChallenge(), SVC_Info(), SVC_RemoteCommand(), SVCmd_AddIP_f(), SVCmd_ListIP_f(), SVCmd_RemoveIP_f(), SVCmd_WriteIP_f(), target_earthquake_think(), teleporter_touch(), UpdateChaseCam(), V_TestEntities(), V_TestLights(), V_TestParticles(), VectorLength(), VID_MenuInit(), Vk_BeginBuildingLightmaps(), Vk_BuildPolygonFromSurface(), Vk_DrawAliasFrameLerp(), Vk_DrawAliasShadow(), Vk_DrawParticles(), Vk_FindImage(), Vk_FreeUnusedImages(), Vk_ImageList_f(), Vk_InitImages(), Vk_LerpVerts(), Vk_LightScaleTexture(), Vk_LmapTextureMode(), Vk_LoadPic(), Vk_RenderLightmappedPoly(), Vk_ResampleTexture(), Vk_ScreenShot_f(), Vk_ShutdownImages(), Vk_Strings_f(), Vk_SubdivideSurface(), Vk_TextureMode(), Vk_Upload8(), vorbis_decode_initial(), vorbis_decode_packet_rest(), vorbis_deinit(), vorbis_find_page(), vorbis_finish_frame(), vorbis_search_for_page_pushdata(), WinMain(), WriteGame(), WriteLevel(), and WritePCXfile().
paged_total
int paged_total
Definition at line 1159 of file q_shared.c.
Referenced by Com_PageInMemory().
vec3_origin
vec3_t vec3_origin = {0,0,0}
Definition at line 24 of file q_shared.c.
Referenced by AngleMove_Final(), bfg_explode(), bfg_think(), blaster_touch(), CanDamage(), CL_AddPlayerBeams(), CL_ClipMoveToEntities(), CL_ParseMuzzleFlash2(), CL_WidowSplash(), Cmd_Kill_f(), D_DrawSurfaces(), door_blocked(), door_secret_blocked(), door_secret_move6(), door_secret_use(), DrawSkyPolygon(), fire_hit(), floater_zap(), func_explosive_use(), func_object_touch(), Grenade_Explode(), hurt_touch(), InitTrigger(), KillBox(), M_CheckBottom(), M_WorldEffects(), MakronSpawn(), P_FallingDamage(), P_WorldEffects(), parasite_drain_attack(), PF_Configstring(), plat_blocked(), PM_FlyMove(), PM_StepSlideMove_(), R_BuildPolygonFromSurface(), R_DrawEntitiesOnList(), R_LightPoint(), R_LightPointColor(), RecursiveLightPoint(), RecursiveLightPointColor(), rotating_blocked(), rotating_touch(), rotating_use(), SP_trigger_multiple(), SV_ClipMoveToEntities(), SV_FindIndex(), SV_FlyMove(), SV_Physics_Toss(), SV_PointContents(), SV_Push(), SV_Trace(), T_RadiusDamage(), target_laser_think(), Touch_Multi(), train_blocked(), turret_blocked(), UpdateChaseCam(), use_target_changelevel(), visible(), and Weapon_Blaster_Fire().