vkQuake2 doxygen: C:/entry/dev/vq2/src/client/keys.h File Reference
keys.h File Reference
Macros
#define K_TAB 9
#define K_ENTER 13
#define K_ESCAPE 27
#define K_SPACE 32
#define K_BACKSPACE 127
#define K_UPARROW 128
#define K_DOWNARROW 129
#define K_LEFTARROW 130
#define K_RIGHTARROW 131
#define K_ALT 132
#define K_CTRL 133
#define K_SHIFT 134
#define K_F1 135
#define K_F2 136
#define K_F3 137
#define K_F4 138
#define K_F5 139
#define K_F6 140
#define K_F7 141
#define K_F8 142
#define K_F9 143
#define K_F10 144
#define K_F11 145
#define K_F12 146
#define K_INS 147
#define K_DEL 148
#define K_PGDN 149
#define K_PGUP 150
#define K_HOME 151
#define K_END 152
#define K_CMD 153
#define K_KP_HOME 160
#define K_KP_UPARROW 161
#define K_KP_PGUP 162
#define K_KP_LEFTARROW 163
#define K_KP_5 164
#define K_KP_RIGHTARROW 165
#define K_KP_END 166
#define K_KP_DOWNARROW 167
#define K_KP_PGDN 168
#define K_KP_ENTER 169
#define K_KP_INS 170
#define K_KP_DEL 171
#define K_KP_SLASH 172
#define K_KP_MINUS 173
#define K_KP_PLUS 174
#define K_PAUSE 255
#define K_MOUSE1 200
#define K_MOUSE2 201
#define K_MOUSE3 202
#define K_JOY1 203
#define K_JOY2 204
#define K_JOY3 205
#define K_JOY4 206
#define K_AUX1 207
#define K_AUX2 208
#define K_AUX3 209
#define K_AUX4 210
#define K_AUX5 211
#define K_AUX6 212
#define K_AUX7 213
#define K_AUX8 214
#define K_AUX9 215
#define K_AUX10 216
#define K_AUX11 217
#define K_AUX12 218
#define K_AUX13 219
#define K_AUX14 220
#define K_AUX15 221
#define K_AUX16 222
#define K_AUX17 223
#define K_AUX18 224
#define K_AUX19 225
#define K_AUX20 226
#define K_AUX21 227
#define K_AUX22 228
#define K_AUX23 229
#define K_AUX24 230
#define K_AUX25 231
#define K_AUX26 232
#define K_AUX27 233
#define K_AUX28 234
#define K_AUX29 235
#define K_AUX30 236
#define K_AUX31 237
#define K_AUX32 238
#define K_MWHEELDOWN 239
#define K_MWHEELUP 240
Functions
void Key_Event (int key, qboolean down, unsigned time)
void Key_Init (void)
void Key_WriteBindings (FILE *f)
void Key_SetBinding (int keynum, char *binding)
void Key_ClearStates (void)
int Key_GetKey (void)
Variables
char * keybindings [256]
int key_repeats [256]
int anykeydown
char chat_buffer []
int chat_bufferlen
qboolean chat_team
Macro Definition Documentation
K_ALT
#define K_ALT 132
Definition at line 38 of file keys.h.
K_AUX1
#define K_AUX1 207
Definition at line 98 of file keys.h.
K_AUX10
#define K_AUX10 216
Definition at line 107 of file keys.h.
K_AUX11
#define K_AUX11 217
Definition at line 108 of file keys.h.
K_AUX12
#define K_AUX12 218
Definition at line 109 of file keys.h.
K_AUX13
#define K_AUX13 219
Definition at line 110 of file keys.h.
K_AUX14
#define K_AUX14 220
Definition at line 111 of file keys.h.
K_AUX15
#define K_AUX15 221
Definition at line 112 of file keys.h.
K_AUX16
#define K_AUX16 222
Definition at line 113 of file keys.h.
K_AUX17
#define K_AUX17 223
Definition at line 114 of file keys.h.
K_AUX18
#define K_AUX18 224
Definition at line 115 of file keys.h.
K_AUX19
#define K_AUX19 225
Definition at line 116 of file keys.h.
K_AUX2
#define K_AUX2 208
Definition at line 99 of file keys.h.
K_AUX20
#define K_AUX20 226
Definition at line 117 of file keys.h.
K_AUX21
#define K_AUX21 227
Definition at line 118 of file keys.h.
K_AUX22
#define K_AUX22 228
Definition at line 119 of file keys.h.
K_AUX23
#define K_AUX23 229
Definition at line 120 of file keys.h.
K_AUX24
#define K_AUX24 230
Definition at line 121 of file keys.h.
K_AUX25
#define K_AUX25 231
Definition at line 122 of file keys.h.
K_AUX26
#define K_AUX26 232
Definition at line 123 of file keys.h.
K_AUX27
#define K_AUX27 233
Definition at line 124 of file keys.h.
K_AUX28
#define K_AUX28 234
Definition at line 125 of file keys.h.
K_AUX29
#define K_AUX29 235
Definition at line 126 of file keys.h.
K_AUX3
#define K_AUX3 209
Definition at line 100 of file keys.h.
K_AUX30
#define K_AUX30 236
Definition at line 127 of file keys.h.
K_AUX31
#define K_AUX31 237
Definition at line 128 of file keys.h.
K_AUX32
#define K_AUX32 238
Definition at line 129 of file keys.h.
K_AUX4
#define K_AUX4 210
Definition at line 101 of file keys.h.
K_AUX5
#define K_AUX5 211
Definition at line 102 of file keys.h.
K_AUX6
#define K_AUX6 212
Definition at line 103 of file keys.h.
K_AUX7
#define K_AUX7 213
Definition at line 104 of file keys.h.
K_AUX8
#define K_AUX8 214
Definition at line 105 of file keys.h.
K_AUX9
#define K_AUX9 215
Definition at line 106 of file keys.h.
K_BACKSPACE
#define K_BACKSPACE 127
Definition at line 32 of file keys.h.
K_CMD
#define K_CMD 153
Definition at line 59 of file keys.h.
K_CTRL
#define K_CTRL 133
Definition at line 39 of file keys.h.
K_DEL
#define K_DEL 148
Definition at line 54 of file keys.h.
K_DOWNARROW
#define K_DOWNARROW 129
Definition at line 34 of file keys.h.
K_END
#define K_END 152
Definition at line 58 of file keys.h.
K_ENTER
#define K_ENTER 13
Definition at line 26 of file keys.h.
K_ESCAPE
#define K_ESCAPE 27
Definition at line 27 of file keys.h.
K_F1
#define K_F1 135
Definition at line 41 of file keys.h.
K_F10
#define K_F10 144
Definition at line 50 of file keys.h.
K_F11
#define K_F11 145
Definition at line 51 of file keys.h.
K_F12
#define K_F12 146
Definition at line 52 of file keys.h.
K_F2
#define K_F2 136
Definition at line 42 of file keys.h.
K_F3
#define K_F3 137
Definition at line 43 of file keys.h.
K_F4
#define K_F4 138
Definition at line 44 of file keys.h.
K_F5
#define K_F5 139
Definition at line 45 of file keys.h.
K_F6
#define K_F6 140
Definition at line 46 of file keys.h.
K_F7
#define K_F7 141
Definition at line 47 of file keys.h.
K_F8
#define K_F8 142
Definition at line 48 of file keys.h.
K_F9
#define K_F9 143
Definition at line 49 of file keys.h.
K_HOME
#define K_HOME 151
Definition at line 57 of file keys.h.
K_INS
#define K_INS 147
Definition at line 53 of file keys.h.
K_JOY1
#define K_JOY1 203
Definition at line 89 of file keys.h.
K_JOY2
#define K_JOY2 204
Definition at line 90 of file keys.h.
K_JOY3
#define K_JOY3 205
Definition at line 91 of file keys.h.
K_JOY4
#define K_JOY4 206
Definition at line 92 of file keys.h.
K_KP_5
#define K_KP_5 164
Definition at line 65 of file keys.h.
K_KP_DEL
#define K_KP_DEL 171
Definition at line 72 of file keys.h.
K_KP_DOWNARROW
#define K_KP_DOWNARROW 167
Definition at line 68 of file keys.h.
K_KP_END
#define K_KP_END 166
Definition at line 67 of file keys.h.
K_KP_ENTER
#define K_KP_ENTER 169
Definition at line 70 of file keys.h.
K_KP_HOME
#define K_KP_HOME 160
Definition at line 61 of file keys.h.
K_KP_INS
#define K_KP_INS 170
Definition at line 71 of file keys.h.
K_KP_LEFTARROW
#define K_KP_LEFTARROW 163
Definition at line 64 of file keys.h.
K_KP_MINUS
#define K_KP_MINUS 173
Definition at line 74 of file keys.h.
K_KP_PGDN
#define K_KP_PGDN 168
Definition at line 69 of file keys.h.
K_KP_PGUP
#define K_KP_PGUP 162
Definition at line 63 of file keys.h.
K_KP_PLUS
#define K_KP_PLUS 174
Definition at line 75 of file keys.h.
K_KP_RIGHTARROW
#define K_KP_RIGHTARROW 165
Definition at line 66 of file keys.h.
K_KP_SLASH
#define K_KP_SLASH 172
Definition at line 73 of file keys.h.
K_KP_UPARROW
#define K_KP_UPARROW 161
Definition at line 62 of file keys.h.
K_LEFTARROW
#define K_LEFTARROW 130
Definition at line 35 of file keys.h.
K_MOUSE1
#define K_MOUSE1 200
Definition at line 82 of file keys.h.
K_MOUSE2
#define K_MOUSE2 201
Definition at line 83 of file keys.h.
K_MOUSE3
#define K_MOUSE3 202
Definition at line 84 of file keys.h.
K_MWHEELDOWN
#define K_MWHEELDOWN 239
Definition at line 131 of file keys.h.
K_MWHEELUP
#define K_MWHEELUP 240
Definition at line 132 of file keys.h.
K_PAUSE
#define K_PAUSE 255
Definition at line 77 of file keys.h.
K_PGDN
#define K_PGDN 149
Definition at line 55 of file keys.h.
K_PGUP
#define K_PGUP 150
Definition at line 56 of file keys.h.
K_RIGHTARROW
#define K_RIGHTARROW 131
Definition at line 36 of file keys.h.
K_SHIFT
#define K_SHIFT 134
Definition at line 40 of file keys.h.
K_SPACE
#define K_SPACE 32
Definition at line 28 of file keys.h.
K_TAB
#define K_TAB 9
Definition at line 25 of file keys.h.
K_UPARROW
#define K_UPARROW 128
Definition at line 33 of file keys.h.
Function Documentation
Key_ClearStates()
void Key_ClearStates (void)
Definition at line 935 of file keys.c.
 {
     int     i;
     anykeydown = false;
     for (i=0 ; i<256 ; i++)
     {
         if ( keydown[i] || key_repeats[i] )
             Key_Event( i, false, 0 );
         keydown[i] = 0;
         key_repeats[i] = 0;
     }
 }
Referenced by AppActivate(), and M_ForceMenuOff().
Key_Event()
void Key_Event (int key, qboolean down, unsigned time)
Definition at line 744 of file keys.c.
 {
     char    *kb;
     char    cmd[1024];
     // hack for modal presses
     if (key_waiting == -1)
     {
         if (down)
             key_waiting = key;
         return;
     }
     keydown[key] = down;
     // ALT+ENTER fullscreen toggle
     if (down && keydown[K_ALT] && key == K_ENTER)
     {
         extern cvar_t *vid_fullscreen;
         Cvar_Set("vid_fullscreen", vid_fullscreen->value ? "0" : "1");
         vid_fullscreen->modified = true;
         return;
     }
 #ifdef __APPLE__
     // ALT+F4 game shutdown
     if (down && keydown[K_ALT] && key == K_F4)
     {
         CL_Quit_f();
         return;
     }
 #endif
     // update auto-repeat status
     if (down)
     {
         key_repeats[key]++;
         if (key != K_BACKSPACE
             && key != K_PAUSE
             && key != K_PGUP
             && key != K_KP_PGUP
             && key != K_PGDN
             && key != K_KP_PGDN
             && key_repeats[key] > 1)
             return; // ignore most autorepeats
         if (key >= 200 && key != K_MWHEELUP && key != K_MWHEELDOWN && !keybindings[key])
             Com_Printf ("%s is unbound, hit F4 to set.\n", Key_KeynumToString (key) );
     }
     else
     {
         key_repeats[key] = 0;
     }
     if (key == K_SHIFT)
         shift_down = down;
     // console key is hardcoded, so the user can never unbind it
     if (key == '`' || key == '~')
     {
         if (!down)
             return;
         Con_ToggleConsole_f ();
         return;
     }
     // any key during the attract mode will bring up the menu
     if (cl.attractloop && cls.key_dest != key_menu &&
         !(key >= K_F1 && key <= K_F12))
         key = K_ESCAPE;
     // menu key is hardcoded, so the user can never unbind it
     if (key == K_ESCAPE)
     {
         if (!down)
             return;
         if (cl.frame.playerstate.stats[STAT_LAYOUTS] && cls.key_dest == key_game)
         {   // put away help computer / inventory
             Cbuf_AddText ("cmd putaway\n");
             return;
         }
         switch (cls.key_dest)
         {
         case key_message:
             Key_Message (key);
             break;
         case key_menu:
             M_Keydown (key);
             break;
         case key_game:
         case key_console:
             M_Menu_Main_f ();
             break;
         default:
             Com_Error (ERR_FATAL, "Bad cls.key_dest");
         }
         return;
     }
     if (down)
     {
         if (key_repeats[key] == 1)
             anykeydown++;
     }
     else
     {
         anykeydown--;
         if (anykeydown < 0)
             anykeydown = 0;
     }
 //
 // key up events only generate commands if the game key binding is
 // a button command (leading + sign).  These will occur even in console mode,
 // to keep the character from continuing an action started before a console
 // switch.  Button commands include the kenum as a parameter, so multiple
 // downs can be matched with ups
 //
     if (!down)
     {
         kb = keybindings[key];
         if (kb && kb[0] == '+')
         {
             Com_sprintf (cmd, sizeof(cmd), "-%s %i %i\n", kb+1, key, time);
             Cbuf_AddText (cmd);
         }
         if (keyshift[key] != key)
         {
             kb = keybindings[keyshift[key]];
             if (kb && kb[0] == '+')
             {
                 Com_sprintf (cmd, sizeof(cmd), "-%s %i %i\n", kb+1, key, time);
                 Cbuf_AddText (cmd);
             }
         }
         return;
     }
 //
 // if not a consolekey, send to the interpreter no matter what mode is
 //
     if ( (cls.key_dest == key_menu && menubound[key])
     || (cls.key_dest == key_console && !consolekeys[key])
     || (cls.key_dest == key_game && ( cls.state == ca_active || !consolekeys[key] ) ) )
     {
         kb = keybindings[key];
         if (kb)
         {
             if (kb[0] == '+')
             {   // button commands add keynum and time as a parm
                 Com_sprintf (cmd, sizeof(cmd), "%s %i %i\n", kb, key, time);
                 Cbuf_AddText (cmd);
             }
             else
             {
                 Cbuf_AddText (kb);
                 Cbuf_AddText ("\n");
             }
         }
         return;
     }
     if (!down)
         return;     // other systems only care about key down events
     if (shift_down)
         key = keyshift[key];
     switch (cls.key_dest)
     {
     case key_message:
         Key_Message (key);
         break;
     case key_menu:
         M_Keydown (key);
         break;
     case key_game:
     case key_console:
         Key_Console (key);
         break;
     default:
         Com_Error (ERR_FATAL, "Bad cls.key_dest");
     }
 }
Referenced by IN_Commands(), IN_MouseEvent(), Key_ClearStates(), and MainWndProc().
Key_GetKey()
int Key_GetKey (void)
Definition at line 956 of file keys.c.
 {
     key_waiting = -1;
     while (key_waiting == -1)
         Sys_SendKeyEvents ();
     return key_waiting;
 }
Key_Init()
void Key_Init (void)
Definition at line 647 of file keys.c.
 {
     int     i;
     for (i=0 ; i<128 ; i++)
     {
         key_lines[i][0] = ']';
         key_lines[i][1] = 0;
     }
     key_linepos = 1;
 //
 // init ascii characters in console mode
 //
     for (i=32 ; i<128 ; i++)
         consolekeys[i] = true;
     consolekeys[K_ENTER] = true;
     consolekeys[K_KP_ENTER] = true;
     consolekeys[K_TAB] = true;
     consolekeys[K_LEFTARROW] = true;
     consolekeys[K_KP_LEFTARROW] = true;
     consolekeys[K_RIGHTARROW] = true;
     consolekeys[K_KP_RIGHTARROW] = true;
     consolekeys[K_UPARROW] = true;
     consolekeys[K_KP_UPARROW] = true;
     consolekeys[K_DOWNARROW] = true;
     consolekeys[K_KP_DOWNARROW] = true;
     consolekeys[K_BACKSPACE] = true;
     consolekeys[K_HOME] = true;
     consolekeys[K_KP_HOME] = true;
     consolekeys[K_END] = true;
     consolekeys[K_KP_END] = true;
     consolekeys[K_PGUP] = true;
     consolekeys[K_KP_PGUP] = true;
     consolekeys[K_PGDN] = true;
     consolekeys[K_KP_PGDN] = true;
     consolekeys[K_MWHEELUP] = true;
     consolekeys[K_MWHEELDOWN] = true;
     consolekeys[K_SHIFT] = true;
     consolekeys[K_INS] = true;
     consolekeys[K_KP_INS] = true;
     consolekeys[K_KP_DEL] = true;
     consolekeys[K_KP_SLASH] = true;
     consolekeys[K_KP_PLUS] = true;
     consolekeys[K_KP_MINUS] = true;
     consolekeys[K_KP_5] = true;
     consolekeys['`'] = false;
     consolekeys['~'] = false;
     for (i=0 ; i<256 ; i++)
         keyshift[i] = i;
     for (i='a' ; i<='z' ; i++)
         keyshift[i] = i - 'a' + 'A';
     keyshift['1'] = '!';
     keyshift['2'] = '@';
     keyshift['3'] = '#';
     keyshift['4'] = '$';
     keyshift['5'] = '%';
     keyshift['6'] = '^';
     keyshift['7'] = '&';
     keyshift['8'] = '*';
     keyshift['9'] = '(';
     keyshift['0'] = ')';
     keyshift['-'] = '_';
     keyshift['='] = '+';
     keyshift[','] = '<';
     keyshift['.'] = '>';
     keyshift['/'] = '?';
     keyshift[';'] = ':';
     keyshift['\''] = '"';
     keyshift['['] = '{';
     keyshift[']'] = '}';
     keyshift['`'] = '~';
     keyshift['\\'] = '|';
     menubound[K_ESCAPE] = true;
     for (i=0 ; i<12 ; i++)
         menubound[K_F1+i] = true;
 //
 // register our functions
 //
     Cmd_AddCommand ("bind",Key_Bind_f);
     Cmd_AddCommand ("unbind",Key_Unbind_f);
     Cmd_AddCommand ("unbindall",Key_Unbindall_f);
     Cmd_AddCommand ("bindlist",Key_Bindlist_f);
 }
Key_SetBinding()
void Key_SetBinding (int keynum, char * binding)
Definition at line 506 of file keys.c.
 {
     char    *new;
     int     l;
     if (keynum == -1)
         return;
 // free old bindings
     if (keybindings[keynum])
     {
         Z_Free (keybindings[keynum]);
         keybindings[keynum] = NULL;
     }
 // allocate memory for new binding
     l = (int)strlen (binding);
     new = Z_Malloc (l+1);
     strcpy (new, binding);
     new[l] = 0;
     keybindings[keynum] = new;
 }
Referenced by Key_Bind_f(), Key_Unbind_f(), Key_Unbindall_f(), and M_UnbindCommand().
Key_WriteBindings()
void Key_WriteBindings (FILE * f)
Definition at line 616 of file keys.c.
 {
     int     i;
     for (i=0 ; i<256 ; i++)
         if (keybindings[i] && keybindings[i][0])
             fprintf (f, "bind %s \"%s\"\n", Key_KeynumToString(i), keybindings[i]);
 }
Referenced by CL_WriteConfiguration().
Variable Documentation
anykeydown
int anykeydown
Definition at line 34 of file keys.c.
Referenced by CL_FinishMove(), Key_ClearStates(), and Key_Event().
chat_buffer
char chat_buffer[]
Definition at line 392 of file keys.c.
Referenced by Con_DrawNotify(), and Key_Message().
chat_bufferlen
int chat_bufferlen
Definition at line 393 of file keys.c.
Referenced by Con_DrawNotify(), and Key_Message().
chat_team
qboolean chat_team
Definition at line 391 of file keys.c.
Referenced by Con_DrawNotify(), Con_MessageMode2_f(), Con_MessageMode_f(), and Key_Message().
key_repeats
int key_repeats[256]
Definition at line 44 of file keys.c.
Referenced by Key_ClearStates(), and Key_Event().
keybindings
char* keybindings[256]
Definition at line 40 of file keys.c.
Referenced by CL_DrawInventory(), Key_Bind_f(), Key_Bindlist_f(), Key_Event(), Key_SetBinding(), Key_Unbindall_f(), Key_WriteBindings(), M_FindKeysForCommand(), and M_UnbindCommand().