vq2 doxygen: game_import_t Struct Reference
game_import_t Struct Reference
#include <game.h>
Public Attributes
void(* bprintf)(int printlevel, char *fmt,...)
void(* dprintf)(char *fmt,...)
void(* cprintf)(edict_t *ent, int printlevel, char *fmt,...)
void(* centerprintf)(edict_t *ent, char *fmt,...)
void(* sound)(edict_t *ent, int channel, int soundindex, float volume, float attenuation, float timeofs)
void(* positioned_sound)(vec3_t origin, edict_t *ent, int channel, int soundinedex, float volume, float attenuation, float timeofs)
void(* configstring)(int num, char *string)
void(* error)(char *fmt,...)
int(* modelindex)(char *name)
int(* soundindex)(char *name)
int(* imageindex)(char *name)
void(* setmodel)(edict_t *ent, char *name)
trace_t(* trace)(vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, edict_t *passent, int contentmask)
int(* pointcontents)(vec3_t point)
qboolean(* inPVS)(vec3_t p1, vec3_t p2)
qboolean(* inPHS)(vec3_t p1, vec3_t p2)
void(* SetAreaPortalState)(int portalnum, qboolean open)
qboolean(* AreasConnected)(int area1, int area2)
void(* linkentity)(edict_t *ent)
void(* unlinkentity)(edict_t *ent)
int(* BoxEdicts)(vec3_t mins, vec3_t maxs, edict_t **list, int maxcount, int areatype)
void(* Pmove)(pmove_t *pmove)
void(* multicast)(vec3_t origin, multicast_t to)
void(* unicast)(edict_t *ent, qboolean reliable)
void(* WriteChar)(int c)
void(* WriteByte)(int c)
void(* WriteShort)(int c)
void(* WriteLong)(int c)
void(* WriteFloat)(float f)
void(* WriteString)(char *s)
void(* WritePosition)(vec3_t pos)
void(* WriteDir)(vec3_t pos)
void(* WriteAngle)(float f)
void *(* TagMalloc)(int size, int tag)
void(* TagFree)(void *block)
void(* FreeTags)(int tag)
cvar_t *(* cvar)(char *var_name, char *value, int flags)
cvar_t *(* cvar_set)(char *var_name, char *value)
cvar_t *(* cvar_forceset)(char *var_name, char *value)
int(* argc)(void)
char *(* argv)(int n)
char *(* args)(void)
void(* AddCommandString)(char *text)
void(* DebugGraph)(float value, int color)
Detailed Description
Definition at line 109 of file game.h.
Member Data Documentation
AddCommandString
void(* game_import_t::AddCommandString)(char *text)
Definition at line 180 of file game.h.
Referenced by CTFBoot(), ExitLevel(), and respawn().
AreasConnected
qboolean(* game_import_t::AreasConnected)(int area1, int area2)
Definition at line 140 of file game.h.
Referenced by FindTarget().
argc
int(* game_import_t::argc)(void)
Definition at line 174 of file game.h.
Referenced by Cmd_Give_f(), Cmd_Say_f(), CTFAdmin(), CTFBoot(), CTFGhost(), CTFWarp(), SVCmd_AddIP_f(), and SVCmd_RemoveIP_f().
args
char *(* game_import_t::args)(void)
Definition at line 176 of file game.h.
Referenced by ClientCommand(), Cmd_Drop_f(), Cmd_Give_f(), Cmd_Say_f(), Cmd_Use_f(), and CTFTeam_f().
argv
char *(* game_import_t::argv)(int n)
Definition at line 175 of file game.h.
Referenced by ClientCommand(), Cmd_Give_f(), Cmd_Say_f(), Cmd_Wave_f(), CTFAdmin(), CTFBoot(), CTFGhost(), CTFWarp(), ServerCommand(), SVCmd_AddIP_f(), and SVCmd_RemoveIP_f().
BoxEdicts
int(* game_import_t::BoxEdicts)(vec3_t mins, vec3_t maxs, edict_t **list, int maxcount, int areatype)
Definition at line 147 of file game.h.
Referenced by G_TouchSolids(), and G_TouchTriggers().
bprintf
void(* game_import_t::bprintf)(int printlevel, char *fmt,...)
Definition at line 112 of file game.h.
Referenced by BecomeExplosion1(), CheckDMRules(), ClientBegin(), ClientBeginDeathmatch(), ClientDisconnect(), ClientObituary(), CTFAdmin(), CTFAdmin_MatchSet(), CTFAdmin_Reset(), CTFAdmin_SettingsApply(), CTFBeginElection(), CTFCheckRules(), CTFDeadDropFlag(), CTFDropFlagThink(), CTFEndMatch(), CTFFragBonuses(), CTFGhost(), CTFJoinTeam(), CTFNotReady(), CTFPickup_Flag(), CTFReady(), CTFTeam_f(), CTFVoteNo(), CTFVoteYes(), CTFWarp(), CTFWinElection(), spectator_respawn(), and use_target_changelevel().
centerprintf
void(* game_import_t::centerprintf)(edict_t *ent, char *fmt,...)
Definition at line 115 of file game.h.
Referenced by CTFHasTech(), CTFJoinTeam(), CTFStartMatch(), door_touch(), G_UseTargets(), GetChaseTarget(), trigger_counter_use(), and trigger_key_use().
configstring
void(* game_import_t::configstring)(int num, char *string)
Definition at line 123 of file game.h.
Referenced by ClientDisconnect(), ClientUserinfoChanged(), CTFAssignSkin(), CTFCheckRules(), light_use(), SetItemNames(), SP_light(), SP_worldspawn(), target_lightramp_think(), and use_target_goal().
cprintf
void(* game_import_t::cprintf)(edict_t *ent, int printlevel, char *fmt,...)
Definition at line 114 of file game.h.
Referenced by actor_pain(), CheckFlood(), Cmd_Drop_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_InvDrop_f(), Cmd_InvUse_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_PlayerList_f(), Cmd_Players_f(), Cmd_Say_f(), Cmd_Use_f(), Cmd_Wave_f(), CTFAdmin(), CTFAssignGhost(), CTFBeginElection(), CTFBoot(), CTFDrop_Flag(), CTFFragBonuses(), CTFGhost(), CTFID_f(), CTFNotReady(), CTFPickup_Flag(), CTFPlayerList(), CTFReady(), CTFSay_Team(), CTFStats(), CTFTeam_f(), CTFVoteNo(), CTFVoteYes(), CTFWarp(), CTFWinElection(), Drop_Ammo(), Drop_Weapon(), ServerCommand(), spectator_respawn(), StringToFilter(), SVCmd_AddIP_f(), SVCmd_ListIP_f(), SVCmd_RemoveIP_f(), Svcmd_Test_f(), SVCmd_WriteIP_f(), target_actor_touch(), Use_PowerArmor(), and Use_Weapon().
cvar
cvar_t *(* game_import_t::cvar)(char *var_name, char *value, int flags)
Definition at line 169 of file game.h.
Referenced by CTFInit(), InitGame(), and SVCmd_WriteIP_f().
cvar_forceset
cvar_t *(* game_import_t::cvar_forceset)(char *var_name, char *value)
Definition at line 171 of file game.h.
Referenced by SpawnEntities().
cvar_set
cvar_t *(* game_import_t::cvar_set)(char *var_name, char *value)
Definition at line 170 of file game.h.
Referenced by CheckNeedPass(), CTFAdmin_MatchMode(), CTFAdmin_Reset(), CTFAdmin_SettingsApply(), CTFCheckRules(), CTFWinElection(), InitGame(), and SP_worldspawn().
DebugGraph
void(* game_import_t::DebugGraph)(float value, int color)
Definition at line 182 of file game.h.
dprintf
void(* game_import_t::dprintf)(char *fmt,...)
Definition at line 113 of file game.h.
Referenced by actor_use(), ClientConnect(), Com_Printf(), CTFFlagSetup(), droptofloor(), ED_CallSpawn(), ED_ParseField(), flymonster_start_go(), FoundTarget(), func_train_find(), G_FindTeams(), G_PickTarget(), G_UseTargets(), InitGame(), monster_start(), monster_start_go(), old_teleporter_touch(), PMenu_Do_Update(), PMenu_Next(), PMenu_Open(), PMenu_Prev(), PMenu_Select(), PMenu_Update(), point_combat_touch(), ShutdownGame(), SP_func_clock(), SP_func_door_rotating(), SP_func_timer(), SP_func_train(), SP_func_wall(), SP_misc_actor(), SP_misc_strogg_ship(), SP_misc_teleporter(), SP_misc_viper(), SP_path_corner(), SP_target_actor(), SP_target_changelevel(), SP_target_earthquake(), SP_target_help(), SP_target_lightramp(), SP_target_speaker(), SP_trigger_gravity(), SP_trigger_key(), SP_trigger_once(), SP_trigger_teleport(), SP_turret_driver(), SP_viewthing(), SpawnEntities(), SpawnItem(), target_laser_start(), target_lightramp_use(), teleporter_touch(), train_next(), trigger_elevator_init(), trigger_elevator_use(), turret_breach_finish_init(), and walkmonster_start_go().
error
void(* game_import_t::error)(char *fmt,...)
Definition at line 125 of file game.h.
Referenced by ED_ParseEdict(), G_RunEntity(), G_Spawn(), PrecacheItem(), ReadField(), ReadGame(), ReadLevel(), SelectSpawnPoint(), SpawnEntities(), SV_Physics_Pusher(), SV_RunThink(), Sys_Error(), WriteField1(), WriteGame(), and WriteLevel().
FreeTags
void(* game_import_t::FreeTags)(int tag)
Definition at line 166 of file game.h.
Referenced by ReadGame(), ReadLevel(), ShutdownGame(), and SpawnEntities().
imageindex
int(* game_import_t::imageindex)(char *name)
Definition at line 130 of file game.h.
Referenced by CTFPrecache(), DeathmatchScoreboardMessage(), G_SetStats(), PrecacheItem(), SetCTFStats(), SP_worldspawn(), and Touch_Item().
inPHS
qboolean(* game_import_t::inPHS)(vec3_t p1, vec3_t p2)
Definition at line 138 of file game.h.
Referenced by FindTarget().
inPVS
qboolean(* game_import_t::inPVS)(vec3_t p1, vec3_t p2)
Definition at line 137 of file game.h.
linkentity
void(* game_import_t::linkentity)(edict_t *ent)
Definition at line 145 of file game.h.
Referenced by actor_dead(), berserk_dead(), boss2_dead(), brain_dead(), brain_duck_down(), brain_duck_up(), chick_dead(), chick_duck_down(), chick_duck_up(), ClientThink(), CopyToBodyQue(), CTFFireGrapple(), CTFFlagSetup(), CTFGrapplePull(), CTFObserver(), CTFResetFlag(), CTFStartClient(), CTFStartMatch(), DoRespawn(), Drop_Item(), droptofloor(), fire_bfg(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_rocket(), flipper_dead(), floater_dead(), func_explosive_spawn(), func_train_find(), func_wall_use(), gladiator_dead(), gunner_dead(), gunner_duck_down(), gunner_duck_up(), hover_dead(), hurt_use(), infantry_dead(), infantry_duck_down(), infantry_duck_up(), insane_dead(), jorg_dead(), M_droptofloor(), makron_dead(), makron_torso(), medic_dead(), medic_duck_down(), medic_duck_up(), monster_triggered_spawn(), mutant_dead(), old_teleporter_touch(), parasite_dead(), plat_spawn_inside_trigger(), player_die(), PlayerNoise(), PutClientInServer(), ReadLevel(), SetRespawn(), soldier_dead(), soldier_duck_down(), soldier_duck_up(), SP_func_button(), SP_func_conveyor(), SP_func_door(), SP_func_door_rotating(), SP_func_door_secret(), SP_func_explosive(), SP_func_object(), SP_func_plat(), SP_func_rotating(), SP_func_train(), SP_func_wall(), SP_func_water(), SP_light_mine1(), SP_light_mine2(), SP_misc_actor(), SP_misc_banner(), SP_misc_bigviper(), SP_misc_blackhole(), SP_misc_ctf_banner(), SP_misc_ctf_small_banner(), SP_misc_deadsoldier(), SP_misc_easterchick(), SP_misc_easterchick2(), SP_misc_eastertank(), SP_misc_explobox(), SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), SP_misc_insane(), SP_misc_satellite_dish(), SP_misc_strogg_ship(), SP_misc_teleporter(), SP_misc_teleporter_dest(), SP_misc_viper(), SP_misc_viper_bomb(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_commander_body(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier_x(), SP_monster_supertank(), SP_monster_tank(), SP_path_corner(), SP_point_combat(), SP_target_actor(), SP_target_character(), SP_target_speaker(), SP_trigger_hurt(), SP_trigger_multiple(), SP_trigger_push(), SP_trigger_teleport(), SP_turret_base(), SP_turret_breach(), SP_turret_driver(), SP_viewthing(), SpawnTech(), supertank_dead(), SV_movestep(), SV_Physics_Noclip(), SV_Physics_Step(), SV_Physics_Toss(), SV_Push(), SV_PushEntity(), SV_StepDirection(), tank_dead(), target_laser_start(), teleporter_touch(), Think_SpawnDoorTrigger(), ThrowClientHead(), ThrowDebris(), ThrowGib(), ThrowHead(), train_next(), trigger_enable(), UpdateChaseCam(), Use_Item(), and use_target_spawner().
modelindex
int(* game_import_t::modelindex)(char *name)
Definition at line 128 of file game.h.
Referenced by bfg_touch(), ChangeWeapon(), CTFEffects(), CTFFireGrapple(), fire_bfg(), fire_blaster(), fire_grenade(), fire_grenade2(), fire_rocket(), makron_torso(), MakronPrecache(), PrecacheItem(), PutClientInServer(), SP_func_explosive(), SP_light_mine1(), SP_light_mine2(), SP_misc_actor(), SP_misc_banner(), SP_misc_bigviper(), SP_misc_blackhole(), SP_misc_ctf_banner(), SP_misc_ctf_small_banner(), SP_misc_deadsoldier(), SP_misc_easterchick(), SP_misc_easterchick2(), SP_misc_eastertank(), SP_misc_explobox(), SP_misc_insane(), SP_misc_satellite_dish(), SP_misc_strogg_ship(), SP_misc_viper(), SP_misc_viper_bomb(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_commander_body(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_makron(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier_light(), SP_monster_soldier_x(), SP_monster_supertank(), SP_monster_tank(), SP_turret_driver(), SP_viewthing(), SP_worldspawn(), and SpawnItem().
multicast
void(* game_import_t::multicast)(vec3_t origin, multicast_t to)
Definition at line 151 of file game.h.
Referenced by BecomeExplosion1(), BecomeExplosion2(), bfg_explode(), bfg_think(), bfg_touch(), Blaster_Fire(), blaster_touch(), BossExplode(), Chaingun_Fire(), ClientBegin(), ClientBeginDeathmatch(), ClientDisconnect(), CTFGrappleDrawCable(), CTFGrappleFire(), CTFGrappleTouch(), fire_lead(), fire_rail(), floater_zap(), Grenade_Explode(), Machinegun_Fire(), medic_cable_attack(), monster_fire_bfg(), monster_fire_blaster(), monster_fire_bullet(), monster_fire_grenade(), monster_fire_railgun(), monster_fire_rocket(), monster_fire_shotgun(), parasite_drain_attack(), rocket_touch(), SpawnDamage(), spectator_respawn(), target_explosion_explode(), target_laser_think(), Use_Boss3(), use_target_splash(), Use_Target_Tent(), weapon_bfg_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
Pmove
void(* game_import_t::Pmove)(pmove_t *pmove)
Definition at line 148 of file game.h.
Referenced by ClientThink().
pointcontents
int(* game_import_t::pointcontents)(vec3_t point)
Definition at line 136 of file game.h.
Referenced by ClientThink(), fire_lead(), M_CatagorizePosition(), M_CheckBottom(), SV_CalcBlend(), SV_movestep(), and SV_Physics_Toss().
positioned_sound
void(* game_import_t::positioned_sound)(vec3_t origin, edict_t *ent, int channel, int soundinedex, float volume, float attenuation, float timeofs)
Definition at line 117 of file game.h.
Referenced by CTFAdmin_MatchSet(), CTFCheckRules(), CTFReady(), SV_Physics_Toss(), target_earthquake_think(), turret_breach_fire(), and Use_Target_Speaker().
SetAreaPortalState
void(* game_import_t::SetAreaPortalState)(int portalnum, qboolean open)
Definition at line 139 of file game.h.
Referenced by door_use_areaportals(), and Use_Areaportal().
setmodel
void(* game_import_t::setmodel)(edict_t *ent, char *name)
Definition at line 132 of file game.h.
Referenced by CTFFlagSetup(), Drop_Item(), droptofloor(), InitTrigger(), SP_func_button(), SP_func_conveyor(), SP_func_door(), SP_func_door_rotating(), SP_func_door_secret(), SP_func_explosive(), SP_func_killbox(), SP_func_object(), SP_func_plat(), SP_func_rotating(), SP_func_train(), SP_func_wall(), SP_func_water(), SP_misc_gib_arm(), SP_misc_gib_head(), SP_misc_gib_leg(), SP_misc_teleporter(), SP_misc_teleporter_dest(), SP_target_character(), SP_trigger_multiple(), SP_trigger_teleport(), SP_turret_base(), SP_turret_breach(), SpawnTech(), ThrowClientHead(), ThrowDebris(), ThrowGib(), and ThrowHead().
sound
void(* game_import_t::sound)(edict_t *ent, int channel, int soundindex, float volume, float attenuation, float timeofs)
Definition at line 116 of file game.h.
Referenced by berserk_die(), berserk_fidget(), berserk_pain(), berserk_search(), berserk_sight(), berserk_swing(), bfg_touch(), body_die(), boss2_die(), boss2_pain(), boss2_search(), brain_chest_open(), brain_die(), brain_hit_left(), brain_hit_right(), brain_idle(), brain_pain(), brain_search(), brain_sight(), brain_swing_left(), brain_swing_right(), brain_tentacle_attack(), button_fire(), Chaingun_Fire(), chick_die(), chick_pain(), Chick_PreAttack1(), chick_sight(), ChickMoan(), ChickReload(), ChickSlash(), ClientThink(), commander_body_think(), commander_body_use(), CTFApplyHasteSound(), CTFApplyRegeneration(), CTFApplyResistance(), CTFApplyStrengthSound(), CTFGrappleFire(), CTFGrapplePull(), CTFGrappleTouch(), CTFPickup_Flag(), CTFResetGrapple(), door_go_down(), door_go_up(), door_hit_bottom(), door_hit_top(), door_touch(), fire_grenade2(), flipper_die(), flipper_pain(), flipper_preattack(), flipper_sight(), floater_die(), floater_idle(), floater_pain(), floater_sight(), floater_wham(), floater_zap(), flyer_die(), flyer_idle(), flyer_pain(), flyer_pop_blades(), flyer_sight(), flyer_slash_left(), flyer_slash_right(), G_SetClientSound(), G_SetStats(), G_UseTargets(), GaldiatorMelee(), gib_touch(), gladiator_attack(), gladiator_cleaver_swing(), gladiator_die(), gladiator_idle(), gladiator_pain(), gladiator_search(), gladiator_sight(), Grenade_Touch(), gunner_die(), gunner_idlesound(), gunner_opengun(), gunner_pain(), gunner_search(), gunner_sight(), hover_die(), hover_pain(), hover_search(), hover_sight(), hurt_touch(), infantry_cock_gun(), infantry_die(), infantry_fidget(), infantry_pain(), infantry_sight(), infantry_smack(), infantry_swing(), insane_die(), insane_fist(), insane_moan(), insane_pain(), insane_scream(), insane_shake(), jorg_attack(), jorg_death_hit(), jorg_die(), jorg_idle(), jorg_pain(), jorg_search(), jorg_step_left(), jorg_step_right(), jorgBFG(), M_WorldEffects(), Machinegun_Fire(), makron_brainsplorch(), makron_die(), makron_hit(), makron_pain(), makron_popup(), makron_prerailgun(), makron_step_left(), makron_step_right(), makron_taunt(), makronBFG(), medic_cable_attack(), medic_die(), medic_hook_launch(), medic_hook_retract(), medic_idle(), medic_pain(), medic_search(), medic_sight(), misc_deadsoldier_die(), mutant_check_landing(), mutant_die(), mutant_hit_left(), mutant_hit_right(), mutant_idle(), mutant_jump_takeoff(), mutant_pain(), mutant_search(), mutant_sight(), mutant_step(), mutant_swing(), P_DamageFeedback(), P_WorldEffects(), parasite_die(), parasite_drain_attack(), parasite_launch(), parasite_pain(), parasite_reel_in(), parasite_scratch(), parasite_search(), parasite_sight(), parasite_tap(), plat_go_down(), plat_go_up(), plat_hit_bottom(), plat_hit_top(), player_die(), soldier_cock(), soldier_die(), soldier_idle(), soldier_pain(), soldier_sight(), supertank_die(), supertank_pain(), supertank_search(), SV_CalcBlend(), SV_Physics_Step(), T_Damage(), tank_die(), tank_footstep(), tank_idle(), tank_pain(), tank_sight(), tank_thud(), tank_windup(), TankStrike(), target_actor_touch(), Touch_Item(), train_next(), train_wait(), TreadSound(), trigger_counter_use(), trigger_key_use(), trigger_push_touch(), Use_Invulnerability(), Use_PowerArmor(), Use_Quad(), use_target_blaster(), use_target_goal(), use_target_secret(), Weapon_Generic(), Weapon_Generic2(), Weapon_Grenade(), and Weapon_HyperBlaster_Fire().
soundindex
int(* game_import_t::soundindex)(char *name)
Definition at line 129 of file game.h.
Referenced by berserk_die(), bfg_touch(), body_die(), boss2_die(), brain_die(), Chaingun_Fire(), chick_die(), ClientThink(), commander_body_think(), commander_body_use(), CTFAdmin_MatchSet(), CTFApplyHasteSound(), CTFApplyRegeneration(), CTFApplyResistance(), CTFApplyStrengthSound(), CTFCheckRules(), CTFGrappleFire(), CTFGrapplePull(), CTFGrappleTouch(), CTFPickup_Flag(), CTFReady(), CTFResetGrapple(), door_touch(), fire_bfg(), fire_blaster(), fire_grenade2(), fire_rocket(), flipper_die(), G_SetClientSound(), G_SetStats(), G_UseTargets(), gib_touch(), gladiator_die(), Grenade_Touch(), gunner_die(), hover_die(), infantry_die(), insane_die(), insane_pain(), jorg_attack(), M_FliesOn(), M_WorldEffects(), Machinegun_Fire(), makron_die(), makron_torso(), MakronPrecache(), medic_die(), misc_deadsoldier_die(), mutant_die(), P_DamageFeedback(), P_WorldEffects(), parasite_die(), player_die(), PrecacheItem(), soldier_die(), SP_func_button(), SP_func_door(), SP_func_door_rotating(), SP_func_door_secret(), SP_func_plat(), SP_func_train(), SP_func_water(), SP_item_health(), SP_item_health_large(), SP_item_health_mega(), SP_item_health_small(), SP_misc_insane(), SP_misc_teleporter(), SP_monster_berserk(), SP_monster_boss2(), SP_monster_boss3_stand(), SP_monster_brain(), SP_monster_chick(), SP_monster_commander_body(), SP_monster_flipper(), SP_monster_floater(), SP_monster_flyer(), SP_monster_gladiator(), SP_monster_gunner(), SP_monster_hover(), SP_monster_infantry(), SP_monster_jorg(), SP_monster_medic(), SP_monster_mutant(), SP_monster_parasite(), SP_monster_soldier(), SP_monster_soldier_light(), SP_monster_soldier_ss(), SP_monster_soldier_x(), SP_monster_supertank(), SP_monster_tank(), SP_target_blaster(), SP_target_earthquake(), SP_target_goal(), SP_target_secret(), SP_target_speaker(), SP_trigger_hurt(), SP_trigger_key(), SP_trigger_multiple(), SP_trigger_push(), SP_trigger_teleport(), SP_worldspawn(), SV_CalcBlend(), SV_Physics_Step(), SV_Physics_Toss(), T_Damage(), tank_die(), target_actor_touch(), Touch_Item(), trigger_counter_use(), trigger_key_use(), turret_breach_fire(), Use_Invulnerability(), Use_PowerArmor(), Use_Quad(), Weapon_Generic(), Weapon_Generic2(), Weapon_Grenade(), and Weapon_HyperBlaster_Fire().
TagFree
void(* game_import_t::TagFree)(void *block)
Definition at line 165 of file game.h.
TagMalloc
void *(* game_import_t::TagMalloc)(int size, int tag)
Definition at line 164 of file game.h.
Referenced by ED_NewString(), G_CopyString(), InitGame(), ReadField(), ReadGame(), and SP_func_clock().
trace
trace_t(* game_import_t::trace)(vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, edict_t *passent, int contentmask)
Definition at line 135 of file game.h.
Referenced by ai_run(), bfg_think(), Boss2_CheckAttack(), CanDamage(), check_dodge(), CTFFireGrapple(), CTFFlagSetup(), CTFGrappleDrawCable(), CTFSetIDView(), Drop_Item(), droptofloor(), fire_blaster(), fire_hit(), fire_lead(), fire_rail(), Jorg_CheckAttack(), KillBox(), loc_CanSee(), M_CheckAttack(), M_CheckBottom(), M_CheckGround(), M_droptofloor(), Makron_CheckAttack(), medic_cable_attack(), parasite_drain_attack(), PM_trace(), SV_FlyMove(), SV_movestep(), SV_PushEntity(), SV_TestEntityPosition(), target_laser_think(), UpdateChaseCam(), and visible().
unicast
void(* game_import_t::unicast)(edict_t *ent, qboolean reliable)
Definition at line 152 of file game.h.
Referenced by ClientEndServerFrame(), ClientThink(), Cmd_Inven_f(), DeathmatchScoreboard(), HelpComputer(), MoveClientToIntermission(), PMenu_Open(), PMenu_Update(), spectator_respawn(), stuffcmd(), and UpdateChaseCam().
unlinkentity
void(* game_import_t::unlinkentity)(edict_t *ent)
Definition at line 146 of file game.h.
Referenced by ClientDisconnect(), CopyToBodyQue(), G_FreeEdict(), old_teleporter_touch(), teleporter_touch(), and use_target_spawner().
WriteAngle
void(* game_import_t::WriteAngle)(float f)
Definition at line 161 of file game.h.
WriteByte
void(* game_import_t::WriteByte)(int c)
Definition at line 154 of file game.h.
Referenced by BecomeExplosion1(), BecomeExplosion2(), bfg_explode(), bfg_think(), bfg_touch(), Blaster_Fire(), blaster_touch(), BossExplode(), Chaingun_Fire(), ClientBegin(), ClientBeginDeathmatch(), ClientDisconnect(), Cmd_Inven_f(), CTFGrappleDrawCable(), CTFGrappleFire(), CTFGrappleTouch(), CTFScoreboardMessage(), DeathmatchScoreboardMessage(), fire_lead(), fire_rail(), floater_zap(), Grenade_Explode(), HelpComputer(), Machinegun_Fire(), medic_cable_attack(), monster_fire_bfg(), monster_fire_blaster(), monster_fire_bullet(), monster_fire_grenade(), monster_fire_railgun(), monster_fire_rocket(), monster_fire_shotgun(), parasite_drain_attack(), PMenu_Do_Update(), rocket_touch(), SpawnDamage(), spectator_respawn(), stuffcmd(), target_explosion_explode(), target_laser_think(), UpdateChaseCam(), Use_Boss3(), use_target_splash(), Use_Target_Tent(), weapon_bfg_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
WriteChar
void(* game_import_t::WriteChar)(int c)
Definition at line 153 of file game.h.
WriteDir
void(* game_import_t::WriteDir)(vec3_t pos)
Definition at line 160 of file game.h.
Referenced by bfg_think(), blaster_touch(), CTFGrappleTouch(), fire_lead(), floater_zap(), SpawnDamage(), target_laser_think(), and use_target_splash().
WriteFloat
void(* game_import_t::WriteFloat)(float f)
Definition at line 157 of file game.h.
WriteLong
void(* game_import_t::WriteLong)(int c)
Definition at line 156 of file game.h.
WritePosition
void(* game_import_t::WritePosition)(vec3_t pos)
Definition at line 159 of file game.h.
Referenced by BecomeExplosion1(), BecomeExplosion2(), bfg_explode(), bfg_think(), bfg_touch(), blaster_touch(), BossExplode(), CTFGrappleDrawCable(), CTFGrappleTouch(), fire_lead(), fire_rail(), floater_zap(), Grenade_Explode(), medic_cable_attack(), parasite_drain_attack(), rocket_touch(), SpawnDamage(), target_explosion_explode(), target_laser_think(), Use_Boss3(), use_target_splash(), and Use_Target_Tent().
WriteShort
void(* game_import_t::WriteShort)(int c)
Definition at line 155 of file game.h.
Referenced by Blaster_Fire(), Chaingun_Fire(), ClientBegin(), ClientBeginDeathmatch(), ClientDisconnect(), Cmd_Inven_f(), CTFGrappleDrawCable(), CTFGrappleFire(), Machinegun_Fire(), medic_cable_attack(), monster_fire_bfg(), monster_fire_blaster(), monster_fire_bullet(), monster_fire_grenade(), monster_fire_railgun(), monster_fire_rocket(), monster_fire_shotgun(), parasite_drain_attack(), spectator_respawn(), weapon_bfg_fire(), weapon_grenadelauncher_fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_shotgun_fire(), and weapon_supershotgun_fire().
WriteString
void(* game_import_t::WriteString)(char *s)
Definition at line 158 of file game.h.
Referenced by CTFScoreboardMessage(), DeathmatchScoreboardMessage(), HelpComputer(), PMenu_Do_Update(), spectator_respawn(), stuffcmd(), and UpdateChaseCam().
The documentation for this struct was generated from the following file:
C:/entry/syn/github/vq2/ctf/game.h