vkQuake2 doxygen: C:/entry/dev/vq2/src/client/cl_inv.c File Reference
cl_inv.c File Reference
#include "client.h"
Macros
#define DISPLAY_ITEMS 17
Functions
void CL_ParseInventory (void)
void Inv_DrawString (int x, int y, char *string)
void SetStringHighBit (char *s)
void CL_DrawInventory (void)
Variables
cvar_t * vid_hudscale
Macro Definition Documentation
DISPLAY_ITEMS
#define DISPLAY_ITEMS 17
Definition at line 66 of file cl_inv.c.
Function Documentation
CL_DrawInventory()
void CL_DrawInventory (void)
Definition at line 68 of file cl_inv.c.
 {
     int     i, j;
     int     num, selected_num, item;
     int     index[MAX_ITEMS];
     char    string[1024];
     int     x, y;
     char    binding[1024];
     char    *bind;
     int     selected;
     int     top;
     selected = cl.frame.playerstate.stats[STAT_SELECTED_ITEM];
     num = 0;
     selected_num = 0;
     for (i=0 ; i<MAX_ITEMS ; i++)
     {
         if (i==selected)
             selected_num = num;
         if (cl.inventory[i])
         {
             index[num] = i;
             num++;
         }
     }
     // determine scroll point
     top = selected_num - DISPLAY_ITEMS/2;
     if (num - top < DISPLAY_ITEMS)
         top = num - DISPLAY_ITEMS;
     if (top < 0)
         top = 0;
     x = (viddef.width-256 * vid_hudscale->value)/2;
     y = (viddef.height-240 * vid_hudscale->value)/2;
     // repaint everything next frame
     SCR_DirtyScreen ();
     re.DrawPic (x, y + 8 * vid_hudscale->value, "inventory");
     y += 24 * vid_hudscale->value;
     x += 24 * vid_hudscale->value;
     Inv_DrawString (x, y, "hotkey ### item");
     Inv_DrawString (x, y+8*vid_hudscale->value, "------ --- ----");
     y += 16 * vid_hudscale->value;
     for (i=top ; i<num && i < top+DISPLAY_ITEMS ; i++)
     {
         item = index[i];
         // search for a binding
         Com_sprintf (binding, sizeof(binding), "use %s", cl.configstrings[CS_ITEMS+item]);
         bind = "";
         for (j=0 ; j<256 ; j++)
             if (keybindings[j] && !Q_stricmp (keybindings[j], binding))
             {
                 bind = Key_KeynumToString(j);
                 break;
             }
         Com_sprintf (string, sizeof(string), "%6s %3i %s", bind, cl.inventory[item],
             cl.configstrings[CS_ITEMS+item] );
         if (item != selected)
             SetStringHighBit (string);
         else    // draw a blinky cursor by the selected item
         {
             if ( (int)(cls.realtime*10) & 1)
                 re.DrawChar (x - 8 * vid_hudscale->value, y * vid_hudscale->value, 15);
         }
         Inv_DrawString (x, y, string);
         y += 8 * vid_hudscale->value;
     }
 }
Referenced by SCR_UpdateScreen().
CL_ParseInventory()
void CL_ParseInventory (void)
Definition at line 31 of file cl_inv.c.
 {
     int     i;
     for (i=0 ; i<MAX_ITEMS ; i++)
         cl.inventory[i] = MSG_ReadShort (&net_message);
 }
Referenced by CL_ParseServerMessage().
Inv_DrawString()
void Inv_DrawString (int x, int y, char * string)
Definition at line 45 of file cl_inv.c.
 {
     while (*string)
     {
         re.DrawChar (x, y, *string);
         x+=8 * vid_hudscale->value;
         string++;
     }
 }
Referenced by CL_DrawInventory().
SetStringHighBit()
void SetStringHighBit (char * s)
Definition at line 55 of file cl_inv.c.
 {
     while (*s)
         *s++ |= 128;
 }
Referenced by CL_DrawInventory().
Variable Documentation
vid_hudscale
cvar_t* vid_hudscale
Definition at line 48 of file vid_dll.c.
Referenced by CL_DrawInventory(), and Inv_DrawString().