vkQuake2 doxygen: C:/entry/dev/vq2/src/ref_gl/gl_local.h File Reference
gl_local.h File Reference
#include <windows.h>
#include <stdio.h>
#include <GL/gl.h>
#include <GL/glu.h>
#include <math.h>
#include "../client/ref.h"
#include "qgl.h"
#include "gl_model.h"
Classes
struct viddef_t
struct image_s
struct glvert_t
struct glconfig_t
struct glstate_t
Macros
#define GL_COLOR_INDEX8_EXT GL_COLOR_INDEX
#define REF_VERSION "GL 0.01"
#define PITCH 0
#define YAW 1
#define ROLL 2
#define __VIDDEF_T
#define TEXNUM_LIGHTMAPS 1024
#define TEXNUM_SCRAPS 1152
#define TEXNUM_IMAGES 1153
#define MAX_GLTEXTURES 1024
#define MAX_LBM_HEIGHT 480
#define BACKFACE_EPSILON 0.01
#define GL_RENDERER_VOODOO 0x00000001
#define GL_RENDERER_VOODOO2 0x00000002
#define GL_RENDERER_VOODOO_RUSH 0x00000004
#define GL_RENDERER_BANSHEE 0x00000008
#define GL_RENDERER_3DFX 0x0000000F
#define GL_RENDERER_PCX1 0x00000010
#define GL_RENDERER_PCX2 0x00000020
#define GL_RENDERER_PMX 0x00000040
#define GL_RENDERER_POWERVR 0x00000070
#define GL_RENDERER_PERMEDIA2 0x00000100
#define GL_RENDERER_GLINT_MX 0x00000200
#define GL_RENDERER_GLINT_TX 0x00000400
#define GL_RENDERER_3DLABS_MISC 0x00000800
#define GL_RENDERER_3DLABS 0x00000F00
#define GL_RENDERER_REALIZM 0x00001000
#define GL_RENDERER_REALIZM2 0x00002000
#define GL_RENDERER_INTERGRAPH 0x00003000
#define GL_RENDERER_3DPRO 0x00004000
#define GL_RENDERER_REAL3D 0x00008000
#define GL_RENDERER_RIVA128 0x00010000
#define GL_RENDERER_DYPIC 0x00020000
#define GL_RENDERER_V1000 0x00040000
#define GL_RENDERER_V2100 0x00080000
#define GL_RENDERER_V2200 0x00100000
#define GL_RENDERER_RENDITION 0x001C0000
#define GL_RENDERER_O2 0x00100000
#define GL_RENDERER_IMPACT 0x00200000
#define GL_RENDERER_RE 0x00400000
#define GL_RENDERER_IR 0x00800000
#define GL_RENDERER_SGI 0x00F00000
#define GL_RENDERER_MCD 0x01000000
#define GL_RENDERER_OTHER 0x80000000
Typedefs
typedef struct image_s image_t
Enumerations
enum imagetype_t {
it_skin, it_sprite, it_wall, it_pic,
it_sky, it_skin, it_sprite, it_wall,
it_pic, it_sky, it_skin, it_sprite,
it_wall, it_pic, it_sky
}
enum rserr_t {
rserr_ok, rserr_invalid_fullscreen, rserr_invalid_mode, rserr_unknown,
rserr_ok, rserr_invalid_fullscreen, rserr_invalid_mode, rserr_unknown,
rserr_ok, rserr_invalid_fullscreen, rserr_invalid_mode, rserr_unknown
}
Functions
void GL_BeginRendering (int *x, int *y, int *width, int *height)
void GL_EndRendering (void)
void GL_SetDefaultState (void)
void GL_UpdateSwapInterval (void)
void R_TranslatePlayerSkin (int playernum)
void GL_Bind (int texnum)
void GL_MBind (GLenum target, int texnum)
void GL_TexEnv (GLenum value)
void GL_EnableMultitexture (qboolean enable)
void GL_SelectTexture (GLenum)
void R_LightPoint (vec3_t p, vec3_t color)
void R_PushDlights (void)
void V_AddBlend (float r, float g, float b, float a, float *v_blend)
qboolean R_Init (void *hinstance, void *hWnd)
void R_Shutdown (void)
void R_RenderView (refdef_t *fd)
void GL_ScreenShot_f (void)
void R_DrawAliasModel (entity_t *e)
void R_DrawBrushModel (entity_t *e)
void R_DrawSpriteModel (entity_t *e)
void R_DrawBeam (entity_t *e)
void R_DrawWorld (void)
void R_RenderDlights (void)
void R_DrawAlphaSurfaces (void)
void R_RenderBrushPoly (msurface_t *fa)
void R_InitParticleTexture (void)
void Draw_InitLocal (void)
void GL_SubdivideSurface (msurface_t *fa)
qboolean R_CullBox (vec3_t mins, vec3_t maxs)
void R_RotateForEntity (entity_t *e)
void R_MarkLeaves (void)
glpoly_t * WaterWarpPolyVerts (glpoly_t *p)
void EmitWaterPolys (msurface_t *fa)
void R_AddSkySurface (msurface_t *fa)
void R_ClearSkyBox (void)
void R_DrawSkyBox (void)
void R_MarkLights (dlight_t *light, int bit, mnode_t *node)
void COM_StripExtension (char *in, char *out)
void Draw_GetPicSize (int *w, int *h, char *name)
void Draw_Pic (int x, int y, char *name)
void Draw_StretchPic (int x, int y, int w, int h, char *name)
void Draw_Char (int x, int y, int c)
void Draw_TileClear (int x, int y, int w, int h, char *name)
void Draw_Fill (int x, int y, int w, int h, int c)
void Draw_FadeScreen (void)
void Draw_StretchRaw (int x, int y, int w, int h, int cols, int rows, byte *data)
void R_BeginFrame (float camera_separation)
void R_SwapBuffers (int)
void R_SetPalette (const unsigned char *palette)
int Draw_GetPalette (void)
void GL_ResampleTexture (unsigned *in, int inwidth, int inheight, unsigned *out, int outwidth, int outheight)
struct image_s * R_RegisterSkin (char *name)
void LoadPCX (char *filename, byte **pic, byte **palette, int *width, int *height)
image_t * GL_LoadPic (char *name, byte *pic, int width, int height, imagetype_t type, int bits)
image_t * GL_FindImage (char *name, imagetype_t type)
void GL_TextureMode (char *string)
void GL_ImageList_f (void)
void GL_SetTexturePalette (unsigned palette[256])
void GL_InitImages (void)
void GL_ShutdownImages (void)
void GL_FreeUnusedImages (void)
void GL_TextureAlphaMode (char *string)
void GL_TextureSolidMode (char *string)
void GL_DrawParticles (int n, const particle_t particles[], const unsigned colortable[768])
void GLimp_BeginFrame (float camera_separation)
void GLimp_EndFrame (void)
qboolean GLimp_Init (void *hinstance, void *hWnd)
void GLimp_Shutdown (void)
rserr_t GLimp_SetMode (int *pwidth, int *pheight, int mode, qboolean fullscreen)
void GLimp_AppActivate (qboolean active)
void GLimp_EnableLogging (qboolean enable)
void GLimp_LogNewFrame (void)
Variables
viddef_t vid
float gldepthmin
float gldepthmax
image_t gltextures [MAX_GLTEXTURES]
int numgltextures
image_t * r_notexture
image_t * r_particletexture
entity_t * currententity
model_t * currentmodel
int r_visframecount
int r_framecount
cplane_t frustum [4]
int c_brush_polys
int c_alias_polys
int gl_filter_min
int gl_filter_max
vec3_t vup
vec3_t vpn
vec3_t vright
vec3_t r_origin
refdef_t r_newrefdef
int r_viewcluster
int r_viewcluster2
int r_oldviewcluster
int r_oldviewcluster2
cvar_t * r_norefresh
cvar_t * r_lefthand
cvar_t * r_drawentities
cvar_t * r_drawworld
cvar_t * r_speeds
cvar_t * r_fullbright
cvar_t * r_novis
cvar_t * r_nocull
cvar_t * r_lerpmodels
cvar_t * r_lightlevel
cvar_t * gl_vertex_arrays
cvar_t * gl_ext_swapinterval
cvar_t * gl_ext_palettedtexture
cvar_t * gl_ext_multitexture
cvar_t * gl_ext_pointparameters
cvar_t * gl_ext_compiled_vertex_array
cvar_t * gl_particle_min_size
cvar_t * gl_particle_max_size
cvar_t * gl_particle_size
cvar_t * gl_particle_att_a
cvar_t * gl_particle_att_b
cvar_t * gl_particle_att_c
cvar_t * gl_nosubimage
cvar_t * gl_bitdepth
cvar_t * gl_mode
cvar_t * gl_log
cvar_t * gl_lightmap
cvar_t * gl_shadows
cvar_t * gl_dynamic
cvar_t * gl_monolightmap
cvar_t * gl_nobind
cvar_t * gl_round_down
cvar_t * gl_picmip
cvar_t * gl_skymip
cvar_t * gl_showtris
cvar_t * gl_finish
cvar_t * gl_ztrick
cvar_t * gl_clear
cvar_t * gl_cull
cvar_t * gl_poly
cvar_t * gl_texsort
cvar_t * gl_polyblend
cvar_t * gl_flashblend
cvar_t * gl_lightmaptype
cvar_t * gl_modulate
cvar_t * gl_playermip
cvar_t * gl_drawbuffer
cvar_t * gl_3dlabs_broken
cvar_t * gl_driver
cvar_t * gl_swapinterval
cvar_t * gl_texturemode
cvar_t * gl_texturealphamode
cvar_t * gl_texturesolidmode
cvar_t * gl_saturatelighting
cvar_t * gl_lockpvs
cvar_t * vid_fullscreen
cvar_t * vid_gamma
cvar_t * intensity
int gl_lightmap_format
int gl_solid_format
int gl_alpha_format
int gl_tex_solid_format
int gl_tex_alpha_format
int c_visible_lightmaps
int c_visible_textures
float r_world_matrix [16]
model_t * r_worldmodel
unsigned d_8to24table [256]
int registration_sequence
glconfig_t gl_config
glstate_t gl_state
refimport_t ri
Macro Definition Documentation
__VIDDEF_T
#define __VIDDEF_T
Definition at line 55 of file gl_local.h.
BACKFACE_EPSILON
#define BACKFACE_EPSILON 0.01
Definition at line 141 of file gl_local.h.
GL_COLOR_INDEX8_EXT
#define GL_COLOR_INDEX8_EXT GL_COLOR_INDEX
Definition at line 34 of file gl_local.h.
GL_RENDERER_3DFX
#define GL_RENDERER_3DFX 0x0000000F
Definition at line 360 of file gl_local.h.
GL_RENDERER_3DLABS
#define GL_RENDERER_3DLABS 0x00000F00
Definition at line 371 of file gl_local.h.
GL_RENDERER_3DLABS_MISC
#define GL_RENDERER_3DLABS_MISC 0x00000800
Definition at line 370 of file gl_local.h.
GL_RENDERER_3DPRO
#define GL_RENDERER_3DPRO 0x00004000
Definition at line 377 of file gl_local.h.
GL_RENDERER_BANSHEE
#define GL_RENDERER_BANSHEE 0x00000008
Definition at line 359 of file gl_local.h.
GL_RENDERER_DYPIC
#define GL_RENDERER_DYPIC 0x00020000
Definition at line 380 of file gl_local.h.
GL_RENDERER_GLINT_MX
#define GL_RENDERER_GLINT_MX 0x00000200
Definition at line 368 of file gl_local.h.
GL_RENDERER_GLINT_TX
#define GL_RENDERER_GLINT_TX 0x00000400
Definition at line 369 of file gl_local.h.
GL_RENDERER_IMPACT
#define GL_RENDERER_IMPACT 0x00200000
Definition at line 388 of file gl_local.h.
GL_RENDERER_INTERGRAPH
#define GL_RENDERER_INTERGRAPH 0x00003000
Definition at line 375 of file gl_local.h.
GL_RENDERER_IR
#define GL_RENDERER_IR 0x00800000
Definition at line 390 of file gl_local.h.
GL_RENDERER_MCD
#define GL_RENDERER_MCD 0x01000000
Definition at line 393 of file gl_local.h.
GL_RENDERER_O2
#define GL_RENDERER_O2 0x00100000
Definition at line 387 of file gl_local.h.
GL_RENDERER_OTHER
#define GL_RENDERER_OTHER 0x80000000
Definition at line 394 of file gl_local.h.
GL_RENDERER_PCX1
#define GL_RENDERER_PCX1 0x00000010
Definition at line 362 of file gl_local.h.
GL_RENDERER_PCX2
#define GL_RENDERER_PCX2 0x00000020
Definition at line 363 of file gl_local.h.
GL_RENDERER_PERMEDIA2
#define GL_RENDERER_PERMEDIA2 0x00000100
Definition at line 367 of file gl_local.h.
GL_RENDERER_PMX
#define GL_RENDERER_PMX 0x00000040
Definition at line 364 of file gl_local.h.
GL_RENDERER_POWERVR
#define GL_RENDERER_POWERVR 0x00000070
Definition at line 365 of file gl_local.h.
GL_RENDERER_RE
#define GL_RENDERER_RE 0x00400000
Definition at line 389 of file gl_local.h.
GL_RENDERER_REAL3D
#define GL_RENDERER_REAL3D 0x00008000
Definition at line 378 of file gl_local.h.
GL_RENDERER_REALIZM
#define GL_RENDERER_REALIZM 0x00001000
Definition at line 373 of file gl_local.h.
GL_RENDERER_REALIZM2
#define GL_RENDERER_REALIZM2 0x00002000
Definition at line 374 of file gl_local.h.
GL_RENDERER_RENDITION
#define GL_RENDERER_RENDITION 0x001C0000
Definition at line 385 of file gl_local.h.
GL_RENDERER_RIVA128
#define GL_RENDERER_RIVA128 0x00010000
Definition at line 379 of file gl_local.h.
GL_RENDERER_SGI
#define GL_RENDERER_SGI 0x00F00000
Definition at line 391 of file gl_local.h.
GL_RENDERER_V1000
#define GL_RENDERER_V1000 0x00040000
Definition at line 382 of file gl_local.h.
GL_RENDERER_V2100
#define GL_RENDERER_V2100 0x00080000
Definition at line 383 of file gl_local.h.
GL_RENDERER_V2200
#define GL_RENDERER_V2200 0x00100000
Definition at line 384 of file gl_local.h.
GL_RENDERER_VOODOO
#define GL_RENDERER_VOODOO 0x00000001
Definition at line 356 of file gl_local.h.
GL_RENDERER_VOODOO2
#define GL_RENDERER_VOODOO2 0x00000002
Definition at line 357 of file gl_local.h.
GL_RENDERER_VOODOO_RUSH
#define GL_RENDERER_VOODOO_RUSH 0x00000004
Definition at line 358 of file gl_local.h.
MAX_GLTEXTURES
#define MAX_GLTEXTURES 1024
Definition at line 107 of file gl_local.h.
MAX_LBM_HEIGHT
#define MAX_LBM_HEIGHT 480
Definition at line 139 of file gl_local.h.
PITCH
#define PITCH 0
Definition at line 45 of file gl_local.h.
REF_VERSION
#define REF_VERSION "GL 0.01"
Definition at line 42 of file gl_local.h.
ROLL
#define ROLL 2
Definition at line 51 of file gl_local.h.
TEXNUM_IMAGES
#define TEXNUM_IMAGES 1153
Definition at line 105 of file gl_local.h.
TEXNUM_LIGHTMAPS
#define TEXNUM_LIGHTMAPS 1024
Definition at line 103 of file gl_local.h.
TEXNUM_SCRAPS
#define TEXNUM_SCRAPS 1152
Definition at line 104 of file gl_local.h.
YAW
#define YAW 1
Definition at line 48 of file gl_local.h.
Typedef Documentation
image_t
typedef struct image_s image_t
Enumeration Type Documentation
imagetype_t
enum imagetype_t
Enumerator
it_skin
it_sprite
it_wall
it_pic
it_sky
it_skin
it_sprite
it_wall
it_pic
it_sky
it_skin
it_sprite
it_wall
it_pic
it_sky
Definition at line 78 of file gl_local.h.
 {
     it_skin,
     it_sprite,
     it_wall,
     it_pic,
     it_sky
 } imagetype_t;
rserr_t
enum rserr_t
Enumerator
rserr_ok
rserr_invalid_fullscreen
rserr_invalid_mode
rserr_unknown
rserr_ok
rserr_invalid_fullscreen
rserr_invalid_mode
rserr_unknown
rserr_ok
rserr_invalid_fullscreen
rserr_invalid_mode
rserr_unknown
Definition at line 111 of file gl_local.h.
 {
     rserr_ok,
     rserr_invalid_fullscreen,
     rserr_invalid_mode,
     rserr_unknown
 } rserr_t;
Function Documentation
COM_StripExtension()
void COM_StripExtension (char * in, char * out)
Definition at line 826 of file q_shared.c.
 {
     while (*in && *in != '.')
         *out++ = *in++;
     *out = 0;
 }
Draw_Char()
void Draw_Char (int x, int y, int c)
Definition at line 242 of file r_draw.c.
 {
     byte            *dest;
     byte            *source;
     byte            *src;
     int             drawline;
     int             row, col, f, i, v, skip = 0;
     int             fstep, tbyte, sv;
     num &= 255;
     if (num == 32 || num == 32 + 128)
         return;
     if (y <= -8)
         return;         // totally off screen
     //  if ( ( y + 8 ) >= vid.height )
     if ((y + 8) > vid.height)       // PGM - status text was missing in sw...
         return;
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
 #ifdef PARANOID
     if (y > vid.height - 8 || x < 0 || x > vid.width - 8)
         ri.Sys_Error(ERR_FATAL, "Con_DrawCharacter: (%i, %i)", x, y);
     if (num < 0 || num > 255)
         ri.Sys_Error(ERR_FATAL, "Con_DrawCharacter: char %i", num);
 #endif
     row = num >> 4;
     col = num & 15;
     source = draw_chars->pixels[0] + (row << 10) + (col << 3);
     if (y < 0)
     {   // clipped
         skip = y;
         drawline = 8 * scale->value + y;
         source -= 128 * y;
         y = 0;
     }
     else
         drawline = 8 * scale->value;
     dest = vid.buffer + y*vid.rowbytes + x;
     fstep = 0x8000 / scale->value;
     for (v = 0; v < drawline; v++, dest += vid.rowbytes)
     {
         sv = (skip + v) / scale->value;
         src = source + sv * draw_chars->width;
         f = 0;
         for (i = 0; i < 8 * scale->value; i += 4)
         {
             if ((tbyte = src[f >> 15]) != TRANSPARENT_COLOR)
                 dest[i] = tbyte;
             f += fstep;
             if ((tbyte = src[f >> 15]) != TRANSPARENT_COLOR)
                 dest[i + 1] = tbyte;
             f += fstep;
             if ((tbyte = src[f >> 15]) != TRANSPARENT_COLOR)
                 dest[i + 2] = tbyte;
             f += fstep;
             if ((tbyte = src[f >> 15]) != TRANSPARENT_COLOR)
                 dest[i + 3] = tbyte;
             f += fstep;
         }
     }
 }
Draw_FadeScreen()
void Draw_FadeScreen (void)
Definition at line 620 of file r_draw.c.
 {
     int         x, y;
     byte        *pbuf;
     int t;
     for (y = 0; y < vid.height; y++)
     {
         pbuf = (byte *)(vid.buffer + vid.rowbytes*y);
         t = (y & 1) << 1;
         for (x = 0; x < vid.width; x++)
         {
             if ((x & 3) != t)
                 pbuf[x] = 0;
         }
     }
 }
Draw_Fill()
void Draw_Fill (int x, int y, int w, int h, int c)
Definition at line 586 of file r_draw.c.
 {
     byte            *dest;
     int             u, v;
     if (x + w > vid.width)
         w = vid.width - x;
     if (y + h > vid.height)
         h = vid.height - y;
     if (x < 0)
     {
         w += x;
         x = 0;
     }
     if (y < 0)
     {
         h += y;
         y = 0;
     }
     if (w < 0 || h < 0)
         return;
     dest = vid.buffer + y*vid.rowbytes + x;
     for (v = 0; v < h; v++, dest += vid.rowbytes)
     for (u = 0; u < w; u++)
         dest[u] = c;
 }
Draw_GetPalette()
int Draw_GetPalette (void)
Definition at line 1423 of file r_main.c.
 {
     byte    *out;
     int     i;
     int     r, g, b;
     // get the palette and colormap
     LoadPCX("pics/colormap.pcx", &vid.colormap, &thepalette, NULL, NULL);
     if (!vid.colormap)
         ri.Sys_Error(ERR_FATAL, "Couldn't load pics/colormap.pcx");
     vid.alphamap = vid.colormap + 64 * 256;
     out = (byte *)d_8to24table;
     for (i=0 ; i<256 ; i++, out+=4)
     {
         r = thepalette[i*3+0];
         g = thepalette[i*3+1];
         b = thepalette[i*3+2];
         out[0] = r;
         out[1] = g;
         out[2] = b;
     }
 }
Draw_GetPicSize()
void Draw_GetPicSize (int * w, int * h, char * name)
Definition at line 321 of file r_draw.c.
 {
     image_t *gl;
     gl = Draw_FindPic(pic);
     if (!gl)
     {
         *w = *h = -1;
         return;
     }
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     *w = gl->width*scale->value;
     *h = gl->height*scale->value;
 }
Draw_InitLocal()
void Draw_InitLocal (void)
Definition at line 222 of file r_draw.c.
 {
     draw_chars = Draw_FindPic("conchars");
     // Knightmare- error out instead of crashing if we can't load this
     if (!draw_chars)
         ri.Sys_Error(ERR_FATAL, "Couldn't load pics/conchars.pcx");
     // end Knightmare
 }
Draw_Pic()
void Draw_Pic (int x, int y, char * name)
Definition at line 438 of file r_draw.c.
 {
     image_t         *pic;
     byte            *dest, *source;
     int             v, u;
     int             tbyte;
     int             height;
     pic = Draw_FindPic(name);
     if (!pic)
     {
         ri.Con_Printf(PRINT_ALL, "Can't find pic: %s\n", name);
         return;
     }
     cvar_t *scale = ri.Cvar_Get("hudscale", "1", 0);
     if (scale->value > 1.f)
     {
         Draw_StretchPicImplementation(x, y, pic->width*scale->value, pic->height*scale->value, pic);
         return;
     }
     if ((x < 0) ||
         (x + pic->width > vid.width) ||
         (y + pic->height > vid.height))
         return; //  ri.Sys_Error (ERR_FATAL,"Draw_Pic: bad coordinates");
     height = pic->height;
     source = pic->pixels[0];
     if (y < 0)
     {
         height += y;
         source += pic->width*-y;
         y = 0;
     }
     dest = vid.buffer + y * vid.rowbytes + x;
     if (!pic->transparent)
     {
         for (v = 0; v < height; v++)
         {
             memcpy(dest, source, pic->width);
             dest += vid.rowbytes;
             source += pic->width;
         }
     }
     else
     {
         if (pic->width & 7)
         {   // general
             for (v = 0; v < height; v++)
             {
                 for (u = 0; u < pic->width; u++)
                 if ((tbyte = source[u]) != TRANSPARENT_COLOR)
                     dest[u] = tbyte;
                 dest += vid.rowbytes;
                 source += pic->width;
             }
         }
         else
         {   // unwound
             for (v = 0; v < height; v++)
             {
                 for (u = 0; u < pic->width; u += 8)
                 {
                     if ((tbyte = source[u]) != TRANSPARENT_COLOR)
                         dest[u] = tbyte;
                     if ((tbyte = source[u + 1]) != TRANSPARENT_COLOR)
                         dest[u + 1] = tbyte;
                     if ((tbyte = source[u + 2]) != TRANSPARENT_COLOR)
                         dest[u + 2] = tbyte;
                     if ((tbyte = source[u + 3]) != TRANSPARENT_COLOR)
                         dest[u + 3] = tbyte;
                     if ((tbyte = source[u + 4]) != TRANSPARENT_COLOR)
                         dest[u + 4] = tbyte;
                     if ((tbyte = source[u + 5]) != TRANSPARENT_COLOR)
                         dest[u + 5] = tbyte;
                     if ((tbyte = source[u + 6]) != TRANSPARENT_COLOR)
                         dest[u + 6] = tbyte;
                     if ((tbyte = source[u + 7]) != TRANSPARENT_COLOR)
                         dest[u + 7] = tbyte;
                 }
                 dest += vid.rowbytes;
                 source += pic->width;
             }
         }
     }
 }
Draw_StretchPic()
void Draw_StretchPic (int x, int y, int w, int h, char * name)
Definition at line 405 of file r_draw.c.
 {
     image_t *pic;
     pic = Draw_FindPic(name);
     if (!pic)
     {
         ri.Con_Printf(PRINT_ALL, "Can't find pic: %s\n", name);
         return;
     }
     Draw_StretchPicImplementation(x, y, w, h, pic);
 }
Draw_StretchRaw()
void Draw_StretchRaw (int x, int y, int w, int h, int cols, int rows, byte * data)
Definition at line 423 of file r_draw.c.
 {
     image_t pic;
     pic.pixels[0] = data;
     pic.width = cols;
     pic.height = rows;
     Draw_StretchPicImplementation(x, y, w, h, &pic);
 }
Draw_TileClear()
void Draw_TileClear (int x, int y, int w, int h, char * name)
Definition at line 537 of file r_draw.c.
 {
     int         i, j;
     byte        *psrc;
     byte        *pdest;
     image_t     *pic;
     int         x2;
     if (x < 0)
     {
         w += x;
         x = 0;
     }
     if (y < 0)
     {
         h += y;
         y = 0;
     }
     if (x + w > vid.width)
         w = vid.width - x;
     if (y + h > vid.height)
         h = vid.height - y;
     if (w <= 0 || h <= 0)
         return;
     pic = Draw_FindPic(name);
     if (!pic)
     {
         ri.Con_Printf(PRINT_ALL, "Can't find pic: %s\n", name);
         return;
     }
     x2 = x + w;
     pdest = vid.buffer + y*vid.rowbytes;
     for (i = 0; i < h; i++, pdest += vid.rowbytes)
     {
         psrc = pic->pixels[0] + pic->width * ((i + y) & 63);
         for (j = x; j < x2; j++)
             pdest[j] = psrc[j & 63];
     }
 }
EmitWaterPolys()
void EmitWaterPolys (msurface_t * fa)
Definition at line 211 of file gl_warp.c.
 {
     glpoly_t    *p, *bp;
     float       *v;
     int         i;
     float       s, t, os, ot;
     float       scroll;
     float       rdt = r_newrefdef.time;
     if (fa->texinfo->flags & SURF_FLOWING)
         scroll = -64 * ( (r_newrefdef.time*0.5) - (int)(r_newrefdef.time*0.5) );
     else
         scroll = 0;
     for (bp=fa->polys ; bp ; bp=bp->next)
     {
         p = bp;
         qglBegin (GL_TRIANGLE_FAN);
         for (i=0,v=p->verts[0] ; i<p->numverts ; i++, v+=VERTEXSIZE)
         {
             os = v[3];
             ot = v[4];
 #if !id386
             s = os + r_turbsin[(int)((ot*0.125+r_newrefdef.time) * TURBSCALE) & 255];
 #else
             s = os + r_turbsin[Q_ftol( ((ot*0.125+rdt) * TURBSCALE) ) & 255];
 #endif
             s += scroll;
             s *= (1.0/64);
 #if !id386
             t = ot + r_turbsin[(int)((os*0.125+rdt) * TURBSCALE) & 255];
 #else
             t = ot + r_turbsin[Q_ftol( ((os*0.125+rdt) * TURBSCALE) ) & 255];
 #endif
             t *= (1.0/64);
             qglTexCoord2f (s, t);
             qglVertex3fv (v);
         }
         qglEnd ();
     }
 }
Referenced by R_DrawAlphaSurfaces(), and R_RenderBrushPoly().
GL_BeginRendering()
void GL_BeginRendering (int * x, int * y, int * width, int * height)
GL_Bind()
void GL_Bind (int texnum)
Definition at line 137 of file gl_image.c.
 {
     extern  image_t *draw_chars;
     if (gl_nobind->value && draw_chars)     // performance evaluation option
         texnum = draw_chars->texnum;
     if ( gl_state.currenttextures[gl_state.currenttmu] == texnum)
         return;
     gl_state.currenttextures[gl_state.currenttmu] = texnum;
     qglBindTexture (GL_TEXTURE_2D, texnum);
 }
Referenced by Draw_Char(), Draw_InitLocal(), Draw_Pic(), Draw_StretchPic(), Draw_StretchRaw(), Draw_TileClear(), GL_BeginBuildingLightmaps(), GL_DrawParticles(), GL_LoadPic(), GL_MBind(), GL_TextureMode(), LM_UploadBlock(), R_BlendLightmaps(), R_DrawAliasModel(), R_DrawAlphaSurfaces(), R_DrawSkyBox(), R_DrawSpriteModel(), R_RenderBrushPoly(), and Scrap_Upload().
GL_DrawParticles()
void GL_DrawParticles (int n, const particle_t particles[], const unsigned colortable[768])
Definition at line 415 of file gl_rmain.c.
 {
     const particle_t *p;
     int             i;
     vec3_t          up, right;
     float           scale;
     byte            color[4];
     GL_Bind(r_particletexture->texnum);
     qglDepthMask( GL_FALSE );       // no z buffering
     qglEnable( GL_BLEND );
     GL_TexEnv( GL_MODULATE );
     qglBegin( GL_TRIANGLES );
     VectorScale (vup, 1.5, up);
     VectorScale (vright, 1.5, right);
     for ( p = particles, i=0 ; i < num_particles ; i++,p++)
     {
         // hack a scale up to keep particles from disapearing
         scale = ( p->origin[0] - r_origin[0] ) * vpn[0] +
                 ( p->origin[1] - r_origin[1] ) * vpn[1] +
                 ( p->origin[2] - r_origin[2] ) * vpn[2];
         if (scale < 20)
             scale = 1;
         else
             scale = 1 + scale * 0.004;
         *(int *)color = colortable[p->color];
         color[3] = p->alpha*255;
         qglColor4ubv( color );
         qglTexCoord2f( 0.0625, 0.0625 );
         qglVertex3fv( p->origin );
         qglTexCoord2f( 1.0625, 0.0625 );
         qglVertex3f( p->origin[0] + up[0]*scale,
                      p->origin[1] + up[1]*scale,
                      p->origin[2] + up[2]*scale);
         qglTexCoord2f( 0.0625, 1.0625 );
         qglVertex3f( p->origin[0] + right[0]*scale,
                      p->origin[1] + right[1]*scale,
                      p->origin[2] + right[2]*scale);
     }
     qglEnd ();
     qglDisable( GL_BLEND );
     qglColor4f( 1,1,1,1 );
     qglDepthMask( 1 );      // back to normal Z buffering
     GL_TexEnv( GL_REPLACE );
 }
Referenced by R_DrawParticles().
GL_EnableMultitexture()
void GL_EnableMultitexture (qboolean enable)
Definition at line 71 of file gl_image.c.
 {
     if ( !qglSelectTextureSGIS && !qglActiveTextureARB )
         return;
     if ( enable )
     {
         GL_SelectTexture( gl_texture1 );
         qglEnable( GL_TEXTURE_2D );
         GL_TexEnv( GL_REPLACE );
     }
     else
     {
         GL_SelectTexture( gl_texture1 );
         qglDisable( GL_TEXTURE_2D );
         GL_TexEnv( GL_REPLACE );
     }
     GL_SelectTexture( gl_texture0 );
     GL_TexEnv( GL_REPLACE );
 }
Referenced by DrawTextureChains(), GL_BeginBuildingLightmaps(), GL_EndBuildingLightmaps(), R_DrawBrushModel(), R_DrawInlineBModel(), and R_DrawWorld().
GL_EndRendering()
void GL_EndRendering (void)
GL_FindImage()
image_t* GL_FindImage (char * name, imagetype_t type)
Definition at line 1363 of file gl_image.c.
 {
     image_t *image;
     int     i, len;
     byte    *pic, *palette;
     int     width, height;
     if (!name)
         return NULL;    //  ri.Sys_Error (ERR_DROP, "GL_FindImage: NULL name");
     len = (int)strlen(name);
     if (len<5)
         return NULL;    //  ri.Sys_Error (ERR_DROP, "GL_FindImage: bad name: %s", name);
     // look for it
     for (i=0, image=gltextures ; i<numgltextures ; i++,image++)
     {
         if (!strcmp(name, image->name))
         {
             image->registration_sequence = registration_sequence;
             return image;
         }
     }
     //
     // load the pic from disk
     //
     pic = NULL;
     palette = NULL;
     if (!strcmp(name+len-4, ".pcx"))
     {
         LoadPCX (name, &pic, &palette, &width, &height);
         if (!pic)
             return NULL; // ri.Sys_Error (ERR_DROP, "GL_FindImage: can't load %s", name);
         image = GL_LoadPic (name, pic, width, height, type, 8);
     }
     else if (!strcmp(name+len-4, ".wal"))
     {
         image = GL_LoadWal (name);
     }
     else if (!strcmp(name+len-4, ".tga"))
     {
         LoadTGA (name, &pic, &width, &height);
         if (!pic)
             return NULL; // ri.Sys_Error (ERR_DROP, "GL_FindImage: can't load %s", name);
         image = GL_LoadPic (name, pic, width, height, type, 32);
     }
     else
         return NULL;    //  ri.Sys_Error (ERR_DROP, "GL_FindImage: bad extension on: %s", name);
     if (pic)
         free(pic);
     if (palette)
         free(palette);
     return image;
 }
Referenced by Draw_FindPic(), Draw_InitLocal(), Mod_LoadAliasModel(), Mod_LoadSpriteModel(), Mod_LoadTexinfo(), R_RegisterModel(), R_RegisterSkin(), and R_SetSky().
GL_FreeUnusedImages()
void GL_FreeUnusedImages (void)
Definition at line 1442 of file gl_image.c.
 {
     int     i;
     image_t *image;
     // never free r_notexture or particle texture
     r_notexture->registration_sequence = registration_sequence;
     r_particletexture->registration_sequence = registration_sequence;
     for (i=0, image=gltextures ; i<numgltextures ; i++, image++)
     {
         if (image->registration_sequence == registration_sequence)
             continue;       // used this sequence
         if (!image->registration_sequence)
             continue;       // free image_t slot
         if (image->type == it_pic)
             continue;       // don't free pics
         // free it
         qglDeleteTextures (1, &image->texnum);
         memset (image, 0, sizeof(*image));
     }
 }
Referenced by R_EndRegistration().
GL_ImageList_f()
void GL_ImageList_f (void)
Definition at line 303 of file gl_image.c.
 {
     int     i;
     image_t *image;
     int     texels;
     const char *palstrings[2] =
     {
         "RGB",
         "PAL"
     };
     ri.Con_Printf (PRINT_ALL, "------------------\n");
     texels = 0;
     for (i=0, image=gltextures ; i<numgltextures ; i++, image++)
     {
         if (image->texnum <= 0)
             continue;
         texels += image->upload_width*image->upload_height;
         switch (image->type)
         {
         case it_skin:
             ri.Con_Printf (PRINT_ALL, "M");
             break;
         case it_sprite:
             ri.Con_Printf (PRINT_ALL, "S");
             break;
         case it_wall:
             ri.Con_Printf (PRINT_ALL, "W");
             break;
         case it_pic:
             ri.Con_Printf (PRINT_ALL, "P");
             break;
         default:
             ri.Con_Printf (PRINT_ALL, " ");
             break;
         }
         ri.Con_Printf (PRINT_ALL,  " %3i %3i %s: %s\n",
             image->upload_width, image->upload_height, palstrings[image->paletted], image->name);
     }
     ri.Con_Printf (PRINT_ALL, "Total texel count (not counting mipmaps): %i\n", texels);
 }
Referenced by R_Register().
GL_InitImages()
void GL_InitImages (void)
Definition at line 1509 of file gl_image.c.
 {
     int     i, j;
     float   g = vid_gamma->value;
     registration_sequence = 1;
     // init intensity conversions
     intensity = ri.Cvar_Get ("intensity", "2", 0);
     if ( intensity->value <= 1 )
         ri.Cvar_Set( "intensity", "1" );
     gl_state.inverse_intensity = 1 / intensity->value;
     Draw_GetPalette ();
     if ( qglColorTableEXT )
     {
       ri.FS_LoadFile( "pics/16to8.dat", (void **)&gl_state.d_16to8table );
         if ( !gl_state.d_16to8table )
             ri.Sys_Error( ERR_FATAL, "Couldn't load pics/16to8.pcx");
     }
     if ( gl_config.renderer & ( GL_RENDERER_VOODOO | GL_RENDERER_VOODOO2 ) )
     {
         g = 1.0F;
     }
     for ( i = 0; i < 256; i++ )
     {
         if ( g == 1 )
         {
             gammatable[i] = i;
         }
         else
         {
             float inf;
             inf = 255 * pow ( (i+0.5)/255.5 , g ) + 0.5;
             if (inf < 0)
                 inf = 0;
             if (inf > 255)
                 inf = 255;
             gammatable[i] = inf;
         }
     }
     for (i=0 ; i<256 ; i++)
     {
         j = i*intensity->value;
         if (j > 255)
             j = 255;
         intensitytable[i] = j;
     }
 }
Referenced by R_Init().
GL_LoadPic()
image_t* GL_LoadPic (char * name, byte * pic, int width, int height, imagetype_t type, int bits)
Definition at line 1247 of file gl_image.c.
 {
     image_t     *image;
     int         i;
     // find a free image_t
     for (i=0, image=gltextures ; i<numgltextures ; i++,image++)
     {
         if (!image->texnum)
             break;
     }
     if (i == numgltextures)
     {
         if (numgltextures == MAX_GLTEXTURES)
             ri.Sys_Error (ERR_DROP, "MAX_GLTEXTURES");
         numgltextures++;
     }
     image = &gltextures[i];
     if (strlen(name) >= sizeof(image->name))
         ri.Sys_Error (ERR_DROP, "Draw_LoadPic: \"%s\" is too long", name);
     strcpy (image->name, name);
     image->registration_sequence = registration_sequence;
     image->width = width;
     image->height = height;
     image->type = type;
     if (type == it_skin && bits == 8)
         R_FloodFillSkin(pic, width, height);
     // load little pics into the scrap
     if (image->type == it_pic && bits == 8
         && image->width < 64 && image->height < 64)
     {
         int     x, y;
         int     i, j, k;
         int     texnum;
         texnum = Scrap_AllocBlock (image->width, image->height, &x, &y);
         if (texnum == -1)
             goto nonscrap;
         scrap_dirty = true;
         // copy the texels into the scrap block
         k = 0;
         for (i=0 ; i<image->height ; i++)
             for (j=0 ; j<image->width ; j++, k++)
                 scrap_texels[texnum][(y+i)*BLOCK_WIDTH + x + j] = pic[k];
         image->texnum = TEXNUM_SCRAPS + texnum;
         image->scrap = true;
         image->has_alpha = true;
         image->sl = (x+0.01)/(float)BLOCK_WIDTH;
         image->sh = (x+image->width-0.01)/(float)BLOCK_WIDTH;
         image->tl = (y+0.01)/(float)BLOCK_WIDTH;
         image->th = (y+image->height-0.01)/(float)BLOCK_WIDTH;
     }
     else
     {
 nonscrap:
         image->scrap = false;
         image->texnum = TEXNUM_IMAGES + (image - gltextures);
         GL_Bind(image->texnum);
         if (bits == 8)
             image->has_alpha = GL_Upload8 (pic, width, height, (image->type != it_pic && image->type != it_sky), image->type == it_sky );
         else
             image->has_alpha = GL_Upload32 ((unsigned *)pic, width, height, (image->type != it_pic && image->type != it_sky) );
         image->upload_width = upload_width;     // after power of 2 and scales
         image->upload_height = upload_height;
         image->paletted = uploaded_paletted;
         image->sl = 0;
         image->sh = 1;
         image->tl = 0;
         image->th = 1;
     }
     return image;
 }
Referenced by GL_FindImage(), and GL_LoadWal().
GL_MBind()
void GL_MBind (GLenum target, int texnum)
Definition at line 149 of file gl_image.c.
 {
     GL_SelectTexture( target );
     if ( target == gl_texture0 )
     {
         if ( gl_state.currenttextures[0] == texnum )
             return;
     }
     else
     {
         if ( gl_state.currenttextures[1] == texnum )
             return;
     }
     GL_Bind( texnum );
 }
Referenced by GL_RenderLightmappedPoly().
GL_ResampleTexture()
void GL_ResampleTexture (unsigned * in, int inwidth, int inheight, unsigned * out, int outwidth, int outheight)
Definition at line 827 of file gl_image.c.
 {
     int     i, j;
     unsigned    *inrow, *inrow2;
     unsigned    frac, fracstep;
     unsigned    p1[1024], p2[1024];
     byte        *pix1, *pix2, *pix3, *pix4;
     fracstep = inwidth*0x10000/outwidth;
     frac = fracstep>>2;
     for (i=0 ; i<outwidth ; i++)
     {
         p1[i] = 4*(frac>>16);
         frac += fracstep;
     }
     frac = 3*(fracstep>>2);
     for (i=0 ; i<outwidth ; i++)
     {
         p2[i] = 4*(frac>>16);
         frac += fracstep;
     }
     for (i=0 ; i<outheight ; i++, out += outwidth)
     {
         inrow = in + inwidth*(int)((i+0.25)*inheight/outheight);
         inrow2 = in + inwidth*(int)((i+0.75)*inheight/outheight);
         frac = fracstep >> 1;
         for (j=0 ; j<outwidth ; j++)
         {
             pix1 = (byte *)inrow + p1[j];
             pix2 = (byte *)inrow + p2[j];
             pix3 = (byte *)inrow2 + p1[j];
             pix4 = (byte *)inrow2 + p2[j];
             ((byte *)(out+j))[0] = (pix1[0] + pix2[0] + pix3[0] + pix4[0])>>2;
             ((byte *)(out+j))[1] = (pix1[1] + pix2[1] + pix3[1] + pix4[1])>>2;
             ((byte *)(out+j))[2] = (pix1[2] + pix2[2] + pix3[2] + pix4[2])>>2;
             ((byte *)(out+j))[3] = (pix1[3] + pix2[3] + pix3[3] + pix4[3])>>2;
         }
     }
 }
Referenced by GL_Upload32().
GL_ScreenShot_f()
void GL_ScreenShot_f (void)
Definition at line 100 of file gl_rmisc.c.
 {
     byte        *buffer;
     char        picname[80];
     char        checkname[MAX_OSPATH];
     int         i, c, temp;
     FILE        *f;
     // create the scrnshots directory if it doesn't exist
     Com_sprintf (checkname, sizeof(checkname), "%s/scrnshot", ri.FS_Gamedir());
     Sys_Mkdir (checkname);
 //
 // find a file name to save it to
 //
     strcpy(picname,"quake00.tga");
     for (i=0 ; i<=99 ; i++)
     {
         picname[5] = i/10 + '0';
         picname[6] = i%10 + '0';
         Com_sprintf (checkname, sizeof(checkname), "%s/scrnshot/%s", ri.FS_Gamedir(), picname);
         f = fopen (checkname, "rb");
         if (!f)
             break;  // file doesn't exist
         fclose (f);
     }
     if (i==100)
     {
         ri.Con_Printf (PRINT_ALL, "SCR_ScreenShot_f: Couldn't create a file\n");
         return;
     }
     buffer = malloc(vid.width*vid.height*3 + 18);
     memset (buffer, 0, 18);
     buffer[2] = 2;      // uncompressed type
     buffer[12] = vid.width&255;
     buffer[13] = vid.width>>8;
     buffer[14] = vid.height&255;
     buffer[15] = vid.height>>8;
     buffer[16] = 24;    // pixel size
     qglReadPixels (0, 0, vid.width, vid.height, GL_RGB, GL_UNSIGNED_BYTE, buffer+18 );
     // swap rgb to bgr
     c = 18+vid.width*vid.height*3;
     for (i=18 ; i<c ; i+=3)
     {
         temp = buffer[i];
         buffer[i] = buffer[i+2];
         buffer[i+2] = temp;
     }
     f = fopen (checkname, "wb");
     fwrite (buffer, 1, c, f);
     fclose (f);
     free (buffer);
     ri.Con_Printf (PRINT_ALL, "Wrote %s\n", picname);
 }
Referenced by R_Register().
GL_SelectTexture()
void GL_SelectTexture (GLenum)
Definition at line 92 of file gl_image.c.
 {
     int tmu;
     if ( !qglSelectTextureSGIS && !qglActiveTextureARB )
         return;
     if ( texture == gl_texture0 )
     {
         tmu = 0;
     }
     else
     {
         tmu = 1;
     }
     if ( tmu == gl_state.currenttmu )
     {
         return;
     }
     gl_state.currenttmu = tmu;
     if ( qglSelectTextureSGIS )
     {
         qglSelectTextureSGIS( texture );
     }
     else if ( qglActiveTextureARB )
     {
         qglActiveTextureARB( texture );
         qglClientActiveTextureARB( texture );
     }
 }
Referenced by GL_BeginBuildingLightmaps(), GL_EnableMultitexture(), GL_MBind(), R_DrawBrushModel(), and R_DrawWorld().
GL_SetDefaultState()
void GL_SetDefaultState (void)
Definition at line 176 of file gl_rmisc.c.
 {
     qglClearColor (1,0, 0.5 , 0.5);
     qglCullFace(GL_FRONT);
     qglEnable(GL_TEXTURE_2D);
     qglEnable(GL_ALPHA_TEST);
     qglAlphaFunc(GL_GREATER, 0.666);
     qglDisable (GL_DEPTH_TEST);
     qglDisable (GL_CULL_FACE);
     qglDisable (GL_BLEND);
     qglColor4f (1,1,1,1);
     qglPolygonMode (GL_FRONT_AND_BACK, GL_FILL);
     qglShadeModel (GL_FLAT);
     GL_TextureMode( gl_texturemode->string );
     GL_TextureAlphaMode( gl_texturealphamode->string );
     GL_TextureSolidMode( gl_texturesolidmode->string );
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, gl_filter_min);
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, gl_filter_max);
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
     qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
     qglBlendFunc (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     GL_TexEnv( GL_REPLACE );
     if ( qglPointParameterfEXT )
     {
         float attenuations[3];
         attenuations[0] = gl_particle_att_a->value;
         attenuations[1] = gl_particle_att_b->value;
         attenuations[2] = gl_particle_att_c->value;
         qglEnable( GL_POINT_SMOOTH );
         qglPointParameterfEXT( GL_POINT_SIZE_MIN_EXT, gl_particle_min_size->value );
         qglPointParameterfEXT( GL_POINT_SIZE_MAX_EXT, gl_particle_max_size->value );
         qglPointParameterfvEXT( GL_DISTANCE_ATTENUATION_EXT, attenuations );
     }
     if ( qglColorTableEXT && gl_ext_palettedtexture->value )
     {
         qglEnable( GL_SHARED_TEXTURE_PALETTE_EXT );
         GL_SetTexturePalette( d_8to24table );
     }
     GL_UpdateSwapInterval();
 }
Referenced by R_Init().
GL_SetTexturePalette()
void GL_SetTexturePalette (unsigned palette[256])
Definition at line 48 of file gl_image.c.
 {
     int i;
     unsigned char temptable[768];
     if ( qglColorTableEXT && gl_ext_palettedtexture->value )
     {
         for ( i = 0; i < 256; i++ )
         {
             temptable[i*3+0] = ( palette[i] >> 0 ) & 0xff;
             temptable[i*3+1] = ( palette[i] >> 8 ) & 0xff;
             temptable[i*3+2] = ( palette[i] >> 16 ) & 0xff;
         }
         qglColorTableEXT( GL_SHARED_TEXTURE_PALETTE_EXT,
                            GL_RGB,
                            256,
                            GL_RGB,
                            GL_UNSIGNED_BYTE,
                            temptable );
     }
 }
Referenced by GL_SetDefaultState(), and R_SetPalette().
GL_ShutdownImages()
void GL_ShutdownImages (void)
Definition at line 1571 of file gl_image.c.
 {
     int     i;
     image_t *image;
     for (i=0, image=gltextures ; i<numgltextures ; i++, image++)
     {
         if (!image->registration_sequence)
             continue;       // free image_t slot
         // free it
         qglDeleteTextures (1, &image->texnum);
         memset (image, 0, sizeof(*image));
     }
 }
Referenced by R_Shutdown().
GL_SubdivideSurface()
void GL_SubdivideSurface (msurface_t * fa)
Definition at line 164 of file gl_warp.c.
 {
     vec3_t      verts[64];
     int         numverts;
     int         i;
     int         lindex;
     float       *vec;
     warpface = fa;
     //
     // convert edges back to a normal polygon
     //
     numverts = 0;
     for (i=0 ; i<fa->numedges ; i++)
     {
         lindex = loadmodel->surfedges[fa->firstedge + i];
         if (lindex > 0)
             vec = loadmodel->vertexes[loadmodel->edges[lindex].v[0]].position;
         else
             vec = loadmodel->vertexes[loadmodel->edges[-lindex].v[1]].position;
         VectorCopy (vec, verts[numverts]);
         numverts++;
     }
     SubdividePolygon (numverts, verts[0]);
 }
Referenced by Mod_LoadFaces().
GL_TexEnv()
void GL_TexEnv (GLenum value)
Definition at line 126 of file gl_image.c.
 {
     static int lastmodes[2] = { -1, -1 };
     if ( mode != lastmodes[gl_state.currenttmu] )
     {
         qglTexEnvf( GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, mode );
         lastmodes[gl_state.currenttmu] = mode;
     }
 }
Referenced by DrawTextureChains(), GL_DrawParticles(), GL_EnableMultitexture(), GL_SetDefaultState(), R_DrawAliasModel(), R_DrawAlphaSurfaces(), R_DrawBrushModel(), R_DrawInlineBModel(), R_DrawSkyBox(), R_DrawSpriteModel(), R_DrawWorld(), and R_RenderBrushPoly().
GL_TextureAlphaMode()
void GL_TextureAlphaMode (char * string)
Definition at line 255 of file gl_image.c.
 {
     int     i;
     for (i=0 ; i< NUM_GL_ALPHA_MODES ; i++)
     {
         if ( !Q_stricmp( gl_alpha_modes[i].name, string ) )
             break;
     }
     if (i == NUM_GL_ALPHA_MODES)
     {
         ri.Con_Printf (PRINT_ALL, "bad alpha texture mode name\n");
         return;
     }
     gl_tex_alpha_format = gl_alpha_modes[i].mode;
 }
Referenced by GL_SetDefaultState(), and R_BeginFrame().
GL_TextureMode()
void GL_TextureMode (char * string)
Definition at line 218 of file gl_image.c.
 {
     int     i;
     image_t *glt;
     for (i=0 ; i< NUM_GL_MODES ; i++)
     {
         if ( !Q_stricmp( modes[i].name, string ) )
             break;
     }
     if (i == NUM_GL_MODES)
     {
         ri.Con_Printf (PRINT_ALL, "bad filter name\n");
         return;
     }
     gl_filter_min = modes[i].minimize;
     gl_filter_max = modes[i].maximize;
     // change all the existing mipmap texture objects
     for (i=0, glt=gltextures ; i<numgltextures ; i++, glt++)
     {
         if (glt->type != it_pic && glt->type != it_sky )
         {
             GL_Bind (glt->texnum);
             qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, gl_filter_min);
             qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, gl_filter_max);
         }
     }
 }
Referenced by GL_SetDefaultState(), and R_BeginFrame().
GL_TextureSolidMode()
void GL_TextureSolidMode (char * string)
Definition at line 279 of file gl_image.c.
 {
     int     i;
     for (i=0 ; i< NUM_GL_SOLID_MODES ; i++)
     {
         if ( !Q_stricmp( gl_solid_modes[i].name, string ) )
             break;
     }
     if (i == NUM_GL_SOLID_MODES)
     {
         ri.Con_Printf (PRINT_ALL, "bad solid texture mode name\n");
         return;
     }
     gl_tex_solid_format = gl_solid_modes[i].mode;
 }
Referenced by GL_SetDefaultState(), and R_BeginFrame().
GL_UpdateSwapInterval()
void GL_UpdateSwapInterval (void)
Definition at line 232 of file gl_rmisc.c.
 {
     if ( gl_swapinterval->modified )
     {
         gl_swapinterval->modified = false;
         if ( !gl_state.stereo_enabled )
         {
 #ifdef _WIN32
             if ( qwglSwapIntervalEXT )
                 qwglSwapIntervalEXT( gl_swapinterval->value );
 #endif
         }
     }
 }
Referenced by GL_SetDefaultState(), and R_BeginFrame().
GLimp_AppActivate()
void GLimp_AppActivate (qboolean active)
Definition at line 578 of file glw_imp.c.
 {
     if ( active )
     {
         SetForegroundWindow( glw_state.hWnd );
         ShowWindow( glw_state.hWnd, SW_RESTORE );
     }
     else
     {
         if ( vid_fullscreen->value )
             ShowWindow( glw_state.hWnd, SW_MINIMIZE );
     }
 }
Referenced by GetRefAPI().
GLimp_BeginFrame()
void GLimp_BeginFrame (float camera_separation)
Definition at line 528 of file glw_imp.c.
 {
     if ( gl_bitdepth->modified )
     {
         if ( gl_bitdepth->value != 0 && !glw_state.allowdisplaydepthchange )
         {
             ri.Cvar_SetValue( "gl_bitdepth", 0 );
             ri.Con_Printf( PRINT_ALL, "gl_bitdepth requires Win95 OSR2.x or WinNT 4.x\n" );
         }
         gl_bitdepth->modified = false;
     }
     if ( camera_separation < 0 && gl_state.stereo_enabled )
     {
         qglDrawBuffer( GL_BACK_LEFT );
     }
     else if ( camera_separation > 0 && gl_state.stereo_enabled )
     {
         qglDrawBuffer( GL_BACK_RIGHT );
     }
     else
     {
         qglDrawBuffer( GL_BACK );
     }
 }
Referenced by R_BeginFrame().
GLimp_EnableLogging()
void GLimp_EnableLogging (qboolean enable)
Definition at line 3427 of file qgl_win.c.
 {
     if ( enable )
     {
         if ( !glw_state.log_fp )
         {
             struct tm *newtime;
             time_t aclock;
             char buffer[1024];
             time( &aclock );
             newtime = localtime( &aclock );
             asctime( newtime );
             Com_sprintf( buffer, sizeof(buffer), "%s/gl.log", ri.FS_Gamedir() );
             glw_state.log_fp = fopen( buffer, "wt" );
             fprintf( glw_state.log_fp, "%s\n", asctime( newtime ) );
         }
         qglAccum                     = logAccum;
         qglAlphaFunc                 = logAlphaFunc;
         qglAreTexturesResident       = logAreTexturesResident;
         qglArrayElement              = logArrayElement;
         qglBegin                     = logBegin;
         qglBindTexture               = logBindTexture;
         qglBitmap                    = logBitmap;
         qglBlendFunc                 = logBlendFunc;
         qglCallList                  = logCallList;
         qglCallLists                 = logCallLists;
         qglClear                     = logClear;
         qglClearAccum                = logClearAccum;
         qglClearColor                = logClearColor;
         qglClearDepth                = logClearDepth;
         qglClearIndex                = logClearIndex;
         qglClearStencil              = logClearStencil;
         qglClipPlane                 = logClipPlane;
         qglColor3b                   = logColor3b;
         qglColor3bv                  = logColor3bv;
         qglColor3d                   = logColor3d;
         qglColor3dv                  = logColor3dv;
         qglColor3f                   = logColor3f;
         qglColor3fv                  = logColor3fv;
         qglColor3i                   = logColor3i;
         qglColor3iv                  = logColor3iv;
         qglColor3s                   = logColor3s;
         qglColor3sv                  = logColor3sv;
         qglColor3ub                  = logColor3ub;
         qglColor3ubv                 = logColor3ubv;
         qglColor3ui                  = logColor3ui;
         qglColor3uiv                 = logColor3uiv;
         qglColor3us                  = logColor3us;
         qglColor3usv                 = logColor3usv;
         qglColor4b                   = logColor4b;
         qglColor4bv                  = logColor4bv;
         qglColor4d                   = logColor4d;
         qglColor4dv                  = logColor4dv;
         qglColor4f                   = logColor4f;
         qglColor4fv                  = logColor4fv;
         qglColor4i                   = logColor4i;
         qglColor4iv                  = logColor4iv;
         qglColor4s                   = logColor4s;
         qglColor4sv                  = logColor4sv;
         qglColor4ub                  = logColor4ub;
         qglColor4ubv                 = logColor4ubv;
         qglColor4ui                  = logColor4ui;
         qglColor4uiv                 = logColor4uiv;
         qglColor4us                  = logColor4us;
         qglColor4usv                 = logColor4usv;
         qglColorMask                 = logColorMask;
         qglColorMaterial             = logColorMaterial;
         qglColorPointer              = logColorPointer;
         qglCopyPixels                = logCopyPixels;
         qglCopyTexImage1D            = logCopyTexImage1D;
         qglCopyTexImage2D            = logCopyTexImage2D;
         qglCopyTexSubImage1D         = logCopyTexSubImage1D;
         qglCopyTexSubImage2D         = logCopyTexSubImage2D;
         qglCullFace                  = logCullFace;
         qglDeleteLists               = logDeleteLists ;
         qglDeleteTextures            = logDeleteTextures ;
         qglDepthFunc                 = logDepthFunc ;
         qglDepthMask                 = logDepthMask ;
         qglDepthRange                = logDepthRange ;
         qglDisable                   = logDisable ;
         qglDisableClientState        = logDisableClientState ;
         qglDrawArrays                = logDrawArrays ;
         qglDrawBuffer                = logDrawBuffer ;
         qglDrawElements              = logDrawElements ;
         qglDrawPixels                = logDrawPixels ;
         qglEdgeFlag                  = logEdgeFlag ;
         qglEdgeFlagPointer           = logEdgeFlagPointer ;
         qglEdgeFlagv                 = logEdgeFlagv ;
         qglEnable                    =  logEnable                    ;
         qglEnableClientState         =  logEnableClientState         ;
         qglEnd                       =  logEnd                       ;
         qglEndList                   =  logEndList                   ;
         qglEvalCoord1d               =  logEvalCoord1d               ;
         qglEvalCoord1dv              =  logEvalCoord1dv              ;
         qglEvalCoord1f               =  logEvalCoord1f               ;
         qglEvalCoord1fv              =  logEvalCoord1fv              ;
         qglEvalCoord2d               =  logEvalCoord2d               ;
         qglEvalCoord2dv              =  logEvalCoord2dv              ;
         qglEvalCoord2f               =  logEvalCoord2f               ;
         qglEvalCoord2fv              =  logEvalCoord2fv              ;
         qglEvalMesh1                 =  logEvalMesh1                 ;
         qglEvalMesh2                 =  logEvalMesh2                 ;
         qglEvalPoint1                =  logEvalPoint1                ;
         qglEvalPoint2                =  logEvalPoint2                ;
         qglFeedbackBuffer            =  logFeedbackBuffer            ;
         qglFinish                    =  logFinish                    ;
         qglFlush                     =  logFlush                     ;
         qglFogf                      =  logFogf                      ;
         qglFogfv                     =  logFogfv                     ;
         qglFogi                      =  logFogi                      ;
         qglFogiv                     =  logFogiv                     ;
         qglFrontFace                 =  logFrontFace                 ;
         qglFrustum                   =  logFrustum                   ;
         qglGenLists                  =  logGenLists                  ;
         qglGenTextures               =  logGenTextures               ;
         qglGetBooleanv               =  logGetBooleanv               ;
         qglGetClipPlane              =  logGetClipPlane              ;
         qglGetDoublev                =  logGetDoublev                ;
         qglGetError                  =  logGetError                  ;
         qglGetFloatv                 =  logGetFloatv                 ;
         qglGetIntegerv               =  logGetIntegerv               ;
         qglGetLightfv                =  logGetLightfv                ;
         qglGetLightiv                =  logGetLightiv                ;
         qglGetMapdv                  =  logGetMapdv                  ;
         qglGetMapfv                  =  logGetMapfv                  ;
         qglGetMapiv                  =  logGetMapiv                  ;
         qglGetMaterialfv             =  logGetMaterialfv             ;
         qglGetMaterialiv             =  logGetMaterialiv             ;
         qglGetPixelMapfv             =  logGetPixelMapfv             ;
         qglGetPixelMapuiv            =  logGetPixelMapuiv            ;
         qglGetPixelMapusv            =  logGetPixelMapusv            ;
         qglGetPointerv               =  logGetPointerv               ;
         qglGetPolygonStipple         =  logGetPolygonStipple         ;
         qglGetString                 =  logGetString                 ;
         qglGetTexEnvfv               =  logGetTexEnvfv               ;
         qglGetTexEnviv               =  logGetTexEnviv               ;
         qglGetTexGendv               =  logGetTexGendv               ;
         qglGetTexGenfv               =  logGetTexGenfv               ;
         qglGetTexGeniv               =  logGetTexGeniv               ;
         qglGetTexImage               =  logGetTexImage               ;
         qglGetTexLevelParameterfv    =  logGetTexLevelParameterfv    ;
         qglGetTexLevelParameteriv    =  logGetTexLevelParameteriv    ;
         qglGetTexParameterfv         =  logGetTexParameterfv         ;
         qglGetTexParameteriv         =  logGetTexParameteriv         ;
         qglHint                      =  logHint                      ;
         qglIndexMask                 =  logIndexMask                 ;
         qglIndexPointer              =  logIndexPointer              ;
         qglIndexd                    =  logIndexd                    ;
         qglIndexdv                   =  logIndexdv                   ;
         qglIndexf                    =  logIndexf                    ;
         qglIndexfv                   =  logIndexfv                   ;
         qglIndexi                    =  logIndexi                    ;
         qglIndexiv                   =  logIndexiv                   ;
         qglIndexs                    =  logIndexs                    ;
         qglIndexsv                   =  logIndexsv                   ;
         qglIndexub                   =  logIndexub                   ;
         qglIndexubv                  =  logIndexubv                  ;
         qglInitNames                 =  logInitNames                 ;
         qglInterleavedArrays         =  logInterleavedArrays         ;
         qglIsEnabled                 =  logIsEnabled                 ;
         qglIsList                    =  logIsList                    ;
         qglIsTexture                 =  logIsTexture                 ;
         qglLightModelf               =  logLightModelf               ;
         qglLightModelfv              =  logLightModelfv              ;
         qglLightModeli               =  logLightModeli               ;
         qglLightModeliv              =  logLightModeliv              ;
         qglLightf                    =  logLightf                    ;
         qglLightfv                   =  logLightfv                   ;
         qglLighti                    =  logLighti                    ;
         qglLightiv                   =  logLightiv                   ;
         qglLineStipple               =  logLineStipple               ;
         qglLineWidth                 =  logLineWidth                 ;
         qglListBase                  =  logListBase                  ;
         qglLoadIdentity              =  logLoadIdentity              ;
         qglLoadMatrixd               =  logLoadMatrixd               ;
         qglLoadMatrixf               =  logLoadMatrixf               ;
         qglLoadName                  =  logLoadName                  ;
         qglLogicOp                   =  logLogicOp                   ;
         qglMap1d                     =  logMap1d                     ;
         qglMap1f                     =  logMap1f                     ;
         qglMap2d                     =  logMap2d                     ;
         qglMap2f                     =  logMap2f                     ;
         qglMapGrid1d                 =  logMapGrid1d                 ;
         qglMapGrid1f                 =  logMapGrid1f                 ;
         qglMapGrid2d                 =  logMapGrid2d                 ;
         qglMapGrid2f                 =  logMapGrid2f                 ;
         qglMaterialf                 =  logMaterialf                 ;
         qglMaterialfv                =  logMaterialfv                ;
         qglMateriali                 =  logMateriali                 ;
         qglMaterialiv                =  logMaterialiv                ;
         qglMatrixMode                =  logMatrixMode                ;
         qglMultMatrixd               =  logMultMatrixd               ;
         qglMultMatrixf               =  logMultMatrixf               ;
         qglNewList                   =  logNewList                   ;
         qglNormal3b                  =  logNormal3b                  ;
         qglNormal3bv                 =  logNormal3bv                 ;
         qglNormal3d                  =  logNormal3d                  ;
         qglNormal3dv                 =  logNormal3dv                 ;
         qglNormal3f                  =  logNormal3f                  ;
         qglNormal3fv                 =  logNormal3fv                 ;
         qglNormal3i                  =  logNormal3i                  ;
         qglNormal3iv                 =  logNormal3iv                 ;
         qglNormal3s                  =  logNormal3s                  ;
         qglNormal3sv                 =  logNormal3sv                 ;
         qglNormalPointer             =  logNormalPointer             ;
         qglOrtho                     =  logOrtho                     ;
         qglPassThrough               =  logPassThrough               ;
         qglPixelMapfv                =  logPixelMapfv                ;
         qglPixelMapuiv               =  logPixelMapuiv               ;
         qglPixelMapusv               =  logPixelMapusv               ;
         qglPixelStoref               =  logPixelStoref               ;
         qglPixelStorei               =  logPixelStorei               ;
         qglPixelTransferf            =  logPixelTransferf            ;
         qglPixelTransferi            =  logPixelTransferi            ;
         qglPixelZoom                 =  logPixelZoom                 ;
         qglPointSize                 =  logPointSize                 ;
         qglPolygonMode               =  logPolygonMode               ;
         qglPolygonOffset             =  logPolygonOffset             ;
         qglPolygonStipple            =  logPolygonStipple            ;
         qglPopAttrib                 =  logPopAttrib                 ;
         qglPopClientAttrib           =  logPopClientAttrib           ;
         qglPopMatrix                 =  logPopMatrix                 ;
         qglPopName                   =  logPopName                   ;
         qglPrioritizeTextures        =  logPrioritizeTextures        ;
         qglPushAttrib                =  logPushAttrib                ;
         qglPushClientAttrib          =  logPushClientAttrib          ;
         qglPushMatrix                =  logPushMatrix                ;
         qglPushName                  =  logPushName                  ;
         qglRasterPos2d               =  logRasterPos2d               ;
         qglRasterPos2dv              =  logRasterPos2dv              ;
         qglRasterPos2f               =  logRasterPos2f               ;
         qglRasterPos2fv              =  logRasterPos2fv              ;
         qglRasterPos2i               =  logRasterPos2i               ;
         qglRasterPos2iv              =  logRasterPos2iv              ;
         qglRasterPos2s               =  logRasterPos2s               ;
         qglRasterPos2sv              =  logRasterPos2sv              ;
         qglRasterPos3d               =  logRasterPos3d               ;
         qglRasterPos3dv              =  logRasterPos3dv              ;
         qglRasterPos3f               =  logRasterPos3f               ;
         qglRasterPos3fv              =  logRasterPos3fv              ;
         qglRasterPos3i               =  logRasterPos3i               ;
         qglRasterPos3iv              =  logRasterPos3iv              ;
         qglRasterPos3s               =  logRasterPos3s               ;
         qglRasterPos3sv              =  logRasterPos3sv              ;
         qglRasterPos4d               =  logRasterPos4d               ;
         qglRasterPos4dv              =  logRasterPos4dv              ;
         qglRasterPos4f               =  logRasterPos4f               ;
         qglRasterPos4fv              =  logRasterPos4fv              ;
         qglRasterPos4i               =  logRasterPos4i               ;
         qglRasterPos4iv              =  logRasterPos4iv              ;
         qglRasterPos4s               =  logRasterPos4s               ;
         qglRasterPos4sv              =  logRasterPos4sv              ;
         qglReadBuffer                =  logReadBuffer                ;
         qglReadPixels                =  logReadPixels                ;
         qglRectd                     =  logRectd                     ;
         qglRectdv                    =  logRectdv                    ;
         qglRectf                     =  logRectf                     ;
         qglRectfv                    =  logRectfv                    ;
         qglRecti                     =  logRecti                     ;
         qglRectiv                    =  logRectiv                    ;
         qglRects                     =  logRects                     ;
         qglRectsv                    =  logRectsv                    ;
         qglRenderMode                =  logRenderMode                ;
         qglRotated                   =  logRotated                   ;
         qglRotatef                   =  logRotatef                   ;
         qglScaled                    =  logScaled                    ;
         qglScalef                    =  logScalef                    ;
         qglScissor                   =  logScissor                   ;
         qglSelectBuffer              =  logSelectBuffer              ;
         qglShadeModel                =  logShadeModel                ;
         qglStencilFunc               =  logStencilFunc               ;
         qglStencilMask               =  logStencilMask               ;
         qglStencilOp                 =  logStencilOp                 ;
         qglTexCoord1d                =  logTexCoord1d                ;
         qglTexCoord1dv               =  logTexCoord1dv               ;
         qglTexCoord1f                =  logTexCoord1f                ;
         qglTexCoord1fv               =  logTexCoord1fv               ;
         qglTexCoord1i                =  logTexCoord1i                ;
         qglTexCoord1iv               =  logTexCoord1iv               ;
         qglTexCoord1s                =  logTexCoord1s                ;
         qglTexCoord1sv               =  logTexCoord1sv               ;
         qglTexCoord2d                =  logTexCoord2d                ;
         qglTexCoord2dv               =  logTexCoord2dv               ;
         qglTexCoord2f                =  logTexCoord2f                ;
         qglTexCoord2fv               =  logTexCoord2fv               ;
         qglTexCoord2i                =  logTexCoord2i                ;
         qglTexCoord2iv               =  logTexCoord2iv               ;
         qglTexCoord2s                =  logTexCoord2s                ;
         qglTexCoord2sv               =  logTexCoord2sv               ;
         qglTexCoord3d                =  logTexCoord3d                ;
         qglTexCoord3dv               =  logTexCoord3dv               ;
         qglTexCoord3f                =  logTexCoord3f                ;
         qglTexCoord3fv               =  logTexCoord3fv               ;
         qglTexCoord3i                =  logTexCoord3i                ;
         qglTexCoord3iv               =  logTexCoord3iv               ;
         qglTexCoord3s                =  logTexCoord3s                ;
         qglTexCoord3sv               =  logTexCoord3sv               ;
         qglTexCoord4d                =  logTexCoord4d                ;
         qglTexCoord4dv               =  logTexCoord4dv               ;
         qglTexCoord4f                =  logTexCoord4f                ;
         qglTexCoord4fv               =  logTexCoord4fv               ;
         qglTexCoord4i                =  logTexCoord4i                ;
         qglTexCoord4iv               =  logTexCoord4iv               ;
         qglTexCoord4s                =  logTexCoord4s                ;
         qglTexCoord4sv               =  logTexCoord4sv               ;
         qglTexCoordPointer           =  logTexCoordPointer           ;
         qglTexEnvf                   =  logTexEnvf                   ;
         qglTexEnvfv                  =  logTexEnvfv                  ;
         qglTexEnvi                   =  logTexEnvi                   ;
         qglTexEnviv                  =  logTexEnviv                  ;
         qglTexGend                   =  logTexGend                   ;
         qglTexGendv                  =  logTexGendv                  ;
         qglTexGenf                   =  logTexGenf                   ;
         qglTexGenfv                  =  logTexGenfv                  ;
         qglTexGeni                   =  logTexGeni                   ;
         qglTexGeniv                  =  logTexGeniv                  ;
         qglTexImage1D                =  logTexImage1D                ;
         qglTexImage2D                =  logTexImage2D                ;
         qglTexParameterf             =  logTexParameterf             ;
         qglTexParameterfv            =  logTexParameterfv            ;
         qglTexParameteri             =  logTexParameteri             ;
         qglTexParameteriv            =  logTexParameteriv            ;
         qglTexSubImage1D             =  logTexSubImage1D             ;
         qglTexSubImage2D             =  logTexSubImage2D             ;
         qglTranslated                =  logTranslated                ;
         qglTranslatef                =  logTranslatef                ;
         qglVertex2d                  =  logVertex2d                  ;
         qglVertex2dv                 =  logVertex2dv                 ;
         qglVertex2f                  =  logVertex2f                  ;
         qglVertex2fv                 =  logVertex2fv                 ;
         qglVertex2i                  =  logVertex2i                  ;
         qglVertex2iv                 =  logVertex2iv                 ;
         qglVertex2s                  =  logVertex2s                  ;
         qglVertex2sv                 =  logVertex2sv                 ;
         qglVertex3d                  =  logVertex3d                  ;
         qglVertex3dv                 =  logVertex3dv                 ;
         qglVertex3f                  =  logVertex3f                  ;
         qglVertex3fv                 =  logVertex3fv                 ;
         qglVertex3i                  =  logVertex3i                  ;
         qglVertex3iv                 =  logVertex3iv                 ;
         qglVertex3s                  =  logVertex3s                  ;
         qglVertex3sv                 =  logVertex3sv                 ;
         qglVertex4d                  =  logVertex4d                  ;
         qglVertex4dv                 =  logVertex4dv                 ;
         qglVertex4f                  =  logVertex4f                  ;
         qglVertex4fv                 =  logVertex4fv                 ;
         qglVertex4i                  =  logVertex4i                  ;
         qglVertex4iv                 =  logVertex4iv                 ;
         qglVertex4s                  =  logVertex4s                  ;
         qglVertex4sv                 =  logVertex4sv                 ;
         qglVertexPointer             =  logVertexPointer             ;
         qglViewport                  =  logViewport                  ;
     }
     else
     {
         qglAccum                     = dllAccum;
         qglAlphaFunc                 = dllAlphaFunc;
         qglAreTexturesResident       = dllAreTexturesResident;
         qglArrayElement              = dllArrayElement;
         qglBegin                     = dllBegin;
         qglBindTexture               = dllBindTexture;
         qglBitmap                    = dllBitmap;
         qglBlendFunc                 = dllBlendFunc;
         qglCallList                  = dllCallList;
         qglCallLists                 = dllCallLists;
         qglClear                     = dllClear;
         qglClearAccum                = dllClearAccum;
         qglClearColor                = dllClearColor;
         qglClearDepth                = dllClearDepth;
         qglClearIndex                = dllClearIndex;
         qglClearStencil              = dllClearStencil;
         qglClipPlane                 = dllClipPlane;
         qglColor3b                   = dllColor3b;
         qglColor3bv                  = dllColor3bv;
         qglColor3d                   = dllColor3d;
         qglColor3dv                  = dllColor3dv;
         qglColor3f                   = dllColor3f;
         qglColor3fv                  = dllColor3fv;
         qglColor3i                   = dllColor3i;
         qglColor3iv                  = dllColor3iv;
         qglColor3s                   = dllColor3s;
         qglColor3sv                  = dllColor3sv;
         qglColor3ub                  = dllColor3ub;
         qglColor3ubv                 = dllColor3ubv;
         qglColor3ui                  = dllColor3ui;
         qglColor3uiv                 = dllColor3uiv;
         qglColor3us                  = dllColor3us;
         qglColor3usv                 = dllColor3usv;
         qglColor4b                   = dllColor4b;
         qglColor4bv                  = dllColor4bv;
         qglColor4d                   = dllColor4d;
         qglColor4dv                  = dllColor4dv;
         qglColor4f                   = dllColor4f;
         qglColor4fv                  = dllColor4fv;
         qglColor4i                   = dllColor4i;
         qglColor4iv                  = dllColor4iv;
         qglColor4s                   = dllColor4s;
         qglColor4sv                  = dllColor4sv;
         qglColor4ub                  = dllColor4ub;
         qglColor4ubv                 = dllColor4ubv;
         qglColor4ui                  = dllColor4ui;
         qglColor4uiv                 = dllColor4uiv;
         qglColor4us                  = dllColor4us;
         qglColor4usv                 = dllColor4usv;
         qglColorMask                 = dllColorMask;
         qglColorMaterial             = dllColorMaterial;
         qglColorPointer              = dllColorPointer;
         qglCopyPixels                = dllCopyPixels;
         qglCopyTexImage1D            = dllCopyTexImage1D;
         qglCopyTexImage2D            = dllCopyTexImage2D;
         qglCopyTexSubImage1D         = dllCopyTexSubImage1D;
         qglCopyTexSubImage2D         = dllCopyTexSubImage2D;
         qglCullFace                  = dllCullFace;
         qglDeleteLists               = dllDeleteLists ;
         qglDeleteTextures            = dllDeleteTextures ;
         qglDepthFunc                 = dllDepthFunc ;
         qglDepthMask                 = dllDepthMask ;
         qglDepthRange                = dllDepthRange ;
         qglDisable                   = dllDisable ;
         qglDisableClientState        = dllDisableClientState ;
         qglDrawArrays                = dllDrawArrays ;
         qglDrawBuffer                = dllDrawBuffer ;
         qglDrawElements              = dllDrawElements ;
         qglDrawPixels                = dllDrawPixels ;
         qglEdgeFlag                  = dllEdgeFlag ;
         qglEdgeFlagPointer           = dllEdgeFlagPointer ;
         qglEdgeFlagv                 = dllEdgeFlagv ;
         qglEnable                    =  dllEnable                    ;
         qglEnableClientState         =  dllEnableClientState         ;
         qglEnd                       =  dllEnd                       ;
         qglEndList                   =  dllEndList                   ;
         qglEvalCoord1d               =  dllEvalCoord1d               ;
         qglEvalCoord1dv              =  dllEvalCoord1dv              ;
         qglEvalCoord1f               =  dllEvalCoord1f               ;
         qglEvalCoord1fv              =  dllEvalCoord1fv              ;
         qglEvalCoord2d               =  dllEvalCoord2d               ;
         qglEvalCoord2dv              =  dllEvalCoord2dv              ;
         qglEvalCoord2f               =  dllEvalCoord2f               ;
         qglEvalCoord2fv              =  dllEvalCoord2fv              ;
         qglEvalMesh1                 =  dllEvalMesh1                 ;
         qglEvalMesh2                 =  dllEvalMesh2                 ;
         qglEvalPoint1                =  dllEvalPoint1                ;
         qglEvalPoint2                =  dllEvalPoint2                ;
         qglFeedbackBuffer            =  dllFeedbackBuffer            ;
         qglFinish                    =  dllFinish                    ;
         qglFlush                     =  dllFlush                     ;
         qglFogf                      =  dllFogf                      ;
         qglFogfv                     =  dllFogfv                     ;
         qglFogi                      =  dllFogi                      ;
         qglFogiv                     =  dllFogiv                     ;
         qglFrontFace                 =  dllFrontFace                 ;
         qglFrustum                   =  dllFrustum                   ;
         qglGenLists                  =  dllGenLists                  ;
         qglGenTextures               =  dllGenTextures               ;
         qglGetBooleanv               =  dllGetBooleanv               ;
         qglGetClipPlane              =  dllGetClipPlane              ;
         qglGetDoublev                =  dllGetDoublev                ;
         qglGetError                  =  dllGetError                  ;
         qglGetFloatv                 =  dllGetFloatv                 ;
         qglGetIntegerv               =  dllGetIntegerv               ;
         qglGetLightfv                =  dllGetLightfv                ;
         qglGetLightiv                =  dllGetLightiv                ;
         qglGetMapdv                  =  dllGetMapdv                  ;
         qglGetMapfv                  =  dllGetMapfv                  ;
         qglGetMapiv                  =  dllGetMapiv                  ;
         qglGetMaterialfv             =  dllGetMaterialfv             ;
         qglGetMaterialiv             =  dllGetMaterialiv             ;
         qglGetPixelMapfv             =  dllGetPixelMapfv             ;
         qglGetPixelMapuiv            =  dllGetPixelMapuiv            ;
         qglGetPixelMapusv            =  dllGetPixelMapusv            ;
         qglGetPointerv               =  dllGetPointerv               ;
         qglGetPolygonStipple         =  dllGetPolygonStipple         ;
         qglGetString                 =  dllGetString                 ;
         qglGetTexEnvfv               =  dllGetTexEnvfv               ;
         qglGetTexEnviv               =  dllGetTexEnviv               ;
         qglGetTexGendv               =  dllGetTexGendv               ;
         qglGetTexGenfv               =  dllGetTexGenfv               ;
         qglGetTexGeniv               =  dllGetTexGeniv               ;
         qglGetTexImage               =  dllGetTexImage               ;
         qglGetTexLevelParameterfv    =  dllGetTexLevelParameterfv    ;
         qglGetTexLevelParameteriv    =  dllGetTexLevelParameteriv    ;
         qglGetTexParameterfv         =  dllGetTexParameterfv         ;
         qglGetTexParameteriv         =  dllGetTexParameteriv         ;
         qglHint                      =  dllHint                      ;
         qglIndexMask                 =  dllIndexMask                 ;
         qglIndexPointer              =  dllIndexPointer              ;
         qglIndexd                    =  dllIndexd                    ;
         qglIndexdv                   =  dllIndexdv                   ;
         qglIndexf                    =  dllIndexf                    ;
         qglIndexfv                   =  dllIndexfv                   ;
         qglIndexi                    =  dllIndexi                    ;
         qglIndexiv                   =  dllIndexiv                   ;
         qglIndexs                    =  dllIndexs                    ;
         qglIndexsv                   =  dllIndexsv                   ;
         qglIndexub                   =  dllIndexub                   ;
         qglIndexubv                  =  dllIndexubv                  ;
         qglInitNames                 =  dllInitNames                 ;
         qglInterleavedArrays         =  dllInterleavedArrays         ;
         qglIsEnabled                 =  dllIsEnabled                 ;
         qglIsList                    =  dllIsList                    ;
         qglIsTexture                 =  dllIsTexture                 ;
         qglLightModelf               =  dllLightModelf               ;
         qglLightModelfv              =  dllLightModelfv              ;
         qglLightModeli               =  dllLightModeli               ;
         qglLightModeliv              =  dllLightModeliv              ;
         qglLightf                    =  dllLightf                    ;
         qglLightfv                   =  dllLightfv                   ;
         qglLighti                    =  dllLighti                    ;
         qglLightiv                   =  dllLightiv                   ;
         qglLineStipple               =  dllLineStipple               ;
         qglLineWidth                 =  dllLineWidth                 ;
         qglListBase                  =  dllListBase                  ;
         qglLoadIdentity              =  dllLoadIdentity              ;
         qglLoadMatrixd               =  dllLoadMatrixd               ;
         qglLoadMatrixf               =  dllLoadMatrixf               ;
         qglLoadName                  =  dllLoadName                  ;
         qglLogicOp                   =  dllLogicOp                   ;
         qglMap1d                     =  dllMap1d                     ;
         qglMap1f                     =  dllMap1f                     ;
         qglMap2d                     =  dllMap2d                     ;
         qglMap2f                     =  dllMap2f                     ;
         qglMapGrid1d                 =  dllMapGrid1d                 ;
         qglMapGrid1f                 =  dllMapGrid1f                 ;
         qglMapGrid2d                 =  dllMapGrid2d                 ;
         qglMapGrid2f                 =  dllMapGrid2f                 ;
         qglMaterialf                 =  dllMaterialf                 ;
         qglMaterialfv                =  dllMaterialfv                ;
         qglMateriali                 =  dllMateriali                 ;
         qglMaterialiv                =  dllMaterialiv                ;
         qglMatrixMode                =  dllMatrixMode                ;
         qglMultMatrixd               =  dllMultMatrixd               ;
         qglMultMatrixf               =  dllMultMatrixf               ;
         qglNewList                   =  dllNewList                   ;
         qglNormal3b                  =  dllNormal3b                  ;
         qglNormal3bv                 =  dllNormal3bv                 ;
         qglNormal3d                  =  dllNormal3d                  ;
         qglNormal3dv                 =  dllNormal3dv                 ;
         qglNormal3f                  =  dllNormal3f                  ;
         qglNormal3fv                 =  dllNormal3fv                 ;
         qglNormal3i                  =  dllNormal3i                  ;
         qglNormal3iv                 =  dllNormal3iv                 ;
         qglNormal3s                  =  dllNormal3s                  ;
         qglNormal3sv                 =  dllNormal3sv                 ;
         qglNormalPointer             =  dllNormalPointer             ;
         qglOrtho                     =  dllOrtho                     ;
         qglPassThrough               =  dllPassThrough               ;
         qglPixelMapfv                =  dllPixelMapfv                ;
         qglPixelMapuiv               =  dllPixelMapuiv               ;
         qglPixelMapusv               =  dllPixelMapusv               ;
         qglPixelStoref               =  dllPixelStoref               ;
         qglPixelStorei               =  dllPixelStorei               ;
         qglPixelTransferf            =  dllPixelTransferf            ;
         qglPixelTransferi            =  dllPixelTransferi            ;
         qglPixelZoom                 =  dllPixelZoom                 ;
         qglPointSize                 =  dllPointSize                 ;
         qglPolygonMode               =  dllPolygonMode               ;
         qglPolygonOffset             =  dllPolygonOffset             ;
         qglPolygonStipple            =  dllPolygonStipple            ;
         qglPopAttrib                 =  dllPopAttrib                 ;
         qglPopClientAttrib           =  dllPopClientAttrib           ;
         qglPopMatrix                 =  dllPopMatrix                 ;
         qglPopName                   =  dllPopName                   ;
         qglPrioritizeTextures        =  dllPrioritizeTextures        ;
         qglPushAttrib                =  dllPushAttrib                ;
         qglPushClientAttrib          =  dllPushClientAttrib          ;
         qglPushMatrix                =  dllPushMatrix                ;
         qglPushName                  =  dllPushName                  ;
         qglRasterPos2d               =  dllRasterPos2d               ;
         qglRasterPos2dv              =  dllRasterPos2dv              ;
         qglRasterPos2f               =  dllRasterPos2f               ;
         qglRasterPos2fv              =  dllRasterPos2fv              ;
         qglRasterPos2i               =  dllRasterPos2i               ;
         qglRasterPos2iv              =  dllRasterPos2iv              ;
         qglRasterPos2s               =  dllRasterPos2s               ;
         qglRasterPos2sv              =  dllRasterPos2sv              ;
         qglRasterPos3d               =  dllRasterPos3d               ;
         qglRasterPos3dv              =  dllRasterPos3dv              ;
         qglRasterPos3f               =  dllRasterPos3f               ;
         qglRasterPos3fv              =  dllRasterPos3fv              ;
         qglRasterPos3i               =  dllRasterPos3i               ;
         qglRasterPos3iv              =  dllRasterPos3iv              ;
         qglRasterPos3s               =  dllRasterPos3s               ;
         qglRasterPos3sv              =  dllRasterPos3sv              ;
         qglRasterPos4d               =  dllRasterPos4d               ;
         qglRasterPos4dv              =  dllRasterPos4dv              ;
         qglRasterPos4f               =  dllRasterPos4f               ;
         qglRasterPos4fv              =  dllRasterPos4fv              ;
         qglRasterPos4i               =  dllRasterPos4i               ;
         qglRasterPos4iv              =  dllRasterPos4iv              ;
         qglRasterPos4s               =  dllRasterPos4s               ;
         qglRasterPos4sv              =  dllRasterPos4sv              ;
         qglReadBuffer                =  dllReadBuffer                ;
         qglReadPixels                =  dllReadPixels                ;
         qglRectd                     =  dllRectd                     ;
         qglRectdv                    =  dllRectdv                    ;
         qglRectf                     =  dllRectf                     ;
         qglRectfv                    =  dllRectfv                    ;
         qglRecti                     =  dllRecti                     ;
         qglRectiv                    =  dllRectiv                    ;
         qglRects                     =  dllRects                     ;
         qglRectsv                    =  dllRectsv                    ;
         qglRenderMode                =  dllRenderMode                ;
         qglRotated                   =  dllRotated                   ;
         qglRotatef                   =  dllRotatef                   ;
         qglScaled                    =  dllScaled                    ;
         qglScalef                    =  dllScalef                    ;
         qglScissor                   =  dllScissor                   ;
         qglSelectBuffer              =  dllSelectBuffer              ;
         qglShadeModel                =  dllShadeModel                ;
         qglStencilFunc               =  dllStencilFunc               ;
         qglStencilMask               =  dllStencilMask               ;
         qglStencilOp                 =  dllStencilOp                 ;
         qglTexCoord1d                =  dllTexCoord1d                ;
         qglTexCoord1dv               =  dllTexCoord1dv               ;
         qglTexCoord1f                =  dllTexCoord1f                ;
         qglTexCoord1fv               =  dllTexCoord1fv               ;
         qglTexCoord1i                =  dllTexCoord1i                ;
         qglTexCoord1iv               =  dllTexCoord1iv               ;
         qglTexCoord1s                =  dllTexCoord1s                ;
         qglTexCoord1sv               =  dllTexCoord1sv               ;
         qglTexCoord2d                =  dllTexCoord2d                ;
         qglTexCoord2dv               =  dllTexCoord2dv               ;
         qglTexCoord2f                =  dllTexCoord2f                ;
         qglTexCoord2fv               =  dllTexCoord2fv               ;
         qglTexCoord2i                =  dllTexCoord2i                ;
         qglTexCoord2iv               =  dllTexCoord2iv               ;
         qglTexCoord2s                =  dllTexCoord2s                ;
         qglTexCoord2sv               =  dllTexCoord2sv               ;
         qglTexCoord3d                =  dllTexCoord3d                ;
         qglTexCoord3dv               =  dllTexCoord3dv               ;
         qglTexCoord3f                =  dllTexCoord3f                ;
         qglTexCoord3fv               =  dllTexCoord3fv               ;
         qglTexCoord3i                =  dllTexCoord3i                ;
         qglTexCoord3iv               =  dllTexCoord3iv               ;
         qglTexCoord3s                =  dllTexCoord3s                ;
         qglTexCoord3sv               =  dllTexCoord3sv               ;
         qglTexCoord4d                =  dllTexCoord4d                ;
         qglTexCoord4dv               =  dllTexCoord4dv               ;
         qglTexCoord4f                =  dllTexCoord4f                ;
         qglTexCoord4fv               =  dllTexCoord4fv               ;
         qglTexCoord4i                =  dllTexCoord4i                ;
         qglTexCoord4iv               =  dllTexCoord4iv               ;
         qglTexCoord4s                =  dllTexCoord4s                ;
         qglTexCoord4sv               =  dllTexCoord4sv               ;
         qglTexCoordPointer           =  dllTexCoordPointer           ;
         qglTexEnvf                   =  dllTexEnvf                   ;
         qglTexEnvfv                  =  dllTexEnvfv                  ;
         qglTexEnvi                   =  dllTexEnvi                   ;
         qglTexEnviv                  =  dllTexEnviv                  ;
         qglTexGend                   =  dllTexGend                   ;
         qglTexGendv                  =  dllTexGendv                  ;
         qglTexGenf                   =  dllTexGenf                   ;
         qglTexGenfv                  =  dllTexGenfv                  ;
         qglTexGeni                   =  dllTexGeni                   ;
         qglTexGeniv                  =  dllTexGeniv                  ;
         qglTexImage1D                =  dllTexImage1D                ;
         qglTexImage2D                =  dllTexImage2D                ;
         qglTexParameterf             =  dllTexParameterf             ;
         qglTexParameterfv            =  dllTexParameterfv            ;
         qglTexParameteri             =  dllTexParameteri             ;
         qglTexParameteriv            =  dllTexParameteriv            ;
         qglTexSubImage1D             =  dllTexSubImage1D             ;
         qglTexSubImage2D             =  dllTexSubImage2D             ;
         qglTranslated                =  dllTranslated                ;
         qglTranslatef                =  dllTranslatef                ;
         qglVertex2d                  =  dllVertex2d                  ;
         qglVertex2dv                 =  dllVertex2dv                 ;
         qglVertex2f                  =  dllVertex2f                  ;
         qglVertex2fv                 =  dllVertex2fv                 ;
         qglVertex2i                  =  dllVertex2i                  ;
         qglVertex2iv                 =  dllVertex2iv                 ;
         qglVertex2s                  =  dllVertex2s                  ;
         qglVertex2sv                 =  dllVertex2sv                 ;
         qglVertex3d                  =  dllVertex3d                  ;
         qglVertex3dv                 =  dllVertex3dv                 ;
         qglVertex3f                  =  dllVertex3f                  ;
         qglVertex3fv                 =  dllVertex3fv                 ;
         qglVertex3i                  =  dllVertex3i                  ;
         qglVertex3iv                 =  dllVertex3iv                 ;
         qglVertex3s                  =  dllVertex3s                  ;
         qglVertex3sv                 =  dllVertex3sv                 ;
         qglVertex4d                  =  dllVertex4d                  ;
         qglVertex4dv                 =  dllVertex4dv                 ;
         qglVertex4f                  =  dllVertex4f                  ;
         qglVertex4fv                 =  dllVertex4fv                 ;
         qglVertex4i                  =  dllVertex4i                  ;
         qglVertex4iv                 =  dllVertex4iv                 ;
         qglVertex4s                  =  dllVertex4s                  ;
         qglVertex4sv                 =  dllVertex4sv                 ;
         qglVertexPointer             =  dllVertexPointer             ;
         qglViewport                  =  dllViewport                  ;
     }
 }
Referenced by R_BeginFrame().
GLimp_EndFrame()
void GLimp_EndFrame (void)
Definition at line 561 of file glw_imp.c.
 {
     int     err;
     err = qglGetError();
     assert( err == GL_NO_ERROR );
     if ( stricmp( gl_drawbuffer->string, "GL_BACK" ) == 0 )
     {
         if ( !qwglSwapBuffers( glw_state.hDC ) )
             ri.Sys_Error( ERR_FATAL, "GLimp_EndFrame() - SwapBuffers() failed!\n" );
     }
 }
Referenced by GetRefAPI(), and GL_DrawStereoPattern().
GLimp_Init()
qboolean GLimp_Init (void * hinstance, void * hWnd)
Definition at line 321 of file glw_imp.c.
 {
 #define OSR2_BUILD_NUMBER 1111
     OSVERSIONINFO   vinfo;
     vinfo.dwOSVersionInfoSize = sizeof(vinfo);
     glw_state.allowdisplaydepthchange = false;
     if ( GetVersionEx( &vinfo) )
     {
         if ( vinfo.dwMajorVersion > 4 )
         {
             glw_state.allowdisplaydepthchange = true;
         }
         else if ( vinfo.dwMajorVersion == 4 )
         {
             if ( vinfo.dwPlatformId == VER_PLATFORM_WIN32_NT )
             {
                 glw_state.allowdisplaydepthchange = true;
             }
             else if ( vinfo.dwPlatformId == VER_PLATFORM_WIN32_WINDOWS )
             {
                 if ( LOWORD( vinfo.dwBuildNumber ) >= OSR2_BUILD_NUMBER )
                 {
                     glw_state.allowdisplaydepthchange = true;
                 }
             }
         }
     }
     else
     {
         ri.Con_Printf( PRINT_ALL, "GLimp_Init() - GetVersionEx failed\n" );
         return false;
     }
     glw_state.hInstance = ( HINSTANCE ) hinstance;
     glw_state.wndproc = wndproc;
     return true;
 }
Referenced by R_Init().
GLimp_LogNewFrame()
void GLimp_LogNewFrame (void)
Definition at line 4127 of file qgl_win.c.
 {
     fprintf( glw_state.log_fp, "*** R_BeginFrame ***\n" );
 }
Referenced by R_BeginFrame().
GLimp_SetMode()
rserr_t GLimp_SetMode (int * pwidth, int * pheight, int mode, qboolean fullscreen)
Definition at line 185 of file glw_imp.c.
 {
     int width, height;
     const char *win_fs[] = { "W", "FS" };
     ri.Con_Printf( PRINT_ALL, "Initializing OpenGL display\n");
     ri.Con_Printf (PRINT_ALL, "...setting mode %d:", mode );
     if ( !ri.Vid_GetModeInfo( &width, &height, mode ) )
     {
         ri.Con_Printf( PRINT_ALL, " invalid mode\n" );
         return rserr_invalid_mode;
     }
     ri.Con_Printf( PRINT_ALL, " %d %d %s\n", width, height, win_fs[fullscreen] );
     // destroy the existing window
     if (glw_state.hWnd)
     {
         GLimp_Shutdown ();
     }
     // do a CDS if needed
     if ( fullscreen )
     {
         ri.Con_Printf( PRINT_ALL, "...attempting fullscreen\n" );
         if ( gl_bitdepth->value != 0 )
         {
             ri.Con_Printf( PRINT_ALL, "...using gl_bitdepth of %d\n", ( int ) gl_bitdepth->value );
         }
         else
         {
             HDC hdc = GetDC( NULL );
             int bitspixel = GetDeviceCaps( hdc, BITSPIXEL );
             ri.Con_Printf( PRINT_ALL, "...using desktop display depth of %d\n", bitspixel );
             ReleaseDC( 0, hdc );
         }
         ri.Con_Printf( PRINT_ALL, "...calling CDS: " );
         if ( VID_CreateWindow(width, height, true) )
         {
             *pwidth = width;
             *pheight = height;
             gl_state.fullscreen = true;
             ri.Con_Printf( PRINT_ALL, "ok\n" );
             return rserr_ok;
         }
         else
         {
             ri.Con_Printf( PRINT_ALL, " failed\n" );
             ri.Con_Printf( PRINT_ALL, "...setting windowed mode\n" );
             DestroyWindow(glw_state.hWnd);
             UnregisterClass(WINDOW_CLASS_NAME, glw_state.hInstance);
             VID_CreateWindow(width, height, false);
             *pwidth = width;
             *pheight = height;
             gl_state.fullscreen = false;
             return rserr_invalid_fullscreen;
         }
     }
     else
     {
         ri.Con_Printf( PRINT_ALL, "...setting windowed mode\n" );
         *pwidth = width;
         *pheight = height;
         gl_state.fullscreen = false;
         if ( !VID_CreateWindow (width, height, false) )
             return rserr_invalid_mode;
     }
     return rserr_ok;
 }
Referenced by R_SetMode().
GLimp_Shutdown()
void GLimp_Shutdown (void)
Definition at line 276 of file glw_imp.c.
 {
     if ( qwglMakeCurrent && !qwglMakeCurrent( NULL, NULL ) )
         ri.Con_Printf( PRINT_ALL, "ref_gl::R_Shutdown() - wglMakeCurrent failed\n");
     if ( glw_state.hGLRC )
     {
         if (  qwglDeleteContext && !qwglDeleteContext( glw_state.hGLRC ) )
             ri.Con_Printf( PRINT_ALL, "ref_gl::R_Shutdown() - wglDeleteContext failed\n");
         glw_state.hGLRC = NULL;
     }
     if (glw_state.hDC)
     {
         if ( !ReleaseDC( glw_state.hWnd, glw_state.hDC ) )
             ri.Con_Printf( PRINT_ALL, "ref_gl::R_Shutdown() - ReleaseDC failed\n" );
         glw_state.hDC   = NULL;
     }
     if (glw_state.hWnd)
     {
         DestroyWindow ( glw_state.hWnd );
         glw_state.hWnd = NULL;
     }
     if ( glw_state.log_fp )
     {
         fclose( glw_state.log_fp );
         glw_state.log_fp = 0;
     }
     UnregisterClass (WINDOW_CLASS_NAME, glw_state.hInstance);
     if ( gl_state.fullscreen )
     {
         ChangeDisplaySettingsEx( glw_state.monInfo.szDevice, NULL, NULL, 0, NULL );
         gl_state.fullscreen = false;
     }
 }
Referenced by GLimp_SetMode(), and R_Shutdown().
LoadPCX()
void LoadPCX (char * filename, byte ** pic, byte ** palette, int * width, int * height)
Definition at line 87 of file r_image.c.
 {
     byte    *raw;
     pcx_t   *pcx;
     int     x, y;
     int     len;
     int     dataByte, runLength;
     byte    *out, *pix;
     *pic = NULL;
     //
     // load the file
     //
     len = ri.FS_LoadFile (filename, (void **)&raw);
     if (!raw)
     {
         ri.Con_Printf (PRINT_DEVELOPER, "Bad pcx file %s\n", filename);
         return;
     }
     //
     // parse the PCX file
     //
     pcx = (pcx_t *)raw;
     pcx->xmin = LittleShort(pcx->xmin);
     pcx->ymin = LittleShort(pcx->ymin);
     pcx->xmax = LittleShort(pcx->xmax);
     pcx->ymax = LittleShort(pcx->ymax);
     pcx->hres = LittleShort(pcx->hres);
     pcx->vres = LittleShort(pcx->vres);
     pcx->bytes_per_line = LittleShort(pcx->bytes_per_line);
     pcx->palette_type = LittleShort(pcx->palette_type);
     raw = &pcx->data;
     if (pcx->manufacturer != 0x0a
         || pcx->version != 5
         || pcx->encoding != 1
         || pcx->bits_per_pixel != 8
         || pcx->xmax >= 640
         || pcx->ymax >= 480)
     {
         ri.Con_Printf (PRINT_ALL, "Bad pcx file %s\n", filename);
         return;
     }
     out = malloc ( (pcx->ymax+1) * (pcx->xmax+1) );
     *pic = out;
     pix = out;
     if (palette)
     {
         *palette = malloc(768);
         memcpy (*palette, (byte *)pcx + len - 768, 768);
     }
     if (width)
         *width = pcx->xmax+1;
     if (height)
         *height = pcx->ymax+1;
     for (y=0 ; y<=pcx->ymax ; y++, pix += pcx->xmax+1)
     {
         for (x=0 ; x<=pcx->xmax ; )
         {
             dataByte = *raw++;
             if((dataByte & 0xC0) == 0xC0)
             {
                 runLength = dataByte & 0x3F;
                 dataByte = *raw++;
             }
             else
                 runLength = 1;
             while(runLength-- > 0)
                 pix[x++] = dataByte;
         }
     }
     if ( raw - (byte *)pcx > len)
     {
         ri.Con_Printf (PRINT_DEVELOPER, "PCX file %s was malformed", filename);
         free (*pic);
         *pic = NULL;
     }
     ri.FS_FreeFile (pcx);
 }
R_AddSkySurface()
void R_AddSkySurface (msurface_t * fa)
Definition at line 485 of file gl_warp.c.
 {
     int         i;
     vec3_t      verts[MAX_CLIP_VERTS];
     glpoly_t    *p;
     // calculate vertex values for sky box
     for (p=fa->polys ; p ; p=p->next)
     {
         for (i=0 ; i<p->numverts ; i++)
         {
             VectorSubtract (p->verts[i], r_origin, verts[i]);
         }
         ClipSkyPolygon (p->numverts, verts[0], 0);
     }
 }
Referenced by R_RecursiveWorldNode().
R_BeginFrame()
void R_BeginFrame (float camera_separation)
Definition at line 1177 of file r_main.c.
 {
     extern void Draw_BuildGammaTable(void);
 #ifdef REDBLUE
     SetStereoBuffer((camera_separation <= 0.0) ? 0 : 1);
 #endif
     /*
     ** rebuild the gamma correction palette if necessary
     */
     if (vid_gamma->modified)
     {
         Draw_BuildGammaTable();
         R_GammaCorrectAndSetPalette((const unsigned char *)d_8to24table);
         vid_gamma->modified = false;
     }
     while (sw_mode->modified || vid_fullscreen->modified)
     {
         rserr_t err;
         /* a bit hackish approach to enable custom resolutions:
         * SWimp_SetMode needs these values set for mode -1 */
         vid.width = r_customwidth->value;
         vid.height = r_customheight->value;
         /*
         ** if this returns rserr_invalid_fullscreen then it set the mode but not as a
         ** fullscreen mode, e.g. 320x200 on a system that doesn't support that res
         */
         if ((err = SWimp_SetMode(&vid.width, &vid.height, sw_mode->value, vid_fullscreen->value > 0)) == rserr_ok)
         {
             R_InitGraphics(vid.width, vid.height);
             if (sw_mode->value == -1)
             {
                 sw_state.prev_mode = 4; /* safe default for custom mode */
             }
             else
             {
                 sw_state.prev_mode = sw_mode->value;
             }
             vid_fullscreen->modified = false;
             sw_mode->modified = false;
         }
         else
         {
             if (err == rserr_invalid_mode)
             {
                 ri.Cvar_SetValue("sw_mode", sw_state.prev_mode);
                 ri.Con_Printf(PRINT_ALL, "ref_soft::R_BeginFrame() - could not set mode\n");
             }
             else if (err == rserr_invalid_fullscreen)
             {
                 R_InitGraphics(vid.width, vid.height);
                 ri.Con_Printf(PRINT_ALL, "ref_soft::R_BeginFrame() - fullscreen unavailable in this mode\n");
                 sw_state.prev_mode = sw_mode->value;
                 //              vid_fullscreen->modified = false;
                 //              sw_mode->modified = false;
             }
             else
             {
                 ri.Sys_Error(ERR_FATAL, "ref_soft::R_BeginFrame() - catastrophic mode change failure\n");
             }
         }
     }
 }
R_ClearSkyBox()
void R_ClearSkyBox (void)
Definition at line 508 of file gl_warp.c.
 {
     int     i;
     for (i=0 ; i<6 ; i++)
     {
         skymins[0][i] = skymins[1][i] = 9999;
         skymaxs[0][i] = skymaxs[1][i] = -9999;
     }
 }
Referenced by R_DrawWorld().
R_CullBox()
qboolean R_CullBox (vec3_t mins, vec3_t maxs)
Definition at line 151 of file gl_rmain.c.
 {
     int     i;
     if (r_nocull->value)
         return false;
     for (i=0 ; i<4 ; i++)
         if ( BOX_ON_PLANE_SIDE(mins, maxs, &frustum[i]) == 2)
             return true;
     return false;
 }
Referenced by R_DrawBrushModel(), and R_RecursiveWorldNode().
R_DrawAliasModel()
void R_DrawAliasModel (entity_t * e)
Definition at line 519 of file gl_mesh.c.
 {
     int         i;
     dmdl_t      *paliashdr;
     float       an;
     vec3_t      bbox[8];
     image_t     *skin;
     if ( !( e->flags & RF_WEAPONMODEL ) )
     {
         if ( R_CullAliasModel( bbox, e ) )
             return;
     }
     if ( e->flags & RF_WEAPONMODEL )
     {
         if ( r_lefthand->value == 2 )
             return;
     }
     paliashdr = (dmdl_t *)currentmodel->extradata;
     //
     // get lighting information
     //
     // PMM - rewrote, reordered to handle new shells & mixing
     // PMM - 3.20 code .. replaced with original way of doing it to keep mod authors happy
     //
     if ( currententity->flags & ( RF_SHELL_HALF_DAM | RF_SHELL_GREEN | RF_SHELL_RED | RF_SHELL_BLUE | RF_SHELL_DOUBLE ) )
     {
         VectorClear (shadelight);
         if (currententity->flags & RF_SHELL_HALF_DAM)
         {
                 shadelight[0] = 0.56;
                 shadelight[1] = 0.59;
                 shadelight[2] = 0.45;
         }
         if ( currententity->flags & RF_SHELL_DOUBLE )
         {
             shadelight[0] = 0.9;
             shadelight[1] = 0.7;
         }
         if ( currententity->flags & RF_SHELL_RED )
             shadelight[0] = 1.0;
         if ( currententity->flags & RF_SHELL_GREEN )
             shadelight[1] = 1.0;
         if ( currententity->flags & RF_SHELL_BLUE )
             shadelight[2] = 1.0;
     }
 /*
         // PMM -special case for godmode
         if ( (currententity->flags & RF_SHELL_RED) &&
             (currententity->flags & RF_SHELL_BLUE) &&
             (currententity->flags & RF_SHELL_GREEN) )
         {
             for (i=0 ; i<3 ; i++)
                 shadelight[i] = 1.0;
         }
         else if ( currententity->flags & ( RF_SHELL_RED | RF_SHELL_BLUE | RF_SHELL_DOUBLE ) )
         {
             VectorClear (shadelight);
             if ( currententity->flags & RF_SHELL_RED )
             {
                 shadelight[0] = 1.0;
                 if (currententity->flags & (RF_SHELL_BLUE|RF_SHELL_DOUBLE) )
                     shadelight[2] = 1.0;
             }
             else if ( currententity->flags & RF_SHELL_BLUE )
             {
                 if ( currententity->flags & RF_SHELL_DOUBLE )
                 {
                     shadelight[1] = 1.0;
                     shadelight[2] = 1.0;
                 }
                 else
                 {
                     shadelight[2] = 1.0;
                 }
             }
             else if ( currententity->flags & RF_SHELL_DOUBLE )
             {
                 shadelight[0] = 0.9;
                 shadelight[1] = 0.7;
             }
         }
         else if ( currententity->flags & ( RF_SHELL_HALF_DAM | RF_SHELL_GREEN ) )
         {
             VectorClear (shadelight);
             // PMM - new colors
             if ( currententity->flags & RF_SHELL_HALF_DAM )
             {
                 shadelight[0] = 0.56;
                 shadelight[1] = 0.59;
                 shadelight[2] = 0.45;
             }
             if ( currententity->flags & RF_SHELL_GREEN )
             {
                 shadelight[1] = 1.0;
             }
         }
     }
             //PMM - ok, now flatten these down to range from 0 to 1.0.
     //      max_shell_val = max(shadelight[0], max(shadelight[1], shadelight[2]));
     //      if (max_shell_val > 0)
     //      {
     //          for (i=0; i<3; i++)
     //          {
     //              shadelight[i] = shadelight[i] / max_shell_val;
     //          }
     //      }
     // pmm
 */
     else if ( currententity->flags & RF_FULLBRIGHT )
     {
         for (i=0 ; i<3 ; i++)
             shadelight[i] = 1.0;
     }
     else
     {
         R_LightPoint (currententity->origin, shadelight);
         // player lighting hack for communication back to server
         // big hack!
         if ( currententity->flags & RF_WEAPONMODEL )
         {
             // pick the greatest component, which should be the same
             // as the mono value returned by software
             if (shadelight[0] > shadelight[1])
             {
                 if (shadelight[0] > shadelight[2])
                     r_lightlevel->value = 150*shadelight[0];
                 else
                     r_lightlevel->value = 150*shadelight[2];
             }
             else
             {
                 if (shadelight[1] > shadelight[2])
                     r_lightlevel->value = 150*shadelight[1];
                 else
                     r_lightlevel->value = 150*shadelight[2];
             }
         }
         if ( gl_monolightmap->string[0] != '0' )
         {
             float s = shadelight[0];
             if ( s < shadelight[1] )
                 s = shadelight[1];
             if ( s < shadelight[2] )
                 s = shadelight[2];
             shadelight[0] = s;
             shadelight[1] = s;
             shadelight[2] = s;
         }
     }
     if ( currententity->flags & RF_MINLIGHT )
     {
         for (i=0 ; i<3 ; i++)
             if (shadelight[i] > 0.1)
                 break;
         if (i == 3)
         {
             shadelight[0] = 0.1;
             shadelight[1] = 0.1;
             shadelight[2] = 0.1;
         }
     }
     if ( currententity->flags & RF_GLOW )
     {   // bonus items will pulse with time
         float   scale;
         float   min;
         scale = 0.1 * sin(r_newrefdef.time*7);
         for (i=0 ; i<3 ; i++)
         {
             min = shadelight[i] * 0.8;
             shadelight[i] += scale;
             if (shadelight[i] < min)
                 shadelight[i] = min;
         }
     }
 // =================
 // PGM  ir goggles color override
     if ( r_newrefdef.rdflags & RDF_IRGOGGLES && currententity->flags & RF_IR_VISIBLE)
     {
         shadelight[0] = 1.0;
         shadelight[1] = 0.0;
         shadelight[2] = 0.0;
     }
 // PGM
 // =================
     shadedots = r_avertexnormal_dots[((int)(currententity->angles[1] * (SHADEDOT_QUANT / 360.0))) & (SHADEDOT_QUANT - 1)];
     an = currententity->angles[1]/180*M_PI;
     shadevector[0] = cos(-an);
     shadevector[1] = sin(-an);
     shadevector[2] = 1;
     VectorNormalize (shadevector);
     //
     // locate the proper data
     //
     c_alias_polys += paliashdr->num_tris;
     //
     // draw all the triangles
     //
     if (currententity->flags & RF_DEPTHHACK) // hack the depth range to prevent view model from poking into walls
         qglDepthRange (gldepthmin, gldepthmin + 0.3*(gldepthmax-gldepthmin));
     if ( ( currententity->flags & RF_WEAPONMODEL ) && ( r_lefthand->value == 1.0F ) )
     {
         extern void MYgluPerspective( GLdouble fovy, GLdouble aspect, GLdouble zNear, GLdouble zFar );
         qglMatrixMode( GL_PROJECTION );
         qglPushMatrix();
         qglLoadIdentity();
         qglScalef( -1, 1, 1 );
         MYgluPerspective( r_newrefdef.fov_y, ( float ) r_newrefdef.width / r_newrefdef.height,  4,  4096);
         qglMatrixMode( GL_MODELVIEW );
         qglCullFace( GL_BACK );
     }
     qglPushMatrix ();
     e->angles[PITCH] = -e->angles[PITCH];   // sigh.
     R_RotateForEntity (e);
     e->angles[PITCH] = -e->angles[PITCH];   // sigh.
     // select skin
     if (currententity->skin)
         skin = currententity->skin; // custom player skin
     else
     {
         if (currententity->skinnum >= MAX_MD2SKINS)
             skin = currentmodel->skins[0];
         else
         {
             skin = currentmodel->skins[currententity->skinnum];
             if (!skin)
                 skin = currentmodel->skins[0];
         }
     }
     if (!skin)
         skin = r_notexture; // fallback...
     GL_Bind(skin->texnum);
     // draw it
     qglShadeModel (GL_SMOOTH);
     GL_TexEnv( GL_MODULATE );
     if ( currententity->flags & RF_TRANSLUCENT )
     {
         qglEnable (GL_BLEND);
     }
     if ( (currententity->frame >= paliashdr->num_frames)
         || (currententity->frame < 0) )
     {
         ri.Con_Printf (PRINT_ALL, "R_DrawAliasModel %s: no such frame %d\n",
             currentmodel->name, currententity->frame);
         currententity->frame = 0;
         currententity->oldframe = 0;
     }
     if ( (currententity->oldframe >= paliashdr->num_frames)
         || (currententity->oldframe < 0))
     {
         ri.Con_Printf (PRINT_ALL, "R_DrawAliasModel %s: no such oldframe %d\n",
             currentmodel->name, currententity->oldframe);
         currententity->frame = 0;
         currententity->oldframe = 0;
     }
     if ( !r_lerpmodels->value )
         currententity->backlerp = 0;
     GL_DrawAliasFrameLerp (paliashdr, currententity->backlerp);
     GL_TexEnv( GL_REPLACE );
     qglShadeModel (GL_FLAT);
     qglPopMatrix ();
 #if 0
     qglDisable( GL_CULL_FACE );
     qglPolygonMode( GL_FRONT_AND_BACK, GL_LINE );
     qglDisable( GL_TEXTURE_2D );
     qglBegin( GL_TRIANGLE_STRIP );
     for ( i = 0; i < 8; i++ )
     {
         qglVertex3fv( bbox[i] );
     }
     qglEnd();
     qglEnable( GL_TEXTURE_2D );
     qglPolygonMode( GL_FRONT_AND_BACK, GL_FILL );
     qglEnable( GL_CULL_FACE );
 #endif
     if ( ( currententity->flags & RF_WEAPONMODEL ) && ( r_lefthand->value == 1.0F ) )
     {
         qglMatrixMode( GL_PROJECTION );
         qglPopMatrix();
         qglMatrixMode( GL_MODELVIEW );
         qglCullFace( GL_FRONT );
     }
     if ( currententity->flags & RF_TRANSLUCENT )
     {
         qglDisable (GL_BLEND);
     }
     if (currententity->flags & RF_DEPTHHACK)
         qglDepthRange (gldepthmin, gldepthmax);
 #if 1
     if (gl_shadows->value && !(currententity->flags & (RF_TRANSLUCENT | RF_WEAPONMODEL)))
     {
         qglPushMatrix ();
         R_RotateForEntity (e);
         qglDisable (GL_TEXTURE_2D);
         qglEnable (GL_BLEND);
         qglColor4f (0,0,0,0.5);
         GL_DrawAliasShadow (paliashdr, currententity->frame );
         qglEnable (GL_TEXTURE_2D);
         qglDisable (GL_BLEND);
         qglPopMatrix ();
     }
 #endif
     qglColor4f (1,1,1,1);
 }
Referenced by R_DrawEntitiesOnList().
R_DrawAlphaSurfaces()
void R_DrawAlphaSurfaces (void)
Definition at line 1342 of file r_poly.c.
 {
     msurface_t *s = r_alpha_surfaces;
     currentmodel = r_worldmodel;
     modelorg[0] = -r_origin[0];
     modelorg[1] = -r_origin[1];
     modelorg[2] = -r_origin[2];
     while (s)
     {
         R_BuildPolygonFromSurface(s);
         //=======
         //PGM
         //      if (s->texinfo->flags & SURF_TRANS66)
         //          R_ClipAndDrawPoly( 0.60f, ( s->texinfo->flags & SURF_WARP) != 0, true );
         //      else
         //          R_ClipAndDrawPoly( 0.30f, ( s->texinfo->flags & SURF_WARP) != 0, true );
         // PGM - pass down all the texinfo flags, not just SURF_WARP.
         if (s->texinfo->flags & SURF_TRANS66)
             R_ClipAndDrawPoly(0.60f, (s->texinfo->flags & (SURF_WARP | SURF_FLOWING)), true);
         else
             R_ClipAndDrawPoly(0.30f, (s->texinfo->flags & (SURF_WARP | SURF_FLOWING)), true);
         //PGM
         //=======
         s = s->nextalphasurface;
     }
     r_alpha_surfaces = NULL;
 }
R_DrawBeam()
void R_DrawBeam (entity_t * e)
Definition at line 1342 of file r_main.c.
 {
 #define NUM_BEAM_SEGS 6
     int i;
     vec3_t perpvec;
     vec3_t direction, normalized_direction;
     vec3_t start_points[NUM_BEAM_SEGS], end_points[NUM_BEAM_SEGS];
     vec3_t oldorigin, origin;
     oldorigin[0] = e->oldorigin[0];
     oldorigin[1] = e->oldorigin[1];
     oldorigin[2] = e->oldorigin[2];
     origin[0] = e->origin[0];
     origin[1] = e->origin[1];
     origin[2] = e->origin[2];
     normalized_direction[0] = direction[0] = oldorigin[0] - origin[0];
     normalized_direction[1] = direction[1] = oldorigin[1] - origin[1];
     normalized_direction[2] = direction[2] = oldorigin[2] - origin[2];
     if (VectorNormalize(normalized_direction) == 0)
         return;
     PerpendicularVector(perpvec, normalized_direction);
     VectorScale(perpvec, e->frame / 2, perpvec);
     for (i = 0; i < NUM_BEAM_SEGS; i++)
     {
         RotatePointAroundVector(start_points[i], normalized_direction, perpvec, (360.0 / NUM_BEAM_SEGS)*i);
         VectorAdd(start_points[i], origin, start_points[i]);
         VectorAdd(start_points[i], direction, end_points[i]);
     }
     for (i = 0; i < NUM_BEAM_SEGS; i++)
     {
         R_IMFlatShadedQuad(start_points[i],
             end_points[i],
             end_points[(i + 1) % NUM_BEAM_SEGS],
             start_points[(i + 1) % NUM_BEAM_SEGS],
             e->skinnum & 0xFF,
             e->alpha);
     }
 }
R_DrawBrushModel()
void R_DrawBrushModel (entity_t * e)
Definition at line 957 of file gl_rsurf.c.
 {
     vec3_t      mins, maxs;
     int         i;
     qboolean    rotated;
     if (currentmodel->nummodelsurfaces == 0)
         return;
     currententity = e;
     gl_state.currenttextures[0] = gl_state.currenttextures[1] = -1;
     if (e->angles[0] || e->angles[1] || e->angles[2])
     {
         rotated = true;
         for (i=0 ; i<3 ; i++)
         {
             mins[i] = e->origin[i] - currentmodel->radius;
             maxs[i] = e->origin[i] + currentmodel->radius;
         }
     }
     else
     {
         rotated = false;
         VectorAdd (e->origin, currentmodel->mins, mins);
         VectorAdd (e->origin, currentmodel->maxs, maxs);
     }
     if (R_CullBox (mins, maxs))
         return;
     qglColor3f (1,1,1);
     memset (gl_lms.lightmap_surfaces, 0, sizeof(gl_lms.lightmap_surfaces));
     VectorSubtract (r_newrefdef.vieworg, e->origin, modelorg);
     if (rotated)
     {
         vec3_t  temp;
         vec3_t  forward, right, up;
         VectorCopy (modelorg, temp);
         AngleVectors (e->angles, forward, right, up);
         modelorg[0] = DotProduct (temp, forward);
         modelorg[1] = -DotProduct (temp, right);
         modelorg[2] = DotProduct (temp, up);
     }
     qglPushMatrix ();
 e->angles[0] = -e->angles[0];   // stupid quake bug
 e->angles[2] = -e->angles[2];   // stupid quake bug
     R_RotateForEntity (e);
 e->angles[0] = -e->angles[0];   // stupid quake bug
 e->angles[2] = -e->angles[2];   // stupid quake bug
     GL_EnableMultitexture( true );
     GL_SelectTexture( gl_texture0);
     GL_TexEnv( GL_REPLACE );
     GL_SelectTexture( gl_texture1);
     GL_TexEnv( GL_MODULATE );
     R_DrawInlineBModel ();
     GL_EnableMultitexture( false );
     qglPopMatrix ();
 }
Referenced by R_DrawEntitiesOnList().
R_DrawSkyBox()
void R_DrawSkyBox (void)
Definition at line 562 of file gl_warp.c.
 {
     int     i;
 #if 0
 qglEnable (GL_BLEND);
 GL_TexEnv( GL_MODULATE );
 qglColor4f (1,1,1,0.5);
 qglDisable (GL_DEPTH_TEST);
 #endif
     if (skyrotate)
     {   // check for no sky at all
         for (i=0 ; i<6 ; i++)
             if (skymins[0][i] < skymaxs[0][i]
             && skymins[1][i] < skymaxs[1][i])
                 break;
         if (i == 6)
             return;     // nothing visible
     }
 qglPushMatrix ();
 qglTranslatef (r_origin[0], r_origin[1], r_origin[2]);
 qglRotatef (r_newrefdef.time * skyrotate, skyaxis[0], skyaxis[1], skyaxis[2]);
     for (i=0 ; i<6 ; i++)
     {
         if (skyrotate)
         {   // hack, forces full sky to draw when rotating
             skymins[0][i] = -1;
             skymins[1][i] = -1;
             skymaxs[0][i] = 1;
             skymaxs[1][i] = 1;
         }
         if (skymins[0][i] >= skymaxs[0][i]
         || skymins[1][i] >= skymaxs[1][i])
             continue;
         GL_Bind (sky_images[skytexorder[i]]->texnum);
         qglBegin (GL_QUADS);
         MakeSkyVec (skymins[0][i], skymins[1][i], i);
         MakeSkyVec (skymins[0][i], skymaxs[1][i], i);
         MakeSkyVec (skymaxs[0][i], skymaxs[1][i], i);
         MakeSkyVec (skymaxs[0][i], skymins[1][i], i);
         qglEnd ();
     }
 qglPopMatrix ();
 #if 0
 glDisable (GL_BLEND);
 glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE);
 glColor4f (1,1,1,0.5);
 glEnable (GL_DEPTH_TEST);
 #endif
 }
Referenced by R_DrawWorld().
R_DrawSpriteModel()
void R_DrawSpriteModel (entity_t * e)
Definition at line 189 of file gl_rmain.c.
 {
     float alpha = 1.0F;
     vec3_t  point;
     dsprframe_t *frame;
     float       *up, *right;
     dsprite_t       *psprite;
     // don't even bother culling, because it's just a single
     // polygon without a surface cache
     psprite = (dsprite_t *)currentmodel->extradata;
 #if 0
     if (e->frame < 0 || e->frame >= psprite->numframes)
     {
         ri.Con_Printf (PRINT_ALL, "no such sprite frame %i\n", e->frame);
         e->frame = 0;
     }
 #endif
     e->frame %= psprite->numframes;
     frame = &psprite->frames[e->frame];
 #if 0
     if (psprite->type == SPR_ORIENTED)
     {   // bullet marks on walls
     vec3_t      v_forward, v_right, v_up;
     AngleVectors (currententity->angles, v_forward, v_right, v_up);
         up = v_up;
         right = v_right;
     }
     else
 #endif
     {   // normal sprite
         up = vup;
         right = vright;
     }
     if ( e->flags & RF_TRANSLUCENT )
         alpha = e->alpha;
     if ( alpha != 1.0F )
         qglEnable( GL_BLEND );
     qglColor4f( 1, 1, 1, alpha );
     GL_Bind(currentmodel->skins[e->frame]->texnum);
     GL_TexEnv( GL_MODULATE );
     if ( alpha == 1.0 )
         qglEnable (GL_ALPHA_TEST);
     else
         qglDisable( GL_ALPHA_TEST );
     qglBegin (GL_QUADS);
     qglTexCoord2f (0, 1);
     VectorMA (e->origin, -frame->origin_y, up, point);
     VectorMA (point, -frame->origin_x, right, point);
     qglVertex3fv (point);
     qglTexCoord2f (0, 0);
     VectorMA (e->origin, frame->height - frame->origin_y, up, point);
     VectorMA (point, -frame->origin_x, right, point);
     qglVertex3fv (point);
     qglTexCoord2f (1, 0);
     VectorMA (e->origin, frame->height - frame->origin_y, up, point);
     VectorMA (point, frame->width - frame->origin_x, right, point);
     qglVertex3fv (point);
     qglTexCoord2f (1, 1);
     VectorMA (e->origin, -frame->origin_y, up, point);
     VectorMA (point, frame->width - frame->origin_x, right, point);
     qglVertex3fv (point);
     qglEnd ();
     qglDisable (GL_ALPHA_TEST);
     GL_TexEnv( GL_REPLACE );
     if ( alpha != 1.0F )
         qglDisable( GL_BLEND );
     qglColor4f( 1, 1, 1, 1 );
 }
R_DrawWorld()
void R_DrawWorld (void)
Definition at line 1197 of file gl_rsurf.c.
 {
     entity_t    ent;
     if (!r_drawworld->value)
         return;
     if ( r_newrefdef.rdflags & RDF_NOWORLDMODEL )
         return;
     currentmodel = r_worldmodel;
     VectorCopy (r_newrefdef.vieworg, modelorg);
     // auto cycle the world frame for texture animation
     memset (&ent, 0, sizeof(ent));
     ent.frame = (int)(r_newrefdef.time*2);
     currententity = &ent;
     gl_state.currenttextures[0] = gl_state.currenttextures[1] = -1;
     qglColor3f (1,1,1);
     memset (gl_lms.lightmap_surfaces, 0, sizeof(gl_lms.lightmap_surfaces));
     R_ClearSkyBox ();
     if ( qglMTexCoord2fSGIS )
     {
         GL_EnableMultitexture( true );
         GL_SelectTexture( gl_texture0);
         GL_TexEnv( GL_REPLACE );
         GL_SelectTexture( gl_texture1);
         if ( gl_lightmap->value )
             GL_TexEnv( GL_REPLACE );
         else
             GL_TexEnv( GL_MODULATE );
         R_RecursiveWorldNode (r_worldmodel->nodes);
         GL_EnableMultitexture( false );
     }
     else
     {
         R_RecursiveWorldNode (r_worldmodel->nodes);
     }
     /*
     ** theoretically nothing should happen in the next two functions
     ** if multitexture is enabled
     */
     DrawTextureChains ();
     R_BlendLightmaps ();
     R_DrawSkyBox ();
     R_DrawTriangleOutlines ();
 }
Referenced by R_RenderView().
R_Init()
qboolean R_Init (void * hinstance, void * hWnd)
Definition at line 326 of file r_main.c.
 {
     R_InitImages();
     Mod_Init();
     Draw_InitLocal();
     R_InitTextures();
     R_InitTurb();
     view_clipplanes[0].leftedge = true;
     view_clipplanes[1].rightedge = true;
     view_clipplanes[1].leftedge = view_clipplanes[2].leftedge =
         view_clipplanes[3].leftedge = false;
     view_clipplanes[0].rightedge = view_clipplanes[2].rightedge =
         view_clipplanes[3].rightedge = false;
     r_refdef.xOrigin = XCENTERING;
     r_refdef.yOrigin = YCENTERING;
     // TODO: collect 386-specific code in one place
 #if id386
     Sys_MakeCodeWriteable((long)R_EdgeCodeStart,
         (long)R_EdgeCodeEnd - (long)R_EdgeCodeStart);
     Sys_SetFPCW();      // get bit masks for FPCW   (FIXME: is this id386?)
 #endif  // id386
     r_aliasuvscale = 1.0;
     R_Register();
     Draw_GetPalette();
     Draw_InitRGBMap();      // leilei - colored lights
     if (SWimp_Init(hInstance, wndProc) == false)
         return -1;
     // create the window
     R_BeginFrame(0);
     ri.Con_Printf(PRINT_ALL, "ref_soft version: "REF_VERSION"\n");
     return true;
 }
R_InitParticleTexture()
void R_InitParticleTexture (void)
Definition at line 41 of file gl_rmisc.c.
 {
     int     x,y;
     byte    data[8][8][4];
     //
     // particle texture
     //
     for (x=0 ; x<8 ; x++)
     {
         for (y=0 ; y<8 ; y++)
         {
             data[y][x][0] = 255;
             data[y][x][1] = 255;
             data[y][x][2] = 255;
             data[y][x][3] = dottexture[x][y]*255;
         }
     }
     r_particletexture = GL_LoadPic ("***particle***", (byte *)data, 8, 8, it_sprite, 32);
     //
     // also use this for bad textures, but without alpha
     //
     for (x=0 ; x<8 ; x++)
     {
         for (y=0 ; y<8 ; y++)
         {
             data[y][x][0] = dottexture[x&3][y&3]*255;
             data[y][x][1] = 0; // dottexture[x&3][y&3]*255;
             data[y][x][2] = 0; //dottexture[x&3][y&3]*255;
             data[y][x][3] = 255;
         }
     }
     r_notexture = GL_LoadPic ("***r_notexture***", (byte *)data, 8, 8, it_wall, 32);
 }
Referenced by R_Init().
R_LightPoint()
void R_LightPoint (vec3_t p, vec3_t color)
Definition at line 226 of file r_light.c.
 {
     vec3_t      end;
     float       r;
     int         lnum;
     dlight_t    *dl;
     vec3_t      dist;
     float       add;
     if (!r_worldmodel->lightdata)
     {
         color[0] = color[1] = color[2] = 1.0;
         return;
     }
     end[0] = p[0];
     end[1] = p[1];
     end[2] = p[2] - 2048;
     r = RecursiveLightPoint(r_worldmodel->nodes, p, end);
     if (r == -1)
     {
         VectorCopy(vec3_origin, color);
     }
     else
     {
         VectorCopy(pointcolor, color);
     }
     //
     // add dynamic lights
     //
     for (lnum = 0; lnum<r_newrefdef.num_dlights; lnum++)
     {
         dl = &r_newrefdef.dlights[lnum];
         VectorSubtract(currententity->origin,
             dl->origin,
             dist);
         add = dl->intensity - VectorLength(dist);
         add *= (1.0 / 256);
         if (add > 0)
         {
             VectorMA(color, add, dl->color, color);
         }
     }
 }
R_MarkLeaves()
void R_MarkLeaves (void)
Definition at line 467 of file r_main.c.
 {
     byte    *vis;
     mnode_t *node;
     int     i;
     mleaf_t *leaf;
     int     cluster;
     if (r_oldviewcluster == r_viewcluster && !r_novis->value && r_viewcluster != -1)
         return;
     // development aid to let you run around and see exactly where
     // the pvs ends
     if (sw_lockpvs->value)
         return;
     r_visframecount++;
     r_oldviewcluster = r_viewcluster;
     if (r_novis->value || r_viewcluster == -1 || !r_worldmodel->vis)
     {
         // mark everything
         for (i = 0; i < r_worldmodel->numleafs; i++)
             r_worldmodel->leafs[i].visframe = r_visframecount;
         for (i = 0; i < r_worldmodel->numnodes; i++)
             r_worldmodel->nodes[i].visframe = r_visframecount;
         return;
     }
     vis = Mod_ClusterPVS(r_viewcluster, r_worldmodel);
     for (i = 0, leaf = r_worldmodel->leafs; i < r_worldmodel->numleafs; i++, leaf++)
     {
         cluster = leaf->cluster;
         if (cluster == -1)
             continue;
         if (vis[cluster >> 3] & (1 << (cluster & 7)))
         {
             node = (mnode_t *)leaf;
             do
             {
                 if (node->visframe == r_visframecount)
                     break;
                 node->visframe = r_visframecount;
                 node = node->parent;
             } while (node);
         }
     }
 #if 0
     for (i=0 ; i<r_worldmodel->vis->numclusters ; i++)
     {
         if (vis[i>>3] & (1<<(i&7)))
         {
             node = (mnode_t *)&r_worldmodel->leafs[i];  // FIXME: cluster
             do
             {
                 if (node->visframe == r_visframecount)
                     break;
                 node->visframe = r_visframecount;
                 node = node->parent;
             } while (node);
         }
     }
 #endif
 }
R_MarkLights()
void R_MarkLights (dlight_t * light, int bit, mnode_t * node)
Definition at line 40 of file r_light.c.
 {
     mplane_t    *splitplane;
     float       dist;
     msurface_t  *surf;
     int         i;
     if (node->contents != -1)
         return;
     splitplane = node->plane;
     dist = DotProduct(light->origin, splitplane->normal) - splitplane->dist;
     //=====
     //PGM
     i = light->intensity;
     if (i<0)
         i = -i;
     //PGM
     //=====
     if (dist > i)   // PGM (dist > light->intensity)
     {
         R_MarkLights(light, bit, node->children[0]);
         return;
     }
     if (dist < -i)  // PGM (dist < -light->intensity)
     {
         R_MarkLights(light, bit, node->children[1]);
         return;
     }
     // mark the polygons
     surf = r_worldmodel->surfaces + node->firstsurface;
     for (i = 0; i < node->numsurfaces; i++, surf++)
     {
         if (surf->dlightframe != r_dlightframecount)
         {
             surf->dlightbits = 0;
             surf->dlightframe = r_dlightframecount;
         }
         surf->dlightbits |= bit;
     }
     R_MarkLights(light, bit, node->children[0]);
     R_MarkLights(light, bit, node->children[1]);
 }
R_PushDlights()
void R_PushDlights (void)
Definition at line 164 of file gl_light.c.
 {
     int     i;
     dlight_t    *l;
     if (gl_flashblend->value)
         return;
     r_dlightframecount = r_framecount + 1;  // because the count hasn't
                                             //  advanced yet for this frame
     l = r_newrefdef.dlights;
     for (i=0 ; i<r_newrefdef.num_dlights ; i++, l++)
         R_MarkLights ( l, 1<<i, r_worldmodel->nodes );
 }
R_RegisterSkin()
struct image_s* R_RegisterSkin (char * name)
Definition at line 550 of file r_image.c.
 {
     return R_FindImage (name, it_skin);
 }
R_RenderBrushPoly()
void R_RenderBrushPoly (msurface_t * fa)
Definition at line 478 of file gl_rsurf.c.
 {
     int         maps;
     image_t     *image;
     qboolean is_dynamic = false;
     c_brush_polys++;
     image = R_TextureAnimation (fa->texinfo);
     if (fa->flags & SURF_DRAWTURB)
     {
         GL_Bind( image->texnum );
         // warp texture, no lightmaps
         GL_TexEnv( GL_MODULATE );
         qglColor4f( gl_state.inverse_intensity,
                     gl_state.inverse_intensity,
                     gl_state.inverse_intensity,
                     1.0F );
         EmitWaterPolys (fa);
         GL_TexEnv( GL_REPLACE );
         return;
     }
     else
     {
         GL_Bind( image->texnum );
         GL_TexEnv( GL_REPLACE );
     }
 //======
 //PGM
     if(fa->texinfo->flags & SURF_FLOWING)
         DrawGLFlowingPoly (fa);
     else
         DrawGLPoly (fa->polys);
 //PGM
 //======
     /*
     ** check for lightmap modification
     */
     for ( maps = 0; maps < MAXLIGHTMAPS && fa->styles[maps] != 255; maps++ )
     {
         if ( r_newrefdef.lightstyles[fa->styles[maps]].white != fa->cached_light[maps] )
             goto dynamic;
     }
     // dynamic this frame or dynamic previously
     if ( ( fa->dlightframe == r_framecount ) )
     {
 dynamic:
         if ( gl_dynamic->value )
         {
             if (!( fa->texinfo->flags & (SURF_SKY|SURF_TRANS33|SURF_TRANS66|SURF_WARP ) ) )
             {
                 is_dynamic = true;
             }
         }
     }
     if ( is_dynamic )
     {
         if ( ( fa->styles[maps] >= 32 || fa->styles[maps] == 0 ) && ( fa->dlightframe != r_framecount ) )
         {
             unsigned    temp[34*34];
             int         smax, tmax;
             smax = (fa->extents[0]>>4)+1;
             tmax = (fa->extents[1]>>4)+1;
             R_BuildLightMap( fa, (void *)temp, smax*4 );
             R_SetCacheState( fa );
             GL_Bind( gl_state.lightmap_textures + fa->lightmaptexturenum );
             qglTexSubImage2D( GL_TEXTURE_2D, 0,
                               fa->light_s, fa->light_t,
                               smax, tmax,
                               GL_LIGHTMAP_FORMAT,
                               GL_UNSIGNED_BYTE, temp );
             fa->lightmapchain = gl_lms.lightmap_surfaces[fa->lightmaptexturenum];
             gl_lms.lightmap_surfaces[fa->lightmaptexturenum] = fa;
         }
         else
         {
             fa->lightmapchain = gl_lms.lightmap_surfaces[0];
             gl_lms.lightmap_surfaces[0] = fa;
         }
     }
     else
     {
         fa->lightmapchain = gl_lms.lightmap_surfaces[fa->lightmaptexturenum];
         gl_lms.lightmap_surfaces[fa->lightmaptexturenum] = fa;
     }
 }
Referenced by DrawTextureChains(), and R_DrawInlineBModel().
R_RenderDlights()
void R_RenderDlights (void)
Definition at line 77 of file gl_light.c.
 {
     int     i;
     dlight_t    *l;
     if (!gl_flashblend->value)
         return;
     r_dlightframecount = r_framecount + 1;  // because the count hasn't
                                             //  advanced yet for this frame
     qglDepthMask (0);
     qglDisable (GL_TEXTURE_2D);
     qglShadeModel (GL_SMOOTH);
     qglEnable (GL_BLEND);
     qglBlendFunc (GL_ONE, GL_ONE);
     l = r_newrefdef.dlights;
     for (i=0 ; i<r_newrefdef.num_dlights ; i++, l++)
         R_RenderDlight (l);
     qglColor3f (1,1,1);
     qglDisable (GL_BLEND);
     qglEnable (GL_TEXTURE_2D);
     qglBlendFunc (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     qglDepthMask (1);
 }
R_RenderView()
void R_RenderView (refdef_t * fd)
Definition at line 818 of file gl_rmain.c.
 {
     if (r_norefresh->value)
         return;
     r_newrefdef = *fd;
     if (!r_worldmodel && !( r_newrefdef.rdflags & RDF_NOWORLDMODEL ) )
         ri.Sys_Error (ERR_DROP, "R_RenderView: NULL worldmodel");
     if (r_speeds->value)
     {
         c_brush_polys = 0;
         c_alias_polys = 0;
     }
     R_PushDlights ();
     if (gl_finish->value)
         qglFinish ();
     R_SetupFrame ();
     R_SetFrustum ();
     R_SetupGL ();
     R_MarkLeaves ();    // done here so we know if we're in water
     R_DrawWorld ();
     R_DrawEntitiesOnList ();
     R_RenderDlights ();
     R_DrawParticles ();
     R_DrawAlphaSurfaces ();
     R_Flash();
     if (r_speeds->value)
     {
         ri.Con_Printf (PRINT_ALL, "%4i wpoly %4i epoly %i tex %i lmaps\n",
             c_brush_polys,
             c_alias_polys,
             c_visible_textures,
             c_visible_lightmaps);
     }
 }
R_RotateForEntity()
void R_RotateForEntity (entity_t * e)
Definition at line 165 of file gl_rmain.c.
 {
     qglTranslatef (e->origin[0],  e->origin[1],  e->origin[2]);
     qglRotatef (e->angles[1],  0, 0, 1);
     qglRotatef (-e->angles[0],  0, 1, 0);
     qglRotatef (-e->angles[2],  1, 0, 0);
 }
Referenced by R_DrawAliasModel(), R_DrawBrushModel(), and R_DrawNullModel().
R_SetPalette()
void R_SetPalette (const unsigned char * palette)
Definition at line 1574 of file gl_rmain.c.
 {
     int     i;
     byte *rp = ( byte * ) r_rawpalette;
     if ( palette )
     {
         for ( i = 0; i < 256; i++ )
         {
             rp[i*4+0] = palette[i*3+0];
             rp[i*4+1] = palette[i*3+1];
             rp[i*4+2] = palette[i*3+2];
             rp[i*4+3] = 0xff;
         }
     }
     else
     {
         for ( i = 0; i < 256; i++ )
         {
             rp[i*4+0] = d_8to24table[i] & 0xff;
             rp[i*4+1] = ( d_8to24table[i] >> 8 ) & 0xff;
             rp[i*4+2] = ( d_8to24table[i] >> 16 ) & 0xff;
             rp[i*4+3] = 0xff;
         }
     }
     GL_SetTexturePalette( r_rawpalette );
     qglClearColor (0,0,0,0);
     qglClear (GL_COLOR_BUFFER_BIT);
     qglClearColor (1,0, 0.5 , 0.5);
 }
R_Shutdown()
void R_Shutdown (void)
Definition at line 375 of file r_main.c.
 {
     // free z buffer
     if (d_pzbuffer)
     {
         free(d_pzbuffer);
         d_pzbuffer = NULL;
     }
     // free surface cache
     if (sc_base)
     {
         D_FlushCaches();
         free(sc_base);
         sc_base = NULL;
     }
     if (r_warpbuffer)
     {
         free(r_warpbuffer);
         r_warpbuffer = NULL;
     }
     // free colormap
     if (vid.colormap)
     {
         free(vid.colormap);
         vid.colormap = NULL;
     }
     R_UnRegister();
     Mod_FreeAll();
     R_ShutdownImages();
     SWimp_Shutdown();
 }
R_SwapBuffers()
void R_SwapBuffers (int)
R_TranslatePlayerSkin()
void R_TranslatePlayerSkin (int playernum)
V_AddBlend()
void V_AddBlend (float r, float g, float b, float a, float * v_blend)
Referenced by R_RenderDlight().
WaterWarpPolyVerts()
glpoly_t* WaterWarpPolyVerts (glpoly_t * p)
Variable Documentation
c_alias_polys
int c_alias_polys
Definition at line 157 of file gl_local.h.
Referenced by R_DrawAliasModel().
c_brush_polys
int c_brush_polys
Definition at line 55 of file gl_rmain.c.
Referenced by GL_RenderLightmappedPoly(), R_DrawAlphaSurfaces(), R_RenderBrushPoly(), and Vk_RenderLightmappedPoly().
c_visible_lightmaps
int c_visible_lightmaps
Definition at line 40 of file gl_rsurf.c.
Referenced by R_RenderView().
c_visible_textures
int c_visible_textures
Definition at line 41 of file gl_rsurf.c.
Referenced by R_RenderView().
currententity
entity_t* currententity
Definition at line 28 of file r_bsp.c.
currentmodel
model_t* currentmodel
Definition at line 39 of file r_main.c.
d_8to24table
unsigned d_8to24table[256]
Definition at line 27 of file r_main.c.
frustum
cplane_t frustum[4]
Definition at line 50 of file gl_rmain.c.
Referenced by R_CullAliasModel().
gl_3dlabs_broken
cvar_t* gl_3dlabs_broken
Definition at line 138 of file gl_rmain.c.
Referenced by R_Init(), and R_Register().
gl_alpha_format
int gl_alpha_format
Definition at line 40 of file gl_image.c.
Referenced by GL_Upload32().
gl_bitdepth
cvar_t* gl_bitdepth
Definition at line 110 of file gl_rmain.c.
Referenced by GLimp_BeginFrame(), GLimp_SetMode(), R_Register(), and VID_CreateWindow().
gl_clear
cvar_t* gl_clear
Definition at line 126 of file gl_rmain.c.
Referenced by R_Clear(), and R_Register().
gl_config
glconfig_t gl_config
Definition at line 41 of file gl_rmain.c.
Referenced by Draw_Pic(), Draw_StretchPic(), Draw_StretchRaw(), Draw_TileClear(), GL_DrawStereoPattern(), GL_InitImages(), GL_Strings_f(), QGL_Init(), R_BeginFrame(), R_Init(), and R_SetMode().
gl_cull
cvar_t* gl_cull
Definition at line 127 of file gl_rmain.c.
Referenced by R_Register(), and R_SetupGL().
gl_drawbuffer
cvar_t* gl_drawbuffer
Definition at line 111 of file gl_rmain.c.
Referenced by GLimp_EndFrame(), R_BeginFrame(), and R_Register().
gl_driver
cvar_t* gl_driver
Definition at line 112 of file gl_rmain.c.
Referenced by R_Init(), and R_Register().
gl_dynamic
cvar_t* gl_dynamic
Definition at line 116 of file gl_rmain.c.
Referenced by GL_RenderLightmappedPoly(), R_BlendLightmaps(), R_Register(), and R_RenderBrushPoly().
gl_ext_compiled_vertex_array
cvar_t* gl_ext_compiled_vertex_array
Definition at line 107 of file gl_rmain.c.
Referenced by R_Register().
gl_ext_multitexture
cvar_t* gl_ext_multitexture
Definition at line 105 of file gl_rmain.c.
Referenced by R_Init(), and R_Register().
gl_ext_palettedtexture
cvar_t* gl_ext_palettedtexture
Definition at line 104 of file gl_rmain.c.
Referenced by R_Init(), and R_Register().
gl_ext_pointparameters
cvar_t* gl_ext_pointparameters
Definition at line 106 of file gl_rmain.c.
Referenced by R_DrawParticles(), R_Init(), and R_Register().
gl_ext_swapinterval
cvar_t* gl_ext_swapinterval
Definition at line 103 of file gl_rmain.c.
Referenced by R_Register().
gl_filter_max
int gl_filter_max
Definition at line 160 of file gl_local.h.
gl_filter_min
int gl_filter_min
Definition at line 45 of file gl_image.c.
Referenced by GL_SetDefaultState(), GL_TextureMode(), and GL_Upload32().
gl_finish
cvar_t* gl_finish
Definition at line 125 of file gl_rmain.c.
Referenced by R_Register(), and R_RenderView().
gl_flashblend
cvar_t* gl_flashblend
Definition at line 129 of file gl_rmain.c.
Referenced by R_DrawInlineBModel(), R_PushDlights(), R_Register(), and R_RenderDlights().
gl_lightmap
cvar_t* gl_lightmap
Definition at line 113 of file gl_rmain.c.
Referenced by R_BlendLightmaps(), R_DrawWorld(), and R_Register().
gl_lightmap_format
int gl_lightmap_format
gl_lightmaptype
cvar_t* gl_lightmaptype
gl_lockpvs
cvar_t* gl_lockpvs
Definition at line 136 of file gl_rmain.c.
Referenced by R_MarkLeaves(), and R_Register().
gl_log
cvar_t* gl_log
Definition at line 109 of file gl_rmain.c.
Referenced by R_BeginFrame(), and R_Register().
gl_mode
cvar_t* gl_mode
Definition at line 115 of file gl_rmain.c.
Referenced by R_BeginFrame(), R_Register(), and R_SetMode().
gl_modulate
cvar_t* gl_modulate
Definition at line 118 of file gl_rmain.c.
Referenced by R_BuildLightMap(), R_LightPoint(), R_Register(), and RecursiveLightPoint().
gl_monolightmap
cvar_t* gl_monolightmap
Definition at line 117 of file gl_rmain.c.
Referenced by GL_BeginBuildingLightmaps(), R_BlendLightmaps(), R_BuildLightMap(), R_DrawAliasModel(), R_Init(), and R_Register().
gl_nobind
cvar_t* gl_nobind
Definition at line 119 of file gl_rmain.c.
Referenced by GL_Bind(), and R_Register().
gl_nosubimage
cvar_t* gl_nosubimage
Definition at line 91 of file gl_rmain.c.
Referenced by R_Register().
gl_particle_att_a
cvar_t* gl_particle_att_a
Definition at line 99 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), and R_Register().
gl_particle_att_b
cvar_t* gl_particle_att_b
Definition at line 100 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), and R_Register().
gl_particle_att_c
cvar_t* gl_particle_att_c
Definition at line 101 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), and R_Register().
gl_particle_max_size
cvar_t* gl_particle_max_size
Definition at line 97 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), and R_Register().
gl_particle_min_size
cvar_t* gl_particle_min_size
Definition at line 96 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), and R_Register().
gl_particle_size
cvar_t* gl_particle_size
Definition at line 98 of file gl_rmain.c.
Referenced by R_DrawParticles(), and R_Register().
gl_picmip
cvar_t* gl_picmip
Definition at line 121 of file gl_rmain.c.
Referenced by R_Register().
gl_playermip
cvar_t* gl_playermip
Definition at line 130 of file gl_rmain.c.
Referenced by R_Register().
gl_poly
cvar_t* gl_poly
gl_polyblend
cvar_t* gl_polyblend
Definition at line 128 of file gl_rmain.c.
Referenced by R_PolyBlend(), and R_Register().
gl_round_down
cvar_t* gl_round_down
Definition at line 120 of file gl_rmain.c.
Referenced by GL_Upload32(), and R_Register().
gl_saturatelighting
cvar_t* gl_saturatelighting
Definition at line 131 of file gl_rmain.c.
Referenced by R_BlendLightmaps(), and R_Register().
gl_shadows
cvar_t* gl_shadows
Definition at line 114 of file gl_rmain.c.
Referenced by R_DrawAliasModel(), and R_Register().
gl_showtris
cvar_t* gl_showtris
Definition at line 123 of file gl_rmain.c.
Referenced by R_DrawTriangleOutlines(), and R_Register().
gl_skymip
cvar_t* gl_skymip
Definition at line 122 of file gl_rmain.c.
Referenced by R_Register(), and R_SetSky().
gl_solid_format
int gl_solid_format
Definition at line 39 of file gl_image.c.
Referenced by GL_Upload32().
gl_state
glstate_t gl_state
Definition at line 42 of file gl_rmain.c.
Referenced by GL_BeginBuildingLightmaps(), GL_Bind(), GL_BuildPalettedTexture(), GL_DrawStereoPattern(), GL_InitImages(), GL_MBind(), GL_RenderLightmappedPoly(), GL_SelectTexture(), GL_TexEnv(), GL_UpdateSwapInterval(), GLimp_BeginFrame(), GLimp_InitGL(), GLimp_SetMode(), GLimp_Shutdown(), LM_UploadBlock(), MYgluPerspective(), R_BeginFrame(), R_BlendLightmaps(), R_DrawAlphaSurfaces(), R_DrawBrushModel(), R_DrawWorld(), R_Init(), R_RenderBrushPoly(), and R_SetMode().
gl_swapinterval
cvar_t* gl_swapinterval
Definition at line 132 of file gl_rmain.c.
Referenced by GL_UpdateSwapInterval(), and R_Register().
gl_tex_alpha_format
int gl_tex_alpha_format
Definition at line 43 of file gl_image.c.
Referenced by GL_BeginBuildingLightmaps(), GL_TextureAlphaMode(), and GL_Upload32().
gl_tex_solid_format
int gl_tex_solid_format
Definition at line 42 of file gl_image.c.
Referenced by Draw_StretchRaw(), GL_BeginBuildingLightmaps(), GL_TextureSolidMode(), and GL_Upload32().
gl_texsort
cvar_t* gl_texsort
gl_texturealphamode
cvar_t* gl_texturealphamode
Definition at line 134 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), R_BeginFrame(), and R_Register().
gl_texturemode
cvar_t* gl_texturemode
Definition at line 133 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), R_BeginFrame(), and R_Register().
gl_texturesolidmode
cvar_t* gl_texturesolidmode
Definition at line 135 of file gl_rmain.c.
Referenced by GL_SetDefaultState(), R_BeginFrame(), and R_Register().
gl_vertex_arrays
cvar_t* gl_vertex_arrays
Definition at line 94 of file gl_rmain.c.
Referenced by GL_DrawAliasFrameLerp(), and R_Register().
gl_ztrick
cvar_t* gl_ztrick
Definition at line 124 of file gl_rmain.c.
Referenced by R_Clear(), and R_Register().
gldepthmax
float gldepthmax
Definition at line 129 of file gl_local.h.
Referenced by R_DrawAliasModel().
gldepthmin
float gldepthmin
Definition at line 39 of file gl_rmain.c.
Referenced by R_Clear(), and R_DrawAliasModel().
gltextures
image_t gltextures[MAX_GLTEXTURES]
Definition at line 24 of file gl_image.c.
Referenced by DrawTextureChains(), GL_FindImage(), GL_FreeUnusedImages(), GL_ImageList_f(), GL_LoadPic(), GL_ShutdownImages(), and GL_TextureMode().
intensity
cvar_t* intensity
Definition at line 31 of file gl_image.c.
numgltextures
int numgltextures
Definition at line 25 of file gl_image.c.
Referenced by DrawTextureChains(), GL_FindImage(), GL_FreeUnusedImages(), GL_ImageList_f(), GL_LoadPic(), GL_ShutdownImages(), and GL_TextureMode().
r_drawentities
cvar_t* r_drawentities
Definition at line 135 of file r_main.c.
r_drawworld
cvar_t* r_drawworld
Definition at line 134 of file r_main.c.
r_framecount
int r_framecount
Definition at line 97 of file r_main.c.
r_fullbright
cvar_t* r_fullbright
Definition at line 137 of file r_main.c.
r_lefthand
cvar_t* r_lefthand
Definition at line 117 of file r_main.c.
r_lerpmodels
cvar_t* r_lerpmodels
Definition at line 138 of file r_main.c.
r_lightlevel
cvar_t* r_lightlevel
Definition at line 142 of file r_main.c.
r_newrefdef
refdef_t r_newrefdef
Definition at line 38 of file r_main.c.
r_nocull
cvar_t* r_nocull
Definition at line 85 of file gl_rmain.c.
r_norefresh
cvar_t* r_norefresh
Definition at line 79 of file gl_rmain.c.
r_notexture
image_t* r_notexture
Definition at line 44 of file gl_rmain.c.
Referenced by GL_FreeUnusedImages(), GL_LoadWal(), Mod_LoadTexinfo(), R_DrawAliasModel(), R_InitParticleTexture(), R_SetSky(), Vk_FreeUnusedImages(), and Vk_LoadWal().
r_novis
cvar_t* r_novis
Definition at line 139 of file r_main.c.
r_oldviewcluster
int r_oldviewcluster
Definition at line 174 of file gl_local.h.
r_oldviewcluster2
int r_oldviewcluster2
Definition at line 174 of file gl_local.h.
Referenced by R_MarkLeaves().
r_origin
vec3_t r_origin
Definition at line 75 of file r_main.c.
r_particletexture
image_t* r_particletexture
Definition at line 45 of file gl_rmain.c.
Referenced by GL_FreeUnusedImages(), R_InitParticleTexture(), and Vk_FreeUnusedImages().
r_speeds
cvar_t* r_speeds
Definition at line 141 of file r_main.c.
r_viewcluster
int r_viewcluster
Definition at line 108 of file r_main.c.
r_viewcluster2
int r_viewcluster2
Definition at line 174 of file gl_local.h.
Referenced by R_MarkLeaves().
r_visframecount
int r_visframecount
Definition at line 98 of file r_main.c.
r_world_matrix
float r_world_matrix[16]
Definition at line 69 of file gl_rmain.c.
Referenced by R_DrawAlphaSurfaces(), and R_SetupGL().
r_worldmodel
model_t* r_worldmodel
Definition at line 41 of file r_main.c.
registration_sequence
int registration_sequence
Definition at line 44 of file r_model.c.
ri
refimport_t ri
Definition at line 25 of file r_main.c.
vid
viddef_t vid
Definition at line 24 of file r_main.c.
vid_fullscreen
cvar_t* vid_fullscreen
Definition at line 47 of file vid_dll.c.
vid_gamma
cvar_t* vid_gamma
Definition at line 43 of file vid_dll.c.
vpn
vec3_t vpn
Definition at line 73 of file r_main.c.
vright
vec3_t vright
Definition at line 74 of file r_main.c.
vup
vec3_t vup
Definition at line 72 of file r_main.c.